
%%XXDIR = { "WIN32" : "N:\\m3-tools", "POSIX" : "/proj/cmass/src.2/m3-tools" }
%%WORKDIR = XXDIR {OS_TYPE}

%override ("libm3", ROOT & "/m3-libs")
%override ("m3tk", ROOT & "/m3-tools")
/* $Id$ */
include("../../../m3overrides")
