% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Fri Jan 14 09:31:40 PST 1994 by kalsow
%      modified on Fri Jan 15 14:40:34 PST 1993 by jdd
%      modified on Tue Jun 16 19:06:34 PDT 1992 by muller

import ("vbtkit")
implementation ("ShowHeap")
build_standalone()
Program ("showheap")

ManPage ("showheap","1")
