
MYROOT=ROOT & "/ESC/Simplify"

override("cgi-utils", MYROOT )
override("prover", MYROOT )

override("ui",ROOT & "/m3-ui")
override("X11R4",ROOT & "/m3-ui")
override("mtex",ROOT & "/m3-tools")








