/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Thu May 18 20:05:48 PDT 1995 by najork                   */

if equal (TARGET, "NT386")
  override ("formsvbt", "..\\..")
end

import		("formsvbt")
resource	("Juno2Logo.ppm")
resource	("Test25.fv")
bundle		("TestBundle")
implementation	("Test25")
Program	        ("Test25") 
