% Copyright 1994 Digital Equipment Corporation.
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Aug 19 22:14:35 PDT 1996 by mhb      
%      modified on Fri Sep  8 14:44:53 PDT 1995 by najork   
%      modified on Wed Aug 24 22:09:20 PDT 1994 by shillner 


import		("parseparams")
import		("formsvbt")
import 		("web")
import 		("webvbt")

include_dir	("resources")
bundle		("MyBundle")

module		("WSObjectVBT")
module		("DocVBT")
module		("FreeDocVBT")
module		("DeckVBT")
module		("WorkspaceVBT")
module		("Storage")
interface	("Options")
implementation	("Main")

ManPage		("DeckScape","1")
Program		("DeckScape")

