% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Nov 21 08:29:28 PST 1994 by kalsow 

implementation ("RTArgs")
implementation ("RTOS")
module         ("RTPerfTool")
c_source       ("RTOSc")
interface      ("RTSignalPrivate")
c_source       ("RTSignalC")
interface      ("RTSignalC")
implementation ("RTSignal")
