% Copyright 1996-2000, Critical Mass, Inc.  All rights reserved.
% See file COPYRIGHT-CMASS for details.

if defined("configure_system_libs")
  configure_system_libs()
end

if SYSTEM_LIBS contains "ODBC"
    import("libm3")
    import_sys_lib ("ODBC")
    include_dir ("WIN32") % correct for POSIX too
    Library("m3odbc")
end
