% Copyright 1996-2000, Critical Mass, Inc.  All rights reserved.
% See file COPYRIGHT-CMASS for details.

if defined("configure_system_libs")
  configure_system_libs()
end

if SYSTEM_LIBS contains "ODBC"
    import("libm3")
    import_sys_lib ("ODBC")

% The head compiler will compile files SQL.i3, SQLext.[im]3 in the WIN32
% subdirectory, for any platform.  The release 5.8 compiler will not.  
% Keep the distinct versions until a new release is made.  
    if equal (TARGET, "NT386")
        include_dir ("WIN32")
    else
        include_dir (OS_TYPE)
    end

    Library("m3odbc")
end
