/* Copyright 1994 Digital Equipment Corporation. */
/* Distributed only by permission. */
/* Makefile for network object daemon */
/* Last modified on Thu Mar 24 11:38:15 PST 1994 by wobber     */
/*      modified on Mon Sep 14 11:35:01 PDT 1992 by evers      */


import("netobj")
import("tcp")

export_interface("NetObjMon")
export_interface("NGCMonitor")
export_interface("WireRep")
export_interface("Transport")
export_interface("DirtyElem")
export_interface("SpaceID")

build_standalone()
module ("NMonRegistrySvr")
implementation ("NetObjDaemon")

ManPage("netobjd","1")

Program("netobjd")
