%remove_m3_option("-map")
%remove_m3_option("-g")

import("libm3")


Module("ExtendedType")

readonly proc FloatBasic (nm, mod, modt) is
  local basic = nm & "Basic"
  build_generic_intf (basic, "FloatBasic", [mod, modt], VISIBLE)
  build_generic_impl (basic, "FloatBasic", [])
end

generic_module("FloatBasic")
FloatBasic("Real",     "Real",     "RealType")
FloatBasic("LongReal", "LongReal", "LongrealType")
FloatBasic("Extended", "Extended", "ExtendedType")

readonly proc FloatTrans (nm, mod) is
  local trans = nm & "Trans"
  build_generic_intf (trans, "FloatTrans", [mod], VISIBLE)
  build_generic_impl (trans, "FloatTrans", [])
end

generic_module("FloatTrans")
FloatTrans("Real",     "Real")
FloatTrans("LongReal", "LongReal")
FloatTrans("Extended", "Extended")


readonly proc ComplexBasic (nm, mod) is
  local basic = nm & "ComplexBasic"
  build_generic_intf (basic, "ComplexBasic", [mod], VISIBLE)
  build_generic_impl (basic, "ComplexBasic", [mod])
end

generic_module("ComplexBasic")
ComplexBasic("Real",     "RealBasic")
ComplexBasic("LongReal", "LongRealBasic")
ComplexBasic("Extended", "ExtendedBasic")


readonly proc ComplexFast (nm, elt) is
  local basic = nm & "ComplexFast"
  build_generic_intf (basic, "ComplexFast", [elt], VISIBLE)
  build_generic_impl (basic, "ComplexFast", [elt])
end

generic_module("ComplexFast")
ComplexFast("Real",     "Real")
ComplexFast("LongReal", "LongReal")
ComplexFast("Extended", "Extended")



module("xUtils")
export_interface("xUtils")

module("xWordEx")
export_interface("xWordEx")

module("xBits")
export_interface("xBits")

module("xInteger")
implementation("xPrime")
export_interface("xInteger")

module("xReal32")
export_interface("xReal32")

module("xReal64")
implementation("xSpecFtn")
export_interface("xReal64")

module("xComplex")
export_interface("xComplex")

module("xPoly")
export_interface("xPoly")

module("xVect")
export_interface("xVect")

module("xMat")
export_interface("xMat")

module("xRoot")
export_interface("xRoot")

module("xInterp")
export_interface("xInterp")

module("xSLE")
export_interface("xSLE")

module("xRand")
interface("xRandP")
export_interface("xRand")

module("xRNG01")
export_interface("xRNG01")

module("xRNG02")
export_interface("xRNG02")

module("xStat")
export_interface("xStat")

%module("xInteg")
%export_interface("xInteg")

%module("xCheby")
%export_interface("xCheby")

module("xFFT")
export_interface("xFFT")

%module("xStat")
%export_interface("xStat")

library("m3na")
