import("libm3")

include_dir("lowlevel")

include_dir("integer")
include_dir("biginteger")
include_dir("fraction")

include_dir("float")
include_dir("complex")
include_dir("polar")
include_dir("physicalunit")

include_dir("vector")
include_dir("matrix")
include_dir("fourier")

include_dir("polynomial")
include_dir("chebyshev")
include_dir("root")
include_dir("algebra")

include_dir("nonlinear")
include_dir("stochastic")

module("NADefinitions")

% if the statement is given twice, no quake error is thrown
% but the .M3EXPORT file remain incomplete and thus modules
% will not be found, if importing this library somewhere
library("m3na")
