%remove_m3_option("-map")
%remove_m3_option("-g")

import("libm3")


include_dir("integer")
include_dir("biginteger")
include_dir("fraction")

include_dir("float")
include_dir("complex")
include_dir("polar")

include_dir("vector")
include_dir("matrix")
include_dir("fourier")

include_dir("polynomial")
include_dir("root")
include_dir("algebra")

include_dir("nonlinear")


module("xUtils")
export_interface("xUtils")

module("xWordEx")
export_interface("xWordEx")

module("xBits")
export_interface("xBits")

module("xInteger")
implementation("xPrime")
export_interface("xInteger")

module("xReal32")
export_interface("xReal32")

module("xReal64")
implementation("xSpecFtn")
export_interface("xReal64")

module("xComplex")
export_interface("xComplex")

module("xPoly")
export_interface("xPoly")

module("xVect")
export_interface("xVect")

module("xMat")
export_interface("xMat")

module("xRoot")
export_interface("xRoot")

module("xInterp")
export_interface("xInterp")

module("xSLE")
export_interface("xSLE")

% xRandP cannot be found, when the package is imported for testing
module("xRand")
interface("xRandP")
export_interface("xRand")

module("xRNG01")
export_interface("xRNG01")

module("xRNG02")
export_interface("xRNG02")

module("xStat")
export_interface("xStat")

%module("xInteg")
%export_interface("xInteg")

%module("xCheby")
%export_interface("xCheby")

module("xFFT")
export_interface("xFFT")

%module("xStat")
%export_interface("xStat")

% this is also given in the m3makefile in the directory above
% if the statement is given twice, no quake error is thrown
% but the .M3EXPORT file remain incomplete and thus modules
% will not be found, if importing this library somewhere
%library("m3na")
