/* Copyright (C) 1993, Digital Equipment Corporation                         */

/* All rights reserved.                                                      */

/* See the file COPYRIGHT for a full description.                            */



/* Last modified on Fri Oct 22 14:56:19 PDT 1993 by mhb    */



resource ("Grid")

resource ("minusOff")

resource ("plusOff")

resource ("IvyScrollH")

resource ("IvyScrollV")

resource ("NEDiagonal")

resource ("NWDiagonal")

resource ("checkMarkOff")

resource ("checkMarkOffExcited")

resource ("checkMarkOn")

resource ("checkMarkOnExcited")

resource ("checkOff")

resource ("checkOffExcited")

resource ("checkOn")

resource ("checkOnExcited")

resource ("radioOff")

resource ("radioOffExcited")

resource ("radioOn")

resource ("radioOnExcited")

resource ("Close.pbm")

resource ("Digital.pbm")

resource ("Grow.pbm")

if equal (OS_TYPE, "WIN32")
   resource ("ScrollBg")
   resource ("up.ppm")
   resource ("down.ppm")
   resource ("right.ppm")
   resource ("left.ppm")
   resource ("grow.ppm")
   resource ("close.ppm")
end

bundle ("VBTKitBundle")

