
%% M3_FRONT_FLAGS += "-vsdebug"

%% override ("libm3", "N:\\m3-libs")
%override ("ui", "N:\\m3-ui")
%override ("vbtkit", "N:\\m3-ui")

override ("libm3", ROOT & "/m3-libs")
override ("ui", ROOT & "/m3-ui")
override ("vbtkit", ROOT & "/m3-ui")
override ("formsvbt", ROOT & "/m3-ui")

build_standalone ()
