
import("libm3")
import("sysutils")
import("pkgversions")

resource("compact-copyrights.txt")
bundle("CopyrightBundle")

Module("Copyright")
%Module("ProgramVersion")
Module("Release")

Library("compact-copyright")

