% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Fri Jul 30 09:36:51 PDT 1993 by kalsow
%      modified on Fri May  7 14:52:56 PDT 1993 by muller

Module ("FloatMode")

interface("FloatModeC")
c_source("FloatModeC")
