% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Fri Feb 18 14:11:06 PST 1994 by kalsow
%      modified on Mon Oct 12 14:02:53 PDT 1992 by muller

c_source ("dtoa")
c_source ("getdtablesize")
c_source ("utimes")
