% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Feb 23 14:05:15 PST 1995 by kalsow
%      modified on Fri Jun 26 16:10:14 PDT 1992 by muller
%      modified on Thu Mar  5 13:51:55 PST 1992 by meehan
%      modified on Thu Jul 25 21:30:24 PDT 1991 by stolfi
%      modified on Mon Jul  1 14:19:31 PDT 1991 by mhb

%
%  To rebuild the parser or lexer tables, cd to the src/lex-yacc
%  or src/flex-bison directory and run the standard make.
%

if defined("configure_system_libs")
  configure_system_libs()
end

if SYSTEM_LIBS contains "LEX-YACC" or SYSTEM_LIBS contains "FLEX-BISON"

import ("vbtkit")

include_dir("afm")
bundle("AFMBundle")

if defined("configure_system_libs")
  configure_system_libs()
end 

if SYSTEM_LIBS contains "FLEX-BISON"
  include_dir ("flex-bison")
else if SYSTEM_LIBS contains "LEX-YACC"
  if equal (TARGET, "HPPA")
    include_dir ("lex-yacc-HPPA")
  else
    include_dir ("lex-yacc")
  end
else
  error ("Unable to build the pretty printer without Lex&Yacc or Flex&Bison libraries.")
end end

% source   ("Parse.lex")
% source   ("Parse.yacc")

h_source ("hash")
h_source ("lex_help")

interface      ("ExceptionArg")
interface      ("FBE")
module         ("FBEPostScript")
module         ("FBEWr")
module         ("Parse")
module         ("NewFormatter")
implementation ("Main")

generate_tfile()
Program ("m3pp")
ManPage ("m3pp",1)

end
