% Copyright (C) 1994, Digital Equipment Corporation.
% All rights reserved.
% See the file COPYRIGHT for a full description.
 
interface ("FloatTest")
interface ("LongTest")
implementation ("FloatTest")
implementation ("LongTest")
implementation ("Main")
