% Copyright (C) 1994, Digital Equipment Corporation.
% All rights reserved.
% See the file COPYRIGHT for a full description.
 
interface ("BuffOWr")
interface ("BuffOWrDotT")
interface ("OWr")
implementation ("BuffOWr")
implementation ("OWr")
