if not equal (OS_TYPE, "WIN32")

import("parseparams")
import("libm3")
import("cit_util")

%template("listf")
%generic_module("ListF")

%table("TextTextList", "Text", "TextList")
Module("CharRange")
Module("CharCodes")
Module("Import")
Module("TokSpec")
Module("TokParams")
%Module("FileReWr")
Module("FileRdErr")
Module("BracedCode")

%Module("IntInt")
%Array_sort("IntInt", "IntInt")

/* moved to cit_util
module("TextSubsClause")
list("TextSubsClause", "TextSubsClause")
table("TextSubsClauseList", "Char", "TextSubsClauseList")
Module("TextSubs")
*/

Module("FmtTable")

Interface("Pragma")
table("Pragma", "Text", "Pragma")
Module("PragmaRead")

Library("ktoklib")

end
