/* $Id: m3makefile,v 1.5 2009-07-29 17:54:16 jkrell Exp $ */
%m3_option("-X2@-pg@")
%m3_option("-g")
%remove_m3_option("-O")
m3_option("-times")
import ("libm3")
Module("TextReader") % needed by m3tmplhack, must be compiled before cit_util

Library("cit_common")
