/* $Id: m3overrides,v 1.2 2001-09-19 13:27:07 wagner Exp $ */
libm3 = ROOT & "/m3-libs/libm3"
m3core = ROOT & "/m3-libs/m3core"
if not stale(m3core, m3core)
  override("m3core", ROOT & "/m3-libs")
end
if not stale(libm3, libm3)
  override("libm3", ROOT & "/m3-libs")
end

