% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Mar 20 18:54:08 PST 1995 by najork
%      modified on Tue Dec 21 14:41:55 PST 1993 by kalsow
%

if HasTrestle()

import ("ui")
implementation ("Main")
Program ("Cards")

end
