
import ("libm3")
import ("patternmatching")
import ("parseparams")
interface ("regex")
implementation ("regex")
%c_source ("regex")

implementation("Main")
program ("test-regex")

if defined("RUN")
  r = q_exec( "." & SL & "test-regex -unix < .." & SL & "tests.input" )
  write( CR, "program returned ", r, CR )
  r = q_exec( "." & SL & "test-regex -unix < .." & SL & "testsdiffer.input" )
  write( CR, "program returned ", r, CR )
end
