
import ("libm3")
import ("patternmatching")
import ("parseparams")
interface ("regex")
c_source ("regex")

if equal(TARGET, "FreeBSD3") or
   equal(TARGET, "FreeBSD4") or
   equal(TARGET, "FreeBSD5")
  import_lib("compat", "/usr/lib")
end

implementation("Main")
program ("test-regex")

if defined("RUN")
  r = q_exec( "." & SL & "test-regex -unix < .." & SL & "tests.input" )
  write( CR, "program returned ", r, CR )
  r = q_exec( "." & SL & "test-regex -unix < .." & SL & "testsdiffer.input" )
  write( CR, "program returned ", r, CR )
end
