(* open arrays *)

MODULE Main;

PROCEDURE F2(b: ARRAY OF INTEGER) = BEGIN END F2;
PROCEDURE F3(VAR b: ARRAY OF INTEGER) = BEGIN END F3;
PROCEDURE F4(b: REF ARRAY OF INTEGER): REF ARRAY OF INTEGER = BEGIN RETURN b; END F4;

PROCEDURE F5() = BEGIN
  EVAL NEW(REF ARRAY OF INTEGER, 1);
END F5;

PROCEDURE F6() = BEGIN
  EVAL NEW(REF ARRAY OF ARRAY OF INTEGER, 1, 2);
END F6;

PROCEDURE F7() =
VAR a := NEW(REF ARRAY OF INTEGER, 10);
BEGIN
    SUBARRAY(a^, 0, 4) := SUBARRAY(a^, 1, 5);
END F7;

PROCEDURE F1(): REF ARRAY OF INTEGER =
VAR a := NEW(REF ARRAY OF INTEGER, 10);
BEGIN
    F2(a^);
    F3(a^);
    SUBARRAY(a^, 0, 4) := SUBARRAY(a^, 0, 4);
    RETURN F4(a);
END F1;

BEGIN
  F5();
  F6();
  (*F7(); bug *)
  EVAL F4(F1());
END Main.
