% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Mar 21 23:10:22 PST 1994 by luca
%      modified on Wed Dec 22 14:36:40 PST 1993 by kalsow

import("libm3")

Module("SynWr")
Module("SynLocation")

Library("synwr")
