% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Makefile for netobj test program
% Last modified on Thu Mar 24 10:20:30 PST 1994 by wobber
%      modified on Mon Dec 20 14:14:37 PST 1993 by kalsow

if defined("AT_SRC") if AT_SRC m3_option("-O") end end 

import("libm3")
import("netobj")
import("tcp")

interface("Test")
implementation("FDTest")
netobj("Test", "T")

build_standalone()

program("test")


