% Copyright (C) 1995, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%

if HasTrestle()

import ("ui")
import ("netobj")
%override ("board", "/udir/umesh/m3/board/3")
import ("board")

sequence ("Item", "Item")

implementation ("Calendar")
program ("calendar")

end
