% Copyright (C) 1994, Digital Equipment Corporation.
% All rights reserved.
% See the file COPYRIGHT for a full description.

import("libm3")

implementation ("Main")
build_standalone()
Program("pgm")

write(fs_contents(".M3SHIP"))
