if equal (OS_TYPE, "WIN32")
  override("obliqrt", "\\\\stieglitz\\graphics\\arm3\\bm-work\\cm3\\m3-obliq")
  override("obliqlibui", "\\\\stieglitz\\graphics\\arm3\\bm-work\\cm3\\m3-obliq")
else
  override("obliqrt", "/proj/graphics/arm3/bm-work/cm3/m3-obliq")
  override("obliqlibui", "/proj/graphics/arm3/bm-work/cm3/m3-obliq")
end
