% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Fri Jan 14 10:09:34 PST 1994 by kalsow
%      modified on Mon Mar 16 13:26:54 PST 1992 by muller

BinExport ("recordheap")
ManPage ("recordheap",1)
