.\" Copyright (C) 1989, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.nh
.TH RECORDHEAP 1
.SH NAME
recordheap \- record the traced heap activity of a Modula-3 program

.SH DESCRIPTION

.B recordheap
records the activity of the traced heap of a Modula-3
program in the file
.BR m3heap.trace .
To use it, pass the option @M3showheap=recordheap to the Modula-3
program of interest.

.SH SEE ALSO
showheap(1) replayheap(1)

.SH AUTHOR OF OBJECT
Eric Muller

.SH AUTHOR OF DOCUMENTATION
Eric Muller
