/* Copyright 1993 Digital Equipment Corporation.                             */
/* Distributed only by permission.                                           */
/*                                                                           */
/* Last modified on Thu Sep  8 22:34:35 PDT 1994 by heydon                   */

import (libm3)
implementation (HeapSort)

program(HeapSort)
