/* Copyright 1993 Digital Equipment Corporation.                             */
/* Distributed only by permission.                                           */
/*                                                                           */
/* Last modified on Thu Sep  8 22:34:35 PDT 1994 by heydon                   */

include( ".." & SL & ".." & SL & ".." & SL & "src" & SL & "defs.quake" )

src = ".." & SL & "src"

import("libm3")
implementation("HeapSort")

program("HeapSort")

if defined("RUN")

  tid = "pqueue-heapsort2"
  write( CR, "performing " & tid & "...", CR )
  r = q_exec( "." & SL & "HeapSort" )
  write( CR, "program returned ", r, CR )

end
