% Copyright (C) 1996, Roumen Roupski Corporation
% All rights reserved.
%
% File: m3makefile
% Last modified on Mon 6/17/96 7:48PM by R. Roupski
%
% This make file creates a static library RTMain.

%M3_MAIN_IN_C = TRUE

build_standalone()

import ("m3core")
import ("libm3")

module("RTMain")
Library("RTMain")
