/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Tue Feb 11 15:10:13 PST 1992 by muller                   */

implementation ("RandomReal")
