% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Mar 21 23:12:27 PST 1994 by luca  
%      modified on Wed Dec 22 15:10:58 PST 1993 by kalsow

import("synloc")
import("obliqrt")

Module ("ObLibM3")

Library("obliqlibm3")

/* ManPage(obliqlibm3,?) */


