% Copyright (C) 1993 Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Sep 20 12:30:39 PDT 1993 by kalsow 
%      modified on Tue Aug 17 12:00:33 PDT 1993 by mcjones

Module ("WeakRef")
