% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Tue Oct 12 09:52:36 PDT 1993 by kalsow
%      modified on Tue Feb 11 15:18:41 PST 1992 by muller

c_source ("dtoa")
h_source ("float")
c_source ("memmove")


