% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%

Interface      ("RTMachine")
implementation ("RTSignal")
implementation ("RTThread")
c_source       ("RTThreadC")
