% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Makefile for netobj long call test program
% Last modified on Mon Dec 20 14:15:15 PST 1993 by kalsow
%      modified on Wed Aug 25 17:44:44 PDT 1993 by wobber

import("netobj")
import("tcp")
import("libm3")

interface("LongCall")
implementation("LongCallTest")
netobj("LongCall", "T")

program("longcall")


