
write("Virtual memory protection and system call wrappers needed for")
write("enhanced garbage collection are currently not supported on this")
write("target platform. Use package m3gc-simple instead or implement")
write("the missing support functions.")

c_source("nonexistant")

