/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Thu Jun 26 11:25:27 PDT 1997 by heydon                   */

/* m3makefile for /proj/m3/pkg/juno-compiler/tests/compiler/src */

import		("libm3")
import		("juno-machine")
import		("juno-compiler")

export_interface("JunoAssemble")
export_interface("JunoCompileRep")
export_interface("JunoParse")
export_interface("JunoLex")
export_interface("JunoToken")

module		("BackPtr")
implementation	("CompilerTest")

build_standalone()
program		("CompilerTest")
