#! /bin/csh -f
#
# Copyright (C) 1992, Digital Equipment Corporation 
# All rights reserved.
# See the file COPYRIGHT for a full description.
#
# Last modified on Thu Jun  9 09:03:59 PDT 1994 by heydon

set arch = `/udir/heydon/libi/csh/m3arch`
set prog = CompilerTest

if (-e ../$arch/$prog) then
  set newoutfile = /tmp/compilertes-$$.txt.out
  foreach outfile ($*)
    set infile = "$outfile:r".in
    echo ../$arch/$prog -disassem $infile '>' $newoutfile
    ../$arch/$prog -disassem $infile > $newoutfile
    echo "diff $outfile $newoutfile"
    diff $outfile $newoutfile
    rm $newoutfile
  end
else
  echo "Unknown host type \"$arch\""
endif
