% Copyright according to COPYRIGHT-CMASS.

Interface      ("RTMachine")
implementation ("RTHeapDep")
implementation ("RTSignal")
implementation ("RTThread")
c_source       ("RTThreadC")
s_source       ("_fpsetjmp")
c_source       ("malloc")


