/* Copyright (C) 1993, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Wed May 29 13:52:36 PDT 1996 by mcjones */

import("libm3")
import("mtex")

include_dir(OS_TYPE)

Interface("LecternClient")
Interface("LecternServer")


Library("lecternserver")
Mtex("LecternClient", 1) /* manpage */


