% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Wed Apr 28 21:32:00 PDT 1993 by mjordan
%      modified on Thu Jan 21 17:04:32 1993 by birrell
%      modified on Fri Sep 11 16:11:59 PDT 1992 by evers

Module("Pickle")
module("BuiltinSpecials")
