MODULE Main;
IMPORT IO;

<*UNUSED*> VAR a : ARRAY [0..0] OF CHAR := ARRAY OF CHAR {'a'};
<*UNUSED*> VAR b : ARRAY [0..0] OF CHAR := ARRAY OF CHAR {'b'};
<*UNUSED*> VAR c : ARRAY [0..0] OF CHAR := ARRAY OF CHAR {'c'};
<*UNUSED*> VAR d : ARRAY [0..0] OF CHAR := ARRAY OF CHAR {'d'};

BEGIN
  IO.Put("OK\n");
END Main.
