/* $Id: m3makefile,v 1.1.1.1 2001-09-19 11:40:10 wagner Exp $ */
import("cit_common")
template("generics")
Interface("DblRefany")
Module("Debug")
Module("TextUtils")
implementation("TextUtilsFmt")

Generic_module("OpenArrayTable")
template("dbltable")
Generic_module("DblTable")

Generic_module("BrandedSet")
template("brandedset")
Module("RTBrand")

Module("SIsuffix")
table("Suffix", "Char", "SIsuffix")

Generic_module("KeyPair")
template("keypair")
KeyPair("Int", "Integer", "Integer")
List("IntPair", "IntPair")

gmodule("Ref")
gmodule("ArrayRef")
ArrayRef("Int", "Integer")

Module("ToRefany")
Gmodule("ToRefany")
Interface("ToRefanyClass")
table("ToRefany","Integer","ToRefanyClass")

/* this is a dumb hack.  to ensure that initialization code gets run,
   you MUST import xToRefany in ToRefanyPrivate (or in some other 
   module that does get run). */

implementation("ToRefanyPrivate")
template("to_refany")
ord_to_refany("Int", "Integer")
ord_to_refany("Bool", "Boolean")
ord_to_refany("Char", "Char")
ord_to_refany("Real", "RealType")
ord_to_refany("Longreal", "LongrealType")

/* new stuff */
MkSet("IntPair", "IntPair")
MkSetDef("IntPair", "IntPair")
Table("IntPairRef", "IntPair", "Refany")

/* used to be in ktoklib */
Module("TextSubs")

Gmodule("Equivalence")
Equivalence("Text", "Text", "TextTextTbl")
Module("TextTextTblExtras")

Library("cit_util")



