if not equal (OS_TYPE, "WIN32")

import("cit_util")
import("parserlib")

token("Calc")
lexer("Calc", "Calc")
parser("Calc", "Calc")
extended("CalcTokStd")
extended("CalcLexStd")
extended("CalcParseStd")
extended("CalcParseTree")

implementation("Main")
program("test")

end
