% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Jul 17 14:28:15 PDT 1996 by heydon 
%      modified on Mon Mar 21 23:12:55 PST 1994 by luca  
%      modified on Wed Dec 22 15:02:37 PST 1993 by kalsow

import ("synex")
import ("metasyn")
import ("obliqrt")

Module ("ObFrame")
Module ("ObParseFrame")
Module ("ObParseTree")
Module ("ObliqParser")

if equal (OS_TYPE, "WIN32")
  implementation ("ObPathSepWin32")
else if equal (OS_TYPE, "POSIX")
  implementation ("ObPathSepPosix")
else
  error ("obliqparse: unrecognized OS: " & OS_TYPE & CR)
end end

resource_named ("ObliqGram", "obliq.gr")
bundle ("ObliqBdl")

Library ("obliqparse")

/* ManPage(obliqparse,?) */


