%if equal (OS_TYPE, "WIN32")
%  override("obliqrt", "\\\\stieglitz\\graphics\\arm3\\bm-work\\cm3\\m3-obliq")
%else
%  override("obliqrt", "/proj/graphics/arm3/bm-work/cm3/m3-obliq")
%end
override ("libm3", ROOT & "/m3-libs")
override ("synex", ROOT & "/m3-obliq")
override ("metasyn", ROOT & "/m3-obliq")
override ("obliqrt", ROOT & "/m3-obliq")

