%
% Copyright 1995-96 Critical Mass, Inc. All rights reserved.
% m3makefile for CM3_IDE
%

% m3_option ("-times")

import ("libm3")
import ("tcp")
import ("m3tools")
import ("m3quake")

include_dir ("utils")
include_dir ("markup")
include_dir ("server")
include_dir ("nodes")
include_dir ("misc")
include_dir ("forms")
include_dir ("rsrc")
include_dir ("examples")

bundle ("CM3_IDE_Bundle")
implementation ("Main") 

build_standalone()
Program ("cm3ide")

