
%XXDIR = { "WIN32" : "N:\\m3-sys",  "POSIX" : "/proj/cmass/src.2/m3-sys" }
%WORKDIR = XXDIR {OS_TYPE}
WORKDIR = ROOT & SL & "m3-sys"
LIBDIR = ROOT & SL & "m3-libs"
COMMDIR = ROOT & SL & "m3-comm"

if not defined("BOOT")
  override ("m3core", LIBDIR)
  override ("libm3", LIBDIR)
end

override ("m3middle", WORKDIR)
override ("m3quake",  WORKDIR)
override ("m3tools",  WORKDIR)
override ("cmkey",    WORKDIR)
override ("tcp",      COMMDIR)
override ("windowsResources", WORKDIR)
