/* $Id$ */

if not equal (OS_TYPE, "WIN32")

if defined("pm3_version")
	option("optimization","") 
end


if not SYSTEM_LIBS contains "MPZ"
  SYSTEM_LIBS{"MPZ"} = [ "-L/opt/homebrew/lib", "-lgmp" ]
  SYSTEM_LIBORDER += [ "MPZ" ]
end

import("libm3")
import("cit_util")
import("mscheme")
import("schemesig")
import("modula3scheme")
import("parseparams")

implementation("Main")

program("mscheme")

end