/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Wed Nov 24 15:23:47 PST 1993 by steveg                   */

Interface ("XMachine")
