% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Makefile for smalldb library
% Last modified on Wed Dec 22 16:25:31 PST 1993 by kalsow
%      modified on Thu Jul 29 16:49:55 PDT 1993 by wobber

import("libm3")

Module("SmallDB")
if equal (OS_TYPE, "WIN32")
  interface("OSSupport")
  interface("OSSupportWIN32IF")
  implementation("OSSupportWIN32")
else
  module("OSSupport")
end

Library("m3smalldb")
