dir src
dir /proj/graphics/arm3/rdwr/src
dir /proj/graphics/software/src/modula3-3.5.4/m3/m3core/src/runtime/common
dir /proj/graphics/software/src/modula3-3.5.4/m3/m3core/src/runtime/POSIX
dir /proj/graphics/software/src/modula3-3.5.4/m3/m3core/src/thread/Common
dir /proj/graphics/software/src/modula3-3.5.4/m3/m3core/src/thread/POSIX
dir /proj/graphics/software/src/modula3-3.5.4/m3/libm3/src/rw/Common
dir /proj/graphics/software/src/modula3-3.5.4/m3/libm3/src/rw/POSIX
dir /proj/graphics/software/src/modula3-3.5.4/m3/libm3/src/pickle
break RdWrPipe__RdSeek
break RdWrPipe__WrSeek
break RdWrPipe__WrFlush
