UP1 = SL & ".." & SL
UP2 = SL & ".." & UP1
UP3 = SL & ".." & UP2

%include(path() & UP3 & "dccslib/quake/src/quake.elego")

import("libm3")
import("vbtkit")

import("sysutils")

Module("RsrcFilter")
Module("RsrcUtils")
Interface("StdFonts")
if equal (OS_TYPE, "WIN32")
  implementation("StdFontsWin32")
else
  implementation("StdFontsX")
end


Library("graphicutils")
