% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Mar 21 23:12:40 PST 1994 by luca  
%      modified on Wed Dec 22 15:13:36 PST 1993 by kalsow

if not HasTrestle()
  build_standalone()
end

import("formsvbt")
import("synloc")
import("obliqrt")

Module ("ObLibUI")

Library("obliqlibui")

/* ManPage(obliqlibui,?) */
