% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Sep 20 11:47:30 PDT 1993 by kalsow
%      modified on Thu Jul 15 16:14:28 PDT 1993 by swart

% interface("WinRPC")
implementation("MachineIDWin32")
