/* m3makefile for windowsResources library */

import("libm3")

%% The WinResDummy interface is	needed to get around a limitation
%% in CM3 4.1 so that the package can be shipped.
interface ("WinResDummy")

%
% Due to a bug in the Win32 WINBASE.H header,
% version 4.1 of the Critical Mass Modula-3
% the m3linker generates an incorrect call
% to GetEnvironmentStrings, where it should
% be calling GetEnvironmentStringsA. To
% work around the problem, we link a small
% C fragment that maps calls to	GetEnvironmentString
% to GetEnvironmentStringA.
%
% This problem has been	fixed in later releases
% of Critical Mass compilers.
%
%c_source("cm3-41-hack")

template("winRes")

Library("windowsResources")
