#! /usr/bin/env python

import os, sys

PossibleExecutables = [
    "/usr/bin/cc",
    "/opt/solarisstudio12.3/bin/cc",
    "/opt/solstudio12.2/bin/cc",
    "/opt/studio/SOS12/SUNWspro/bin/cc",
    "/opt/studio/SOS11/SUNWspro/bin/cc",
    "/opt/SUNWspro/bin/cc",
    #"/opt/csw/gcc4/bin/gcc",
    #"/usr/sfw/bin/gcc",
    #"/opt/csw/gcc4/bin/gcc",
    ]

for Executable in PossibleExecutables:
    if os.access(Executable, os.X_OK):
        break;
if not os.access(Executable, os.X_OK):
  sys.stderr.write(Executable + " not executable\n")
  sys.exit(1)

sys.argv[0] = Executable
print(" ".join(sys.argv)) # won't show quotes, ok
os.execvp(Executable, sys.argv)
