/* Copyright (C) 1994, Digital Equipment Corporation */
/* All rights reserved. */
/* See the file COPYRIGHT for a full description. */
/* Makefile for pkgtool libraries - POSIX/MIPS-Ultrix specific */
/* Last modified on Mon Apr  4 10:56:47 PDT 1994 by wobber     */

interface ("Umnt")
implementation ("FileSysExtra")
