% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Fri Jul 30 09:35:20 PDT 1993 by kalsow
%      modified on Fri May  7 14:56:08 PDT 1993 by muller

Interface ("Real")
Interface ("LongReal")
%Interface ("Extended")

implementation ("RealFloat")
implementation ("LongFloat")
%implementation ("ExtendedFloat")

%Extended interface and ExtendedFloat implementation 
% - one of these dirs depending on backend
if not equal (M3_BACKEND_MODE, "IntegratedObject")
  include_dir ("ext64")
else
  include_dir ("ext128")
end
