#!/bin/bash
modname=$1
typechar=$2
typeChar=$3

filelist="
bdsqr
gebak
gebal
gebd2
gebrd
gecon
geequ
gees
geesx
gegs
gehd2
gehrd
gelq2
gelqf
gels
gelsx
geqpf
geqr2
geqrf
gerfs
gerq2
gerqf
gesvx
getf2
getrf
getri
getrs
ggbak
ggbal
gghrd
hgeqz
hseqr
labad
labrd
lacon
lacpy
ladiv
lae2
laev2
laexc
lag2
lahqr
lahrd
laic1
laln2
lange
lanhs
lansp
lanst
lansy
lantr
lanv2
lapmt
lapy2
lapy3
laqge
larf
larfb
larfg
larft
larfx
lartg
las2
lascl
laset
lasq1
lasq2
lasq3
lasq4
lasr
lasrt
lassq
lasv2
laswp
lasy2
lasyf
latrs
latzm
opgtr
org2l
org2r
orgbr
orghr
orgl2
orglq
orgql
orgqr
orgr2
orgrq
orgtr
orm2r
ormbr
ormhr
orml2
ormlq
ormqr
ormr2
ormrq
pocon
potrs
pptrf
rscl
spev
spgst
spgv
sptrd
sptrf
steqr
sterf
sycon
syev
sytf2
sytrf
sytri
sytrs
tgevc
trcon
trexc
trsen
trsyl
trti2
trtri
tzrqf
"

# geqlf
# gesvd
# gges
# lamch
# ormql
# potrf
# sytrd


(
echo "INTERFACE "$modname";" ;
echo "(* This is automatically generated by lapack2i3.sh *)" ;
echo "(* Abstract: Low level interfaces to LAPACK" ;
echo ;
echo "Using them directly is unsafe, please use the safe wrappers from "`basename $modname Raw`" *)" ;
for file in $filelist; do echo $file >&2; \
echo ; \
f2i3.sh /tmp/LAPACK/SRC/$typechar$file.f; \
done ;
echo ;
echo "END "$modname"."
) | sed -e "s/PROCEDURE  *"$typeChar"/PROCEDURE /" | m3pp
