import("libm3")

template("matrix")


generic_module("MatrixBasic")
MatrixBasic("Real",	       "RealVectorBasic",             "RealBasic")
MatrixBasic("LongReal",        "LongRealVectorBasic",         "LongRealBasic")
MatrixBasic("Extended",        "ExtendedVectorBasic",         "ExtendedBasic")
MatrixBasic("LongRealComplex", "LongRealComplexVectorBasic",  "LongRealComplexBasic")
MatrixBasic("Integer32",       "Integer32VectorBasic",        "Integer32Basic")
MatrixBasic("BigInteger",      "BigIntegerVectorBasic",       "BigIntegerBasic")

generic_module("MatrixFast")
MatrixFast("Real",     "RealVectorFast",     "RealBasic")
MatrixFast("LongReal", "LongRealVectorFast", "LongRealBasic")
MatrixFast("Extended", "ExtendedVectorFast", "ExtendedBasic")

generic_module("MatrixDecomposition")
MatrixDecomposition("Real",     "RealMatrixFast",     "RealVectorFast",     "RealBasic",     "RealTrans")
MatrixDecomposition("LongReal", "LongRealMatrixFast", "LongRealVectorFast", "LongRealBasic", "LongRealTrans")
MatrixDecomposition("Extended", "ExtendedMatrixFast", "ExtendedVectorFast", "ExtendedBasic", "ExtendedTrans")

module("EigenSystem")
%generic_module("EigenSystem")
%EigenSystem("Real",     "RealMatrixFast",     "RealVectorFast",     "RealBasic",     "RealTrans")
%EigenSystem("LongReal", "LongRealMatrixFast", "LongRealVectorFast", "LongRealBasic", "LongRealTrans")
%EigenSystem("Extended", "ExtendedMatrixFast", "ExtendedVectorFast", "ExtendedBasic", "ExtendedTrans")

generic_module("MatrixFmtLex")
MatrixFmtLex("Real",     "RealMatrixFast",     "RealFmtLex")
MatrixFmtLex("LongReal", "LongRealMatrixFast", "LongRealFmtLex")
MatrixFmtLex("Extended", "ExtendedMatrixFast", "ExtendedFmtLex")
MatrixFmtLex("LongRealComplex", "LongRealComplexMatrixBasic", "LongRealComplexFmtLex")
MatrixFmtLex("Integer32",       "Integer32MatrixBasic",       "Integer32FmtLex")
MatrixFmtLex("BigInteger",      "BigIntegerMatrixBasic",      "BigIntegerFmtLex")
