import("libm3")

template("matrix")


generic_module("MatrixBasic")
MatrixBasic("LongRealComplex",  "LongRealComplexBasic", "LongRealComplexVectorBasic")
MatrixBasic("Integer32",        "Integer32Basic",       "Integer32VectorBasic")
MatrixBasic("BigInteger",       "BigIntegerBasic",      "BigIntegerVectorBasic")

generic_module("MatrixFast")
MatrixFast("Real",     "RealBasic",     "RealVectorFast")
MatrixFast("LongReal", "LongRealBasic", "LongRealVectorFast")
MatrixFast("Extended", "ExtendedBasic", "ExtendedVectorFast")

generic_module("MatrixTrans")
MatrixTrans("Real",             "Fast",  "Real",     "",        "Basic")
MatrixTrans("LongReal",         "Fast",  "LongReal", "",        "Basic")
MatrixTrans("Extended",         "Fast",  "Extended", "",        "Basic")
%MatrixTrans("RealComplex",     "Basic", "Real",     "Complex", "Fast")
%MatrixTrans("LongRealComplex", "Basic", "LongReal", "Complex", "Fast")
%MatrixTrans("ExtendedComplex", "Basic", "Extended", "Complex", "Fast")

generic_module("MatrixDecomposition")
MatrixDecomposition("Real",     "Fast")
MatrixDecomposition("LongReal", "Fast")
MatrixDecomposition("Extended", "Fast")

generic_module("EigenSystem")
EigenSystem("Real",     "Fast")
EigenSystem("LongReal", "Fast")
EigenSystem("Extended", "Fast")

module("LongRealMatrixLapack")

generic_module("CharPolynomial")
CharPolynomial("Real",            "Fast",  "Basic")
CharPolynomial("LongReal",        "Fast",  "Basic")
CharPolynomial("Extended",        "Fast",  "Basic")
CharPolynomial("LongRealComplex", "Basic", "Fast")
CharPolynomial("Integer32",       "Basic", "Basic")
CharPolynomial("BigInteger",      "Basic", "Basic")

generic_module("MatrixFmtLex")
MatrixFmtLex("Real",            "Fast")
MatrixFmtLex("LongReal",        "Fast")
MatrixFmtLex("Extended",        "Fast")
MatrixFmtLex("LongRealComplex", "Basic")
MatrixFmtLex("Integer32",       "Basic")
MatrixFmtLex("BigInteger",      "Basic")
