import("libm3")

template("matrix")


generic_module("MatrixBasic")
MatrixBasic("LongRealComplex", "LongRealComplexVectorBasic",  "LongRealComplexBasic")
MatrixBasic("Integer32",       "Integer32VectorBasic",        "Integer32Basic")
MatrixBasic("BigInteger",      "BigIntegerVectorBasic",       "BigIntegerBasic")

generic_module("MatrixFast")
MatrixFast("Real",     "RealVectorFast",     "RealBasic")
MatrixFast("LongReal", "LongRealVectorFast", "LongRealBasic")
MatrixFast("Extended", "ExtendedVectorFast", "ExtendedBasic")

generic_module("MatrixTrans")
MatrixTrans("Real",     "RealMatrixFast",     "RealEigenSystem",     "RealTrans",     "RealBasic",     "RealTrans")
MatrixTrans("LongReal", "LongRealMatrixFast", "LongRealEigenSystem", "LongRealTrans", "LongRealBasic", "LongRealTrans")
MatrixTrans("Extended", "ExtendedMatrixFast", "ExtendedEigenSystem", "ExtendedTrans", "ExtendedBasic", "ExtendedTrans")
%MatrixTrans("RealComplex",     "RealComplexMatrixFast",     "RealComplexEigenSystem",     "RealComplexTrans",     "RealBasic",     "RealTrans")
%MatrixTrans("LongRealComplex", "LongRealComplexMatrixFast", "LongRealComplexEigenSystem", "LongRealComplexTrans", "LongRealBasic", "LongRealTrans")
%MatrixTrans("ExtendedComplex", "ExtendedComplexMatrixFast", "ExtendedComplexEigenSystem", "ExtendedComplexTrans", "ExtendedBasic", "ExtendedTrans")

generic_module("MatrixDecomposition")
MatrixDecomposition("Real",     "RealMatrixFast",     "RealVectorFast",     "RealBasic",     "RealTrans")
MatrixDecomposition("LongReal", "LongRealMatrixFast", "LongRealVectorFast", "LongRealBasic", "LongRealTrans")
MatrixDecomposition("Extended", "ExtendedMatrixFast", "ExtendedVectorFast", "ExtendedBasic", "ExtendedTrans")

generic_module("EigenSystem")
EigenSystem("Real",     "RealMatrixFast",     "RealVectorFast",    "RealBasic",     "RealTrans")
EigenSystem("LongReal", "LongRealMatrixFast", "LongRealVectorFast", "LongRealBasic", "LongRealTrans")
EigenSystem("Extended", "ExtendedMatrixFast", "ExtendedVectorFast", "ExtendedBasic", "ExtendedTrans")

generic_module("CharPolynomial")
CharPolynomial("Real",            "RealMatrixFast",              "RealRootBasic",             "RealBasic")
CharPolynomial("LongReal",        "LongRealMatrixFast",          "LongRealRootBasic",         "LongRealBasic")
CharPolynomial("Extended",        "ExtendedMatrixFast",          "ExtendedRootBasic",         "ExtendedBasic")
CharPolynomial("LongRealComplex", "LongRealComplexMatrixBasic",  "LongRealComplexRootBasic",  "LongRealComplexBasic")
CharPolynomial("Integer32",       "Integer32MatrixBasic",        "Integer32RootBasic",        "Integer32Basic")
CharPolynomial("BigInteger",      "BigIntegerMatrixBasic",       "BigIntegerRootBasic",       "BigIntegerBasic")

generic_module("MatrixFmtLex")
MatrixFmtLex("Real",     "RealMatrixFast",     "RealFmtLex")
MatrixFmtLex("LongReal", "LongRealMatrixFast", "LongRealFmtLex")
MatrixFmtLex("Extended", "ExtendedMatrixFast", "ExtendedFmtLex")
MatrixFmtLex("LongRealComplex", "LongRealComplexMatrixBasic", "LongRealComplexFmtLex")
MatrixFmtLex("Integer32",       "Integer32MatrixBasic",       "Integer32FmtLex")
MatrixFmtLex("BigInteger",      "BigIntegerMatrixBasic",      "BigIntegerFmtLex")
