% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

Interface ("ThreadF")
Interface ("ThreadContext")
implementation ("ThreadWin32")
interface("ThreadInternal")

if equal (OS_TYPE, "POSIX")   
    implementation("SchedulerPosix")   
end 
