% See the file COPYRIGHTi-COLUMBIA for a full description.

import("libm3")
import("netobj")
import("rdwr")
import("events")
import("debug")
import("embutils")

% m3_option("-commands")

% Interface ("ShProxiedObj")
Interface ("SharedObj")
Module ("SharedObjF")
Module ("SharedObjRep")
Module ("SharedObjStubLib")
Interface ("SharedObjError")
Interface ("ObjectSpace")
Module ("WeakerRef")
Module ("SharedObjRT")
List	 ("WeakRef", "WeakerRef")
ListFuncs ("WeakRef", "WeakerRef", "WeakRefList")

interface ("SharedObjRTF")
module ("LocalObjectSpace")

module ("Message")
module ("ObjCopy")
module ("ObjectInfo")
module ("SpaceConn")

% module ("AckInfo")
% list     ("Ack", "AckInfo")

list     ("ObjCopy", "ObjCopy")
listfuncs ("ObjCopy", "ObjCopy", "ObjCopyList")
table    ("ObjectInfo", "EventWireRep", "ObjectInfo")
table    ("Space", "Fingerprint", "SpaceConn")
list     ("Message", "Message")
listfuncs ("Message", "Message", "MessageList")

template("sharedobj")

%netobj("ObjectSpace", "FindObjCallBack")
%netobj("ObjectSpace", "T")
% won't generate it properly with the field
%    callbacks: WeakRefList.T := NIL;
% in the SharedObjRep.T
Module   ("ObjectSpace_T_v2")
Module   ("ObjectSpace_FindObjCallBack_v2")

Library("sharedobj")
