% Copyright (C) 1995, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Oct 11 13:54:10 PDT 1995 by najork
%      modified on Wed Jun 14 13:41:11 PDT 1995 by kalsow
%
% Contributed by Harry George (hgeorge@eskimo.com), 5/16/95

if defined("configure_system_libs")
  configure_system_libs()
end 

if SYSTEM_LIBS contains "MOTIF"
  import_sys_lib ("MOTIF")
  import ("X11R4")

  Interface ("IntrinsicP")
  Module    ("Xmacro")
  Module    ("Xm")
  Module    ("XmC")
  Module    ("XmN")
  Module    ("Xmw")

  Library ("m3motif")
end
