% Copyright 1996, Critical Mass, Inc.  All rights reserved.

import_sys_lib ("POSTGRES95")
import ("libm3")

Interface ("PQ")
Interface ("PQcomm")
Interface ("Postgres")

if equal (TARGET, "ALPHA_OSF")
  % missing libpq.a => can't build local .so file...
  build_standalone ()
end

Library ("postgres95")
