% Copyright 1996-2000, Critical Mass, Inc.  All rights reserved.
% See file COPYRIGHT-CMASS for details.

configure_system_libs()

if SYSTEM_LIBS contains "POSTGRES95"

import_sys_lib ("POSTGRES95")
import ("libm3")

Interface ("PQ")
Interface ("PQcomm")
Interface ("Postgres")

implementation ("PQ")

if equal (TARGET, "ALPHA_OSF")
  % missing libpq.a => can't build local .so file...
  build_standalone ()
end

Library ("postgres95")

end