/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Thu Apr 21 15:38:24 PDT 1994 by heydon                   */

/* m3makefile for /proj/m3/pkg/juno-compiler/tests/lexer/src */

implementation(LexerTest)

import(juno-machine)
import(juno-compiler)
import(libm3)
export_interface(JunoLex)
export_interface(JunoToken)

build_standalone()
program(LexerTest)
