/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Mon Apr  4 09:26:29 PDT 1994 by heydon                   */

/* m3overrides for /proj/m3/pkg/juno-compiler/tests/lexer/src */

override(juno-machine,  WDROOT)
override(juno-compiler, WDROOT)
