% Copyright (C) 1998, Compaq Computer Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Fri Dec 11 15:41:23 PST 1998 by heydon  

Interface ("UDP")

c_source("UDP_c")
interface("UDPInternal")

if AT_SRC
  local_i3 ("UDP")
end
