SHAREDOBJGEN = format("/u/stieglitz/bm/arm3/bm-work/cm3/sharedobjgen/%s/shobjcodegen", BUILD_DIR)

import("sharedobj")
import("trackers")

interface("TrackerPosition")
interface("TrackerPositionF")

sharedobj("TrackerPosition", ["T"], ["TrackerPositionF"])

interface("TrackerPositionPickle")

library("fudge")
