(*********************************************************************)
(*                                                                   *)
(* TrackerPositionTstPRX.m3                                          *)
(* -- autogenerated by SOCodeGen --                                  *)
(* Thu Dec 21 08:02:15 EST 1995                                      *)
(*                                                                   *)
(*********************************************************************)

MODULE TrackerPositionTstPRX;

IMPORT TrackerPositionTst;

REVEAL

 TrackerPositionTst_T = Public_TrackerPositionTst_T BRANDED Brand_TrackerPositionTst_T OBJECT;
  item: TrackerPositionTst.T;
  OVERRIDES
   init := Init_TrackerPositionTst_T;

   get := My_get_TrackerPositionTst_T;
 END;


 TrackerPositionTst_U = Public_TrackerPositionTst_U BRANDED Brand_TrackerPositionTst_U OBJECT;
  item: TrackerPositionTst.U;
  OVERRIDES
   init := Init_TrackerPositionTst_U;

   init := My_init_TrackerPositionTst_U;
   get := My_get_TrackerPositionTst_U;
 END;


PROCEDURE Init_TrackerPositionTst_T( self: TrackerPositionTst_T; t: TrackerPositionTst.T) :TrackerPositionTst_T =
 BEGIN
  self.item := t;
  RETURN self;
 END Init_TrackerPositionTst_T;

PROCEDURE My_get_TrackerPositionTst_T( self: TrackerPositionTst_T; ): TrackerPositionTst.T =
 BEGIN
  RETURN self.item;
 END My_get_TrackerPositionTst_T;

PROCEDURE Init_TrackerPositionTst_U( self: TrackerPositionTst_U; t: TrackerPositionTst.U) :TrackerPositionTst_U =
 BEGIN
  self.item := t;
  RETURN self;
 END Init_TrackerPositionTst_U;

PROCEDURE My_init_TrackerPositionTst_U( self: TrackerPositionTst_U; ): TrackerPositionTst.U =
 BEGIN
  RETURN self.item;
 END My_init_TrackerPositionTst_U;

PROCEDURE My_get_TrackerPositionTst_U( self: TrackerPositionTst_U; ): TrackerPositionTst.U =
 BEGIN
  RETURN self.item;
 END My_get_TrackerPositionTst_U;

BEGIN
END TrackerPositionTstPRX.
