/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Thu Jun 26 15:23:18 PDT 1997 by heydon                   */
/*      modified on Wed Feb 15 16:52:09 PDT 1995 by gnelson                  */

/* m3makefile for /proj/m3/pkg/juno-compiler/src */

/* imported packages */
import		("libm3")
import		("juno-machine")

/* public interfaces */
Module		("BuiltInSlots")
Module		("JunoAST")
Module		("JunoASTUtils")
Module		("JunoChkBNF")
Module		("JunoCompile")
Module		("JunoCompileErr")
Module		("JunoLex")
Module		("JunoParse")
Module		("JunoScope")
Module		("JunoToken")
Module		("JunoUnparse")
Module		("StackTbl")

/* private interfaces */
module		("JunoAssemble")
interface	("JunoCompileRep")
module		("JunoCompileNF")
module		("IndexedNF")
module		("WriteVal")

/* build the "libjuno-compiler.a" library */
library		("juno-compiler")

/* extra compiler options */
m3_option	("-times")
m3_option	("-O")
