#! /usr/bin/env python

#
# This stub lets Hudson find java on NetBSD.     
#
# Put it at /usr/local/bin/java.
# Make sure it is executable.
# Test it out:
#  java -version
#

import sys
import os

jdk = "/usr/pkg/java/openjdk7/bin"                             
base = os.path.basename(sys.argv[0]);

full = os.path.join(jdk, base)

if os.path.isfile(full):
    os.environ["PATH"] = jdk + ":" + os.environ["PATH"]
    sys.argv[0] = full
    os.execv(full, sys.argv)

print("unknown " + str(sys.argv))
sys.exit(1)
