.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" Last modified on Tue Jun 16 23:36:49 PDT 1992 by muller
.\"      modified on Wed Jun 10 17:17:08 1992 by mhb
.nh
.TH fisheye 1
.SH NAME
fisheye \- an experimental fisheye browser of graphs

.SH SYNTAX
.B fisheye

.SH DESCRIPTION 
.B fisheye
is an experimental application that was developed
to validate concepts about "graphical fisheye views of graphs".
See SRC Research Report #84 or the CHI '92 proceedings.

The system is somewhat fragile. It is not supported nor is it 
well-documented. It isn't recommended for general consumption.
However, if you are interested enough, you may find it of some 
use. Enjoy, enhance, exclaim, but don't complain!

.SH DATA FILES
.../fisheye/src/fisheye.datafiles

.SH AUTHOR OF OBJECT
Manojit Sarkar (Intern at SRC in Summer '91); a tad by Marc H. Brown

.SH AUTHOR OF DOCUMENTATION
Marc H. Brown

