

m3_option("-verbose")
m3_option("-w2")

import ("libm3")
module ("Action")
implementation ("PickleExample")

table("AtomAction", "Atom", "Action")
module("Action")

program ("peratom-db")
                     
