%The m3makefile for the QtCore library

include("../../common/qinclude")

import("libm3")

cxx_source("dynamicqobject")
import_obj("dynamicqobject")

%Core stubs
interface("QCoreStubs")

%m3qtcore branch (perm) has m3makefile

qtbuild("QtNamespace")
%the sligslots interface
qtbuild("QtDynamic")

%core1 branch

qtbuild("QtByteArray")
qtbuild("QtString")
qtbuild("QtList")
qtbuild("QtStringList")

%core2 branch

qtbuild("QtEvent")
qtbuild("QtObject")

%core3 branch

qtbuild("QtPoint")
qtbuild("QtLine")
qtbuild("QtSize")
qtbuild("QtRect")

%core4 branch

qtbuild("QtDateTime")
qtbuild("QtMargins")
qtbuild("QtAbstractItemModel")
%not working yet
%qtbuild("QtObjectDefs")

library("m3qtcore")
