
import("bilist")

template("refinablefunction")


generic_module("RefinableFunction")
RefinableFunction("Real",            "RealBasic",       "RealComplex")
RefinableFunction("LongReal",        "LongRealBasic",   "LongRealComplex")
% requires EigenSystem
%RefinableFunction("Extended",        "ExtendedBasic",   "ExtendedComplex")
%RefinableFunction("RealComplex",     "RealComplex",     "RealComplex")
%RefinableFunction("LongRealComplex", "LongRealComplex", "LongRealComplex")
%RefinableFunction("ExtendedComplex", "ExtendedComplex", "ExtendedComplex")

generic_module("RefinableSmooth")
RefinableSmooth("Real",            "RealBasic",       "RealComplex")
RefinableSmooth("LongReal",        "LongRealBasic",   "LongRealComplex")
