
template("refinablefunc")


generic_module("RefinableFunc")
RefinableFunc("Real",            "RealBasic",           "RealSignal",            "RealVectorFast",             "RealMatrixFast")
RefinableFunc("LongReal",        "LongRealBasic",       "LongRealSignal",        "LongRealVectorFast",         "LongRealMatrixFast")
RefinableFunc("Extended",        "ExtendedBasic",       "ExtendedSignal",        "ExtendedVectorFast",         "ExtendedMatrixFast")
%RefinableFunc("RealComplex",     "RealComplexFast",     "RealComplexSignal",     "RealComplexVectorBasic",     "RealComplexMatrixBasic")
RefinableFunc("LongRealComplex", "LongRealComplexFast", "LongRealComplexSignal", "LongRealComplexVectorBasic", "LongRealComplexMatrixBasic")
%RefinableFunc("ExtendedComplex", "ExtendedComplexFast", "ExtendedComplexSignal", "ExtendedComplexVectorBasic", "ExtendedComplexMatrixBasic")
