
template("refinablefunc")


generic_module("RefinableFunc")
RefinableFunc("Real",            "Real",            "Basic", "Fast",  "Fast")
RefinableFunc("LongReal",        "LongReal",        "Basic", "Fast",  "Fast")
RefinableFunc("Extended",        "Extended",        "Basic", "Fast",  "Fast")
%RefinableFunc("RealComplex",     "RealComplex",     "Fast",  "Basic", "Basic")
RefinableFunc("LongRealComplex", "LongRealComplex", "Fast",  "Basic", "Basic")
%RefinableFunc("ExtendedComplex", "ExtendedComplex", "Fast",  "Basic", "Basic")
