import("libm3")

include("polar.tmpl")

generic_module("PolarBasic")
PolarBasic("Real",     "RealComplexBasic",     "RealComplexTrans",     "RealBasic",	"RealTrans")
PolarBasic("LongReal", "LongRealComplexBasic", "LongRealComplexTrans", "LongRealBasic", "LongRealTrans")
PolarBasic("Extended", "ExtendedComplexBasic", "ExtendedComplexTrans", "ExtendedBasic", "ExtendedTrans")

%generic_module("PolarFmtLex")
%PolarFmtLex("Real",     "RealPolarBasic",     "RealBasic",     "RealFmtLex")
%PolarFmtLex("LongReal", "LongRealPolarBasic", "LongRealBasic", "LongRealFmtLex")
%PolarFmtLex("Extended", "ExtendedPolarBasic", "ExtendedBasic", "ExtendedFmtLex")
