import("libm3")

template("polar")


generic_module("PolarBasic")
PolarBasic("Real",     "RealComplexBasic",     "RealComplexTrans",     "RealBasic",	"RealTrans")
PolarBasic("LongReal", "LongRealComplexBasic", "LongRealComplexTrans", "LongRealBasic", "LongRealTrans")
PolarBasic("Extended", "ExtendedComplexBasic", "ExtendedComplexTrans", "ExtendedBasic", "ExtendedTrans")

generic_module("PolarFmtLex")
PolarFmtLex("Real",     "RealPolarBasic",     "RealFmtLex")
PolarFmtLex("LongReal", "LongRealPolarBasic", "LongRealFmtLex")
PolarFmtLex("Extended", "ExtendedPolarBasic", "ExtendedFmtLex")
