% Copyright (C) 1995, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
%override 	("board", "/udir/umesh/m3/board/3")
import		("board")
import		("m3tk-misc")
import		("smalldb")

interface ("AtomicItemTbl")

module ("ClientInfoX")
list ("ClientInfo", "ClientInfo")
module ("AtomicClientList")

module ("NotifyRec")
list ("NotifyRec", "NotifyRec")
module ("NotifyQueue")
module ("Log")

module ("BoardX")
table ("Board", "Text", "Board")
module ("BoardServerX")

implementation ("Server")
program ("boardserver")

