% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Aug 22 23:08:23 PDT 1996 by najork 
%      modified on Wed Apr  5 17:07:09 PDT 1995 by mhb   
%      modified on Sat Jul 16 08:20:08 PDT 1994 by bharat

import ("formsvbt")
implementation("Main")
Program("voquery")

