% (* ----------------------------------------------------------------------1- *)
% (* File m3makefile for Modula3 compiler test p288                           *)
% (* Copyright 2021, Rodney M. Bates.                                         *)
% (* rodney.m.bates@acm.org                                                   *)
% (* Licensed under the MIT license.                                          *)
% (* ----------------------------------------------------------------------2- *)

import("libm3")

interface("Named")
module("First")
module("Display")
module("Second")

implementation ("Main")
include("../../Test.common")
