% Copyright (C) 1994, Digital Equipment Corporation.
% All rights reserved.
% See the file COPYRIGHT for a full description.
 
if equal(WORD_SIZE, "64BITS")
  implementation("Main64")
else
  implementation("Main32")
end

include ("../../Test.common") 
