% Copyright (C) 1994, Digital Equipment Corporation.
% All rights reserved.
% See the file COPYRIGHT for a full description.
 
interface ("A")
interface ("X")
implementation ("A")
implementation ("Main")
implementation ("X")
generic_interface ("Generic")
generic_implementation ("Generic")
