% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

h_source ("dtoa")
c_source ("hand")
if equal(TARGET, "NT386")
  % c_source ("hand2")
end
