/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Fri Jun  2 10:50:44 PDT 1995 by najork                   */

if equal (TARGET, "NT386")
  override ("vbtkit", "..\\..")
end

import		("vbtkit")
resource	("Juno2Logo.ppm")
bundle		("TestBundle")
implementation	("Test28")
Program	        ("Test28") 
