% Copyright (C) 1996, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Aug 19 15:09:14 PDT 1996 by steveg

import("libm3")
import("tcp")

Module("App")
Module("AppBackup")
Module("HTTP")
Module("HTTPApp")
Module("HTTPPayment")
Module("HTTPProxy")
Module("HTTPControl")
Module("HTTPControlValue")
module("TextExtras")
Module("FastLex")

Library("http")
