% Copyright (C) 1996, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Jan 23 15:45:13 PST 1997 by steveg

%write("WDROOT = ", WDROOT, CR)

import("libm3")
import("tcp")
import("sysutils")

Module("App")
Module("AppBackup")
Module("HTTP")
Module("HTTPApp")
Module("HTTPPayment")
Module("HTTPProxy")
Module("HTTPControl")
Module("HTTPControlValue")

Library("http")
