% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Oct 26 13:44:21 PDT 1995 by steveg   
%      modified on Wed Sep 28 18:46:24 PDT 1994 by glassman 
%      modified on Tue Sep 27 09:50:34 PDT 1994 by mhb     
%      modified on Wed Dec 22 16:22:13 PST 1993 by kalsow

% import ("web")
import ("http")

% implementation ("Main")
implementation("HTTPCat")

Program ("webcat")
ManPage ("webcat", "1")
