% Copyright (C) 1998, Compaq Computer Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Sun Dec  6 18:29:29 PST 1998 by heydon  

import ("libm3")
import ("tcp")
import ("udp")

implementation ("TestUDP")
program ("TestUDP")

% FIXME: TestUDP needs a more complex setup, running both client
% and server. This would be possible from quake, but we also need
% a timeout mechanism in case something hangs.
% It doesn't work out-of-the-box on FreeBSD 6.3.
% Find and fix errors later.
%if defined("RUN")
%  r = q_exec( "." & SL & "TestUDP" )
%  write( CR, "program returned ", r, CR )
%end
