% Copyright (C) 1998, Compaq Computer Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Sun Dec  6 18:32:34 PST 1998 by heydon  

override ("udp", PACKAGE_DIR & SL & ".." & SL & "..")
