write(CR, "--- tests in ", getwd(), "---", CR)

import("libm3")
import("unittest")
import("unittest-numeric")

implementation("Main")
program("test")

if defined("RUN")
  r = q_exec( "." & SL & "test" )
  write( CR, "program returned ", r, CR )
end
