% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Wed Jun  9 17:25:24 PDT 1993 by harrison
%      modified on Thu May  6 12:13:41 PDT 1993 by muller

Interface ("Csetjmp")
Interface ("Cstdio")
Interface ("Cstring")

