---
name: Unix install binary release
description: Install a binary release on a Unix-like system

inputs:
  cm3inst:
    description: Target location for install
    required: true
  cm3release:
    description: Release tarball to install
    required: true

runs:
  using: composite

  steps:
  - name: Install binary release
    run: |
      mkdir -p "${{ inputs.cm3inst }}"
      curl --location --silent "${{ inputs.cm3release }}" | tar zxf - --directory="${{ inputs.cm3inst }}" --strip-components=1
    shell: bash

  - name: Add release binary to path
    run: |
      echo "${{ inputs.cm3inst }}/bin" >> $GITHUB_PATH
    shell: bash
