import("libm3")

template("fraction")


Generic_module("FractionBasic")
Fraction("Integer32",            "Basic", "Integer32Basic",  "Integer32GCD")
Fraction("BigInteger",           "Basic", "BigInteger",      "BigIntegerGCD")
%Fraction("BigIntegerPolynomial", "Basic", "BigIntegerPolynomial", "BigIntegerPolynomialGCD")
%Fraction("LongRealPolynomial",   "Basic", "LongRealPolynomial",   "LongRealPolynomialGCD")

Generic_module("FractionFmtLex")
FractionFmtLex("Integer32",            "Integer32Basic")
FractionFmtLex("BigInteger",           "BigInteger")
%FractionFmtLex("BigIntegerPolynomial", "BigIntegerPolynomial")
