import("libm3")

template("fraction")


generic_module("FractionBasic")
FractionBasic("Integer32",            "Integer32Basic",            "Integer32GCD")
FractionBasic("BigInteger",           "BigIntegerBasic",           "BigIntegerGCD")
FractionBasic("BigIntegerPolynomial", "BigIntegerPolynomialBasic", "BigIntegerPolynomialGCD")

generic_module("FractionFmtLex")
FractionFmtLex("Integer32",            "Integer32FractionBasic",            "Integer32Basic",            "Integer32FmtLex")
FractionFmtLex("BigInteger",           "BigIntegerFractionBasic",           "BigIntegerBasic",           "BigIntegerFmtLex")
FractionFmtLex("BigIntegerPolynomial", "BigIntegerPolynomialFractionBasic", "BigIntegerPolynomialBasic", "BigIntegerPolynomialFmtLex")
