/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGMODULA3


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif




#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#include <QtGui/qcolordialog.h>
#define  ColorDialogOptions  QColorDialog::ColorDialogOptions


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT QColorDialog * New_QColorDialog0(QWidget * parent) {
  QWidget *arg1 = (QWidget *) 0 ;
  QColorDialog *result = 0 ;
  QColorDialog * cresult ;
  
  arg1 = *(QWidget **)&parent; 
  result = (QColorDialog *)new QColorDialog(arg1);
  *(QColorDialog **)&cresult = result; 
  return cresult;
}


SWIGEXPORT QColorDialog * New_QColorDialog1() {
  QColorDialog *result = 0 ;
  QColorDialog * cresult ;
  
  result = (QColorDialog *)new QColorDialog();
  *(QColorDialog **)&cresult = result; 
  return cresult;
}


SWIGEXPORT QColorDialog * New_QColorDialog2(QColor * initial, QWidget * parent) {
  QColor *arg1 = 0 ;
  QWidget *arg2 = (QWidget *) 0 ;
  QColorDialog *result = 0 ;
  QColorDialog * cresult ;
  
  arg1 = *(QColor **)&initial;
  arg2 = *(QWidget **)&parent; 
  result = (QColorDialog *)new QColorDialog((QColor const &)*arg1,arg2);
  *(QColorDialog **)&cresult = result; 
  return cresult;
}


SWIGEXPORT QColorDialog * New_QColorDialog3(QColor * initial) {
  QColor *arg1 = 0 ;
  QColorDialog *result = 0 ;
  QColorDialog * cresult ;
  
  arg1 = *(QColor **)&initial;
  result = (QColorDialog *)new QColorDialog((QColor const &)*arg1);
  *(QColorDialog **)&cresult = result; 
  return cresult;
}


SWIGEXPORT void Delete_QColorDialog(QColorDialog * self) {
  QColorDialog *arg1 = (QColorDialog *) 0 ;
  
  arg1 = *(QColorDialog **)&self; 
  delete arg1;
}


SWIGEXPORT void QColorDialog_setCurrentColor(QColorDialog * self, QColor * color) {
  QColorDialog *arg1 = (QColorDialog *) 0 ;
  QColor *arg2 = 0 ;
  
  arg1 = *(QColorDialog **)&self; 
  arg2 = *(QColor **)&color;
  (arg1)->setCurrentColor((QColor const &)*arg2);
}


SWIGEXPORT QColor * QColorDialog_currentColor(QColorDialog const * self) {
  QColorDialog *arg1 = (QColorDialog *) 0 ;
  QColor * cresult ;
  
  arg1 = *(QColorDialog **)&self; 
  *(QColor **)&cresult = new QColor((const QColor &)((QColorDialog const *)arg1)->currentColor());
  return cresult;
}


SWIGEXPORT QColor * QColorDialog_selectedColor(QColorDialog const * self) {
  QColorDialog *arg1 = (QColorDialog *) 0 ;
  QColor * cresult ;
  
  arg1 = *(QColorDialog **)&self; 
  *(QColor **)&cresult = new QColor((const QColor &)((QColorDialog const *)arg1)->selectedColor());
  return cresult;
}


SWIGEXPORT void QColorDialog_setOption(QColorDialog * self, QColorDialog::ColorDialogOption option, bool on) {
  QColorDialog *arg1 = (QColorDialog *) 0 ;
  QColorDialog::ColorDialogOption arg2 ;
  bool arg3 ;
  
  arg1 = *(QColorDialog **)&self; 
  arg2 = (QColorDialog::ColorDialogOption)option; 
  arg3 = on ? true : false; 
  (arg1)->setOption(arg2,arg3);
}


SWIGEXPORT void QColorDialog_setOption1(QColorDialog * self, QColorDialog::ColorDialogOption option) {
  QColorDialog *arg1 = (QColorDialog *) 0 ;
  QColorDialog::ColorDialogOption arg2 ;
  
  arg1 = *(QColorDialog **)&self; 
  arg2 = (QColorDialog::ColorDialogOption)option; 
  (arg1)->setOption(arg2);
}


SWIGEXPORT bool QColorDialog_testOption(QColorDialog const * self, QColorDialog::ColorDialogOption option) {
  QColorDialog *arg1 = (QColorDialog *) 0 ;
  QColorDialog::ColorDialogOption arg2 ;
  bool result;
  bool cresult ;
  
  arg1 = *(QColorDialog **)&self; 
  arg2 = (QColorDialog::ColorDialogOption)option; 
  result = (bool)((QColorDialog const *)arg1)->testOption(arg2);
  cresult = result; 
  return cresult;
}


SWIGEXPORT void QColorDialog_setOptions(QColorDialog * self, ColorDialogOptions options) {
  QColorDialog *arg1 = (QColorDialog *) 0 ;
  ColorDialogOptions arg2 ;
  
  arg1 = *(QColorDialog **)&self; 
  arg2 = (ColorDialogOptions)options; 
  (arg1)->setOptions(arg2);
}


SWIGEXPORT ColorDialogOptions QColorDialog_options(QColorDialog const * self) {
  QColorDialog *arg1 = (QColorDialog *) 0 ;
  ColorDialogOptions cresult ;
  
  arg1 = *(QColorDialog **)&self; 
  *(ColorDialogOptions **)&cresult = new ColorDialogOptions((const ColorDialogOptions &)((QColorDialog const *)arg1)->options());
  return cresult;
}


SWIGEXPORT void QColorDialog_open0_0(QColorDialog * self) {
  QColorDialog *arg1 = (QColorDialog *) 0 ;
  
  arg1 = *(QColorDialog **)&self; 
  (arg1)->open();
}


SWIGEXPORT void QColorDialog_open1(QColorDialog * self, QObject * receiver, char * member) {
  QColorDialog *arg1 = (QColorDialog *) 0 ;
  QObject *arg2 = (QObject *) 0 ;
  char *arg3 = (char *) 0 ;
  
  arg1 = *(QColorDialog **)&self; 
  arg2 = *(QObject **)&receiver; 
  {
    arg3 = member;
  }
  (arg1)->open(arg2,(char const *)arg3);
}


SWIGEXPORT void QColorDialog_setVisible(QColorDialog * self, bool visible) {
  QColorDialog *arg1 = (QColorDialog *) 0 ;
  bool arg2 ;
  
  arg1 = *(QColorDialog **)&self; 
  arg2 = visible ? true : false; 
  (arg1)->setVisible(arg2);
}


SWIGEXPORT QColor * GetColor(QColor * initial, QWidget * parent, QString * title, ColorDialogOptions options) {
  QColor *arg1 = 0 ;
  QWidget *arg2 = (QWidget *) 0 ;
  QString *arg3 = 0 ;
  ColorDialogOptions arg4 ;
  QColor * cresult ;
  
  arg1 = *(QColor **)&initial;
  arg2 = *(QWidget **)&parent; 
  arg3 = *(QString **)&title;
  arg4 = (ColorDialogOptions)options; 
  *(QColor **)&cresult = new QColor((const QColor &)QColorDialog::getColor((QColor const &)*arg1,arg2,(QString const &)*arg3,arg4));
  return cresult;
}


SWIGEXPORT QColor * GetColor1(QColor * initial, QWidget * parent, QString * title) {
  QColor *arg1 = 0 ;
  QWidget *arg2 = (QWidget *) 0 ;
  QString *arg3 = 0 ;
  QColor * cresult ;
  
  arg1 = *(QColor **)&initial;
  arg2 = *(QWidget **)&parent; 
  arg3 = *(QString **)&title;
  *(QColor **)&cresult = new QColor((const QColor &)QColorDialog::getColor((QColor const &)*arg1,arg2,(QString const &)*arg3));
  return cresult;
}


SWIGEXPORT QColor * GetColor2(QColor * initial, QWidget * parent) {
  QColor *arg1 = 0 ;
  QWidget *arg2 = (QWidget *) 0 ;
  QColor * cresult ;
  
  arg1 = *(QColor **)&initial;
  arg2 = *(QWidget **)&parent; 
  *(QColor **)&cresult = new QColor((const QColor &)QColorDialog::getColor((QColor const &)*arg1,arg2));
  return cresult;
}


SWIGEXPORT QColor * GetColor3(QColor * initial) {
  QColor *arg1 = 0 ;
  QColor * cresult ;
  
  arg1 = *(QColor **)&initial;
  *(QColor **)&cresult = new QColor((const QColor &)QColorDialog::getColor((QColor const &)*arg1));
  return cresult;
}


SWIGEXPORT QColor * GetColor4() {
  QColor * cresult ;
  
  *(QColor **)&cresult = new QColor((const QColor &)QColorDialog::getColor());
  return cresult;
}


SWIGEXPORT QRgb GetRgba(QRgb rgba, bool * ok, QWidget * parent) {
  QRgb arg1 ;
  bool *arg2 = (bool *) 0 ;
  QWidget *arg3 = (QWidget *) 0 ;
  QRgb *argp1 ;
  QRgb cresult ;
  
  argp1 = *(QRgb **)&rgba;
  /*
     if (!argp1) {
  //     SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null QRgb");
       //RETURN 0;
       return 0;
     }
  */
  arg1 = *argp1; 
  arg2 = *(bool **)&ok; 
  arg3 = *(QWidget **)&parent; 
  *(QRgb **)&cresult = new QRgb((const QRgb &)QColorDialog::getRgba(arg1,arg2,arg3));
  return cresult;
}


SWIGEXPORT QRgb GetRgba1(QRgb rgba, bool * ok) {
  QRgb arg1 ;
  bool *arg2 = (bool *) 0 ;
  QRgb *argp1 ;
  QRgb cresult ;
  
  argp1 = *(QRgb **)&rgba;
  /*
     if (!argp1) {
  //     SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null QRgb");
       //RETURN 0;
       return 0;
     }
  */
  arg1 = *argp1; 
  arg2 = *(bool **)&ok; 
  *(QRgb **)&cresult = new QRgb((const QRgb &)QColorDialog::getRgba(arg1,arg2));
  return cresult;
}


SWIGEXPORT QRgb GetRgba2(QRgb rgba) {
  QRgb arg1 ;
  QRgb *argp1 ;
  QRgb cresult ;
  
  argp1 = *(QRgb **)&rgba;
  /*
     if (!argp1) {
  //     SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null QRgb");
       //RETURN 0;
       return 0;
     }
  */
  arg1 = *argp1; 
  *(QRgb **)&cresult = new QRgb((const QRgb &)QColorDialog::getRgba(arg1));
  return cresult;
}


SWIGEXPORT QRgb GetRgba3() {
  QRgb cresult ;
  
  *(QRgb **)&cresult = new QRgb((const QRgb &)QColorDialog::getRgba());
  return cresult;
}


SWIGEXPORT int CustomCount() {
  int result;
  int cresult ;
  
  result = (int)QColorDialog::customCount();
  cresult = result; 
  return cresult;
}


SWIGEXPORT QRgb CustomColor(int index) {
  int arg1 ;
  QRgb cresult ;
  
  arg1 = (int)index; 
  *(QRgb **)&cresult = new QRgb((const QRgb &)QColorDialog::customColor(arg1));
  return cresult;
}


SWIGEXPORT void SetCustomColor(int index, QRgb color) {
  int arg1 ;
  QRgb arg2 ;
  QRgb *argp2 ;
  
  arg1 = (int)index; 
  argp2 = *(QRgb **)&color;
  /*
     if (!argp2) {
  //     SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null QRgb");
       //RETURN ;
       return ;
     }
  */
  arg2 = *argp2; 
  QColorDialog::setCustomColor(arg1,arg2);
}


SWIGEXPORT void SetStandardColor(int index, QRgb color) {
  int arg1 ;
  QRgb arg2 ;
  QRgb *argp2 ;
  
  arg1 = (int)index; 
  argp2 = *(QRgb **)&color;
  /*
     if (!argp2) {
  //     SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null QRgb");
       //RETURN ;
       return ;
     }
  */
  arg2 = *argp2; 
  QColorDialog::setStandardColor(arg1,arg2);
}


SWIGEXPORT long Modula3_QColorDialogToQDialog(long objectRef) {
    long baseptr = 0;
    *(QDialog **)&baseptr = *(QColorDialog **)&objectRef;
    return baseptr;
}

#ifdef __cplusplus
}
#endif

