/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGMODULA3


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif




#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#include <QtGui/qkeysequence.h>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT QKeySequence * New_QKeySequence0() {
  QKeySequence *result = 0 ;
  QKeySequence * cresult ;
  
  result = (QKeySequence *)new QKeySequence();
  *(QKeySequence **)&cresult = result; 
  return cresult;
}


SWIGEXPORT QKeySequence * New_QKeySequence1(QString * key) {
  QString *arg1 = 0 ;
  QKeySequence *result = 0 ;
  QKeySequence * cresult ;
  
  arg1 = *(QString **)&key;
  result = (QKeySequence *)new QKeySequence((QString const &)*arg1);
  *(QKeySequence **)&cresult = result; 
  return cresult;
}


SWIGEXPORT QKeySequence * New_QKeySequence2(int k1, int k2, int k3, int k4) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  QKeySequence *result = 0 ;
  QKeySequence * cresult ;
  
  arg1 = (int)k1; 
  arg2 = (int)k2; 
  arg3 = (int)k3; 
  arg4 = (int)k4; 
  result = (QKeySequence *)new QKeySequence(arg1,arg2,arg3,arg4);
  *(QKeySequence **)&cresult = result; 
  return cresult;
}


SWIGEXPORT QKeySequence * New_QKeySequence3(int k1, int k2, int k3) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  QKeySequence *result = 0 ;
  QKeySequence * cresult ;
  
  arg1 = (int)k1; 
  arg2 = (int)k2; 
  arg3 = (int)k3; 
  result = (QKeySequence *)new QKeySequence(arg1,arg2,arg3);
  *(QKeySequence **)&cresult = result; 
  return cresult;
}


SWIGEXPORT QKeySequence * New_QKeySequence4(int k1, int k2) {
  int arg1 ;
  int arg2 ;
  QKeySequence *result = 0 ;
  QKeySequence * cresult ;
  
  arg1 = (int)k1; 
  arg2 = (int)k2; 
  result = (QKeySequence *)new QKeySequence(arg1,arg2);
  *(QKeySequence **)&cresult = result; 
  return cresult;
}


SWIGEXPORT QKeySequence * New_QKeySequence5(int k1) {
  int arg1 ;
  QKeySequence *result = 0 ;
  QKeySequence * cresult ;
  
  arg1 = (int)k1; 
  result = (QKeySequence *)new QKeySequence(arg1);
  *(QKeySequence **)&cresult = result; 
  return cresult;
}


SWIGEXPORT QKeySequence * New_QKeySequence6(QKeySequence const & ks) {
  QKeySequence *arg1 = 0 ;
  QKeySequence *result = 0 ;
  QKeySequence * cresult ;
  
  arg1 = *(QKeySequence **)&ks;
  result = (QKeySequence *)new QKeySequence((QKeySequence const &)*arg1);
  *(QKeySequence **)&cresult = result; 
  return cresult;
}


SWIGEXPORT QKeySequence * New_QKeySequence7(QKeySequence::StandardKey key) {
  QKeySequence::StandardKey arg1 ;
  QKeySequence *result = 0 ;
  QKeySequence * cresult ;
  
  arg1 = (QKeySequence::StandardKey)key; 
  result = (QKeySequence *)new QKeySequence(arg1);
  *(QKeySequence **)&cresult = result; 
  return cresult;
}


SWIGEXPORT void Delete_QKeySequence(QKeySequence * self) {
  QKeySequence *arg1 = (QKeySequence *) 0 ;
  
  arg1 = *(QKeySequence **)&self; 
  delete arg1;
}


SWIGEXPORT unsigned int QKeySequence_count(QKeySequence const * self) {
  QKeySequence *arg1 = (QKeySequence *) 0 ;
  unsigned int result;
  unsigned int cresult ;
  
  arg1 = *(QKeySequence **)&self; 
  result = (unsigned int)((QKeySequence const *)arg1)->count();
  cresult = result; 
  return cresult;
}


SWIGEXPORT bool QKeySequence_isEmpty(QKeySequence const * self) {
  QKeySequence *arg1 = (QKeySequence *) 0 ;
  bool result;
  bool cresult ;
  
  arg1 = *(QKeySequence **)&self; 
  result = (bool)((QKeySequence const *)arg1)->isEmpty();
  cresult = result; 
  return cresult;
}


SWIGEXPORT QString * QKeySequence_toString(QKeySequence const * self, QKeySequence::SequenceFormat format) {
  QKeySequence *arg1 = (QKeySequence *) 0 ;
  QKeySequence::SequenceFormat arg2 ;
  QString * cresult ;
  
  arg1 = *(QKeySequence **)&self; 
  arg2 = (QKeySequence::SequenceFormat)format; 
  *(QString **)&cresult = new QString((const QString &)((QKeySequence const *)arg1)->toString(arg2));
  return cresult;
}


SWIGEXPORT QString * QKeySequence_toString1(QKeySequence const * self) {
  QKeySequence *arg1 = (QKeySequence *) 0 ;
  QString * cresult ;
  
  arg1 = *(QKeySequence **)&self; 
  *(QString **)&cresult = new QString((const QString &)((QKeySequence const *)arg1)->toString());
  return cresult;
}


SWIGEXPORT QKeySequence * FromString(QString * str, QKeySequence::SequenceFormat format) {
  QString *arg1 = 0 ;
  QKeySequence::SequenceFormat arg2 ;
  QKeySequence * cresult ;
  
  arg1 = *(QString **)&str;
  arg2 = (QKeySequence::SequenceFormat)format; 
  *(QKeySequence **)&cresult = new QKeySequence((const QKeySequence &)QKeySequence::fromString((QString const &)*arg1,arg2));
  return cresult;
}


SWIGEXPORT QKeySequence * FromString1(QString * str) {
  QString *arg1 = 0 ;
  QKeySequence * cresult ;
  
  arg1 = *(QString **)&str;
  *(QKeySequence **)&cresult = new QKeySequence((const QKeySequence &)QKeySequence::fromString((QString const &)*arg1));
  return cresult;
}


SWIGEXPORT QKeySequence::SequenceMatch QKeySequence_matches(QKeySequence const * self, QKeySequence const & seq) {
  QKeySequence *arg1 = (QKeySequence *) 0 ;
  QKeySequence *arg2 = 0 ;
  QKeySequence::SequenceMatch result;
  QKeySequence::SequenceMatch cresult ;
  
  arg1 = *(QKeySequence **)&self; 
  arg2 = *(QKeySequence **)&seq;
  result = (QKeySequence::SequenceMatch)((QKeySequence const *)arg1)->matches((QKeySequence const &)*arg2);
  cresult = result; 
  return cresult;
}


SWIGEXPORT QKeySequence * Mnemonic(QString * text) {
  QString *arg1 = 0 ;
  QKeySequence * cresult ;
  
  arg1 = *(QString **)&text;
  *(QKeySequence **)&cresult = new QKeySequence((const QKeySequence &)QKeySequence::mnemonic((QString const &)*arg1));
  return cresult;
}


SWIGEXPORT bool QKeySequence_isDetached(QKeySequence const * self) {
  QKeySequence *arg1 = (QKeySequence *) 0 ;
  bool result;
  bool cresult ;
  
  arg1 = *(QKeySequence **)&self; 
  result = (bool)((QKeySequence const *)arg1)->isDetached();
  cresult = result; 
  return cresult;
}


#ifdef __cplusplus
}
#endif

