(*******************************************************************************
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
*******************************************************************************)

INTERFACE QtListWidget;

FROM QtIcon IMPORT QIcon;
FROM QtSize IMPORT QSize;
FROM QtFont IMPORT QFont;
FROM QtColor IMPORT QColor;
FROM QtWidget IMPORT QWidget;
FROM QtBrush IMPORT QBrush;
FROM QtPoint IMPORT QPoint;
FROM QtNamespace IMPORT ItemFlags, CheckState, SortOrder;
FROM QtRect IMPORT QRect;
FROM QtAbstractItemView IMPORT ScrollHint;


FROM QtListView IMPORT QListView;

TYPE T = QListWidget;


CONST                            (* Enum ItemType *)
  Type     = 0;
  UserType = 1000;

TYPE                             (* Enum ItemType *)
  ItemType = [0 .. 1000];


TYPE
  QListWidgetItem <: QListWidgetItemPublic;
  QListWidgetItemPublic =
    BRANDED OBJECT
      cxxObj: ADDRESS;
    METHODS
      init_0 (view: QListWidget; type: INTEGER; ): QListWidgetItem;
      init_1 (view: QListWidget; ): QListWidgetItem;
      init_2 (): QListWidgetItem;
      init_3 (text: TEXT; view: QListWidget; type: INTEGER; ):
              QListWidgetItem;
      init_4 (text: TEXT; view: QListWidget; ): QListWidgetItem;
      init_5 (text: TEXT; ): QListWidgetItem;
      init_6 (icon: QIcon; text: TEXT; view: QListWidget; type: INTEGER; ):
              QListWidgetItem;
      init_7 (icon: QIcon; text: TEXT; view: QListWidget; ):
              QListWidgetItem;
      init_8             (icon: QIcon; text: TEXT; ): QListWidgetItem;
      init_9             (other: QListWidgetItem; ): QListWidgetItem;
      clone              (): QListWidgetItem; (* virtual *)
      listWidget         (): QListWidget;
      setSelected        (select: BOOLEAN; );
      isSelected         (): BOOLEAN;
      setHidden          (hide: BOOLEAN; );
      isHidden           (): BOOLEAN;
      flags              (): ItemFlags;
      setFlags           (flags: ItemFlags; );
      text               (): TEXT;
      setText            (text: TEXT; );
      icon               (): QIcon;
      setIcon            (icon: QIcon; );
      statusTip          (): TEXT;
      setStatusTip       (statusTip: TEXT; );
      toolTip            (): TEXT;
      setToolTip         (toolTip: TEXT; );
      whatsThis          (): TEXT;
      setWhatsThis       (whatsThis: TEXT; );
      font               (): QFont;
      setFont            (font: QFont; );
      textAlignment      (): INTEGER;
      setTextAlignment   (alignment: INTEGER; );
      backgroundColor    (): QColor;
      setBackgroundColor (color: QColor; ); (* virtual *)
      background         (): QBrush;
      setBackground      (brush: QBrush; );
      textColor          (): QColor;
      setTextColor       (color: QColor; );
      foreground         (): QBrush;
      setForeground      (brush: QBrush; );
      checkState         (): CheckState;
      setCheckState      (state: CheckState; );
      sizeHint           (): QSize;
      setSizeHint        (size: QSize; );
      type               (): INTEGER;
      destroyCxx         ();
    END;

  QListWidget <: QListWidgetPublic;
  QListWidgetPublic =
    QListView BRANDED OBJECT
    METHODS
      init_0                (parent: QWidget; ): QListWidget;
      init_1                (): QListWidget;
      item                  (row: INTEGER; ): QListWidgetItem;
      row                   (item: QListWidgetItem; ): INTEGER;
      insertItem            (row: INTEGER; item: QListWidgetItem; );
      insertItem1           (row: INTEGER; label: TEXT; );
      addItem               (label: TEXT; );
      addItem1              (item: QListWidgetItem; );
      takeItem              (row: INTEGER; ): QListWidgetItem;
      count                 (): INTEGER;
      currentItem           (): QListWidgetItem;
      currentRow            (): INTEGER;
      setCurrentRow         (row: INTEGER; );
      itemAt                (p: QPoint; ): QListWidgetItem;
      itemAt1               (x, y: INTEGER; ): QListWidgetItem;
      visualItemRect        (item: QListWidgetItem; ): QRect;
      sortItems             (order: SortOrder; );
      sortItems1            ();
      setSortingEnabled     (enable: BOOLEAN; );
      isSortingEnabled      (): BOOLEAN;
      editItem              (item: QListWidgetItem; );
      openPersistentEditor  (item: QListWidgetItem; );
      closePersistentEditor (item: QListWidgetItem; );
      itemWidget            (item: QListWidgetItem; ): QWidget;
      setItemWidget         (item: QListWidgetItem; widget: QWidget; );
      removeItemWidget      (item: QListWidgetItem; );
      isItemSelected        (item: QListWidgetItem; ): BOOLEAN;
      setItemSelected       (item: QListWidgetItem; select: BOOLEAN; );
      isItemHidden          (item: QListWidgetItem; ): BOOLEAN;
      setItemHidden         (item: QListWidgetItem; hide: BOOLEAN; );
      scrollToItem          (item: QListWidgetItem; hint: ScrollHint; );
      scrollToItem1         (item: QListWidgetItem; );
      clear                 ();
      destroyCxx            ();
    END;


END QtListWidget.
