% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Nov  9 15:14:29 PST 1994 by kalsow  

Interface  ("WinBaseTypes")
Module     ("WinDef")
Interface  ("WinError")
Module     ("WinNT")
Interface  ("WinBase")
Interface  ("WinCon")
Module     ("WinGDI")
Module     ("WinIoctl")
Interface  ("WinNetwk")
Interface  ("WinNLS")
Module     ("WinReg")
Module     ("WinUser")
Module     ("WinVer")
Module     ("NB30")
Interface  ("CDErr")
Interface  ("CommDlg")
Interface  ("TlHelp32")
