% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Nov  9 15:14:29 PST 1994 by kalsow  

% $Id$

if not equal (OS_TYPE, "WIN32") and not equal (TARGET, "NT386") and not equal (TARGET, "NT386GNU")

Interface  ("WinBaseTypes")
Module     ("WinDef")
Module     ("WinNT")

else

Interface  ("WinBaseTypes")
Module     ("WinDef")
Interface  ("WinError")
Module     ("WinNT")
Interface  ("WinBase")
Interface  ("WinCon")
Module     ("WinGDI")
Module     ("WinIoctl")
Interface  ("WinNetwk")
Interface  ("WinNLS")
Module     ("WinReg")
Module     ("WinSock")
Module     ("WinUser")
Module     ("WinVer")
Module     ("NB30")
Interface  ("CDErr")
Interface  ("CommDlg")
Interface  ("TlHelp32")

% New interfaces added March 2003 by darkov
Interface  ("WinMidi")
Interface  ("WinCommCtrl")
Module     ("WinTabCon")
Module     ("WinListView")
Module     ("WinImageList")

end