% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Nov  9 15:14:29 PST 1994 by kalsow  

Interface  ("WinBaseTypes")
Module     ("WinDef")
Module     ("WinNT")

Interface  ("WinError")
Interface  ("WinBase")
Interface  ("WinCon")
Module     ("WinGDI")
Module     ("WinIoctl")
Interface  ("WinNetwk")
Interface  ("WinNLS")
Module     ("WinReg")
Module     ("WinSock")
Module     ("WinUser")
Module     ("WinVer")
Module     ("NB30")
Interface  ("CDErr")
Interface  ("CommDlg")
Interface  ("TlHelp32")

% New interfaces added March 2003 by darkov
Interface  ("WinMidi")
Interface  ("WinCommCtrl")
Module     ("WinTabCon")
Module     ("WinListView")
Module     ("WinImageList")

%
% copied from cm3cfg.common
% Would prefer to update config files at start of build,
% and maintain compatibility there, not here.
%
proc InternalCheckTargetOS(x) is
  if defined("TARGET_OS")
    return equal(TARGET_OS, x)
  end
  error("config file (or cm3 executable) must define TARGET_OS")
  return FALSE
end

proc IsTargetCygwin()  is return InternalCheckTargetOS("CYGWIN") end
proc IsTargetNT()      is return InternalCheckTargetOS("NT") end

if IsTargetNT() or IsTargetCygwin()

c_source   ("WinNTc")
c_source   ("WinUserC")

end
