.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH CM3 1 08-May-2009 "CRITICAL MASS" "MODULA-3 PROGRAMMER'S MANUAL"
.SH  NAME
cm3\- Critical Mass Modula-3 Compiler
.SH SYNOPSIS
.B cm3
.RI [ options ]

./ ============ Description =========
.SH DESCRIPTION
The Critical Mass Modula-3 Compiler 
.B cm3
is a descendant of the Modula-3 compiler developed by 
Digital Equipment Corp. (DEC) Systems Research Center (SRC)
and Olivetti Corp.  
.B Cm3
was a component of a commercial product (Reactor) of Critical Mass.
When that company went out of business, Elego Software Solutions
acquired the rights to Reactor and its components.  
They released the Modula-3 compiler 
.B cm3
as an open source project, and currently support it by hosting
its web site.

.SS Expected Directory Structure
Each modula-3 software package has a root directory in which
certain files and directories may appear.  
The optional files
.IR m3makefile ", and " m3overrides 
may be placed in the root of the package directory.
All the source code should be in a directory named 
.IR src ,
and the compiler will place all generated object files, 
libraries, and exectuables in directories appropriate for the target
architecture, generating those directories in the 
package root directory if required.  
The 
.I src
directory may contain nested subdirectories further
organizing the source code.


./ ============ OPTIONS =========
.SH OPTIONS
./ ------------ MODE Options ---------
.SS Mode Options
.TP
.BI "\-build"
Compile and Link the entire project
.TP
.B "\-ship"
Install the package into the 
.B CM3_INSTALL_ROOT
directory tree.  
.B NOTE: 
This may require administrator priviledges.
.TP
.B "\-clean"
Delete derived files.
.TP
.B "\-realclean"
Delete entire derived target directory.
.TP
.B "\-find"
Locate source files.
.TP
.B "\-depend"
Generate package dependencies.

./ ------------ Compiler Options ---------
.SS Compiler Options
.TP
.B "\-gstabs+"
Produce symbol table information for the debugger.
.TP
.B "\-O"
Optimize the generated code.
.TP
.B "\-A"
Disable code generation for assertions.
.TP
.B "\-once"
Don't recompile to improve opaque object code
.TP
.B "\-w0 ... \-w3"
Limit the compiler warning messages.
.TP
.B "\-Z"
Generate coverage analysis code.
.TP
.B "\-profile"
Generate profiling code.
.TP
.B "\-lazy"
Generate lazy module initialization code.
.TP
.B "\-linkall"
Generate module initialization code for all modules, even those that
are not imported directly or indirectly by Main.  
This is currently experimental and does not always work as expected.

./ ------------ Program and Library Options ---------
.SS Program and Library Options
.TP
.B "\-c"
Compile only, do not link or produce a program executable or library.
.TP
.BI "\-a" " <foo>"
Build a library named foo.
.TP
.BI "\-o" " <foo>"
Build program named foo.
.TP
.B "\-skiplink"
Skip the final link step.

./ ------------ Message Options ---------
.SS Message Options
.TP
.BI "\-?"
Print a short help message.
.TP
.BI "\-silent"
Produce no diagnostic output.
.TP
.BI "\-why"
Explain why code is being recompiled.
.TP
.BI "\-commands"
List system commands as they are performed.
.TP
.BI "\-verbose"
List internal steps as they are performed.
.TP
.BI "\-debug"
Dump internal debugging information.
.TP
.BI "\-trace"
Trace quake code execution.

./ ------------ Information & Help Options ---------
.SS Information and Help Options
.TP
.B "\-help"
Print a short help message.
.TP
.B "\-?"
See \-help.
.TP
.B "\-version"
Print the compiler's version information and exit.
.TP
.B "\-config"
Print the compiler's version information and exit.

./ ------------ Miscellaneous Options ---------
.SS Miscellaneous Options
.TP
.B "\-keep"
Preserve intermediate and temporary files.
.TP
.B "\-times"
Produce a dump of elapsed times.
.TP
.B "\-override"
Include the "m3overrides" file.
.TP
.B "\-x"
Include the "m3overrides" file. (see 
.B \-override 
) above.
.TP
.BI "\-D" <symbol>
Define <symbol> with the value TRUE.
.TP
.BI "\-D" "<symbol>=<value>"
Define <symbol> with the supplied <value>.
.TP
.BI "\-F" " <fn>"
Prepend the quake code of file <fn>.
.TP
.BI "\-FP" " <fn>"
Prepend the quake code of file <fn>.
.TP
.B "\-prepend" " <fn>"
Prepend the quake code of file <fn>.
.TP
.BI "\-FA" " <fn>"
Append the quake code of file <fn>.
.TP
.BI "\-append" " <fn>"
Append the quake code of file <fn>.
.TP
.B "\-console"
Produce a MS-Windows CONSOLE subsystem program.
.TP
.B "\-gui"
Produce a MS-Windows GUI subsystem program.
.TP
.B "\-windows"
Produce a MS-Windows GUI subsystem program.
.TP
.BI "\-pretend" " <version>"
Pretend to run CM3 as if it were 
.IR <version> .
.TP
.B "\-no-m3ship-resolution"
Use quake variables in .M3SHIP files (experimental).
.TP
.B "\-group-writable"
Use group-writable file modes in quake installation procedures.

./ ============ EXIT STATUS =========
.SH EXIT STATUS

./ ============ ENVIRONMENT STATUS =========
.SH ENVIRONMENT
.TP
.B CM3_INSTALL_PREFIX
is the path prefix prepended to files being installed.  
This is similar to the behavior "make DESTDIR=${prefix}".
Use this when creating a software distribution package.
.TP
.B M3CONFIG
Platform dependent configuration file to use.  
By default this is
.IR cm3.cfg .
.TP
.B QUAKE_SHELL
Shell to be used by the quake interpreter for 
.BR exec (2).
.TP
.B QUAKE_SHELL_OPTION
Command option for the quake shell (eg., -c, or /c).
.TP
.B QUAKE_TMPDIR
The directory for temporary files used by quake.


./ ============ ENVIRONMENT STATUS =========
.SH FILES
The
.BI m3makefile (7). 
is a text file read by
.BR cm3 .
It describes any special actions needed to build or ship the
software package.  This can include linking against specified
libraries, creating documentation, or a number of other actions.

The 
.BI m3overrides (7)
file is used to stop a package from linking against the normal
cm3 system libraries, but rather use the libraries listed in this file.

./ ============ VERSIONS =========
.SH VERSIONS
The version of 
.B cm3
herein described is 5.7.1

./ ============ CONFORMING TO =========
.SH CONFORMING TO
.B cm3
conforms to DEC-SRC Research Report 52, with several additional features.
.SS Deviations
.TP
.B TEXT
The text object in which constant strings are stored, may contain 
.B unicode
characters, if no unicode characters are used, then only ASCII ones
will be used.
.TP
.B WIDECHAR
In support of unicode characters this new builtin type is a character
with ORD(LAST(WIDECHAR)) = 16_10FFFF, and may be used by TEXT.

.TP
.B LONGINT
The LONGINT type is an additional builtin type, and is a signed
integral type with 64 bits.

./ ============ NOTES =========
./ .SH NOTES
./ ============ BUGS =========
.SH BUGS
Probably too many to count.

./ ============ SEE ALSO =========
.SH SEE ALSO
.SS Websites
.TP
.URL http://www.opencm3.net/ "The Free Critical Mass website" .
.TP
.URL http://www.modula3.org/ "Modula-3 Resource Page" .
.TP
.URL http://en.wikipedia.org/wiki/Modula-3 "Wikipedias Modula-3 Entry" .

.SS Manual Pages
.BI modula3 (7).
.PP
.BI modula3 (7), m3makefile (7), m3overrides (7).
.SS Books
"Modula-3", Samual Harbison
.PP
"Systems Programming with Modula-3", Greg Nelson.
.PP
"Algorithms in MODULA-3", Robert Sedgewick

./ ============ AUTHOR =========
.SH AUTHOR
Peter. P. Eiserloh (eiserlohpp -at- yahoo.com)
