
XXDIR = { "WIN32" : "N:\\m3-sys", "POSIX" : "/proj/cmass/src.2/m3-sys" }
WORKDIR = XXDIR {OS_TYPE}

override ("m3middle",  WORKDIR)
override ("m3front",   WORKDIR)
override ("m3linker",  WORKDIR)
override ("m3back",    WORKDIR)
override ("m3objfile", WORKDIR)
override ("m3quake",   WORKDIR)
override ("cmkey",     WORKDIR)
