
import("libm3")
import("m3quake")

%import("m3fix")
import("fileinfo")
import("sysutils")
import("pkgversions")
import("compactrc")
%import("pkg_base")

Module("OpResultCache")
%interface("Process2")  %% for debugging on OS2unix
%implementation("ProcessPosixOS2") %% for debugging on OS2unix
Interface("FileRevision")
Sequence("FileRevision", "FileRevision")
Module("FileObj")
Interface("VCIF")
Interface("CVS")
Interface("CVSLockInfo")
Sequence("CVSLockInfo", "CVSLockInfo")
Table("TextLockInfo", "Text", "CVSLockInfoSeq")
%implementation("CVS") %% implementation using nullRd threads
implementation("CVS_st") %% implementation using null device (single threaded)
Module("PkgVC")
Module("VCUtils")
Module("PkgVCUtils")
Library("pkg_vc")
