% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Fri Jun  9 13:14:37 PDT 1995 by najork
%      modified on Tue Dec 21 14:41:55 PST 1993 by kalsow
%

if equal (TARGET, "NT386")
  override ("ui", "..\\..")
end

import ("ui")

implementation ("Main")
Program ("Test30")
