% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Fri Sep 10 14:33:36 PDT 1993 by muller

Interface ("Csetjmp")
Interface ("Cstdio")
Interface ("Cstring")

