MODULE Not;
<*NOWARN*>IMPORT Cstdint, Word, Long;

(* define some types *)

<*NOWARN*>TYPE FLOAT32 = REAL;
<*NOWARN*>TYPE FLOAT64 = LONGREAL;
<*NOWARN*>TYPE INT8 = Cstdint.int8_t;
<*NOWARN*>TYPE UINT64 = Cstdint.uint64_t;
<*NOWARN*>TYPE INT32 = Cstdint.int32_t;
<*NOWARN*>TYPE UINT16 = Cstdint.uint16_t;
<*NOWARN*>TYPE INT64 = Cstdint.int64_t;
<*NOWARN*>TYPE INT16 = Cstdint.int16_t;
<*NOWARN*>TYPE UINT32 = Cstdint.uint32_t;
<*NOWARN*>TYPE UINT8 = Cstdint.uint8_t;

(* constants *)

<*NOWARN*> CONST ki8:INT8=577;
<*NOWARN*> CONST ku64:UINT64=578L;
<*NOWARN*> CONST kf64:FLOAT64=579.580d0;
<*NOWARN*> CONST ki32:INT32=581;
<*NOWARN*> CONST kLC:LONGCARD=582L;
<*NOWARN*> CONST ku16:UINT16=583;
<*NOWARN*> CONST kI:INTEGER=584;
<*NOWARN*> CONST ki64:INT64=585L;
<*NOWARN*> CONST kf32:FLOAT32=586.587e0;
<*NOWARN*> CONST ki16:INT16=588;
<*NOWARN*> CONST kC:CARDINAL=589;
<*NOWARN*> CONST ku32:UINT32=590;
<*NOWARN*> CONST ku8:UINT8=591;
<*NOWARN*> CONST kL:LONGINT=592L;

(* variables *)

<*NOWARN*> VAR vi8:INT8:=593;
<*NOWARN*> VAR vu64:UINT64:=594L;
<*NOWARN*> VAR vf64:FLOAT64:=595.596d0;
<*NOWARN*> VAR vi32:INT32:=597;
<*NOWARN*> VAR vLC:LONGCARD:=598L;
<*NOWARN*> VAR vu16:UINT16:=599;
<*NOWARN*> VAR vI:INTEGER:=600;
<*NOWARN*> VAR vi64:INT64:=601L;
<*NOWARN*> VAR vf32:FLOAT32:=602.603e0;
<*NOWARN*> VAR vi16:INT16:=604;
<*NOWARN*> VAR vC:CARDINAL:=605;
<*NOWARN*> VAR vu32:UINT32:=606;
<*NOWARN*> VAR vu8:UINT8:=607;
<*NOWARN*> VAR vL:LONGINT:=608L;
<*NOWARN*>VAR offset, count:CARDINAL;

(* Not *)

<*NOWARN*>PROCEDURE uNot_var_i8_i8():Word.T=BEGIN RETURN Word.Not(vi8);END uNot_var_i8_i8;
<*NOWARN*>PROCEDURE Not_var_i8_i8():INT8=BEGIN RETURN - vi8;END Not_var_i8_i8;
<*NOWARN*>PROCEDURE uNot_param_i8_i8(a:INT8;b:INT8):Word.T=BEGIN RETURN Word.Not(a);END uNot_param_i8_i8;
<*NOWARN*>PROCEDURE Not_param_i8_i8(a:INT8;b:INT8):INT8=BEGIN RETURN - b;END Not_param_i8_i8;
<*NOWARN*>PROCEDURE uNot_var_u64_u64():Long.T=BEGIN RETURN Long.Not(vu64);END uNot_var_u64_u64;
<*NOWARN*>PROCEDURE Not_var_u64_u64():LONGINT=BEGIN RETURN - vu64;END Not_var_u64_u64;
<*NOWARN*>PROCEDURE uNot_param_u64_u64(a:UINT64;b:UINT64):Long.T=BEGIN RETURN Long.Not(a);END uNot_param_u64_u64;
<*NOWARN*>PROCEDURE Not_param_u64_u64(a:UINT64;b:UINT64):LONGINT=BEGIN RETURN - b;END Not_param_u64_u64;
<*NOWARN*>PROCEDURE Not_var_f64_f64():FLOAT64=BEGIN RETURN - vf64;END Not_var_f64_f64;
<*NOWARN*>PROCEDURE Not_param_f64_f64(a:FLOAT64;b:FLOAT64):FLOAT64=BEGIN RETURN - b;END Not_param_f64_f64;
<*NOWARN*>PROCEDURE uNot_var_i32_i32():Word.T=BEGIN RETURN Word.Not(vi32);END uNot_var_i32_i32;
<*NOWARN*>PROCEDURE Not_var_i32_i32():INT32=BEGIN RETURN - vi32;END Not_var_i32_i32;
<*NOWARN*>PROCEDURE uNot_param_i32_i32(a:INT32;b:INT32):Word.T=BEGIN RETURN Word.Not(a);END uNot_param_i32_i32;
<*NOWARN*>PROCEDURE Not_param_i32_i32(a:INT32;b:INT32):INT32=BEGIN RETURN - b;END Not_param_i32_i32;
<*NOWARN*>PROCEDURE uNot_var_LC_LC():Long.T=BEGIN RETURN Long.Not(vLC);END uNot_var_LC_LC;
<*NOWARN*>PROCEDURE Not_var_LC_LC():LONGINT=BEGIN RETURN - vLC;END Not_var_LC_LC;
<*NOWARN*>PROCEDURE uNot_param_LC_LC(a:LONGCARD;b:LONGCARD):Long.T=BEGIN RETURN Long.Not(a);END uNot_param_LC_LC;
<*NOWARN*>PROCEDURE Not_param_LC_LC(a:LONGCARD;b:LONGCARD):LONGINT=BEGIN RETURN - b;END Not_param_LC_LC;
<*NOWARN*>PROCEDURE uNot_var_u16_u16():Word.T=BEGIN RETURN Word.Not(vu16);END uNot_var_u16_u16;
<*NOWARN*>PROCEDURE Not_var_u16_u16():UINT16=BEGIN RETURN - vu16;END Not_var_u16_u16;
<*NOWARN*>PROCEDURE uNot_param_u16_u16(a:UINT16;b:UINT16):Word.T=BEGIN RETURN Word.Not(a);END uNot_param_u16_u16;
<*NOWARN*>PROCEDURE Not_param_u16_u16(a:UINT16;b:UINT16):UINT16=BEGIN RETURN - b;END Not_param_u16_u16;
<*NOWARN*>PROCEDURE uNot_var_I_I():Word.T=BEGIN RETURN Word.Not(vI);END uNot_var_I_I;
<*NOWARN*>PROCEDURE Not_var_I_I():INTEGER=BEGIN RETURN - vI;END Not_var_I_I;
<*NOWARN*>PROCEDURE uNot_param_I_I(a:INTEGER;b:INTEGER):Word.T=BEGIN RETURN Word.Not(a);END uNot_param_I_I;
<*NOWARN*>PROCEDURE Not_param_I_I(a:INTEGER;b:INTEGER):INTEGER=BEGIN RETURN - b;END Not_param_I_I;
<*NOWARN*>PROCEDURE uNot_var_i64_i64():Long.T=BEGIN RETURN Long.Not(vi64);END uNot_var_i64_i64;
<*NOWARN*>PROCEDURE Not_var_i64_i64():LONGINT=BEGIN RETURN - vi64;END Not_var_i64_i64;
<*NOWARN*>PROCEDURE uNot_param_i64_i64(a:INT64;b:INT64):Long.T=BEGIN RETURN Long.Not(a);END uNot_param_i64_i64;
<*NOWARN*>PROCEDURE Not_param_i64_i64(a:INT64;b:INT64):LONGINT=BEGIN RETURN - b;END Not_param_i64_i64;
<*NOWARN*>PROCEDURE Not_var_f32_f32():FLOAT32=BEGIN RETURN - vf32;END Not_var_f32_f32;
<*NOWARN*>PROCEDURE Not_param_f32_f32(a:FLOAT32;b:FLOAT32):FLOAT32=BEGIN RETURN - b;END Not_param_f32_f32;
<*NOWARN*>PROCEDURE uNot_var_i16_i16():Word.T=BEGIN RETURN Word.Not(vi16);END uNot_var_i16_i16;
<*NOWARN*>PROCEDURE Not_var_i16_i16():INT16=BEGIN RETURN - vi16;END Not_var_i16_i16;
<*NOWARN*>PROCEDURE uNot_param_i16_i16(a:INT16;b:INT16):Word.T=BEGIN RETURN Word.Not(a);END uNot_param_i16_i16;
<*NOWARN*>PROCEDURE Not_param_i16_i16(a:INT16;b:INT16):INT16=BEGIN RETURN - b;END Not_param_i16_i16;
<*NOWARN*>PROCEDURE uNot_var_C_C():Word.T=BEGIN RETURN Word.Not(vC);END uNot_var_C_C;
<*NOWARN*>PROCEDURE Not_var_C_C():CARDINAL=BEGIN RETURN - vC;END Not_var_C_C;
<*NOWARN*>PROCEDURE uNot_param_C_C(a:CARDINAL;b:CARDINAL):Word.T=BEGIN RETURN Word.Not(a);END uNot_param_C_C;
<*NOWARN*>PROCEDURE Not_param_C_C(a:CARDINAL;b:CARDINAL):CARDINAL=BEGIN RETURN - b;END Not_param_C_C;
<*NOWARN*>PROCEDURE uNot_var_u32_u32():Word.T=BEGIN RETURN Word.Not(vu32);END uNot_var_u32_u32;
<*NOWARN*>PROCEDURE Not_var_u32_u32():UINT32=BEGIN RETURN - vu32;END Not_var_u32_u32;
<*NOWARN*>PROCEDURE uNot_param_u32_u32(a:UINT32;b:UINT32):Word.T=BEGIN RETURN Word.Not(a);END uNot_param_u32_u32;
<*NOWARN*>PROCEDURE Not_param_u32_u32(a:UINT32;b:UINT32):UINT32=BEGIN RETURN - b;END Not_param_u32_u32;
<*NOWARN*>PROCEDURE uNot_var_u8_u8():Word.T=BEGIN RETURN Word.Not(vu8);END uNot_var_u8_u8;
<*NOWARN*>PROCEDURE Not_var_u8_u8():UINT8=BEGIN RETURN - vu8;END Not_var_u8_u8;
<*NOWARN*>PROCEDURE uNot_param_u8_u8(a:UINT8;b:UINT8):Word.T=BEGIN RETURN Word.Not(a);END uNot_param_u8_u8;
<*NOWARN*>PROCEDURE Not_param_u8_u8(a:UINT8;b:UINT8):UINT8=BEGIN RETURN - b;END Not_param_u8_u8;
<*NOWARN*>PROCEDURE uNot_var_L_L():Long.T=BEGIN RETURN Long.Not(vL);END uNot_var_L_L;
<*NOWARN*>PROCEDURE Not_var_L_L():LONGINT=BEGIN RETURN - vL;END Not_var_L_L;
<*NOWARN*>PROCEDURE uNot_param_L_L(a:LONGINT;b:LONGINT):Long.T=BEGIN RETURN Long.Not(a);END uNot_param_L_L;
<*NOWARN*>PROCEDURE Not_param_L_L(a:LONGINT;b:LONGINT):LONGINT=BEGIN RETURN - b;END Not_param_L_L;
BEGIN
END Not.
