MODULE return_parameter;
<*NOWARN*>IMPORT Cstdint, Word, Long;

(* define some types *)

<*NOWARN*>TYPE FLOAT32 = REAL;
<*NOWARN*>TYPE FLOAT64 = LONGREAL;
<*NOWARN*>TYPE INT8 = Cstdint.int8_t;
<*NOWARN*>TYPE UINT64 = Cstdint.uint64_t;
<*NOWARN*>TYPE INT32 = Cstdint.int32_t;
<*NOWARN*>TYPE UINT16 = Cstdint.uint16_t;
<*NOWARN*>TYPE INT64 = Cstdint.int64_t;
<*NOWARN*>TYPE INT16 = Cstdint.int16_t;
<*NOWARN*>TYPE UINT32 = Cstdint.uint32_t;
<*NOWARN*>TYPE UINT8 = Cstdint.uint8_t;

(* constants *)

<*NOWARN*> CONST ki8:INT8=65;
<*NOWARN*> CONST ku64:UINT64=66L;
<*NOWARN*> CONST kf64:FLOAT64=67.68d0;
<*NOWARN*> CONST ki32:INT32=69;
<*NOWARN*> CONST kLC:LONGCARD=70L;
<*NOWARN*> CONST ku16:UINT16=71;
<*NOWARN*> CONST kI:INTEGER=72;
<*NOWARN*> CONST ki64:INT64=73L;
<*NOWARN*> CONST kf32:FLOAT32=74.75e0;
<*NOWARN*> CONST ki16:INT16=76;
<*NOWARN*> CONST kC:CARDINAL=77;
<*NOWARN*> CONST ku32:UINT32=78;
<*NOWARN*> CONST ku8:UINT8=79;
<*NOWARN*> CONST kL:LONGINT=80L;

(* variables *)

<*NOWARN*> VAR vi8:INT8:=81;
<*NOWARN*> VAR vu64:UINT64:=82L;
<*NOWARN*> VAR vf64:FLOAT64:=83.84d0;
<*NOWARN*> VAR vi32:INT32:=85;
<*NOWARN*> VAR vLC:LONGCARD:=86L;
<*NOWARN*> VAR vu16:UINT16:=87;
<*NOWARN*> VAR vI:INTEGER:=88;
<*NOWARN*> VAR vi64:INT64:=89L;
<*NOWARN*> VAR vf32:FLOAT32:=90.91e0;
<*NOWARN*> VAR vi16:INT16:=92;
<*NOWARN*> VAR vC:CARDINAL:=93;
<*NOWARN*> VAR vu32:UINT32:=94;
<*NOWARN*> VAR vu8:UINT8:=95;
<*NOWARN*> VAR vL:LONGINT:=96L;
<*NOWARN*>VAR offset, count:CARDINAL;

(* functions that return parameters *)

<*NOWARN*>PROCEDURE ret_pi8(p:INT8):INT8=BEGIN RETURN p;END ret_pi8;
<*NOWARN*>PROCEDURE ret_pu64(p:UINT64):UINT64=BEGIN RETURN p;END ret_pu64;
<*NOWARN*>PROCEDURE ret_pf64(p:FLOAT64):FLOAT64=BEGIN RETURN p;END ret_pf64;
<*NOWARN*>PROCEDURE ret_pi32(p:INT32):INT32=BEGIN RETURN p;END ret_pi32;
<*NOWARN*>PROCEDURE ret_pLC(p:LONGCARD):LONGCARD=BEGIN RETURN p;END ret_pLC;
<*NOWARN*>PROCEDURE ret_pu16(p:UINT16):UINT16=BEGIN RETURN p;END ret_pu16;
<*NOWARN*>PROCEDURE ret_pI(p:INTEGER):INTEGER=BEGIN RETURN p;END ret_pI;
<*NOWARN*>PROCEDURE ret_pi64(p:INT64):INT64=BEGIN RETURN p;END ret_pi64;
<*NOWARN*>PROCEDURE ret_pf32(p:FLOAT32):FLOAT32=BEGIN RETURN p;END ret_pf32;
<*NOWARN*>PROCEDURE ret_pi16(p:INT16):INT16=BEGIN RETURN p;END ret_pi16;
<*NOWARN*>PROCEDURE ret_pC(p:CARDINAL):CARDINAL=BEGIN RETURN p;END ret_pC;
<*NOWARN*>PROCEDURE ret_pu32(p:UINT32):UINT32=BEGIN RETURN p;END ret_pu32;
<*NOWARN*>PROCEDURE ret_pu8(p:UINT8):UINT8=BEGIN RETURN p;END ret_pu8;
<*NOWARN*>PROCEDURE ret_pL(p:LONGINT):LONGINT=BEGIN RETURN p;END ret_pL;
BEGIN
END return_parameter.
