MODULE return_constant;
<*NOWARN*>IMPORT Cstdint, Word, Long;

(* define some types *)

<*NOWARN*>TYPE FLOAT32 = REAL;
<*NOWARN*>TYPE FLOAT64 = LONGREAL;
<*NOWARN*>TYPE INT8 = Cstdint.int8_t;
<*NOWARN*>TYPE UINT64 = Cstdint.uint64_t;
<*NOWARN*>TYPE INT32 = Cstdint.int32_t;
<*NOWARN*>TYPE UINT16 = Cstdint.uint16_t;
<*NOWARN*>TYPE INT64 = Cstdint.int64_t;
<*NOWARN*>TYPE INT16 = Cstdint.int16_t;
<*NOWARN*>TYPE UINT32 = Cstdint.uint32_t;
<*NOWARN*>TYPE UINT8 = Cstdint.uint8_t;

(* constants *)

<*NOWARN*> CONST ki8:INT8=1;
<*NOWARN*> CONST ku64:UINT64=2L;
<*NOWARN*> CONST kf64:FLOAT64=3.4d0;
<*NOWARN*> CONST ki32:INT32=5;
<*NOWARN*> CONST kLC:LONGCARD=6L;
<*NOWARN*> CONST ku16:UINT16=7;
<*NOWARN*> CONST kI:INTEGER=8;
<*NOWARN*> CONST ki64:INT64=9L;
<*NOWARN*> CONST kf32:FLOAT32=10.11e0;
<*NOWARN*> CONST ki16:INT16=12;
<*NOWARN*> CONST kC:CARDINAL=13;
<*NOWARN*> CONST ku32:UINT32=14;
<*NOWARN*> CONST ku8:UINT8=15;
<*NOWARN*> CONST kL:LONGINT=16L;

(* variables *)

<*NOWARN*> VAR vi8:INT8:=17;
<*NOWARN*> VAR vu64:UINT64:=18L;
<*NOWARN*> VAR vf64:FLOAT64:=19.20d0;
<*NOWARN*> VAR vi32:INT32:=21;
<*NOWARN*> VAR vLC:LONGCARD:=22L;
<*NOWARN*> VAR vu16:UINT16:=23;
<*NOWARN*> VAR vI:INTEGER:=24;
<*NOWARN*> VAR vi64:INT64:=25L;
<*NOWARN*> VAR vf32:FLOAT32:=26.27e0;
<*NOWARN*> VAR vi16:INT16:=28;
<*NOWARN*> VAR vC:CARDINAL:=29;
<*NOWARN*> VAR vu32:UINT32:=30;
<*NOWARN*> VAR vu8:UINT8:=31;
<*NOWARN*> VAR vL:LONGINT:=32L;
<*NOWARN*>VAR offset, count:CARDINAL;

(* functions that return constants *)

<*NOWARN*>PROCEDURE ret_ki8():INT8=BEGIN RETURN ki8;END ret_ki8;
<*NOWARN*>PROCEDURE ret_ku64():UINT64=BEGIN RETURN ku64;END ret_ku64;
<*NOWARN*>PROCEDURE ret_kf64():FLOAT64=BEGIN RETURN kf64;END ret_kf64;
<*NOWARN*>PROCEDURE ret_ki32():INT32=BEGIN RETURN ki32;END ret_ki32;
<*NOWARN*>PROCEDURE ret_kLC():LONGCARD=BEGIN RETURN kLC;END ret_kLC;
<*NOWARN*>PROCEDURE ret_ku16():UINT16=BEGIN RETURN ku16;END ret_ku16;
<*NOWARN*>PROCEDURE ret_kI():INTEGER=BEGIN RETURN kI;END ret_kI;
<*NOWARN*>PROCEDURE ret_ki64():INT64=BEGIN RETURN ki64;END ret_ki64;
<*NOWARN*>PROCEDURE ret_kf32():FLOAT32=BEGIN RETURN kf32;END ret_kf32;
<*NOWARN*>PROCEDURE ret_ki16():INT16=BEGIN RETURN ki16;END ret_ki16;
<*NOWARN*>PROCEDURE ret_kC():CARDINAL=BEGIN RETURN kC;END ret_kC;
<*NOWARN*>PROCEDURE ret_ku32():UINT32=BEGIN RETURN ku32;END ret_ku32;
<*NOWARN*>PROCEDURE ret_ku8():UINT8=BEGIN RETURN ku8;END ret_ku8;
<*NOWARN*>PROCEDURE ret_kL():LONGINT=BEGIN RETURN kL;END ret_kL;
BEGIN
END return_constant.
