MODULE return_variable;
<*NOWARN*>IMPORT Cstdint, Word, Long;

(* define some types *)

<*NOWARN*>TYPE FLOAT32 = REAL;
<*NOWARN*>TYPE FLOAT64 = LONGREAL;
<*NOWARN*>TYPE INT8 = Cstdint.int8_t;
<*NOWARN*>TYPE UINT64 = Cstdint.uint64_t;
<*NOWARN*>TYPE INT32 = Cstdint.int32_t;
<*NOWARN*>TYPE UINT16 = Cstdint.uint16_t;
<*NOWARN*>TYPE INT64 = Cstdint.int64_t;
<*NOWARN*>TYPE INT16 = Cstdint.int16_t;
<*NOWARN*>TYPE UINT32 = Cstdint.uint32_t;
<*NOWARN*>TYPE UINT8 = Cstdint.uint8_t;

(* constants *)

<*NOWARN*> CONST ki8:INT8=33;
<*NOWARN*> CONST ku64:UINT64=34L;
<*NOWARN*> CONST kf64:FLOAT64=35.36d0;
<*NOWARN*> CONST ki32:INT32=37;
<*NOWARN*> CONST kLC:LONGCARD=38L;
<*NOWARN*> CONST ku16:UINT16=39;
<*NOWARN*> CONST kI:INTEGER=40;
<*NOWARN*> CONST ki64:INT64=41L;
<*NOWARN*> CONST kf32:FLOAT32=42.43e0;
<*NOWARN*> CONST ki16:INT16=44;
<*NOWARN*> CONST kC:CARDINAL=45;
<*NOWARN*> CONST ku32:UINT32=46;
<*NOWARN*> CONST ku8:UINT8=47;
<*NOWARN*> CONST kL:LONGINT=48L;

(* variables *)

<*NOWARN*> VAR vi8:INT8:=49;
<*NOWARN*> VAR vu64:UINT64:=50L;
<*NOWARN*> VAR vf64:FLOAT64:=51.52d0;
<*NOWARN*> VAR vi32:INT32:=53;
<*NOWARN*> VAR vLC:LONGCARD:=54L;
<*NOWARN*> VAR vu16:UINT16:=55;
<*NOWARN*> VAR vI:INTEGER:=56;
<*NOWARN*> VAR vi64:INT64:=57L;
<*NOWARN*> VAR vf32:FLOAT32:=58.59e0;
<*NOWARN*> VAR vi16:INT16:=60;
<*NOWARN*> VAR vC:CARDINAL:=61;
<*NOWARN*> VAR vu32:UINT32:=62;
<*NOWARN*> VAR vu8:UINT8:=63;
<*NOWARN*> VAR vL:LONGINT:=64L;
<*NOWARN*>VAR offset, count:CARDINAL;

(* functions that return variables *)

<*NOWARN*>PROCEDURE ret_vi8():INT8=BEGIN RETURN vi8;END ret_vi8;
<*NOWARN*>PROCEDURE ret_vu64():UINT64=BEGIN RETURN vu64;END ret_vu64;
<*NOWARN*>PROCEDURE ret_vf64():FLOAT64=BEGIN RETURN vf64;END ret_vf64;
<*NOWARN*>PROCEDURE ret_vi32():INT32=BEGIN RETURN vi32;END ret_vi32;
<*NOWARN*>PROCEDURE ret_vLC():LONGCARD=BEGIN RETURN vLC;END ret_vLC;
<*NOWARN*>PROCEDURE ret_vu16():UINT16=BEGIN RETURN vu16;END ret_vu16;
<*NOWARN*>PROCEDURE ret_vI():INTEGER=BEGIN RETURN vI;END ret_vI;
<*NOWARN*>PROCEDURE ret_vi64():INT64=BEGIN RETURN vi64;END ret_vi64;
<*NOWARN*>PROCEDURE ret_vf32():FLOAT32=BEGIN RETURN vf32;END ret_vf32;
<*NOWARN*>PROCEDURE ret_vi16():INT16=BEGIN RETURN vi16;END ret_vi16;
<*NOWARN*>PROCEDURE ret_vC():CARDINAL=BEGIN RETURN vC;END ret_vC;
<*NOWARN*>PROCEDURE ret_vu32():UINT32=BEGIN RETURN vu32;END ret_vu32;
<*NOWARN*>PROCEDURE ret_vu8():UINT8=BEGIN RETURN vu8;END ret_vu8;
<*NOWARN*>PROCEDURE ret_vL():LONGINT=BEGIN RETURN vL;END ret_vL;
BEGIN
END return_variable.
