/* Copyright (C) 1993, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Thu May  6 09:33:00 PDT 1993 by mjordan                  */

include_dir ("Common")
include_dir (OS_TYPE)
