% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Makefile for netobj test program
% Last modified on Mon Dec 20 14:14:04 PST 1993 by kalsow
%      modified on Tue Aug 24 17:03:14 PDT 1993 by wobber

import("netobj")
import("libm3")

Interface ("SharedObj")
Module ("SharedObjRep")

Interface ("ObjectSpace")
Module ("WeakerRef")

List	 ("WeakRef", "WeakerRef")
%ListFuncs ("WeakRef", "WeakerRef", "WeakRefList")

netobj("ObjectSpace", "T")
% won't generate it properly with the field
%    callbacks: WeakRefList.T := NIL;
% in the SharedObjRep.T
%Module   ("ObjectSpace_T_v1")

Library("testnetobj")

