% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Mar 23 14:09:14 1994 by luca      
%      modified on Wed Dec 22 15:43:58 PST 1993 by kalsow

import("obliqlibm3")
import("obliqlibui")
import("obliqlibanim")
import("obliq")
implementation("Main")

Program("obliq-anim")
ManPage("obliq-anim","1")
