/* Copyright (C) 1995, Digital Equipment Corporation                         */
/* Digital Internal Use Only                                                 */
/* All rights reserved.                                                      */
/*                                                                           */
/* Last modified on Wed Jun 28 18:42:36 PDT 1995 by najork                   */
/*       Created on Sat Jun 10 17:56:47 PDT 1995 by najork                   */


if equal (TARGET, "NT386")
  override ("ui", "..\\..")
end

import ("ui")

implementation ("Main")
Program ("Test19")
