Interface("ProcessSplit")
implementation("ProcessSplitList")
%implementation("ProcessSplitPQ")
%implementation("ProcessSplitSeq")
Module("ProcessMultiOutput")

include_dir("oscillator")

Module("ProcessWhiteNoise")


% time modulations
Module("ProcessDelay")
Module("ProcessPhaseModulation")
Module("ProcessFrequencyModulation")
Module("ProcessReverse")

% control curves
Module("ProcessLinear")
Module("ProcessExponential")

% mixer
Module("ProcessMixer")

% cut
Module("ProcessClip")
Module("ProcessConcat")

% filters
Module("ProcessAmplifier")
Module("ProcessLowPass")
Module("ProcessComplexLowPass")
Module("ProcessStateVariableFilter")
Module("ProcessEcho")
