/* $Id$ */

/* 
   Copyright (c) Generation Capital Ltd., 2008.  All rights reserved.

   Author: Mika Nystrom <mika@alum.mit.edu>
*/

if not equal (OS_TYPE, "WIN32")

import ("libm3")

Interface("Csighandler")

c_source ("sighandler")

library ("schemesig")

end
