% Copyright (C) 1993, Digital Equipment Corporation 
% All rights reserved.                              
% See the file COPYRIGHT for a full description.    

% Last modified on Thu Jun 20 15:46:31 PDT 1996 by heydon

import("zeus")
	
module("MiscFmt")

zume("Wheeler")
oblume("Wheeler", "Compress")
oblume("Wheeler", "Decompress")
oblume("Wheeler", "WhyDecompressWorks")

module("Wheeler")
module("CharArraySort")

resource("Decompress.pcode")
resource("WheelerInput.fv")

if not defined ("MENTOR_UMBRELLA") 
  implementation ("Main")
  bundle("WheelerBundle")
  program("wheeler")
end
