/* Copyright (C) 1993, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Mon Jun  3 14:10:23 PDT 1996 by mcjones */

% readonly proc simple_c_program(nm) is
%   local SRCFILE = path_of(nm & ".c")
%   local EXEFILE = nm
%
%   if stale(EXEFILE, SRCFILE)
%     exec (CC, "-o " & EXEFILE, SRCFILE)
%   end
%
%   deriveds(EXEFILE, no_extension)
% end

readonly proc simple_c_program(nm) is
  local src = path_of (nm & ".c")
  local obj = nm & ".o"
  local pgm = program_name (nm)
  local toss = 0

  if defined ("_all")
    if stale (pgm, src)
      toss = compile_c (src, obj, [], FALSE, FALSE)
      toss = m3_link (pgm, [], obj, SYSTEM_LIBS{"LIBC"}, FALSE)
    end
  end

  deriveds("", [ obj, pgm ])
  BindExport (pgm)
end

simple_c_program("LecternClient")

implementation("LecternClientPosix")
implementation("LecternServerPosix")


