/* Copyright (C) 1993, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Wed May  5 20:55:11 PDT 1993 by mjordan                  */

Module("M3PathTool")
Module("M3ToolFrame")

