% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% File: m3makefile
% Last modified on Thu Apr  6 09:41:48 PDT 1995 by kalsow
%      modified on Fri Feb  7 00:38:19 PST 1992 by muller

generic_module ("Module")
generic_module ("And")
generic_module ("Divide")
generic_module ("Extract")
generic_module ("GE")
generic_module ("GT")
generic_module ("Insert")
generic_module ("LE")
generic_module ("LT")
generic_module ("Minus")
generic_module ("Mod")
generic_module ("Not")
generic_module ("Or")
generic_module ("Plus")
generic_module ("Rotate")
generic_module ("Shift")
generic_module ("Times")
generic_module ("Xor")

template ("word")
word("Int", "Word")
word("LInt", "Long")
