% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% File: m3makefile
% Last modified on Thu Apr  6 09:41:48 PDT 1995 by kalsow
%      modified on Fri Feb  7 00:38:19 PST 1992 by muller

generic_module ("GenModule")
generic_module ("GenAnd")
generic_module ("GenDivide")
generic_module ("GenExtract")
generic_module ("GenGE")
generic_module ("GenGT")
generic_module ("GenInsert")
generic_module ("GenLE")
generic_module ("GenLT")
generic_module ("GenMinus")
generic_module ("GenMod")
generic_module ("GenNot")
generic_module ("GenOr")
generic_module ("GenPlus")
generic_module ("GenRotate")
generic_module ("GenShift")
generic_module ("GenTimes")
generic_module ("GenXor")

template ("word")
word("Int", "Word")
word("LInt", "Long")
