% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Fri Jul 30 09:36:28 PDT 1993 by kalsow
%      modified on Fri May  7 14:19:12 PDT 1993 by muller

Interface ("RealRep")
Interface ("LongRealRep")

%ExtendedRep interface is one of these dirs depending on backend
/*
 *    If the target is windows and any backend except llvm we have
 *    to keep the definition of extended as longreal 
      if equal (TARGET_OS, "NT") and not IsBackendLlvm ()
   No - we only allow the AMD64_LINUX target to have 128 bit floats.
   Others can be added when proven.
*/
if equal (TARGET, "AMD64_LINUX")
  include_dir ("ext128")
else
  include_dir ("ext64")
end
