/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Tue Dec 20 17:10:57 PST 1994 by heydon                   */
/*      modified on Sun Oct 18 13:54:36 PDT 1992 by gnelson                  */
/*                                                                           */
/* m3makefile for /proj/m3/pkgs/juno-app/pkl-fonts/src/rsrc                  */

/* character encodings */
resource	("StandardEncoding")
resource	("ISOLatin1Encoding")
resource	("SymbolEncoding")

/* Font metric files */
resource	("Times-Roman.afm")
resource	("Times-Bold.afm")
resource	("Times-Italic.afm")
resource	("Times-BoldItalic.afm")
resource	("Helvetica.afm")
resource	("Helvetica-Bold.afm")
resource	("Helvetica-Oblique.afm")
resource	("Helvetica-BoldOblique.afm")
resource	("Courier.afm")
resource	("Courier-Bold.afm")
resource	("Courier-Oblique.afm")
resource	("Courier-BoldOblique.afm")
resource	("Symbol.afm")

/* bundle file */
bundle		("PklFontsBundle")
