% (* ----------------------------------------------------------------------1- *)
% (* File m3makefile for Modula3 compiler test e041                           *)
% (* Copyright 2022, Rodney M. Bates.                                         *)
% (* rodney.m.bates@acm.org                                                   *)
% (* Licensed under the MIT license.                                          *)
% (* ----------------------------------------------------------------------2- *)

import("libm3")

module ("One")
module ("Two")
implementation ("Main")

build_standalone ()
include("../../Test.common")
program ("pgm")
