% Copyright (C) 2010, Peter Eiserloh
% All rights reserved

checkx_root = pn_prefix(pn_prefix(pn_prefix(path())))
project_root = pn_prefix(pn_prefix(checkx_root))
tree_root = pn_prefix(project_root)
write("check-x root: [[" & checkx_root & "]]\n")
write("Project root: [[" & project_root & "]]\n")
write("tree_root: [[" & tree_root & "]]\n")


override("m3lua", tree_root)
% override("m3lua", "/home/peter/src/modula-3")
