% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% setjmp.s implements _setjmp and _longjmp then same way setjmp and longjmp
% are implemented on the OKI
% signal.o is taken from /usr/ucblib/libucb.a

pgm_source ("signal.o")

Interface ("Csetjmp")
