% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu May  4 11:19:51 PDT 1995 by kalsow 
%      modified on Wed May 25 14:44:43 PDT 1994 by detlefs
%      modified on Wed Jun  2 15:25:51 PDT 1993 by muller
%      modified on Fri May  7 22:32:22 PDT 1993 by mjordan
%      modified on Tue Apr 20 14:35:55 PDT 1993 by mcjones
%      modified on Sun Feb 21 14:07:29 PST 1993 by jdd

pgm_source ("RTBuiltin.mx")

Module    ("RTHooks")
Module    ("RT0")
Module    ("RuntimeError")

include   ("Compiler.tmpl")
implementation ("Compiler")

Module    ("RTAllocator")
Interface ("RTAllocCnts")
Module    ("RTAllocStats")
Module    ("RTHeap")
Module    ("RTHeapInfo")
Module    ("RTHeapMap")
Module    ("RTHeapRep")
Module    ("RTHeapStats")
Module    ("RTCollector")
Interface ("RTCollectorSRC")
interface ("RTWeakRef")
Module    ("RTIO")
c_source  ("RTIOc")
interface ("RTLinkerX")
Module    ("RTLinker")
c_source  ("RTLinkerC")
Module    ("RTDebug")
c_source  ("RTDebugC")
Module    ("RTError")
Module    ("RTException")
Module    ("RTMapOp")
Module    ("RTMisc")
c_source  ("RTMiscC")
Interface ("RTModule")
Module    ("RTPacking")
Module    ("RTParams")
Module    ("RTProcedure")
Module    ("RTProcess")
c_source  ("RTProcessC")
interface ("RTThread")
Module    ("RTTipe")
Module    ("RTType")
Module    ("RTTypeFP")
Module    ("RTTypeMap")
Module    ("RTutils")
Module    ("RTHeapDebug")
Interface ("RTArgs")
Interface ("RTHeapEvent")
Interface ("RTProcedureSRC")
Interface ("RTSignal")
Interface ("RTStack")
Interface ("RTTypeSRC")
interface ("RTOS")

proc FileExists(a) is
    return not stale (a, a)
end

if     not FileExists(path() & "/../" & TARGET & "/RTMachine.i3")
    or not FileExists(path() & "/../" & TARGET & "/m3makefile")
  interface      ("RTMachine")   
end 
