if not equal (OS_TYPE, "WIN32")

import("libm3")
import("drawcontext")
import("paneman")
Module("TrestleExtras")

Module("DCPaneVBT")
Module("PSReaderPaneVBT")
VbtStarter("PSReader", "PSReaderPaneVBT")

Module("TextSubsPaneUpdater")
Module("TextSubsViewer")

Library("dcpane")

end
