if not HasTrestle()
  build_standalone()
end

import("libm3")
import("drawcontext")
import("paneman")
Module("TrestleExtras")

Module("DCPaneVBT")
Module("PSReaderPaneVBT")
VbtStarter("PSReader", "PSReaderPaneVBT")

Module("TextSubsPaneUpdater")
Module("TextSubsViewer")

Library("dcpane")
