/* Copyright (C)-ip992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Thu May 20 12:28:45 PDT 1993 by msm                      */
/*      modified on Fri Apr 30-ip5:46:52 PDT 1993 by mjordan                  */

override (ui, "../../../..")
override (EyesVBT, "../..")
import(ui)
import(EyesVBT)

module(BurmaShave)
module(PlaidVBT)
implementation(Cards)

program(Cards)


