.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" Last modified on Mon Feb 10 22:41:14 PST 1992 by muller
.nh
.TH DPSSLIDES 1
.SH Name
dpsslides \- a demonstration of the Display PostScript library

.SH Syntax
.B dpsslides
[-xlate] [-warp] [-tall]

.SH Description

This program is an example use of the Display PostScript
sandbox.  It displays "viewgraphs" and allows paging forward
and backward in the viewgraph set, highlighting of individual
viewgraph lines, and "progressive disclosure" within a
viewgraph.

The description of the viewgraph is taken from the standard input.

.SH Author
Robert M. Ayers


