% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Sun Jun 20 14:07:19 PDT 1993 by harrison
%      modified on Tue Feb 11 16:27:56 PST 1992 by muller

Module ("Stat")
