# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/openbsd7"

  config.vm.provider("virtualbox") do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  config.vm.synced_folder(".", "/vagrant", disabled: true)

  config.vm.provision "shell", inline: <<-SHELL
    pkg_add cmake gtar-1.34 python3
  SHELL
end
