/* Copyright (C) 1995, Digital Equipment Corporation                         */
/* Digital Internal Use Only                                                 */
/* All rights reserved.                                                      */
/*                                                                           */
/* Last modified on Thu Jun  1 11:17:18 PDT 1995 by najork                   */
/*       Created on Wed Jan 11 21:58:14 PST 1995 by najork                   */

if equal (TARGET, "NT386")
  override ("ui", "..\\..")
end

import("ui")
implementation("Test27")
program("Test27")
