% Copyright (C) 1994, Digital Equipment Corporation.
% All rights reserved.
% See the file COPYRIGHT for a full description.
 
interface ("Int")
interface ("IntList")
implementation ("Int")
implementation ("IntList")
generic_interface ("List")
generic_implementation ("List")
