% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Nov  1 10:02:30 PST 1994 by kalsow
%      modified on Mon May 24 10:49:09 PDT 1993 by muller

override (slisp, WDROOT)
import (slisp)

implementation (Main)

program (test)

