
%%XXDIR = { "WIN32" : "N:\\m3-libs", "POSIX" : "/proj/cmass/src.2/m3-libs" }
%%WORKDIR = XXDIR {OS_TYPE}

% override ("m3core", WORKDIR)
override("m3core", ROOT & "/m3-libs")
M3_FRONT_FLAGS += "-vsdebug"
_M3BUNDLE_OVERRIDE = "T"
