% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Jul 30 13:55:56 EST 1997 by hosking
%      modified on Mon Nov 21 13:17:30 PST 1994 by kalsow
%      modified on Mon Dec 14 19:59:03 PST 1992 by jdd
%      modified on Wed May 20 17:21:29 PDT 1992 by muller

interface      ("RTMachine")
c_source       ("RTStackC")
