% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Aug 22 09:47:08 PDT 1994 by kalsow
%      modified on Thu Sep 10 09:16:47 PDT 1992 by mhb
%      modified on Tue Feb 11 22:04:30 PST 1992 by gnelson

import ("libm3")

implementation ("m3bundle")

build_standalone ()
Program ("m3bundle")

ManPage ("m3bundle","1")

