% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Dec 21 14:41:55 PST 1993 by kalsow
%

if HasTrestle()

import ("bicycle")

module ("Solve")
module ("Solve2")
module ("Tree")
sequence ("Tree", "Tree")
implementation ("Solitaire")

m3_option ("-gui")
build_standalone()
Program ("solitaire")
ManPage ("solitaire","6")

end
