
%% M3_MAIN_IN_C = TRUE

%override ("m3core", "N:\\m3-libs")
%override ("ui", "N:\\m3-ui")
override ("m3core", ROOT & "/m3-libs")
override ("libm3", ROOT & "/m3-libs")
override ("bicycle", ROOT & "/m3-ui")
override ("ui", ROOT & "/m3-ui")

build_standalone ()
