interface("Upthread")
Interface("Utypes")

Interface ("Uexec")
Interface ("Unix")
Interface ("Utime")
Interface ("Uutsname")

if not equal(TARGET, "SPARC32_LINUX") and not equal(TARGET, "SPARC64_LINUX")
    Interface ("Uerror")
    Interface ("Usocket")
    Interface ("Usignal")
end
