interface("Upthread")
Interface("Utypes")
Interface("Usem")
Interface("Usched")

Interface ("Uexec")
Interface ("Umman")
Interface ("Unix")
Interface ("Uprocess")
Interface ("Uresource")
Interface ("Utime")
Interface ("Uutsname")

if not equal(TARGET, "SPARC32_LINUX") and not equal(TARGET, "SPARC64_LINUX")
    Interface ("Uerror")
    Interface ("Usocket")
    Interface ("Usignal")
end
