% Copyright 1994 Digital Equipment Corporation.
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Aug 19 22:14:44 PDT 1996 by mhb      

resource	("macros.fv")
resource	("Deck.fv")
resource	("Doc.fv")
resource	("FreeDoc.fv")
resource	("Help.fv")
resource	("Help.html")
resource	("MButton.fv")
resource	("OpenURL.fv")
resource	("Rename.fv")
resource	("Search.fv")
resource	("Titles.fv")
resource	("Workspace.fv")

resource	("NWDiagonal")
resource	("NEDiagonal")

resource	("iconize.pbm")
resource	("leftArrow.pbm")
resource	("mapped.pbm")
resource	("menuArrow.pbm")
resource	("pulldown.pbm")
resource	("rightArrow.pbm")
resource	("unmapped.pbm") 

