Generic_interface("Atomic")
if equal(TARGET, "NT386")
  Generic_implementation("AtomicSequential")
else
  Generic_implementation("Atomic")
end
template("atomic")
Atomic("Address")
Atomic("Boolean")
Atomic("Char")
Atomic("Integer")
if not (equal(TARGET, "PPC_LINUX") or equal(TARGET, "PPC_DARWIN")
    or equal(TARGET, "PPC32_OPENBSD"))
  Atomic("Longint")
end
Atomic("Refany")
Atomic("WideChar")
