if not equal(TARGET, "ARMEL_LINUX")

Generic_module("Atomic")
template("atomic")

Atomic("Address")
Atomic("Boolean")
Atomic("Char")
Atomic("Integer")
if not (equal(TARGET, "PPC_LINUX") or equal(TARGET, "PPC_DARWIN")
    or equal(TARGET, "PPC32_OPENBSD"))
  Atomic("Longint")
end
Atomic("Refany")
Atomic("WideChar")

end
