% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Sat Sep  2 22:11:42 PDT 1995 by najork  

include_dir(OS_TYPE)
