/* Copyright (C) 1995, Digital Equipment Corporation                         */
/* Digital Internal Use Only                                                 */
/* All rights reserved.                                                      */
/*                                                                           */
/* Last modified on Wed Oct 11 14:00:40 PDT 1995 by najork                   */
/*       Created on Fri Oct  2 16:04:26 PDT 1995 by najork                   */

if defined("configure_system_libs")
  configure_system_libs()
end 

if SYSTEM_LIBS contains "OPENGL"
  import_sys_lib ("OPENGL")

  include_dir (OS_TYPE)

  Library ("opengl")
end
