% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Wed Jun  9 17:25:14 PDT 1993 by harrison
%      modified on Fri May  7 21:06:11 PDT 1993 by mjordan
%      modified on Thu May  6 12:10:31 PDT 1993 by muller

Interface ("Cerrno")
Interface ("Cstddef")
Interface ("Cstdint")
Interface ("Cstdlib")
Interface ("Ctypes")
Module ("M3toC")
c_source ("CerrnoC")

% not yet common to all, but should be, will be

if     equal (TARGET, "AMD64_LINUX")
    or equal (TARGET, "AMD64_FREEBSD")
    or equal (TARGET, "SPARC32_LINUX")
    or equal (TARGET, "SPARC64_LINUX")
    or equal (TARGET, "MIPS64_OPENBSD")
    or equal (TARGET, "PPC32_OPENBSD")
    or equal (TARGET, "SPARC64_OPENBSD")
    or equal (TARGET, "SPARC64_SOLARIS")
    or equal (TARGET, "NT386")
    or equal (TARGET, "LINUXLIBC6")
    or equal (TARGET, "PPC_LINUX")
    or equal (TARGET, "I386_OPENBSD")
    or equal (TARGET, "PA32_HPUX")
    or equal (TARGET, "PA64_HPUX")
    or equal (TARGET, "ARM_DARWIN")
  Interface ("Cstring")
  Interface ("Cstdio")
end

% not used by all ports

Interface ("Csignal")
