% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

Interface ("Cerrno")
Interface ("Cstddef")
Interface ("Cstdint")
Interface ("Cstdlib")
c_source("CstdlibC")
Interface ("Ctypes")
Module ("M3toC")
c_source ("CerrnoC")

Interface ("Cstring")
c_source("CstringC")
Interface ("Cstdio")
c_source ("CstdioC")

Interface ("Csignal") % not used by all ports
c_source("CsignalC")

% none exist
%if     not FileExists(path() & "/../" & TARGET & "/Csetjmp.i3")
%    or not FileExists(path() & "/../" & TARGET & "/m3makefile")
  interface      ("Csetjmp")   
  c_source ("CsetjmpC")
%end 
