% Copyright 1996-2000, Critical Mass, Inc.  All rights reserved.
% See file COPYRIGHT-CMASS for details.

import ("libm3")
import ("m3quake")
import ("patternmatching")
import ("sysutils")
%import ("cmkey")

% This does not work with the modular config files.
configfn = ".." & SL & "src" & SL & "config" & SL & TARGET
resource_named ("config", configfn)
bundle ("Setup")

module ("Msg")
module ("Text2")

module ("OS")
implementation ("OS" & OS_TYPE)

interface ("Registry")
implementation ("Registry" & OS_TYPE)

implementation ("Main")

proc target_intf(name) is
  local filename = name & ".i3"
  local tempname = "." & filename
  local cmd = ""
  local ret = 0
  if defined("_all")
    > tempname in
      write("INTERFACE InstallTarget;", CR, CR, "CONST")
    end
    >> tempname in
      write("  Target = \"", TARGET, "\";", CR)
    end
    >> tempname in
      write("END InstallTarget.", CR)
    end
    cp_if(tempname, filename)
    derived_interface(name, "HIDDEN")
  end
end

target_intf ("InstallTarget")

build_standalone()
program ("cminstall")
