% Copyright 1996-2000, Critical Mass, Inc.  All rights reserved.
% See file COPYRIGHT-CMASS for details.

import ("libm3")
import ("m3quake")
import ("cmkey")

resource_named ("config", "config" & SL & TARGET)
bundle ("Setup")

module ("Msg")
module ("Text2")

module ("OS")
implementation ("OS" & OS_TYPE)

interface ("Registry")
implementation ("Registry" & OS_TYPE)

implementation ("Main")

build_standalone()
program ("cminstall")
