/* Makefile for tcp library (POSIX) */
/* Copyright 1993 Digital Equipment Corporation. */
/* Distributed only by permission. */
/* Last modified on Thu Feb  9 15:55:57 PST 1995 by wobber     */

Interface("TCPPosix")
interface("Herrno")
c_source("HerrnoC")
implementation("IP")
implementation("IPErrorPosix")
implementation("TCP")
implementation("TCPExtras")
implementation("TCPPeer")
interface("TCPHack")

if equal (TARGET, "ALPHA_OSF") or equal(TARGET, "DS3100")
   implementation("TCPHack")
else
   implementation("TCPHackNull")
end


