% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon May 22 15:46:25 PDT 1995 by kalsow

import ("libm3")
import ("libbuf")
import ("m3scan")

Module ("CharMap")
Module ("ID")
Module ("XFormat")
Module ("MarkUp")
module ("M3MarkUp")
Module ("CMarkUp")
Module ("ErrLog")

Library ("m3markup")

