/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Tue Feb 11 17:20:01 PST 1992 by muller                   */

Generic_interface("GenWord")
interface("WordRep")
Interface("Word")
interface("LongRep")
Interface("Long")

generic_implementation("GenWord")
implementation ("Word")
implementation ("Long")
