% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Jun 20 10:13:13 PDT 1996 by heydon
%      modified on Thu Mar  2 02:47:13 PST 1995 by msm
%      modified on Fri Jan 13 15:58:10 PST 1995 by najork
%      modified on Fri Oct 28 17:08:10 PDT 1994 by kalsow
%      modified on Tue Oct  5 18:17:24 PDT 1993 by sfreeman
%      modified on Fri Apr 16 09:42:42 PDT 1993 by steveg
%      modified on Mon Feb 24 14:00:03 PST 1992 by muller

if defined("configure_system_libs")
  configure_system_libs()
end 

if not (SYSTEM_LIBS contains "X11")
  build_standalone()
end

import ("X11R4")
import ("tcp")

module ("Compl")
sequence("Compl", "Compl")

module ("XExtensions")
interface("XImUtil")
interface("TrslOnXF")
Interface("XShm")
interface ("XClientExt")
Module("XPicture")

Interface ("XSharedMem")
if X11_WITH_SHARED_MEM
  implementation ("XSharedMem")
else
  implementation ("XNoSharedMem")
end

implementation ("XPictureFree")
implementation ("XSharedFree")

implementation("PictureImpl")

Module ("XClient")
module ("XEventQueue")
Module ("XScreenType")
module ("XScrollQueue")
module ("XAtomQueue")
module ("XMessenger")
module ("XPaint")
module ("XInput")
module ("XProperties")
Module ("XClientF")
module ("XGC")
module ("XScrnTpRep")
module ("XScrnCrsr")
Module ("XScrnCmap")
module ("XScrnFont")
module ("XScrnPntOp")
module ("XScrnPxmp")
interface ("XCursors")
module ("XConfCtl")
Module ("TrestleOnX")
implementation ("TrestleOS")
