% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Fri Aug 13 09:55:30 PDT 1993 by kalsow

include_dir ("Common")
if equal (TARGET, "NT386") and equal(OS_TYPE, "POSIX")
    include_dir ("NT386GNU")
else
    include_dir (TARGET)
end
