#!/bin/csh
#(cd ../../ui; m3build)
(m3build)
#(cd browser0; m3build -O)
#(cd browser1; m3build -O)
#(cd browser2; m3build -O)
(cd browser3; m3build -O)
setenv WWW_HOME http://src-www.pa.dec.com/~mhb/cmtalk/cm.html
browser3/AOSF/browser
