% Copyright 1994 Digital Equipment Corporation.
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Aug 22 09:50:58 PDT 1996 by mhb      

import		("formsvbt")
import		("webvbt")

resource	("ui.fv")
bundle		("UIBundle")
implementation	("Main")

ManPage		("WebScape", 1)
Program		("WebScape")






