.\" Copyright (C) 1995, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" Last modified on Tue Oct  3 10:15:11 PDT 1995 by mhb   
.nh
.TH WebScape 1
.SH NAME
WebScape \- An Experimental Web Browser

.SH SYNTAX
.B WebScape

.SH DESCRIPTION 
.B WebScape
is an experimental World-Wide Web browser whose primary
purpose is to test WebVBT.

.SH AUTHOR OF OBJECT
Marc H. Brown

.SH AUTHOR OF DOCUMENTATION
Marc H. Brown
