
% Each package contains an m3makefile which describes
% the components of a package and how it should be
% built. 

% It turns out that this program is simple enough
% that you don't need an m3makefile. If you run
% cm3 in the directory, even if you didn't have
% an m3makefile, it'd figure out what it has to do.
% So, this file is here for pedgagogical reasons.

% To build most programs, you first have to 
% install the standard Modula-3 libraries.

import ("libm3")

% An implementation is a module that doesn't export
% an interface under its name.

implementation ("Hello")

% Each package can have a README file or an index.html which 
% will be viewable from CM3_IDE user interface. This is very 
% handy for external documentation. You don't have to 
% include the external documentation as part of the package.

program ("hello")

