---
name: Unix upgrade release
description: Upgrade a binary release on a Unix-like system.

inputs:
  m3backendmode:
    description: Target backend mode for upgrade
    required: false
    default: ""

runs:
  using: composite

  steps:
  - name: Build all the things
    run: |
      ./boot2min.py "${{ inputs.m3backendmode }}"
      ./do-cm3-all.py buildship "${{ inputs.m3backendmode }}"
    shell: bash
    working-directory: scripts/python
