
template("daubechieswavelet")


generic_module("DaubechiesWavelet")
DaubechiesWavelet("Real",            "RealSignal",            "RealBasic")
DaubechiesWavelet("LongReal",        "LongRealSignal",        "LongRealBasic")
DaubechiesWavelet("Extended",        "ExtendedSignal",        "ExtendedBasic")
%DaubechiesWavelet("RealComplex",     "RealComplexSignal",     "RealComplexFast")
%DaubechiesWavelet("LongRealComplex", "LongRealComplexSignal", "LongRealComplexFast")
%DaubechiesWavelet("ExtendedComplex", "ExtendedComplexSignal", "ExtendedComplexFast")
