
template("daubechieswavelet")
template("bsplinewavelet")


generic_module("DaubechiesWavelet")
DaubechiesWavelet("Real",            "Real",            "Basic")
DaubechiesWavelet("LongReal",        "LongReal",        "Basic")
DaubechiesWavelet("Extended",        "Extended",        "Basic")
%DaubechiesWavelet("RealComplex",     "RealComplex",     "Fast")
%DaubechiesWavelet("LongRealComplex", "LongRealComplex", "Fast")
%DaubechiesWavelet("ExtendedComplex", "ExtendedComplex", "Fast")

generic_module("BSplineWavelet")
BSplineWavelet("Real",            "Real",            "Basic")
BSplineWavelet("LongReal",        "LongReal",        "Basic")
BSplineWavelet("Extended",        "Extended",        "Basic")
%BSplineWavelet("RealComplex",     "RealComplex",     "Fast")
%BSplineWavelet("LongRealComplex", "LongRealComplex", "Fast")
%BSplineWavelet("ExtendedComplex", "ExtendedComplex", "Fast")

module("LongRealWaveletPlot")
