
template("daubechieswavelet")
template("bsplinewavelet")


generic_module("DaubechiesWavelet")
DaubechiesWavelet("Real",            "RealBasic")
DaubechiesWavelet("LongReal",        "LongRealBasic")
DaubechiesWavelet("Extended",        "ExtendedBasic")
%DaubechiesWavelet("RealComplex",     "RealComplex")
%DaubechiesWavelet("LongRealComplex", "LongRealComplex")
%DaubechiesWavelet("ExtendedComplex", "ExtendedComplex")

generic_module("BSplineWavelet")
BSplineWavelet("Real",            "RealBasic")
BSplineWavelet("LongReal",        "LongRealBasic")
BSplineWavelet("Extended",        "ExtendedBasic")
%BSplineWavelet("RealComplex",     "RealComplex")
%BSplineWavelet("LongRealComplex", "LongRealComplex")
%BSplineWavelet("ExtendedComplex", "ExtendedComplex")

module("LongRealWaveletPlot")
