% Copyright according to COPYRIGHT-CMASS.
% FIXME: copied from FreeBSD3 target. Probably needs to be changed.

Interface ("Csetjmp")
Interface ("Csignal")
Interface ("Cstring")
Module ("Cstdio")

c_source ("CstdioC")


