#! /bin/sh

# Set this to the unique user name that cvsupd is run under.
user=cvsup

tf=/tmp/cvsupwho$$
trap "rm -f ${tf}" 0 1 2 3 15

ps -ww -o pid,start,command -U ${user} |\
    sed -e '1s/COMMAND/WHO/' \
	-e '/ cvsupd /d' \
	-e 's/cvsupd: //' \
	-e 's/ (cvsupd)$//' |\
    tee ${tf}
echo "Total $((`wc -l < ${tf}`-1)) active clients"
