.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" Last modified on Sun Jul 19 05:02:49 1992 by mhb   
.nh
.TH Sort 1
.SH NAME
Sorting \- a simple Zeus demo to illustrate various sorting algorithms

.SH SYNTAX
Sorting

.SH DESCRIPTION
.B Sorting
displays a number of fundamental sorting algorithms
using fairly common displays. The package is used by 
the Zeus developers for testing out features of Zeus,
so there's a good chance that it will contain all the 
latest and greatest stuff.

.SH AUTHOR OF OBJECT
Marc H. Brown

.SH AUTHOR OF DOCUMENTATION
Marc H. Brown


