include_dir ("runtime")

library("m3gcdefs")

> "libm3gcdefs.m3x" in 
  write("")
end
> "libm3gcdefs.m3x" in 
  write("")
end
> ".M3WEB" in 
  write("")
end

local libname = library_name("m3gcdefs")
LibdExport(libname)
