import("libm3")

template("fourier")


generic_module("FourierTransform")
FourierTransform("Real",     "RealBasic")
FourierTransform("LongReal", "LongRealBasic")
FourierTransform("Extended", "ExtendedBasic")
