.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" File: m3.1
.\" Last modified on Wed May 11 14:36:38 PDT 1994 by glassman                .
.\"      modified on Mon Mar 02 14:44:26 PST 1992 by muller                  .
.nh
.TH BADBRICKS 6
.SH NAME
BadBricks \- False bricks, or, why we like Luca
.SH SYNTAX
.B BadBricks

.SH DESCRIPTION
This game only makes sense if you were at SRC during the summer
of '91, or if you just happen to love buildings with false brick
facades.  Click the mouse buttons on bricks; curse at Luca.
.PP
Future developments may include:  Olympic Drug Testing, Bumper
Cars (aim for yellow poles), and Escape from the Grisly Garage.
.PP
.SH AUTHOR
Luca, who else?

.SH COPYRIGHT
Copyright (C) 1991, Digital Equipment Corporation
.PP
Permission to use, copy, modify, distribute, and sell this software
and its documentation for any purpose is hereby granted without fee,
provided that the above copyright notices appear in all copies and that
both those copyright notices and this permission notice appear in
supporting documentation.

