% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Jan 12 15:59:09 PST 1994 by kalsow

import ("ui")

implementation ("BadBricks")

Program ("BadBricks")
ManPage ("BadBricks","6")
