% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Jan 12 15:59:09 PST 1994 by kalsow

if HasTrestle()

import ("ui")

implementation ("BadBricks")

m3_option ("-gui")
Program ("BadBricks")
ManPage ("BadBricks","6")

end
