(* test for typenames esp. with C backend *)

MODULE Main;
IMPORT Ctypes;
FROM Ctypes IMPORT int;

<*NOWARN*>PROCEDURE F1(a:Ctypes.int) = BEGIN END F1;
<*NOWARN*>PROCEDURE F2(a:int) = BEGIN END F2;
<*NOWARN*>PROCEDURE F3(VAR a:Ctypes.int) = BEGIN END F3;
<*NOWARN*>PROCEDURE F4(VAR a:int) = BEGIN END F4;
<*NOWARN*>PROCEDURE F5(a:REF Ctypes.int) = BEGIN END F5;
<*NOWARN*>PROCEDURE F6(a:REF int) = BEGIN END F6;
<*NOWARN*>PROCEDURE F7(VAR a:REF Ctypes.int) = BEGIN END F7;
<*NOWARN*>PROCEDURE F8(VAR a:REF int) = BEGIN END F8;
<*NOWARN*>PROCEDURE F9(a:REF REF Ctypes.int) = BEGIN END F9;
<*NOWARN*>PROCEDURE FA(a:REF REF int) = BEGIN END FA;
<*NOWARN*>PROCEDURE FB(VAR a:REF REF Ctypes.int) = BEGIN END FB;
<*NOWARN*>PROCEDURE FC(VAR a:REF REF int) = BEGIN END FC;

BEGIN 
END Main.
