.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" Last modified on Fri Jul 15 09:58:17 PDT 1994 by glassman
.\"      modified on Tue Feb 11 17:43:25 PST 1992 by muller
.nh
.TH columns 6
.SH NAME
columns \- simple game for X

.SH SYNTAX
.B columns

.SH Description
.B columns
is a suite of simple video games.  To play the game,
you need X and a color display.  To win the game, you must
get 3 squares in a row, again and again.

.SH Bugs
right.

.SH Tasks for the bored

Add a score file

Do a better job with the animation.

Add sound effects.

Build a mouse driven version.

Pick beautiful colors.

Build a multi-player version....

.SH Acknowledgments

I saw a similar game on a PC.

.SH Author
Bill Kalsow.


