% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Oct 11 14:07:51 PDT 1995 by najork
%      modified on Wed Jan 12 15:55:18 PST 1994 by kalsow
%      modified on Mon May 04 15:16:48 PDT 1992 by muller

if defined("configure_system_libs")
  configure_system_libs()
end

if SYSTEM_LIBS contains "X11"
  import ("X11R4")

  module ("Bars")
  module ("Columns")
  module ("Config")
  module ("Rows")
  module ("Squares")
  module ("Threes")
  implementation ("Main")

  Program ("columns")
  ManPage ("columns", 6)
end
