configure_system_libs()

if SYSTEM_LIBS contains "POSTGRES95"

import ("libm3")
import ("postgres95")

implementation ("Demo2")
program ("Demo")

if defined("RUN")
  r = q_exec( "." & SL & "Demo" )
  write( CR, "program returned ", r, CR )
end

end
