% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Nov  1 09:07:25 PST 1994 by kalsow 
%      modified on Tue May  4 10:25:02 PDT 1993 by mjordan

include_dir ("Common")
include_dir (OS_TYPE)
