UNSAFE MODULE Main;
IMPORT Word, Long;

(* This program endeavors to exercise
 * every sort of integer, float, address comparison,
 * and some set compares, in order to support
 * cleanup and improvement of comparison in m3back.
 * If this isn't fleshed out further, it really
 * belongs in the "c for code" test section.
 *)

<*UNUSED*>PROCEDURE WordLT(a,b:Word.T):BOOLEAN=BEGIN RETURN Word.LT(a,b); END WordLT;
<*UNUSED*>PROCEDURE WordLE(a,b:Word.T):BOOLEAN=BEGIN RETURN Word.LE(a,b); END WordLE;
<*UNUSED*>PROCEDURE WordGT(a,b:Word.T):BOOLEAN=BEGIN RETURN Word.GT(a,b); END WordGT;
<*UNUSED*>PROCEDURE WordGE(a,b:Word.T):BOOLEAN=BEGIN RETURN Word.GE(a,b); END WordGE;
<*UNUSED*>PROCEDURE WordEQ(a,b:Word.T):BOOLEAN=BEGIN RETURN a=b; END WordEQ;
<*UNUSED*>PROCEDURE WordNE(a,b:Word.T):BOOLEAN=BEGIN RETURN a#b; END WordNE;
<*UNUSED*>PROCEDURE WordLT0(a:Word.T):BOOLEAN=BEGIN RETURN Word.LT(a,0); END WordLT0;
<*UNUSED*>PROCEDURE WordLE0(a:Word.T):BOOLEAN=BEGIN RETURN Word.LE(a,0); END WordLE0;
<*UNUSED*>PROCEDURE WordGT0(a:Word.T):BOOLEAN=BEGIN RETURN Word.GT(a,0); END WordGT0;
<*UNUSED*>PROCEDURE WordGE0(a:Word.T):BOOLEAN=BEGIN RETURN Word.GE(a,0); END WordGE0;
<*UNUSED*>PROCEDURE WordEQ0(a:Word.T):BOOLEAN=BEGIN RETURN a=0; END WordEQ0;
<*UNUSED*>PROCEDURE WordNE0(a:Word.T):BOOLEAN=BEGIN RETURN a#0; END WordNE0;

<*UNUSED*>PROCEDURE LongLT(a,b:Long.T):BOOLEAN=BEGIN RETURN Long.LT(a,b); END LongLT;
<*UNUSED*>PROCEDURE LongLE(a,b:Long.T):BOOLEAN=BEGIN RETURN Long.LE(a,b); END LongLE;
<*UNUSED*>PROCEDURE LongGT(a,b:Long.T):BOOLEAN=BEGIN RETURN Long.GT(a,b); END LongGT;
<*UNUSED*>PROCEDURE LongGE(a,b:Long.T):BOOLEAN=BEGIN RETURN Long.GE(a,b); END LongGE;
<*UNUSED*>PROCEDURE LongEQ(a,b:Long.T):BOOLEAN=BEGIN RETURN a=b; END LongEQ;
<*UNUSED*>PROCEDURE LongNE(a,b:Long.T):BOOLEAN=BEGIN RETURN a#b; END LongNE;
<*UNUSED*>PROCEDURE LongLT0(a:Long.T):BOOLEAN=BEGIN RETURN Long.LT(a,0L); END LongLT0;
<*UNUSED*>PROCEDURE LongLE0(a:Long.T):BOOLEAN=BEGIN RETURN Long.LE(a,0L); END LongLE0;
<*UNUSED*>PROCEDURE LongGT0(a:Long.T):BOOLEAN=BEGIN RETURN Long.GT(a,0L); END LongGT0;
<*UNUSED*>PROCEDURE LongGE0(a:Long.T):BOOLEAN=BEGIN RETURN Long.GE(a,0L); END LongGE0;
<*UNUSED*>PROCEDURE LongEQ0(a:Long.T):BOOLEAN=BEGIN RETURN a=0L; END LongEQ0;
<*UNUSED*>PROCEDURE LongNE0(a:Long.T):BOOLEAN=BEGIN RETURN a#0L; END LongNE0;

<*UNUSED*>PROCEDURE IntegerLT(a,b:INTEGER):BOOLEAN=BEGIN RETURN a<b; END IntegerLT;
<*UNUSED*>PROCEDURE IntegerLE(a,b:INTEGER):BOOLEAN=BEGIN RETURN a<=b; END IntegerLE;
<*UNUSED*>PROCEDURE IntegerGT(a,b:INTEGER):BOOLEAN=BEGIN RETURN a>b; END IntegerGT;
<*UNUSED*>PROCEDURE IntegerGE(a,b:INTEGER):BOOLEAN=BEGIN RETURN a>=b; END IntegerGE;
<*UNUSED*>PROCEDURE IntegerEQ(a,b:INTEGER):BOOLEAN=BEGIN RETURN a=b; END IntegerEQ;
<*UNUSED*>PROCEDURE IntegerNE(a,b:INTEGER):BOOLEAN=BEGIN RETURN a#b; END IntegerNE;
<*UNUSED*>PROCEDURE IntegerLT0(a:INTEGER):BOOLEAN=BEGIN RETURN a<0; END IntegerLT0;
<*UNUSED*>PROCEDURE IntegerLE0(a:INTEGER):BOOLEAN=BEGIN RETURN a<=0; END IntegerLE0;
<*UNUSED*>PROCEDURE IntegerGT0(a:INTEGER):BOOLEAN=BEGIN RETURN a>0; END IntegerGT0;
<*UNUSED*>PROCEDURE IntegerGE0(a:INTEGER):BOOLEAN=BEGIN RETURN a>=0; END IntegerGE0;
<*UNUSED*>PROCEDURE IntegerEQ0(a:INTEGER):BOOLEAN=BEGIN RETURN a=0; END IntegerEQ0;
<*UNUSED*>PROCEDURE IntegerNE0(a:INTEGER):BOOLEAN=BEGIN RETURN a#0; END IntegerNE0;

<*UNUSED*>PROCEDURE RealLT(a,b:REAL):BOOLEAN=BEGIN RETURN a<b; END RealLT;
<*UNUSED*>PROCEDURE RealLE(a,b:REAL):BOOLEAN=BEGIN RETURN a<=b; END RealLE;

<*UNUSED*>PROCEDURE RealGT(a,b:REAL):BOOLEAN=BEGIN RETURN a>b; END RealGT;
<*UNUSED*>PROCEDURE RealGE(a,b:REAL):BOOLEAN=BEGIN RETURN a>=b; END RealGE;

<*UNUSED*>PROCEDURE RealEQ(a,b:REAL):BOOLEAN=BEGIN RETURN a=b; END RealEQ;
<*UNUSED*>PROCEDURE RealNE(a,b:REAL):BOOLEAN=BEGIN RETURN a#b; END RealNE;

<*UNUSED*>PROCEDURE LongrealLT(a,b:LONGREAL):BOOLEAN=BEGIN RETURN a<b; END LongrealLT;
<*UNUSED*>PROCEDURE LongrealLE(a,b:LONGREAL):BOOLEAN=BEGIN RETURN a<=b; END LongrealLE;
<*UNUSED*>PROCEDURE LongrealGT(a,b:LONGREAL):BOOLEAN=BEGIN RETURN a>b; END LongrealGT;
<*UNUSED*>PROCEDURE LongrealGE(a,b:LONGREAL):BOOLEAN=BEGIN RETURN a>=b; END LongrealGE;
<*UNUSED*>PROCEDURE LongrealEQ(a,b:LONGREAL):BOOLEAN=BEGIN RETURN a=b; END LongrealEQ;
<*UNUSED*>PROCEDURE LongrealNE(a,b:LONGREAL):BOOLEAN=BEGIN RETURN a#b; END LongrealNE;

<*UNUSED*>PROCEDURE ExtendedLT(a,b:EXTENDED):BOOLEAN=BEGIN RETURN a<b; END ExtendedLT;
<*UNUSED*>PROCEDURE ExtendedLE(a,b:EXTENDED):BOOLEAN=BEGIN RETURN a<=b; END ExtendedLE;
<*UNUSED*>PROCEDURE ExtendedGT(a,b:EXTENDED):BOOLEAN=BEGIN RETURN a>b; END ExtendedGT;
<*UNUSED*>PROCEDURE ExtendedGE(a,b:EXTENDED):BOOLEAN=BEGIN RETURN a>=b; END ExtendedGE;
<*UNUSED*>PROCEDURE ExtendedEQ(a,b:EXTENDED):BOOLEAN=BEGIN RETURN a=b; END ExtendedEQ;
<*UNUSED*>PROCEDURE ExtendedNE(a,b:EXTENDED):BOOLEAN=BEGIN RETURN a#b; END ExtendedNE;

<*UNUSED*>PROCEDURE AddressLT(a,b:ADDRESS):BOOLEAN=BEGIN RETURN a<b; END AddressLT;
<*UNUSED*>PROCEDURE AddressLE(a,b:ADDRESS):BOOLEAN=BEGIN RETURN a<=b; END AddressLE;
<*UNUSED*>PROCEDURE AddressGT(a,b:ADDRESS):BOOLEAN=BEGIN RETURN a>b; END AddressGT;
<*UNUSED*>PROCEDURE AddressGE(a,b:ADDRESS):BOOLEAN=BEGIN RETURN a>=b; END AddressGE;
<*UNUSED*>PROCEDURE AddressEQ(a,b:ADDRESS):BOOLEAN=BEGIN RETURN a=b; END AddressEQ;
<*UNUSED*>PROCEDURE AddressNE(a,b:ADDRESS):BOOLEAN=BEGIN RETURN a#b; END AddressNE;
<*UNUSED*>PROCEDURE AddressLT0(a:ADDRESS):BOOLEAN=BEGIN RETURN a<NIL; END AddressLT0;
<*UNUSED*>PROCEDURE AddressLE0(a:ADDRESS):BOOLEAN=BEGIN RETURN a<=NIL; END AddressLE0;
<*UNUSED*>PROCEDURE AddressGT0(a:ADDRESS):BOOLEAN=BEGIN RETURN a>NIL; END AddressGT0;
<*UNUSED*>PROCEDURE AddressGE0(a:ADDRESS):BOOLEAN=BEGIN RETURN a>=NIL; END AddressGE0;
<*UNUSED*>PROCEDURE AddressEQ0(a:ADDRESS):BOOLEAN=BEGIN RETURN a=NIL; END AddressEQ0;
<*UNUSED*>PROCEDURE AddressNE0(a:ADDRESS):BOOLEAN=BEGIN RETURN a#NIL; END AddressNE0;

(* CARDINAL is really the same as INTEGER.
 * To get unsigned, use Word.
 *)

<*UNUSED*>PROCEDURE CardinalLT(a,b:CARDINAL):BOOLEAN=BEGIN RETURN a<b; END CardinalLT;
<*UNUSED*>PROCEDURE CardinalLE(a,b:CARDINAL):BOOLEAN=BEGIN RETURN a<=b; END CardinalLE;
<*UNUSED*>PROCEDURE CardinalGT(a,b:CARDINAL):BOOLEAN=BEGIN RETURN a>b; END CardinalGT;
<*UNUSED*>PROCEDURE CardinalGE(a,b:CARDINAL):BOOLEAN=BEGIN RETURN a>=b; END CardinalGE;
<*UNUSED*>PROCEDURE CardinalEQ(a,b:CARDINAL):BOOLEAN=BEGIN RETURN a=b; END CardinalEQ;
<*UNUSED*>PROCEDURE CardinalNE(a,b:CARDINAL):BOOLEAN=BEGIN RETURN a#b; END CardinalNE;


<*UNUSED*>PROCEDURE LongintLT(a,b:LONGINT):BOOLEAN=BEGIN RETURN a<b; END LongintLT;
<*UNUSED*>PROCEDURE LongintLE(a,b:LONGINT):BOOLEAN=BEGIN RETURN a<=b; END LongintLE;
<*UNUSED*>PROCEDURE LongintGT(a,b:LONGINT):BOOLEAN=BEGIN RETURN a>b; END LongintGT;
<*UNUSED*>PROCEDURE LongintGE(a,b:LONGINT):BOOLEAN=BEGIN RETURN a>=b; END LongintGE;
<*UNUSED*>PROCEDURE LongintEQ(a,b:LONGINT):BOOLEAN=BEGIN RETURN a=b; END LongintEQ;
<*UNUSED*>PROCEDURE LongintNE(a,b:LONGINT):BOOLEAN=BEGIN RETURN a#b; END LongintNE;
<*UNUSED*>PROCEDURE LongintLT0(a:LONGINT):BOOLEAN=BEGIN RETURN a<0L; END LongintLT0;
<*UNUSED*>PROCEDURE LongintLE0(a:LONGINT):BOOLEAN=BEGIN RETURN a<=0L; END LongintLE0;
<*UNUSED*>PROCEDURE LongintGT0(a:LONGINT):BOOLEAN=BEGIN RETURN a>0L; END LongintGT0;
<*UNUSED*>PROCEDURE LongintGE0(a:LONGINT):BOOLEAN=BEGIN RETURN a>=0L; END LongintGE0;
<*UNUSED*>PROCEDURE LongintEQ0(a:LONGINT):BOOLEAN=BEGIN RETURN a=0L; END LongintEQ0;
<*UNUSED*>PROCEDURE LongintNE0(a:LONGINT):BOOLEAN=BEGIN RETURN a#0L; END LongintNE0;

(* For actual unsigned operations, use interface Long. *)

<*UNUSED*>PROCEDURE LongcardLT(a,b:LONGCARD):BOOLEAN=BEGIN RETURN a<b; END LongcardLT;
<*UNUSED*>PROCEDURE LongcardLE(a,b:LONGCARD):BOOLEAN=BEGIN RETURN a<=b; END LongcardLE;
<*UNUSED*>PROCEDURE LongcardGT(a,b:LONGCARD):BOOLEAN=BEGIN RETURN a>b; END LongcardGT;
<*UNUSED*>PROCEDURE LongcardGE(a,b:LONGCARD):BOOLEAN=BEGIN RETURN a>=b; END LongcardGE;
<*UNUSED*>PROCEDURE LongcardEQ(a,b:LONGCARD):BOOLEAN=BEGIN RETURN a=b; END LongcardEQ;
<*UNUSED*>PROCEDURE LongcardNE(a,b:LONGCARD):BOOLEAN=BEGIN RETURN a#b; END LongcardNE;


TYPE Set = SET OF [0..1023];
<*UNUSED*>PROCEDURE SetLT(READONLY a,b:Set):BOOLEAN=BEGIN RETURN a<b; END SetLT;
<*UNUSED*>PROCEDURE SetLE(READONLY a,b:Set):BOOLEAN=BEGIN RETURN a<=b; END SetLE;
<*UNUSED*>PROCEDURE SetGT(READONLY a,b:Set):BOOLEAN=BEGIN RETURN a>b; END SetGT;
<*UNUSED*>PROCEDURE SetGE(READONLY a,b:Set):BOOLEAN=BEGIN RETURN a>=b; END SetGE;
<*UNUSED*>PROCEDURE SetEQ(READONLY a,b:Set):BOOLEAN=BEGIN RETURN a=b; END SetEQ;
<*UNUSED*>PROCEDURE SetNE(READONLY a,b:Set):BOOLEAN=BEGIN RETURN a#b; END SetNE;


<*UNUSED*>PROCEDURE CardinalLT0(a:CARDINAL):BOOLEAN=BEGIN RETURN a<0; END CardinalLT0;
<*UNUSED*>PROCEDURE CardinalLE0(a:CARDINAL):BOOLEAN=BEGIN RETURN a<=0; END CardinalLE0;
<*UNUSED*>PROCEDURE CardinalGT0(a:CARDINAL):BOOLEAN=BEGIN RETURN a>0; END CardinalGT0;
<*UNUSED*>PROCEDURE CardinalGE0(a:CARDINAL):BOOLEAN=BEGIN RETURN a>=0; END CardinalGE0;
<*UNUSED*>PROCEDURE CardinalEQ0(a:CARDINAL):BOOLEAN=BEGIN RETURN a=0; END CardinalEQ0;
<*UNUSED*>PROCEDURE CardinalNE0(a:CARDINAL):BOOLEAN=BEGIN RETURN a#0; END CardinalNE0;

<*UNUSED*>PROCEDURE LongcardLT0(a:LONGCARD):BOOLEAN=BEGIN RETURN a<0L; END LongcardLT0;
<*UNUSED*>PROCEDURE LongcardLE0(a:LONGCARD):BOOLEAN=BEGIN RETURN a<=0L; END LongcardLE0;
<*UNUSED*>PROCEDURE LongcardGT0(a:LONGCARD):BOOLEAN=BEGIN RETURN a>0L; END LongcardGT0;
<*UNUSED*>PROCEDURE LongcardGE0(a:LONGCARD):BOOLEAN=BEGIN RETURN a>=0L; END LongcardGE0;
<*UNUSED*>PROCEDURE LongcardEQ0(a:LONGCARD):BOOLEAN=BEGIN RETURN a=0L; END LongcardEQ0;
<*UNUSED*>PROCEDURE LongcardNE0(a:LONGCARD):BOOLEAN=BEGIN RETURN a#0L; END LongcardNE0;


BEGIN
END Main.
