% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description. 
%
% by Stephen Harrison (harrison@src.dec.com)
%
% Last modified on Fri Feb 17 15:05:48 PST 1995 by kalsow  
%      modified on Sun Mar 27 10:38:19 PST 1994 by harrison

% m3_option ("-times")

import("libm3")
import("m3middle")
import("sysutils")

Module   ("Quake")
Module   ("QToken")
Module   ("QIdent")
Module   ("QScanner")
Module   ("QCode")
Module   ("QCompiler")
Module   ("QValue")
Table    ("QV", "Integer", "QValue")
Sequence ("QV", "QValue")
Module   ("QMachine")
Module   ("QVal")
Module   ("MxConfig")
Module   ("M3Path")
Module   ("QPromise")
Sequence ("QPromise", "QPromise")

interface("MxConfigC")
c_source("MxConfigC")

build_standalone ()
Library("m3quake")

ManPage ("quake","7")
