
%%XXDIR = { "WIN32" : "N:\\m3-sys", "POSIX" : "/proj/cmass/src.2/m3-sys" }
%%WORKDIR = XXDIR {OS_TYPE}
       
if not defined("BOOT")
  override ("m3core", ROOT & "/m3-libs")
  override ("libm3", ROOT & "/m3-libs")
end
override ("m3middle", ROOT & "/m3-sys")
