.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" Last modified on Fri Jul 17 09:54:00 1992 by mhb   
.nh
.TH match 1
.SH NAME
match \- a Q+D Zeus demo/game version of "Concentration"

.SH SYNTAX
match

To get things started, select "Game Board" in the browser labeled "Views." This
will create a top-level window called "Match.Game Board". Now, click
on the "GO" button, and start playing the game. To restart the game,
hit "GO"; to abort a game, hit "ABORT". It may take a few seconds before
the game is actually stopped. 

.SH DESCRIPTION
.B match
is a Zeus version of Concentration, a popular TV game show.
This hack provides hours of entertainment for 4-year olds.

.SH STUFF TO DO 
Lots. It would be nice if the board shuffled itself (but at
least one 4-year old did realize she was playing the same game), and if the
player could specifying the size of the board and clues wordlist.

.SH BUGS
Often, core is dumped when the program exits.

.SH AUTHOR OF OBJECT
Marc H. Brown and Steve Glassman

.SH AUTHOR OF DOCUMENTATION
Marc H. Brown


