% Imported into CM3 from PM3 by Darko Volaric July 2003
% This is a simplification of the previous makefile and does not
% handle automatic generation of the parser because Coco has not
% been ported. Be careful if you modify the generated parser files
% because someday someone might port Coco and you changes may
% be lost.

import("libm3")
import("deepcopy")

Module("SGML")
Module("SGMLPrint")
Module("FSM")
Interface("SGMLElement")
interface("SGMLCScanner")
interface("SGMLRep")
interface("SGMLC")
implementation("SGMLCS")
implementation("SGMLCP")
sequence("SGMLElement", "SGMLElement")

library("sgml")
