import("libm3")
import("m3na")
import("wavelib")

module("TestDaubechies")
module("TestTransition")
module("TestBSpline")
module("TestMatchWavelet")
module("TestCDFLifting")
implementation("Main")

program("test")
