import("libm3")
import("arithmetic")
import("wavelib")
import("bilist")

module("TestDaubechies")
module("TestTransition")
module("TestBSpline")
module("TestMatchWavelet")
module("TestCDFLifting")
module("TestTransform")
implementation("Main")

program("test")
