%m3back_debug = ""
%m3back_optimize = ""
%m3back_pic = ""
%m3back_unwind_table = "-fno-asynchronous-unwind-tables"

interface("Color")
module("Main2")
module("Main3")
implementation("Main")
build_standalone()
include ("../../Test.common")
