% Copyright 1996, Critical Mass, Inc.  All rights reserved.

import("libm3")

if SYSTEM_LIBS contains "ODBC"
  include_dir ("odbc")
else
  include_dir ("postgres95")
end

Interface ("DB")

if equal (TARGET, "ALPHA_OSF")
  % missing libpq.a => can't build local .so file ...
  build_standalone ()
end

Library ("db")
