% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Feb 23 14:06:31 PST 1995 by kalsow 
%      modified on Fri Nov  5 16:41:57 PST 1993 by detlefs
%      modified on Mon Jan 18 19:09:20 PST 1993 by muller

if defined("configure_system_libs")
  configure_system_libs()
end 

if SYSTEM_LIBS contains "LEX-YACC"
  if equal (TARGET, "HPPA")
    include_dir ("lex-yacc-HPPA")
  else
    include_dir ("lex-yacc")
  end
else if SYSTEM_LIBS contains "FLEX-BISON"
  include_dir ("flex-bison")
else
  error ("Unable to build m3tags without Lex&Yacc or Flex&Bison libraries.")
end end

source    ("parse.lex")
source    ("parse.yacc")
c_source  ("m3tags")
h_source  ("hash")
C_program ("m3tags")
ManPage   ("m3tags","1")

CompiledGnuemacs ("m3tags")
CompiledGnuemacs ("modula3")
CompiledGnuemacs ("ispell19-3.0")
% CompiledGnuemacs ("m3-debug")
% CompiledGnuemacs ("shell-compile")

