% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Makefile for netobj test program
% Last modified on Thu Feb 24 13:47:28 PST 1994 by wobber
%      modified on Mon Dec 20 14:14:37 PST 1993 by kalsow

if defined("AT_SRC") if AT_SRC m3_option("-O") end end 

import("netobj")
import("tcp")
import("libm3")

interface("Test")
module("XRd")
implementation("NetObjTest")
netobjv2("Test","T")
netobjv2("Test","Return")

build_standalone()

program("test")


