% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Makefile for netobject umbrella library
% Last modified on Fri Oct 28 16:39:06 PDT 1994 by kalsow
%      modified on Fri Feb 11 13:47:27 PST 1994 by wobber
%      modified on Tue May 18 22:58:27 PDT 1993 by mjordan
%      modified on Fri Feb 19 15:47:54 PST 1993 by owicki
%      modified on Thu Sep 17 16:24:58 PDT 1992 by evers

if defined ("AT_SRC") m3_option("-O") end

% m3_option ("-verbose")
% m3_option ("-keep")

import("m3middle")
import("libm3")
import("tcp")

if defined("_NETOBJ_OVERRIDE")
  template("netobj-ov")
end
template("netobj")

include_dir("netobjrt")
include_dir("tcpnetobj")

interface("NetObjMonInit")
module ("NetObjMon")

/*
netobjr(NetObjMon,T,NetObjMon)
netobjr(NetObjMon,Registry,NetObjMon)
*/

module("NetObjMon_T_v1")
module("NetObjMon_Registry_v1")

implementation("NetObj")

Library("m3netobj")
