
%%XXDIR = { "WIN32" : "h:\\new\\m3-libs", "POSIX" : "/proj/cmass/src.2/m3-libs" }
%%WORKDIR = XXDIR {OS_TYPE}
%%YYDIR = { "WIN32" : "h:\\new\\m3-comm", "POSIX" : "/proj/cmass/src.2/m3-comm" }
%%COMMDIR = YYDIR {OS_TYPE}

_NETOBJ_OVERRIDE = "T"
override ("libm3", ROOT & "/m3-libs")
override ("tcp", ROOT & "/m3-comm")
