% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Nov  1 09:09:31 PST 1994 by kalsow 

write(CR, "--- tests in ", getwd(), "---", CR)

import("libm3")
implementation("Test")
program("Test")


if defined("RUN")
  r = q_exec( "." & SL & "Test" )
  write( CR, "program returned ", r, CR )
end
