if not HasTrestle()
  build_standalone()
end

import ("obliq")
import("sharedobj")

%m3_option("-verbose")
if equal (TARGET, "SPARC") or equal (TARGET, "SOLgnu")
	build_standalone()
end
% what the programmer would write
Generic_interface("ShSequence")
Generic_interface("ShSequenceRep")
Generic_implementation("ShSequence")

template ("shsequence")

% Sequence (Atom, Atom)
% Sequence (Int,  Integer)

% ShSequence (Ref,  Refany)

% Sequence (Text, Text)
