if equal (OS_TYPE, "WIN32")
  override("sharedobj", "\\arm3")
  override("events", "\\arm3")
  override("rdwr", "\\arm3")
  override("debug", "\\arm3")
  override("obliqlibemb", "\\arm3")
else
  override("sharedobj", "/proj/graphics/arm3")
  override("events", "/proj/graphics/arm3")
  override("rdwr", "/proj/graphics/arm3")
  override("debug", "/proj/graphics/arm3")
  override("obliqlibemb", "/proj/graphics/arm3")
end
