/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Sun Aug 15 22:48:28 PDT 1993 by heydon                   */

/* m3overrides for /proj/m3/pkg/juno-compiler/tests/parser/src */

include(ROOT & "/m3overrides")
