#! /bin/csh -f
#
# Copyright (C) 1992, Digital Equipment Corporation 
# All rights reserved.
# See the file COPYRIGHT for a full description.
#
# Last modified on Mon Aug 16 10:49:11 PDT 1993 by heydon

set x = $1:r
set x = $x:r
echo "-$x:e"
