#! /bin/csh -f
#
# Copyright (C) 1992, Digital Equipment Corporation 
# All rights reserved.
# See the file COPYRIGHT for a full description.
#
# Last modified on Wed Jun  8 19:50:06 PDT 1994 by heydon

set arch = `/udir/heydon/libi/csh/m3arch`
set prog = ParserTest

if (-e ../$arch/$prog) then
  set newoutfile = /tmp/parsertest-$$.txt.out
  foreach outfile ($*)
    set infile = "$outfile:r".in
    echo ../$arch/$prog `option $infile` $infile '>' $newoutfile
    ../$arch/$prog `option $infile` $infile > $newoutfile
    echo "diff $outfile $newoutfile"
    diff $outfile $newoutfile
    rm $newoutfile
  end
else
  echo "Unknown host type \"$arch\""
endif
