import("libm3")

template("root")


generic_module("RootBasic")
RootBasic("Real",               "RealPolynomialBasic",               "RealBasic")
RootBasic("LongReal",           "LongRealPolynomialBasic",           "LongRealBasic")
RootBasic("Extended",           "ExtendedPolynomialBasic",           "ExtendedBasic")
RootBasic("RealComplex",        "RealComplexPolynomialBasic",        "RealComplexBasic")
RootBasic("LongRealComplex",    "LongRealComplexPolynomialBasic",    "LongRealComplexBasic")
RootBasic("ExtendedComplex",    "ExtendedComplexPolynomialBasic",    "ExtendedComplexBasic")
RootBasic("Integer32",          "Integer32PolynomialBasic",          "Integer32Basic")
RootBasic("BigInteger",         "BigIntegerPolynomialBasic",         "BigIntegerBasic")

generic_module("RootApproximation")
RootApproximation("Real",     "RealComplexPolynomialBasic",     "RealComplexRootBasic",     "RealComplexTrans",     "RealComplexFast",     "RealRootBasic",     "RealTrans",     "RealBasic")
RootApproximation("LongReal", "LongRealComplexPolynomialBasic", "LongRealComplexRootBasic", "LongRealComplexTrans", "LongRealComplexFast", "LongRealRootBasic", "LongRealTrans", "LongRealBasic")
RootApproximation("Extended", "ExtendedComplexPolynomialBasic", "ExtendedComplexRootBasic", "ExtendedComplexTrans", "ExtendedComplexFast", "ExtendedRootBasic", "ExtendedTrans", "ExtendedBasic")
