import("libm3")

template("root")


generic_module("RootBasic")
RootBasic("Real",               "Real",            "Basic")
RootBasic("LongReal",           "LongReal",        "Basic")
RootBasic("Extended",           "Extended",        "Basic")
RootBasic("RealComplex",        "RealComplex",     "Basic")
RootBasic("LongRealComplex",    "LongRealComplex", "Basic")
RootBasic("ExtendedComplex",    "ExtendedComplex", "Basic")
RootBasic("Integer32",          "Integer32",       "Basic")
RootBasic("BigInteger",         "BigInteger",      "Basic")

generic_module("RootApproximation")
RootApproximation("Real",     "Real",     "Basic", "Fast")
RootApproximation("LongReal", "LongReal", "Basic", "Fast")
RootApproximation("Extended", "Extended", "Basic", "Fast")
