.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" Last modified on Tue Jun 16 23:36:40 PDT 1992 by muller
.\"      modified on Thu Jan  2 13:26:53 PST 1992 by mhb
.nh
.TH Calculator 1
.SH NAME
Calculator \- graphical (FormsVBT) integer calculator

.SH SYNTAX
.B Calculator

.SH DESCRIPTION 
.B Calculator 
is a simple calculator that can perform addition, 
subtraction, multiplication, and division in integer space. 

Its source code is sufficiently simple, yet interesting, that 
it makes for a good FormsVBT example to study.

.SH AUTHOR OF OBJECT
Marc H. Brown

.SH AUTHOR OF DOCUMENTATION
Marc H. Brown


