/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Wed Dec 22 15:50:13 PST 1993 by mhb     */
/*      modified on Tue Jun 16 18:26:52 PDT 1992 by muller  */

import         ("formsvbt")

ManPage        ("Calculator", 1)
resource       ("Calculator.fv")
bundle         ("CalculatorBundle")
implementation ("Calculator")
Program        ("Calculator")
