
% import netobj to bring in 
% network object libraries

import("netobj")

% for each network object I.T you must call
% 		netobj(I,T)

interface("Bank")
netobj("Bank", "T")
netobj("Bank", "Account")

library("netobj-interface")

% the name of the library created


