% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Feb  7 11:30:11 PST 1995 by kalsow

import("libm3")
import("tcp")

readonly _JVPieces = {
% "ALPHA_OSF"  : "osf1",
  "DS3100"     : "ultrix",
  "DS3100_OSF" : "osf1"
}

if not defined ("JV_TARGET")  JV_TARGET = TARGET  end
if _JVPieces contains JV_TARGET
  include_dir (_JVPieces {JV_TARGET})
else
  include_dir("generic")
end


Interface ("JVBuffer")
Interface ("JVSink")
Interface ("Jv")
implementation ("Jv")
Module    ("Jvs")
Module    ("Jva")
Interface ("JvsProtocol")
Interface ("JvaProtocol")
Interface ("jvprotocol")
Interface ("JvsBuffer")
Module    ("JVFromSource")
Module    ("JVFromDecomp")
Module    ("JVConverter")
Interface ("JVConverterF")
Module    ("JVDecomp")
Module    ("JVAudio")

Module    ("JVSinkPool")
Module    ("JVDecompPool")

Library("jvideo")
