if not equal (OS_TYPE, "WIN32")

import("libm3")
import("ktoklib")

resource("tokform.i3")
resource("tokform.m3")
resource("tokform.type")
resource("tokform.case")
bundle("tokformBundle")

%module("tokformBundle")
implementation("Main")
build_standalone()
Program("ktok")

end
