.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" File: m3.1
.\" Last modified on Wed Mar 23 17:09:09 1994 by luca
.nh
.TH obliqsrv-std 1
.SH Name
Obliq Server-std \- start an Obliq server

.SH Syntax
.B obliqsrv-std
[options] &

.SH Description

An Obliq server linked with standard libraries. See "obliqsrv".

.SH SRC Documentation

    /src/hypertext/SRC/obliq/Obliq.html    (quick start, for mosaic)

.SH External Site Documentation

    ...obliqdoc/src/Obliq.html/           (quick start, for mosaic)
    ...obliqdoc/src/ObliqPaper.ps         (paper/manual, for printing)
    ...obliqdoc/src/ObliqPaper-html/ObliqPaper.html (same, for mosaic)
    ...obliqdoc/src/Example/*.obl         (example programs)

.SH Files

    /tmp/obliqsrvstd.log
    /tmp/obliqsrvui.log

.SH See Also

    obliqsrv

.SH Author Of Object

  Luca Cardelli

.SH Author Of Documentation

  Luca Cardelli

