/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Wed Apr 24 18:00:45 PDT 1996 by heydon                   */

/* m3makefile for /proj/m3/pkg/juno-machine/tests/nonlinear/src */

import		("libm3")
import		("juno-machine")
export_interface("RedundantSolve")
export_interface("NonLinearSolveRep")

implementation	("NonLinearTest")
program		("NonLinearTest")
