
override("miniscan", ".." & SL & ".." & SL & "..")

import("libm3")

import("sysutils")
import("miniscan")

implementation("Main")

build_standalone()
program("tscan")

if defined("RUN")
  r = q_exec( "." & SL & "tscan" )
  write( CR, "program returned ", r, CR )
end
