module ("Grisu")
module ("CachedPowers")
module ("SimFP")
module ("IEEE")

% temporarily disable Grisu for NT386 until problems investigated

local readonly proc MakeGrisuDisable(Name, Value) is
    > Name & ".i3.tmp" in
        write("INTERFACE " & Name & ";\n")
        write("CONST Value = " & Value & ";\n")
        write("END " & Name & ".")
        derived_interface(Name, HIDDEN)
    end
    cp_if(Name & ".i3.tmp", Name & ".i3")
end

if equal(TARGET, "NT386")
  MakeGrisuDisable("GrisuDisable", "TRUE")
else
  MakeGrisuDisable("GrisuDisable", "FALSE")
end
