% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Sun Jun 20 20:55:33 PDT 1993 by harrison
%      modified on Mon Jun  8 16:01:57 PDT 1992 by mcjones

Module("Atom")
% implementation("AtomWeak")
