% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Makefile for net object runtime package
% Last modified on Thu Apr 13 13:39:24 PDT 1995 by kalsow
%      modified on Tue Feb  7 14:57:44 PST 1995 by wobber
%      modified on Fri Feb 19 15:39:36 PST 1993 by owicki
%      modified on Fri Sep 11 15:45:49 PDT 1992 by evers


include_dir (OS_TYPE)

Interface ("NetObj")
Interface ("NetObjNotifier")
interface ("NetObjRep")
Interface ("StubConn")
module ("NetObjRT")

module ("ListPkl")
module("AtomPkl")

Interface ("NetStream")
Module ("StubLib")
module ("WireRep")
interface ("Protocol")
module ("SpaceID")
interface ("NetObjInit")
Interface ("DirtyElem")
interface ("ObjElem")
interface ("Transport")
interface ("TransportUtils")
interface ("TransportRegistry")
interface ("NGCMonitor")
interface ("SpecialObj")
interface ("Voucher")
implementation ("AgentStubs")
implementation ("VoucherStubs")
module ("ObjTbl")
module ("DirtyTbl")
module ("FPRefTbl")
