#!/bin/sh

RSYNCOPTS="${RSYNCOPTS:- -L}"
SHIP="$0"
if [ -z "${REMOTE}" ] ; then
  REMOTE="root@www.elegosoft.com:/var/www/elegosoft.com/cm3/doc"
  #REMOTE="${REMOTE} m3@www.m3.org:html/cm3"
fi

usage() {
  echo ""
  echo "$SHIP [-n][-v]"
  echo ""
  echo "  update the web servers at \$REMOTE,"
  echo ""
  for r in ${REMOTE}; do
    echo "    ${r},"
  done
  echo ""
  echo "  recursively using rsync over ssh."
  echo ""
  echo "Options:"
  echo ""
  echo "  -n     no action (do nothing)"
  echo "  -v     be verbose"
  echo ""
}

if [ "$1" = "-h" ] ; then
  usage
  exit 0
fi
N=""
NOPT=""
if [ "$1" = "-n" ] ; then
  N="echo"
  NOPT="-n"
  shift
fi
VERBOSE=""
if [ "$1" = "-v" ] ; then
  VERBOSE="-v"
  shift
fi


for r in ${REMOTE}; do
  if [ "x${VERBOSE}" = x-v ] ; then
    echo "updating remote site ${r}..."
  fi
  RSYNC_RSH=ssh rsync ${NOPT} ${VERBOSE} -C ${RSYNCOPTS} -ruptl \
    --exclude=CVS \
    --exclude=PkgTags \
    --exclude=PkgDesc \
    --exclude=tmp \
    --exclude=\*~ \
    --exclude=\*.flc \
    --exclude=www-install.sh \
    --exclude=ship-cm3-www \
    --exclude=ship-cm3-testing \
    * ${r}
done
