% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Oct 28 14:25:54 PST 1996 by heydon
%      modified on Tue Oct 27 17:53:57 PST 1992 by gnelson
%
% m3makefile for /proj/m3/pkgs/juno-app/pkl-fonts/src

% imported packages
import		("libm3")
import		("vbtkit")

% generic instantiation
table		("TextIntSeq", "Text", "IntSeq")

% private interfaces
interface	("PSFont")
interface	("JunoValue")
interface	("JunoRect")
implementation	("PklFonts")

% include resource files
include_dir	("rsrc")

% extra compiler options
m3_option	("-times")

% the "PklFonts" executable
program		("PklFonts")
