% (* ----------------------------------------------------------------------1- *)
% (* File m3makefile for Modula3 compiler test p287                           *)
% (* Copyright 2021, Rodney M. Bates.                                         *)
% (* rodney.m.bates@acm.org                                                   *)
% (* Licensed under the MIT license.                                          *)
% (* ----------------------------------------------------------------------2- *)

import("libm3")

interface("Named")
module("Def")
module("Display")
module("Second")

build_standalone ()

implementation ("Main")
program ("pgm")
