#! /bin/csh

setenv ROOT    /proj/cmass/src.2
setenv CM3     /proj/cmass/install/$M3TARGET/bin/cm3
setenv INSTALL /proj/cmass/install.2/$M3TARGET

cd $ROOT/m3-libs

# ( cd m3core ; $CM3 ; $CM3 -ship )
# ( cd libm3  ; $CM3 ; $CM3 -ship )
# ( cd tcp    ; $CM3 ; $CM3 -ship )

cd $ROOT/m3-sys

( cd cmkey     ; $CM3 )
( cd m3middle  ; $CM3 )
( cd m3linker  ; $CM3 -x )
( cd m3front   ; $CM3 -x )
( cd m3quake   ; $CM3 -x )
( cd cm3       ; $CM3 -x )
# ( cd m3tools   ; $CM3 -x )
# ( cd reactor   ; $CM3 -x )
# ( cd cminstall ; $CM3 -x )

cp cm3/$M3TARGET/cm3      $INSTALL/bin/cm3
cp cm3/$M3TARGET/cm3.cfg $INSTALL/bin/cm3.cfg

# cp reactor/$M3TARGET/reactor $INSTALL/bin/reactor
