#! /bin/csh

setenv ROOT /proj/cmass/src.1
setenv CM3  /proj/cmass/install/$M3TARGET/bin/cm3

cd $ROOT/m3-libs

# ( cd m3core ; $CM3 ; $CM3 -ship )
# ( cd libm3  ; $CM3 ; $CM3 -ship )
# ( cd tcp    ; $CM3 ; $CM3 -ship )

cd $ROOT/m3-sys

( cd m3middle  ; $CM3 )
( cd m3linker  ; $CM3 -x )
( cd m3front   ; $CM3 -x )
( cd m3quake   ; $CM3 -x )
( cd m3tools   ; $CM3 -x )
( cd cmexpire  ; $CM3 -x )
( cd cm3       ; $CM3 -x -Ddemo ; $CM3 -x )
( cd reactor   ; $CM3 -x -Ddemo ; $CM3 -x )
( cd cminstall ; %CM3 -x )
