#! /bin/csh -x

## setenv M3TARGET LINUXELF

setenv SOURCE  "/proj/cmass/src.1"
setenv INSTALL "/proj/cmass/install/$M3TARGET"
setenv BIN     "$INSTALL/bin"
setenv DOC     "$INSTALL/doc"
setenv MAN1    "$INSTALL/man/man1"

cd $SOURCE

(cd m3-libs/m3core           ; cm3 -silent && cm3 -ship -silent )
(cd m3-libs/libm3            ; cm3 -silent && cm3 -ship -silent )
(cd m3-libs/digraph          ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-libs/parseparams      ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-libs/realgeometry     ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-libs/set              ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-libs/slisp            ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-libs/table-list       ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-libs/tempfiles        ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )

(cd m3-tools/m3bundle        ; cm3 -silent && cp $M3TARGET/m3bundle $BIN ; cp $M3TARGET/m3bundle.1 $MAN1 ; rm -rf $M3TARGET )

(cd m3-tools/coverage        ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-tools/m3tk            ; cm3  )
(cd m3-tools/mtex            ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )

(cd m3-comm/tcp              ; cm3 -silent && cm3 -ship -silent )
(cd m3-comm/netobj           ; cm3 -silent && cm3 -ship -silent )
(cd m3-comm/netobjd          ; cm3 -silent && cp $M3TARGET/netobjd $BIN ; cp $M3TARGET/netobjd.1 $MAN1 ; rm -rf $M3TARGET )
(cd m3-comm/serial           ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-comm/stubgen          ; cm3 -x -silent && cp $M3TARGET/stubgen $BIN ; cp $M3TARGET/stubgen.1 $MAN1 ; rm -rf $M3TARGET )

(cd m3-sys/m3middle          ; cm3 )
(cd m3-sys/m3linker          ; cm3 -x )
(cd m3-sys/m3front           ; cm3 -x )
(cd m3-sys/m3quake           ; cm3 -x )
(cd m3-sys/cmexpire          ; cm3 )
(cd m3-sys/m3tools           ; cm3 -x )
(cd m3-sys/cm3               ; cm3 -x -Ddemo ; cm3 -x  && cp $M3TARGET/cm3 $DOC/intro.doc ; cp $M3TARGET/cm3demo $BIN/cm3 )
(cd m3-sys/cminstall         ; cm3 -x )
(cd m3-sys/reactor           ; cm3 -x -Ddemo -silent ; cm3 -x -silent && cp $M3TARGET/reactor $DOC/preface.doc ; cp $M3TARGET/reactdemo $BIN/reactor )

(cd m3-tools/gnuemacs        ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-tools/pp              ; cm3 -silent && cp $M3TARGET/m3pp $BIN ; cp $M3TARGET/m3pp.1 $MAN1 ; rm -rf $M3TARGET )

(cd m3-db/postgres95         ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-db/db                 ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-db/smalldb            ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-db/stable             ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-db/stablegen          ; cm3 -x -silent && cp $M3TARGET/stablegen $BIN ; cp $M3TARGET/stablegen.1 $MAN1 ; rm -rf $M3TARGET )

(cd m3-www/http              ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-www/web               ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )

(cd m3-ui/X11R4              ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-ui/motif              ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-ui/PEX                ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-ui/opengl             ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )
(cd m3-ui/ui                 ; cm3 -silent && cm3 -ship -silent )
(cd m3-ui/vbtkit             ; cm3 -silent && cm3 -ship -silent ; rm -rf $M3TARGET )

(cd m3-tools/recordheap      ; cm3 -silent && cp src/recordheap $BIN ; cp $M3TARGET/recordheap.1 $MAN1 ; rm -rf $M3TARGET )
(cd m3-tools/replayheap      ; cm3 -silent && cp $M3TARGET/replayheap $BIN ; cp $M3TARGET/replayheap.1 $MAN1 ; rm -rf $M3TARGET )
(cd m3-tools/showheap        ; cm3 -silent && cp $M3TARGET/showheap $BIN ; cp $M3TARGET/showheap.1 $MAN1 ; rm -rf $M3TARGET )
(cd m3-tools/shownew         ; cm3 -silent && cp $M3TARGET/shownew $BIN ; cp $M3TARGET/shownew.1 $MAN1 ; rm -rf $M3TARGET )
(cd m3-tools/showthread      ; cm3 -silent && cp $M3TARGET/showthread $BIN ; cp $M3TARGET/showthread.1 $MAN1 ; rm -rf $M3TARGET )


