#! /bin/csh

cd /proj/cmass2

tar -cf - -C jvm/unix  jvm jvm/ALPHA_OSF | gzip > jvm-CD/jvm-ALPHA_OSF.tgz
tar -cf - -C jvm/unix  jvm jvm/HPPA      | gzip > jvm-CD/jvm-HPPA.tgz
tar -cf - -C jvm/unix  jvm jvm/IRIX5     | gzip > jvm-CD/jvm-IRIX5.tgz
tar -cf - -C jvm/unix  jvm jvm/LINUXELF  | gzip > jvm-CD/jvm-LINUXELF.tgz
tar -cf - -C jvm/win32 jvm jvm/NT386     | gzip > jvm-CD/jvm-NT386.tgz
tar -cf - -C jvm/unix  jvm jvm/SOLgnu    | gzip > jvm-CD/jvm-SOLgnu.tgz
tar -cf - -C jvm/unix  jvm jvm/SOLsun    | gzip > jvm-CD/jvm-SOLsun.tgz
tar -cf - -C jvm/unix  jvm jvm/SPARC     | gzip > jvm-CD/jvm-SPARC.tgz

