#! /bin/csh -x

## setenv M3TARGET LINUXELF

setenv SOURCE  "/proj/cmass/src.1"
setenv INSTALL "/proj/cmass/install/$M3TARGET"
setenv BIN     "$INSTALL/bin"
setenv DOC     "$INSTALL/doc"
setenv MAN1    "$INSTALL/man/man1"

cd $SOURCE

fix_nl m3-libs/m3core/src
fix_nl m3-libs/libm3/src
fix_nl m3-libs/digraph/src
fix_nl m3-libs/parseparams/src
fix_nl m3-libs/realgeometry/src
fix_nl m3-libs/set/src
fix_nl m3-libs/slisp/src
fix_nl m3-libs/table-list/src
fix_nl m3-libs/tempfiles/src

fix_nl m3-tools/coverage/src
fix_nl m3-tools/m3tk/src
fix_nl m3-tools/mtex/src

fix_nl m3-comm/tcp/src
fix_nl m3-comm/netobj/src
fix_nl m3-comm/netobjd/src
fix_nl m3-comm/serial/src
fix_nl m3-comm/stubgen/src

fix_nl m3-sys/cm3/src
fix_nl m3-sys/cminstall/src
fix_nl m3-sys/reactor/src

fix_nl m3-tools/m3bundle/src
fix_nl m3-tools/gnuemacs/src
fix_nl m3-tools/pp/src

fix_nl m3-db/db/src
fix_nl m3-db/smalldb/src
fix_nl m3-db/stable/src
fix_nl m3-db/stablegen/src

fix_nl m3-www/http/src
fix_nl m3-www/web/src

fix_nl m3-ui/X11R4/src
fix_nl m3-ui/motif/src
fix_nl m3-ui/PEX/src
fix_nl m3-ui/opengl/src
fix_nl m3-ui/ui/src
fix_nl m3-ui/vbtkit/src

fix_nl m3-tools/recordheap/src
fix_nl m3-tools/replayheap/src
fix_nl m3-tools/showheap/src
fix_nl m3-tools/shownew/src
fix_nl m3-tools/showthread/src


