#! /bin/sh

ROOT=/proj/cmass/src.1
SYS=$ROOT/m3-sys
INSTALL=/proj/cmass/install/$M3TARGET
SHIP=/proj/cmass/CD

if [ ! -d $SHIP ]; then mkdir $SHIP ; fi
cd $SHIP

if [ ! -d SOURCE ]; then mkdir SOURCE ; fi
if [ ! -d BINARY ]; then mkdir BINARY ; fi
if [ ! -d CONTRIB ]; then mkdir CONTRIB ; fi


cp -r $SYS/cdroot/* .

for TARGET in ALPHA_OSF HPPA IRIX5 SOLgnu SOLsun SPARC ; do
  cp $SYS/cminstall/$TARGET/cminstall BINARY/$TARGET/CMINSTAL
done


