#! /bin/sh

INSTALL=/proj/cmass/install
CDBIN=/proj/cmass/CD/BINARY

df $CDBIN
echo

# convert 8+3 CD-ROM names to M3 platform names
( cd $CDBIN ; mv ALPHAOSF ALPHA_OSF ; mv SOLGNU SOLgnu ; mv SOLSUN SOLsun )

# pack each platform's tar file 
for TARGET in ALPHA_OSF HPPA IRIX5 LINUXELF NT386 SOLgnu SOLsun SPARC ; do
  TARFILE=$CDBIN/$TARGET/SYSTEM.TGZ
  echo
  echo $TARGET ...
  rm -rf $TARFILE
  ( cd $INSTALL/$TARGET ;\
    rm doc examples ;\
    tar -cf - . | gzip > $TARFILE ;\
    ln -s /proj/cmass/src.1/m3-docs/doc       doc ;\
    ln -s /proj/cmass/src.1/m3-docs/examples  examples ;\
  )
  chmod 0664 $TARFILE
  ls -l $TARFILE
done

# convert M3 platform names back to 8+3 CD-ROM names
( cd $CDBIN ; mv ALPHA_OSF ALPHAOSF ; mv SOLgnu SOLGNU ; mv SOLsun SOLSUN )

echo
df $CDBIN
echo
echo done.


