#! /bin/csh -x

setenv ROOT "/proj/cmass/src.1"
setenv SAVE $ROOT/src-save
setenv CDSRC "/proj/cmass/CD/SOURCE"
cd $ROOT

tar -cf - \
  m3-libs/m3core/src \
  m3-libs/m3core/tests \
  m3-libs/libm3/src \
  m3-libs/libm3/tests \
  m3-libs/digraph/src \
  m3-libs/parseparams/src \
  m3-libs/realgeometry/src \
  m3-libs/set/src \
  m3-libs/slisp/src \
  m3-libs/slisp/tests \
  m3-libs/table-list/src \
  m3-libs/tempfiles/src \
  m3-libs/dps/src \
  m3-libs/dps/test \
  m3-libs/tcl/src \
  m3-libs/tcl/test \
| gzip > $CDSRC/M3-LIBS.TGZ

tar -cf - \
  m3-tools/coverage/src \
  m3-tools/m3tk/src \
  m3-tools/mtex/src \
  m3-tools/hexdump/src \
  m3-tools/cmpdir/src \
  m3-tools/m3bundle/src \
  m3-tools/gnuemacs/src \
  m3-tools/m3tohtml/src \
  m3-tools/m3totex/src \
  m3-tools/pp/src \
  m3-tools/recordheap/src \
  m3-tools/rehearsecode/src \
  m3-tools/replayheap/src \
  m3-tools/showheap/src \
  m3-tools/shownew/src \
  m3-tools/showthread/src \
| gzip > $CDSRC/M3-TOOLS.TGZ

tar -cf - \
  m3-comm/tcp/src \
  m3-comm/netobj/src \
  m3-comm/netobj/tests \
  m3-comm/netobjd/src \
  m3-comm/serial/src \
  m3-comm/stubgen/src \
  m3-comm/tapi/src \
| gzip > $CDSRC/M3-COMM.TGZ

(cd m3-sys ; tar -cf - \
  m3cc/src \
  m3cc/gcc-2.7.2 \
  m3cc/gcc \
| gzip > $CDSRC/M3CC.TGZ )

(cd m3-sys ; tar -cf - \
  m3gdb/src \
  m3gdb/gdb-4.16 \
  m3gdb/gdb \
| gzip > $CDSRC/M3GDB.TGZ )

tar -cf - \
  m3-db/postgres95/src \
  m3-db/postgres95/test \
  m3-db/pgodbc/src \
  m3-db/pgodbc/test \
  m3-db/odbc/src \
  m3-db/odbc/test \
  m3-db/db/src \
  m3-db/db/test \
  m3-db/smalldb/src \
  m3-db/stable/src \
  m3-db/stable/test \
  m3-db/stable/example \
  m3-db/stablegen/src \
| gzip > $CDSRC/M3-DB.TGZ

tar -cf - \
  m3-www/http/src \
  m3-www/web/src \
  m3-www/proxy/src \
  m3-www/webcat/src \
  m3-www/deckscape/src \
  m3-www/webscape/src \
| gzip > $CDSRC/M3-WWW.TGZ

tar -cf - \
  m3-ui/X11R4/src \
  m3-ui/motif/src \
  m3-ui/motif/tests \
  m3-ui/PEX/src \
  m3-ui/opengl/src \
  m3-ui/ui/src \
  m3-ui/ui/test \
  m3-ui/bicycle/src \
  m3-ui/vbtkit/src \
  m3-ui/images/src \
  m3-ui/jvideo/src \
  m3-ui/videovbt/src \
  m3-ui/formsvbtpixmaps/src \
  m3-ui/formsvbt/src \
  m3-ui/mg/src \
  m3-ui/mgkit/src \
  m3-ui/anim3D/src \
  m3-ui/m3zume/src \
  m3-ui/codeview/src \
  m3-ui/zeus/src \
  m3-ui/formsedit/src \
  m3-ui/webvbt/src \
  m3-ui/ui-tests \
| gzip > $CDSRC/M3-UI.TGZ


tar -cf - \
  m3-obliq/synloc/src \
  m3-obliq/synex/src \
  m3-obliq/metasyn/src \
  m3-obliq/obliqrt/src \
  m3-obliq/obliqparse/src \
  m3-obliq/obliqprint/src \
  m3-obliq/obliq/src \
  m3-obliq/obliqlibm3/src \
  m3-obliq/obliqlibui/src \
  m3-obliq/obliqlibanim/src \
  m3-obliq/obliqlib3D/src \
  m3-obliq/obliqbinmin/src \
  m3-obliq/obliqbinstd/src \
  m3-obliq/obliqbinui/src \
  m3-obliq/obliqbinanim/src \
  m3-obliq/obliqbin3D/src \
  m3-obliq/obliqsrvstd/src \
  m3-obliq/obliqsrvui/src \
  m3-obliq/visualobliq/src \
  m3-obliq/voquery/src \
  m3-obliq/vocgi/src \
  m3-obliq/vorun/src \
| gzip > $CDSRC/M3-OBLIQ.TGZ


tar -cf - \
  m3-games/tetris/src \
  m3-games/badbricks/src \
  m3-games/solitaire/src \
  m3-games/fours/src \
  m3-games/columns/src \
| gzip > $CDSRC/M3-GAMES.TGZ

tar -cf - \
  m3-demo/calculator/src \
  m3-demo/cube/src \
  m3-demo/fisheye/src \
  m3-demo/mentor/src \
  m3-demo/sharedboard \
  m3-demo/dpsslides/src \
  m3-demo/sil/src \
| gzip > $CDSRC/M3-DEMO.TGZ

tar -cf - \
  m3-pkgtools/pkgobj/src \
  m3-pkgtools/pkgtool/src \
  m3-pkgtools/pkgsrv/src \
  m3-pkgtools/pkgq/src \
  m3-pkgtools/pkgfprint/src \
| gzip > $CDSRC/M3-PKGTL.TGZ

tar -cf - \
  m3-mail/llscan/src \
  m3-mail/postcard/src \
  m3-mail/webcard/src \
| gzip > $CDSRC/M3-MAIL.TGZ

tar -cf - \
  m3-lectern/ocr/src \
  m3-lectern/lecterndoc/src \
  m3-lectern/lecternclient/src \
  m3-lectern/lecterntohtml/src \
  m3-lectern/lectern/src \
  m3-lectern/buildlectern/src \
  m3-lectern/editlectern/src \
| gzip > $CDSRC/M3-LCTRN.TGZ


