#! /bin/csh

setenv ROOT    /proj/cmass/src.2
setenv SYS     $ROOT/m3-sys
setenv INSTALL /proj/cmass/install.2/$M3TARGET

cp $SYS/cm3/$M3TARGET/cm      $INSTALL/bin/cm3
cp $SYS/cm3/$M3TARGET/cm3.cfg $INSTALL/bin/cm3.cfg

cp $SYS/reactor/$M3TARGET/reactor $INSTALL/bin/reactor
