
% M3 = "H:\\m3\\compiler\\m3\\nt386\\m3"

% m3_option("-commands")
% m3_option("-verbose")
% m3_option("-keep")

import ("libm3")
import ("db")

% implementation ("Demo")
% implementation ("Demo2")
 implementation ("Demo3")
% implementation ("Demo4")
% implementation ("Demo5")

program ("Demo")
