% Copyright (C) 1995, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%

if not HasTrestle()
  build_standalone()
end

import ("ui")
import ("netobj")
import ("formsvbt")

Module ("Item")
List   ("Item", "Item")
Table  ("Item", "Integer", "Item")
Module ("Trans")

Interface ("ItemClass")
Interface ("Focus")
Module	  ("PointR")
Module	  ("RectR")
Module	  ("RuleItem")
Module	  ("TextItem")
Table	  ("Font", "Text", "Font")
Module	  ("FontCache")
Module	  ("ItemFont")

Interface ("Callback")
Module    ("ClientInfo")
Interface ("Board")
Interface ("BoardServer")

Netobj ("Board", "T")
Netobj ("BoardServer", "T")
Netobj ("ClientInfo", "T")
Netobj ("Callback", "T")

Library ("board")
