.\" Copyright (C) 1995, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" Last modified on Tue Aug 22 12:08:23 PDT 1995 by najork
.nh
.TH obliq-3D 1
.SH NAME
obliq-3D \- a 3D animation system

.SH SYNTAX
obliq-3D

.SH DESCRIPTION

obliq-3D is an Obliq interpreter extended for describing 3D animations.
The system is described in SRC Report 129, "Obliq-3D Reference Manual
and Tutorial". This report is available in Lectern and in Postscript format:
.PP
http://src-www.pa.dec.com/SRC/virtualpaper/cgi-bin/relay?/src/vp/com/dec/src/report/SRC-129.lect
.PP
http://gatekeeper.dec.com/pub/DEC/SRC/research-reports/abstracts/src-rr-129.html
.PP


.SH "SEE ALSO"

Additional information can be found on the 3D animation home page:
.PP
http://src-www.pa.dec.com/SRC/3D-animate/home.html (Internal)
.PP
http://www.research.digital.com/SRC/3D-animate (External)

.SH AUTHOR 

Marc Najork
