/* Makefile for tcp library (POSIX) */
/* Copyright 1993 Digital Equipment Corporation. */
/* Distributed only by permission. */
/* Last modified on Thu Feb  9 15:55:57 PST 1995 by wobber     */
/* $Id: m3makefile,v 1.3 2009-04-12 05:36:02 jkrell Exp $ */

%Interface("SupTCPPosix")
%implementation("SupTCP")
interface("SupTCPHack")
interface("SockOpt")

if equal (TARGET, "ALPHA_OSF") or equal(TARGET, "DS3100")
   implementation("SupTCPHack")
else
   implementation("SupTCPHackNull")
end

if equal(TARGET, "FreeBSD2") or equal(TARGET, "FreeBSD2p")
   implementation("SockOptFBSD")
else
   implementation("SockOptOther")
end
