% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Sep 28 18:43:38 PDT 1994 by glassman
%      modified on Wed Dec 22 16:22:13 PST 1993 by kalsow

import ("libm3")
import ("tcp")

Module ("Web")
Library ("web")
