% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Fri Jun 18 13:21:39 PDT 1993 by harrison
%      modified on Thu May  6 12:17:08 PDT 1993 by muller

Interface ("Csetjmp")
Interface ("Cstdio")
Interface ("Cstring")

