% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Fri Jan 13 15:13:42 PST 1995 by najork
%      modified on Fri Oct 28 17:11:16 PDT 1994 by kalsow
%      modified on Tue Oct  5 18:17:24 PDT 1993 by sfreeman

Module("Completion")
Module("Picture")
Interface("PictureRep")

generic_implementation ("FreeList")

sequence("Completion", "Completion")
