import("libm3")

template("findzero")
template("interpolation")
template("eulersum")


generic_module("FindZero")
FindZero("Real",     "RealTrans",     "RealBasic")
FindZero("LongReal", "LongRealTrans", "LongRealBasic")
FindZero("Extended", "ExtendedTrans", "ExtendedBasic")

generic_module("Interpolation")
Interpolation("Real",     "RealBasic",     "RealTrans",     "RealBasic")
Interpolation("LongReal", "LongRealBasic", "LongRealTrans", "LongRealBasic")
Interpolation("Extended", "ExtendedBasic", "ExtendedTrans", "ExtendedBasic")
Interpolation("LongRealComplex",    "LongRealComplexFast",    "LongRealTrans", "LongRealBasic")
Interpolation("LongRealVector",     "LongRealVector",         "LongRealTrans", "LongRealBasic")
Interpolation("LongRealMatrix",     "LongRealMatrixFast",     "LongRealTrans", "LongRealBasic")
Interpolation("LongRealPolynomial", "LongRealPolynomialFast", "LongRealTrans", "LongRealBasic")

generic_module("EulerSum")
EulerSum("Real",     "RealTrans",     "RealBasic")
EulerSum("LongReal", "LongRealTrans", "LongRealBasic")
EulerSum("Extended", "ExtendedTrans", "ExtendedBasic")
