import("libm3")

template("findzero")
template("interpolation")
template("eulersum")


generic_module("FindZero")
FindZero("Real",     "RealBasic")
FindZero("LongReal", "LongRealBasic")
FindZero("Extended", "ExtendedBasic")

generic_module("Interpolation")
Interpolation("Real",               "Real",     "Basic", "Basic")
Interpolation("LongReal",           "LongReal", "Basic", "Basic")
Interpolation("Extended",           "Extended", "Basic", "Basic")
Interpolation("LongRealComplex",    "LongReal", "Basic", "")
Interpolation("LongRealVector",     "LongReal", "Basic", "")
Interpolation("LongRealMatrix",     "LongReal", "Basic", "")
Interpolation("LongRealPolynomial", "LongReal", "Basic", "")

generic_module("EulerSum")
EulerSum("Real",     "Real",     "Basic")
EulerSum("LongReal", "LongReal", "Basic")
EulerSum("Extended", "Extended", "Basic")
