% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Jul 14 13:59:16 PDT 1994 by mcjones
%      modified on Mon Aug  2 11:57:40 PDT 1993 by kalsow
%      modified on Fri Jun 18 17:38:56 PDT 1993 by muller
%      modified on Thu Jun 17 19:14:36 PDT 1993 by harrison
%      modified on Tue Feb  2 20:40:02 PST 1993 by mjordan


Interface("OSError")
Interface("File")
Interface("RegularFile")
Interface("Pipe")
Interface("Pathname")
Interface("FS")
Interface("Process")
Interface("Terminal")

/* The following only initialize the File.Type variables: */
implementation("FS")
implementation("Terminal")
implementation("RegularFile")
implementation("Pipe")
