/* $Id: m3makefile,v 1.3 2005/11/24 06:29:54 mika Exp $ */
import ("libm3")
import ("cit_util")
import ("set")

Module("Voronoi")

c_source("edgelist")
c_source("geometry")
c_source("heap")
c_source("memory")
c_source("mod3_main")
c_source("output")
c_source("voronoi")
c_source("mymalloc")
c_source("defs")

library("voronoi")