
include(".." & SL & ".." & SL & "quake.elego")

import("libm3")
import("parseparams")
import("vbtkit")

import("sysutils")
import("graphicutils")
import("fileinfo")
import("pkgversions")
import("pkg_vc")
import("compactrc")

import("compact-copyright")
%if defined("ComPactDemo")
%  import("compact-demo")
%else
%  import("no-demo")
%end

resource("compactrc")
resource("pkgvm.desc")
resource("pkgvm.help")
bundle("PkgVMBundle")

creation_date_module("Creation")
implementation("Main")

Program("pkgvm")
