% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Tue Jun 15 21:54:03 PDT 1993 by harrison
%      modified on Thu Jan 28 09:37:34 PST 1993 by mjordan
%      modified on Mon Jan 11 10:07:43 PST 1993 by mcjones

Interface ("Time")
Interface ("Tick")
Interface ("Date")
Module ("FmtTime")
