
% Copyright 1996-2000 Critical Mass, Inc. All Rights Reserved.
% See file COPYRIGHT-CMASS for details.

import ("libm3")

interface ("PGODBC")
h_source ("confg")
h_source ("structure")
h_source ("error")
h_source ("addenv")
h_source ("sql1")
h_source ("sqlext1")

if defined("configure_system_libs")
  configure_system_libs()
end 

if not SYSTEM_LIBS contains "POSTGRES95"
  write ("WARNING: Your system configuration does not define the", CR,
         "Location of the Postgres 95 library.", CR)
  c_source ("no_sql")
else
  import_sys_lib ("POSTGRES95")
  c_source ("sql")
end
Library ("pgodbc")
