/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Fri Feb  4 16:24:51 PST 2000 by heydon                   */
/*      modified on Sun Oct 18 13:54:36 PDT 1992 by gnelson                  */
/*                                                                           */
/* m3makefile for /proj/m3/pkgs/juno-app/src/rsrc                            */

/* Juno code for built-in functions and modules */
resource	("Bundled.modlist")
resource	("Angle.juno")
resource	("Anim.juno")
resource	("Arc.juno")
resource	("Arrow.juno")
resource        ("Bezier.juno")
resource        ("BST.juno")
resource        ("BuiltIn.juno")
resource	("C.juno")
resource	("CharSet.juno")
resource	("Circle.juno")
resource	("Color.juno")
resource	("Curve.juno")
resource	("Dash.juno")
resource	("DiGraph.juno")
resource	("Ellipse.juno")
resource	("Geometry.juno")
resource	("JunoUI.juno")
resource	("Line.juno")
resource	("LineSkip.juno")
resource	("List.juno")
resource	("Math.juno")
resource	("Offset.juno")
resource	("Outline.juno")
resource	("Path.juno")
resource	("Pen.juno")
resource	("PieChart.juno")
resource	("Plot.juno")
resource	("Print.juno")
resource	("Proj3D.juno")
resource	("PS.juno")
resource	("PtLabel.juno")
resource	("PtLoc.juno")
resource	("R2.juno")
resource	("R3.juno")
resource	("Random.juno")
resource	("Rect.juno")
resource	("Rel.juno")
resource	("Shadow.juno")
resource	("Show.juno")
resource	("ShowLine.juno")
resource	("Slider.juno")
resource	("Square.juno")
resource	("Text.juno")
resource	("TextList.juno")
resource	("Time.juno")
resource	("Triangle.juno")
resource	("Type.juno")
resource	("TypeLinesC.juno")
resource	("TypeLinesL.juno")
resource	("TypeLinesR.juno")
resource	("Unit.juno")
resource	("Unparse.juno")
resource	("VPrint.juno")
resource	("Xform2.juno")

/* pixmaps */
resource	("CompaqLogo.ppm")
resource	("Grow.pbm")
resource	("Juno2Logo.ppm")
resource	("MenuArrow.pbm")
resource	("UpArrow.pbm")

/* FormsVBT forms */
resource	("Macros.fv")
resource	("Startup.fv")
resource	("Juno.fv")
resource	("Toolbox.fv")
resource	("Editor2.fv")
resource	("AboutBox.fv")
resource	("Configure.fv")
resource	("LoadModule.fv")
resource	("LoadFile.fv")
resource	("SaveFile.fv")
resource	("SaveConfirm.fv")
resource	("SavePS.fv")
resource	("Fold.fv")
resource	("FoldAsAnim.fv")
resource	("SaveChanges.fv")

/* PostScript code for printing run-time errors */
resource	("prologue.ps")
resource	("showerror.ps")

/* default configuration file */
resource	("DefaultConfig.sx")

/* font name and metric data (pickled) */
resource_named	("FontData.pkl", "../../pkl-fonts/"&BUILD_DIR&"/FontData.pkl")

/* bundle file */
bundle		("JunoBundle")
