/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Wed Apr 24 16:56:43 PDT 1996 by heydon                   */

/* m3makefile for /proj/m3/pkg/juno-machine/tests/linear/src */

import("libm3")
import("juno-machine")

implementation("LinearTest")
export_interface("RedundantLSolve")

build_standalone()
program("LinearTest")
