/* Copyright (C) 1995, Digital Equipment Corporation                         */
/* Digital Internal Use Only                                                 */
/* All rights reserved.                                                      */
/*                                                                           */
/* Last modified on Wed Sep 13 11:16:48 PDT 1995 by najork                   */
/*       Created on Sat Jun 10 17:56:47 PDT 1995 by najork                   */

import ("ui")

implementation ("Main")
Program ("Test18")
