% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

include_dir ("Common")

if equal (TARGET, "VAX")
  include_dir (TARGET)
else
  include_dir ("IEEE")
end
