import("libm3")

template("residueclass")


Generic_module("ResidueClassBasic")
ResidueClass("Integer32",            "Basic", "Integer32Basic",  "Integer32GCD")
ResidueClass("BigInteger",           "Basic", "BigInteger",      "BigIntegerGCD")
%ResidueClass("LongRealPolynomial",   "Basic", "LongRealPolynomial",   "LongRealPolynomialGCD")
ResidueClass("Integer32Complex",     "Basic", "Integer32Complex",  "Integer32ComplexGCD")
ResidueClass("BigIntegerComplex",    "Basic", "BigIntegerComplex",  "BigIntegerComplexGCD")

Generic_module("ResidueClassFmtLex")
ResidueClassFmtLex("Integer32",            "Integer32Basic")
ResidueClassFmtLex("BigInteger",           "BigInteger")
