% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

module ("PklFpMap" ) 
table ( "FpInt", "Fingerprint", "Integer" ) 
module ("PklTipeMap")
module ("ConvertPacking")
interface ("PklAction")
interface ("PickleRd")
interface ("PickleWr")
sequence ("PklAction", "PklAction")
module ("PackingTypeCode")
table ("Packing", "PackingTypeCode", "Refany")
module ("BuiltinSpecials2")

Module ("Pickle2")
Module ("PickleStubs")
