% (* ----------------------------------------------------------------------1- *)
% (* File m3makefile for Modula3 compiler test p291                           *)
% (* Copyright 2021, Rodney M. Bates.                                         *)
% (* rodney.m.bates@acm.org                                                   *)
% (* Licensed under the MIT license.                                          *)
% (* ----------------------------------------------------------------------2- *)


import("libm3")

module ("TInttt")
implementation ("Main")

build_standalone ()
include("../../Test.common")
program ("pgm")
