/* $Id$ */

/* Copyright (c) 2000 California Institute of Technology */
/* All rights reserved. See the file COPYRIGHT for a full description. */

/* these packages are needed in order to build this distribution */
/* warning: some of these packages may include an overrides file, */
/* which better not conflict with the ones at the end of this file */

/* include("../.top") */
/* override("cit_util", TOP) */
/* override("term", TOP) */

/* include the "magic overrides file" which adds the compiler option */
/* ensuring that static libraries can be found at runtime */
include("../m3overrides")

/* these are the packages that are part of this distribution */
/* .parsertop is made by the Makefile before building anything */
include(".parsertop")
override("ktoklib", _PARSER_TOP)
override("klexlib", _PARSER_TOP)
override("kyacclib", _PARSER_TOP)
override("parserlib", _PARSER_TOP)
