%
% This program passes floats and doubles from Modula-3 to C code to check
% that they have the correct value. Strings are used as a presumed working
% transport.
%

module("A")
c_source("C")
include ("../../Test.common") 
