% Copyright 1996-2003 John D. Polstra.
% All rights reserved.
%
% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions
% are met:
% 1. Redistributions of source code must retain the above copyright
%    notice, this list of conditions and the following disclaimer.
% 2. Redistributions in binary form must reproduce the above copyright
%    notice, this list of conditions and the following disclaimer in the
%    documentation and/or other materials provided with the distribution.
% 3. All advertising materials mentioning features or use of this software
%    must display the following acknowledgment:
%      This product includes software developed by John D. Polstra.
% 4. The name of the author may not be used to endorse or promote products
%    derived from this software without specific prior written permission.
%
% THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
% IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
% OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
% IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
% INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
% NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
% DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
% THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
% (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
% THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
%
% $Id$

include(path() & "/../../quake/cvsup.quake")

if defined("STATIC")
  build_standalone()
end

override("suplib", path() & "/../..")
import("libm3")
import("suplib")
import("tcp")

interface("Version")
version_impl("Version")

module("FileInfo")
merger("FileInfo", "FileInfo")

table("Link", "FileID", "Text")

merger("RCSDelta", "RCSDelta")
merger("RCSTag", "RCSTag")
sequence("SupFileRec", "SupFileRec")
sequence("FileAttr", "FileAttr") % FIXME - Remove after CVTree is fixed

module("ParsedDelta")
list("ParsedDelta", "ParsedDelta")

module("AccessRules")
module("Passwd")
module("ClientClass")
module("ClassDB")

module("RCSComp")
module("TreeComp")

interface("FSServer")
interface("FSServerRep")
implementation("FSServer")
implementation("FSServerU")

implementation("Main")

program("cvsupd")
ManPage("cvsupd","8")
ManPage("cvsupd.class","5")
