configure_system_libs()

if SYSTEM_LIBS contains "ODBC"

import("libm3")
import("odbc")

implementation ("Demo")
program ("Demo")

if defined("RUN")
  r = q_exec( "." & SL & "Demo" )
  write( CR, "program returned ", r, CR )
end

end
