/* Copyright (C) 1995, Digital Equipment Corporation                         */
/* Digital Internal Use Only                                                 */
/* All rights reserved.                                                      */
/*                                                                           */
/* Last modified on Mon Jun  5 09:40:52 PDT 1995 by najork                   */
/*       Created on Mon Jun  5 09:39:47 PDT 1995 by najork                   */


if equal (TARGET, "NT386")
  override ("ui", "..\\..")
end

import         ("ui")
implementation ("Test29")
Program        ("Test29")
