% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% File: m3makefile
% Last modified on Tue Dec 21 15:10:13 PST 1993 by kalsow

import ("libm3")
import ("m3middle")
import ("m3quake")
import ("m3scanner")

Module ("M3Lexer")
Module ("M3AST")  implementation ("M3Parse")
Module ("M3Scope")
Module ("M3Type")
Module ("M3Const")
Module ("M3SetVal")
Module ("M3RecVal")
Module ("M3ArrVal")
Module ("M3Builtin")

build_standalone ()
Library ("m3tools")


