
%%XXDIR = { "WIN32" : "N:\\m3-sys",  "POSIX" : "/proj/cmass/src.2/m3-sys" }
%%WORKDIR = XXDIR {OS_TYPE}

if not defined("BOOT")
  override ("libm3", ROOT & "/m3-libs")
end
override ("m3scanner", ROOT & "/m3-sys")
override ("m3middle", ROOT & "/m3-sys")
override ("m3quake", ROOT & "/m3-sys")
