# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-13.0-RELEASE"
  config.vm.box_version = "2021.04.09"

  config.vm.provider("virtualbox") do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  config.vm.synced_folder("../..", "/vagrant_src")

  config.vm.provision "shell", inline: <<-SHELL
    pkg install --yes cmake gtar python3 unixODBC wget
  SHELL
end
