% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Oct 19 14:31:54 PDT 1995 by najork
%      modified on Sat Jun  4 18:21:04 1994 by luca
%      modified on Wed Dec 22 15:25:31 PST 1993 by kalsow

import("netobj")
import("synloc")
import("synex")
import("metasyn")
import("obliqrt")
import("obliqparse")
import("obliqprint")

Module ("ObLibM3Help")
Module ("ObLibUIHelp")
Module ("ObLibAnimHelp")
Module ("ObliqOnline")
Module ("ObLibOnline")
Module ("ObLibOnlineHelp")

resource_named("ObliqSyntax","syntax.hlp")
resource_named("ObliqLexicon","lexicon.hlp")
resource_named("ObliqHelpOnline","online.hlp")
resource_named("ObliqHelpSys","sys.hlp")
resource_named("ObliqHelpBool","bool.hlp")
resource_named("ObliqHelpInt","int.hlp")
resource_named("ObliqHelpReal","real.hlp")
resource_named("ObliqHelpMath","math.hlp")
resource_named("ObliqHelpChar","char.hlp")
resource_named("ObliqHelpText","text.hlp")
resource_named("ObliqHelpArray","array.hlp")
resource_named("ObliqHelpNet","net.hlp")
resource_named("ObliqHelpRd","rd.hlp")
resource_named("ObliqHelpWr","wr.hlp")
resource_named("ObliqHelpLex","lex.hlp")
resource_named("ObliqHelpFmt","fmt.hlp")
resource_named("ObliqHelpPickle","pickle.hlp")
resource_named("ObliqHelpProcess","process.hlp")
resource_named("ObliqHelpVBT","vbt.hlp")
resource_named("ObliqHelpThread","thread.hlp")
resource_named("ObliqHelpColor","color.hlp")
resource_named("ObliqHelpForm","form.hlp")
resource_named("ObliqHelpRects","rects.hlp")
resource_named("ObliqHelpGraph","graph.hlp")
resource_named("ObliqHelpZeus","zeus.hlp")
bundle("ObliqBdl2")

Library("obliq")

BinExport("obliq")
ManPage("obliq","1")

BinExport("obliqsrv")
ManPage("obliqsrv","1")

