%WORKDIR = "/proj/cmass/src.1/m3-obliq"

override ("synloc", ROOT & "/m3-obliq")
override ("synex", ROOT & "/m3-obliq")
override ("metasyn", ROOT & "/m3-obliq")
override ("obliqrt", ROOT & "/m3-obliq")
override ("obliqprint", ROOT & "/m3-obliq")
override ("obliqparse", ROOT & "/m3-obliq")
