import("libm3")
import("json")
import("m3tk")
import("m3quake")
import("libbuf")

interface("ValueProc")
module("Value")
module("Type")
module("AstToVal")
module("FRefRefTbl")
module("AstToType")
module("AstCompile")

module("LSP")
module("Msg")
module("Utils")
module("Debug")
module("Feature")

resource("msg.json")
bundle("MsgBundle")

implementation("Main")

build_standalone()

program("m3_lang_server")


