import("m3core")
import("libm3")
import("m3quake")
implementation("t")
build_standalone()
program("t")

if defined("RUN")

  tid = "cm3 M3Path"
  write( CR, "performing " & tid & "...", CR )
  r = q_exec( "." & SL & "t" )
  write( CR, "program returned ", r, CR )

end
