.\" This file generated automatically by mtex2man(1)

.nh
.TH "m3tohtml" "1"
.SH "Name"
.PP
m3tohtml \- convert Modula\-3 source to HTML
.SH "Syntax"
.PP
\fBm3tohtml\fR
.SH "Description"
.PP
\fBm3tohtml\fR is a program Bill Kalsow wrote as part
of his HTML browser for /proj/m3. He didn't write
a man page. The sources are in /proj/m3/pkg/m3tohtml.
.SH "Author of object"
.PP
Bill Kalsow
.SH "Author of documentation"
.PP
Allan Heydon
