/* Copyright (C) 1996, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Fri May 24 08:43:02 PDT 1996 by mcjones */

% readonly proc simple_c_program(nm) is
%   local SRCFILE = path_of(nm & ".c")
%   local EXEFILE = nm & ".EXE"
%
%   if stale(EXEFILE, SRCFILE)
%     exec (DEV_BIN & "cl /Fe" & EXEFILE, SRCFILE)
%   end
%
%   deriveds(EXEFILE, [nm & ".OBJ"])
% end


readonly proc simple_c_program(nm) is
  local src = path_of (nm & ".c")
  local obj = nm & ".obj"
  local pgm = program_name (nm)
  local toss = 0

  if defined ("_all")
    if stale (pgm, src)
      toss = compile_c (src, obj, [], FALSE, FALSE)
      toss = m3_link (pgm, [], obj, SYSTEM_LIBS{"LIBC"}, FALSE)
    end
  end

  deriveds("", [ obj, pgm ])
  BindExport (pgm)
end

simple_c_program("LecternClient")

implementation("LecternClientWin32")
implementation("LecternServerWin32")



