% Copyright (C) 1998, Compaq Computer Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Fri Dec 11 15:39:03 PST 1998 by heydon  

if not defined("AT_SRC")
  AT_SRC = ""
end
if AT_SRC
  include ("tex.quake")
end

import ("libm3")
import ("tcp")
include_dir ("Common")
include_dir (OS_TYPE)
Library ("UDP")

% generate documentation -----------------------------------------------------

if AT_SRC
  Document ("UDP")
end
