/* Copyright (C) 1993, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Fri Sep 30 14:47:52 PDT 1994 by mcjones */

Interface("OCR")
