% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Nov  1 09:04:13 PST 1994 by kalsow 

include( ".." & SL & ".." & SL & ".." & SL & "src" & SL & "defs.quake" )

src = ".." & SL & "src"
inp = src & SL & "Pump.m3"

import("libm3")
implementation("Pump")
program("Pump")

if defined("RUN")

  tid = "rw-copy"
  write( CR, "performing " & tid & "...", CR )
  r = q_exec( "." & SL & "Pump 10000 1 <" & inp & ">x")
  write( CR, "program returned ", r, CR )
  ok = cmp_files( tid, "x", inp )
  if not ok write( "FAILED", CR ) end
  r = q_exec( "." & SL & "Pump 10000 2 <" & inp & ">x")
  write( CR, "program returned ", r, CR )
  ok = cmp_files( tid, "x", inp )
  if not ok write( "FAILED", CR ) end

end
