#include <mach-o/nlist.h>
#include <mach-o/loader.h>
//#include <mach-o/machine.h>
#include <mach-o/reloc.h>

#define X(a) x##a a
X(LC_UUID)
X(LC_SEGMENT)
X(LC_SEGMENT_64)
X(LC_SYMTAB)
X(LC_DYSYMTAB)
X(LC_THREAD)
X(LC_UNIXTHREAD)
X(LC_LOAD_DYLIB)
X(LC_ID_DYLIB)
X(LC_PREBOUND_DYLIB)
X(LC_LOAD_DYLINKER)
X(LC_ID_DYLINKER)
X(LC_ROUTINES)
X(LC_ROUTINES_64)
X(LC_TWOLEVEL_HINTS)
X(LC_SUB_FRAMEWORK)
X(LC_SUB_UMBRELLA)
X(CPU_TYPE_I386)
X(CPU_SUBTYPE_I386_ALL)
X(CPU_TYPE_POWERPC)
X(CPU_SUBTYPE_POWERPC_ALL)
