
c_source ("UtimeC")
c_source ("UnixC")

include(ROOT & SL & "m3-libs" & SL & "m3core" & SL & "src" & SL & "Uwaitpid.quake")
MakeUwaitpid("")

if equal (TARGET, "MIPS64_OPENBSD") or equal (TARGET, "I386_OPENBSD")
        or equal (TARGET, "PPC32_OPENBSD") or equal (TARGET, "SPARC64_OPENBSD")
        or equal (TARGET, "AMD64_LINUX") or equal (TARGET, "PPC_LINUX")
        or equal (TARGET, "SPARC32_LINUX") or equal (TARGET, "SPARC64_LINUX")
        or equal (TARGET, "NT386") or equal (TARGET, "AMD64_FREEBSD")
    c_source("UstatC")
    Interface ("Uexec")
    Interface ("Uuio")
    Interface ("Upwd")
    Interface ("Unetdb")
    Interface ("Uugid")
    Interface ("Uprocess")
    Interface ("Uresource")

    Interface("Unix")
    Interface("Utime")
    Interface("Utypes")

    %
    % pthreads related
    %
    if not equal (TARGET, "NT386")
        Interface("Upthread")
        Interface("Usched")
        Interface("Usem")
        Interface("Uucontext")
    end

    %
    % NT386 has a slimmer Usignal, omitting pthreads stuff
    % SPARC*_LINUX needs some work, for now has its own of Usignal and Usocket
    %
    if not equal (TARGET, "NT386") and not equal (TARGET, "SPARC32_LINUX") and not equal (TARGET, "SPARC64_LINUX")
        Interface("Usignal")
    end
    if not equal (TARGET, "SPARC32_LINUX") and not equal (TARGET, "SPARC64_LINUX")
        Interface("Usocket")
    end
end

if equal (TARGET, "MIPS64_OPENBSD") or equal (TARGET, "I386_OPENBSD")
        or equal (TARGET, "PPC32_OPENBSD") or equal (TARGET, "SPARC64_OPENBSD")
        or equal (TARGET, "AMD64_LINUX") or equal (TARGET, "PPC_LINUX")
        or equal (TARGET, "SPARC32_LINUX") or equal (TARGET, "SPARC64_LINUX")
        or equal (TARGET, "AMD64_FREEBSD")
%
% everything
%
    Interface ("Ustat")
    Interface ("Udir")
end

if equal (TARGET, "NT386")
%
% Cygwin's stat flags are not common -- Ustat ommited here.
%
    Interface ("Udir")
end
