% Eventually everything in this file will apply to all platforms,
% but we will get to that point very gradually.

c_source ("UtimeC")
c_source ("UnixC")
Interface("Uexec")
c_source("Uexec")
Interface ("Unetdb")
c_source ("Unetdb")

if         equal (TARGET, "I386_OPENBSD")
        or equal (TARGET, "LINUXLIBC6")
    c_source("Uucontext")
    h_source("Uucontext")
end

include_dir("context")
c_source("Uconstants")
Interface("Uutmp")

if equal (TARGET, "MIPS64_OPENBSD") or equal (TARGET, "I386_OPENBSD")
        or equal (TARGET, "PPC32_OPENBSD") or equal (TARGET, "SPARC64_OPENBSD")
        or equal (TARGET, "AMD64_LINUX") or equal (TARGET, "PPC_LINUX")
        or equal (TARGET, "SPARC32_LINUX") or equal (TARGET, "SPARC64_LINUX")
        or equal (TARGET, "PA32_HPUX") or equal (TARGET, "PA64_HPUX")
        or equal (TARGET, "NT386") or equal (TARGET, "AMD64_FREEBSD")
	or equal (TARGET, "LINUXLIBC6")
        or equal (TARGET, "PPC_DARWIN")

    Interface ("Umman")
    c_source("UstatC")
    Interface ("Uuio")
    Interface ("Upwd")
    Interface ("Uugid")
    Interface ("Uprocess")

    Module("Unix")
    Interface("Utime")
    Interface("Utypes")

    Interface("Uerror")
    c_source("Uconstants")
    h_source("UerrorX")

    Interface("Upthread")
    Interface("Usched")

    Interface("Usocket")
    c_source("Usocket")

    Interface ("Ustat")
    Interface ("Udir")
end

if equal (TARGET, "MIPS64_OPENBSD") or equal (TARGET, "I386_OPENBSD")
        or equal (TARGET, "PPC32_OPENBSD") or equal (TARGET, "SPARC64_OPENBSD")
        or equal (TARGET, "AMD64_LINUX") or equal (TARGET, "PPC_LINUX")
        or equal (TARGET, "SPARC32_LINUX") or equal (TARGET, "SPARC64_LINUX")
        or equal (TARGET, "PA32_HPUX") or equal (TARGET, "PA64_HPUX")
        or equal (TARGET, "NT386") or equal (TARGET, "AMD64_FREEBSD")

    Interface("Uucontext")
    Interface("Usignal")

end

if equal (TARGET, "NT386")
    Interface ("Utermio")
end
