
template("signal")


generic_module("Signal")
generic_module("SignalFmtLex")
generic_interface("SignalRep")
Signal("Real",            "RealBasic",           "RealFmtLex")
Signal("LongReal",        "LongRealBasic",       "LongRealFmtLex")
Signal("Extended",        "ExtendedBasic",       "ExtendedFmtLex")
Signal("RealComplex",     "RealComplexFast",     "RealComplexFmtLex")
Signal("LongRealComplex", "LongRealComplexFast", "LongRealComplexFmtLex")
Signal("ExtendedComplex", "ExtendedComplexFast", "ExtendedComplexFmtLex")
