
template("signal")


generic_module("Signal")
generic_module("SignalFmtLex")
generic_interface("SignalRep")
Signal("Real",            "RealBasic",           "RealFmtLex",            "RealPolynomialFast")
Signal("LongReal",        "LongRealBasic",       "LongRealFmtLex",	  "LongRealPolynomialFast")
Signal("Extended",        "ExtendedBasic",       "ExtendedFmtLex",	  "ExtendedPolynomialFast")
Signal("RealComplex",     "RealComplexFast",     "RealComplexFmtLex",	  "RealComplexPolynomialBasic")
Signal("LongRealComplex", "LongRealComplexFast", "LongRealComplexFmtLex", "LongRealComplexPolynomialBasic")
Signal("ExtendedComplex", "ExtendedComplexFast", "ExtendedComplexFmtLex", "ExtendedComplexPolynomialBasic")
