
template("signal")


generic_module("Signal")
generic_module("SignalFmtLex")
generic_interface("SignalRep")
Signal("Real",            "RealBasic")
Signal("LongReal",        "LongRealBasic")
Signal("Extended",        "ExtendedBasic")
Signal("RealComplex",     "RealComplex")
Signal("LongRealComplex", "LongRealComplex")
Signal("ExtendedComplex", "ExtendedComplex")

IntegerPower("RealSignal",            "RealSignal")
IntegerPower("LongRealSignal",        "LongRealSignal")
IntegerPower("ExtendedSignal",        "ExtendedSignal")
IntegerPower("LongRealComplexSignal", "LongRealComplexSignal")

Vector("LongRealSignal",        "Basic", "LongRealSignal")
Vector("LongRealComplexSignal", "Basic", "LongRealComplexSignal")
Matrix("LongRealSignal",        "Basic", "LongRealSignal")
Matrix("LongRealComplexSignal", "Basic", "LongRealComplexSignal")


import("fftw")

template("convolution")


generic_module("Convolution")
generic_implementation("ComplexConvolution")
Convolution("Real",     "Real",     "Basic")
Convolution("LongReal", "LongReal", "Basic")
%Convolution("Extended", "Extended", "Basic")
