import("libm3")
import("m3middle")
import("m3quake")
import("llvm5.0bindings")

module("M3CG_LLVM")

implementation("Main")

% ideally:
%build_standalone()
% but there are problems with it.
Program("m3llvm")
