import		("libm3")
Module		("BitVector")
Interface	("BitVectorRep")
Library		("BitVector")

% generate documentation -----------------------------------------------------

% if (AT_SRC)
%   include ("tex.quake")
%   local_i3 ("BitVector")
%   local_i3 ("BitVectorRep")
%   Document ("BitVector")
% end
