
include(".." & SL & ".." & SL & "quake.elego")

%m3_option("-commands")
import("libm3")
import("parseparams")
import("digraph")
import("vbtkit")
import("sysutils")

%import("m3fix")
import("miniscan")
import("graphicutils")
import("pkg_base")
import("compactrc")
import("prjbase")

import("compact-copyright")

resource("UsageHelp")
resource("ShortUsageHelp")
resource("compactrc")
bundle("ProjectManagerBundle")

creation_date_module("Creation")
implementation("ProjectManager")

Program("prjm")

