% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Feb 23 14:02:51 PST 1995 by kalsow

%
% This m3makefile is strange but reusing e.g. c_source() or program()
% or library is problematic, as there is no Modula-3 in this directory at all.
%
% For example:
%
% c_source("report_coverage")
% c_source("analyze_coverage")
% LibdExport ("report_coverage.o")
% build_standalone()
% library("coverage")
%
% does not work.

if defined ("_all")
  local src = path_of ("report_coverage.c")
  local obj = "report_coverage" & ".o"
  local toss = 0
  if stale (obj, src)
    toss = compile_c (src, obj, [], FALSE, TRUE)
  end
  LibdExport (obj)
end

if defined ("_all")
  local src = path_of ("analyze_coverage.c")
  local obj = "analyze_coverage.o"
  local pgm = program_name ("analyze_coverage")
  local toss = 0
  if stale (pgm, src)
    toss = compile_c (src, obj, [], FALSE, TRUE)
    toss = m3_link (pgm, [ "-I" & path_of ("") ], obj, SYSTEM_LIBS{"LIBC"}, FALSE)
  end
  BindExport (pgm)
end

ManPage ("analyze_coverage","1")
