	.text
.no_dead_strip _mod_pow2__mod_pow2_i32_0
_mod_pow2__mod_pow2_i32_0:
LFB0:
	pushq	%rbp
LCFI0:
	movq	%rsp, %rbp
LCFI1:
	movl	%edi, -4(%rbp)
	movl	$0, %eax
	leave
LCFI2:
	ret
LFE0:
.no_dead_strip _mod_pow2__mod_pow2_i32_1
_mod_pow2__mod_pow2_i32_1:
LFB1:
	pushq	%rbp
LCFI3:
	movq	%rsp, %rbp
LCFI4:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$1, %eax
	leave
LCFI5:
	ret
LFE1:
.no_dead_strip _mod_pow2__mod_pow2_i32_2
_mod_pow2__mod_pow2_i32_2:
LFB2:
	pushq	%rbp
LCFI6:
	movq	%rsp, %rbp
LCFI7:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$3, %eax
	leave
LCFI8:
	ret
LFE2:
.no_dead_strip _mod_pow2__mod_pow2_i32_3
_mod_pow2__mod_pow2_i32_3:
LFB3:
	pushq	%rbp
LCFI9:
	movq	%rsp, %rbp
LCFI10:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$7, %eax
	leave
LCFI11:
	ret
LFE3:
.no_dead_strip _mod_pow2__mod_pow2_i32_4
_mod_pow2__mod_pow2_i32_4:
LFB4:
	pushq	%rbp
LCFI12:
	movq	%rsp, %rbp
LCFI13:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$15, %eax
	leave
LCFI14:
	ret
LFE4:
.no_dead_strip _mod_pow2__mod_pow2_i32_5
_mod_pow2__mod_pow2_i32_5:
LFB5:
	pushq	%rbp
LCFI15:
	movq	%rsp, %rbp
LCFI16:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$31, %eax
	leave
LCFI17:
	ret
LFE5:
.no_dead_strip _mod_pow2__mod_pow2_i32_6
_mod_pow2__mod_pow2_i32_6:
LFB6:
	pushq	%rbp
LCFI18:
	movq	%rsp, %rbp
LCFI19:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$63, %eax
	leave
LCFI20:
	ret
LFE6:
.no_dead_strip _mod_pow2__mod_pow2_i32_7
_mod_pow2__mod_pow2_i32_7:
LFB7:
	pushq	%rbp
LCFI21:
	movq	%rsp, %rbp
LCFI22:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$127, %eax
	leave
LCFI23:
	ret
LFE7:
.no_dead_strip _mod_pow2__mod_pow2_i32_8
_mod_pow2__mod_pow2_i32_8:
LFB8:
	pushq	%rbp
LCFI24:
	movq	%rsp, %rbp
LCFI25:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$255, %eax
	leave
LCFI26:
	ret
LFE8:
.no_dead_strip _mod_pow2__mod_pow2_i32_9
_mod_pow2__mod_pow2_i32_9:
LFB9:
	pushq	%rbp
LCFI27:
	movq	%rsp, %rbp
LCFI28:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$511, %eax
	leave
LCFI29:
	ret
LFE9:
.no_dead_strip _mod_pow2__mod_pow2_i32_10
_mod_pow2__mod_pow2_i32_10:
LFB10:
	pushq	%rbp
LCFI30:
	movq	%rsp, %rbp
LCFI31:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$1023, %eax
	leave
LCFI32:
	ret
LFE10:
.no_dead_strip _mod_pow2__mod_pow2_i32_11
_mod_pow2__mod_pow2_i32_11:
LFB11:
	pushq	%rbp
LCFI33:
	movq	%rsp, %rbp
LCFI34:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$2047, %eax
	leave
LCFI35:
	ret
LFE11:
.no_dead_strip _mod_pow2__mod_pow2_i32_12
_mod_pow2__mod_pow2_i32_12:
LFB12:
	pushq	%rbp
LCFI36:
	movq	%rsp, %rbp
LCFI37:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$4095, %eax
	leave
LCFI38:
	ret
LFE12:
.no_dead_strip _mod_pow2__mod_pow2_i32_13
_mod_pow2__mod_pow2_i32_13:
LFB13:
	pushq	%rbp
LCFI39:
	movq	%rsp, %rbp
LCFI40:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$8191, %eax
	leave
LCFI41:
	ret
LFE13:
.no_dead_strip _mod_pow2__mod_pow2_i32_14
_mod_pow2__mod_pow2_i32_14:
LFB14:
	pushq	%rbp
LCFI42:
	movq	%rsp, %rbp
LCFI43:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$16383, %eax
	leave
LCFI44:
	ret
LFE14:
.no_dead_strip _mod_pow2__mod_pow2_i32_15
_mod_pow2__mod_pow2_i32_15:
LFB15:
	pushq	%rbp
LCFI45:
	movq	%rsp, %rbp
LCFI46:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$32767, %eax
	leave
LCFI47:
	ret
LFE15:
.no_dead_strip _mod_pow2__mod_pow2_i32_16
_mod_pow2__mod_pow2_i32_16:
LFB16:
	pushq	%rbp
LCFI48:
	movq	%rsp, %rbp
LCFI49:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$65535, %eax
	leave
LCFI50:
	ret
LFE16:
.no_dead_strip _mod_pow2__mod_pow2_i32_17
_mod_pow2__mod_pow2_i32_17:
LFB17:
	pushq	%rbp
LCFI51:
	movq	%rsp, %rbp
LCFI52:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$131071, %eax
	leave
LCFI53:
	ret
LFE17:
.no_dead_strip _mod_pow2__mod_pow2_i32_18
_mod_pow2__mod_pow2_i32_18:
LFB18:
	pushq	%rbp
LCFI54:
	movq	%rsp, %rbp
LCFI55:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$262143, %eax
	leave
LCFI56:
	ret
LFE18:
.no_dead_strip _mod_pow2__mod_pow2_i32_19
_mod_pow2__mod_pow2_i32_19:
LFB19:
	pushq	%rbp
LCFI57:
	movq	%rsp, %rbp
LCFI58:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$524287, %eax
	leave
LCFI59:
	ret
LFE19:
.no_dead_strip _mod_pow2__mod_pow2_i32_20
_mod_pow2__mod_pow2_i32_20:
LFB20:
	pushq	%rbp
LCFI60:
	movq	%rsp, %rbp
LCFI61:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$1048575, %eax
	leave
LCFI62:
	ret
LFE20:
.no_dead_strip _mod_pow2__mod_pow2_i32_21
_mod_pow2__mod_pow2_i32_21:
LFB21:
	pushq	%rbp
LCFI63:
	movq	%rsp, %rbp
LCFI64:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$2097151, %eax
	leave
LCFI65:
	ret
LFE21:
.no_dead_strip _mod_pow2__mod_pow2_i32_22
_mod_pow2__mod_pow2_i32_22:
LFB22:
	pushq	%rbp
LCFI66:
	movq	%rsp, %rbp
LCFI67:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$4194303, %eax
	leave
LCFI68:
	ret
LFE22:
.no_dead_strip _mod_pow2__mod_pow2_i32_23
_mod_pow2__mod_pow2_i32_23:
LFB23:
	pushq	%rbp
LCFI69:
	movq	%rsp, %rbp
LCFI70:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$8388607, %eax
	leave
LCFI71:
	ret
LFE23:
.no_dead_strip _mod_pow2__mod_pow2_i32_24
_mod_pow2__mod_pow2_i32_24:
LFB24:
	pushq	%rbp
LCFI72:
	movq	%rsp, %rbp
LCFI73:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$16777215, %eax
	leave
LCFI74:
	ret
LFE24:
.no_dead_strip _mod_pow2__mod_pow2_i32_25
_mod_pow2__mod_pow2_i32_25:
LFB25:
	pushq	%rbp
LCFI75:
	movq	%rsp, %rbp
LCFI76:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$33554431, %eax
	leave
LCFI77:
	ret
LFE25:
.no_dead_strip _mod_pow2__mod_pow2_i32_26
_mod_pow2__mod_pow2_i32_26:
LFB26:
	pushq	%rbp
LCFI78:
	movq	%rsp, %rbp
LCFI79:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$67108863, %eax
	leave
LCFI80:
	ret
LFE26:
.no_dead_strip _mod_pow2__mod_pow2_i32_27
_mod_pow2__mod_pow2_i32_27:
LFB27:
	pushq	%rbp
LCFI81:
	movq	%rsp, %rbp
LCFI82:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$134217727, %eax
	leave
LCFI83:
	ret
LFE27:
.no_dead_strip _mod_pow2__mod_pow2_i32_28
_mod_pow2__mod_pow2_i32_28:
LFB28:
	pushq	%rbp
LCFI84:
	movq	%rsp, %rbp
LCFI85:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$268435455, %eax
	leave
LCFI86:
	ret
LFE28:
.no_dead_strip _mod_pow2__mod_pow2_i32_29
_mod_pow2__mod_pow2_i32_29:
LFB29:
	pushq	%rbp
LCFI87:
	movq	%rsp, %rbp
LCFI88:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$536870911, %eax
	leave
LCFI89:
	ret
LFE29:
.no_dead_strip _mod_pow2__mod_pow2_i32_30
_mod_pow2__mod_pow2_i32_30:
LFB30:
	pushq	%rbp
LCFI90:
	movq	%rsp, %rbp
LCFI91:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$1073741823, %eax
	leave
LCFI92:
	ret
LFE30:
.no_dead_strip _mod_pow2__mod_pow2_i32_31
_mod_pow2__mod_pow2_i32_31:
LFB31:
	pushq	%rbp
LCFI93:
	movq	%rsp, %rbp
LCFI94:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$2147483647, %eax
	leave
LCFI95:
	ret
LFE31:
.no_dead_strip _mod_pow2__mod_pow2_u32_0
_mod_pow2__mod_pow2_u32_0:
LFB32:
	pushq	%rbp
LCFI96:
	movq	%rsp, %rbp
LCFI97:
	movl	%edi, -4(%rbp)
	movl	$0, %eax
	leave
LCFI98:
	ret
LFE32:
.no_dead_strip _mod_pow2__mod_pow2_u32_1
_mod_pow2__mod_pow2_u32_1:
LFB33:
	pushq	%rbp
LCFI99:
	movq	%rsp, %rbp
LCFI100:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$1, %eax
	leave
LCFI101:
	ret
LFE33:
.no_dead_strip _mod_pow2__mod_pow2_u32_2
_mod_pow2__mod_pow2_u32_2:
LFB34:
	pushq	%rbp
LCFI102:
	movq	%rsp, %rbp
LCFI103:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$3, %eax
	leave
LCFI104:
	ret
LFE34:
.no_dead_strip _mod_pow2__mod_pow2_u32_3
_mod_pow2__mod_pow2_u32_3:
LFB35:
	pushq	%rbp
LCFI105:
	movq	%rsp, %rbp
LCFI106:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$7, %eax
	leave
LCFI107:
	ret
LFE35:
.no_dead_strip _mod_pow2__mod_pow2_u32_4
_mod_pow2__mod_pow2_u32_4:
LFB36:
	pushq	%rbp
LCFI108:
	movq	%rsp, %rbp
LCFI109:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$15, %eax
	leave
LCFI110:
	ret
LFE36:
.no_dead_strip _mod_pow2__mod_pow2_u32_5
_mod_pow2__mod_pow2_u32_5:
LFB37:
	pushq	%rbp
LCFI111:
	movq	%rsp, %rbp
LCFI112:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$31, %eax
	leave
LCFI113:
	ret
LFE37:
.no_dead_strip _mod_pow2__mod_pow2_u32_6
_mod_pow2__mod_pow2_u32_6:
LFB38:
	pushq	%rbp
LCFI114:
	movq	%rsp, %rbp
LCFI115:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$63, %eax
	leave
LCFI116:
	ret
LFE38:
.no_dead_strip _mod_pow2__mod_pow2_u32_7
_mod_pow2__mod_pow2_u32_7:
LFB39:
	pushq	%rbp
LCFI117:
	movq	%rsp, %rbp
LCFI118:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$127, %eax
	leave
LCFI119:
	ret
LFE39:
.no_dead_strip _mod_pow2__mod_pow2_u32_8
_mod_pow2__mod_pow2_u32_8:
LFB40:
	pushq	%rbp
LCFI120:
	movq	%rsp, %rbp
LCFI121:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$255, %eax
	leave
LCFI122:
	ret
LFE40:
.no_dead_strip _mod_pow2__mod_pow2_u32_9
_mod_pow2__mod_pow2_u32_9:
LFB41:
	pushq	%rbp
LCFI123:
	movq	%rsp, %rbp
LCFI124:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$511, %eax
	leave
LCFI125:
	ret
LFE41:
.no_dead_strip _mod_pow2__mod_pow2_u32_10
_mod_pow2__mod_pow2_u32_10:
LFB42:
	pushq	%rbp
LCFI126:
	movq	%rsp, %rbp
LCFI127:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$1023, %eax
	leave
LCFI128:
	ret
LFE42:
.no_dead_strip _mod_pow2__mod_pow2_u32_11
_mod_pow2__mod_pow2_u32_11:
LFB43:
	pushq	%rbp
LCFI129:
	movq	%rsp, %rbp
LCFI130:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$2047, %eax
	leave
LCFI131:
	ret
LFE43:
.no_dead_strip _mod_pow2__mod_pow2_u32_12
_mod_pow2__mod_pow2_u32_12:
LFB44:
	pushq	%rbp
LCFI132:
	movq	%rsp, %rbp
LCFI133:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$4095, %eax
	leave
LCFI134:
	ret
LFE44:
.no_dead_strip _mod_pow2__mod_pow2_u32_13
_mod_pow2__mod_pow2_u32_13:
LFB45:
	pushq	%rbp
LCFI135:
	movq	%rsp, %rbp
LCFI136:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$8191, %eax
	leave
LCFI137:
	ret
LFE45:
.no_dead_strip _mod_pow2__mod_pow2_u32_14
_mod_pow2__mod_pow2_u32_14:
LFB46:
	pushq	%rbp
LCFI138:
	movq	%rsp, %rbp
LCFI139:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$16383, %eax
	leave
LCFI140:
	ret
LFE46:
.no_dead_strip _mod_pow2__mod_pow2_u32_15
_mod_pow2__mod_pow2_u32_15:
LFB47:
	pushq	%rbp
LCFI141:
	movq	%rsp, %rbp
LCFI142:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$32767, %eax
	leave
LCFI143:
	ret
LFE47:
.no_dead_strip _mod_pow2__mod_pow2_u32_16
_mod_pow2__mod_pow2_u32_16:
LFB48:
	pushq	%rbp
LCFI144:
	movq	%rsp, %rbp
LCFI145:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$65535, %eax
	leave
LCFI146:
	ret
LFE48:
.no_dead_strip _mod_pow2__mod_pow2_u32_17
_mod_pow2__mod_pow2_u32_17:
LFB49:
	pushq	%rbp
LCFI147:
	movq	%rsp, %rbp
LCFI148:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$131071, %eax
	leave
LCFI149:
	ret
LFE49:
.no_dead_strip _mod_pow2__mod_pow2_u32_18
_mod_pow2__mod_pow2_u32_18:
LFB50:
	pushq	%rbp
LCFI150:
	movq	%rsp, %rbp
LCFI151:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$262143, %eax
	leave
LCFI152:
	ret
LFE50:
.no_dead_strip _mod_pow2__mod_pow2_u32_19
_mod_pow2__mod_pow2_u32_19:
LFB51:
	pushq	%rbp
LCFI153:
	movq	%rsp, %rbp
LCFI154:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$524287, %eax
	leave
LCFI155:
	ret
LFE51:
.no_dead_strip _mod_pow2__mod_pow2_u32_20
_mod_pow2__mod_pow2_u32_20:
LFB52:
	pushq	%rbp
LCFI156:
	movq	%rsp, %rbp
LCFI157:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$1048575, %eax
	leave
LCFI158:
	ret
LFE52:
.no_dead_strip _mod_pow2__mod_pow2_u32_21
_mod_pow2__mod_pow2_u32_21:
LFB53:
	pushq	%rbp
LCFI159:
	movq	%rsp, %rbp
LCFI160:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$2097151, %eax
	leave
LCFI161:
	ret
LFE53:
.no_dead_strip _mod_pow2__mod_pow2_u32_22
_mod_pow2__mod_pow2_u32_22:
LFB54:
	pushq	%rbp
LCFI162:
	movq	%rsp, %rbp
LCFI163:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$4194303, %eax
	leave
LCFI164:
	ret
LFE54:
.no_dead_strip _mod_pow2__mod_pow2_u32_23
_mod_pow2__mod_pow2_u32_23:
LFB55:
	pushq	%rbp
LCFI165:
	movq	%rsp, %rbp
LCFI166:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$8388607, %eax
	leave
LCFI167:
	ret
LFE55:
.no_dead_strip _mod_pow2__mod_pow2_u32_24
_mod_pow2__mod_pow2_u32_24:
LFB56:
	pushq	%rbp
LCFI168:
	movq	%rsp, %rbp
LCFI169:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$16777215, %eax
	leave
LCFI170:
	ret
LFE56:
.no_dead_strip _mod_pow2__mod_pow2_u32_25
_mod_pow2__mod_pow2_u32_25:
LFB57:
	pushq	%rbp
LCFI171:
	movq	%rsp, %rbp
LCFI172:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$33554431, %eax
	leave
LCFI173:
	ret
LFE57:
.no_dead_strip _mod_pow2__mod_pow2_u32_26
_mod_pow2__mod_pow2_u32_26:
LFB58:
	pushq	%rbp
LCFI174:
	movq	%rsp, %rbp
LCFI175:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$67108863, %eax
	leave
LCFI176:
	ret
LFE58:
.no_dead_strip _mod_pow2__mod_pow2_u32_27
_mod_pow2__mod_pow2_u32_27:
LFB59:
	pushq	%rbp
LCFI177:
	movq	%rsp, %rbp
LCFI178:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$134217727, %eax
	leave
LCFI179:
	ret
LFE59:
.no_dead_strip _mod_pow2__mod_pow2_u32_28
_mod_pow2__mod_pow2_u32_28:
LFB60:
	pushq	%rbp
LCFI180:
	movq	%rsp, %rbp
LCFI181:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$268435455, %eax
	leave
LCFI182:
	ret
LFE60:
.no_dead_strip _mod_pow2__mod_pow2_u32_29
_mod_pow2__mod_pow2_u32_29:
LFB61:
	pushq	%rbp
LCFI183:
	movq	%rsp, %rbp
LCFI184:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$536870911, %eax
	leave
LCFI185:
	ret
LFE61:
.no_dead_strip _mod_pow2__mod_pow2_u32_30
_mod_pow2__mod_pow2_u32_30:
LFB62:
	pushq	%rbp
LCFI186:
	movq	%rsp, %rbp
LCFI187:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$1073741823, %eax
	leave
LCFI188:
	ret
LFE62:
.no_dead_strip _mod_pow2__mod_pow2_u32_31
_mod_pow2__mod_pow2_u32_31:
LFB63:
	pushq	%rbp
LCFI189:
	movq	%rsp, %rbp
LCFI190:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	andl	$2147483647, %eax
	leave
LCFI191:
	ret
LFE63:
.no_dead_strip _mod_pow2__mod_pow2_i64_0
_mod_pow2__mod_pow2_i64_0:
LFB64:
	pushq	%rbp
LCFI192:
	movq	%rsp, %rbp
LCFI193:
	movq	%rdi, -8(%rbp)
	movl	$0, %eax
	leave
LCFI194:
	ret
LFE64:
.no_dead_strip _mod_pow2__mod_pow2_i64_1
_mod_pow2__mod_pow2_i64_1:
LFB65:
	pushq	%rbp
LCFI195:
	movq	%rsp, %rbp
LCFI196:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1, %eax
	leave
LCFI197:
	ret
LFE65:
.no_dead_strip _mod_pow2__mod_pow2_i64_2
_mod_pow2__mod_pow2_i64_2:
LFB66:
	pushq	%rbp
LCFI198:
	movq	%rsp, %rbp
LCFI199:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$3, %eax
	leave
LCFI200:
	ret
LFE66:
.no_dead_strip _mod_pow2__mod_pow2_i64_3
_mod_pow2__mod_pow2_i64_3:
LFB67:
	pushq	%rbp
LCFI201:
	movq	%rsp, %rbp
LCFI202:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$7, %eax
	leave
LCFI203:
	ret
LFE67:
.no_dead_strip _mod_pow2__mod_pow2_i64_4
_mod_pow2__mod_pow2_i64_4:
LFB68:
	pushq	%rbp
LCFI204:
	movq	%rsp, %rbp
LCFI205:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$15, %eax
	leave
LCFI206:
	ret
LFE68:
.no_dead_strip _mod_pow2__mod_pow2_i64_5
_mod_pow2__mod_pow2_i64_5:
LFB69:
	pushq	%rbp
LCFI207:
	movq	%rsp, %rbp
LCFI208:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$31, %eax
	leave
LCFI209:
	ret
LFE69:
.no_dead_strip _mod_pow2__mod_pow2_i64_6
_mod_pow2__mod_pow2_i64_6:
LFB70:
	pushq	%rbp
LCFI210:
	movq	%rsp, %rbp
LCFI211:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$63, %eax
	leave
LCFI212:
	ret
LFE70:
.no_dead_strip _mod_pow2__mod_pow2_i64_7
_mod_pow2__mod_pow2_i64_7:
LFB71:
	pushq	%rbp
LCFI213:
	movq	%rsp, %rbp
LCFI214:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$127, %eax
	leave
LCFI215:
	ret
LFE71:
.no_dead_strip _mod_pow2__mod_pow2_i64_8
_mod_pow2__mod_pow2_i64_8:
LFB72:
	pushq	%rbp
LCFI216:
	movq	%rsp, %rbp
LCFI217:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$255, %eax
	leave
LCFI218:
	ret
LFE72:
.no_dead_strip _mod_pow2__mod_pow2_i64_9
_mod_pow2__mod_pow2_i64_9:
LFB73:
	pushq	%rbp
LCFI219:
	movq	%rsp, %rbp
LCFI220:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$511, %eax
	leave
LCFI221:
	ret
LFE73:
.no_dead_strip _mod_pow2__mod_pow2_i64_10
_mod_pow2__mod_pow2_i64_10:
LFB74:
	pushq	%rbp
LCFI222:
	movq	%rsp, %rbp
LCFI223:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1023, %eax
	leave
LCFI224:
	ret
LFE74:
.no_dead_strip _mod_pow2__mod_pow2_i64_11
_mod_pow2__mod_pow2_i64_11:
LFB75:
	pushq	%rbp
LCFI225:
	movq	%rsp, %rbp
LCFI226:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2047, %eax
	leave
LCFI227:
	ret
LFE75:
.no_dead_strip _mod_pow2__mod_pow2_i64_12
_mod_pow2__mod_pow2_i64_12:
LFB76:
	pushq	%rbp
LCFI228:
	movq	%rsp, %rbp
LCFI229:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4095, %eax
	leave
LCFI230:
	ret
LFE76:
.no_dead_strip _mod_pow2__mod_pow2_i64_13
_mod_pow2__mod_pow2_i64_13:
LFB77:
	pushq	%rbp
LCFI231:
	movq	%rsp, %rbp
LCFI232:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$8191, %eax
	leave
LCFI233:
	ret
LFE77:
.no_dead_strip _mod_pow2__mod_pow2_i64_14
_mod_pow2__mod_pow2_i64_14:
LFB78:
	pushq	%rbp
LCFI234:
	movq	%rsp, %rbp
LCFI235:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$16383, %eax
	leave
LCFI236:
	ret
LFE78:
.no_dead_strip _mod_pow2__mod_pow2_i64_15
_mod_pow2__mod_pow2_i64_15:
LFB79:
	pushq	%rbp
LCFI237:
	movq	%rsp, %rbp
LCFI238:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$32767, %eax
	leave
LCFI239:
	ret
LFE79:
.no_dead_strip _mod_pow2__mod_pow2_i64_16
_mod_pow2__mod_pow2_i64_16:
LFB80:
	pushq	%rbp
LCFI240:
	movq	%rsp, %rbp
LCFI241:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$65535, %eax
	leave
LCFI242:
	ret
LFE80:
.no_dead_strip _mod_pow2__mod_pow2_i64_17
_mod_pow2__mod_pow2_i64_17:
LFB81:
	pushq	%rbp
LCFI243:
	movq	%rsp, %rbp
LCFI244:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$131071, %eax
	leave
LCFI245:
	ret
LFE81:
.no_dead_strip _mod_pow2__mod_pow2_i64_18
_mod_pow2__mod_pow2_i64_18:
LFB82:
	pushq	%rbp
LCFI246:
	movq	%rsp, %rbp
LCFI247:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$262143, %eax
	leave
LCFI248:
	ret
LFE82:
.no_dead_strip _mod_pow2__mod_pow2_i64_19
_mod_pow2__mod_pow2_i64_19:
LFB83:
	pushq	%rbp
LCFI249:
	movq	%rsp, %rbp
LCFI250:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$524287, %eax
	leave
LCFI251:
	ret
LFE83:
.no_dead_strip _mod_pow2__mod_pow2_i64_20
_mod_pow2__mod_pow2_i64_20:
LFB84:
	pushq	%rbp
LCFI252:
	movq	%rsp, %rbp
LCFI253:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1048575, %eax
	leave
LCFI254:
	ret
LFE84:
.no_dead_strip _mod_pow2__mod_pow2_i64_21
_mod_pow2__mod_pow2_i64_21:
LFB85:
	pushq	%rbp
LCFI255:
	movq	%rsp, %rbp
LCFI256:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2097151, %eax
	leave
LCFI257:
	ret
LFE85:
.no_dead_strip _mod_pow2__mod_pow2_i64_22
_mod_pow2__mod_pow2_i64_22:
LFB86:
	pushq	%rbp
LCFI258:
	movq	%rsp, %rbp
LCFI259:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4194303, %eax
	leave
LCFI260:
	ret
LFE86:
.no_dead_strip _mod_pow2__mod_pow2_i64_23
_mod_pow2__mod_pow2_i64_23:
LFB87:
	pushq	%rbp
LCFI261:
	movq	%rsp, %rbp
LCFI262:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$8388607, %eax
	leave
LCFI263:
	ret
LFE87:
.no_dead_strip _mod_pow2__mod_pow2_i64_24
_mod_pow2__mod_pow2_i64_24:
LFB88:
	pushq	%rbp
LCFI264:
	movq	%rsp, %rbp
LCFI265:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$16777215, %eax
	leave
LCFI266:
	ret
LFE88:
.no_dead_strip _mod_pow2__mod_pow2_i64_25
_mod_pow2__mod_pow2_i64_25:
LFB89:
	pushq	%rbp
LCFI267:
	movq	%rsp, %rbp
LCFI268:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$33554431, %eax
	leave
LCFI269:
	ret
LFE89:
.no_dead_strip _mod_pow2__mod_pow2_i64_26
_mod_pow2__mod_pow2_i64_26:
LFB90:
	pushq	%rbp
LCFI270:
	movq	%rsp, %rbp
LCFI271:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$67108863, %eax
	leave
LCFI272:
	ret
LFE90:
.no_dead_strip _mod_pow2__mod_pow2_i64_27
_mod_pow2__mod_pow2_i64_27:
LFB91:
	pushq	%rbp
LCFI273:
	movq	%rsp, %rbp
LCFI274:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$134217727, %eax
	leave
LCFI275:
	ret
LFE91:
.no_dead_strip _mod_pow2__mod_pow2_i64_28
_mod_pow2__mod_pow2_i64_28:
LFB92:
	pushq	%rbp
LCFI276:
	movq	%rsp, %rbp
LCFI277:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$268435455, %eax
	leave
LCFI278:
	ret
LFE92:
.no_dead_strip _mod_pow2__mod_pow2_i64_29
_mod_pow2__mod_pow2_i64_29:
LFB93:
	pushq	%rbp
LCFI279:
	movq	%rsp, %rbp
LCFI280:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$536870911, %eax
	leave
LCFI281:
	ret
LFE93:
.no_dead_strip _mod_pow2__mod_pow2_i64_30
_mod_pow2__mod_pow2_i64_30:
LFB94:
	pushq	%rbp
LCFI282:
	movq	%rsp, %rbp
LCFI283:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1073741823, %eax
	leave
LCFI284:
	ret
LFE94:
.no_dead_strip _mod_pow2__mod_pow2_i64_31
_mod_pow2__mod_pow2_i64_31:
LFB95:
	pushq	%rbp
LCFI285:
	movq	%rsp, %rbp
LCFI286:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2147483647, %eax
	leave
LCFI287:
	ret
LFE95:
.no_dead_strip _mod_pow2__mod_pow2_i64_32
_mod_pow2__mod_pow2_i64_32:
LFB96:
	pushq	%rbp
LCFI288:
	movq	%rsp, %rbp
LCFI289:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4294967295, %eax
	leave
LCFI290:
	ret
LFE96:
.no_dead_strip _mod_pow2__mod_pow2_i64_33
_mod_pow2__mod_pow2_i64_33:
LFB97:
	pushq	%rbp
LCFI291:
	movq	%rsp, %rbp
LCFI292:
	movq	%rdi, -8(%rbp)
	movabsq	$8589934591, %rax
	andq	-8(%rbp), %rax
	leave
LCFI293:
	ret
LFE97:
.no_dead_strip _mod_pow2__mod_pow2_i64_34
_mod_pow2__mod_pow2_i64_34:
LFB98:
	pushq	%rbp
LCFI294:
	movq	%rsp, %rbp
LCFI295:
	movq	%rdi, -8(%rbp)
	movabsq	$17179869183, %rax
	andq	-8(%rbp), %rax
	leave
LCFI296:
	ret
LFE98:
.no_dead_strip _mod_pow2__mod_pow2_i64_35
_mod_pow2__mod_pow2_i64_35:
LFB99:
	pushq	%rbp
LCFI297:
	movq	%rsp, %rbp
LCFI298:
	movq	%rdi, -8(%rbp)
	movabsq	$34359738367, %rax
	andq	-8(%rbp), %rax
	leave
LCFI299:
	ret
LFE99:
.no_dead_strip _mod_pow2__mod_pow2_i64_36
_mod_pow2__mod_pow2_i64_36:
LFB100:
	pushq	%rbp
LCFI300:
	movq	%rsp, %rbp
LCFI301:
	movq	%rdi, -8(%rbp)
	movabsq	$68719476735, %rax
	andq	-8(%rbp), %rax
	leave
LCFI302:
	ret
LFE100:
.no_dead_strip _mod_pow2__mod_pow2_i64_37
_mod_pow2__mod_pow2_i64_37:
LFB101:
	pushq	%rbp
LCFI303:
	movq	%rsp, %rbp
LCFI304:
	movq	%rdi, -8(%rbp)
	movabsq	$137438953471, %rax
	andq	-8(%rbp), %rax
	leave
LCFI305:
	ret
LFE101:
.no_dead_strip _mod_pow2__mod_pow2_i64_38
_mod_pow2__mod_pow2_i64_38:
LFB102:
	pushq	%rbp
LCFI306:
	movq	%rsp, %rbp
LCFI307:
	movq	%rdi, -8(%rbp)
	movabsq	$274877906943, %rax
	andq	-8(%rbp), %rax
	leave
LCFI308:
	ret
LFE102:
.no_dead_strip _mod_pow2__mod_pow2_i64_39
_mod_pow2__mod_pow2_i64_39:
LFB103:
	pushq	%rbp
LCFI309:
	movq	%rsp, %rbp
LCFI310:
	movq	%rdi, -8(%rbp)
	movabsq	$549755813887, %rax
	andq	-8(%rbp), %rax
	leave
LCFI311:
	ret
LFE103:
.no_dead_strip _mod_pow2__mod_pow2_i64_40
_mod_pow2__mod_pow2_i64_40:
LFB104:
	pushq	%rbp
LCFI312:
	movq	%rsp, %rbp
LCFI313:
	movq	%rdi, -8(%rbp)
	movabsq	$1099511627775, %rax
	andq	-8(%rbp), %rax
	leave
LCFI314:
	ret
LFE104:
.no_dead_strip _mod_pow2__mod_pow2_i64_41
_mod_pow2__mod_pow2_i64_41:
LFB105:
	pushq	%rbp
LCFI315:
	movq	%rsp, %rbp
LCFI316:
	movq	%rdi, -8(%rbp)
	movabsq	$2199023255551, %rax
	andq	-8(%rbp), %rax
	leave
LCFI317:
	ret
LFE105:
.no_dead_strip _mod_pow2__mod_pow2_i64_42
_mod_pow2__mod_pow2_i64_42:
LFB106:
	pushq	%rbp
LCFI318:
	movq	%rsp, %rbp
LCFI319:
	movq	%rdi, -8(%rbp)
	movabsq	$4398046511103, %rax
	andq	-8(%rbp), %rax
	leave
LCFI320:
	ret
LFE106:
.no_dead_strip _mod_pow2__mod_pow2_i64_43
_mod_pow2__mod_pow2_i64_43:
LFB107:
	pushq	%rbp
LCFI321:
	movq	%rsp, %rbp
LCFI322:
	movq	%rdi, -8(%rbp)
	movabsq	$8796093022207, %rax
	andq	-8(%rbp), %rax
	leave
LCFI323:
	ret
LFE107:
.no_dead_strip _mod_pow2__mod_pow2_i64_44
_mod_pow2__mod_pow2_i64_44:
LFB108:
	pushq	%rbp
LCFI324:
	movq	%rsp, %rbp
LCFI325:
	movq	%rdi, -8(%rbp)
	movabsq	$17592186044415, %rax
	andq	-8(%rbp), %rax
	leave
LCFI326:
	ret
LFE108:
.no_dead_strip _mod_pow2__mod_pow2_i64_45
_mod_pow2__mod_pow2_i64_45:
LFB109:
	pushq	%rbp
LCFI327:
	movq	%rsp, %rbp
LCFI328:
	movq	%rdi, -8(%rbp)
	movabsq	$35184372088831, %rax
	andq	-8(%rbp), %rax
	leave
LCFI329:
	ret
LFE109:
.no_dead_strip _mod_pow2__mod_pow2_i64_46
_mod_pow2__mod_pow2_i64_46:
LFB110:
	pushq	%rbp
LCFI330:
	movq	%rsp, %rbp
LCFI331:
	movq	%rdi, -8(%rbp)
	movabsq	$70368744177663, %rax
	andq	-8(%rbp), %rax
	leave
LCFI332:
	ret
LFE110:
.no_dead_strip _mod_pow2__mod_pow2_i64_47
_mod_pow2__mod_pow2_i64_47:
LFB111:
	pushq	%rbp
LCFI333:
	movq	%rsp, %rbp
LCFI334:
	movq	%rdi, -8(%rbp)
	movabsq	$140737488355327, %rax
	andq	-8(%rbp), %rax
	leave
LCFI335:
	ret
LFE111:
.no_dead_strip _mod_pow2__mod_pow2_i64_48
_mod_pow2__mod_pow2_i64_48:
LFB112:
	pushq	%rbp
LCFI336:
	movq	%rsp, %rbp
LCFI337:
	movq	%rdi, -8(%rbp)
	movabsq	$281474976710655, %rax
	andq	-8(%rbp), %rax
	leave
LCFI338:
	ret
LFE112:
.no_dead_strip _mod_pow2__mod_pow2_i64_49
_mod_pow2__mod_pow2_i64_49:
LFB113:
	pushq	%rbp
LCFI339:
	movq	%rsp, %rbp
LCFI340:
	movq	%rdi, -8(%rbp)
	movabsq	$562949953421311, %rax
	andq	-8(%rbp), %rax
	leave
LCFI341:
	ret
LFE113:
.no_dead_strip _mod_pow2__mod_pow2_i64_50
_mod_pow2__mod_pow2_i64_50:
LFB114:
	pushq	%rbp
LCFI342:
	movq	%rsp, %rbp
LCFI343:
	movq	%rdi, -8(%rbp)
	movabsq	$1125899906842623, %rax
	andq	-8(%rbp), %rax
	leave
LCFI344:
	ret
LFE114:
.no_dead_strip _mod_pow2__mod_pow2_i64_51
_mod_pow2__mod_pow2_i64_51:
LFB115:
	pushq	%rbp
LCFI345:
	movq	%rsp, %rbp
LCFI346:
	movq	%rdi, -8(%rbp)
	movabsq	$2251799813685247, %rax
	andq	-8(%rbp), %rax
	leave
LCFI347:
	ret
LFE115:
.no_dead_strip _mod_pow2__mod_pow2_i64_52
_mod_pow2__mod_pow2_i64_52:
LFB116:
	pushq	%rbp
LCFI348:
	movq	%rsp, %rbp
LCFI349:
	movq	%rdi, -8(%rbp)
	movabsq	$4503599627370495, %rax
	andq	-8(%rbp), %rax
	leave
LCFI350:
	ret
LFE116:
.no_dead_strip _mod_pow2__mod_pow2_i64_53
_mod_pow2__mod_pow2_i64_53:
LFB117:
	pushq	%rbp
LCFI351:
	movq	%rsp, %rbp
LCFI352:
	movq	%rdi, -8(%rbp)
	movabsq	$9007199254740991, %rax
	andq	-8(%rbp), %rax
	leave
LCFI353:
	ret
LFE117:
.no_dead_strip _mod_pow2__mod_pow2_i64_54
_mod_pow2__mod_pow2_i64_54:
LFB118:
	pushq	%rbp
LCFI354:
	movq	%rsp, %rbp
LCFI355:
	movq	%rdi, -8(%rbp)
	movabsq	$18014398509481983, %rax
	andq	-8(%rbp), %rax
	leave
LCFI356:
	ret
LFE118:
.no_dead_strip _mod_pow2__mod_pow2_i64_55
_mod_pow2__mod_pow2_i64_55:
LFB119:
	pushq	%rbp
LCFI357:
	movq	%rsp, %rbp
LCFI358:
	movq	%rdi, -8(%rbp)
	movabsq	$36028797018963967, %rax
	andq	-8(%rbp), %rax
	leave
LCFI359:
	ret
LFE119:
.no_dead_strip _mod_pow2__mod_pow2_i64_56
_mod_pow2__mod_pow2_i64_56:
LFB120:
	pushq	%rbp
LCFI360:
	movq	%rsp, %rbp
LCFI361:
	movq	%rdi, -8(%rbp)
	movabsq	$72057594037927935, %rax
	andq	-8(%rbp), %rax
	leave
LCFI362:
	ret
LFE120:
.no_dead_strip _mod_pow2__mod_pow2_i64_57
_mod_pow2__mod_pow2_i64_57:
LFB121:
	pushq	%rbp
LCFI363:
	movq	%rsp, %rbp
LCFI364:
	movq	%rdi, -8(%rbp)
	movabsq	$144115188075855871, %rax
	andq	-8(%rbp), %rax
	leave
LCFI365:
	ret
LFE121:
.no_dead_strip _mod_pow2__mod_pow2_i64_58
_mod_pow2__mod_pow2_i64_58:
LFB122:
	pushq	%rbp
LCFI366:
	movq	%rsp, %rbp
LCFI367:
	movq	%rdi, -8(%rbp)
	movabsq	$288230376151711743, %rax
	andq	-8(%rbp), %rax
	leave
LCFI368:
	ret
LFE122:
.no_dead_strip _mod_pow2__mod_pow2_i64_59
_mod_pow2__mod_pow2_i64_59:
LFB123:
	pushq	%rbp
LCFI369:
	movq	%rsp, %rbp
LCFI370:
	movq	%rdi, -8(%rbp)
	movabsq	$576460752303423487, %rax
	andq	-8(%rbp), %rax
	leave
LCFI371:
	ret
LFE123:
.no_dead_strip _mod_pow2__mod_pow2_i64_60
_mod_pow2__mod_pow2_i64_60:
LFB124:
	pushq	%rbp
LCFI372:
	movq	%rsp, %rbp
LCFI373:
	movq	%rdi, -8(%rbp)
	movabsq	$1152921504606846975, %rax
	andq	-8(%rbp), %rax
	leave
LCFI374:
	ret
LFE124:
.no_dead_strip _mod_pow2__mod_pow2_i64_61
_mod_pow2__mod_pow2_i64_61:
LFB125:
	pushq	%rbp
LCFI375:
	movq	%rsp, %rbp
LCFI376:
	movq	%rdi, -8(%rbp)
	movabsq	$2305843009213693951, %rax
	andq	-8(%rbp), %rax
	leave
LCFI377:
	ret
LFE125:
.no_dead_strip _mod_pow2__mod_pow2_i64_62
_mod_pow2__mod_pow2_i64_62:
LFB126:
	pushq	%rbp
LCFI378:
	movq	%rsp, %rbp
LCFI379:
	movq	%rdi, -8(%rbp)
	movabsq	$4611686018427387903, %rax
	andq	-8(%rbp), %rax
	leave
LCFI380:
	ret
LFE126:
.no_dead_strip _mod_pow2__mod_pow2_i64_63
_mod_pow2__mod_pow2_i64_63:
LFB127:
	pushq	%rbp
LCFI381:
	movq	%rsp, %rbp
LCFI382:
	pushq	%rbx
LCFI383:
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leaq	-1(%rax), %rdx
	movq	%rax, %rcx
	orq	%rdx, %rcx
	sarq	$63, %rcx
	movq	%rdx, %rbx
	subq	%rcx, %rbx
	movabsq	$-9223372036854775808, %rdx
	cmpq	%rdx, %rbx
	sete	%dl
	movzbl	%dl, %edx
	notq	%rcx
	addq	%rcx, %rdx
	salq	$63, %rdx
	movq	%rax, %rcx
	subq	%rdx, %rcx
	movq	%rcx, %rdx
	movq	%rdx, %rax
	popq	%rbx
	leave
LCFI384:
	ret
LFE127:
.no_dead_strip _mod_pow2__mod_pow2_u64_0
_mod_pow2__mod_pow2_u64_0:
LFB128:
	pushq	%rbp
LCFI385:
	movq	%rsp, %rbp
LCFI386:
	movq	%rdi, -8(%rbp)
	movl	$0, %eax
	leave
LCFI387:
	ret
LFE128:
.no_dead_strip _mod_pow2__mod_pow2_u64_1
_mod_pow2__mod_pow2_u64_1:
LFB129:
	pushq	%rbp
LCFI388:
	movq	%rsp, %rbp
LCFI389:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1, %eax
	leave
LCFI390:
	ret
LFE129:
.no_dead_strip _mod_pow2__mod_pow2_u64_2
_mod_pow2__mod_pow2_u64_2:
LFB130:
	pushq	%rbp
LCFI391:
	movq	%rsp, %rbp
LCFI392:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$3, %eax
	leave
LCFI393:
	ret
LFE130:
.no_dead_strip _mod_pow2__mod_pow2_u64_3
_mod_pow2__mod_pow2_u64_3:
LFB131:
	pushq	%rbp
LCFI394:
	movq	%rsp, %rbp
LCFI395:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$7, %eax
	leave
LCFI396:
	ret
LFE131:
.no_dead_strip _mod_pow2__mod_pow2_u64_4
_mod_pow2__mod_pow2_u64_4:
LFB132:
	pushq	%rbp
LCFI397:
	movq	%rsp, %rbp
LCFI398:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$15, %eax
	leave
LCFI399:
	ret
LFE132:
.no_dead_strip _mod_pow2__mod_pow2_u64_5
_mod_pow2__mod_pow2_u64_5:
LFB133:
	pushq	%rbp
LCFI400:
	movq	%rsp, %rbp
LCFI401:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$31, %eax
	leave
LCFI402:
	ret
LFE133:
.no_dead_strip _mod_pow2__mod_pow2_u64_6
_mod_pow2__mod_pow2_u64_6:
LFB134:
	pushq	%rbp
LCFI403:
	movq	%rsp, %rbp
LCFI404:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$63, %eax
	leave
LCFI405:
	ret
LFE134:
.no_dead_strip _mod_pow2__mod_pow2_u64_7
_mod_pow2__mod_pow2_u64_7:
LFB135:
	pushq	%rbp
LCFI406:
	movq	%rsp, %rbp
LCFI407:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$127, %eax
	leave
LCFI408:
	ret
LFE135:
.no_dead_strip _mod_pow2__mod_pow2_u64_8
_mod_pow2__mod_pow2_u64_8:
LFB136:
	pushq	%rbp
LCFI409:
	movq	%rsp, %rbp
LCFI410:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$255, %eax
	leave
LCFI411:
	ret
LFE136:
.no_dead_strip _mod_pow2__mod_pow2_u64_9
_mod_pow2__mod_pow2_u64_9:
LFB137:
	pushq	%rbp
LCFI412:
	movq	%rsp, %rbp
LCFI413:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$511, %eax
	leave
LCFI414:
	ret
LFE137:
.no_dead_strip _mod_pow2__mod_pow2_u64_10
_mod_pow2__mod_pow2_u64_10:
LFB138:
	pushq	%rbp
LCFI415:
	movq	%rsp, %rbp
LCFI416:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1023, %eax
	leave
LCFI417:
	ret
LFE138:
.no_dead_strip _mod_pow2__mod_pow2_u64_11
_mod_pow2__mod_pow2_u64_11:
LFB139:
	pushq	%rbp
LCFI418:
	movq	%rsp, %rbp
LCFI419:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2047, %eax
	leave
LCFI420:
	ret
LFE139:
.no_dead_strip _mod_pow2__mod_pow2_u64_12
_mod_pow2__mod_pow2_u64_12:
LFB140:
	pushq	%rbp
LCFI421:
	movq	%rsp, %rbp
LCFI422:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4095, %eax
	leave
LCFI423:
	ret
LFE140:
.no_dead_strip _mod_pow2__mod_pow2_u64_13
_mod_pow2__mod_pow2_u64_13:
LFB141:
	pushq	%rbp
LCFI424:
	movq	%rsp, %rbp
LCFI425:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$8191, %eax
	leave
LCFI426:
	ret
LFE141:
.no_dead_strip _mod_pow2__mod_pow2_u64_14
_mod_pow2__mod_pow2_u64_14:
LFB142:
	pushq	%rbp
LCFI427:
	movq	%rsp, %rbp
LCFI428:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$16383, %eax
	leave
LCFI429:
	ret
LFE142:
.no_dead_strip _mod_pow2__mod_pow2_u64_15
_mod_pow2__mod_pow2_u64_15:
LFB143:
	pushq	%rbp
LCFI430:
	movq	%rsp, %rbp
LCFI431:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$32767, %eax
	leave
LCFI432:
	ret
LFE143:
.no_dead_strip _mod_pow2__mod_pow2_u64_16
_mod_pow2__mod_pow2_u64_16:
LFB144:
	pushq	%rbp
LCFI433:
	movq	%rsp, %rbp
LCFI434:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$65535, %eax
	leave
LCFI435:
	ret
LFE144:
.no_dead_strip _mod_pow2__mod_pow2_u64_17
_mod_pow2__mod_pow2_u64_17:
LFB145:
	pushq	%rbp
LCFI436:
	movq	%rsp, %rbp
LCFI437:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$131071, %eax
	leave
LCFI438:
	ret
LFE145:
.no_dead_strip _mod_pow2__mod_pow2_u64_18
_mod_pow2__mod_pow2_u64_18:
LFB146:
	pushq	%rbp
LCFI439:
	movq	%rsp, %rbp
LCFI440:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$262143, %eax
	leave
LCFI441:
	ret
LFE146:
.no_dead_strip _mod_pow2__mod_pow2_u64_19
_mod_pow2__mod_pow2_u64_19:
LFB147:
	pushq	%rbp
LCFI442:
	movq	%rsp, %rbp
LCFI443:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$524287, %eax
	leave
LCFI444:
	ret
LFE147:
.no_dead_strip _mod_pow2__mod_pow2_u64_20
_mod_pow2__mod_pow2_u64_20:
LFB148:
	pushq	%rbp
LCFI445:
	movq	%rsp, %rbp
LCFI446:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1048575, %eax
	leave
LCFI447:
	ret
LFE148:
.no_dead_strip _mod_pow2__mod_pow2_u64_21
_mod_pow2__mod_pow2_u64_21:
LFB149:
	pushq	%rbp
LCFI448:
	movq	%rsp, %rbp
LCFI449:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2097151, %eax
	leave
LCFI450:
	ret
LFE149:
.no_dead_strip _mod_pow2__mod_pow2_u64_22
_mod_pow2__mod_pow2_u64_22:
LFB150:
	pushq	%rbp
LCFI451:
	movq	%rsp, %rbp
LCFI452:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4194303, %eax
	leave
LCFI453:
	ret
LFE150:
.no_dead_strip _mod_pow2__mod_pow2_u64_23
_mod_pow2__mod_pow2_u64_23:
LFB151:
	pushq	%rbp
LCFI454:
	movq	%rsp, %rbp
LCFI455:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$8388607, %eax
	leave
LCFI456:
	ret
LFE151:
.no_dead_strip _mod_pow2__mod_pow2_u64_24
_mod_pow2__mod_pow2_u64_24:
LFB152:
	pushq	%rbp
LCFI457:
	movq	%rsp, %rbp
LCFI458:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$16777215, %eax
	leave
LCFI459:
	ret
LFE152:
.no_dead_strip _mod_pow2__mod_pow2_u64_25
_mod_pow2__mod_pow2_u64_25:
LFB153:
	pushq	%rbp
LCFI460:
	movq	%rsp, %rbp
LCFI461:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$33554431, %eax
	leave
LCFI462:
	ret
LFE153:
.no_dead_strip _mod_pow2__mod_pow2_u64_26
_mod_pow2__mod_pow2_u64_26:
LFB154:
	pushq	%rbp
LCFI463:
	movq	%rsp, %rbp
LCFI464:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$67108863, %eax
	leave
LCFI465:
	ret
LFE154:
.no_dead_strip _mod_pow2__mod_pow2_u64_27
_mod_pow2__mod_pow2_u64_27:
LFB155:
	pushq	%rbp
LCFI466:
	movq	%rsp, %rbp
LCFI467:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$134217727, %eax
	leave
LCFI468:
	ret
LFE155:
.no_dead_strip _mod_pow2__mod_pow2_u64_28
_mod_pow2__mod_pow2_u64_28:
LFB156:
	pushq	%rbp
LCFI469:
	movq	%rsp, %rbp
LCFI470:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$268435455, %eax
	leave
LCFI471:
	ret
LFE156:
.no_dead_strip _mod_pow2__mod_pow2_u64_29
_mod_pow2__mod_pow2_u64_29:
LFB157:
	pushq	%rbp
LCFI472:
	movq	%rsp, %rbp
LCFI473:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$536870911, %eax
	leave
LCFI474:
	ret
LFE157:
.no_dead_strip _mod_pow2__mod_pow2_u64_30
_mod_pow2__mod_pow2_u64_30:
LFB158:
	pushq	%rbp
LCFI475:
	movq	%rsp, %rbp
LCFI476:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1073741823, %eax
	leave
LCFI477:
	ret
LFE158:
.no_dead_strip _mod_pow2__mod_pow2_u64_31
_mod_pow2__mod_pow2_u64_31:
LFB159:
	pushq	%rbp
LCFI478:
	movq	%rsp, %rbp
LCFI479:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2147483647, %eax
	leave
LCFI480:
	ret
LFE159:
.no_dead_strip _mod_pow2__mod_pow2_u64_32
_mod_pow2__mod_pow2_u64_32:
LFB160:
	pushq	%rbp
LCFI481:
	movq	%rsp, %rbp
LCFI482:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4294967295, %eax
	leave
LCFI483:
	ret
LFE160:
.no_dead_strip _mod_pow2__mod_pow2_u64_33
_mod_pow2__mod_pow2_u64_33:
LFB161:
	pushq	%rbp
LCFI484:
	movq	%rsp, %rbp
LCFI485:
	movq	%rdi, -8(%rbp)
	movabsq	$8589934591, %rax
	andq	-8(%rbp), %rax
	leave
LCFI486:
	ret
LFE161:
.no_dead_strip _mod_pow2__mod_pow2_u64_34
_mod_pow2__mod_pow2_u64_34:
LFB162:
	pushq	%rbp
LCFI487:
	movq	%rsp, %rbp
LCFI488:
	movq	%rdi, -8(%rbp)
	movabsq	$17179869183, %rax
	andq	-8(%rbp), %rax
	leave
LCFI489:
	ret
LFE162:
.no_dead_strip _mod_pow2__mod_pow2_u64_35
_mod_pow2__mod_pow2_u64_35:
LFB163:
	pushq	%rbp
LCFI490:
	movq	%rsp, %rbp
LCFI491:
	movq	%rdi, -8(%rbp)
	movabsq	$34359738367, %rax
	andq	-8(%rbp), %rax
	leave
LCFI492:
	ret
LFE163:
.no_dead_strip _mod_pow2__mod_pow2_u64_36
_mod_pow2__mod_pow2_u64_36:
LFB164:
	pushq	%rbp
LCFI493:
	movq	%rsp, %rbp
LCFI494:
	movq	%rdi, -8(%rbp)
	movabsq	$68719476735, %rax
	andq	-8(%rbp), %rax
	leave
LCFI495:
	ret
LFE164:
.no_dead_strip _mod_pow2__mod_pow2_u64_37
_mod_pow2__mod_pow2_u64_37:
LFB165:
	pushq	%rbp
LCFI496:
	movq	%rsp, %rbp
LCFI497:
	movq	%rdi, -8(%rbp)
	movabsq	$137438953471, %rax
	andq	-8(%rbp), %rax
	leave
LCFI498:
	ret
LFE165:
.no_dead_strip _mod_pow2__mod_pow2_u64_38
_mod_pow2__mod_pow2_u64_38:
LFB166:
	pushq	%rbp
LCFI499:
	movq	%rsp, %rbp
LCFI500:
	movq	%rdi, -8(%rbp)
	movabsq	$274877906943, %rax
	andq	-8(%rbp), %rax
	leave
LCFI501:
	ret
LFE166:
.no_dead_strip _mod_pow2__mod_pow2_u64_39
_mod_pow2__mod_pow2_u64_39:
LFB167:
	pushq	%rbp
LCFI502:
	movq	%rsp, %rbp
LCFI503:
	movq	%rdi, -8(%rbp)
	movabsq	$549755813887, %rax
	andq	-8(%rbp), %rax
	leave
LCFI504:
	ret
LFE167:
.no_dead_strip _mod_pow2__mod_pow2_u64_40
_mod_pow2__mod_pow2_u64_40:
LFB168:
	pushq	%rbp
LCFI505:
	movq	%rsp, %rbp
LCFI506:
	movq	%rdi, -8(%rbp)
	movabsq	$1099511627775, %rax
	andq	-8(%rbp), %rax
	leave
LCFI507:
	ret
LFE168:
.no_dead_strip _mod_pow2__mod_pow2_u64_41
_mod_pow2__mod_pow2_u64_41:
LFB169:
	pushq	%rbp
LCFI508:
	movq	%rsp, %rbp
LCFI509:
	movq	%rdi, -8(%rbp)
	movabsq	$2199023255551, %rax
	andq	-8(%rbp), %rax
	leave
LCFI510:
	ret
LFE169:
.no_dead_strip _mod_pow2__mod_pow2_u64_42
_mod_pow2__mod_pow2_u64_42:
LFB170:
	pushq	%rbp
LCFI511:
	movq	%rsp, %rbp
LCFI512:
	movq	%rdi, -8(%rbp)
	movabsq	$4398046511103, %rax
	andq	-8(%rbp), %rax
	leave
LCFI513:
	ret
LFE170:
.no_dead_strip _mod_pow2__mod_pow2_u64_43
_mod_pow2__mod_pow2_u64_43:
LFB171:
	pushq	%rbp
LCFI514:
	movq	%rsp, %rbp
LCFI515:
	movq	%rdi, -8(%rbp)
	movabsq	$8796093022207, %rax
	andq	-8(%rbp), %rax
	leave
LCFI516:
	ret
LFE171:
.no_dead_strip _mod_pow2__mod_pow2_u64_44
_mod_pow2__mod_pow2_u64_44:
LFB172:
	pushq	%rbp
LCFI517:
	movq	%rsp, %rbp
LCFI518:
	movq	%rdi, -8(%rbp)
	movabsq	$17592186044415, %rax
	andq	-8(%rbp), %rax
	leave
LCFI519:
	ret
LFE172:
.no_dead_strip _mod_pow2__mod_pow2_u64_45
_mod_pow2__mod_pow2_u64_45:
LFB173:
	pushq	%rbp
LCFI520:
	movq	%rsp, %rbp
LCFI521:
	movq	%rdi, -8(%rbp)
	movabsq	$35184372088831, %rax
	andq	-8(%rbp), %rax
	leave
LCFI522:
	ret
LFE173:
.no_dead_strip _mod_pow2__mod_pow2_u64_46
_mod_pow2__mod_pow2_u64_46:
LFB174:
	pushq	%rbp
LCFI523:
	movq	%rsp, %rbp
LCFI524:
	movq	%rdi, -8(%rbp)
	movabsq	$70368744177663, %rax
	andq	-8(%rbp), %rax
	leave
LCFI525:
	ret
LFE174:
.no_dead_strip _mod_pow2__mod_pow2_u64_47
_mod_pow2__mod_pow2_u64_47:
LFB175:
	pushq	%rbp
LCFI526:
	movq	%rsp, %rbp
LCFI527:
	movq	%rdi, -8(%rbp)
	movabsq	$140737488355327, %rax
	andq	-8(%rbp), %rax
	leave
LCFI528:
	ret
LFE175:
.no_dead_strip _mod_pow2__mod_pow2_u64_48
_mod_pow2__mod_pow2_u64_48:
LFB176:
	pushq	%rbp
LCFI529:
	movq	%rsp, %rbp
LCFI530:
	movq	%rdi, -8(%rbp)
	movabsq	$281474976710655, %rax
	andq	-8(%rbp), %rax
	leave
LCFI531:
	ret
LFE176:
.no_dead_strip _mod_pow2__mod_pow2_u64_49
_mod_pow2__mod_pow2_u64_49:
LFB177:
	pushq	%rbp
LCFI532:
	movq	%rsp, %rbp
LCFI533:
	movq	%rdi, -8(%rbp)
	movabsq	$562949953421311, %rax
	andq	-8(%rbp), %rax
	leave
LCFI534:
	ret
LFE177:
.no_dead_strip _mod_pow2__mod_pow2_u64_50
_mod_pow2__mod_pow2_u64_50:
LFB178:
	pushq	%rbp
LCFI535:
	movq	%rsp, %rbp
LCFI536:
	movq	%rdi, -8(%rbp)
	movabsq	$1125899906842623, %rax
	andq	-8(%rbp), %rax
	leave
LCFI537:
	ret
LFE178:
.no_dead_strip _mod_pow2__mod_pow2_u64_51
_mod_pow2__mod_pow2_u64_51:
LFB179:
	pushq	%rbp
LCFI538:
	movq	%rsp, %rbp
LCFI539:
	movq	%rdi, -8(%rbp)
	movabsq	$2251799813685247, %rax
	andq	-8(%rbp), %rax
	leave
LCFI540:
	ret
LFE179:
.no_dead_strip _mod_pow2__mod_pow2_u64_52
_mod_pow2__mod_pow2_u64_52:
LFB180:
	pushq	%rbp
LCFI541:
	movq	%rsp, %rbp
LCFI542:
	movq	%rdi, -8(%rbp)
	movabsq	$4503599627370495, %rax
	andq	-8(%rbp), %rax
	leave
LCFI543:
	ret
LFE180:
.no_dead_strip _mod_pow2__mod_pow2_u64_53
_mod_pow2__mod_pow2_u64_53:
LFB181:
	pushq	%rbp
LCFI544:
	movq	%rsp, %rbp
LCFI545:
	movq	%rdi, -8(%rbp)
	movabsq	$9007199254740991, %rax
	andq	-8(%rbp), %rax
	leave
LCFI546:
	ret
LFE181:
.no_dead_strip _mod_pow2__mod_pow2_u64_54
_mod_pow2__mod_pow2_u64_54:
LFB182:
	pushq	%rbp
LCFI547:
	movq	%rsp, %rbp
LCFI548:
	movq	%rdi, -8(%rbp)
	movabsq	$18014398509481983, %rax
	andq	-8(%rbp), %rax
	leave
LCFI549:
	ret
LFE182:
.no_dead_strip _mod_pow2__mod_pow2_u64_55
_mod_pow2__mod_pow2_u64_55:
LFB183:
	pushq	%rbp
LCFI550:
	movq	%rsp, %rbp
LCFI551:
	movq	%rdi, -8(%rbp)
	movabsq	$36028797018963967, %rax
	andq	-8(%rbp), %rax
	leave
LCFI552:
	ret
LFE183:
.no_dead_strip _mod_pow2__mod_pow2_u64_56
_mod_pow2__mod_pow2_u64_56:
LFB184:
	pushq	%rbp
LCFI553:
	movq	%rsp, %rbp
LCFI554:
	movq	%rdi, -8(%rbp)
	movabsq	$72057594037927935, %rax
	andq	-8(%rbp), %rax
	leave
LCFI555:
	ret
LFE184:
.no_dead_strip _mod_pow2__mod_pow2_u64_57
_mod_pow2__mod_pow2_u64_57:
LFB185:
	pushq	%rbp
LCFI556:
	movq	%rsp, %rbp
LCFI557:
	movq	%rdi, -8(%rbp)
	movabsq	$144115188075855871, %rax
	andq	-8(%rbp), %rax
	leave
LCFI558:
	ret
LFE185:
.no_dead_strip _mod_pow2__mod_pow2_u64_58
_mod_pow2__mod_pow2_u64_58:
LFB186:
	pushq	%rbp
LCFI559:
	movq	%rsp, %rbp
LCFI560:
	movq	%rdi, -8(%rbp)
	movabsq	$288230376151711743, %rax
	andq	-8(%rbp), %rax
	leave
LCFI561:
	ret
LFE186:
.no_dead_strip _mod_pow2__mod_pow2_u64_59
_mod_pow2__mod_pow2_u64_59:
LFB187:
	pushq	%rbp
LCFI562:
	movq	%rsp, %rbp
LCFI563:
	movq	%rdi, -8(%rbp)
	movabsq	$576460752303423487, %rax
	andq	-8(%rbp), %rax
	leave
LCFI564:
	ret
LFE187:
.no_dead_strip _mod_pow2__mod_pow2_u64_60
_mod_pow2__mod_pow2_u64_60:
LFB188:
	pushq	%rbp
LCFI565:
	movq	%rsp, %rbp
LCFI566:
	movq	%rdi, -8(%rbp)
	movabsq	$1152921504606846975, %rax
	andq	-8(%rbp), %rax
	leave
LCFI567:
	ret
LFE188:
.no_dead_strip _mod_pow2__mod_pow2_u64_61
_mod_pow2__mod_pow2_u64_61:
LFB189:
	pushq	%rbp
LCFI568:
	movq	%rsp, %rbp
LCFI569:
	movq	%rdi, -8(%rbp)
	movabsq	$2305843009213693951, %rax
	andq	-8(%rbp), %rax
	leave
LCFI570:
	ret
LFE189:
.no_dead_strip _mod_pow2__mod_pow2_u64_62
_mod_pow2__mod_pow2_u64_62:
LFB190:
	pushq	%rbp
LCFI571:
	movq	%rsp, %rbp
LCFI572:
	movq	%rdi, -8(%rbp)
	movabsq	$4611686018427387903, %rax
	andq	-8(%rbp), %rax
	leave
LCFI573:
	ret
LFE190:
.no_dead_strip _mod_pow2__mod_pow2_u64_63
_mod_pow2__mod_pow2_u64_63:
LFB191:
	pushq	%rbp
LCFI574:
	movq	%rsp, %rbp
LCFI575:
	pushq	%rbx
LCFI576:
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leaq	-1(%rax), %rdx
	movq	%rax, %rcx
	orq	%rdx, %rcx
	sarq	$63, %rcx
	movq	%rdx, %rbx
	subq	%rcx, %rbx
	movabsq	$-9223372036854775808, %rdx
	cmpq	%rdx, %rbx
	sete	%dl
	movzbl	%dl, %edx
	notq	%rcx
	addq	%rcx, %rdx
	salq	$63, %rdx
	movq	%rax, %rcx
	subq	%rdx, %rcx
	movq	%rcx, %rdx
	movq	%rdx, %rax
	popq	%rbx
	leave
LCFI577:
	ret
LFE191:
.no_dead_strip _mod_pow2__mod_pow2_I_0
_mod_pow2__mod_pow2_I_0:
LFB192:
	pushq	%rbp
LCFI578:
	movq	%rsp, %rbp
LCFI579:
	movq	%rdi, -8(%rbp)
	movl	$0, %eax
	leave
LCFI580:
	ret
LFE192:
.no_dead_strip _mod_pow2__mod_pow2_I_1
_mod_pow2__mod_pow2_I_1:
LFB193:
	pushq	%rbp
LCFI581:
	movq	%rsp, %rbp
LCFI582:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1, %eax
	leave
LCFI583:
	ret
LFE193:
.no_dead_strip _mod_pow2__mod_pow2_I_2
_mod_pow2__mod_pow2_I_2:
LFB194:
	pushq	%rbp
LCFI584:
	movq	%rsp, %rbp
LCFI585:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$3, %eax
	leave
LCFI586:
	ret
LFE194:
.no_dead_strip _mod_pow2__mod_pow2_I_3
_mod_pow2__mod_pow2_I_3:
LFB195:
	pushq	%rbp
LCFI587:
	movq	%rsp, %rbp
LCFI588:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$7, %eax
	leave
LCFI589:
	ret
LFE195:
.no_dead_strip _mod_pow2__mod_pow2_I_4
_mod_pow2__mod_pow2_I_4:
LFB196:
	pushq	%rbp
LCFI590:
	movq	%rsp, %rbp
LCFI591:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$15, %eax
	leave
LCFI592:
	ret
LFE196:
.no_dead_strip _mod_pow2__mod_pow2_I_5
_mod_pow2__mod_pow2_I_5:
LFB197:
	pushq	%rbp
LCFI593:
	movq	%rsp, %rbp
LCFI594:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$31, %eax
	leave
LCFI595:
	ret
LFE197:
.no_dead_strip _mod_pow2__mod_pow2_I_6
_mod_pow2__mod_pow2_I_6:
LFB198:
	pushq	%rbp
LCFI596:
	movq	%rsp, %rbp
LCFI597:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$63, %eax
	leave
LCFI598:
	ret
LFE198:
.no_dead_strip _mod_pow2__mod_pow2_I_7
_mod_pow2__mod_pow2_I_7:
LFB199:
	pushq	%rbp
LCFI599:
	movq	%rsp, %rbp
LCFI600:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$127, %eax
	leave
LCFI601:
	ret
LFE199:
.no_dead_strip _mod_pow2__mod_pow2_I_8
_mod_pow2__mod_pow2_I_8:
LFB200:
	pushq	%rbp
LCFI602:
	movq	%rsp, %rbp
LCFI603:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$255, %eax
	leave
LCFI604:
	ret
LFE200:
.no_dead_strip _mod_pow2__mod_pow2_I_9
_mod_pow2__mod_pow2_I_9:
LFB201:
	pushq	%rbp
LCFI605:
	movq	%rsp, %rbp
LCFI606:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$511, %eax
	leave
LCFI607:
	ret
LFE201:
.no_dead_strip _mod_pow2__mod_pow2_I_10
_mod_pow2__mod_pow2_I_10:
LFB202:
	pushq	%rbp
LCFI608:
	movq	%rsp, %rbp
LCFI609:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1023, %eax
	leave
LCFI610:
	ret
LFE202:
.no_dead_strip _mod_pow2__mod_pow2_I_11
_mod_pow2__mod_pow2_I_11:
LFB203:
	pushq	%rbp
LCFI611:
	movq	%rsp, %rbp
LCFI612:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2047, %eax
	leave
LCFI613:
	ret
LFE203:
.no_dead_strip _mod_pow2__mod_pow2_I_12
_mod_pow2__mod_pow2_I_12:
LFB204:
	pushq	%rbp
LCFI614:
	movq	%rsp, %rbp
LCFI615:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4095, %eax
	leave
LCFI616:
	ret
LFE204:
.no_dead_strip _mod_pow2__mod_pow2_I_13
_mod_pow2__mod_pow2_I_13:
LFB205:
	pushq	%rbp
LCFI617:
	movq	%rsp, %rbp
LCFI618:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$8191, %eax
	leave
LCFI619:
	ret
LFE205:
.no_dead_strip _mod_pow2__mod_pow2_I_14
_mod_pow2__mod_pow2_I_14:
LFB206:
	pushq	%rbp
LCFI620:
	movq	%rsp, %rbp
LCFI621:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$16383, %eax
	leave
LCFI622:
	ret
LFE206:
.no_dead_strip _mod_pow2__mod_pow2_I_15
_mod_pow2__mod_pow2_I_15:
LFB207:
	pushq	%rbp
LCFI623:
	movq	%rsp, %rbp
LCFI624:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$32767, %eax
	leave
LCFI625:
	ret
LFE207:
.no_dead_strip _mod_pow2__mod_pow2_I_16
_mod_pow2__mod_pow2_I_16:
LFB208:
	pushq	%rbp
LCFI626:
	movq	%rsp, %rbp
LCFI627:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$65535, %eax
	leave
LCFI628:
	ret
LFE208:
.no_dead_strip _mod_pow2__mod_pow2_I_17
_mod_pow2__mod_pow2_I_17:
LFB209:
	pushq	%rbp
LCFI629:
	movq	%rsp, %rbp
LCFI630:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$131071, %eax
	leave
LCFI631:
	ret
LFE209:
.no_dead_strip _mod_pow2__mod_pow2_I_18
_mod_pow2__mod_pow2_I_18:
LFB210:
	pushq	%rbp
LCFI632:
	movq	%rsp, %rbp
LCFI633:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$262143, %eax
	leave
LCFI634:
	ret
LFE210:
.no_dead_strip _mod_pow2__mod_pow2_I_19
_mod_pow2__mod_pow2_I_19:
LFB211:
	pushq	%rbp
LCFI635:
	movq	%rsp, %rbp
LCFI636:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$524287, %eax
	leave
LCFI637:
	ret
LFE211:
.no_dead_strip _mod_pow2__mod_pow2_I_20
_mod_pow2__mod_pow2_I_20:
LFB212:
	pushq	%rbp
LCFI638:
	movq	%rsp, %rbp
LCFI639:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1048575, %eax
	leave
LCFI640:
	ret
LFE212:
.no_dead_strip _mod_pow2__mod_pow2_I_21
_mod_pow2__mod_pow2_I_21:
LFB213:
	pushq	%rbp
LCFI641:
	movq	%rsp, %rbp
LCFI642:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2097151, %eax
	leave
LCFI643:
	ret
LFE213:
.no_dead_strip _mod_pow2__mod_pow2_I_22
_mod_pow2__mod_pow2_I_22:
LFB214:
	pushq	%rbp
LCFI644:
	movq	%rsp, %rbp
LCFI645:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4194303, %eax
	leave
LCFI646:
	ret
LFE214:
.no_dead_strip _mod_pow2__mod_pow2_I_23
_mod_pow2__mod_pow2_I_23:
LFB215:
	pushq	%rbp
LCFI647:
	movq	%rsp, %rbp
LCFI648:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$8388607, %eax
	leave
LCFI649:
	ret
LFE215:
.no_dead_strip _mod_pow2__mod_pow2_I_24
_mod_pow2__mod_pow2_I_24:
LFB216:
	pushq	%rbp
LCFI650:
	movq	%rsp, %rbp
LCFI651:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$16777215, %eax
	leave
LCFI652:
	ret
LFE216:
.no_dead_strip _mod_pow2__mod_pow2_I_25
_mod_pow2__mod_pow2_I_25:
LFB217:
	pushq	%rbp
LCFI653:
	movq	%rsp, %rbp
LCFI654:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$33554431, %eax
	leave
LCFI655:
	ret
LFE217:
.no_dead_strip _mod_pow2__mod_pow2_I_26
_mod_pow2__mod_pow2_I_26:
LFB218:
	pushq	%rbp
LCFI656:
	movq	%rsp, %rbp
LCFI657:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$67108863, %eax
	leave
LCFI658:
	ret
LFE218:
.no_dead_strip _mod_pow2__mod_pow2_I_27
_mod_pow2__mod_pow2_I_27:
LFB219:
	pushq	%rbp
LCFI659:
	movq	%rsp, %rbp
LCFI660:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$134217727, %eax
	leave
LCFI661:
	ret
LFE219:
.no_dead_strip _mod_pow2__mod_pow2_I_28
_mod_pow2__mod_pow2_I_28:
LFB220:
	pushq	%rbp
LCFI662:
	movq	%rsp, %rbp
LCFI663:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$268435455, %eax
	leave
LCFI664:
	ret
LFE220:
.no_dead_strip _mod_pow2__mod_pow2_I_29
_mod_pow2__mod_pow2_I_29:
LFB221:
	pushq	%rbp
LCFI665:
	movq	%rsp, %rbp
LCFI666:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$536870911, %eax
	leave
LCFI667:
	ret
LFE221:
.no_dead_strip _mod_pow2__mod_pow2_I_30
_mod_pow2__mod_pow2_I_30:
LFB222:
	pushq	%rbp
LCFI668:
	movq	%rsp, %rbp
LCFI669:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1073741823, %eax
	leave
LCFI670:
	ret
LFE222:
.no_dead_strip _mod_pow2__mod_pow2_I_31
_mod_pow2__mod_pow2_I_31:
LFB223:
	pushq	%rbp
LCFI671:
	movq	%rsp, %rbp
LCFI672:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2147483647, %eax
	leave
LCFI673:
	ret
LFE223:
.no_dead_strip _mod_pow2__mod_pow2_I_32
_mod_pow2__mod_pow2_I_32:
LFB224:
	pushq	%rbp
LCFI674:
	movq	%rsp, %rbp
LCFI675:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4294967295, %eax
	leave
LCFI676:
	ret
LFE224:
.no_dead_strip _mod_pow2__mod_pow2_I_33
_mod_pow2__mod_pow2_I_33:
LFB225:
	pushq	%rbp
LCFI677:
	movq	%rsp, %rbp
LCFI678:
	movq	%rdi, -8(%rbp)
	movabsq	$8589934591, %rax
	andq	-8(%rbp), %rax
	leave
LCFI679:
	ret
LFE225:
.no_dead_strip _mod_pow2__mod_pow2_I_34
_mod_pow2__mod_pow2_I_34:
LFB226:
	pushq	%rbp
LCFI680:
	movq	%rsp, %rbp
LCFI681:
	movq	%rdi, -8(%rbp)
	movabsq	$17179869183, %rax
	andq	-8(%rbp), %rax
	leave
LCFI682:
	ret
LFE226:
.no_dead_strip _mod_pow2__mod_pow2_I_35
_mod_pow2__mod_pow2_I_35:
LFB227:
	pushq	%rbp
LCFI683:
	movq	%rsp, %rbp
LCFI684:
	movq	%rdi, -8(%rbp)
	movabsq	$34359738367, %rax
	andq	-8(%rbp), %rax
	leave
LCFI685:
	ret
LFE227:
.no_dead_strip _mod_pow2__mod_pow2_I_36
_mod_pow2__mod_pow2_I_36:
LFB228:
	pushq	%rbp
LCFI686:
	movq	%rsp, %rbp
LCFI687:
	movq	%rdi, -8(%rbp)
	movabsq	$68719476735, %rax
	andq	-8(%rbp), %rax
	leave
LCFI688:
	ret
LFE228:
.no_dead_strip _mod_pow2__mod_pow2_I_37
_mod_pow2__mod_pow2_I_37:
LFB229:
	pushq	%rbp
LCFI689:
	movq	%rsp, %rbp
LCFI690:
	movq	%rdi, -8(%rbp)
	movabsq	$137438953471, %rax
	andq	-8(%rbp), %rax
	leave
LCFI691:
	ret
LFE229:
.no_dead_strip _mod_pow2__mod_pow2_I_38
_mod_pow2__mod_pow2_I_38:
LFB230:
	pushq	%rbp
LCFI692:
	movq	%rsp, %rbp
LCFI693:
	movq	%rdi, -8(%rbp)
	movabsq	$274877906943, %rax
	andq	-8(%rbp), %rax
	leave
LCFI694:
	ret
LFE230:
.no_dead_strip _mod_pow2__mod_pow2_I_39
_mod_pow2__mod_pow2_I_39:
LFB231:
	pushq	%rbp
LCFI695:
	movq	%rsp, %rbp
LCFI696:
	movq	%rdi, -8(%rbp)
	movabsq	$549755813887, %rax
	andq	-8(%rbp), %rax
	leave
LCFI697:
	ret
LFE231:
.no_dead_strip _mod_pow2__mod_pow2_I_40
_mod_pow2__mod_pow2_I_40:
LFB232:
	pushq	%rbp
LCFI698:
	movq	%rsp, %rbp
LCFI699:
	movq	%rdi, -8(%rbp)
	movabsq	$1099511627775, %rax
	andq	-8(%rbp), %rax
	leave
LCFI700:
	ret
LFE232:
.no_dead_strip _mod_pow2__mod_pow2_I_41
_mod_pow2__mod_pow2_I_41:
LFB233:
	pushq	%rbp
LCFI701:
	movq	%rsp, %rbp
LCFI702:
	movq	%rdi, -8(%rbp)
	movabsq	$2199023255551, %rax
	andq	-8(%rbp), %rax
	leave
LCFI703:
	ret
LFE233:
.no_dead_strip _mod_pow2__mod_pow2_I_42
_mod_pow2__mod_pow2_I_42:
LFB234:
	pushq	%rbp
LCFI704:
	movq	%rsp, %rbp
LCFI705:
	movq	%rdi, -8(%rbp)
	movabsq	$4398046511103, %rax
	andq	-8(%rbp), %rax
	leave
LCFI706:
	ret
LFE234:
.no_dead_strip _mod_pow2__mod_pow2_I_43
_mod_pow2__mod_pow2_I_43:
LFB235:
	pushq	%rbp
LCFI707:
	movq	%rsp, %rbp
LCFI708:
	movq	%rdi, -8(%rbp)
	movabsq	$8796093022207, %rax
	andq	-8(%rbp), %rax
	leave
LCFI709:
	ret
LFE235:
.no_dead_strip _mod_pow2__mod_pow2_I_44
_mod_pow2__mod_pow2_I_44:
LFB236:
	pushq	%rbp
LCFI710:
	movq	%rsp, %rbp
LCFI711:
	movq	%rdi, -8(%rbp)
	movabsq	$17592186044415, %rax
	andq	-8(%rbp), %rax
	leave
LCFI712:
	ret
LFE236:
.no_dead_strip _mod_pow2__mod_pow2_I_45
_mod_pow2__mod_pow2_I_45:
LFB237:
	pushq	%rbp
LCFI713:
	movq	%rsp, %rbp
LCFI714:
	movq	%rdi, -8(%rbp)
	movabsq	$35184372088831, %rax
	andq	-8(%rbp), %rax
	leave
LCFI715:
	ret
LFE237:
.no_dead_strip _mod_pow2__mod_pow2_I_46
_mod_pow2__mod_pow2_I_46:
LFB238:
	pushq	%rbp
LCFI716:
	movq	%rsp, %rbp
LCFI717:
	movq	%rdi, -8(%rbp)
	movabsq	$70368744177663, %rax
	andq	-8(%rbp), %rax
	leave
LCFI718:
	ret
LFE238:
.no_dead_strip _mod_pow2__mod_pow2_I_47
_mod_pow2__mod_pow2_I_47:
LFB239:
	pushq	%rbp
LCFI719:
	movq	%rsp, %rbp
LCFI720:
	movq	%rdi, -8(%rbp)
	movabsq	$140737488355327, %rax
	andq	-8(%rbp), %rax
	leave
LCFI721:
	ret
LFE239:
.no_dead_strip _mod_pow2__mod_pow2_I_48
_mod_pow2__mod_pow2_I_48:
LFB240:
	pushq	%rbp
LCFI722:
	movq	%rsp, %rbp
LCFI723:
	movq	%rdi, -8(%rbp)
	movabsq	$281474976710655, %rax
	andq	-8(%rbp), %rax
	leave
LCFI724:
	ret
LFE240:
.no_dead_strip _mod_pow2__mod_pow2_I_49
_mod_pow2__mod_pow2_I_49:
LFB241:
	pushq	%rbp
LCFI725:
	movq	%rsp, %rbp
LCFI726:
	movq	%rdi, -8(%rbp)
	movabsq	$562949953421311, %rax
	andq	-8(%rbp), %rax
	leave
LCFI727:
	ret
LFE241:
.no_dead_strip _mod_pow2__mod_pow2_I_50
_mod_pow2__mod_pow2_I_50:
LFB242:
	pushq	%rbp
LCFI728:
	movq	%rsp, %rbp
LCFI729:
	movq	%rdi, -8(%rbp)
	movabsq	$1125899906842623, %rax
	andq	-8(%rbp), %rax
	leave
LCFI730:
	ret
LFE242:
.no_dead_strip _mod_pow2__mod_pow2_I_51
_mod_pow2__mod_pow2_I_51:
LFB243:
	pushq	%rbp
LCFI731:
	movq	%rsp, %rbp
LCFI732:
	movq	%rdi, -8(%rbp)
	movabsq	$2251799813685247, %rax
	andq	-8(%rbp), %rax
	leave
LCFI733:
	ret
LFE243:
.no_dead_strip _mod_pow2__mod_pow2_I_52
_mod_pow2__mod_pow2_I_52:
LFB244:
	pushq	%rbp
LCFI734:
	movq	%rsp, %rbp
LCFI735:
	movq	%rdi, -8(%rbp)
	movabsq	$4503599627370495, %rax
	andq	-8(%rbp), %rax
	leave
LCFI736:
	ret
LFE244:
.no_dead_strip _mod_pow2__mod_pow2_I_53
_mod_pow2__mod_pow2_I_53:
LFB245:
	pushq	%rbp
LCFI737:
	movq	%rsp, %rbp
LCFI738:
	movq	%rdi, -8(%rbp)
	movabsq	$9007199254740991, %rax
	andq	-8(%rbp), %rax
	leave
LCFI739:
	ret
LFE245:
.no_dead_strip _mod_pow2__mod_pow2_I_54
_mod_pow2__mod_pow2_I_54:
LFB246:
	pushq	%rbp
LCFI740:
	movq	%rsp, %rbp
LCFI741:
	movq	%rdi, -8(%rbp)
	movabsq	$18014398509481983, %rax
	andq	-8(%rbp), %rax
	leave
LCFI742:
	ret
LFE246:
.no_dead_strip _mod_pow2__mod_pow2_I_55
_mod_pow2__mod_pow2_I_55:
LFB247:
	pushq	%rbp
LCFI743:
	movq	%rsp, %rbp
LCFI744:
	movq	%rdi, -8(%rbp)
	movabsq	$36028797018963967, %rax
	andq	-8(%rbp), %rax
	leave
LCFI745:
	ret
LFE247:
.no_dead_strip _mod_pow2__mod_pow2_I_56
_mod_pow2__mod_pow2_I_56:
LFB248:
	pushq	%rbp
LCFI746:
	movq	%rsp, %rbp
LCFI747:
	movq	%rdi, -8(%rbp)
	movabsq	$72057594037927935, %rax
	andq	-8(%rbp), %rax
	leave
LCFI748:
	ret
LFE248:
.no_dead_strip _mod_pow2__mod_pow2_I_57
_mod_pow2__mod_pow2_I_57:
LFB249:
	pushq	%rbp
LCFI749:
	movq	%rsp, %rbp
LCFI750:
	movq	%rdi, -8(%rbp)
	movabsq	$144115188075855871, %rax
	andq	-8(%rbp), %rax
	leave
LCFI751:
	ret
LFE249:
.no_dead_strip _mod_pow2__mod_pow2_I_58
_mod_pow2__mod_pow2_I_58:
LFB250:
	pushq	%rbp
LCFI752:
	movq	%rsp, %rbp
LCFI753:
	movq	%rdi, -8(%rbp)
	movabsq	$288230376151711743, %rax
	andq	-8(%rbp), %rax
	leave
LCFI754:
	ret
LFE250:
.no_dead_strip _mod_pow2__mod_pow2_I_59
_mod_pow2__mod_pow2_I_59:
LFB251:
	pushq	%rbp
LCFI755:
	movq	%rsp, %rbp
LCFI756:
	movq	%rdi, -8(%rbp)
	movabsq	$576460752303423487, %rax
	andq	-8(%rbp), %rax
	leave
LCFI757:
	ret
LFE251:
.no_dead_strip _mod_pow2__mod_pow2_I_60
_mod_pow2__mod_pow2_I_60:
LFB252:
	pushq	%rbp
LCFI758:
	movq	%rsp, %rbp
LCFI759:
	movq	%rdi, -8(%rbp)
	movabsq	$1152921504606846975, %rax
	andq	-8(%rbp), %rax
	leave
LCFI760:
	ret
LFE252:
.no_dead_strip _mod_pow2__mod_pow2_I_61
_mod_pow2__mod_pow2_I_61:
LFB253:
	pushq	%rbp
LCFI761:
	movq	%rsp, %rbp
LCFI762:
	movq	%rdi, -8(%rbp)
	movabsq	$2305843009213693951, %rax
	andq	-8(%rbp), %rax
	leave
LCFI763:
	ret
LFE253:
.no_dead_strip _mod_pow2__mod_pow2_I_62
_mod_pow2__mod_pow2_I_62:
LFB254:
	pushq	%rbp
LCFI764:
	movq	%rsp, %rbp
LCFI765:
	movq	%rdi, -8(%rbp)
	movabsq	$4611686018427387903, %rax
	andq	-8(%rbp), %rax
	leave
LCFI766:
	ret
LFE254:
.no_dead_strip _mod_pow2__mod_pow2_I_63
_mod_pow2__mod_pow2_I_63:
LFB255:
	pushq	%rbp
LCFI767:
	movq	%rsp, %rbp
LCFI768:
	pushq	%rbx
LCFI769:
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leaq	-1(%rax), %rdx
	movq	%rax, %rcx
	orq	%rdx, %rcx
	sarq	$63, %rcx
	movq	%rdx, %rbx
	subq	%rcx, %rbx
	movabsq	$-9223372036854775808, %rdx
	cmpq	%rdx, %rbx
	sete	%dl
	movzbl	%dl, %edx
	notq	%rcx
	addq	%rcx, %rdx
	salq	$63, %rdx
	movq	%rax, %rcx
	subq	%rdx, %rcx
	movq	%rcx, %rdx
	movq	%rdx, %rax
	popq	%rbx
	leave
LCFI770:
	ret
LFE255:
.no_dead_strip _mod_pow2__mod_pow2_C_0
_mod_pow2__mod_pow2_C_0:
LFB256:
	pushq	%rbp
LCFI771:
	movq	%rsp, %rbp
LCFI772:
	movq	%rdi, -8(%rbp)
	movl	$0, %eax
	leave
LCFI773:
	ret
LFE256:
.no_dead_strip _mod_pow2__mod_pow2_C_1
_mod_pow2__mod_pow2_C_1:
LFB257:
	pushq	%rbp
LCFI774:
	movq	%rsp, %rbp
LCFI775:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1, %eax
	leave
LCFI776:
	ret
LFE257:
.no_dead_strip _mod_pow2__mod_pow2_C_2
_mod_pow2__mod_pow2_C_2:
LFB258:
	pushq	%rbp
LCFI777:
	movq	%rsp, %rbp
LCFI778:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$3, %eax
	leave
LCFI779:
	ret
LFE258:
.no_dead_strip _mod_pow2__mod_pow2_C_3
_mod_pow2__mod_pow2_C_3:
LFB259:
	pushq	%rbp
LCFI780:
	movq	%rsp, %rbp
LCFI781:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$7, %eax
	leave
LCFI782:
	ret
LFE259:
.no_dead_strip _mod_pow2__mod_pow2_C_4
_mod_pow2__mod_pow2_C_4:
LFB260:
	pushq	%rbp
LCFI783:
	movq	%rsp, %rbp
LCFI784:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$15, %eax
	leave
LCFI785:
	ret
LFE260:
.no_dead_strip _mod_pow2__mod_pow2_C_5
_mod_pow2__mod_pow2_C_5:
LFB261:
	pushq	%rbp
LCFI786:
	movq	%rsp, %rbp
LCFI787:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$31, %eax
	leave
LCFI788:
	ret
LFE261:
.no_dead_strip _mod_pow2__mod_pow2_C_6
_mod_pow2__mod_pow2_C_6:
LFB262:
	pushq	%rbp
LCFI789:
	movq	%rsp, %rbp
LCFI790:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$63, %eax
	leave
LCFI791:
	ret
LFE262:
.no_dead_strip _mod_pow2__mod_pow2_C_7
_mod_pow2__mod_pow2_C_7:
LFB263:
	pushq	%rbp
LCFI792:
	movq	%rsp, %rbp
LCFI793:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$127, %eax
	leave
LCFI794:
	ret
LFE263:
.no_dead_strip _mod_pow2__mod_pow2_C_8
_mod_pow2__mod_pow2_C_8:
LFB264:
	pushq	%rbp
LCFI795:
	movq	%rsp, %rbp
LCFI796:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$255, %eax
	leave
LCFI797:
	ret
LFE264:
.no_dead_strip _mod_pow2__mod_pow2_C_9
_mod_pow2__mod_pow2_C_9:
LFB265:
	pushq	%rbp
LCFI798:
	movq	%rsp, %rbp
LCFI799:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$511, %eax
	leave
LCFI800:
	ret
LFE265:
.no_dead_strip _mod_pow2__mod_pow2_C_10
_mod_pow2__mod_pow2_C_10:
LFB266:
	pushq	%rbp
LCFI801:
	movq	%rsp, %rbp
LCFI802:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1023, %eax
	leave
LCFI803:
	ret
LFE266:
.no_dead_strip _mod_pow2__mod_pow2_C_11
_mod_pow2__mod_pow2_C_11:
LFB267:
	pushq	%rbp
LCFI804:
	movq	%rsp, %rbp
LCFI805:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2047, %eax
	leave
LCFI806:
	ret
LFE267:
.no_dead_strip _mod_pow2__mod_pow2_C_12
_mod_pow2__mod_pow2_C_12:
LFB268:
	pushq	%rbp
LCFI807:
	movq	%rsp, %rbp
LCFI808:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4095, %eax
	leave
LCFI809:
	ret
LFE268:
.no_dead_strip _mod_pow2__mod_pow2_C_13
_mod_pow2__mod_pow2_C_13:
LFB269:
	pushq	%rbp
LCFI810:
	movq	%rsp, %rbp
LCFI811:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$8191, %eax
	leave
LCFI812:
	ret
LFE269:
.no_dead_strip _mod_pow2__mod_pow2_C_14
_mod_pow2__mod_pow2_C_14:
LFB270:
	pushq	%rbp
LCFI813:
	movq	%rsp, %rbp
LCFI814:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$16383, %eax
	leave
LCFI815:
	ret
LFE270:
.no_dead_strip _mod_pow2__mod_pow2_C_15
_mod_pow2__mod_pow2_C_15:
LFB271:
	pushq	%rbp
LCFI816:
	movq	%rsp, %rbp
LCFI817:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$32767, %eax
	leave
LCFI818:
	ret
LFE271:
.no_dead_strip _mod_pow2__mod_pow2_C_16
_mod_pow2__mod_pow2_C_16:
LFB272:
	pushq	%rbp
LCFI819:
	movq	%rsp, %rbp
LCFI820:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$65535, %eax
	leave
LCFI821:
	ret
LFE272:
.no_dead_strip _mod_pow2__mod_pow2_C_17
_mod_pow2__mod_pow2_C_17:
LFB273:
	pushq	%rbp
LCFI822:
	movq	%rsp, %rbp
LCFI823:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$131071, %eax
	leave
LCFI824:
	ret
LFE273:
.no_dead_strip _mod_pow2__mod_pow2_C_18
_mod_pow2__mod_pow2_C_18:
LFB274:
	pushq	%rbp
LCFI825:
	movq	%rsp, %rbp
LCFI826:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$262143, %eax
	leave
LCFI827:
	ret
LFE274:
.no_dead_strip _mod_pow2__mod_pow2_C_19
_mod_pow2__mod_pow2_C_19:
LFB275:
	pushq	%rbp
LCFI828:
	movq	%rsp, %rbp
LCFI829:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$524287, %eax
	leave
LCFI830:
	ret
LFE275:
.no_dead_strip _mod_pow2__mod_pow2_C_20
_mod_pow2__mod_pow2_C_20:
LFB276:
	pushq	%rbp
LCFI831:
	movq	%rsp, %rbp
LCFI832:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1048575, %eax
	leave
LCFI833:
	ret
LFE276:
.no_dead_strip _mod_pow2__mod_pow2_C_21
_mod_pow2__mod_pow2_C_21:
LFB277:
	pushq	%rbp
LCFI834:
	movq	%rsp, %rbp
LCFI835:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2097151, %eax
	leave
LCFI836:
	ret
LFE277:
.no_dead_strip _mod_pow2__mod_pow2_C_22
_mod_pow2__mod_pow2_C_22:
LFB278:
	pushq	%rbp
LCFI837:
	movq	%rsp, %rbp
LCFI838:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4194303, %eax
	leave
LCFI839:
	ret
LFE278:
.no_dead_strip _mod_pow2__mod_pow2_C_23
_mod_pow2__mod_pow2_C_23:
LFB279:
	pushq	%rbp
LCFI840:
	movq	%rsp, %rbp
LCFI841:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$8388607, %eax
	leave
LCFI842:
	ret
LFE279:
.no_dead_strip _mod_pow2__mod_pow2_C_24
_mod_pow2__mod_pow2_C_24:
LFB280:
	pushq	%rbp
LCFI843:
	movq	%rsp, %rbp
LCFI844:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$16777215, %eax
	leave
LCFI845:
	ret
LFE280:
.no_dead_strip _mod_pow2__mod_pow2_C_25
_mod_pow2__mod_pow2_C_25:
LFB281:
	pushq	%rbp
LCFI846:
	movq	%rsp, %rbp
LCFI847:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$33554431, %eax
	leave
LCFI848:
	ret
LFE281:
.no_dead_strip _mod_pow2__mod_pow2_C_26
_mod_pow2__mod_pow2_C_26:
LFB282:
	pushq	%rbp
LCFI849:
	movq	%rsp, %rbp
LCFI850:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$67108863, %eax
	leave
LCFI851:
	ret
LFE282:
.no_dead_strip _mod_pow2__mod_pow2_C_27
_mod_pow2__mod_pow2_C_27:
LFB283:
	pushq	%rbp
LCFI852:
	movq	%rsp, %rbp
LCFI853:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$134217727, %eax
	leave
LCFI854:
	ret
LFE283:
.no_dead_strip _mod_pow2__mod_pow2_C_28
_mod_pow2__mod_pow2_C_28:
LFB284:
	pushq	%rbp
LCFI855:
	movq	%rsp, %rbp
LCFI856:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$268435455, %eax
	leave
LCFI857:
	ret
LFE284:
.no_dead_strip _mod_pow2__mod_pow2_C_29
_mod_pow2__mod_pow2_C_29:
LFB285:
	pushq	%rbp
LCFI858:
	movq	%rsp, %rbp
LCFI859:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$536870911, %eax
	leave
LCFI860:
	ret
LFE285:
.no_dead_strip _mod_pow2__mod_pow2_C_30
_mod_pow2__mod_pow2_C_30:
LFB286:
	pushq	%rbp
LCFI861:
	movq	%rsp, %rbp
LCFI862:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1073741823, %eax
	leave
LCFI863:
	ret
LFE286:
.no_dead_strip _mod_pow2__mod_pow2_C_31
_mod_pow2__mod_pow2_C_31:
LFB287:
	pushq	%rbp
LCFI864:
	movq	%rsp, %rbp
LCFI865:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2147483647, %eax
	leave
LCFI866:
	ret
LFE287:
.no_dead_strip _mod_pow2__mod_pow2_C_32
_mod_pow2__mod_pow2_C_32:
LFB288:
	pushq	%rbp
LCFI867:
	movq	%rsp, %rbp
LCFI868:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4294967295, %eax
	leave
LCFI869:
	ret
LFE288:
.no_dead_strip _mod_pow2__mod_pow2_C_33
_mod_pow2__mod_pow2_C_33:
LFB289:
	pushq	%rbp
LCFI870:
	movq	%rsp, %rbp
LCFI871:
	movq	%rdi, -8(%rbp)
	movabsq	$8589934591, %rax
	andq	-8(%rbp), %rax
	leave
LCFI872:
	ret
LFE289:
.no_dead_strip _mod_pow2__mod_pow2_C_34
_mod_pow2__mod_pow2_C_34:
LFB290:
	pushq	%rbp
LCFI873:
	movq	%rsp, %rbp
LCFI874:
	movq	%rdi, -8(%rbp)
	movabsq	$17179869183, %rax
	andq	-8(%rbp), %rax
	leave
LCFI875:
	ret
LFE290:
.no_dead_strip _mod_pow2__mod_pow2_C_35
_mod_pow2__mod_pow2_C_35:
LFB291:
	pushq	%rbp
LCFI876:
	movq	%rsp, %rbp
LCFI877:
	movq	%rdi, -8(%rbp)
	movabsq	$34359738367, %rax
	andq	-8(%rbp), %rax
	leave
LCFI878:
	ret
LFE291:
.no_dead_strip _mod_pow2__mod_pow2_C_36
_mod_pow2__mod_pow2_C_36:
LFB292:
	pushq	%rbp
LCFI879:
	movq	%rsp, %rbp
LCFI880:
	movq	%rdi, -8(%rbp)
	movabsq	$68719476735, %rax
	andq	-8(%rbp), %rax
	leave
LCFI881:
	ret
LFE292:
.no_dead_strip _mod_pow2__mod_pow2_C_37
_mod_pow2__mod_pow2_C_37:
LFB293:
	pushq	%rbp
LCFI882:
	movq	%rsp, %rbp
LCFI883:
	movq	%rdi, -8(%rbp)
	movabsq	$137438953471, %rax
	andq	-8(%rbp), %rax
	leave
LCFI884:
	ret
LFE293:
.no_dead_strip _mod_pow2__mod_pow2_C_38
_mod_pow2__mod_pow2_C_38:
LFB294:
	pushq	%rbp
LCFI885:
	movq	%rsp, %rbp
LCFI886:
	movq	%rdi, -8(%rbp)
	movabsq	$274877906943, %rax
	andq	-8(%rbp), %rax
	leave
LCFI887:
	ret
LFE294:
.no_dead_strip _mod_pow2__mod_pow2_C_39
_mod_pow2__mod_pow2_C_39:
LFB295:
	pushq	%rbp
LCFI888:
	movq	%rsp, %rbp
LCFI889:
	movq	%rdi, -8(%rbp)
	movabsq	$549755813887, %rax
	andq	-8(%rbp), %rax
	leave
LCFI890:
	ret
LFE295:
.no_dead_strip _mod_pow2__mod_pow2_C_40
_mod_pow2__mod_pow2_C_40:
LFB296:
	pushq	%rbp
LCFI891:
	movq	%rsp, %rbp
LCFI892:
	movq	%rdi, -8(%rbp)
	movabsq	$1099511627775, %rax
	andq	-8(%rbp), %rax
	leave
LCFI893:
	ret
LFE296:
.no_dead_strip _mod_pow2__mod_pow2_C_41
_mod_pow2__mod_pow2_C_41:
LFB297:
	pushq	%rbp
LCFI894:
	movq	%rsp, %rbp
LCFI895:
	movq	%rdi, -8(%rbp)
	movabsq	$2199023255551, %rax
	andq	-8(%rbp), %rax
	leave
LCFI896:
	ret
LFE297:
.no_dead_strip _mod_pow2__mod_pow2_C_42
_mod_pow2__mod_pow2_C_42:
LFB298:
	pushq	%rbp
LCFI897:
	movq	%rsp, %rbp
LCFI898:
	movq	%rdi, -8(%rbp)
	movabsq	$4398046511103, %rax
	andq	-8(%rbp), %rax
	leave
LCFI899:
	ret
LFE298:
.no_dead_strip _mod_pow2__mod_pow2_C_43
_mod_pow2__mod_pow2_C_43:
LFB299:
	pushq	%rbp
LCFI900:
	movq	%rsp, %rbp
LCFI901:
	movq	%rdi, -8(%rbp)
	movabsq	$8796093022207, %rax
	andq	-8(%rbp), %rax
	leave
LCFI902:
	ret
LFE299:
.no_dead_strip _mod_pow2__mod_pow2_C_44
_mod_pow2__mod_pow2_C_44:
LFB300:
	pushq	%rbp
LCFI903:
	movq	%rsp, %rbp
LCFI904:
	movq	%rdi, -8(%rbp)
	movabsq	$17592186044415, %rax
	andq	-8(%rbp), %rax
	leave
LCFI905:
	ret
LFE300:
.no_dead_strip _mod_pow2__mod_pow2_C_45
_mod_pow2__mod_pow2_C_45:
LFB301:
	pushq	%rbp
LCFI906:
	movq	%rsp, %rbp
LCFI907:
	movq	%rdi, -8(%rbp)
	movabsq	$35184372088831, %rax
	andq	-8(%rbp), %rax
	leave
LCFI908:
	ret
LFE301:
.no_dead_strip _mod_pow2__mod_pow2_C_46
_mod_pow2__mod_pow2_C_46:
LFB302:
	pushq	%rbp
LCFI909:
	movq	%rsp, %rbp
LCFI910:
	movq	%rdi, -8(%rbp)
	movabsq	$70368744177663, %rax
	andq	-8(%rbp), %rax
	leave
LCFI911:
	ret
LFE302:
.no_dead_strip _mod_pow2__mod_pow2_C_47
_mod_pow2__mod_pow2_C_47:
LFB303:
	pushq	%rbp
LCFI912:
	movq	%rsp, %rbp
LCFI913:
	movq	%rdi, -8(%rbp)
	movabsq	$140737488355327, %rax
	andq	-8(%rbp), %rax
	leave
LCFI914:
	ret
LFE303:
.no_dead_strip _mod_pow2__mod_pow2_C_48
_mod_pow2__mod_pow2_C_48:
LFB304:
	pushq	%rbp
LCFI915:
	movq	%rsp, %rbp
LCFI916:
	movq	%rdi, -8(%rbp)
	movabsq	$281474976710655, %rax
	andq	-8(%rbp), %rax
	leave
LCFI917:
	ret
LFE304:
.no_dead_strip _mod_pow2__mod_pow2_C_49
_mod_pow2__mod_pow2_C_49:
LFB305:
	pushq	%rbp
LCFI918:
	movq	%rsp, %rbp
LCFI919:
	movq	%rdi, -8(%rbp)
	movabsq	$562949953421311, %rax
	andq	-8(%rbp), %rax
	leave
LCFI920:
	ret
LFE305:
.no_dead_strip _mod_pow2__mod_pow2_C_50
_mod_pow2__mod_pow2_C_50:
LFB306:
	pushq	%rbp
LCFI921:
	movq	%rsp, %rbp
LCFI922:
	movq	%rdi, -8(%rbp)
	movabsq	$1125899906842623, %rax
	andq	-8(%rbp), %rax
	leave
LCFI923:
	ret
LFE306:
.no_dead_strip _mod_pow2__mod_pow2_C_51
_mod_pow2__mod_pow2_C_51:
LFB307:
	pushq	%rbp
LCFI924:
	movq	%rsp, %rbp
LCFI925:
	movq	%rdi, -8(%rbp)
	movabsq	$2251799813685247, %rax
	andq	-8(%rbp), %rax
	leave
LCFI926:
	ret
LFE307:
.no_dead_strip _mod_pow2__mod_pow2_C_52
_mod_pow2__mod_pow2_C_52:
LFB308:
	pushq	%rbp
LCFI927:
	movq	%rsp, %rbp
LCFI928:
	movq	%rdi, -8(%rbp)
	movabsq	$4503599627370495, %rax
	andq	-8(%rbp), %rax
	leave
LCFI929:
	ret
LFE308:
.no_dead_strip _mod_pow2__mod_pow2_C_53
_mod_pow2__mod_pow2_C_53:
LFB309:
	pushq	%rbp
LCFI930:
	movq	%rsp, %rbp
LCFI931:
	movq	%rdi, -8(%rbp)
	movabsq	$9007199254740991, %rax
	andq	-8(%rbp), %rax
	leave
LCFI932:
	ret
LFE309:
.no_dead_strip _mod_pow2__mod_pow2_C_54
_mod_pow2__mod_pow2_C_54:
LFB310:
	pushq	%rbp
LCFI933:
	movq	%rsp, %rbp
LCFI934:
	movq	%rdi, -8(%rbp)
	movabsq	$18014398509481983, %rax
	andq	-8(%rbp), %rax
	leave
LCFI935:
	ret
LFE310:
.no_dead_strip _mod_pow2__mod_pow2_C_55
_mod_pow2__mod_pow2_C_55:
LFB311:
	pushq	%rbp
LCFI936:
	movq	%rsp, %rbp
LCFI937:
	movq	%rdi, -8(%rbp)
	movabsq	$36028797018963967, %rax
	andq	-8(%rbp), %rax
	leave
LCFI938:
	ret
LFE311:
.no_dead_strip _mod_pow2__mod_pow2_C_56
_mod_pow2__mod_pow2_C_56:
LFB312:
	pushq	%rbp
LCFI939:
	movq	%rsp, %rbp
LCFI940:
	movq	%rdi, -8(%rbp)
	movabsq	$72057594037927935, %rax
	andq	-8(%rbp), %rax
	leave
LCFI941:
	ret
LFE312:
.no_dead_strip _mod_pow2__mod_pow2_C_57
_mod_pow2__mod_pow2_C_57:
LFB313:
	pushq	%rbp
LCFI942:
	movq	%rsp, %rbp
LCFI943:
	movq	%rdi, -8(%rbp)
	movabsq	$144115188075855871, %rax
	andq	-8(%rbp), %rax
	leave
LCFI944:
	ret
LFE313:
.no_dead_strip _mod_pow2__mod_pow2_C_58
_mod_pow2__mod_pow2_C_58:
LFB314:
	pushq	%rbp
LCFI945:
	movq	%rsp, %rbp
LCFI946:
	movq	%rdi, -8(%rbp)
	movabsq	$288230376151711743, %rax
	andq	-8(%rbp), %rax
	leave
LCFI947:
	ret
LFE314:
.no_dead_strip _mod_pow2__mod_pow2_C_59
_mod_pow2__mod_pow2_C_59:
LFB315:
	pushq	%rbp
LCFI948:
	movq	%rsp, %rbp
LCFI949:
	movq	%rdi, -8(%rbp)
	movabsq	$576460752303423487, %rax
	andq	-8(%rbp), %rax
	leave
LCFI950:
	ret
LFE315:
.no_dead_strip _mod_pow2__mod_pow2_C_60
_mod_pow2__mod_pow2_C_60:
LFB316:
	pushq	%rbp
LCFI951:
	movq	%rsp, %rbp
LCFI952:
	movq	%rdi, -8(%rbp)
	movabsq	$1152921504606846975, %rax
	andq	-8(%rbp), %rax
	leave
LCFI953:
	ret
LFE316:
.no_dead_strip _mod_pow2__mod_pow2_C_61
_mod_pow2__mod_pow2_C_61:
LFB317:
	pushq	%rbp
LCFI954:
	movq	%rsp, %rbp
LCFI955:
	movq	%rdi, -8(%rbp)
	movabsq	$2305843009213693951, %rax
	andq	-8(%rbp), %rax
	leave
LCFI956:
	ret
LFE317:
.no_dead_strip _mod_pow2__mod_pow2_C_62
_mod_pow2__mod_pow2_C_62:
LFB318:
	pushq	%rbp
LCFI957:
	movq	%rsp, %rbp
LCFI958:
	movq	%rdi, -8(%rbp)
	movabsq	$4611686018427387903, %rax
	andq	-8(%rbp), %rax
	leave
LCFI959:
	ret
LFE318:
.no_dead_strip _mod_pow2__mod_pow2_C_63
_mod_pow2__mod_pow2_C_63:
LFB319:
	pushq	%rbp
LCFI960:
	movq	%rsp, %rbp
LCFI961:
	pushq	%rbx
LCFI962:
	subq	$24, %rsp
LCFI963:
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leaq	-1(%rax), %rdx
	movq	%rax, %rcx
	orq	%rdx, %rcx
	sarq	$63, %rcx
	movq	%rdx, %rbx
	subq	%rcx, %rbx
	movabsq	$-9223372036854775808, %rdx
	cmpq	%rdx, %rbx
	sete	%dl
	movzbl	%dl, %edx
	notq	%rcx
	addq	%rcx, %rdx
	salq	$63, %rdx
	movq	%rax, %rcx
	subq	%rdx, %rcx
	movq	%rcx, %rdx
	testq	%rdx, %rdx
	jns	L321
	movl	$22177, %edi
	call	__m3_fault
L321:
	movq	-24(%rbp), %rax
	leaq	-1(%rax), %rdx
	movq	%rax, %rcx
	orq	%rdx, %rcx
	sarq	$63, %rcx
	movq	%rdx, %rbx
	subq	%rcx, %rbx
	movabsq	$-9223372036854775808, %rdx
	cmpq	%rdx, %rbx
	sete	%dl
	movzbl	%dl, %edx
	notq	%rcx
	addq	%rcx, %rdx
	salq	$63, %rdx
	movq	%rax, %rcx
	subq	%rdx, %rcx
	movq	%rcx, %rdx
	movq	%rdx, %rax
	addq	$24, %rsp
	popq	%rbx
	leave
LCFI964:
	ret
LFE319:
.no_dead_strip _mod_pow2__mod_pow2_L_0
_mod_pow2__mod_pow2_L_0:
LFB320:
	pushq	%rbp
LCFI965:
	movq	%rsp, %rbp
LCFI966:
	movq	%rdi, -8(%rbp)
	movl	$0, %eax
	leave
LCFI967:
	ret
LFE320:
.no_dead_strip _mod_pow2__mod_pow2_L_1
_mod_pow2__mod_pow2_L_1:
LFB321:
	pushq	%rbp
LCFI968:
	movq	%rsp, %rbp
LCFI969:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1, %eax
	leave
LCFI970:
	ret
LFE321:
.no_dead_strip _mod_pow2__mod_pow2_L_2
_mod_pow2__mod_pow2_L_2:
LFB322:
	pushq	%rbp
LCFI971:
	movq	%rsp, %rbp
LCFI972:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$3, %eax
	leave
LCFI973:
	ret
LFE322:
.no_dead_strip _mod_pow2__mod_pow2_L_3
_mod_pow2__mod_pow2_L_3:
LFB323:
	pushq	%rbp
LCFI974:
	movq	%rsp, %rbp
LCFI975:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$7, %eax
	leave
LCFI976:
	ret
LFE323:
.no_dead_strip _mod_pow2__mod_pow2_L_4
_mod_pow2__mod_pow2_L_4:
LFB324:
	pushq	%rbp
LCFI977:
	movq	%rsp, %rbp
LCFI978:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$15, %eax
	leave
LCFI979:
	ret
LFE324:
.no_dead_strip _mod_pow2__mod_pow2_L_5
_mod_pow2__mod_pow2_L_5:
LFB325:
	pushq	%rbp
LCFI980:
	movq	%rsp, %rbp
LCFI981:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$31, %eax
	leave
LCFI982:
	ret
LFE325:
.no_dead_strip _mod_pow2__mod_pow2_L_6
_mod_pow2__mod_pow2_L_6:
LFB326:
	pushq	%rbp
LCFI983:
	movq	%rsp, %rbp
LCFI984:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$63, %eax
	leave
LCFI985:
	ret
LFE326:
.no_dead_strip _mod_pow2__mod_pow2_L_7
_mod_pow2__mod_pow2_L_7:
LFB327:
	pushq	%rbp
LCFI986:
	movq	%rsp, %rbp
LCFI987:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$127, %eax
	leave
LCFI988:
	ret
LFE327:
.no_dead_strip _mod_pow2__mod_pow2_L_8
_mod_pow2__mod_pow2_L_8:
LFB328:
	pushq	%rbp
LCFI989:
	movq	%rsp, %rbp
LCFI990:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$255, %eax
	leave
LCFI991:
	ret
LFE328:
.no_dead_strip _mod_pow2__mod_pow2_L_9
_mod_pow2__mod_pow2_L_9:
LFB329:
	pushq	%rbp
LCFI992:
	movq	%rsp, %rbp
LCFI993:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$511, %eax
	leave
LCFI994:
	ret
LFE329:
.no_dead_strip _mod_pow2__mod_pow2_L_10
_mod_pow2__mod_pow2_L_10:
LFB330:
	pushq	%rbp
LCFI995:
	movq	%rsp, %rbp
LCFI996:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1023, %eax
	leave
LCFI997:
	ret
LFE330:
.no_dead_strip _mod_pow2__mod_pow2_L_11
_mod_pow2__mod_pow2_L_11:
LFB331:
	pushq	%rbp
LCFI998:
	movq	%rsp, %rbp
LCFI999:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2047, %eax
	leave
LCFI1000:
	ret
LFE331:
.no_dead_strip _mod_pow2__mod_pow2_L_12
_mod_pow2__mod_pow2_L_12:
LFB332:
	pushq	%rbp
LCFI1001:
	movq	%rsp, %rbp
LCFI1002:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4095, %eax
	leave
LCFI1003:
	ret
LFE332:
.no_dead_strip _mod_pow2__mod_pow2_L_13
_mod_pow2__mod_pow2_L_13:
LFB333:
	pushq	%rbp
LCFI1004:
	movq	%rsp, %rbp
LCFI1005:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$8191, %eax
	leave
LCFI1006:
	ret
LFE333:
.no_dead_strip _mod_pow2__mod_pow2_L_14
_mod_pow2__mod_pow2_L_14:
LFB334:
	pushq	%rbp
LCFI1007:
	movq	%rsp, %rbp
LCFI1008:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$16383, %eax
	leave
LCFI1009:
	ret
LFE334:
.no_dead_strip _mod_pow2__mod_pow2_L_15
_mod_pow2__mod_pow2_L_15:
LFB335:
	pushq	%rbp
LCFI1010:
	movq	%rsp, %rbp
LCFI1011:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$32767, %eax
	leave
LCFI1012:
	ret
LFE335:
.no_dead_strip _mod_pow2__mod_pow2_L_16
_mod_pow2__mod_pow2_L_16:
LFB336:
	pushq	%rbp
LCFI1013:
	movq	%rsp, %rbp
LCFI1014:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$65535, %eax
	leave
LCFI1015:
	ret
LFE336:
.no_dead_strip _mod_pow2__mod_pow2_L_17
_mod_pow2__mod_pow2_L_17:
LFB337:
	pushq	%rbp
LCFI1016:
	movq	%rsp, %rbp
LCFI1017:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$131071, %eax
	leave
LCFI1018:
	ret
LFE337:
.no_dead_strip _mod_pow2__mod_pow2_L_18
_mod_pow2__mod_pow2_L_18:
LFB338:
	pushq	%rbp
LCFI1019:
	movq	%rsp, %rbp
LCFI1020:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$262143, %eax
	leave
LCFI1021:
	ret
LFE338:
.no_dead_strip _mod_pow2__mod_pow2_L_19
_mod_pow2__mod_pow2_L_19:
LFB339:
	pushq	%rbp
LCFI1022:
	movq	%rsp, %rbp
LCFI1023:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$524287, %eax
	leave
LCFI1024:
	ret
LFE339:
.no_dead_strip _mod_pow2__mod_pow2_L_20
_mod_pow2__mod_pow2_L_20:
LFB340:
	pushq	%rbp
LCFI1025:
	movq	%rsp, %rbp
LCFI1026:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1048575, %eax
	leave
LCFI1027:
	ret
LFE340:
.no_dead_strip _mod_pow2__mod_pow2_L_21
_mod_pow2__mod_pow2_L_21:
LFB341:
	pushq	%rbp
LCFI1028:
	movq	%rsp, %rbp
LCFI1029:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2097151, %eax
	leave
LCFI1030:
	ret
LFE341:
.no_dead_strip _mod_pow2__mod_pow2_L_22
_mod_pow2__mod_pow2_L_22:
LFB342:
	pushq	%rbp
LCFI1031:
	movq	%rsp, %rbp
LCFI1032:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4194303, %eax
	leave
LCFI1033:
	ret
LFE342:
.no_dead_strip _mod_pow2__mod_pow2_L_23
_mod_pow2__mod_pow2_L_23:
LFB343:
	pushq	%rbp
LCFI1034:
	movq	%rsp, %rbp
LCFI1035:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$8388607, %eax
	leave
LCFI1036:
	ret
LFE343:
.no_dead_strip _mod_pow2__mod_pow2_L_24
_mod_pow2__mod_pow2_L_24:
LFB344:
	pushq	%rbp
LCFI1037:
	movq	%rsp, %rbp
LCFI1038:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$16777215, %eax
	leave
LCFI1039:
	ret
LFE344:
.no_dead_strip _mod_pow2__mod_pow2_L_25
_mod_pow2__mod_pow2_L_25:
LFB345:
	pushq	%rbp
LCFI1040:
	movq	%rsp, %rbp
LCFI1041:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$33554431, %eax
	leave
LCFI1042:
	ret
LFE345:
.no_dead_strip _mod_pow2__mod_pow2_L_26
_mod_pow2__mod_pow2_L_26:
LFB346:
	pushq	%rbp
LCFI1043:
	movq	%rsp, %rbp
LCFI1044:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$67108863, %eax
	leave
LCFI1045:
	ret
LFE346:
.no_dead_strip _mod_pow2__mod_pow2_L_27
_mod_pow2__mod_pow2_L_27:
LFB347:
	pushq	%rbp
LCFI1046:
	movq	%rsp, %rbp
LCFI1047:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$134217727, %eax
	leave
LCFI1048:
	ret
LFE347:
.no_dead_strip _mod_pow2__mod_pow2_L_28
_mod_pow2__mod_pow2_L_28:
LFB348:
	pushq	%rbp
LCFI1049:
	movq	%rsp, %rbp
LCFI1050:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$268435455, %eax
	leave
LCFI1051:
	ret
LFE348:
.no_dead_strip _mod_pow2__mod_pow2_L_29
_mod_pow2__mod_pow2_L_29:
LFB349:
	pushq	%rbp
LCFI1052:
	movq	%rsp, %rbp
LCFI1053:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$536870911, %eax
	leave
LCFI1054:
	ret
LFE349:
.no_dead_strip _mod_pow2__mod_pow2_L_30
_mod_pow2__mod_pow2_L_30:
LFB350:
	pushq	%rbp
LCFI1055:
	movq	%rsp, %rbp
LCFI1056:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1073741823, %eax
	leave
LCFI1057:
	ret
LFE350:
.no_dead_strip _mod_pow2__mod_pow2_L_31
_mod_pow2__mod_pow2_L_31:
LFB351:
	pushq	%rbp
LCFI1058:
	movq	%rsp, %rbp
LCFI1059:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2147483647, %eax
	leave
LCFI1060:
	ret
LFE351:
.no_dead_strip _mod_pow2__mod_pow2_L_32
_mod_pow2__mod_pow2_L_32:
LFB352:
	pushq	%rbp
LCFI1061:
	movq	%rsp, %rbp
LCFI1062:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4294967295, %eax
	leave
LCFI1063:
	ret
LFE352:
.no_dead_strip _mod_pow2__mod_pow2_L_33
_mod_pow2__mod_pow2_L_33:
LFB353:
	pushq	%rbp
LCFI1064:
	movq	%rsp, %rbp
LCFI1065:
	movq	%rdi, -8(%rbp)
	movabsq	$8589934591, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1066:
	ret
LFE353:
.no_dead_strip _mod_pow2__mod_pow2_L_34
_mod_pow2__mod_pow2_L_34:
LFB354:
	pushq	%rbp
LCFI1067:
	movq	%rsp, %rbp
LCFI1068:
	movq	%rdi, -8(%rbp)
	movabsq	$17179869183, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1069:
	ret
LFE354:
.no_dead_strip _mod_pow2__mod_pow2_L_35
_mod_pow2__mod_pow2_L_35:
LFB355:
	pushq	%rbp
LCFI1070:
	movq	%rsp, %rbp
LCFI1071:
	movq	%rdi, -8(%rbp)
	movabsq	$34359738367, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1072:
	ret
LFE355:
.no_dead_strip _mod_pow2__mod_pow2_L_36
_mod_pow2__mod_pow2_L_36:
LFB356:
	pushq	%rbp
LCFI1073:
	movq	%rsp, %rbp
LCFI1074:
	movq	%rdi, -8(%rbp)
	movabsq	$68719476735, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1075:
	ret
LFE356:
.no_dead_strip _mod_pow2__mod_pow2_L_37
_mod_pow2__mod_pow2_L_37:
LFB357:
	pushq	%rbp
LCFI1076:
	movq	%rsp, %rbp
LCFI1077:
	movq	%rdi, -8(%rbp)
	movabsq	$137438953471, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1078:
	ret
LFE357:
.no_dead_strip _mod_pow2__mod_pow2_L_38
_mod_pow2__mod_pow2_L_38:
LFB358:
	pushq	%rbp
LCFI1079:
	movq	%rsp, %rbp
LCFI1080:
	movq	%rdi, -8(%rbp)
	movabsq	$274877906943, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1081:
	ret
LFE358:
.no_dead_strip _mod_pow2__mod_pow2_L_39
_mod_pow2__mod_pow2_L_39:
LFB359:
	pushq	%rbp
LCFI1082:
	movq	%rsp, %rbp
LCFI1083:
	movq	%rdi, -8(%rbp)
	movabsq	$549755813887, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1084:
	ret
LFE359:
.no_dead_strip _mod_pow2__mod_pow2_L_40
_mod_pow2__mod_pow2_L_40:
LFB360:
	pushq	%rbp
LCFI1085:
	movq	%rsp, %rbp
LCFI1086:
	movq	%rdi, -8(%rbp)
	movabsq	$1099511627775, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1087:
	ret
LFE360:
.no_dead_strip _mod_pow2__mod_pow2_L_41
_mod_pow2__mod_pow2_L_41:
LFB361:
	pushq	%rbp
LCFI1088:
	movq	%rsp, %rbp
LCFI1089:
	movq	%rdi, -8(%rbp)
	movabsq	$2199023255551, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1090:
	ret
LFE361:
.no_dead_strip _mod_pow2__mod_pow2_L_42
_mod_pow2__mod_pow2_L_42:
LFB362:
	pushq	%rbp
LCFI1091:
	movq	%rsp, %rbp
LCFI1092:
	movq	%rdi, -8(%rbp)
	movabsq	$4398046511103, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1093:
	ret
LFE362:
.no_dead_strip _mod_pow2__mod_pow2_L_43
_mod_pow2__mod_pow2_L_43:
LFB363:
	pushq	%rbp
LCFI1094:
	movq	%rsp, %rbp
LCFI1095:
	movq	%rdi, -8(%rbp)
	movabsq	$8796093022207, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1096:
	ret
LFE363:
.no_dead_strip _mod_pow2__mod_pow2_L_44
_mod_pow2__mod_pow2_L_44:
LFB364:
	pushq	%rbp
LCFI1097:
	movq	%rsp, %rbp
LCFI1098:
	movq	%rdi, -8(%rbp)
	movabsq	$17592186044415, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1099:
	ret
LFE364:
.no_dead_strip _mod_pow2__mod_pow2_L_45
_mod_pow2__mod_pow2_L_45:
LFB365:
	pushq	%rbp
LCFI1100:
	movq	%rsp, %rbp
LCFI1101:
	movq	%rdi, -8(%rbp)
	movabsq	$35184372088831, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1102:
	ret
LFE365:
.no_dead_strip _mod_pow2__mod_pow2_L_46
_mod_pow2__mod_pow2_L_46:
LFB366:
	pushq	%rbp
LCFI1103:
	movq	%rsp, %rbp
LCFI1104:
	movq	%rdi, -8(%rbp)
	movabsq	$70368744177663, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1105:
	ret
LFE366:
.no_dead_strip _mod_pow2__mod_pow2_L_47
_mod_pow2__mod_pow2_L_47:
LFB367:
	pushq	%rbp
LCFI1106:
	movq	%rsp, %rbp
LCFI1107:
	movq	%rdi, -8(%rbp)
	movabsq	$140737488355327, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1108:
	ret
LFE367:
.no_dead_strip _mod_pow2__mod_pow2_L_48
_mod_pow2__mod_pow2_L_48:
LFB368:
	pushq	%rbp
LCFI1109:
	movq	%rsp, %rbp
LCFI1110:
	movq	%rdi, -8(%rbp)
	movabsq	$281474976710655, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1111:
	ret
LFE368:
.no_dead_strip _mod_pow2__mod_pow2_L_49
_mod_pow2__mod_pow2_L_49:
LFB369:
	pushq	%rbp
LCFI1112:
	movq	%rsp, %rbp
LCFI1113:
	movq	%rdi, -8(%rbp)
	movabsq	$562949953421311, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1114:
	ret
LFE369:
.no_dead_strip _mod_pow2__mod_pow2_L_50
_mod_pow2__mod_pow2_L_50:
LFB370:
	pushq	%rbp
LCFI1115:
	movq	%rsp, %rbp
LCFI1116:
	movq	%rdi, -8(%rbp)
	movabsq	$1125899906842623, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1117:
	ret
LFE370:
.no_dead_strip _mod_pow2__mod_pow2_L_51
_mod_pow2__mod_pow2_L_51:
LFB371:
	pushq	%rbp
LCFI1118:
	movq	%rsp, %rbp
LCFI1119:
	movq	%rdi, -8(%rbp)
	movabsq	$2251799813685247, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1120:
	ret
LFE371:
.no_dead_strip _mod_pow2__mod_pow2_L_52
_mod_pow2__mod_pow2_L_52:
LFB372:
	pushq	%rbp
LCFI1121:
	movq	%rsp, %rbp
LCFI1122:
	movq	%rdi, -8(%rbp)
	movabsq	$4503599627370495, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1123:
	ret
LFE372:
.no_dead_strip _mod_pow2__mod_pow2_L_53
_mod_pow2__mod_pow2_L_53:
LFB373:
	pushq	%rbp
LCFI1124:
	movq	%rsp, %rbp
LCFI1125:
	movq	%rdi, -8(%rbp)
	movabsq	$9007199254740991, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1126:
	ret
LFE373:
.no_dead_strip _mod_pow2__mod_pow2_L_54
_mod_pow2__mod_pow2_L_54:
LFB374:
	pushq	%rbp
LCFI1127:
	movq	%rsp, %rbp
LCFI1128:
	movq	%rdi, -8(%rbp)
	movabsq	$18014398509481983, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1129:
	ret
LFE374:
.no_dead_strip _mod_pow2__mod_pow2_L_55
_mod_pow2__mod_pow2_L_55:
LFB375:
	pushq	%rbp
LCFI1130:
	movq	%rsp, %rbp
LCFI1131:
	movq	%rdi, -8(%rbp)
	movabsq	$36028797018963967, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1132:
	ret
LFE375:
.no_dead_strip _mod_pow2__mod_pow2_L_56
_mod_pow2__mod_pow2_L_56:
LFB376:
	pushq	%rbp
LCFI1133:
	movq	%rsp, %rbp
LCFI1134:
	movq	%rdi, -8(%rbp)
	movabsq	$72057594037927935, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1135:
	ret
LFE376:
.no_dead_strip _mod_pow2__mod_pow2_L_57
_mod_pow2__mod_pow2_L_57:
LFB377:
	pushq	%rbp
LCFI1136:
	movq	%rsp, %rbp
LCFI1137:
	movq	%rdi, -8(%rbp)
	movabsq	$144115188075855871, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1138:
	ret
LFE377:
.no_dead_strip _mod_pow2__mod_pow2_L_58
_mod_pow2__mod_pow2_L_58:
LFB378:
	pushq	%rbp
LCFI1139:
	movq	%rsp, %rbp
LCFI1140:
	movq	%rdi, -8(%rbp)
	movabsq	$288230376151711743, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1141:
	ret
LFE378:
.no_dead_strip _mod_pow2__mod_pow2_L_59
_mod_pow2__mod_pow2_L_59:
LFB379:
	pushq	%rbp
LCFI1142:
	movq	%rsp, %rbp
LCFI1143:
	movq	%rdi, -8(%rbp)
	movabsq	$576460752303423487, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1144:
	ret
LFE379:
.no_dead_strip _mod_pow2__mod_pow2_L_60
_mod_pow2__mod_pow2_L_60:
LFB380:
	pushq	%rbp
LCFI1145:
	movq	%rsp, %rbp
LCFI1146:
	movq	%rdi, -8(%rbp)
	movabsq	$1152921504606846975, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1147:
	ret
LFE380:
.no_dead_strip _mod_pow2__mod_pow2_L_61
_mod_pow2__mod_pow2_L_61:
LFB381:
	pushq	%rbp
LCFI1148:
	movq	%rsp, %rbp
LCFI1149:
	movq	%rdi, -8(%rbp)
	movabsq	$2305843009213693951, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1150:
	ret
LFE381:
.no_dead_strip _mod_pow2__mod_pow2_L_62
_mod_pow2__mod_pow2_L_62:
LFB382:
	pushq	%rbp
LCFI1151:
	movq	%rsp, %rbp
LCFI1152:
	movq	%rdi, -8(%rbp)
	movabsq	$4611686018427387903, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1153:
	ret
LFE382:
.no_dead_strip _mod_pow2__mod_pow2_L_63
_mod_pow2__mod_pow2_L_63:
LFB383:
	pushq	%rbp
LCFI1154:
	movq	%rsp, %rbp
LCFI1155:
	pushq	%rbx
LCFI1156:
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leaq	-1(%rax), %rdx
	movq	%rax, %rcx
	orq	%rdx, %rcx
	sarq	$63, %rcx
	movq	%rdx, %rbx
	subq	%rcx, %rbx
	movabsq	$-9223372036854775808, %rdx
	cmpq	%rdx, %rbx
	sete	%dl
	movzbl	%dl, %edx
	notq	%rcx
	addq	%rcx, %rdx
	salq	$63, %rdx
	movq	%rax, %rcx
	subq	%rdx, %rcx
	movq	%rcx, %rdx
	movq	%rdx, %rax
	popq	%rbx
	leave
LCFI1157:
	ret
LFE383:
.no_dead_strip _mod_pow2__mod_pow2_LC_0
_mod_pow2__mod_pow2_LC_0:
LFB384:
	pushq	%rbp
LCFI1158:
	movq	%rsp, %rbp
LCFI1159:
	movq	%rdi, -8(%rbp)
	movl	$0, %eax
	leave
LCFI1160:
	ret
LFE384:
.no_dead_strip _mod_pow2__mod_pow2_LC_1
_mod_pow2__mod_pow2_LC_1:
LFB385:
	pushq	%rbp
LCFI1161:
	movq	%rsp, %rbp
LCFI1162:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1, %eax
	leave
LCFI1163:
	ret
LFE385:
.no_dead_strip _mod_pow2__mod_pow2_LC_2
_mod_pow2__mod_pow2_LC_2:
LFB386:
	pushq	%rbp
LCFI1164:
	movq	%rsp, %rbp
LCFI1165:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$3, %eax
	leave
LCFI1166:
	ret
LFE386:
.no_dead_strip _mod_pow2__mod_pow2_LC_3
_mod_pow2__mod_pow2_LC_3:
LFB387:
	pushq	%rbp
LCFI1167:
	movq	%rsp, %rbp
LCFI1168:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$7, %eax
	leave
LCFI1169:
	ret
LFE387:
.no_dead_strip _mod_pow2__mod_pow2_LC_4
_mod_pow2__mod_pow2_LC_4:
LFB388:
	pushq	%rbp
LCFI1170:
	movq	%rsp, %rbp
LCFI1171:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$15, %eax
	leave
LCFI1172:
	ret
LFE388:
.no_dead_strip _mod_pow2__mod_pow2_LC_5
_mod_pow2__mod_pow2_LC_5:
LFB389:
	pushq	%rbp
LCFI1173:
	movq	%rsp, %rbp
LCFI1174:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$31, %eax
	leave
LCFI1175:
	ret
LFE389:
.no_dead_strip _mod_pow2__mod_pow2_LC_6
_mod_pow2__mod_pow2_LC_6:
LFB390:
	pushq	%rbp
LCFI1176:
	movq	%rsp, %rbp
LCFI1177:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$63, %eax
	leave
LCFI1178:
	ret
LFE390:
.no_dead_strip _mod_pow2__mod_pow2_LC_7
_mod_pow2__mod_pow2_LC_7:
LFB391:
	pushq	%rbp
LCFI1179:
	movq	%rsp, %rbp
LCFI1180:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$127, %eax
	leave
LCFI1181:
	ret
LFE391:
.no_dead_strip _mod_pow2__mod_pow2_LC_8
_mod_pow2__mod_pow2_LC_8:
LFB392:
	pushq	%rbp
LCFI1182:
	movq	%rsp, %rbp
LCFI1183:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$255, %eax
	leave
LCFI1184:
	ret
LFE392:
.no_dead_strip _mod_pow2__mod_pow2_LC_9
_mod_pow2__mod_pow2_LC_9:
LFB393:
	pushq	%rbp
LCFI1185:
	movq	%rsp, %rbp
LCFI1186:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$511, %eax
	leave
LCFI1187:
	ret
LFE393:
.no_dead_strip _mod_pow2__mod_pow2_LC_10
_mod_pow2__mod_pow2_LC_10:
LFB394:
	pushq	%rbp
LCFI1188:
	movq	%rsp, %rbp
LCFI1189:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1023, %eax
	leave
LCFI1190:
	ret
LFE394:
.no_dead_strip _mod_pow2__mod_pow2_LC_11
_mod_pow2__mod_pow2_LC_11:
LFB395:
	pushq	%rbp
LCFI1191:
	movq	%rsp, %rbp
LCFI1192:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2047, %eax
	leave
LCFI1193:
	ret
LFE395:
.no_dead_strip _mod_pow2__mod_pow2_LC_12
_mod_pow2__mod_pow2_LC_12:
LFB396:
	pushq	%rbp
LCFI1194:
	movq	%rsp, %rbp
LCFI1195:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4095, %eax
	leave
LCFI1196:
	ret
LFE396:
.no_dead_strip _mod_pow2__mod_pow2_LC_13
_mod_pow2__mod_pow2_LC_13:
LFB397:
	pushq	%rbp
LCFI1197:
	movq	%rsp, %rbp
LCFI1198:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$8191, %eax
	leave
LCFI1199:
	ret
LFE397:
.no_dead_strip _mod_pow2__mod_pow2_LC_14
_mod_pow2__mod_pow2_LC_14:
LFB398:
	pushq	%rbp
LCFI1200:
	movq	%rsp, %rbp
LCFI1201:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$16383, %eax
	leave
LCFI1202:
	ret
LFE398:
.no_dead_strip _mod_pow2__mod_pow2_LC_15
_mod_pow2__mod_pow2_LC_15:
LFB399:
	pushq	%rbp
LCFI1203:
	movq	%rsp, %rbp
LCFI1204:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$32767, %eax
	leave
LCFI1205:
	ret
LFE399:
.no_dead_strip _mod_pow2__mod_pow2_LC_16
_mod_pow2__mod_pow2_LC_16:
LFB400:
	pushq	%rbp
LCFI1206:
	movq	%rsp, %rbp
LCFI1207:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$65535, %eax
	leave
LCFI1208:
	ret
LFE400:
.no_dead_strip _mod_pow2__mod_pow2_LC_17
_mod_pow2__mod_pow2_LC_17:
LFB401:
	pushq	%rbp
LCFI1209:
	movq	%rsp, %rbp
LCFI1210:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$131071, %eax
	leave
LCFI1211:
	ret
LFE401:
.no_dead_strip _mod_pow2__mod_pow2_LC_18
_mod_pow2__mod_pow2_LC_18:
LFB402:
	pushq	%rbp
LCFI1212:
	movq	%rsp, %rbp
LCFI1213:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$262143, %eax
	leave
LCFI1214:
	ret
LFE402:
.no_dead_strip _mod_pow2__mod_pow2_LC_19
_mod_pow2__mod_pow2_LC_19:
LFB403:
	pushq	%rbp
LCFI1215:
	movq	%rsp, %rbp
LCFI1216:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$524287, %eax
	leave
LCFI1217:
	ret
LFE403:
.no_dead_strip _mod_pow2__mod_pow2_LC_20
_mod_pow2__mod_pow2_LC_20:
LFB404:
	pushq	%rbp
LCFI1218:
	movq	%rsp, %rbp
LCFI1219:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1048575, %eax
	leave
LCFI1220:
	ret
LFE404:
.no_dead_strip _mod_pow2__mod_pow2_LC_21
_mod_pow2__mod_pow2_LC_21:
LFB405:
	pushq	%rbp
LCFI1221:
	movq	%rsp, %rbp
LCFI1222:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2097151, %eax
	leave
LCFI1223:
	ret
LFE405:
.no_dead_strip _mod_pow2__mod_pow2_LC_22
_mod_pow2__mod_pow2_LC_22:
LFB406:
	pushq	%rbp
LCFI1224:
	movq	%rsp, %rbp
LCFI1225:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4194303, %eax
	leave
LCFI1226:
	ret
LFE406:
.no_dead_strip _mod_pow2__mod_pow2_LC_23
_mod_pow2__mod_pow2_LC_23:
LFB407:
	pushq	%rbp
LCFI1227:
	movq	%rsp, %rbp
LCFI1228:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$8388607, %eax
	leave
LCFI1229:
	ret
LFE407:
.no_dead_strip _mod_pow2__mod_pow2_LC_24
_mod_pow2__mod_pow2_LC_24:
LFB408:
	pushq	%rbp
LCFI1230:
	movq	%rsp, %rbp
LCFI1231:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$16777215, %eax
	leave
LCFI1232:
	ret
LFE408:
.no_dead_strip _mod_pow2__mod_pow2_LC_25
_mod_pow2__mod_pow2_LC_25:
LFB409:
	pushq	%rbp
LCFI1233:
	movq	%rsp, %rbp
LCFI1234:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$33554431, %eax
	leave
LCFI1235:
	ret
LFE409:
.no_dead_strip _mod_pow2__mod_pow2_LC_26
_mod_pow2__mod_pow2_LC_26:
LFB410:
	pushq	%rbp
LCFI1236:
	movq	%rsp, %rbp
LCFI1237:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$67108863, %eax
	leave
LCFI1238:
	ret
LFE410:
.no_dead_strip _mod_pow2__mod_pow2_LC_27
_mod_pow2__mod_pow2_LC_27:
LFB411:
	pushq	%rbp
LCFI1239:
	movq	%rsp, %rbp
LCFI1240:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$134217727, %eax
	leave
LCFI1241:
	ret
LFE411:
.no_dead_strip _mod_pow2__mod_pow2_LC_28
_mod_pow2__mod_pow2_LC_28:
LFB412:
	pushq	%rbp
LCFI1242:
	movq	%rsp, %rbp
LCFI1243:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$268435455, %eax
	leave
LCFI1244:
	ret
LFE412:
.no_dead_strip _mod_pow2__mod_pow2_LC_29
_mod_pow2__mod_pow2_LC_29:
LFB413:
	pushq	%rbp
LCFI1245:
	movq	%rsp, %rbp
LCFI1246:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$536870911, %eax
	leave
LCFI1247:
	ret
LFE413:
.no_dead_strip _mod_pow2__mod_pow2_LC_30
_mod_pow2__mod_pow2_LC_30:
LFB414:
	pushq	%rbp
LCFI1248:
	movq	%rsp, %rbp
LCFI1249:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$1073741823, %eax
	leave
LCFI1250:
	ret
LFE414:
.no_dead_strip _mod_pow2__mod_pow2_LC_31
_mod_pow2__mod_pow2_LC_31:
LFB415:
	pushq	%rbp
LCFI1251:
	movq	%rsp, %rbp
LCFI1252:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$2147483647, %eax
	leave
LCFI1253:
	ret
LFE415:
.no_dead_strip _mod_pow2__mod_pow2_LC_32
_mod_pow2__mod_pow2_LC_32:
LFB416:
	pushq	%rbp
LCFI1254:
	movq	%rsp, %rbp
LCFI1255:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	andl	$4294967295, %eax
	leave
LCFI1256:
	ret
LFE416:
.no_dead_strip _mod_pow2__mod_pow2_LC_33
_mod_pow2__mod_pow2_LC_33:
LFB417:
	pushq	%rbp
LCFI1257:
	movq	%rsp, %rbp
LCFI1258:
	movq	%rdi, -8(%rbp)
	movabsq	$8589934591, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1259:
	ret
LFE417:
.no_dead_strip _mod_pow2__mod_pow2_LC_34
_mod_pow2__mod_pow2_LC_34:
LFB418:
	pushq	%rbp
LCFI1260:
	movq	%rsp, %rbp
LCFI1261:
	movq	%rdi, -8(%rbp)
	movabsq	$17179869183, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1262:
	ret
LFE418:
.no_dead_strip _mod_pow2__mod_pow2_LC_35
_mod_pow2__mod_pow2_LC_35:
LFB419:
	pushq	%rbp
LCFI1263:
	movq	%rsp, %rbp
LCFI1264:
	movq	%rdi, -8(%rbp)
	movabsq	$34359738367, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1265:
	ret
LFE419:
.no_dead_strip _mod_pow2__mod_pow2_LC_36
_mod_pow2__mod_pow2_LC_36:
LFB420:
	pushq	%rbp
LCFI1266:
	movq	%rsp, %rbp
LCFI1267:
	movq	%rdi, -8(%rbp)
	movabsq	$68719476735, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1268:
	ret
LFE420:
.no_dead_strip _mod_pow2__mod_pow2_LC_37
_mod_pow2__mod_pow2_LC_37:
LFB421:
	pushq	%rbp
LCFI1269:
	movq	%rsp, %rbp
LCFI1270:
	movq	%rdi, -8(%rbp)
	movabsq	$137438953471, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1271:
	ret
LFE421:
.no_dead_strip _mod_pow2__mod_pow2_LC_38
_mod_pow2__mod_pow2_LC_38:
LFB422:
	pushq	%rbp
LCFI1272:
	movq	%rsp, %rbp
LCFI1273:
	movq	%rdi, -8(%rbp)
	movabsq	$274877906943, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1274:
	ret
LFE422:
.no_dead_strip _mod_pow2__mod_pow2_LC_39
_mod_pow2__mod_pow2_LC_39:
LFB423:
	pushq	%rbp
LCFI1275:
	movq	%rsp, %rbp
LCFI1276:
	movq	%rdi, -8(%rbp)
	movabsq	$549755813887, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1277:
	ret
LFE423:
.no_dead_strip _mod_pow2__mod_pow2_LC_40
_mod_pow2__mod_pow2_LC_40:
LFB424:
	pushq	%rbp
LCFI1278:
	movq	%rsp, %rbp
LCFI1279:
	movq	%rdi, -8(%rbp)
	movabsq	$1099511627775, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1280:
	ret
LFE424:
.no_dead_strip _mod_pow2__mod_pow2_LC_41
_mod_pow2__mod_pow2_LC_41:
LFB425:
	pushq	%rbp
LCFI1281:
	movq	%rsp, %rbp
LCFI1282:
	movq	%rdi, -8(%rbp)
	movabsq	$2199023255551, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1283:
	ret
LFE425:
.no_dead_strip _mod_pow2__mod_pow2_LC_42
_mod_pow2__mod_pow2_LC_42:
LFB426:
	pushq	%rbp
LCFI1284:
	movq	%rsp, %rbp
LCFI1285:
	movq	%rdi, -8(%rbp)
	movabsq	$4398046511103, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1286:
	ret
LFE426:
.no_dead_strip _mod_pow2__mod_pow2_LC_43
_mod_pow2__mod_pow2_LC_43:
LFB427:
	pushq	%rbp
LCFI1287:
	movq	%rsp, %rbp
LCFI1288:
	movq	%rdi, -8(%rbp)
	movabsq	$8796093022207, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1289:
	ret
LFE427:
.no_dead_strip _mod_pow2__mod_pow2_LC_44
_mod_pow2__mod_pow2_LC_44:
LFB428:
	pushq	%rbp
LCFI1290:
	movq	%rsp, %rbp
LCFI1291:
	movq	%rdi, -8(%rbp)
	movabsq	$17592186044415, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1292:
	ret
LFE428:
.no_dead_strip _mod_pow2__mod_pow2_LC_45
_mod_pow2__mod_pow2_LC_45:
LFB429:
	pushq	%rbp
LCFI1293:
	movq	%rsp, %rbp
LCFI1294:
	movq	%rdi, -8(%rbp)
	movabsq	$35184372088831, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1295:
	ret
LFE429:
.no_dead_strip _mod_pow2__mod_pow2_LC_46
_mod_pow2__mod_pow2_LC_46:
LFB430:
	pushq	%rbp
LCFI1296:
	movq	%rsp, %rbp
LCFI1297:
	movq	%rdi, -8(%rbp)
	movabsq	$70368744177663, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1298:
	ret
LFE430:
.no_dead_strip _mod_pow2__mod_pow2_LC_47
_mod_pow2__mod_pow2_LC_47:
LFB431:
	pushq	%rbp
LCFI1299:
	movq	%rsp, %rbp
LCFI1300:
	movq	%rdi, -8(%rbp)
	movabsq	$140737488355327, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1301:
	ret
LFE431:
.no_dead_strip _mod_pow2__mod_pow2_LC_48
_mod_pow2__mod_pow2_LC_48:
LFB432:
	pushq	%rbp
LCFI1302:
	movq	%rsp, %rbp
LCFI1303:
	movq	%rdi, -8(%rbp)
	movabsq	$281474976710655, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1304:
	ret
LFE432:
.no_dead_strip _mod_pow2__mod_pow2_LC_49
_mod_pow2__mod_pow2_LC_49:
LFB433:
	pushq	%rbp
LCFI1305:
	movq	%rsp, %rbp
LCFI1306:
	movq	%rdi, -8(%rbp)
	movabsq	$562949953421311, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1307:
	ret
LFE433:
.no_dead_strip _mod_pow2__mod_pow2_LC_50
_mod_pow2__mod_pow2_LC_50:
LFB434:
	pushq	%rbp
LCFI1308:
	movq	%rsp, %rbp
LCFI1309:
	movq	%rdi, -8(%rbp)
	movabsq	$1125899906842623, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1310:
	ret
LFE434:
.no_dead_strip _mod_pow2__mod_pow2_LC_51
_mod_pow2__mod_pow2_LC_51:
LFB435:
	pushq	%rbp
LCFI1311:
	movq	%rsp, %rbp
LCFI1312:
	movq	%rdi, -8(%rbp)
	movabsq	$2251799813685247, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1313:
	ret
LFE435:
.no_dead_strip _mod_pow2__mod_pow2_LC_52
_mod_pow2__mod_pow2_LC_52:
LFB436:
	pushq	%rbp
LCFI1314:
	movq	%rsp, %rbp
LCFI1315:
	movq	%rdi, -8(%rbp)
	movabsq	$4503599627370495, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1316:
	ret
LFE436:
.no_dead_strip _mod_pow2__mod_pow2_LC_53
_mod_pow2__mod_pow2_LC_53:
LFB437:
	pushq	%rbp
LCFI1317:
	movq	%rsp, %rbp
LCFI1318:
	movq	%rdi, -8(%rbp)
	movabsq	$9007199254740991, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1319:
	ret
LFE437:
.no_dead_strip _mod_pow2__mod_pow2_LC_54
_mod_pow2__mod_pow2_LC_54:
LFB438:
	pushq	%rbp
LCFI1320:
	movq	%rsp, %rbp
LCFI1321:
	movq	%rdi, -8(%rbp)
	movabsq	$18014398509481983, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1322:
	ret
LFE438:
.no_dead_strip _mod_pow2__mod_pow2_LC_55
_mod_pow2__mod_pow2_LC_55:
LFB439:
	pushq	%rbp
LCFI1323:
	movq	%rsp, %rbp
LCFI1324:
	movq	%rdi, -8(%rbp)
	movabsq	$36028797018963967, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1325:
	ret
LFE439:
.no_dead_strip _mod_pow2__mod_pow2_LC_56
_mod_pow2__mod_pow2_LC_56:
LFB440:
	pushq	%rbp
LCFI1326:
	movq	%rsp, %rbp
LCFI1327:
	movq	%rdi, -8(%rbp)
	movabsq	$72057594037927935, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1328:
	ret
LFE440:
.no_dead_strip _mod_pow2__mod_pow2_LC_57
_mod_pow2__mod_pow2_LC_57:
LFB441:
	pushq	%rbp
LCFI1329:
	movq	%rsp, %rbp
LCFI1330:
	movq	%rdi, -8(%rbp)
	movabsq	$144115188075855871, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1331:
	ret
LFE441:
.no_dead_strip _mod_pow2__mod_pow2_LC_58
_mod_pow2__mod_pow2_LC_58:
LFB442:
	pushq	%rbp
LCFI1332:
	movq	%rsp, %rbp
LCFI1333:
	movq	%rdi, -8(%rbp)
	movabsq	$288230376151711743, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1334:
	ret
LFE442:
.no_dead_strip _mod_pow2__mod_pow2_LC_59
_mod_pow2__mod_pow2_LC_59:
LFB443:
	pushq	%rbp
LCFI1335:
	movq	%rsp, %rbp
LCFI1336:
	movq	%rdi, -8(%rbp)
	movabsq	$576460752303423487, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1337:
	ret
LFE443:
.no_dead_strip _mod_pow2__mod_pow2_LC_60
_mod_pow2__mod_pow2_LC_60:
LFB444:
	pushq	%rbp
LCFI1338:
	movq	%rsp, %rbp
LCFI1339:
	movq	%rdi, -8(%rbp)
	movabsq	$1152921504606846975, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1340:
	ret
LFE444:
.no_dead_strip _mod_pow2__mod_pow2_LC_61
_mod_pow2__mod_pow2_LC_61:
LFB445:
	pushq	%rbp
LCFI1341:
	movq	%rsp, %rbp
LCFI1342:
	movq	%rdi, -8(%rbp)
	movabsq	$2305843009213693951, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1343:
	ret
LFE445:
.no_dead_strip _mod_pow2__mod_pow2_LC_62
_mod_pow2__mod_pow2_LC_62:
LFB446:
	pushq	%rbp
LCFI1344:
	movq	%rsp, %rbp
LCFI1345:
	movq	%rdi, -8(%rbp)
	movabsq	$4611686018427387903, %rax
	andq	-8(%rbp), %rax
	leave
LCFI1346:
	ret
LFE446:
.no_dead_strip _mod_pow2__mod_pow2_LC_63
_mod_pow2__mod_pow2_LC_63:
LFB447:
	pushq	%rbp
LCFI1347:
	movq	%rsp, %rbp
LCFI1348:
	pushq	%rbx
LCFI1349:
	subq	$24, %rsp
LCFI1350:
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leaq	-1(%rax), %rdx
	movq	%rax, %rcx
	orq	%rdx, %rcx
	sarq	$63, %rcx
	movq	%rdx, %rbx
	subq	%rcx, %rbx
	movabsq	$-9223372036854775808, %rdx
	cmpq	%rdx, %rbx
	sete	%dl
	movzbl	%dl, %edx
	notq	%rcx
	addq	%rcx, %rdx
	salq	$63, %rdx
	movq	%rax, %rcx
	subq	%rdx, %rcx
	movq	%rcx, %rdx
	testq	%rdx, %rdx
	jns	L450
	movl	$30369, %edi
	call	__m3_fault
L450:
	movq	-24(%rbp), %rax
	leaq	-1(%rax), %rdx
	movq	%rax, %rcx
	orq	%rdx, %rcx
	sarq	$63, %rcx
	movq	%rdx, %rbx
	subq	%rcx, %rbx
	movabsq	$-9223372036854775808, %rdx
	cmpq	%rdx, %rbx
	sete	%dl
	movzbl	%dl, %edx
	notq	%rcx
	addq	%rcx, %rdx
	salq	$63, %rdx
	movq	%rax, %rcx
	subq	%rdx, %rcx
	movq	%rcx, %rdx
	movq	%rdx, %rax
	addq	$24, %rsp
	popq	%rbx
	leave
LCFI1351:
	ret
LFE447:
.globl _mod_pow2_M3
.no_dead_strip _mod_pow2_M3
_mod_pow2_M3:
LFB448:
	pushq	%rbp
LCFI1352:
	movq	%rsp, %rbp
LCFI1353:
	movq	%rdi, -8(%rbp)
	leaq	_MM_mod_pow2(%rip), %rax
	leave
LCFI1354:
	ret
LFE448:
__m3_fault:
LFB449:
	pushq	%rbp
LCFI1355:
	movq	%rsp, %rbp
LCFI1356:
	subq	$16, %rsp
LCFI1357:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	movq	%rax, %rsi
	leaq	_MM_mod_pow2(%rip), %rdi
	call	_RTHooks__ReportFault
	leave
LCFI1358:
	ret
LFE449:
	.const_data
	.align 5
_L_1:
	.ascii "mod_pow2_M3"
	.space 1
	.ascii "mod_pow2_LC_63"
	.space 1
	.ascii "mod_pow2_LC_62"
	.space 1
	.ascii "mod_pow2_LC_61"
	.space 1
	.ascii "mod_pow2_LC_60"
	.space 1
	.ascii "mod_pow2_LC_59"
	.space 1
	.ascii "mod_pow2_LC_58"
	.space 1
	.ascii "mod_pow2_LC_57"
	.space 1
	.ascii "mod_pow2_LC_56"
	.space 1
	.ascii "mod_pow2_LC_55"
	.space 1
	.ascii "mod_pow2_LC_54"
	.space 1
	.ascii "mod_pow2_LC_53"
	.space 1
	.ascii "mod_pow2_LC_52"
	.space 1
	.ascii "mod_pow2_LC_51"
	.space 1
	.ascii "mod_pow2_LC_50"
	.space 1
	.ascii "mod_pow2_LC_49"
	.space 1
	.ascii "mod_pow2_LC_48"
	.space 1
	.ascii "mod_pow2_LC_47"
	.space 1
	.ascii "mod_pow2_LC_46"
	.space 1
	.ascii "mod_pow2_LC_45"
	.space 1
	.ascii "mod_pow2_LC_44"
	.space 1
	.ascii "mod_pow2_LC_43"
	.space 1
	.ascii "mod_pow2_LC_42"
	.space 1
	.ascii "mod_pow2_LC_41"
	.space 1
	.ascii "mod_pow2_LC_40"
	.space 1
	.ascii "mod_pow2_LC_39"
	.space 1
	.ascii "mod_pow2_LC_38"
	.space 1
	.ascii "mod_pow2_LC_37"
	.space 1
	.ascii "mod_pow2_LC_36"
	.space 1
	.ascii "mod_pow2_LC_35"
	.space 1
	.ascii "mod_pow2_LC_34"
	.space 1
	.ascii "mod_pow2_LC_33"
	.space 1
	.ascii "mod_pow2_LC_32"
	.space 1
	.ascii "mod_pow2_LC_31"
	.space 1
	.ascii "mod_pow2_LC_30"
	.space 1
	.ascii "mod_pow2_LC_29"
	.space 1
	.ascii "mod_pow2_LC_28"
	.space 1
	.ascii "mod_pow2_LC_27"
	.space 1
	.ascii "mod_pow2_LC_26"
	.space 1
	.ascii "mod_pow2_LC_25"
	.space 1
	.ascii "mod_pow2_LC_24"
	.space 1
	.ascii "mod_pow2_LC_23"
	.space 1
	.ascii "mod_pow2_LC_22"
	.space 1
	.ascii "mod_pow2_LC_21"
	.space 1
	.ascii "mod_pow2_LC_20"
	.space 1
	.ascii "mod_pow2_LC_19"
	.space 1
	.ascii "mod_pow2_LC_18"
	.space 1
	.ascii "mod_pow2_LC_17"
	.space 1
	.ascii "mod_pow2_LC_16"
	.space 1
	.ascii "mod_pow2_LC_15"
	.space 1
	.ascii "mod_pow2_LC_14"
	.space 1
	.ascii "mod_pow2_LC_13"
	.space 1
	.ascii "mod_pow2_LC_12"
	.space 1
	.ascii "mod_pow2_LC_11"
	.space 1
	.ascii "mod_pow2_LC_10"
	.space 1
	.ascii "mod_pow2_LC_9"
	.space 1
	.ascii "mod_pow2_LC_8"
	.space 1
	.ascii "mod_pow2_LC_7"
	.space 1
	.ascii "mod_pow2_LC_6"
	.space 1
	.ascii "mod_pow2_LC_5"
	.space 1
	.ascii "mod_pow2_LC_4"
	.space 1
	.ascii "mod_pow2_LC_3"
	.space 1
	.ascii "mod_pow2_LC_2"
	.space 1
	.ascii "mod_pow2_LC_1"
	.space 1
	.ascii "mod_pow2_LC_0"
	.space 1
	.ascii "mod_pow2_L_63"
	.space 1
	.ascii "mod_pow2_L_62"
	.space 1
	.ascii "mod_pow2_L_61"
	.space 1
	.ascii "mod_pow2_L_60"
	.space 1
	.ascii "mod_pow2_L_59"
	.space 1
	.ascii "mod_pow2_L_58"
	.space 1
	.ascii "mod_pow2_L_57"
	.space 1
	.ascii "mod_pow2_L_56"
	.space 1
	.ascii "mod_pow2_L_55"
	.space 1
	.ascii "mod_pow2_L_54"
	.space 1
	.ascii "mod_pow2_L_53"
	.space 1
	.ascii "mod_pow2_L_52"
	.space 1
	.ascii "mod_pow2_L_51"
	.space 1
	.ascii "mod_pow2_L_50"
	.space 1
	.ascii "mod_pow2_L_49"
	.space 1
	.ascii "mod_pow2_L_48"
	.space 1
	.ascii "mod_pow2_L_47"
	.space 1
	.ascii "mod_pow2_L_46"
	.space 1
	.ascii "mod_pow2_L_45"
	.space 1
	.ascii "mod_pow2_L_44"
	.space 1
	.ascii "mod_pow2_L_43"
	.space 1
	.ascii "mod_pow2_L_42"
	.space 1
	.ascii "mod_pow2_L_41"
	.space 1
	.ascii "mod_pow2_L_40"
	.space 1
	.ascii "mod_pow2_L_39"
	.space 1
	.ascii "mod_pow2_L_38"
	.space 1
	.ascii "mod_pow2_L_37"
	.space 1
	.ascii "mod_pow2_L_36"
	.space 1
	.ascii "mod_pow2_L_35"
	.space 1
	.ascii "mod_pow2_L_34"
	.space 1
	.ascii "mod_pow2_L_33"
	.space 1
	.ascii "mod_pow2_L_32"
	.space 1
	.ascii "mod_pow2_L_31"
	.space 1
	.ascii "mod_pow2_L_30"
	.space 1
	.ascii "mod_pow2_L_29"
	.space 1
	.ascii "mod_pow2_L_28"
	.space 1
	.ascii "mod_pow2_L_27"
	.space 1
	.ascii "mod_pow2_L_26"
	.space 1
	.ascii "mod_pow2_L_25"
	.space 1
	.ascii "mod_pow2_L_24"
	.space 1
	.ascii "mod_pow2_L_23"
	.space 1
	.ascii "mod_pow2_L_22"
	.space 1
	.ascii "mod_pow2_L_21"
	.space 1
	.ascii "mod_pow2_L_20"
	.space 1
	.ascii "mod_pow2_L_19"
	.space 1
	.ascii "mod_pow2_L_18"
	.space 1
	.ascii "mod_pow2_L_17"
	.space 1
	.ascii "mod_pow2_L_16"
	.space 1
	.ascii "mod_pow2_L_15"
	.space 1
	.ascii "mod_pow2_L_14"
	.space 1
	.ascii "mod_pow2_L_13"
	.space 1
	.ascii "mod_pow2_L_12"
	.space 1
	.ascii "mod_pow2_L_11"
	.space 1
	.ascii "mod_pow2_L_10"
	.space 1
	.ascii "mod_pow2_L_9"
	.space 1
	.ascii "mod_pow2_L_8"
	.space 1
	.ascii "mod_pow2_L_7"
	.space 1
	.ascii "mod_pow2_L_6"
	.space 1
	.ascii "mod_pow2_L_5"
	.space 1
	.ascii "mod_pow2_L_4"
	.space 1
	.ascii "mod_pow2_L_3"
	.space 1
	.ascii "mod_pow2_L_2"
	.space 1
	.ascii "mod_pow2_L_1"
	.space 1
	.ascii "mod_pow2_L_0"
	.space 1
	.ascii "mod_pow2_C_63"
	.space 1
	.ascii "mod_pow2_C_62"
	.space 1
	.ascii "mod_pow2_C_61"
	.space 1
	.ascii "mod_pow2_C_60"
	.space 1
	.ascii "mod_pow2_C_59"
	.space 1
	.ascii "mod_pow2_C_58"
	.space 1
	.ascii "mod_pow2_C_57"
	.space 1
	.ascii "mod_pow2_C_56"
	.space 1
	.ascii "mod_pow2_C_55"
	.space 1
	.ascii "mod_pow2_C_54"
	.space 1
	.ascii "mod_pow2_C_53"
	.space 1
	.ascii "mod_pow2_C_52"
	.space 1
	.ascii "mod_pow2_C_51"
	.space 1
	.ascii "mod_pow2_C_50"
	.space 1
	.ascii "mod_pow2_C_49"
	.space 1
	.ascii "mod_pow2_C_48"
	.space 1
	.ascii "mod_pow2_C_47"
	.space 1
	.ascii "mod_pow2_C_46"
	.space 1
	.ascii "mod_pow2_C_45"
	.space 1
	.ascii "mod_pow2_C_44"
	.space 1
	.ascii "mod_pow2_C_43"
	.space 1
	.ascii "mod_pow2_C_42"
	.space 1
	.ascii "mod_pow2_C_41"
	.space 1
	.ascii "mod_pow2_C_40"
	.space 1
	.ascii "mod_pow2_C_39"
	.space 1
	.ascii "mod_pow2_C_38"
	.space 1
	.ascii "mod_pow2_C_37"
	.space 1
	.ascii "mod_pow2_C_36"
	.space 1
	.ascii "mod_pow2_C_35"
	.space 1
	.ascii "mod_pow2_C_34"
	.space 1
	.ascii "mod_pow2_C_33"
	.space 1
	.ascii "mod_pow2_C_32"
	.space 1
	.ascii "mod_pow2_C_31"
	.space 1
	.ascii "mod_pow2_C_30"
	.space 1
	.ascii "mod_pow2_C_29"
	.space 1
	.ascii "mod_pow2_C_28"
	.space 1
	.ascii "mod_pow2_C_27"
	.space 1
	.ascii "mod_pow2_C_26"
	.space 1
	.ascii "mod_pow2_C_25"
	.space 1
	.ascii "mod_pow2_C_24"
	.space 1
	.ascii "mod_pow2_C_23"
	.space 1
	.ascii "mod_pow2_C_22"
	.space 1
	.ascii "mod_pow2_C_21"
	.space 1
	.ascii "mod_pow2_C_20"
	.space 1
	.ascii "mod_pow2_C_19"
	.space 1
	.ascii "mod_pow2_C_18"
	.space 1
	.ascii "mod_pow2_C_17"
	.space 1
	.ascii "mod_pow2_C_16"
	.space 1
	.ascii "mod_pow2_C_15"
	.space 1
	.ascii "mod_pow2_C_14"
	.space 1
	.ascii "mod_pow2_C_13"
	.space 1
	.ascii "mod_pow2_C_12"
	.space 1
	.ascii "mod_pow2_C_11"
	.space 1
	.ascii "mod_pow2_C_10"
	.space 1
	.ascii "mod_pow2_C_9"
	.space 1
	.ascii "mod_pow2_C_8"
	.space 1
	.ascii "mod_pow2_C_7"
	.space 1
	.ascii "mod_pow2_C_6"
	.space 1
	.ascii "mod_pow2_C_5"
	.space 1
	.ascii "mod_pow2_C_4"
	.space 1
	.ascii "mod_pow2_C_3"
	.space 1
	.ascii "mod_pow2_C_2"
	.space 1
	.ascii "mod_pow2_C_1"
	.space 1
	.ascii "mod_pow2_C_0"
	.space 1
	.ascii "mod_pow2_I_63"
	.space 1
	.ascii "mod_pow2_I_62"
	.space 1
	.ascii "mod_pow2_I_61"
	.space 1
	.ascii "mod_pow2_I_60"
	.space 1
	.ascii "mod_pow2_I_59"
	.space 1
	.ascii "mod_pow2_I_58"
	.space 1
	.ascii "mod_pow2_I_57"
	.space 1
	.ascii "mod_pow2_I_56"
	.space 1
	.ascii "mod_pow2_I_55"
	.space 1
	.ascii "mod_pow2_I_54"
	.space 1
	.ascii "mod_pow2_I_53"
	.space 1
	.ascii "mod_pow2_I_52"
	.space 1
	.ascii "mod_pow2_I_51"
	.space 1
	.ascii "mod_pow2_I_50"
	.space 1
	.ascii "mod_pow2_I_49"
	.space 1
	.ascii "mod_pow2_I_48"
	.space 1
	.ascii "mod_pow2_I_47"
	.space 1
	.ascii "mod_pow2_I_46"
	.space 1
	.ascii "mod_pow2_I_45"
	.space 1
	.ascii "mod_pow2_I_44"
	.space 1
	.ascii "mod_pow2_I_43"
	.space 1
	.ascii "mod_pow2_I_42"
	.space 1
	.ascii "mod_pow2_I_41"
	.space 1
	.ascii "mod_pow2_I_40"
	.space 1
	.ascii "mod_pow2_I_39"
	.space 1
	.ascii "mod_pow2_I_38"
	.space 1
	.ascii "mod_pow2_I_37"
	.space 1
	.ascii "mod_pow2_I_36"
	.space 1
	.ascii "mod_pow2_I_35"
	.space 1
	.ascii "mod_pow2_I_34"
	.space 1
	.ascii "mod_pow2_I_33"
	.space 1
	.ascii "mod_pow2_I_32"
	.space 1
	.ascii "mod_pow2_I_31"
	.space 1
	.ascii "mod_pow2_I_30"
	.space 1
	.ascii "mod_pow2_I_29"
	.space 1
	.ascii "mod_pow2_I_28"
	.space 1
	.ascii "mod_pow2_I_27"
	.space 1
	.ascii "mod_pow2_I_26"
	.space 1
	.ascii "mod_pow2_I_25"
	.space 1
	.ascii "mod_pow2_I_24"
	.space 1
	.ascii "mod_pow2_I_23"
	.space 1
	.ascii "mod_pow2_I_22"
	.space 1
	.ascii "mod_pow2_I_21"
	.space 1
	.ascii "mod_pow2_I_20"
	.space 1
	.ascii "mod_pow2_I_19"
	.space 1
	.ascii "mod_pow2_I_18"
	.space 1
	.ascii "mod_pow2_I_17"
	.space 1
	.ascii "mod_pow2_I_16"
	.space 1
	.ascii "mod_pow2_I_15"
	.space 1
	.ascii "mod_pow2_I_14"
	.space 1
	.ascii "mod_pow2_I_13"
	.space 1
	.ascii "mod_pow2_I_12"
	.space 1
	.ascii "mod_pow2_I_11"
	.space 1
	.ascii "mod_pow2_I_10"
	.space 1
	.ascii "mod_pow2_I_9"
	.space 1
	.ascii "mod_pow2_I_8"
	.space 1
	.ascii "mod_pow2_I_7"
	.space 1
	.ascii "mod_pow2_I_6"
	.space 1
	.ascii "mod_pow2_I_5"
	.space 1
	.ascii "mod_pow2_I_4"
	.space 1
	.ascii "mod_pow2_I_3"
	.space 1
	.ascii "mod_pow2_I_2"
	.space 1
	.ascii "mod_pow2_I_1"
	.space 1
	.ascii "mod_pow2_I_0"
	.space 1
	.ascii "mod_pow2_u64_63"
	.space 1
	.ascii "mod_pow2_u64_62"
	.space 1
	.ascii "mod_pow2_u64_61"
	.space 1
	.ascii "mod_pow2_u64_60"
	.space 1
	.ascii "mod_pow2_u64_59"
	.space 1
	.ascii "mod_pow2_u64_58"
	.space 1
	.ascii "mod_pow2_u64_57"
	.space 1
	.ascii "mod_pow2_u64_56"
	.space 1
	.ascii "mod_pow2_u64_55"
	.space 1
	.ascii "mod_pow2_u64_54"
	.space 1
	.ascii "mod_pow2_u64_53"
	.space 1
	.ascii "mod_pow2_u64_52"
	.space 1
	.ascii "mod_pow2_u64_51"
	.space 1
	.ascii "mod_pow2_u64_50"
	.space 1
	.ascii "mod_pow2_u64_49"
	.space 1
	.ascii "mod_pow2_u64_48"
	.space 1
	.ascii "mod_pow2_u64_47"
	.space 1
	.ascii "mod_pow2_u64_46"
	.space 1
	.ascii "mod_pow2_u64_45"
	.space 1
	.ascii "mod_pow2_u64_44"
	.space 1
	.ascii "mod_pow2_u64_43"
	.space 1
	.ascii "mod_pow2_u64_42"
	.space 1
	.ascii "mod_pow2_u64_41"
	.space 1
	.ascii "mod_pow2_u64_40"
	.space 1
	.ascii "mod_pow2_u64_39"
	.space 1
	.ascii "mod_pow2_u64_38"
	.space 1
	.ascii "mod_pow2_u64_37"
	.space 1
	.ascii "mod_pow2_u64_36"
	.space 1
	.ascii "mod_pow2_u64_35"
	.space 1
	.ascii "mod_pow2_u64_34"
	.space 1
	.ascii "mod_pow2_u64_33"
	.space 1
	.ascii "mod_pow2_u64_32"
	.space 1
	.ascii "mod_pow2_u64_31"
	.space 1
	.ascii "mod_pow2_u64_30"
	.space 1
	.ascii "mod_pow2_u64_29"
	.space 1
	.ascii "mod_pow2_u64_28"
	.space 1
	.ascii "mod_pow2_u64_27"
	.space 1
	.ascii "mod_pow2_u64_26"
	.space 1
	.ascii "mod_pow2_u64_25"
	.space 1
	.ascii "mod_pow2_u64_24"
	.space 1
	.ascii "mod_pow2_u64_23"
	.space 1
	.ascii "mod_pow2_u64_22"
	.space 1
	.ascii "mod_pow2_u64_21"
	.space 1
	.ascii "mod_pow2_u64_20"
	.space 1
	.ascii "mod_pow2_u64_19"
	.space 1
	.ascii "mod_pow2_u64_18"
	.space 1
	.ascii "mod_pow2_u64_17"
	.space 1
	.ascii "mod_pow2_u64_16"
	.space 1
	.ascii "mod_pow2_u64_15"
	.space 1
	.ascii "mod_pow2_u64_14"
	.space 1
	.ascii "mod_pow2_u64_13"
	.space 1
	.ascii "mod_pow2_u64_12"
	.space 1
	.ascii "mod_pow2_u64_11"
	.space 1
	.ascii "mod_pow2_u64_10"
	.space 1
	.ascii "mod_pow2_u64_9"
	.space 1
	.ascii "mod_pow2_u64_8"
	.space 1
	.ascii "mod_pow2_u64_7"
	.space 1
	.ascii "mod_pow2_u64_6"
	.space 1
	.ascii "mod_pow2_u64_5"
	.space 1
	.ascii "mod_pow2_u64_4"
	.space 1
	.ascii "mod_pow2_u64_3"
	.space 1
	.ascii "mod_pow2_u64_2"
	.space 1
	.ascii "mod_pow2_u64_1"
	.space 1
	.ascii "mod_pow2_u64_0"
	.space 1
	.ascii "mod_pow2_i64_63"
	.space 1
	.ascii "mod_pow2_i64_62"
	.space 1
	.ascii "mod_pow2_i64_61"
	.space 1
	.ascii "mod_pow2_i64_60"
	.space 1
	.ascii "mod_pow2_i64_59"
	.space 1
	.ascii "mod_pow2_i64_58"
	.space 1
	.ascii "mod_pow2_i64_57"
	.space 1
	.ascii "mod_pow2_i64_56"
	.space 1
	.ascii "mod_pow2_i64_55"
	.space 1
	.ascii "mod_pow2_i64_54"
	.space 1
	.ascii "mod_pow2_i64_53"
	.space 1
	.ascii "mod_pow2_i64_52"
	.space 1
	.ascii "mod_pow2_i64_51"
	.space 1
	.ascii "mod_pow2_i64_50"
	.space 1
	.ascii "mod_pow2_i64_49"
	.space 1
	.ascii "mod_pow2_i64_48"
	.space 1
	.ascii "mod_pow2_i64_47"
	.space 1
	.ascii "mod_pow2_i64_46"
	.space 1
	.ascii "mod_pow2_i64_45"
	.space 1
	.ascii "mod_pow2_i64_44"
	.space 1
	.ascii "mod_pow2_i64_43"
	.space 1
	.ascii "mod_pow2_i64_42"
	.space 1
	.ascii "mod_pow2_i64_41"
	.space 1
	.ascii "mod_pow2_i64_40"
	.space 1
	.ascii "mod_pow2_i64_39"
	.space 1
	.ascii "mod_pow2_i64_38"
	.space 1
	.ascii "mod_pow2_i64_37"
	.space 1
	.ascii "mod_pow2_i64_36"
	.space 1
	.ascii "mod_pow2_i64_35"
	.space 1
	.ascii "mod_pow2_i64_34"
	.space 1
	.ascii "mod_pow2_i64_33"
	.space 1
	.ascii "mod_pow2_i64_32"
	.space 1
	.ascii "mod_pow2_i64_31"
	.space 1
	.ascii "mod_pow2_i64_30"
	.space 1
	.ascii "mod_pow2_i64_29"
	.space 1
	.ascii "mod_pow2_i64_28"
	.space 1
	.ascii "mod_pow2_i64_27"
	.space 1
	.ascii "mod_pow2_i64_26"
	.space 1
	.ascii "mod_pow2_i64_25"
	.space 1
	.ascii "mod_pow2_i64_24"
	.space 1
	.ascii "mod_pow2_i64_23"
	.space 1
	.ascii "mod_pow2_i64_22"
	.space 1
	.ascii "mod_pow2_i64_21"
	.space 1
	.ascii "mod_pow2_i64_20"
	.space 1
	.ascii "mod_pow2_i64_19"
	.space 1
	.ascii "mod_pow2_i64_18"
	.space 1
	.ascii "mod_pow2_i64_17"
	.space 1
	.ascii "mod_pow2_i64_16"
	.space 1
	.ascii "mod_pow2_i64_15"
	.space 1
	.ascii "mod_pow2_i64_14"
	.space 1
	.ascii "mod_pow2_i64_13"
	.space 1
	.ascii "mod_pow2_i64_12"
	.space 1
	.ascii "mod_pow2_i64_11"
	.space 1
	.ascii "mod_pow2_i64_10"
	.space 1
	.ascii "mod_pow2_i64_9"
	.space 1
	.ascii "mod_pow2_i64_8"
	.space 1
	.ascii "mod_pow2_i64_7"
	.space 1
	.ascii "mod_pow2_i64_6"
	.space 1
	.ascii "mod_pow2_i64_5"
	.space 1
	.ascii "mod_pow2_i64_4"
	.space 1
	.ascii "mod_pow2_i64_3"
	.space 1
	.ascii "mod_pow2_i64_2"
	.space 1
	.ascii "mod_pow2_i64_1"
	.space 1
	.ascii "mod_pow2_i64_0"
	.space 1
	.ascii "mod_pow2_u32_31"
	.space 1
	.ascii "mod_pow2_u32_30"
	.space 1
	.ascii "mod_pow2_u32_29"
	.space 1
	.ascii "mod_pow2_u32_28"
	.space 1
	.ascii "mod_pow2_u32_27"
	.space 1
	.ascii "mod_pow2_u32_26"
	.space 1
	.ascii "mod_pow2_u32_25"
	.space 1
	.ascii "mod_pow2_u32_24"
	.space 1
	.ascii "mod_pow2_u32_23"
	.space 1
	.ascii "mod_pow2_u32_22"
	.space 1
	.ascii "mod_pow2_u32_21"
	.space 1
	.ascii "mod_pow2_u32_20"
	.space 1
	.ascii "mod_pow2_u32_19"
	.space 1
	.ascii "mod_pow2_u32_18"
	.space 1
	.ascii "mod_pow2_u32_17"
	.space 1
	.ascii "mod_pow2_u32_16"
	.space 1
	.ascii "mod_pow2_u32_15"
	.space 1
	.ascii "mod_pow2_u32_14"
	.space 1
	.ascii "mod_pow2_u32_13"
	.space 1
	.ascii "mod_pow2_u32_12"
	.space 1
	.ascii "mod_pow2_u32_11"
	.space 1
	.ascii "mod_pow2_u32_10"
	.space 1
	.ascii "mod_pow2_u32_9"
	.space 1
	.ascii "mod_pow2_u32_8"
	.space 1
	.ascii "mod_pow2_u32_7"
	.space 1
	.ascii "mod_pow2_u32_6"
	.space 1
	.ascii "mod_pow2_u32_5"
	.space 1
	.ascii "mod_pow2_u32_4"
	.space 1
	.ascii "mod_pow2_u32_3"
	.space 1
	.ascii "mod_pow2_u32_2"
	.space 1
	.ascii "mod_pow2_u32_1"
	.space 1
	.ascii "mod_pow2_u32_0"
	.space 1
	.ascii "mod_pow2_i32_31"
	.space 1
	.ascii "mod_pow2_i32_30"
	.space 1
	.ascii "mod_pow2_i32_29"
	.space 1
	.ascii "mod_pow2_i32_28"
	.space 1
	.ascii "mod_pow2_i32_27"
	.space 1
	.ascii "mod_pow2_i32_26"
	.space 1
	.ascii "mod_pow2_i32_25"
	.space 1
	.ascii "mod_pow2_i32_24"
	.space 1
	.ascii "mod_pow2_i32_23"
	.space 1
	.ascii "mod_pow2_i32_22"
	.space 1
	.ascii "mod_pow2_i32_21"
	.space 1
	.ascii "mod_pow2_i32_20"
	.space 1
	.ascii "mod_pow2_i32_19"
	.space 1
	.ascii "mod_pow2_i32_18"
	.space 1
	.ascii "mod_pow2_i32_17"
	.space 1
	.ascii "mod_pow2_i32_16"
	.space 1
	.ascii "mod_pow2_i32_15"
	.space 1
	.ascii "mod_pow2_i32_14"
	.space 1
	.ascii "mod_pow2_i32_13"
	.space 1
	.ascii "mod_pow2_i32_12"
	.space 1
	.ascii "mod_pow2_i32_11"
	.space 1
	.ascii "mod_pow2_i32_10"
	.space 1
	.ascii "mod_pow2_i32_9"
	.space 1
	.ascii "mod_pow2_i32_8"
	.space 1
	.ascii "mod_pow2_i32_7"
	.space 1
	.ascii "mod_pow2_i32_6"
	.space 1
	.ascii "mod_pow2_i32_5"
	.space 1
	.ascii "mod_pow2_i32_4"
	.space 1
	.ascii "mod_pow2_i32_3"
	.space 1
	.ascii "mod_pow2_i32_2"
	.space 1
	.ascii "mod_pow2_i32_1"
	.space 1
	.ascii "mod_pow2_i32_0"
	.space 5
	.quad	_mod_pow2_M3
	.quad	_L_1
	.quad	_mod_pow2__mod_pow2_LC_63
	.quad	_L_1+12
	.quad	_mod_pow2__mod_pow2_LC_62
	.quad	_L_1+27
	.quad	_mod_pow2__mod_pow2_LC_61
	.quad	_L_1+42
	.quad	_mod_pow2__mod_pow2_LC_60
	.quad	_L_1+57
	.quad	_mod_pow2__mod_pow2_LC_59
	.quad	_L_1+72
	.quad	_mod_pow2__mod_pow2_LC_58
	.quad	_L_1+87
	.quad	_mod_pow2__mod_pow2_LC_57
	.quad	_L_1+102
	.quad	_mod_pow2__mod_pow2_LC_56
	.quad	_L_1+117
	.quad	_mod_pow2__mod_pow2_LC_55
	.quad	_L_1+132
	.quad	_mod_pow2__mod_pow2_LC_54
	.quad	_L_1+147
	.quad	_mod_pow2__mod_pow2_LC_53
	.quad	_L_1+162
	.quad	_mod_pow2__mod_pow2_LC_52
	.quad	_L_1+177
	.quad	_mod_pow2__mod_pow2_LC_51
	.quad	_L_1+192
	.quad	_mod_pow2__mod_pow2_LC_50
	.quad	_L_1+207
	.quad	_mod_pow2__mod_pow2_LC_49
	.quad	_L_1+222
	.quad	_mod_pow2__mod_pow2_LC_48
	.quad	_L_1+237
	.quad	_mod_pow2__mod_pow2_LC_47
	.quad	_L_1+252
	.quad	_mod_pow2__mod_pow2_LC_46
	.quad	_L_1+267
	.quad	_mod_pow2__mod_pow2_LC_45
	.quad	_L_1+282
	.quad	_mod_pow2__mod_pow2_LC_44
	.quad	_L_1+297
	.quad	_mod_pow2__mod_pow2_LC_43
	.quad	_L_1+312
	.quad	_mod_pow2__mod_pow2_LC_42
	.quad	_L_1+327
	.quad	_mod_pow2__mod_pow2_LC_41
	.quad	_L_1+342
	.quad	_mod_pow2__mod_pow2_LC_40
	.quad	_L_1+357
	.quad	_mod_pow2__mod_pow2_LC_39
	.quad	_L_1+372
	.quad	_mod_pow2__mod_pow2_LC_38
	.quad	_L_1+387
	.quad	_mod_pow2__mod_pow2_LC_37
	.quad	_L_1+402
	.quad	_mod_pow2__mod_pow2_LC_36
	.quad	_L_1+417
	.quad	_mod_pow2__mod_pow2_LC_35
	.quad	_L_1+432
	.quad	_mod_pow2__mod_pow2_LC_34
	.quad	_L_1+447
	.quad	_mod_pow2__mod_pow2_LC_33
	.quad	_L_1+462
	.quad	_mod_pow2__mod_pow2_LC_32
	.quad	_L_1+477
	.quad	_mod_pow2__mod_pow2_LC_31
	.quad	_L_1+492
	.quad	_mod_pow2__mod_pow2_LC_30
	.quad	_L_1+507
	.quad	_mod_pow2__mod_pow2_LC_29
	.quad	_L_1+522
	.quad	_mod_pow2__mod_pow2_LC_28
	.quad	_L_1+537
	.quad	_mod_pow2__mod_pow2_LC_27
	.quad	_L_1+552
	.quad	_mod_pow2__mod_pow2_LC_26
	.quad	_L_1+567
	.quad	_mod_pow2__mod_pow2_LC_25
	.quad	_L_1+582
	.quad	_mod_pow2__mod_pow2_LC_24
	.quad	_L_1+597
	.quad	_mod_pow2__mod_pow2_LC_23
	.quad	_L_1+612
	.quad	_mod_pow2__mod_pow2_LC_22
	.quad	_L_1+627
	.quad	_mod_pow2__mod_pow2_LC_21
	.quad	_L_1+642
	.quad	_mod_pow2__mod_pow2_LC_20
	.quad	_L_1+657
	.quad	_mod_pow2__mod_pow2_LC_19
	.quad	_L_1+672
	.quad	_mod_pow2__mod_pow2_LC_18
	.quad	_L_1+687
	.quad	_mod_pow2__mod_pow2_LC_17
	.quad	_L_1+702
	.quad	_mod_pow2__mod_pow2_LC_16
	.quad	_L_1+717
	.quad	_mod_pow2__mod_pow2_LC_15
	.quad	_L_1+732
	.quad	_mod_pow2__mod_pow2_LC_14
	.quad	_L_1+747
	.quad	_mod_pow2__mod_pow2_LC_13
	.quad	_L_1+762
	.quad	_mod_pow2__mod_pow2_LC_12
	.quad	_L_1+777
	.quad	_mod_pow2__mod_pow2_LC_11
	.quad	_L_1+792
	.quad	_mod_pow2__mod_pow2_LC_10
	.quad	_L_1+807
	.quad	_mod_pow2__mod_pow2_LC_9
	.quad	_L_1+822
	.quad	_mod_pow2__mod_pow2_LC_8
	.quad	_L_1+836
	.quad	_mod_pow2__mod_pow2_LC_7
	.quad	_L_1+850
	.quad	_mod_pow2__mod_pow2_LC_6
	.quad	_L_1+864
	.quad	_mod_pow2__mod_pow2_LC_5
	.quad	_L_1+878
	.quad	_mod_pow2__mod_pow2_LC_4
	.quad	_L_1+892
	.quad	_mod_pow2__mod_pow2_LC_3
	.quad	_L_1+906
	.quad	_mod_pow2__mod_pow2_LC_2
	.quad	_L_1+920
	.quad	_mod_pow2__mod_pow2_LC_1
	.quad	_L_1+934
	.quad	_mod_pow2__mod_pow2_LC_0
	.quad	_L_1+948
	.quad	_mod_pow2__mod_pow2_L_63
	.quad	_L_1+962
	.quad	_mod_pow2__mod_pow2_L_62
	.quad	_L_1+976
	.quad	_mod_pow2__mod_pow2_L_61
	.quad	_L_1+990
	.quad	_mod_pow2__mod_pow2_L_60
	.quad	_L_1+1004
	.quad	_mod_pow2__mod_pow2_L_59
	.quad	_L_1+1018
	.quad	_mod_pow2__mod_pow2_L_58
	.quad	_L_1+1032
	.quad	_mod_pow2__mod_pow2_L_57
	.quad	_L_1+1046
	.quad	_mod_pow2__mod_pow2_L_56
	.quad	_L_1+1060
	.quad	_mod_pow2__mod_pow2_L_55
	.quad	_L_1+1074
	.quad	_mod_pow2__mod_pow2_L_54
	.quad	_L_1+1088
	.quad	_mod_pow2__mod_pow2_L_53
	.quad	_L_1+1102
	.quad	_mod_pow2__mod_pow2_L_52
	.quad	_L_1+1116
	.quad	_mod_pow2__mod_pow2_L_51
	.quad	_L_1+1130
	.quad	_mod_pow2__mod_pow2_L_50
	.quad	_L_1+1144
	.quad	_mod_pow2__mod_pow2_L_49
	.quad	_L_1+1158
	.quad	_mod_pow2__mod_pow2_L_48
	.quad	_L_1+1172
	.quad	_mod_pow2__mod_pow2_L_47
	.quad	_L_1+1186
	.quad	_mod_pow2__mod_pow2_L_46
	.quad	_L_1+1200
	.quad	_mod_pow2__mod_pow2_L_45
	.quad	_L_1+1214
	.quad	_mod_pow2__mod_pow2_L_44
	.quad	_L_1+1228
	.quad	_mod_pow2__mod_pow2_L_43
	.quad	_L_1+1242
	.quad	_mod_pow2__mod_pow2_L_42
	.quad	_L_1+1256
	.quad	_mod_pow2__mod_pow2_L_41
	.quad	_L_1+1270
	.quad	_mod_pow2__mod_pow2_L_40
	.quad	_L_1+1284
	.quad	_mod_pow2__mod_pow2_L_39
	.quad	_L_1+1298
	.quad	_mod_pow2__mod_pow2_L_38
	.quad	_L_1+1312
	.quad	_mod_pow2__mod_pow2_L_37
	.quad	_L_1+1326
	.quad	_mod_pow2__mod_pow2_L_36
	.quad	_L_1+1340
	.quad	_mod_pow2__mod_pow2_L_35
	.quad	_L_1+1354
	.quad	_mod_pow2__mod_pow2_L_34
	.quad	_L_1+1368
	.quad	_mod_pow2__mod_pow2_L_33
	.quad	_L_1+1382
	.quad	_mod_pow2__mod_pow2_L_32
	.quad	_L_1+1396
	.quad	_mod_pow2__mod_pow2_L_31
	.quad	_L_1+1410
	.quad	_mod_pow2__mod_pow2_L_30
	.quad	_L_1+1424
	.quad	_mod_pow2__mod_pow2_L_29
	.quad	_L_1+1438
	.quad	_mod_pow2__mod_pow2_L_28
	.quad	_L_1+1452
	.quad	_mod_pow2__mod_pow2_L_27
	.quad	_L_1+1466
	.quad	_mod_pow2__mod_pow2_L_26
	.quad	_L_1+1480
	.quad	_mod_pow2__mod_pow2_L_25
	.quad	_L_1+1494
	.quad	_mod_pow2__mod_pow2_L_24
	.quad	_L_1+1508
	.quad	_mod_pow2__mod_pow2_L_23
	.quad	_L_1+1522
	.quad	_mod_pow2__mod_pow2_L_22
	.quad	_L_1+1536
	.quad	_mod_pow2__mod_pow2_L_21
	.quad	_L_1+1550
	.quad	_mod_pow2__mod_pow2_L_20
	.quad	_L_1+1564
	.quad	_mod_pow2__mod_pow2_L_19
	.quad	_L_1+1578
	.quad	_mod_pow2__mod_pow2_L_18
	.quad	_L_1+1592
	.quad	_mod_pow2__mod_pow2_L_17
	.quad	_L_1+1606
	.quad	_mod_pow2__mod_pow2_L_16
	.quad	_L_1+1620
	.quad	_mod_pow2__mod_pow2_L_15
	.quad	_L_1+1634
	.quad	_mod_pow2__mod_pow2_L_14
	.quad	_L_1+1648
	.quad	_mod_pow2__mod_pow2_L_13
	.quad	_L_1+1662
	.quad	_mod_pow2__mod_pow2_L_12
	.quad	_L_1+1676
	.quad	_mod_pow2__mod_pow2_L_11
	.quad	_L_1+1690
	.quad	_mod_pow2__mod_pow2_L_10
	.quad	_L_1+1704
	.quad	_mod_pow2__mod_pow2_L_9
	.quad	_L_1+1718
	.quad	_mod_pow2__mod_pow2_L_8
	.quad	_L_1+1731
	.quad	_mod_pow2__mod_pow2_L_7
	.quad	_L_1+1744
	.quad	_mod_pow2__mod_pow2_L_6
	.quad	_L_1+1757
	.quad	_mod_pow2__mod_pow2_L_5
	.quad	_L_1+1770
	.quad	_mod_pow2__mod_pow2_L_4
	.quad	_L_1+1783
	.quad	_mod_pow2__mod_pow2_L_3
	.quad	_L_1+1796
	.quad	_mod_pow2__mod_pow2_L_2
	.quad	_L_1+1809
	.quad	_mod_pow2__mod_pow2_L_1
	.quad	_L_1+1822
	.quad	_mod_pow2__mod_pow2_L_0
	.quad	_L_1+1835
	.quad	_mod_pow2__mod_pow2_C_63
	.quad	_L_1+1848
	.quad	_mod_pow2__mod_pow2_C_62
	.quad	_L_1+1862
	.quad	_mod_pow2__mod_pow2_C_61
	.quad	_L_1+1876
	.quad	_mod_pow2__mod_pow2_C_60
	.quad	_L_1+1890
	.quad	_mod_pow2__mod_pow2_C_59
	.quad	_L_1+1904
	.quad	_mod_pow2__mod_pow2_C_58
	.quad	_L_1+1918
	.quad	_mod_pow2__mod_pow2_C_57
	.quad	_L_1+1932
	.quad	_mod_pow2__mod_pow2_C_56
	.quad	_L_1+1946
	.quad	_mod_pow2__mod_pow2_C_55
	.quad	_L_1+1960
	.quad	_mod_pow2__mod_pow2_C_54
	.quad	_L_1+1974
	.quad	_mod_pow2__mod_pow2_C_53
	.quad	_L_1+1988
	.quad	_mod_pow2__mod_pow2_C_52
	.quad	_L_1+2002
	.quad	_mod_pow2__mod_pow2_C_51
	.quad	_L_1+2016
	.quad	_mod_pow2__mod_pow2_C_50
	.quad	_L_1+2030
	.quad	_mod_pow2__mod_pow2_C_49
	.quad	_L_1+2044
	.quad	_mod_pow2__mod_pow2_C_48
	.quad	_L_1+2058
	.quad	_mod_pow2__mod_pow2_C_47
	.quad	_L_1+2072
	.quad	_mod_pow2__mod_pow2_C_46
	.quad	_L_1+2086
	.quad	_mod_pow2__mod_pow2_C_45
	.quad	_L_1+2100
	.quad	_mod_pow2__mod_pow2_C_44
	.quad	_L_1+2114
	.quad	_mod_pow2__mod_pow2_C_43
	.quad	_L_1+2128
	.quad	_mod_pow2__mod_pow2_C_42
	.quad	_L_1+2142
	.quad	_mod_pow2__mod_pow2_C_41
	.quad	_L_1+2156
	.quad	_mod_pow2__mod_pow2_C_40
	.quad	_L_1+2170
	.quad	_mod_pow2__mod_pow2_C_39
	.quad	_L_1+2184
	.quad	_mod_pow2__mod_pow2_C_38
	.quad	_L_1+2198
	.quad	_mod_pow2__mod_pow2_C_37
	.quad	_L_1+2212
	.quad	_mod_pow2__mod_pow2_C_36
	.quad	_L_1+2226
	.quad	_mod_pow2__mod_pow2_C_35
	.quad	_L_1+2240
	.quad	_mod_pow2__mod_pow2_C_34
	.quad	_L_1+2254
	.quad	_mod_pow2__mod_pow2_C_33
	.quad	_L_1+2268
	.quad	_mod_pow2__mod_pow2_C_32
	.quad	_L_1+2282
	.quad	_mod_pow2__mod_pow2_C_31
	.quad	_L_1+2296
	.quad	_mod_pow2__mod_pow2_C_30
	.quad	_L_1+2310
	.quad	_mod_pow2__mod_pow2_C_29
	.quad	_L_1+2324
	.quad	_mod_pow2__mod_pow2_C_28
	.quad	_L_1+2338
	.quad	_mod_pow2__mod_pow2_C_27
	.quad	_L_1+2352
	.quad	_mod_pow2__mod_pow2_C_26
	.quad	_L_1+2366
	.quad	_mod_pow2__mod_pow2_C_25
	.quad	_L_1+2380
	.quad	_mod_pow2__mod_pow2_C_24
	.quad	_L_1+2394
	.quad	_mod_pow2__mod_pow2_C_23
	.quad	_L_1+2408
	.quad	_mod_pow2__mod_pow2_C_22
	.quad	_L_1+2422
	.quad	_mod_pow2__mod_pow2_C_21
	.quad	_L_1+2436
	.quad	_mod_pow2__mod_pow2_C_20
	.quad	_L_1+2450
	.quad	_mod_pow2__mod_pow2_C_19
	.quad	_L_1+2464
	.quad	_mod_pow2__mod_pow2_C_18
	.quad	_L_1+2478
	.quad	_mod_pow2__mod_pow2_C_17
	.quad	_L_1+2492
	.quad	_mod_pow2__mod_pow2_C_16
	.quad	_L_1+2506
	.quad	_mod_pow2__mod_pow2_C_15
	.quad	_L_1+2520
	.quad	_mod_pow2__mod_pow2_C_14
	.quad	_L_1+2534
	.quad	_mod_pow2__mod_pow2_C_13
	.quad	_L_1+2548
	.quad	_mod_pow2__mod_pow2_C_12
	.quad	_L_1+2562
	.quad	_mod_pow2__mod_pow2_C_11
	.quad	_L_1+2576
	.quad	_mod_pow2__mod_pow2_C_10
	.quad	_L_1+2590
	.quad	_mod_pow2__mod_pow2_C_9
	.quad	_L_1+2604
	.quad	_mod_pow2__mod_pow2_C_8
	.quad	_L_1+2617
	.quad	_mod_pow2__mod_pow2_C_7
	.quad	_L_1+2630
	.quad	_mod_pow2__mod_pow2_C_6
	.quad	_L_1+2643
	.quad	_mod_pow2__mod_pow2_C_5
	.quad	_L_1+2656
	.quad	_mod_pow2__mod_pow2_C_4
	.quad	_L_1+2669
	.quad	_mod_pow2__mod_pow2_C_3
	.quad	_L_1+2682
	.quad	_mod_pow2__mod_pow2_C_2
	.quad	_L_1+2695
	.quad	_mod_pow2__mod_pow2_C_1
	.quad	_L_1+2708
	.quad	_mod_pow2__mod_pow2_C_0
	.quad	_L_1+2721
	.quad	_mod_pow2__mod_pow2_I_63
	.quad	_L_1+2734
	.quad	_mod_pow2__mod_pow2_I_62
	.quad	_L_1+2748
	.quad	_mod_pow2__mod_pow2_I_61
	.quad	_L_1+2762
	.quad	_mod_pow2__mod_pow2_I_60
	.quad	_L_1+2776
	.quad	_mod_pow2__mod_pow2_I_59
	.quad	_L_1+2790
	.quad	_mod_pow2__mod_pow2_I_58
	.quad	_L_1+2804
	.quad	_mod_pow2__mod_pow2_I_57
	.quad	_L_1+2818
	.quad	_mod_pow2__mod_pow2_I_56
	.quad	_L_1+2832
	.quad	_mod_pow2__mod_pow2_I_55
	.quad	_L_1+2846
	.quad	_mod_pow2__mod_pow2_I_54
	.quad	_L_1+2860
	.quad	_mod_pow2__mod_pow2_I_53
	.quad	_L_1+2874
	.quad	_mod_pow2__mod_pow2_I_52
	.quad	_L_1+2888
	.quad	_mod_pow2__mod_pow2_I_51
	.quad	_L_1+2902
	.quad	_mod_pow2__mod_pow2_I_50
	.quad	_L_1+2916
	.quad	_mod_pow2__mod_pow2_I_49
	.quad	_L_1+2930
	.quad	_mod_pow2__mod_pow2_I_48
	.quad	_L_1+2944
	.quad	_mod_pow2__mod_pow2_I_47
	.quad	_L_1+2958
	.quad	_mod_pow2__mod_pow2_I_46
	.quad	_L_1+2972
	.quad	_mod_pow2__mod_pow2_I_45
	.quad	_L_1+2986
	.quad	_mod_pow2__mod_pow2_I_44
	.quad	_L_1+3000
	.quad	_mod_pow2__mod_pow2_I_43
	.quad	_L_1+3014
	.quad	_mod_pow2__mod_pow2_I_42
	.quad	_L_1+3028
	.quad	_mod_pow2__mod_pow2_I_41
	.quad	_L_1+3042
	.quad	_mod_pow2__mod_pow2_I_40
	.quad	_L_1+3056
	.quad	_mod_pow2__mod_pow2_I_39
	.quad	_L_1+3070
	.quad	_mod_pow2__mod_pow2_I_38
	.quad	_L_1+3084
	.quad	_mod_pow2__mod_pow2_I_37
	.quad	_L_1+3098
	.quad	_mod_pow2__mod_pow2_I_36
	.quad	_L_1+3112
	.quad	_mod_pow2__mod_pow2_I_35
	.quad	_L_1+3126
	.quad	_mod_pow2__mod_pow2_I_34
	.quad	_L_1+3140
	.quad	_mod_pow2__mod_pow2_I_33
	.quad	_L_1+3154
	.quad	_mod_pow2__mod_pow2_I_32
	.quad	_L_1+3168
	.quad	_mod_pow2__mod_pow2_I_31
	.quad	_L_1+3182
	.quad	_mod_pow2__mod_pow2_I_30
	.quad	_L_1+3196
	.quad	_mod_pow2__mod_pow2_I_29
	.quad	_L_1+3210
	.quad	_mod_pow2__mod_pow2_I_28
	.quad	_L_1+3224
	.quad	_mod_pow2__mod_pow2_I_27
	.quad	_L_1+3238
	.quad	_mod_pow2__mod_pow2_I_26
	.quad	_L_1+3252
	.quad	_mod_pow2__mod_pow2_I_25
	.quad	_L_1+3266
	.quad	_mod_pow2__mod_pow2_I_24
	.quad	_L_1+3280
	.quad	_mod_pow2__mod_pow2_I_23
	.quad	_L_1+3294
	.quad	_mod_pow2__mod_pow2_I_22
	.quad	_L_1+3308
	.quad	_mod_pow2__mod_pow2_I_21
	.quad	_L_1+3322
	.quad	_mod_pow2__mod_pow2_I_20
	.quad	_L_1+3336
	.quad	_mod_pow2__mod_pow2_I_19
	.quad	_L_1+3350
	.quad	_mod_pow2__mod_pow2_I_18
	.quad	_L_1+3364
	.quad	_mod_pow2__mod_pow2_I_17
	.quad	_L_1+3378
	.quad	_mod_pow2__mod_pow2_I_16
	.quad	_L_1+3392
	.quad	_mod_pow2__mod_pow2_I_15
	.quad	_L_1+3406
	.quad	_mod_pow2__mod_pow2_I_14
	.quad	_L_1+3420
	.quad	_mod_pow2__mod_pow2_I_13
	.quad	_L_1+3434
	.quad	_mod_pow2__mod_pow2_I_12
	.quad	_L_1+3448
	.quad	_mod_pow2__mod_pow2_I_11
	.quad	_L_1+3462
	.quad	_mod_pow2__mod_pow2_I_10
	.quad	_L_1+3476
	.quad	_mod_pow2__mod_pow2_I_9
	.quad	_L_1+3490
	.quad	_mod_pow2__mod_pow2_I_8
	.quad	_L_1+3503
	.quad	_mod_pow2__mod_pow2_I_7
	.quad	_L_1+3516
	.quad	_mod_pow2__mod_pow2_I_6
	.quad	_L_1+3529
	.quad	_mod_pow2__mod_pow2_I_5
	.quad	_L_1+3542
	.quad	_mod_pow2__mod_pow2_I_4
	.quad	_L_1+3555
	.quad	_mod_pow2__mod_pow2_I_3
	.quad	_L_1+3568
	.quad	_mod_pow2__mod_pow2_I_2
	.quad	_L_1+3581
	.quad	_mod_pow2__mod_pow2_I_1
	.quad	_L_1+3594
	.quad	_mod_pow2__mod_pow2_I_0
	.quad	_L_1+3607
	.quad	_mod_pow2__mod_pow2_u64_63
	.quad	_L_1+3620
	.quad	_mod_pow2__mod_pow2_u64_62
	.quad	_L_1+3636
	.quad	_mod_pow2__mod_pow2_u64_61
	.quad	_L_1+3652
	.quad	_mod_pow2__mod_pow2_u64_60
	.quad	_L_1+3668
	.quad	_mod_pow2__mod_pow2_u64_59
	.quad	_L_1+3684
	.quad	_mod_pow2__mod_pow2_u64_58
	.quad	_L_1+3700
	.quad	_mod_pow2__mod_pow2_u64_57
	.quad	_L_1+3716
	.quad	_mod_pow2__mod_pow2_u64_56
	.quad	_L_1+3732
	.quad	_mod_pow2__mod_pow2_u64_55
	.quad	_L_1+3748
	.quad	_mod_pow2__mod_pow2_u64_54
	.quad	_L_1+3764
	.quad	_mod_pow2__mod_pow2_u64_53
	.quad	_L_1+3780
	.quad	_mod_pow2__mod_pow2_u64_52
	.quad	_L_1+3796
	.quad	_mod_pow2__mod_pow2_u64_51
	.quad	_L_1+3812
	.quad	_mod_pow2__mod_pow2_u64_50
	.quad	_L_1+3828
	.quad	_mod_pow2__mod_pow2_u64_49
	.quad	_L_1+3844
	.quad	_mod_pow2__mod_pow2_u64_48
	.quad	_L_1+3860
	.quad	_mod_pow2__mod_pow2_u64_47
	.quad	_L_1+3876
	.quad	_mod_pow2__mod_pow2_u64_46
	.quad	_L_1+3892
	.quad	_mod_pow2__mod_pow2_u64_45
	.quad	_L_1+3908
	.quad	_mod_pow2__mod_pow2_u64_44
	.quad	_L_1+3924
	.quad	_mod_pow2__mod_pow2_u64_43
	.quad	_L_1+3940
	.quad	_mod_pow2__mod_pow2_u64_42
	.quad	_L_1+3956
	.quad	_mod_pow2__mod_pow2_u64_41
	.quad	_L_1+3972
	.quad	_mod_pow2__mod_pow2_u64_40
	.quad	_L_1+3988
	.quad	_mod_pow2__mod_pow2_u64_39
	.quad	_L_1+4004
	.quad	_mod_pow2__mod_pow2_u64_38
	.quad	_L_1+4020
	.quad	_mod_pow2__mod_pow2_u64_37
	.quad	_L_1+4036
	.quad	_mod_pow2__mod_pow2_u64_36
	.quad	_L_1+4052
	.quad	_mod_pow2__mod_pow2_u64_35
	.quad	_L_1+4068
	.quad	_mod_pow2__mod_pow2_u64_34
	.quad	_L_1+4084
	.quad	_mod_pow2__mod_pow2_u64_33
	.quad	_L_1+4100
	.quad	_mod_pow2__mod_pow2_u64_32
	.quad	_L_1+4116
	.quad	_mod_pow2__mod_pow2_u64_31
	.quad	_L_1+4132
	.quad	_mod_pow2__mod_pow2_u64_30
	.quad	_L_1+4148
	.quad	_mod_pow2__mod_pow2_u64_29
	.quad	_L_1+4164
	.quad	_mod_pow2__mod_pow2_u64_28
	.quad	_L_1+4180
	.quad	_mod_pow2__mod_pow2_u64_27
	.quad	_L_1+4196
	.quad	_mod_pow2__mod_pow2_u64_26
	.quad	_L_1+4212
	.quad	_mod_pow2__mod_pow2_u64_25
	.quad	_L_1+4228
	.quad	_mod_pow2__mod_pow2_u64_24
	.quad	_L_1+4244
	.quad	_mod_pow2__mod_pow2_u64_23
	.quad	_L_1+4260
	.quad	_mod_pow2__mod_pow2_u64_22
	.quad	_L_1+4276
	.quad	_mod_pow2__mod_pow2_u64_21
	.quad	_L_1+4292
	.quad	_mod_pow2__mod_pow2_u64_20
	.quad	_L_1+4308
	.quad	_mod_pow2__mod_pow2_u64_19
	.quad	_L_1+4324
	.quad	_mod_pow2__mod_pow2_u64_18
	.quad	_L_1+4340
	.quad	_mod_pow2__mod_pow2_u64_17
	.quad	_L_1+4356
	.quad	_mod_pow2__mod_pow2_u64_16
	.quad	_L_1+4372
	.quad	_mod_pow2__mod_pow2_u64_15
	.quad	_L_1+4388
	.quad	_mod_pow2__mod_pow2_u64_14
	.quad	_L_1+4404
	.quad	_mod_pow2__mod_pow2_u64_13
	.quad	_L_1+4420
	.quad	_mod_pow2__mod_pow2_u64_12
	.quad	_L_1+4436
	.quad	_mod_pow2__mod_pow2_u64_11
	.quad	_L_1+4452
	.quad	_mod_pow2__mod_pow2_u64_10
	.quad	_L_1+4468
	.quad	_mod_pow2__mod_pow2_u64_9
	.quad	_L_1+4484
	.quad	_mod_pow2__mod_pow2_u64_8
	.quad	_L_1+4499
	.quad	_mod_pow2__mod_pow2_u64_7
	.quad	_L_1+4514
	.quad	_mod_pow2__mod_pow2_u64_6
	.quad	_L_1+4529
	.quad	_mod_pow2__mod_pow2_u64_5
	.quad	_L_1+4544
	.quad	_mod_pow2__mod_pow2_u64_4
	.quad	_L_1+4559
	.quad	_mod_pow2__mod_pow2_u64_3
	.quad	_L_1+4574
	.quad	_mod_pow2__mod_pow2_u64_2
	.quad	_L_1+4589
	.quad	_mod_pow2__mod_pow2_u64_1
	.quad	_L_1+4604
	.quad	_mod_pow2__mod_pow2_u64_0
	.quad	_L_1+4619
	.quad	_mod_pow2__mod_pow2_i64_63
	.quad	_L_1+4634
	.quad	_mod_pow2__mod_pow2_i64_62
	.quad	_L_1+4650
	.quad	_mod_pow2__mod_pow2_i64_61
	.quad	_L_1+4666
	.quad	_mod_pow2__mod_pow2_i64_60
	.quad	_L_1+4682
	.quad	_mod_pow2__mod_pow2_i64_59
	.quad	_L_1+4698
	.quad	_mod_pow2__mod_pow2_i64_58
	.quad	_L_1+4714
	.quad	_mod_pow2__mod_pow2_i64_57
	.quad	_L_1+4730
	.quad	_mod_pow2__mod_pow2_i64_56
	.quad	_L_1+4746
	.quad	_mod_pow2__mod_pow2_i64_55
	.quad	_L_1+4762
	.quad	_mod_pow2__mod_pow2_i64_54
	.quad	_L_1+4778
	.quad	_mod_pow2__mod_pow2_i64_53
	.quad	_L_1+4794
	.quad	_mod_pow2__mod_pow2_i64_52
	.quad	_L_1+4810
	.quad	_mod_pow2__mod_pow2_i64_51
	.quad	_L_1+4826
	.quad	_mod_pow2__mod_pow2_i64_50
	.quad	_L_1+4842
	.quad	_mod_pow2__mod_pow2_i64_49
	.quad	_L_1+4858
	.quad	_mod_pow2__mod_pow2_i64_48
	.quad	_L_1+4874
	.quad	_mod_pow2__mod_pow2_i64_47
	.quad	_L_1+4890
	.quad	_mod_pow2__mod_pow2_i64_46
	.quad	_L_1+4906
	.quad	_mod_pow2__mod_pow2_i64_45
	.quad	_L_1+4922
	.quad	_mod_pow2__mod_pow2_i64_44
	.quad	_L_1+4938
	.quad	_mod_pow2__mod_pow2_i64_43
	.quad	_L_1+4954
	.quad	_mod_pow2__mod_pow2_i64_42
	.quad	_L_1+4970
	.quad	_mod_pow2__mod_pow2_i64_41
	.quad	_L_1+4986
	.quad	_mod_pow2__mod_pow2_i64_40
	.quad	_L_1+5002
	.quad	_mod_pow2__mod_pow2_i64_39
	.quad	_L_1+5018
	.quad	_mod_pow2__mod_pow2_i64_38
	.quad	_L_1+5034
	.quad	_mod_pow2__mod_pow2_i64_37
	.quad	_L_1+5050
	.quad	_mod_pow2__mod_pow2_i64_36
	.quad	_L_1+5066
	.quad	_mod_pow2__mod_pow2_i64_35
	.quad	_L_1+5082
	.quad	_mod_pow2__mod_pow2_i64_34
	.quad	_L_1+5098
	.quad	_mod_pow2__mod_pow2_i64_33
	.quad	_L_1+5114
	.quad	_mod_pow2__mod_pow2_i64_32
	.quad	_L_1+5130
	.quad	_mod_pow2__mod_pow2_i64_31
	.quad	_L_1+5146
	.quad	_mod_pow2__mod_pow2_i64_30
	.quad	_L_1+5162
	.quad	_mod_pow2__mod_pow2_i64_29
	.quad	_L_1+5178
	.quad	_mod_pow2__mod_pow2_i64_28
	.quad	_L_1+5194
	.quad	_mod_pow2__mod_pow2_i64_27
	.quad	_L_1+5210
	.quad	_mod_pow2__mod_pow2_i64_26
	.quad	_L_1+5226
	.quad	_mod_pow2__mod_pow2_i64_25
	.quad	_L_1+5242
	.quad	_mod_pow2__mod_pow2_i64_24
	.quad	_L_1+5258
	.quad	_mod_pow2__mod_pow2_i64_23
	.quad	_L_1+5274
	.quad	_mod_pow2__mod_pow2_i64_22
	.quad	_L_1+5290
	.quad	_mod_pow2__mod_pow2_i64_21
	.quad	_L_1+5306
	.quad	_mod_pow2__mod_pow2_i64_20
	.quad	_L_1+5322
	.quad	_mod_pow2__mod_pow2_i64_19
	.quad	_L_1+5338
	.quad	_mod_pow2__mod_pow2_i64_18
	.quad	_L_1+5354
	.quad	_mod_pow2__mod_pow2_i64_17
	.quad	_L_1+5370
	.quad	_mod_pow2__mod_pow2_i64_16
	.quad	_L_1+5386
	.quad	_mod_pow2__mod_pow2_i64_15
	.quad	_L_1+5402
	.quad	_mod_pow2__mod_pow2_i64_14
	.quad	_L_1+5418
	.quad	_mod_pow2__mod_pow2_i64_13
	.quad	_L_1+5434
	.quad	_mod_pow2__mod_pow2_i64_12
	.quad	_L_1+5450
	.quad	_mod_pow2__mod_pow2_i64_11
	.quad	_L_1+5466
	.quad	_mod_pow2__mod_pow2_i64_10
	.quad	_L_1+5482
	.quad	_mod_pow2__mod_pow2_i64_9
	.quad	_L_1+5498
	.quad	_mod_pow2__mod_pow2_i64_8
	.quad	_L_1+5513
	.quad	_mod_pow2__mod_pow2_i64_7
	.quad	_L_1+5528
	.quad	_mod_pow2__mod_pow2_i64_6
	.quad	_L_1+5543
	.quad	_mod_pow2__mod_pow2_i64_5
	.quad	_L_1+5558
	.quad	_mod_pow2__mod_pow2_i64_4
	.quad	_L_1+5573
	.quad	_mod_pow2__mod_pow2_i64_3
	.quad	_L_1+5588
	.quad	_mod_pow2__mod_pow2_i64_2
	.quad	_L_1+5603
	.quad	_mod_pow2__mod_pow2_i64_1
	.quad	_L_1+5618
	.quad	_mod_pow2__mod_pow2_i64_0
	.quad	_L_1+5633
	.quad	_mod_pow2__mod_pow2_u32_31
	.quad	_L_1+5648
	.quad	_mod_pow2__mod_pow2_u32_30
	.quad	_L_1+5664
	.quad	_mod_pow2__mod_pow2_u32_29
	.quad	_L_1+5680
	.quad	_mod_pow2__mod_pow2_u32_28
	.quad	_L_1+5696
	.quad	_mod_pow2__mod_pow2_u32_27
	.quad	_L_1+5712
	.quad	_mod_pow2__mod_pow2_u32_26
	.quad	_L_1+5728
	.quad	_mod_pow2__mod_pow2_u32_25
	.quad	_L_1+5744
	.quad	_mod_pow2__mod_pow2_u32_24
	.quad	_L_1+5760
	.quad	_mod_pow2__mod_pow2_u32_23
	.quad	_L_1+5776
	.quad	_mod_pow2__mod_pow2_u32_22
	.quad	_L_1+5792
	.quad	_mod_pow2__mod_pow2_u32_21
	.quad	_L_1+5808
	.quad	_mod_pow2__mod_pow2_u32_20
	.quad	_L_1+5824
	.quad	_mod_pow2__mod_pow2_u32_19
	.quad	_L_1+5840
	.quad	_mod_pow2__mod_pow2_u32_18
	.quad	_L_1+5856
	.quad	_mod_pow2__mod_pow2_u32_17
	.quad	_L_1+5872
	.quad	_mod_pow2__mod_pow2_u32_16
	.quad	_L_1+5888
	.quad	_mod_pow2__mod_pow2_u32_15
	.quad	_L_1+5904
	.quad	_mod_pow2__mod_pow2_u32_14
	.quad	_L_1+5920
	.quad	_mod_pow2__mod_pow2_u32_13
	.quad	_L_1+5936
	.quad	_mod_pow2__mod_pow2_u32_12
	.quad	_L_1+5952
	.quad	_mod_pow2__mod_pow2_u32_11
	.quad	_L_1+5968
	.quad	_mod_pow2__mod_pow2_u32_10
	.quad	_L_1+5984
	.quad	_mod_pow2__mod_pow2_u32_9
	.quad	_L_1+6000
	.quad	_mod_pow2__mod_pow2_u32_8
	.quad	_L_1+6015
	.quad	_mod_pow2__mod_pow2_u32_7
	.quad	_L_1+6030
	.quad	_mod_pow2__mod_pow2_u32_6
	.quad	_L_1+6045
	.quad	_mod_pow2__mod_pow2_u32_5
	.quad	_L_1+6060
	.quad	_mod_pow2__mod_pow2_u32_4
	.quad	_L_1+6075
	.quad	_mod_pow2__mod_pow2_u32_3
	.quad	_L_1+6090
	.quad	_mod_pow2__mod_pow2_u32_2
	.quad	_L_1+6105
	.quad	_mod_pow2__mod_pow2_u32_1
	.quad	_L_1+6120
	.quad	_mod_pow2__mod_pow2_u32_0
	.quad	_L_1+6135
	.quad	_mod_pow2__mod_pow2_i32_31
	.quad	_L_1+6150
	.quad	_mod_pow2__mod_pow2_i32_30
	.quad	_L_1+6166
	.quad	_mod_pow2__mod_pow2_i32_29
	.quad	_L_1+6182
	.quad	_mod_pow2__mod_pow2_i32_28
	.quad	_L_1+6198
	.quad	_mod_pow2__mod_pow2_i32_27
	.quad	_L_1+6214
	.quad	_mod_pow2__mod_pow2_i32_26
	.quad	_L_1+6230
	.quad	_mod_pow2__mod_pow2_i32_25
	.quad	_L_1+6246
	.quad	_mod_pow2__mod_pow2_i32_24
	.quad	_L_1+6262
	.quad	_mod_pow2__mod_pow2_i32_23
	.quad	_L_1+6278
	.quad	_mod_pow2__mod_pow2_i32_22
	.quad	_L_1+6294
	.quad	_mod_pow2__mod_pow2_i32_21
	.quad	_L_1+6310
	.quad	_mod_pow2__mod_pow2_i32_20
	.quad	_L_1+6326
	.quad	_mod_pow2__mod_pow2_i32_19
	.quad	_L_1+6342
	.quad	_mod_pow2__mod_pow2_i32_18
	.quad	_L_1+6358
	.quad	_mod_pow2__mod_pow2_i32_17
	.quad	_L_1+6374
	.quad	_mod_pow2__mod_pow2_i32_16
	.quad	_L_1+6390
	.quad	_mod_pow2__mod_pow2_i32_15
	.quad	_L_1+6406
	.quad	_mod_pow2__mod_pow2_i32_14
	.quad	_L_1+6422
	.quad	_mod_pow2__mod_pow2_i32_13
	.quad	_L_1+6438
	.quad	_mod_pow2__mod_pow2_i32_12
	.quad	_L_1+6454
	.quad	_mod_pow2__mod_pow2_i32_11
	.quad	_L_1+6470
	.quad	_mod_pow2__mod_pow2_i32_10
	.quad	_L_1+6486
	.quad	_mod_pow2__mod_pow2_i32_9
	.quad	_L_1+6502
	.quad	_mod_pow2__mod_pow2_i32_8
	.quad	_L_1+6517
	.quad	_mod_pow2__mod_pow2_i32_7
	.quad	_L_1+6532
	.quad	_mod_pow2__mod_pow2_i32_6
	.quad	_L_1+6547
	.quad	_mod_pow2__mod_pow2_i32_5
	.quad	_L_1+6562
	.quad	_mod_pow2__mod_pow2_i32_4
	.quad	_L_1+6577
	.quad	_mod_pow2__mod_pow2_i32_3
	.quad	_L_1+6592
	.quad	_mod_pow2__mod_pow2_i32_2
	.quad	_L_1+6607
	.quad	_mod_pow2__mod_pow2_i32_1
	.quad	_L_1+6622
	.quad	_mod_pow2__mod_pow2_i32_0
	.quad	_L_1+6637
	.space 8
	.ascii "../AMD64_DARWIN/mod_pow2.m3"
	.space 5
	.data
	.align 5
_MM_mod_pow2:
	.quad	_L_1+13848
	.space 32
	.quad	_L_1+6656
	.space 24
	.quad	_MM_mod_pow2+224
	.space 8
	.quad	_mod_pow2_M3
	.quad	3
	.word	945
	.space 2
	.long	946
	.quad	947
	.quad	948
	.word	949
	.space 6
	.quad	950
	.long	-1305670058
	.long	1083031453
	.long	953
	.space 4
	.quad	954
	.byte	-69
	.space 7
	.quad	956
	.long	1148157264
	.space 4
	.quad	959
	.byte	-64
	.space 31
	.quad	_mod_pow2_I3
	.quad	_MM_mod_pow2+248
	.space 8
	.quad	_Long_I3
	.quad	_MM_mod_pow2+272
	.space 8
	.quad	_Word_I3
	.quad	_MM_mod_pow2+296
	.space 8
	.quad	_Cstdint_I3
	.quad	_MM_mod_pow2+320
	.space 8
	.quad	_RTHooks_I3
	.space 8
_mod_pow2__mod_pow2_i32_0.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_0.eh
_mod_pow2__mod_pow2_i32_1.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_1.eh
_mod_pow2__mod_pow2_i32_2.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_2.eh
_mod_pow2__mod_pow2_i32_3.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_3.eh
_mod_pow2__mod_pow2_i32_4.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_4.eh
_mod_pow2__mod_pow2_i32_5.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_5.eh
_mod_pow2__mod_pow2_i32_6.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_6.eh
_mod_pow2__mod_pow2_i32_7.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_7.eh
_mod_pow2__mod_pow2_i32_8.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_8.eh
_mod_pow2__mod_pow2_i32_9.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_9.eh
_mod_pow2__mod_pow2_i32_10.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_10.eh
_mod_pow2__mod_pow2_i32_11.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_11.eh
_mod_pow2__mod_pow2_i32_12.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_12.eh
_mod_pow2__mod_pow2_i32_13.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_13.eh
_mod_pow2__mod_pow2_i32_14.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_14.eh
_mod_pow2__mod_pow2_i32_15.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_15.eh
_mod_pow2__mod_pow2_i32_16.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_16.eh
_mod_pow2__mod_pow2_i32_17.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_17.eh
_mod_pow2__mod_pow2_i32_18.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_18.eh
_mod_pow2__mod_pow2_i32_19.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_19.eh
_mod_pow2__mod_pow2_i32_20.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_20.eh
_mod_pow2__mod_pow2_i32_21.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_21.eh
_mod_pow2__mod_pow2_i32_22.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_22.eh
_mod_pow2__mod_pow2_i32_23.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_23.eh
_mod_pow2__mod_pow2_i32_24.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_24.eh
_mod_pow2__mod_pow2_i32_25.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_25.eh
_mod_pow2__mod_pow2_i32_26.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_26.eh
_mod_pow2__mod_pow2_i32_27.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_27.eh
_mod_pow2__mod_pow2_i32_28.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_28.eh
_mod_pow2__mod_pow2_i32_29.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_29.eh
_mod_pow2__mod_pow2_i32_30.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_30.eh
_mod_pow2__mod_pow2_i32_31.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i32_31.eh
_mod_pow2__mod_pow2_u32_0.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_0.eh
_mod_pow2__mod_pow2_u32_1.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_1.eh
_mod_pow2__mod_pow2_u32_2.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_2.eh
_mod_pow2__mod_pow2_u32_3.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_3.eh
_mod_pow2__mod_pow2_u32_4.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_4.eh
_mod_pow2__mod_pow2_u32_5.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_5.eh
_mod_pow2__mod_pow2_u32_6.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_6.eh
_mod_pow2__mod_pow2_u32_7.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_7.eh
_mod_pow2__mod_pow2_u32_8.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_8.eh
_mod_pow2__mod_pow2_u32_9.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_9.eh
_mod_pow2__mod_pow2_u32_10.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_10.eh
_mod_pow2__mod_pow2_u32_11.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_11.eh
_mod_pow2__mod_pow2_u32_12.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_12.eh
_mod_pow2__mod_pow2_u32_13.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_13.eh
_mod_pow2__mod_pow2_u32_14.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_14.eh
_mod_pow2__mod_pow2_u32_15.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_15.eh
_mod_pow2__mod_pow2_u32_16.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_16.eh
_mod_pow2__mod_pow2_u32_17.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_17.eh
_mod_pow2__mod_pow2_u32_18.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_18.eh
_mod_pow2__mod_pow2_u32_19.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_19.eh
_mod_pow2__mod_pow2_u32_20.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_20.eh
_mod_pow2__mod_pow2_u32_21.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_21.eh
_mod_pow2__mod_pow2_u32_22.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_22.eh
_mod_pow2__mod_pow2_u32_23.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_23.eh
_mod_pow2__mod_pow2_u32_24.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_24.eh
_mod_pow2__mod_pow2_u32_25.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_25.eh
_mod_pow2__mod_pow2_u32_26.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_26.eh
_mod_pow2__mod_pow2_u32_27.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_27.eh
_mod_pow2__mod_pow2_u32_28.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_28.eh
_mod_pow2__mod_pow2_u32_29.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_29.eh
_mod_pow2__mod_pow2_u32_30.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_30.eh
_mod_pow2__mod_pow2_u32_31.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u32_31.eh
_mod_pow2__mod_pow2_i64_0.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_0.eh
_mod_pow2__mod_pow2_i64_1.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_1.eh
_mod_pow2__mod_pow2_i64_2.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_2.eh
_mod_pow2__mod_pow2_i64_3.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_3.eh
_mod_pow2__mod_pow2_i64_4.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_4.eh
_mod_pow2__mod_pow2_i64_5.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_5.eh
_mod_pow2__mod_pow2_i64_6.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_6.eh
_mod_pow2__mod_pow2_i64_7.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_7.eh
_mod_pow2__mod_pow2_i64_8.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_8.eh
_mod_pow2__mod_pow2_i64_9.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_9.eh
_mod_pow2__mod_pow2_i64_10.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_10.eh
_mod_pow2__mod_pow2_i64_11.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_11.eh
_mod_pow2__mod_pow2_i64_12.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_12.eh
_mod_pow2__mod_pow2_i64_13.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_13.eh
_mod_pow2__mod_pow2_i64_14.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_14.eh
_mod_pow2__mod_pow2_i64_15.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_15.eh
_mod_pow2__mod_pow2_i64_16.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_16.eh
_mod_pow2__mod_pow2_i64_17.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_17.eh
_mod_pow2__mod_pow2_i64_18.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_18.eh
_mod_pow2__mod_pow2_i64_19.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_19.eh
_mod_pow2__mod_pow2_i64_20.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_20.eh
_mod_pow2__mod_pow2_i64_21.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_21.eh
_mod_pow2__mod_pow2_i64_22.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_22.eh
_mod_pow2__mod_pow2_i64_23.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_23.eh
_mod_pow2__mod_pow2_i64_24.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_24.eh
_mod_pow2__mod_pow2_i64_25.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_25.eh
_mod_pow2__mod_pow2_i64_26.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_26.eh
_mod_pow2__mod_pow2_i64_27.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_27.eh
_mod_pow2__mod_pow2_i64_28.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_28.eh
_mod_pow2__mod_pow2_i64_29.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_29.eh
_mod_pow2__mod_pow2_i64_30.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_30.eh
_mod_pow2__mod_pow2_i64_31.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_31.eh
_mod_pow2__mod_pow2_i64_32.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_32.eh
_mod_pow2__mod_pow2_i64_33.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_33.eh
_mod_pow2__mod_pow2_i64_34.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_34.eh
_mod_pow2__mod_pow2_i64_35.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_35.eh
_mod_pow2__mod_pow2_i64_36.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_36.eh
_mod_pow2__mod_pow2_i64_37.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_37.eh
_mod_pow2__mod_pow2_i64_38.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_38.eh
_mod_pow2__mod_pow2_i64_39.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_39.eh
_mod_pow2__mod_pow2_i64_40.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_40.eh
_mod_pow2__mod_pow2_i64_41.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_41.eh
_mod_pow2__mod_pow2_i64_42.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_42.eh
_mod_pow2__mod_pow2_i64_43.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_43.eh
_mod_pow2__mod_pow2_i64_44.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_44.eh
_mod_pow2__mod_pow2_i64_45.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_45.eh
_mod_pow2__mod_pow2_i64_46.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_46.eh
_mod_pow2__mod_pow2_i64_47.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_47.eh
_mod_pow2__mod_pow2_i64_48.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_48.eh
_mod_pow2__mod_pow2_i64_49.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_49.eh
_mod_pow2__mod_pow2_i64_50.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_50.eh
_mod_pow2__mod_pow2_i64_51.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_51.eh
_mod_pow2__mod_pow2_i64_52.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_52.eh
_mod_pow2__mod_pow2_i64_53.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_53.eh
_mod_pow2__mod_pow2_i64_54.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_54.eh
_mod_pow2__mod_pow2_i64_55.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_55.eh
_mod_pow2__mod_pow2_i64_56.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_56.eh
_mod_pow2__mod_pow2_i64_57.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_57.eh
_mod_pow2__mod_pow2_i64_58.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_58.eh
_mod_pow2__mod_pow2_i64_59.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_59.eh
_mod_pow2__mod_pow2_i64_60.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_60.eh
_mod_pow2__mod_pow2_i64_61.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_61.eh
_mod_pow2__mod_pow2_i64_62.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_62.eh
_mod_pow2__mod_pow2_i64_63.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_i64_63.eh
_mod_pow2__mod_pow2_u64_0.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_0.eh
_mod_pow2__mod_pow2_u64_1.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_1.eh
_mod_pow2__mod_pow2_u64_2.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_2.eh
_mod_pow2__mod_pow2_u64_3.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_3.eh
_mod_pow2__mod_pow2_u64_4.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_4.eh
_mod_pow2__mod_pow2_u64_5.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_5.eh
_mod_pow2__mod_pow2_u64_6.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_6.eh
_mod_pow2__mod_pow2_u64_7.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_7.eh
_mod_pow2__mod_pow2_u64_8.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_8.eh
_mod_pow2__mod_pow2_u64_9.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_9.eh
_mod_pow2__mod_pow2_u64_10.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_10.eh
_mod_pow2__mod_pow2_u64_11.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_11.eh
_mod_pow2__mod_pow2_u64_12.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_12.eh
_mod_pow2__mod_pow2_u64_13.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_13.eh
_mod_pow2__mod_pow2_u64_14.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_14.eh
_mod_pow2__mod_pow2_u64_15.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_15.eh
_mod_pow2__mod_pow2_u64_16.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_16.eh
_mod_pow2__mod_pow2_u64_17.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_17.eh
_mod_pow2__mod_pow2_u64_18.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_18.eh
_mod_pow2__mod_pow2_u64_19.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_19.eh
_mod_pow2__mod_pow2_u64_20.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_20.eh
_mod_pow2__mod_pow2_u64_21.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_21.eh
_mod_pow2__mod_pow2_u64_22.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_22.eh
_mod_pow2__mod_pow2_u64_23.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_23.eh
_mod_pow2__mod_pow2_u64_24.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_24.eh
_mod_pow2__mod_pow2_u64_25.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_25.eh
_mod_pow2__mod_pow2_u64_26.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_26.eh
_mod_pow2__mod_pow2_u64_27.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_27.eh
_mod_pow2__mod_pow2_u64_28.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_28.eh
_mod_pow2__mod_pow2_u64_29.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_29.eh
_mod_pow2__mod_pow2_u64_30.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_30.eh
_mod_pow2__mod_pow2_u64_31.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_31.eh
_mod_pow2__mod_pow2_u64_32.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_32.eh
_mod_pow2__mod_pow2_u64_33.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_33.eh
_mod_pow2__mod_pow2_u64_34.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_34.eh
_mod_pow2__mod_pow2_u64_35.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_35.eh
_mod_pow2__mod_pow2_u64_36.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_36.eh
_mod_pow2__mod_pow2_u64_37.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_37.eh
_mod_pow2__mod_pow2_u64_38.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_38.eh
_mod_pow2__mod_pow2_u64_39.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_39.eh
_mod_pow2__mod_pow2_u64_40.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_40.eh
_mod_pow2__mod_pow2_u64_41.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_41.eh
_mod_pow2__mod_pow2_u64_42.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_42.eh
_mod_pow2__mod_pow2_u64_43.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_43.eh
_mod_pow2__mod_pow2_u64_44.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_44.eh
_mod_pow2__mod_pow2_u64_45.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_45.eh
_mod_pow2__mod_pow2_u64_46.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_46.eh
_mod_pow2__mod_pow2_u64_47.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_47.eh
_mod_pow2__mod_pow2_u64_48.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_48.eh
_mod_pow2__mod_pow2_u64_49.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_49.eh
_mod_pow2__mod_pow2_u64_50.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_50.eh
_mod_pow2__mod_pow2_u64_51.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_51.eh
_mod_pow2__mod_pow2_u64_52.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_52.eh
_mod_pow2__mod_pow2_u64_53.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_53.eh
_mod_pow2__mod_pow2_u64_54.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_54.eh
_mod_pow2__mod_pow2_u64_55.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_55.eh
_mod_pow2__mod_pow2_u64_56.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_56.eh
_mod_pow2__mod_pow2_u64_57.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_57.eh
_mod_pow2__mod_pow2_u64_58.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_58.eh
_mod_pow2__mod_pow2_u64_59.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_59.eh
_mod_pow2__mod_pow2_u64_60.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_60.eh
_mod_pow2__mod_pow2_u64_61.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_61.eh
_mod_pow2__mod_pow2_u64_62.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_62.eh
_mod_pow2__mod_pow2_u64_63.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_u64_63.eh
_mod_pow2__mod_pow2_I_0.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_0.eh
_mod_pow2__mod_pow2_I_1.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_1.eh
_mod_pow2__mod_pow2_I_2.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_2.eh
_mod_pow2__mod_pow2_I_3.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_3.eh
_mod_pow2__mod_pow2_I_4.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_4.eh
_mod_pow2__mod_pow2_I_5.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_5.eh
_mod_pow2__mod_pow2_I_6.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_6.eh
_mod_pow2__mod_pow2_I_7.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_7.eh
_mod_pow2__mod_pow2_I_8.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_8.eh
_mod_pow2__mod_pow2_I_9.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_9.eh
_mod_pow2__mod_pow2_I_10.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_10.eh
_mod_pow2__mod_pow2_I_11.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_11.eh
_mod_pow2__mod_pow2_I_12.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_12.eh
_mod_pow2__mod_pow2_I_13.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_13.eh
_mod_pow2__mod_pow2_I_14.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_14.eh
_mod_pow2__mod_pow2_I_15.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_15.eh
_mod_pow2__mod_pow2_I_16.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_16.eh
_mod_pow2__mod_pow2_I_17.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_17.eh
_mod_pow2__mod_pow2_I_18.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_18.eh
_mod_pow2__mod_pow2_I_19.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_19.eh
_mod_pow2__mod_pow2_I_20.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_20.eh
_mod_pow2__mod_pow2_I_21.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_21.eh
_mod_pow2__mod_pow2_I_22.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_22.eh
_mod_pow2__mod_pow2_I_23.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_23.eh
_mod_pow2__mod_pow2_I_24.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_24.eh
_mod_pow2__mod_pow2_I_25.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_25.eh
_mod_pow2__mod_pow2_I_26.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_26.eh
_mod_pow2__mod_pow2_I_27.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_27.eh
_mod_pow2__mod_pow2_I_28.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_28.eh
_mod_pow2__mod_pow2_I_29.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_29.eh
_mod_pow2__mod_pow2_I_30.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_30.eh
_mod_pow2__mod_pow2_I_31.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_31.eh
_mod_pow2__mod_pow2_I_32.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_32.eh
_mod_pow2__mod_pow2_I_33.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_33.eh
_mod_pow2__mod_pow2_I_34.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_34.eh
_mod_pow2__mod_pow2_I_35.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_35.eh
_mod_pow2__mod_pow2_I_36.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_36.eh
_mod_pow2__mod_pow2_I_37.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_37.eh
_mod_pow2__mod_pow2_I_38.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_38.eh
_mod_pow2__mod_pow2_I_39.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_39.eh
_mod_pow2__mod_pow2_I_40.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_40.eh
_mod_pow2__mod_pow2_I_41.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_41.eh
_mod_pow2__mod_pow2_I_42.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_42.eh
_mod_pow2__mod_pow2_I_43.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_43.eh
_mod_pow2__mod_pow2_I_44.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_44.eh
_mod_pow2__mod_pow2_I_45.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_45.eh
_mod_pow2__mod_pow2_I_46.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_46.eh
_mod_pow2__mod_pow2_I_47.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_47.eh
_mod_pow2__mod_pow2_I_48.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_48.eh
_mod_pow2__mod_pow2_I_49.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_49.eh
_mod_pow2__mod_pow2_I_50.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_50.eh
_mod_pow2__mod_pow2_I_51.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_51.eh
_mod_pow2__mod_pow2_I_52.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_52.eh
_mod_pow2__mod_pow2_I_53.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_53.eh
_mod_pow2__mod_pow2_I_54.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_54.eh
_mod_pow2__mod_pow2_I_55.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_55.eh
_mod_pow2__mod_pow2_I_56.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_56.eh
_mod_pow2__mod_pow2_I_57.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_57.eh
_mod_pow2__mod_pow2_I_58.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_58.eh
_mod_pow2__mod_pow2_I_59.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_59.eh
_mod_pow2__mod_pow2_I_60.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_60.eh
_mod_pow2__mod_pow2_I_61.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_61.eh
_mod_pow2__mod_pow2_I_62.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_62.eh
_mod_pow2__mod_pow2_I_63.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_I_63.eh
_mod_pow2__mod_pow2_C_0.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_0.eh
_mod_pow2__mod_pow2_C_1.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_1.eh
_mod_pow2__mod_pow2_C_2.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_2.eh
_mod_pow2__mod_pow2_C_3.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_3.eh
_mod_pow2__mod_pow2_C_4.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_4.eh
_mod_pow2__mod_pow2_C_5.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_5.eh
_mod_pow2__mod_pow2_C_6.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_6.eh
_mod_pow2__mod_pow2_C_7.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_7.eh
_mod_pow2__mod_pow2_C_8.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_8.eh
_mod_pow2__mod_pow2_C_9.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_9.eh
_mod_pow2__mod_pow2_C_10.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_10.eh
_mod_pow2__mod_pow2_C_11.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_11.eh
_mod_pow2__mod_pow2_C_12.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_12.eh
_mod_pow2__mod_pow2_C_13.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_13.eh
_mod_pow2__mod_pow2_C_14.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_14.eh
_mod_pow2__mod_pow2_C_15.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_15.eh
_mod_pow2__mod_pow2_C_16.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_16.eh
_mod_pow2__mod_pow2_C_17.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_17.eh
_mod_pow2__mod_pow2_C_18.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_18.eh
_mod_pow2__mod_pow2_C_19.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_19.eh
_mod_pow2__mod_pow2_C_20.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_20.eh
_mod_pow2__mod_pow2_C_21.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_21.eh
_mod_pow2__mod_pow2_C_22.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_22.eh
_mod_pow2__mod_pow2_C_23.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_23.eh
_mod_pow2__mod_pow2_C_24.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_24.eh
_mod_pow2__mod_pow2_C_25.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_25.eh
_mod_pow2__mod_pow2_C_26.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_26.eh
_mod_pow2__mod_pow2_C_27.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_27.eh
_mod_pow2__mod_pow2_C_28.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_28.eh
_mod_pow2__mod_pow2_C_29.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_29.eh
_mod_pow2__mod_pow2_C_30.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_30.eh
_mod_pow2__mod_pow2_C_31.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_31.eh
_mod_pow2__mod_pow2_C_32.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_32.eh
_mod_pow2__mod_pow2_C_33.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_33.eh
_mod_pow2__mod_pow2_C_34.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_34.eh
_mod_pow2__mod_pow2_C_35.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_35.eh
_mod_pow2__mod_pow2_C_36.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_36.eh
_mod_pow2__mod_pow2_C_37.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_37.eh
_mod_pow2__mod_pow2_C_38.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_38.eh
_mod_pow2__mod_pow2_C_39.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_39.eh
_mod_pow2__mod_pow2_C_40.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_40.eh
_mod_pow2__mod_pow2_C_41.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_41.eh
_mod_pow2__mod_pow2_C_42.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_42.eh
_mod_pow2__mod_pow2_C_43.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_43.eh
_mod_pow2__mod_pow2_C_44.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_44.eh
_mod_pow2__mod_pow2_C_45.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_45.eh
_mod_pow2__mod_pow2_C_46.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_46.eh
_mod_pow2__mod_pow2_C_47.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_47.eh
_mod_pow2__mod_pow2_C_48.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_48.eh
_mod_pow2__mod_pow2_C_49.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_49.eh
_mod_pow2__mod_pow2_C_50.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_50.eh
_mod_pow2__mod_pow2_C_51.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_51.eh
_mod_pow2__mod_pow2_C_52.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_52.eh
_mod_pow2__mod_pow2_C_53.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_53.eh
_mod_pow2__mod_pow2_C_54.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_54.eh
_mod_pow2__mod_pow2_C_55.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_55.eh
_mod_pow2__mod_pow2_C_56.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_56.eh
_mod_pow2__mod_pow2_C_57.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_57.eh
_mod_pow2__mod_pow2_C_58.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_58.eh
_mod_pow2__mod_pow2_C_59.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_59.eh
_mod_pow2__mod_pow2_C_60.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_60.eh
_mod_pow2__mod_pow2_C_61.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_61.eh
_mod_pow2__mod_pow2_C_62.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_C_62.eh
_mod_pow2__mod_pow2_L_0.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_0.eh
_mod_pow2__mod_pow2_L_1.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_1.eh
_mod_pow2__mod_pow2_L_2.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_2.eh
_mod_pow2__mod_pow2_L_3.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_3.eh
_mod_pow2__mod_pow2_L_4.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_4.eh
_mod_pow2__mod_pow2_L_5.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_5.eh
_mod_pow2__mod_pow2_L_6.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_6.eh
_mod_pow2__mod_pow2_L_7.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_7.eh
_mod_pow2__mod_pow2_L_8.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_8.eh
_mod_pow2__mod_pow2_L_9.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_9.eh
_mod_pow2__mod_pow2_L_10.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_10.eh
_mod_pow2__mod_pow2_L_11.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_11.eh
_mod_pow2__mod_pow2_L_12.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_12.eh
_mod_pow2__mod_pow2_L_13.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_13.eh
_mod_pow2__mod_pow2_L_14.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_14.eh
_mod_pow2__mod_pow2_L_15.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_15.eh
_mod_pow2__mod_pow2_L_16.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_16.eh
_mod_pow2__mod_pow2_L_17.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_17.eh
_mod_pow2__mod_pow2_L_18.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_18.eh
_mod_pow2__mod_pow2_L_19.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_19.eh
_mod_pow2__mod_pow2_L_20.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_20.eh
_mod_pow2__mod_pow2_L_21.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_21.eh
_mod_pow2__mod_pow2_L_22.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_22.eh
_mod_pow2__mod_pow2_L_23.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_23.eh
_mod_pow2__mod_pow2_L_24.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_24.eh
_mod_pow2__mod_pow2_L_25.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_25.eh
_mod_pow2__mod_pow2_L_26.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_26.eh
_mod_pow2__mod_pow2_L_27.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_27.eh
_mod_pow2__mod_pow2_L_28.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_28.eh
_mod_pow2__mod_pow2_L_29.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_29.eh
_mod_pow2__mod_pow2_L_30.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_30.eh
_mod_pow2__mod_pow2_L_31.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_31.eh
_mod_pow2__mod_pow2_L_32.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_32.eh
_mod_pow2__mod_pow2_L_33.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_33.eh
_mod_pow2__mod_pow2_L_34.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_34.eh
_mod_pow2__mod_pow2_L_35.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_35.eh
_mod_pow2__mod_pow2_L_36.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_36.eh
_mod_pow2__mod_pow2_L_37.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_37.eh
_mod_pow2__mod_pow2_L_38.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_38.eh
_mod_pow2__mod_pow2_L_39.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_39.eh
_mod_pow2__mod_pow2_L_40.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_40.eh
_mod_pow2__mod_pow2_L_41.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_41.eh
_mod_pow2__mod_pow2_L_42.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_42.eh
_mod_pow2__mod_pow2_L_43.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_43.eh
_mod_pow2__mod_pow2_L_44.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_44.eh
_mod_pow2__mod_pow2_L_45.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_45.eh
_mod_pow2__mod_pow2_L_46.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_46.eh
_mod_pow2__mod_pow2_L_47.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_47.eh
_mod_pow2__mod_pow2_L_48.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_48.eh
_mod_pow2__mod_pow2_L_49.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_49.eh
_mod_pow2__mod_pow2_L_50.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_50.eh
_mod_pow2__mod_pow2_L_51.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_51.eh
_mod_pow2__mod_pow2_L_52.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_52.eh
_mod_pow2__mod_pow2_L_53.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_53.eh
_mod_pow2__mod_pow2_L_54.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_54.eh
_mod_pow2__mod_pow2_L_55.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_55.eh
_mod_pow2__mod_pow2_L_56.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_56.eh
_mod_pow2__mod_pow2_L_57.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_57.eh
_mod_pow2__mod_pow2_L_58.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_58.eh
_mod_pow2__mod_pow2_L_59.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_59.eh
_mod_pow2__mod_pow2_L_60.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_60.eh
_mod_pow2__mod_pow2_L_61.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_61.eh
_mod_pow2__mod_pow2_L_62.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_62.eh
_mod_pow2__mod_pow2_L_63.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_L_63.eh
_mod_pow2__mod_pow2_LC_0.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_0.eh
_mod_pow2__mod_pow2_LC_1.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_1.eh
_mod_pow2__mod_pow2_LC_2.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_2.eh
_mod_pow2__mod_pow2_LC_3.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_3.eh
_mod_pow2__mod_pow2_LC_4.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_4.eh
_mod_pow2__mod_pow2_LC_5.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_5.eh
_mod_pow2__mod_pow2_LC_6.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_6.eh
_mod_pow2__mod_pow2_LC_7.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_7.eh
_mod_pow2__mod_pow2_LC_8.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_8.eh
_mod_pow2__mod_pow2_LC_9.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_9.eh
_mod_pow2__mod_pow2_LC_10.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_10.eh
_mod_pow2__mod_pow2_LC_11.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_11.eh
_mod_pow2__mod_pow2_LC_12.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_12.eh
_mod_pow2__mod_pow2_LC_13.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_13.eh
_mod_pow2__mod_pow2_LC_14.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_14.eh
_mod_pow2__mod_pow2_LC_15.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_15.eh
_mod_pow2__mod_pow2_LC_16.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_16.eh
_mod_pow2__mod_pow2_LC_17.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_17.eh
_mod_pow2__mod_pow2_LC_18.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_18.eh
_mod_pow2__mod_pow2_LC_19.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_19.eh
_mod_pow2__mod_pow2_LC_20.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_20.eh
_mod_pow2__mod_pow2_LC_21.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_21.eh
_mod_pow2__mod_pow2_LC_22.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_22.eh
_mod_pow2__mod_pow2_LC_23.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_23.eh
_mod_pow2__mod_pow2_LC_24.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_24.eh
_mod_pow2__mod_pow2_LC_25.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_25.eh
_mod_pow2__mod_pow2_LC_26.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_26.eh
_mod_pow2__mod_pow2_LC_27.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_27.eh
_mod_pow2__mod_pow2_LC_28.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_28.eh
_mod_pow2__mod_pow2_LC_29.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_29.eh
_mod_pow2__mod_pow2_LC_30.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_30.eh
_mod_pow2__mod_pow2_LC_31.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_31.eh
_mod_pow2__mod_pow2_LC_32.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_32.eh
_mod_pow2__mod_pow2_LC_33.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_33.eh
_mod_pow2__mod_pow2_LC_34.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_34.eh
_mod_pow2__mod_pow2_LC_35.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_35.eh
_mod_pow2__mod_pow2_LC_36.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_36.eh
_mod_pow2__mod_pow2_LC_37.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_37.eh
_mod_pow2__mod_pow2_LC_38.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_38.eh
_mod_pow2__mod_pow2_LC_39.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_39.eh
_mod_pow2__mod_pow2_LC_40.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_40.eh
_mod_pow2__mod_pow2_LC_41.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_41.eh
_mod_pow2__mod_pow2_LC_42.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_42.eh
_mod_pow2__mod_pow2_LC_43.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_43.eh
_mod_pow2__mod_pow2_LC_44.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_44.eh
_mod_pow2__mod_pow2_LC_45.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_45.eh
_mod_pow2__mod_pow2_LC_46.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_46.eh
_mod_pow2__mod_pow2_LC_47.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_47.eh
_mod_pow2__mod_pow2_LC_48.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_48.eh
_mod_pow2__mod_pow2_LC_49.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_49.eh
_mod_pow2__mod_pow2_LC_50.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_50.eh
_mod_pow2__mod_pow2_LC_51.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_51.eh
_mod_pow2__mod_pow2_LC_52.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_52.eh
_mod_pow2__mod_pow2_LC_53.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_53.eh
_mod_pow2__mod_pow2_LC_54.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_54.eh
_mod_pow2__mod_pow2_LC_55.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_55.eh
_mod_pow2__mod_pow2_LC_56.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_56.eh
_mod_pow2__mod_pow2_LC_57.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_57.eh
_mod_pow2__mod_pow2_LC_58.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_58.eh
_mod_pow2__mod_pow2_LC_59.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_59.eh
_mod_pow2__mod_pow2_LC_60.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_60.eh
_mod_pow2__mod_pow2_LC_61.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_61.eh
_mod_pow2__mod_pow2_LC_62.eh = 0
.no_dead_strip _mod_pow2__mod_pow2_LC_62.eh
.globl _mod_pow2_M3.eh
_mod_pow2_M3.eh = 0
.no_dead_strip _mod_pow2_M3.eh
	.section __TEXT,__eh_frame,coalesced,no_toc+strip_static_syms+live_support
EH_frame1:
	.set L$set$0,LECIE1-LSCIE1
	.long L$set$0
LSCIE1:
	.long	0x0
	.byte	0x1
	.ascii "zR\0"
	.byte	0x1
	.byte	0x78
	.byte	0x10
	.byte	0x1
	.byte	0x10
	.byte	0xc
	.byte	0x7
	.byte	0x8
	.byte	0x90
	.byte	0x1
	.align 3
LECIE1:
_mod_pow2__mod_pow2_C_63.eh:
LSFDE1:
	.set L$set$1,LEFDE1-LASFDE1
	.long L$set$1
LASFDE1:
	.long	LASFDE1-EH_frame1
	.quad	LFB319-.
	.set L$set$2,LFE319-LFB319
	.quad L$set$2
	.byte	0x0
	.byte	0x4
	.set L$set$3,LCFI960-LFB319
	.long L$set$3
	.byte	0xe
	.byte	0x10
	.byte	0x86
	.byte	0x2
	.byte	0x4
	.set L$set$4,LCFI961-LCFI960
	.long L$set$4
	.byte	0xd
	.byte	0x6
	.byte	0x4
	.set L$set$5,LCFI963-LCFI961
	.long L$set$5
	.byte	0x83
	.byte	0x3
	.byte	0x4
	.set L$set$6,LCFI964-LCFI963
	.long L$set$6
	.byte	0xc
	.byte	0x7
	.byte	0x8
	.align 3
LEFDE1:
_mod_pow2__mod_pow2_LC_63.eh:
LSFDE3:
	.set L$set$7,LEFDE3-LASFDE3
	.long L$set$7
LASFDE3:
	.long	LASFDE3-EH_frame1
	.quad	LFB447-.
	.set L$set$8,LFE447-LFB447
	.quad L$set$8
	.byte	0x0
	.byte	0x4
	.set L$set$9,LCFI1347-LFB447
	.long L$set$9
	.byte	0xe
	.byte	0x10
	.byte	0x86
	.byte	0x2
	.byte	0x4
	.set L$set$10,LCFI1348-LCFI1347
	.long L$set$10
	.byte	0xd
	.byte	0x6
	.byte	0x4
	.set L$set$11,LCFI1350-LCFI1348
	.long L$set$11
	.byte	0x83
	.byte	0x3
	.byte	0x4
	.set L$set$12,LCFI1351-LCFI1350
	.long L$set$12
	.byte	0xc
	.byte	0x7
	.byte	0x8
	.align 3
LEFDE3:
__m3_fault.eh:
LSFDE5:
	.set L$set$13,LEFDE5-LASFDE5
	.long L$set$13
LASFDE5:
	.long	LASFDE5-EH_frame1
	.quad	LFB449-.
	.set L$set$14,LFE449-LFB449
	.quad L$set$14
	.byte	0x0
	.byte	0x4
	.set L$set$15,LCFI1355-LFB449
	.long L$set$15
	.byte	0xe
	.byte	0x10
	.byte	0x86
	.byte	0x2
	.byte	0x4
	.set L$set$16,LCFI1356-LCFI1355
	.long L$set$16
	.byte	0xd
	.byte	0x6
	.byte	0x4
	.set L$set$17,LCFI1358-LCFI1356
	.long L$set$17
	.byte	0xc
	.byte	0x7
	.byte	0x8
	.align 3
LEFDE5:
	.subsections_via_symbols
