	.text
.globl _mod_pow2__mod_pow2_i32_0
	.private_extern _mod_pow2__mod_pow2_i32_0
_mod_pow2__mod_pow2_i32_0:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	$0, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_1
	.private_extern _mod_pow2__mod_pow2_i32_1
_mod_pow2__mod_pow2_i32_1:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$1, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_2
	.private_extern _mod_pow2__mod_pow2_i32_2
_mod_pow2__mod_pow2_i32_2:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$3, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_3
	.private_extern _mod_pow2__mod_pow2_i32_3
_mod_pow2__mod_pow2_i32_3:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$7, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_4
	.private_extern _mod_pow2__mod_pow2_i32_4
_mod_pow2__mod_pow2_i32_4:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$15, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_5
	.private_extern _mod_pow2__mod_pow2_i32_5
_mod_pow2__mod_pow2_i32_5:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$31, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_6
	.private_extern _mod_pow2__mod_pow2_i32_6
_mod_pow2__mod_pow2_i32_6:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$63, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_7
	.private_extern _mod_pow2__mod_pow2_i32_7
_mod_pow2__mod_pow2_i32_7:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$127, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_8
	.private_extern _mod_pow2__mod_pow2_i32_8
_mod_pow2__mod_pow2_i32_8:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$255, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_9
	.private_extern _mod_pow2__mod_pow2_i32_9
_mod_pow2__mod_pow2_i32_9:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$511, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_10
	.private_extern _mod_pow2__mod_pow2_i32_10
_mod_pow2__mod_pow2_i32_10:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$1023, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_11
	.private_extern _mod_pow2__mod_pow2_i32_11
_mod_pow2__mod_pow2_i32_11:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$2047, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_12
	.private_extern _mod_pow2__mod_pow2_i32_12
_mod_pow2__mod_pow2_i32_12:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$4095, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_13
	.private_extern _mod_pow2__mod_pow2_i32_13
_mod_pow2__mod_pow2_i32_13:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$8191, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_14
	.private_extern _mod_pow2__mod_pow2_i32_14
_mod_pow2__mod_pow2_i32_14:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$16383, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_15
	.private_extern _mod_pow2__mod_pow2_i32_15
_mod_pow2__mod_pow2_i32_15:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$32767, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_16
	.private_extern _mod_pow2__mod_pow2_i32_16
_mod_pow2__mod_pow2_i32_16:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$65535, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_17
	.private_extern _mod_pow2__mod_pow2_i32_17
_mod_pow2__mod_pow2_i32_17:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$131071, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_18
	.private_extern _mod_pow2__mod_pow2_i32_18
_mod_pow2__mod_pow2_i32_18:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$262143, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_19
	.private_extern _mod_pow2__mod_pow2_i32_19
_mod_pow2__mod_pow2_i32_19:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$524287, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_20
	.private_extern _mod_pow2__mod_pow2_i32_20
_mod_pow2__mod_pow2_i32_20:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$1048575, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_21
	.private_extern _mod_pow2__mod_pow2_i32_21
_mod_pow2__mod_pow2_i32_21:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$2097151, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_22
	.private_extern _mod_pow2__mod_pow2_i32_22
_mod_pow2__mod_pow2_i32_22:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$4194303, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_23
	.private_extern _mod_pow2__mod_pow2_i32_23
_mod_pow2__mod_pow2_i32_23:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$8388607, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_24
	.private_extern _mod_pow2__mod_pow2_i32_24
_mod_pow2__mod_pow2_i32_24:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$16777215, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_25
	.private_extern _mod_pow2__mod_pow2_i32_25
_mod_pow2__mod_pow2_i32_25:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$33554431, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_26
	.private_extern _mod_pow2__mod_pow2_i32_26
_mod_pow2__mod_pow2_i32_26:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$67108863, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_27
	.private_extern _mod_pow2__mod_pow2_i32_27
_mod_pow2__mod_pow2_i32_27:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$134217727, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_28
	.private_extern _mod_pow2__mod_pow2_i32_28
_mod_pow2__mod_pow2_i32_28:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$268435455, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_29
	.private_extern _mod_pow2__mod_pow2_i32_29
_mod_pow2__mod_pow2_i32_29:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$536870911, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_30
	.private_extern _mod_pow2__mod_pow2_i32_30
_mod_pow2__mod_pow2_i32_30:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$1073741823, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i32_31
	.private_extern _mod_pow2__mod_pow2_i32_31
_mod_pow2__mod_pow2_i32_31:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	andl	$2147483647, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_0
	.private_extern _mod_pow2__mod_pow2_u32_0
_mod_pow2__mod_pow2_u32_0:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	$0, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_1
	.private_extern _mod_pow2__mod_pow2_u32_1
_mod_pow2__mod_pow2_u32_1:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$1, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_2
	.private_extern _mod_pow2__mod_pow2_u32_2
_mod_pow2__mod_pow2_u32_2:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$3, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_3
	.private_extern _mod_pow2__mod_pow2_u32_3
_mod_pow2__mod_pow2_u32_3:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$7, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_4
	.private_extern _mod_pow2__mod_pow2_u32_4
_mod_pow2__mod_pow2_u32_4:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$15, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_5
	.private_extern _mod_pow2__mod_pow2_u32_5
_mod_pow2__mod_pow2_u32_5:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$31, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_6
	.private_extern _mod_pow2__mod_pow2_u32_6
_mod_pow2__mod_pow2_u32_6:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$63, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_7
	.private_extern _mod_pow2__mod_pow2_u32_7
_mod_pow2__mod_pow2_u32_7:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$127, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_8
	.private_extern _mod_pow2__mod_pow2_u32_8
_mod_pow2__mod_pow2_u32_8:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$255, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_9
	.private_extern _mod_pow2__mod_pow2_u32_9
_mod_pow2__mod_pow2_u32_9:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$511, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_10
	.private_extern _mod_pow2__mod_pow2_u32_10
_mod_pow2__mod_pow2_u32_10:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$1023, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_11
	.private_extern _mod_pow2__mod_pow2_u32_11
_mod_pow2__mod_pow2_u32_11:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$2047, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_12
	.private_extern _mod_pow2__mod_pow2_u32_12
_mod_pow2__mod_pow2_u32_12:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$4095, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_13
	.private_extern _mod_pow2__mod_pow2_u32_13
_mod_pow2__mod_pow2_u32_13:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$8191, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_14
	.private_extern _mod_pow2__mod_pow2_u32_14
_mod_pow2__mod_pow2_u32_14:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$16383, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_15
	.private_extern _mod_pow2__mod_pow2_u32_15
_mod_pow2__mod_pow2_u32_15:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$32767, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_16
	.private_extern _mod_pow2__mod_pow2_u32_16
_mod_pow2__mod_pow2_u32_16:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$65535, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_17
	.private_extern _mod_pow2__mod_pow2_u32_17
_mod_pow2__mod_pow2_u32_17:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$131071, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_18
	.private_extern _mod_pow2__mod_pow2_u32_18
_mod_pow2__mod_pow2_u32_18:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$262143, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_19
	.private_extern _mod_pow2__mod_pow2_u32_19
_mod_pow2__mod_pow2_u32_19:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$524287, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_20
	.private_extern _mod_pow2__mod_pow2_u32_20
_mod_pow2__mod_pow2_u32_20:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$1048575, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_21
	.private_extern _mod_pow2__mod_pow2_u32_21
_mod_pow2__mod_pow2_u32_21:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$2097151, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_22
	.private_extern _mod_pow2__mod_pow2_u32_22
_mod_pow2__mod_pow2_u32_22:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$4194303, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_23
	.private_extern _mod_pow2__mod_pow2_u32_23
_mod_pow2__mod_pow2_u32_23:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$8388607, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_24
	.private_extern _mod_pow2__mod_pow2_u32_24
_mod_pow2__mod_pow2_u32_24:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$16777215, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_25
	.private_extern _mod_pow2__mod_pow2_u32_25
_mod_pow2__mod_pow2_u32_25:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$33554431, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_26
	.private_extern _mod_pow2__mod_pow2_u32_26
_mod_pow2__mod_pow2_u32_26:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$67108863, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_27
	.private_extern _mod_pow2__mod_pow2_u32_27
_mod_pow2__mod_pow2_u32_27:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$134217727, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_28
	.private_extern _mod_pow2__mod_pow2_u32_28
_mod_pow2__mod_pow2_u32_28:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$268435455, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_29
	.private_extern _mod_pow2__mod_pow2_u32_29
_mod_pow2__mod_pow2_u32_29:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$536870911, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_30
	.private_extern _mod_pow2__mod_pow2_u32_30
_mod_pow2__mod_pow2_u32_30:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$1073741823, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u32_31
	.private_extern _mod_pow2__mod_pow2_u32_31
_mod_pow2__mod_pow2_u32_31:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	andl	$2147483647, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_0
	.private_extern _mod_pow2__mod_pow2_i64_0
_mod_pow2__mod_pow2_i64_0:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movl	$0, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_1
	.private_extern _mod_pow2__mod_pow2_i64_1
_mod_pow2__mod_pow2_i64_1:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_2
	.private_extern _mod_pow2__mod_pow2_i64_2
_mod_pow2__mod_pow2_i64_2:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$3, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_3
	.private_extern _mod_pow2__mod_pow2_i64_3
_mod_pow2__mod_pow2_i64_3:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$7, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_4
	.private_extern _mod_pow2__mod_pow2_i64_4
_mod_pow2__mod_pow2_i64_4:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$15, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_5
	.private_extern _mod_pow2__mod_pow2_i64_5
_mod_pow2__mod_pow2_i64_5:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$31, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_6
	.private_extern _mod_pow2__mod_pow2_i64_6
_mod_pow2__mod_pow2_i64_6:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$63, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_7
	.private_extern _mod_pow2__mod_pow2_i64_7
_mod_pow2__mod_pow2_i64_7:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$127, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_8
	.private_extern _mod_pow2__mod_pow2_i64_8
_mod_pow2__mod_pow2_i64_8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$255, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_9
	.private_extern _mod_pow2__mod_pow2_i64_9
_mod_pow2__mod_pow2_i64_9:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$511, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_10
	.private_extern _mod_pow2__mod_pow2_i64_10
_mod_pow2__mod_pow2_i64_10:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1023, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_11
	.private_extern _mod_pow2__mod_pow2_i64_11
_mod_pow2__mod_pow2_i64_11:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2047, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_12
	.private_extern _mod_pow2__mod_pow2_i64_12
_mod_pow2__mod_pow2_i64_12:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4095, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_13
	.private_extern _mod_pow2__mod_pow2_i64_13
_mod_pow2__mod_pow2_i64_13:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$8191, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_14
	.private_extern _mod_pow2__mod_pow2_i64_14
_mod_pow2__mod_pow2_i64_14:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$16383, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_15
	.private_extern _mod_pow2__mod_pow2_i64_15
_mod_pow2__mod_pow2_i64_15:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$32767, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_16
	.private_extern _mod_pow2__mod_pow2_i64_16
_mod_pow2__mod_pow2_i64_16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$65535, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_17
	.private_extern _mod_pow2__mod_pow2_i64_17
_mod_pow2__mod_pow2_i64_17:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$131071, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_18
	.private_extern _mod_pow2__mod_pow2_i64_18
_mod_pow2__mod_pow2_i64_18:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$262143, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_19
	.private_extern _mod_pow2__mod_pow2_i64_19
_mod_pow2__mod_pow2_i64_19:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$524287, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_20
	.private_extern _mod_pow2__mod_pow2_i64_20
_mod_pow2__mod_pow2_i64_20:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1048575, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_21
	.private_extern _mod_pow2__mod_pow2_i64_21
_mod_pow2__mod_pow2_i64_21:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2097151, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_22
	.private_extern _mod_pow2__mod_pow2_i64_22
_mod_pow2__mod_pow2_i64_22:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4194303, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_23
	.private_extern _mod_pow2__mod_pow2_i64_23
_mod_pow2__mod_pow2_i64_23:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$8388607, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_24
	.private_extern _mod_pow2__mod_pow2_i64_24
_mod_pow2__mod_pow2_i64_24:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$16777215, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_25
	.private_extern _mod_pow2__mod_pow2_i64_25
_mod_pow2__mod_pow2_i64_25:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$33554431, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_26
	.private_extern _mod_pow2__mod_pow2_i64_26
_mod_pow2__mod_pow2_i64_26:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$67108863, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_27
	.private_extern _mod_pow2__mod_pow2_i64_27
_mod_pow2__mod_pow2_i64_27:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$134217727, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_28
	.private_extern _mod_pow2__mod_pow2_i64_28
_mod_pow2__mod_pow2_i64_28:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$268435455, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_29
	.private_extern _mod_pow2__mod_pow2_i64_29
_mod_pow2__mod_pow2_i64_29:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$536870911, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_30
	.private_extern _mod_pow2__mod_pow2_i64_30
_mod_pow2__mod_pow2_i64_30:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1073741823, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_31
	.private_extern _mod_pow2__mod_pow2_i64_31
_mod_pow2__mod_pow2_i64_31:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2147483647, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_32
	.private_extern _mod_pow2__mod_pow2_i64_32
_mod_pow2__mod_pow2_i64_32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4294967295, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_33
	.private_extern _mod_pow2__mod_pow2_i64_33
_mod_pow2__mod_pow2_i64_33:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$8589934591, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_34
	.private_extern _mod_pow2__mod_pow2_i64_34
_mod_pow2__mod_pow2_i64_34:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$17179869183, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_35
	.private_extern _mod_pow2__mod_pow2_i64_35
_mod_pow2__mod_pow2_i64_35:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$34359738367, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_36
	.private_extern _mod_pow2__mod_pow2_i64_36
_mod_pow2__mod_pow2_i64_36:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$68719476735, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_37
	.private_extern _mod_pow2__mod_pow2_i64_37
_mod_pow2__mod_pow2_i64_37:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$137438953471, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_38
	.private_extern _mod_pow2__mod_pow2_i64_38
_mod_pow2__mod_pow2_i64_38:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$274877906943, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_39
	.private_extern _mod_pow2__mod_pow2_i64_39
_mod_pow2__mod_pow2_i64_39:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$549755813887, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_40
	.private_extern _mod_pow2__mod_pow2_i64_40
_mod_pow2__mod_pow2_i64_40:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1099511627775, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_41
	.private_extern _mod_pow2__mod_pow2_i64_41
_mod_pow2__mod_pow2_i64_41:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2199023255551, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_42
	.private_extern _mod_pow2__mod_pow2_i64_42
_mod_pow2__mod_pow2_i64_42:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4398046511103, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_43
	.private_extern _mod_pow2__mod_pow2_i64_43
_mod_pow2__mod_pow2_i64_43:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$8796093022207, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_44
	.private_extern _mod_pow2__mod_pow2_i64_44
_mod_pow2__mod_pow2_i64_44:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$17592186044415, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_45
	.private_extern _mod_pow2__mod_pow2_i64_45
_mod_pow2__mod_pow2_i64_45:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$35184372088831, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_46
	.private_extern _mod_pow2__mod_pow2_i64_46
_mod_pow2__mod_pow2_i64_46:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$70368744177663, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_47
	.private_extern _mod_pow2__mod_pow2_i64_47
_mod_pow2__mod_pow2_i64_47:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$140737488355327, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_48
	.private_extern _mod_pow2__mod_pow2_i64_48
_mod_pow2__mod_pow2_i64_48:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$281474976710655, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_49
	.private_extern _mod_pow2__mod_pow2_i64_49
_mod_pow2__mod_pow2_i64_49:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$562949953421311, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_50
	.private_extern _mod_pow2__mod_pow2_i64_50
_mod_pow2__mod_pow2_i64_50:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1125899906842623, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_51
	.private_extern _mod_pow2__mod_pow2_i64_51
_mod_pow2__mod_pow2_i64_51:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2251799813685247, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_52
	.private_extern _mod_pow2__mod_pow2_i64_52
_mod_pow2__mod_pow2_i64_52:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4503599627370495, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_53
	.private_extern _mod_pow2__mod_pow2_i64_53
_mod_pow2__mod_pow2_i64_53:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$9007199254740991, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_54
	.private_extern _mod_pow2__mod_pow2_i64_54
_mod_pow2__mod_pow2_i64_54:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$18014398509481983, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_55
	.private_extern _mod_pow2__mod_pow2_i64_55
_mod_pow2__mod_pow2_i64_55:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$36028797018963967, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_56
	.private_extern _mod_pow2__mod_pow2_i64_56
_mod_pow2__mod_pow2_i64_56:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$72057594037927935, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_57
	.private_extern _mod_pow2__mod_pow2_i64_57
_mod_pow2__mod_pow2_i64_57:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$144115188075855871, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_58
	.private_extern _mod_pow2__mod_pow2_i64_58
_mod_pow2__mod_pow2_i64_58:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$288230376151711743, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_59
	.private_extern _mod_pow2__mod_pow2_i64_59
_mod_pow2__mod_pow2_i64_59:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$576460752303423487, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_60
	.private_extern _mod_pow2__mod_pow2_i64_60
_mod_pow2__mod_pow2_i64_60:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1152921504606846975, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_61
	.private_extern _mod_pow2__mod_pow2_i64_61
_mod_pow2__mod_pow2_i64_61:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2305843009213693951, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_62
	.private_extern _mod_pow2__mod_pow2_i64_62
_mod_pow2__mod_pow2_i64_62:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4611686018427387903, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_i64_63
	.private_extern _mod_pow2__mod_pow2_i64_63
_mod_pow2__mod_pow2_i64_63:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rcx
	leaq	-1(%rcx), %rdx
	movq	%rcx, %rax
	orq	%rdx, %rax
	movq	%rax, %rsi
	sarq	$63, %rsi
	subq	%rsi, %rdx
	movabsq	$-9223372036854775808, %rax
	cmpq	%rax, %rdx
	sete	%al
	movzbl	%al, %edx
	movq	%rsi, %rax
	notq	%rax
	leaq	(%rdx,%rax), %rax
	salq	$63, %rax
	movq	%rcx, %rdx
	subq	%rax, %rdx
	movq	%rdx, %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_0
	.private_extern _mod_pow2__mod_pow2_u64_0
_mod_pow2__mod_pow2_u64_0:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movl	$0, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_1
	.private_extern _mod_pow2__mod_pow2_u64_1
_mod_pow2__mod_pow2_u64_1:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_2
	.private_extern _mod_pow2__mod_pow2_u64_2
_mod_pow2__mod_pow2_u64_2:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$3, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_3
	.private_extern _mod_pow2__mod_pow2_u64_3
_mod_pow2__mod_pow2_u64_3:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$7, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_4
	.private_extern _mod_pow2__mod_pow2_u64_4
_mod_pow2__mod_pow2_u64_4:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$15, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_5
	.private_extern _mod_pow2__mod_pow2_u64_5
_mod_pow2__mod_pow2_u64_5:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$31, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_6
	.private_extern _mod_pow2__mod_pow2_u64_6
_mod_pow2__mod_pow2_u64_6:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$63, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_7
	.private_extern _mod_pow2__mod_pow2_u64_7
_mod_pow2__mod_pow2_u64_7:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$127, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_8
	.private_extern _mod_pow2__mod_pow2_u64_8
_mod_pow2__mod_pow2_u64_8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$255, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_9
	.private_extern _mod_pow2__mod_pow2_u64_9
_mod_pow2__mod_pow2_u64_9:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$511, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_10
	.private_extern _mod_pow2__mod_pow2_u64_10
_mod_pow2__mod_pow2_u64_10:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1023, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_11
	.private_extern _mod_pow2__mod_pow2_u64_11
_mod_pow2__mod_pow2_u64_11:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2047, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_12
	.private_extern _mod_pow2__mod_pow2_u64_12
_mod_pow2__mod_pow2_u64_12:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4095, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_13
	.private_extern _mod_pow2__mod_pow2_u64_13
_mod_pow2__mod_pow2_u64_13:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$8191, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_14
	.private_extern _mod_pow2__mod_pow2_u64_14
_mod_pow2__mod_pow2_u64_14:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$16383, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_15
	.private_extern _mod_pow2__mod_pow2_u64_15
_mod_pow2__mod_pow2_u64_15:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$32767, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_16
	.private_extern _mod_pow2__mod_pow2_u64_16
_mod_pow2__mod_pow2_u64_16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$65535, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_17
	.private_extern _mod_pow2__mod_pow2_u64_17
_mod_pow2__mod_pow2_u64_17:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$131071, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_18
	.private_extern _mod_pow2__mod_pow2_u64_18
_mod_pow2__mod_pow2_u64_18:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$262143, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_19
	.private_extern _mod_pow2__mod_pow2_u64_19
_mod_pow2__mod_pow2_u64_19:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$524287, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_20
	.private_extern _mod_pow2__mod_pow2_u64_20
_mod_pow2__mod_pow2_u64_20:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1048575, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_21
	.private_extern _mod_pow2__mod_pow2_u64_21
_mod_pow2__mod_pow2_u64_21:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2097151, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_22
	.private_extern _mod_pow2__mod_pow2_u64_22
_mod_pow2__mod_pow2_u64_22:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4194303, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_23
	.private_extern _mod_pow2__mod_pow2_u64_23
_mod_pow2__mod_pow2_u64_23:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$8388607, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_24
	.private_extern _mod_pow2__mod_pow2_u64_24
_mod_pow2__mod_pow2_u64_24:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$16777215, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_25
	.private_extern _mod_pow2__mod_pow2_u64_25
_mod_pow2__mod_pow2_u64_25:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$33554431, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_26
	.private_extern _mod_pow2__mod_pow2_u64_26
_mod_pow2__mod_pow2_u64_26:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$67108863, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_27
	.private_extern _mod_pow2__mod_pow2_u64_27
_mod_pow2__mod_pow2_u64_27:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$134217727, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_28
	.private_extern _mod_pow2__mod_pow2_u64_28
_mod_pow2__mod_pow2_u64_28:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$268435455, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_29
	.private_extern _mod_pow2__mod_pow2_u64_29
_mod_pow2__mod_pow2_u64_29:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$536870911, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_30
	.private_extern _mod_pow2__mod_pow2_u64_30
_mod_pow2__mod_pow2_u64_30:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1073741823, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_31
	.private_extern _mod_pow2__mod_pow2_u64_31
_mod_pow2__mod_pow2_u64_31:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2147483647, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_32
	.private_extern _mod_pow2__mod_pow2_u64_32
_mod_pow2__mod_pow2_u64_32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4294967295, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_33
	.private_extern _mod_pow2__mod_pow2_u64_33
_mod_pow2__mod_pow2_u64_33:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$8589934591, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_34
	.private_extern _mod_pow2__mod_pow2_u64_34
_mod_pow2__mod_pow2_u64_34:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$17179869183, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_35
	.private_extern _mod_pow2__mod_pow2_u64_35
_mod_pow2__mod_pow2_u64_35:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$34359738367, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_36
	.private_extern _mod_pow2__mod_pow2_u64_36
_mod_pow2__mod_pow2_u64_36:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$68719476735, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_37
	.private_extern _mod_pow2__mod_pow2_u64_37
_mod_pow2__mod_pow2_u64_37:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$137438953471, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_38
	.private_extern _mod_pow2__mod_pow2_u64_38
_mod_pow2__mod_pow2_u64_38:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$274877906943, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_39
	.private_extern _mod_pow2__mod_pow2_u64_39
_mod_pow2__mod_pow2_u64_39:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$549755813887, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_40
	.private_extern _mod_pow2__mod_pow2_u64_40
_mod_pow2__mod_pow2_u64_40:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1099511627775, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_41
	.private_extern _mod_pow2__mod_pow2_u64_41
_mod_pow2__mod_pow2_u64_41:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2199023255551, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_42
	.private_extern _mod_pow2__mod_pow2_u64_42
_mod_pow2__mod_pow2_u64_42:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4398046511103, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_43
	.private_extern _mod_pow2__mod_pow2_u64_43
_mod_pow2__mod_pow2_u64_43:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$8796093022207, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_44
	.private_extern _mod_pow2__mod_pow2_u64_44
_mod_pow2__mod_pow2_u64_44:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$17592186044415, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_45
	.private_extern _mod_pow2__mod_pow2_u64_45
_mod_pow2__mod_pow2_u64_45:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$35184372088831, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_46
	.private_extern _mod_pow2__mod_pow2_u64_46
_mod_pow2__mod_pow2_u64_46:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$70368744177663, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_47
	.private_extern _mod_pow2__mod_pow2_u64_47
_mod_pow2__mod_pow2_u64_47:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$140737488355327, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_48
	.private_extern _mod_pow2__mod_pow2_u64_48
_mod_pow2__mod_pow2_u64_48:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$281474976710655, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_49
	.private_extern _mod_pow2__mod_pow2_u64_49
_mod_pow2__mod_pow2_u64_49:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$562949953421311, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_50
	.private_extern _mod_pow2__mod_pow2_u64_50
_mod_pow2__mod_pow2_u64_50:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1125899906842623, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_51
	.private_extern _mod_pow2__mod_pow2_u64_51
_mod_pow2__mod_pow2_u64_51:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2251799813685247, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_52
	.private_extern _mod_pow2__mod_pow2_u64_52
_mod_pow2__mod_pow2_u64_52:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4503599627370495, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_53
	.private_extern _mod_pow2__mod_pow2_u64_53
_mod_pow2__mod_pow2_u64_53:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$9007199254740991, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_54
	.private_extern _mod_pow2__mod_pow2_u64_54
_mod_pow2__mod_pow2_u64_54:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$18014398509481983, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_55
	.private_extern _mod_pow2__mod_pow2_u64_55
_mod_pow2__mod_pow2_u64_55:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$36028797018963967, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_56
	.private_extern _mod_pow2__mod_pow2_u64_56
_mod_pow2__mod_pow2_u64_56:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$72057594037927935, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_57
	.private_extern _mod_pow2__mod_pow2_u64_57
_mod_pow2__mod_pow2_u64_57:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$144115188075855871, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_58
	.private_extern _mod_pow2__mod_pow2_u64_58
_mod_pow2__mod_pow2_u64_58:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$288230376151711743, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_59
	.private_extern _mod_pow2__mod_pow2_u64_59
_mod_pow2__mod_pow2_u64_59:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$576460752303423487, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_60
	.private_extern _mod_pow2__mod_pow2_u64_60
_mod_pow2__mod_pow2_u64_60:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1152921504606846975, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_61
	.private_extern _mod_pow2__mod_pow2_u64_61
_mod_pow2__mod_pow2_u64_61:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2305843009213693951, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_62
	.private_extern _mod_pow2__mod_pow2_u64_62
_mod_pow2__mod_pow2_u64_62:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4611686018427387903, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_u64_63
	.private_extern _mod_pow2__mod_pow2_u64_63
_mod_pow2__mod_pow2_u64_63:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rcx
	leaq	-1(%rcx), %rdx
	movq	%rcx, %rax
	orq	%rdx, %rax
	movq	%rax, %rsi
	sarq	$63, %rsi
	subq	%rsi, %rdx
	movabsq	$-9223372036854775808, %rax
	cmpq	%rax, %rdx
	sete	%al
	movzbl	%al, %edx
	movq	%rsi, %rax
	notq	%rax
	leaq	(%rdx,%rax), %rax
	salq	$63, %rax
	movq	%rcx, %rdx
	subq	%rax, %rdx
	movq	%rdx, %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_0
	.private_extern _mod_pow2__mod_pow2_I_0
_mod_pow2__mod_pow2_I_0:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movl	$0, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_1
	.private_extern _mod_pow2__mod_pow2_I_1
_mod_pow2__mod_pow2_I_1:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_2
	.private_extern _mod_pow2__mod_pow2_I_2
_mod_pow2__mod_pow2_I_2:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$3, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_3
	.private_extern _mod_pow2__mod_pow2_I_3
_mod_pow2__mod_pow2_I_3:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$7, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_4
	.private_extern _mod_pow2__mod_pow2_I_4
_mod_pow2__mod_pow2_I_4:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$15, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_5
	.private_extern _mod_pow2__mod_pow2_I_5
_mod_pow2__mod_pow2_I_5:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$31, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_6
	.private_extern _mod_pow2__mod_pow2_I_6
_mod_pow2__mod_pow2_I_6:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$63, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_7
	.private_extern _mod_pow2__mod_pow2_I_7
_mod_pow2__mod_pow2_I_7:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$127, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_8
	.private_extern _mod_pow2__mod_pow2_I_8
_mod_pow2__mod_pow2_I_8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$255, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_9
	.private_extern _mod_pow2__mod_pow2_I_9
_mod_pow2__mod_pow2_I_9:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$511, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_10
	.private_extern _mod_pow2__mod_pow2_I_10
_mod_pow2__mod_pow2_I_10:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1023, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_11
	.private_extern _mod_pow2__mod_pow2_I_11
_mod_pow2__mod_pow2_I_11:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2047, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_12
	.private_extern _mod_pow2__mod_pow2_I_12
_mod_pow2__mod_pow2_I_12:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4095, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_13
	.private_extern _mod_pow2__mod_pow2_I_13
_mod_pow2__mod_pow2_I_13:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$8191, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_14
	.private_extern _mod_pow2__mod_pow2_I_14
_mod_pow2__mod_pow2_I_14:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$16383, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_15
	.private_extern _mod_pow2__mod_pow2_I_15
_mod_pow2__mod_pow2_I_15:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$32767, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_16
	.private_extern _mod_pow2__mod_pow2_I_16
_mod_pow2__mod_pow2_I_16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$65535, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_17
	.private_extern _mod_pow2__mod_pow2_I_17
_mod_pow2__mod_pow2_I_17:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$131071, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_18
	.private_extern _mod_pow2__mod_pow2_I_18
_mod_pow2__mod_pow2_I_18:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$262143, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_19
	.private_extern _mod_pow2__mod_pow2_I_19
_mod_pow2__mod_pow2_I_19:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$524287, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_20
	.private_extern _mod_pow2__mod_pow2_I_20
_mod_pow2__mod_pow2_I_20:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1048575, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_21
	.private_extern _mod_pow2__mod_pow2_I_21
_mod_pow2__mod_pow2_I_21:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2097151, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_22
	.private_extern _mod_pow2__mod_pow2_I_22
_mod_pow2__mod_pow2_I_22:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4194303, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_23
	.private_extern _mod_pow2__mod_pow2_I_23
_mod_pow2__mod_pow2_I_23:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$8388607, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_24
	.private_extern _mod_pow2__mod_pow2_I_24
_mod_pow2__mod_pow2_I_24:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$16777215, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_25
	.private_extern _mod_pow2__mod_pow2_I_25
_mod_pow2__mod_pow2_I_25:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$33554431, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_26
	.private_extern _mod_pow2__mod_pow2_I_26
_mod_pow2__mod_pow2_I_26:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$67108863, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_27
	.private_extern _mod_pow2__mod_pow2_I_27
_mod_pow2__mod_pow2_I_27:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$134217727, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_28
	.private_extern _mod_pow2__mod_pow2_I_28
_mod_pow2__mod_pow2_I_28:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$268435455, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_29
	.private_extern _mod_pow2__mod_pow2_I_29
_mod_pow2__mod_pow2_I_29:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$536870911, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_30
	.private_extern _mod_pow2__mod_pow2_I_30
_mod_pow2__mod_pow2_I_30:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1073741823, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_31
	.private_extern _mod_pow2__mod_pow2_I_31
_mod_pow2__mod_pow2_I_31:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2147483647, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_32
	.private_extern _mod_pow2__mod_pow2_I_32
_mod_pow2__mod_pow2_I_32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4294967295, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_33
	.private_extern _mod_pow2__mod_pow2_I_33
_mod_pow2__mod_pow2_I_33:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$8589934591, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_34
	.private_extern _mod_pow2__mod_pow2_I_34
_mod_pow2__mod_pow2_I_34:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$17179869183, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_35
	.private_extern _mod_pow2__mod_pow2_I_35
_mod_pow2__mod_pow2_I_35:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$34359738367, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_36
	.private_extern _mod_pow2__mod_pow2_I_36
_mod_pow2__mod_pow2_I_36:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$68719476735, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_37
	.private_extern _mod_pow2__mod_pow2_I_37
_mod_pow2__mod_pow2_I_37:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$137438953471, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_38
	.private_extern _mod_pow2__mod_pow2_I_38
_mod_pow2__mod_pow2_I_38:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$274877906943, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_39
	.private_extern _mod_pow2__mod_pow2_I_39
_mod_pow2__mod_pow2_I_39:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$549755813887, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_40
	.private_extern _mod_pow2__mod_pow2_I_40
_mod_pow2__mod_pow2_I_40:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1099511627775, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_41
	.private_extern _mod_pow2__mod_pow2_I_41
_mod_pow2__mod_pow2_I_41:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2199023255551, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_42
	.private_extern _mod_pow2__mod_pow2_I_42
_mod_pow2__mod_pow2_I_42:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4398046511103, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_43
	.private_extern _mod_pow2__mod_pow2_I_43
_mod_pow2__mod_pow2_I_43:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$8796093022207, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_44
	.private_extern _mod_pow2__mod_pow2_I_44
_mod_pow2__mod_pow2_I_44:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$17592186044415, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_45
	.private_extern _mod_pow2__mod_pow2_I_45
_mod_pow2__mod_pow2_I_45:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$35184372088831, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_46
	.private_extern _mod_pow2__mod_pow2_I_46
_mod_pow2__mod_pow2_I_46:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$70368744177663, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_47
	.private_extern _mod_pow2__mod_pow2_I_47
_mod_pow2__mod_pow2_I_47:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$140737488355327, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_48
	.private_extern _mod_pow2__mod_pow2_I_48
_mod_pow2__mod_pow2_I_48:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$281474976710655, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_49
	.private_extern _mod_pow2__mod_pow2_I_49
_mod_pow2__mod_pow2_I_49:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$562949953421311, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_50
	.private_extern _mod_pow2__mod_pow2_I_50
_mod_pow2__mod_pow2_I_50:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1125899906842623, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_51
	.private_extern _mod_pow2__mod_pow2_I_51
_mod_pow2__mod_pow2_I_51:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2251799813685247, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_52
	.private_extern _mod_pow2__mod_pow2_I_52
_mod_pow2__mod_pow2_I_52:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4503599627370495, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_53
	.private_extern _mod_pow2__mod_pow2_I_53
_mod_pow2__mod_pow2_I_53:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$9007199254740991, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_54
	.private_extern _mod_pow2__mod_pow2_I_54
_mod_pow2__mod_pow2_I_54:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$18014398509481983, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_55
	.private_extern _mod_pow2__mod_pow2_I_55
_mod_pow2__mod_pow2_I_55:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$36028797018963967, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_56
	.private_extern _mod_pow2__mod_pow2_I_56
_mod_pow2__mod_pow2_I_56:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$72057594037927935, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_57
	.private_extern _mod_pow2__mod_pow2_I_57
_mod_pow2__mod_pow2_I_57:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$144115188075855871, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_58
	.private_extern _mod_pow2__mod_pow2_I_58
_mod_pow2__mod_pow2_I_58:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$288230376151711743, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_59
	.private_extern _mod_pow2__mod_pow2_I_59
_mod_pow2__mod_pow2_I_59:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$576460752303423487, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_60
	.private_extern _mod_pow2__mod_pow2_I_60
_mod_pow2__mod_pow2_I_60:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1152921504606846975, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_61
	.private_extern _mod_pow2__mod_pow2_I_61
_mod_pow2__mod_pow2_I_61:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2305843009213693951, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_62
	.private_extern _mod_pow2__mod_pow2_I_62
_mod_pow2__mod_pow2_I_62:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4611686018427387903, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_I_63
	.private_extern _mod_pow2__mod_pow2_I_63
_mod_pow2__mod_pow2_I_63:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rcx
	leaq	-1(%rcx), %rdx
	movq	%rcx, %rax
	orq	%rdx, %rax
	movq	%rax, %rsi
	sarq	$63, %rsi
	subq	%rsi, %rdx
	movabsq	$-9223372036854775808, %rax
	cmpq	%rax, %rdx
	sete	%al
	movzbl	%al, %edx
	movq	%rsi, %rax
	notq	%rax
	leaq	(%rdx,%rax), %rax
	salq	$63, %rax
	movq	%rcx, %rdx
	subq	%rax, %rdx
	movq	%rdx, %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_0
	.private_extern _mod_pow2__mod_pow2_C_0
_mod_pow2__mod_pow2_C_0:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movl	$0, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_1
	.private_extern _mod_pow2__mod_pow2_C_1
_mod_pow2__mod_pow2_C_1:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_2
	.private_extern _mod_pow2__mod_pow2_C_2
_mod_pow2__mod_pow2_C_2:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$3, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_3
	.private_extern _mod_pow2__mod_pow2_C_3
_mod_pow2__mod_pow2_C_3:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$7, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_4
	.private_extern _mod_pow2__mod_pow2_C_4
_mod_pow2__mod_pow2_C_4:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$15, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_5
	.private_extern _mod_pow2__mod_pow2_C_5
_mod_pow2__mod_pow2_C_5:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$31, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_6
	.private_extern _mod_pow2__mod_pow2_C_6
_mod_pow2__mod_pow2_C_6:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$63, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_7
	.private_extern _mod_pow2__mod_pow2_C_7
_mod_pow2__mod_pow2_C_7:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$127, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_8
	.private_extern _mod_pow2__mod_pow2_C_8
_mod_pow2__mod_pow2_C_8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$255, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_9
	.private_extern _mod_pow2__mod_pow2_C_9
_mod_pow2__mod_pow2_C_9:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$511, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_10
	.private_extern _mod_pow2__mod_pow2_C_10
_mod_pow2__mod_pow2_C_10:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1023, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_11
	.private_extern _mod_pow2__mod_pow2_C_11
_mod_pow2__mod_pow2_C_11:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2047, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_12
	.private_extern _mod_pow2__mod_pow2_C_12
_mod_pow2__mod_pow2_C_12:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4095, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_13
	.private_extern _mod_pow2__mod_pow2_C_13
_mod_pow2__mod_pow2_C_13:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$8191, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_14
	.private_extern _mod_pow2__mod_pow2_C_14
_mod_pow2__mod_pow2_C_14:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$16383, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_15
	.private_extern _mod_pow2__mod_pow2_C_15
_mod_pow2__mod_pow2_C_15:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$32767, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_16
	.private_extern _mod_pow2__mod_pow2_C_16
_mod_pow2__mod_pow2_C_16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$65535, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_17
	.private_extern _mod_pow2__mod_pow2_C_17
_mod_pow2__mod_pow2_C_17:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$131071, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_18
	.private_extern _mod_pow2__mod_pow2_C_18
_mod_pow2__mod_pow2_C_18:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$262143, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_19
	.private_extern _mod_pow2__mod_pow2_C_19
_mod_pow2__mod_pow2_C_19:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$524287, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_20
	.private_extern _mod_pow2__mod_pow2_C_20
_mod_pow2__mod_pow2_C_20:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1048575, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_21
	.private_extern _mod_pow2__mod_pow2_C_21
_mod_pow2__mod_pow2_C_21:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2097151, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_22
	.private_extern _mod_pow2__mod_pow2_C_22
_mod_pow2__mod_pow2_C_22:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4194303, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_23
	.private_extern _mod_pow2__mod_pow2_C_23
_mod_pow2__mod_pow2_C_23:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$8388607, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_24
	.private_extern _mod_pow2__mod_pow2_C_24
_mod_pow2__mod_pow2_C_24:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$16777215, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_25
	.private_extern _mod_pow2__mod_pow2_C_25
_mod_pow2__mod_pow2_C_25:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$33554431, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_26
	.private_extern _mod_pow2__mod_pow2_C_26
_mod_pow2__mod_pow2_C_26:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$67108863, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_27
	.private_extern _mod_pow2__mod_pow2_C_27
_mod_pow2__mod_pow2_C_27:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$134217727, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_28
	.private_extern _mod_pow2__mod_pow2_C_28
_mod_pow2__mod_pow2_C_28:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$268435455, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_29
	.private_extern _mod_pow2__mod_pow2_C_29
_mod_pow2__mod_pow2_C_29:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$536870911, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_30
	.private_extern _mod_pow2__mod_pow2_C_30
_mod_pow2__mod_pow2_C_30:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1073741823, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_31
	.private_extern _mod_pow2__mod_pow2_C_31
_mod_pow2__mod_pow2_C_31:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2147483647, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_32
	.private_extern _mod_pow2__mod_pow2_C_32
_mod_pow2__mod_pow2_C_32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4294967295, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_33
	.private_extern _mod_pow2__mod_pow2_C_33
_mod_pow2__mod_pow2_C_33:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$8589934591, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_34
	.private_extern _mod_pow2__mod_pow2_C_34
_mod_pow2__mod_pow2_C_34:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$17179869183, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_35
	.private_extern _mod_pow2__mod_pow2_C_35
_mod_pow2__mod_pow2_C_35:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$34359738367, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_36
	.private_extern _mod_pow2__mod_pow2_C_36
_mod_pow2__mod_pow2_C_36:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$68719476735, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_37
	.private_extern _mod_pow2__mod_pow2_C_37
_mod_pow2__mod_pow2_C_37:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$137438953471, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_38
	.private_extern _mod_pow2__mod_pow2_C_38
_mod_pow2__mod_pow2_C_38:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$274877906943, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_39
	.private_extern _mod_pow2__mod_pow2_C_39
_mod_pow2__mod_pow2_C_39:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$549755813887, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_40
	.private_extern _mod_pow2__mod_pow2_C_40
_mod_pow2__mod_pow2_C_40:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1099511627775, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_41
	.private_extern _mod_pow2__mod_pow2_C_41
_mod_pow2__mod_pow2_C_41:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2199023255551, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_42
	.private_extern _mod_pow2__mod_pow2_C_42
_mod_pow2__mod_pow2_C_42:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4398046511103, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_43
	.private_extern _mod_pow2__mod_pow2_C_43
_mod_pow2__mod_pow2_C_43:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$8796093022207, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_44
	.private_extern _mod_pow2__mod_pow2_C_44
_mod_pow2__mod_pow2_C_44:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$17592186044415, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_45
	.private_extern _mod_pow2__mod_pow2_C_45
_mod_pow2__mod_pow2_C_45:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$35184372088831, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_46
	.private_extern _mod_pow2__mod_pow2_C_46
_mod_pow2__mod_pow2_C_46:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$70368744177663, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_47
	.private_extern _mod_pow2__mod_pow2_C_47
_mod_pow2__mod_pow2_C_47:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$140737488355327, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_48
	.private_extern _mod_pow2__mod_pow2_C_48
_mod_pow2__mod_pow2_C_48:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$281474976710655, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_49
	.private_extern _mod_pow2__mod_pow2_C_49
_mod_pow2__mod_pow2_C_49:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$562949953421311, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_50
	.private_extern _mod_pow2__mod_pow2_C_50
_mod_pow2__mod_pow2_C_50:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1125899906842623, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_51
	.private_extern _mod_pow2__mod_pow2_C_51
_mod_pow2__mod_pow2_C_51:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2251799813685247, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_52
	.private_extern _mod_pow2__mod_pow2_C_52
_mod_pow2__mod_pow2_C_52:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4503599627370495, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_53
	.private_extern _mod_pow2__mod_pow2_C_53
_mod_pow2__mod_pow2_C_53:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$9007199254740991, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_54
	.private_extern _mod_pow2__mod_pow2_C_54
_mod_pow2__mod_pow2_C_54:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$18014398509481983, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_55
	.private_extern _mod_pow2__mod_pow2_C_55
_mod_pow2__mod_pow2_C_55:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$36028797018963967, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_56
	.private_extern _mod_pow2__mod_pow2_C_56
_mod_pow2__mod_pow2_C_56:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$72057594037927935, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_57
	.private_extern _mod_pow2__mod_pow2_C_57
_mod_pow2__mod_pow2_C_57:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$144115188075855871, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_58
	.private_extern _mod_pow2__mod_pow2_C_58
_mod_pow2__mod_pow2_C_58:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$288230376151711743, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_59
	.private_extern _mod_pow2__mod_pow2_C_59
_mod_pow2__mod_pow2_C_59:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$576460752303423487, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_60
	.private_extern _mod_pow2__mod_pow2_C_60
_mod_pow2__mod_pow2_C_60:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1152921504606846975, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_61
	.private_extern _mod_pow2__mod_pow2_C_61
_mod_pow2__mod_pow2_C_61:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2305843009213693951, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_62
	.private_extern _mod_pow2__mod_pow2_C_62
_mod_pow2__mod_pow2_C_62:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4611686018427387903, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_C_63
	.private_extern _mod_pow2__mod_pow2_C_63
_mod_pow2__mod_pow2_C_63:
	pushq	%rbp
	movq	%rsp, %rbp
	subq	$32, %rsp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rcx
	leaq	-1(%rcx), %rdx
	movq	%rcx, %rax
	orq	%rdx, %rax
	movq	%rax, %rsi
	sarq	$63, %rsi
	subq	%rsi, %rdx
	movabsq	$-9223372036854775808, %rax
	cmpq	%rax, %rdx
	sete	%al
	movzbl	%al, %edx
	movq	%rsi, %rax
	notq	%rax
	leaq	(%rdx,%rax), %rax
	movq	%rax, -16(%rbp)
	movq	-16(%rbp), %rax
	salq	$63, %rax
	movq	%rcx, %rdx
	subq	%rax, %rdx
	movq	%rdx, %rax
	movq	%rax, -16(%rbp)
	cmpq	$0, -16(%rbp)
	jns	L640
	movl	$22177, %edi
	call	__m3_fault
L640:
	movq	-16(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_0
	.private_extern _mod_pow2__mod_pow2_L_0
_mod_pow2__mod_pow2_L_0:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movl	$0, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_1
	.private_extern _mod_pow2__mod_pow2_L_1
_mod_pow2__mod_pow2_L_1:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_2
	.private_extern _mod_pow2__mod_pow2_L_2
_mod_pow2__mod_pow2_L_2:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$3, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_3
	.private_extern _mod_pow2__mod_pow2_L_3
_mod_pow2__mod_pow2_L_3:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$7, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_4
	.private_extern _mod_pow2__mod_pow2_L_4
_mod_pow2__mod_pow2_L_4:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$15, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_5
	.private_extern _mod_pow2__mod_pow2_L_5
_mod_pow2__mod_pow2_L_5:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$31, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_6
	.private_extern _mod_pow2__mod_pow2_L_6
_mod_pow2__mod_pow2_L_6:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$63, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_7
	.private_extern _mod_pow2__mod_pow2_L_7
_mod_pow2__mod_pow2_L_7:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$127, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_8
	.private_extern _mod_pow2__mod_pow2_L_8
_mod_pow2__mod_pow2_L_8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$255, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_9
	.private_extern _mod_pow2__mod_pow2_L_9
_mod_pow2__mod_pow2_L_9:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$511, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_10
	.private_extern _mod_pow2__mod_pow2_L_10
_mod_pow2__mod_pow2_L_10:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1023, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_11
	.private_extern _mod_pow2__mod_pow2_L_11
_mod_pow2__mod_pow2_L_11:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2047, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_12
	.private_extern _mod_pow2__mod_pow2_L_12
_mod_pow2__mod_pow2_L_12:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4095, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_13
	.private_extern _mod_pow2__mod_pow2_L_13
_mod_pow2__mod_pow2_L_13:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$8191, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_14
	.private_extern _mod_pow2__mod_pow2_L_14
_mod_pow2__mod_pow2_L_14:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$16383, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_15
	.private_extern _mod_pow2__mod_pow2_L_15
_mod_pow2__mod_pow2_L_15:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$32767, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_16
	.private_extern _mod_pow2__mod_pow2_L_16
_mod_pow2__mod_pow2_L_16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$65535, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_17
	.private_extern _mod_pow2__mod_pow2_L_17
_mod_pow2__mod_pow2_L_17:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$131071, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_18
	.private_extern _mod_pow2__mod_pow2_L_18
_mod_pow2__mod_pow2_L_18:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$262143, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_19
	.private_extern _mod_pow2__mod_pow2_L_19
_mod_pow2__mod_pow2_L_19:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$524287, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_20
	.private_extern _mod_pow2__mod_pow2_L_20
_mod_pow2__mod_pow2_L_20:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1048575, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_21
	.private_extern _mod_pow2__mod_pow2_L_21
_mod_pow2__mod_pow2_L_21:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2097151, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_22
	.private_extern _mod_pow2__mod_pow2_L_22
_mod_pow2__mod_pow2_L_22:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4194303, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_23
	.private_extern _mod_pow2__mod_pow2_L_23
_mod_pow2__mod_pow2_L_23:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$8388607, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_24
	.private_extern _mod_pow2__mod_pow2_L_24
_mod_pow2__mod_pow2_L_24:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$16777215, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_25
	.private_extern _mod_pow2__mod_pow2_L_25
_mod_pow2__mod_pow2_L_25:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$33554431, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_26
	.private_extern _mod_pow2__mod_pow2_L_26
_mod_pow2__mod_pow2_L_26:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$67108863, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_27
	.private_extern _mod_pow2__mod_pow2_L_27
_mod_pow2__mod_pow2_L_27:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$134217727, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_28
	.private_extern _mod_pow2__mod_pow2_L_28
_mod_pow2__mod_pow2_L_28:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$268435455, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_29
	.private_extern _mod_pow2__mod_pow2_L_29
_mod_pow2__mod_pow2_L_29:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$536870911, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_30
	.private_extern _mod_pow2__mod_pow2_L_30
_mod_pow2__mod_pow2_L_30:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1073741823, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_31
	.private_extern _mod_pow2__mod_pow2_L_31
_mod_pow2__mod_pow2_L_31:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2147483647, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_32
	.private_extern _mod_pow2__mod_pow2_L_32
_mod_pow2__mod_pow2_L_32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4294967295, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_33
	.private_extern _mod_pow2__mod_pow2_L_33
_mod_pow2__mod_pow2_L_33:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$8589934591, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_34
	.private_extern _mod_pow2__mod_pow2_L_34
_mod_pow2__mod_pow2_L_34:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$17179869183, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_35
	.private_extern _mod_pow2__mod_pow2_L_35
_mod_pow2__mod_pow2_L_35:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$34359738367, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_36
	.private_extern _mod_pow2__mod_pow2_L_36
_mod_pow2__mod_pow2_L_36:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$68719476735, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_37
	.private_extern _mod_pow2__mod_pow2_L_37
_mod_pow2__mod_pow2_L_37:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$137438953471, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_38
	.private_extern _mod_pow2__mod_pow2_L_38
_mod_pow2__mod_pow2_L_38:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$274877906943, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_39
	.private_extern _mod_pow2__mod_pow2_L_39
_mod_pow2__mod_pow2_L_39:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$549755813887, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_40
	.private_extern _mod_pow2__mod_pow2_L_40
_mod_pow2__mod_pow2_L_40:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1099511627775, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_41
	.private_extern _mod_pow2__mod_pow2_L_41
_mod_pow2__mod_pow2_L_41:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2199023255551, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_42
	.private_extern _mod_pow2__mod_pow2_L_42
_mod_pow2__mod_pow2_L_42:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4398046511103, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_43
	.private_extern _mod_pow2__mod_pow2_L_43
_mod_pow2__mod_pow2_L_43:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$8796093022207, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_44
	.private_extern _mod_pow2__mod_pow2_L_44
_mod_pow2__mod_pow2_L_44:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$17592186044415, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_45
	.private_extern _mod_pow2__mod_pow2_L_45
_mod_pow2__mod_pow2_L_45:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$35184372088831, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_46
	.private_extern _mod_pow2__mod_pow2_L_46
_mod_pow2__mod_pow2_L_46:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$70368744177663, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_47
	.private_extern _mod_pow2__mod_pow2_L_47
_mod_pow2__mod_pow2_L_47:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$140737488355327, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_48
	.private_extern _mod_pow2__mod_pow2_L_48
_mod_pow2__mod_pow2_L_48:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$281474976710655, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_49
	.private_extern _mod_pow2__mod_pow2_L_49
_mod_pow2__mod_pow2_L_49:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$562949953421311, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_50
	.private_extern _mod_pow2__mod_pow2_L_50
_mod_pow2__mod_pow2_L_50:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1125899906842623, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_51
	.private_extern _mod_pow2__mod_pow2_L_51
_mod_pow2__mod_pow2_L_51:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2251799813685247, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_52
	.private_extern _mod_pow2__mod_pow2_L_52
_mod_pow2__mod_pow2_L_52:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4503599627370495, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_53
	.private_extern _mod_pow2__mod_pow2_L_53
_mod_pow2__mod_pow2_L_53:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$9007199254740991, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_54
	.private_extern _mod_pow2__mod_pow2_L_54
_mod_pow2__mod_pow2_L_54:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$18014398509481983, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_55
	.private_extern _mod_pow2__mod_pow2_L_55
_mod_pow2__mod_pow2_L_55:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$36028797018963967, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_56
	.private_extern _mod_pow2__mod_pow2_L_56
_mod_pow2__mod_pow2_L_56:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$72057594037927935, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_57
	.private_extern _mod_pow2__mod_pow2_L_57
_mod_pow2__mod_pow2_L_57:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$144115188075855871, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_58
	.private_extern _mod_pow2__mod_pow2_L_58
_mod_pow2__mod_pow2_L_58:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$288230376151711743, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_59
	.private_extern _mod_pow2__mod_pow2_L_59
_mod_pow2__mod_pow2_L_59:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$576460752303423487, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_60
	.private_extern _mod_pow2__mod_pow2_L_60
_mod_pow2__mod_pow2_L_60:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1152921504606846975, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_61
	.private_extern _mod_pow2__mod_pow2_L_61
_mod_pow2__mod_pow2_L_61:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2305843009213693951, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_62
	.private_extern _mod_pow2__mod_pow2_L_62
_mod_pow2__mod_pow2_L_62:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4611686018427387903, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_L_63
	.private_extern _mod_pow2__mod_pow2_L_63
_mod_pow2__mod_pow2_L_63:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rcx
	leaq	-1(%rcx), %rdx
	movq	%rcx, %rax
	orq	%rdx, %rax
	movq	%rax, %rsi
	sarq	$63, %rsi
	subq	%rsi, %rdx
	movabsq	$-9223372036854775808, %rax
	cmpq	%rax, %rdx
	sete	%al
	movzbl	%al, %edx
	movq	%rsi, %rax
	notq	%rax
	leaq	(%rdx,%rax), %rax
	salq	$63, %rax
	movq	%rcx, %rdx
	subq	%rax, %rdx
	movq	%rdx, %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_0
	.private_extern _mod_pow2__mod_pow2_LC_0
_mod_pow2__mod_pow2_LC_0:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movl	$0, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_1
	.private_extern _mod_pow2__mod_pow2_LC_1
_mod_pow2__mod_pow2_LC_1:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_2
	.private_extern _mod_pow2__mod_pow2_LC_2
_mod_pow2__mod_pow2_LC_2:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$3, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_3
	.private_extern _mod_pow2__mod_pow2_LC_3
_mod_pow2__mod_pow2_LC_3:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$7, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_4
	.private_extern _mod_pow2__mod_pow2_LC_4
_mod_pow2__mod_pow2_LC_4:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$15, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_5
	.private_extern _mod_pow2__mod_pow2_LC_5
_mod_pow2__mod_pow2_LC_5:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$31, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_6
	.private_extern _mod_pow2__mod_pow2_LC_6
_mod_pow2__mod_pow2_LC_6:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$63, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_7
	.private_extern _mod_pow2__mod_pow2_LC_7
_mod_pow2__mod_pow2_LC_7:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$127, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_8
	.private_extern _mod_pow2__mod_pow2_LC_8
_mod_pow2__mod_pow2_LC_8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$255, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_9
	.private_extern _mod_pow2__mod_pow2_LC_9
_mod_pow2__mod_pow2_LC_9:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$511, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_10
	.private_extern _mod_pow2__mod_pow2_LC_10
_mod_pow2__mod_pow2_LC_10:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1023, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_11
	.private_extern _mod_pow2__mod_pow2_LC_11
_mod_pow2__mod_pow2_LC_11:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2047, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_12
	.private_extern _mod_pow2__mod_pow2_LC_12
_mod_pow2__mod_pow2_LC_12:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4095, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_13
	.private_extern _mod_pow2__mod_pow2_LC_13
_mod_pow2__mod_pow2_LC_13:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$8191, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_14
	.private_extern _mod_pow2__mod_pow2_LC_14
_mod_pow2__mod_pow2_LC_14:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$16383, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_15
	.private_extern _mod_pow2__mod_pow2_LC_15
_mod_pow2__mod_pow2_LC_15:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$32767, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_16
	.private_extern _mod_pow2__mod_pow2_LC_16
_mod_pow2__mod_pow2_LC_16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$65535, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_17
	.private_extern _mod_pow2__mod_pow2_LC_17
_mod_pow2__mod_pow2_LC_17:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$131071, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_18
	.private_extern _mod_pow2__mod_pow2_LC_18
_mod_pow2__mod_pow2_LC_18:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$262143, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_19
	.private_extern _mod_pow2__mod_pow2_LC_19
_mod_pow2__mod_pow2_LC_19:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$524287, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_20
	.private_extern _mod_pow2__mod_pow2_LC_20
_mod_pow2__mod_pow2_LC_20:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1048575, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_21
	.private_extern _mod_pow2__mod_pow2_LC_21
_mod_pow2__mod_pow2_LC_21:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2097151, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_22
	.private_extern _mod_pow2__mod_pow2_LC_22
_mod_pow2__mod_pow2_LC_22:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4194303, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_23
	.private_extern _mod_pow2__mod_pow2_LC_23
_mod_pow2__mod_pow2_LC_23:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$8388607, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_24
	.private_extern _mod_pow2__mod_pow2_LC_24
_mod_pow2__mod_pow2_LC_24:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$16777215, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_25
	.private_extern _mod_pow2__mod_pow2_LC_25
_mod_pow2__mod_pow2_LC_25:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$33554431, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_26
	.private_extern _mod_pow2__mod_pow2_LC_26
_mod_pow2__mod_pow2_LC_26:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$67108863, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_27
	.private_extern _mod_pow2__mod_pow2_LC_27
_mod_pow2__mod_pow2_LC_27:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$134217727, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_28
	.private_extern _mod_pow2__mod_pow2_LC_28
_mod_pow2__mod_pow2_LC_28:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$268435455, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_29
	.private_extern _mod_pow2__mod_pow2_LC_29
_mod_pow2__mod_pow2_LC_29:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$536870911, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_30
	.private_extern _mod_pow2__mod_pow2_LC_30
_mod_pow2__mod_pow2_LC_30:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$1073741823, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_31
	.private_extern _mod_pow2__mod_pow2_LC_31
_mod_pow2__mod_pow2_LC_31:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$2147483647, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_32
	.private_extern _mod_pow2__mod_pow2_LC_32
_mod_pow2__mod_pow2_LC_32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	andl	$4294967295, %eax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_33
	.private_extern _mod_pow2__mod_pow2_LC_33
_mod_pow2__mod_pow2_LC_33:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$8589934591, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_34
	.private_extern _mod_pow2__mod_pow2_LC_34
_mod_pow2__mod_pow2_LC_34:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$17179869183, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_35
	.private_extern _mod_pow2__mod_pow2_LC_35
_mod_pow2__mod_pow2_LC_35:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$34359738367, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_36
	.private_extern _mod_pow2__mod_pow2_LC_36
_mod_pow2__mod_pow2_LC_36:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$68719476735, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_37
	.private_extern _mod_pow2__mod_pow2_LC_37
_mod_pow2__mod_pow2_LC_37:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$137438953471, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_38
	.private_extern _mod_pow2__mod_pow2_LC_38
_mod_pow2__mod_pow2_LC_38:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$274877906943, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_39
	.private_extern _mod_pow2__mod_pow2_LC_39
_mod_pow2__mod_pow2_LC_39:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$549755813887, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_40
	.private_extern _mod_pow2__mod_pow2_LC_40
_mod_pow2__mod_pow2_LC_40:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1099511627775, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_41
	.private_extern _mod_pow2__mod_pow2_LC_41
_mod_pow2__mod_pow2_LC_41:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2199023255551, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_42
	.private_extern _mod_pow2__mod_pow2_LC_42
_mod_pow2__mod_pow2_LC_42:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4398046511103, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_43
	.private_extern _mod_pow2__mod_pow2_LC_43
_mod_pow2__mod_pow2_LC_43:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$8796093022207, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_44
	.private_extern _mod_pow2__mod_pow2_LC_44
_mod_pow2__mod_pow2_LC_44:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$17592186044415, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_45
	.private_extern _mod_pow2__mod_pow2_LC_45
_mod_pow2__mod_pow2_LC_45:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$35184372088831, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_46
	.private_extern _mod_pow2__mod_pow2_LC_46
_mod_pow2__mod_pow2_LC_46:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$70368744177663, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_47
	.private_extern _mod_pow2__mod_pow2_LC_47
_mod_pow2__mod_pow2_LC_47:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$140737488355327, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_48
	.private_extern _mod_pow2__mod_pow2_LC_48
_mod_pow2__mod_pow2_LC_48:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$281474976710655, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_49
	.private_extern _mod_pow2__mod_pow2_LC_49
_mod_pow2__mod_pow2_LC_49:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$562949953421311, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_50
	.private_extern _mod_pow2__mod_pow2_LC_50
_mod_pow2__mod_pow2_LC_50:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1125899906842623, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_51
	.private_extern _mod_pow2__mod_pow2_LC_51
_mod_pow2__mod_pow2_LC_51:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2251799813685247, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_52
	.private_extern _mod_pow2__mod_pow2_LC_52
_mod_pow2__mod_pow2_LC_52:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4503599627370495, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_53
	.private_extern _mod_pow2__mod_pow2_LC_53
_mod_pow2__mod_pow2_LC_53:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$9007199254740991, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_54
	.private_extern _mod_pow2__mod_pow2_LC_54
_mod_pow2__mod_pow2_LC_54:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$18014398509481983, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_55
	.private_extern _mod_pow2__mod_pow2_LC_55
_mod_pow2__mod_pow2_LC_55:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$36028797018963967, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_56
	.private_extern _mod_pow2__mod_pow2_LC_56
_mod_pow2__mod_pow2_LC_56:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$72057594037927935, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_57
	.private_extern _mod_pow2__mod_pow2_LC_57
_mod_pow2__mod_pow2_LC_57:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$144115188075855871, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_58
	.private_extern _mod_pow2__mod_pow2_LC_58
_mod_pow2__mod_pow2_LC_58:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$288230376151711743, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_59
	.private_extern _mod_pow2__mod_pow2_LC_59
_mod_pow2__mod_pow2_LC_59:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$576460752303423487, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_60
	.private_extern _mod_pow2__mod_pow2_LC_60
_mod_pow2__mod_pow2_LC_60:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$1152921504606846975, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_61
	.private_extern _mod_pow2__mod_pow2_LC_61
_mod_pow2__mod_pow2_LC_61:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$2305843009213693951, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_62
	.private_extern _mod_pow2__mod_pow2_LC_62
_mod_pow2__mod_pow2_LC_62:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movabsq	$4611686018427387903, %rax
	andq	-24(%rbp), %rax
	leave
	ret
.globl _mod_pow2__mod_pow2_LC_63
	.private_extern _mod_pow2__mod_pow2_LC_63
_mod_pow2__mod_pow2_LC_63:
	pushq	%rbp
	movq	%rsp, %rbp
	subq	$32, %rsp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rcx
	leaq	-1(%rcx), %rdx
	movq	%rcx, %rax
	orq	%rdx, %rax
	movq	%rax, %rsi
	sarq	$63, %rsi
	subq	%rsi, %rdx
	movabsq	$-9223372036854775808, %rax
	cmpq	%rax, %rdx
	sete	%al
	movzbl	%al, %edx
	movq	%rsi, %rax
	notq	%rax
	leaq	(%rdx,%rax), %rax
	movq	%rax, -16(%rbp)
	movq	-16(%rbp), %rax
	salq	$63, %rax
	movq	%rcx, %rdx
	subq	%rax, %rdx
	movq	%rdx, %rax
	movq	%rax, -16(%rbp)
	cmpq	$0, -16(%rbp)
	jns	L897
	movl	$30369, %edi
	call	__m3_fault
L897:
	movq	-16(%rbp), %rax
	leave
	ret
.globl _mod_pow2_M3
_mod_pow2_M3:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -8(%rbp)
	leaq	_MM_mod_pow2(%rip), %rax
	leave
	ret
__m3_fault:
	pushq	%rbp
	movq	%rsp, %rbp
	subq	$16, %rsp
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rsi
	leaq	_MM_mod_pow2(%rip), %rdi
	call	_RTHooks__ReportFault
	leave
	ret
	.const_data
	.align 5
_L_1:
	.ascii "mod_pow2_M3"
	.space 1
	.ascii "mod_pow2_LC_63"
	.space 1
	.ascii "mod_pow2_LC_62"
	.space 1
	.ascii "mod_pow2_LC_61"
	.space 1
	.ascii "mod_pow2_LC_60"
	.space 1
	.ascii "mod_pow2_LC_59"
	.space 1
	.ascii "mod_pow2_LC_58"
	.space 1
	.ascii "mod_pow2_LC_57"
	.space 1
	.ascii "mod_pow2_LC_56"
	.space 1
	.ascii "mod_pow2_LC_55"
	.space 1
	.ascii "mod_pow2_LC_54"
	.space 1
	.ascii "mod_pow2_LC_53"
	.space 1
	.ascii "mod_pow2_LC_52"
	.space 1
	.ascii "mod_pow2_LC_51"
	.space 1
	.ascii "mod_pow2_LC_50"
	.space 1
	.ascii "mod_pow2_LC_49"
	.space 1
	.ascii "mod_pow2_LC_48"
	.space 1
	.ascii "mod_pow2_LC_47"
	.space 1
	.ascii "mod_pow2_LC_46"
	.space 1
	.ascii "mod_pow2_LC_45"
	.space 1
	.ascii "mod_pow2_LC_44"
	.space 1
	.ascii "mod_pow2_LC_43"
	.space 1
	.ascii "mod_pow2_LC_42"
	.space 1
	.ascii "mod_pow2_LC_41"
	.space 1
	.ascii "mod_pow2_LC_40"
	.space 1
	.ascii "mod_pow2_LC_39"
	.space 1
	.ascii "mod_pow2_LC_38"
	.space 1
	.ascii "mod_pow2_LC_37"
	.space 1
	.ascii "mod_pow2_LC_36"
	.space 1
	.ascii "mod_pow2_LC_35"
	.space 1
	.ascii "mod_pow2_LC_34"
	.space 1
	.ascii "mod_pow2_LC_33"
	.space 1
	.ascii "mod_pow2_LC_32"
	.space 1
	.ascii "mod_pow2_LC_31"
	.space 1
	.ascii "mod_pow2_LC_30"
	.space 1
	.ascii "mod_pow2_LC_29"
	.space 1
	.ascii "mod_pow2_LC_28"
	.space 1
	.ascii "mod_pow2_LC_27"
	.space 1
	.ascii "mod_pow2_LC_26"
	.space 1
	.ascii "mod_pow2_LC_25"
	.space 1
	.ascii "mod_pow2_LC_24"
	.space 1
	.ascii "mod_pow2_LC_23"
	.space 1
	.ascii "mod_pow2_LC_22"
	.space 1
	.ascii "mod_pow2_LC_21"
	.space 1
	.ascii "mod_pow2_LC_20"
	.space 1
	.ascii "mod_pow2_LC_19"
	.space 1
	.ascii "mod_pow2_LC_18"
	.space 1
	.ascii "mod_pow2_LC_17"
	.space 1
	.ascii "mod_pow2_LC_16"
	.space 1
	.ascii "mod_pow2_LC_15"
	.space 1
	.ascii "mod_pow2_LC_14"
	.space 1
	.ascii "mod_pow2_LC_13"
	.space 1
	.ascii "mod_pow2_LC_12"
	.space 1
	.ascii "mod_pow2_LC_11"
	.space 1
	.ascii "mod_pow2_LC_10"
	.space 1
	.ascii "mod_pow2_LC_9"
	.space 1
	.ascii "mod_pow2_LC_8"
	.space 1
	.ascii "mod_pow2_LC_7"
	.space 1
	.ascii "mod_pow2_LC_6"
	.space 1
	.ascii "mod_pow2_LC_5"
	.space 1
	.ascii "mod_pow2_LC_4"
	.space 1
	.ascii "mod_pow2_LC_3"
	.space 1
	.ascii "mod_pow2_LC_2"
	.space 1
	.ascii "mod_pow2_LC_1"
	.space 1
	.ascii "mod_pow2_LC_0"
	.space 1
	.ascii "mod_pow2_L_63"
	.space 1
	.ascii "mod_pow2_L_62"
	.space 1
	.ascii "mod_pow2_L_61"
	.space 1
	.ascii "mod_pow2_L_60"
	.space 1
	.ascii "mod_pow2_L_59"
	.space 1
	.ascii "mod_pow2_L_58"
	.space 1
	.ascii "mod_pow2_L_57"
	.space 1
	.ascii "mod_pow2_L_56"
	.space 1
	.ascii "mod_pow2_L_55"
	.space 1
	.ascii "mod_pow2_L_54"
	.space 1
	.ascii "mod_pow2_L_53"
	.space 1
	.ascii "mod_pow2_L_52"
	.space 1
	.ascii "mod_pow2_L_51"
	.space 1
	.ascii "mod_pow2_L_50"
	.space 1
	.ascii "mod_pow2_L_49"
	.space 1
	.ascii "mod_pow2_L_48"
	.space 1
	.ascii "mod_pow2_L_47"
	.space 1
	.ascii "mod_pow2_L_46"
	.space 1
	.ascii "mod_pow2_L_45"
	.space 1
	.ascii "mod_pow2_L_44"
	.space 1
	.ascii "mod_pow2_L_43"
	.space 1
	.ascii "mod_pow2_L_42"
	.space 1
	.ascii "mod_pow2_L_41"
	.space 1
	.ascii "mod_pow2_L_40"
	.space 1
	.ascii "mod_pow2_L_39"
	.space 1
	.ascii "mod_pow2_L_38"
	.space 1
	.ascii "mod_pow2_L_37"
	.space 1
	.ascii "mod_pow2_L_36"
	.space 1
	.ascii "mod_pow2_L_35"
	.space 1
	.ascii "mod_pow2_L_34"
	.space 1
	.ascii "mod_pow2_L_33"
	.space 1
	.ascii "mod_pow2_L_32"
	.space 1
	.ascii "mod_pow2_L_31"
	.space 1
	.ascii "mod_pow2_L_30"
	.space 1
	.ascii "mod_pow2_L_29"
	.space 1
	.ascii "mod_pow2_L_28"
	.space 1
	.ascii "mod_pow2_L_27"
	.space 1
	.ascii "mod_pow2_L_26"
	.space 1
	.ascii "mod_pow2_L_25"
	.space 1
	.ascii "mod_pow2_L_24"
	.space 1
	.ascii "mod_pow2_L_23"
	.space 1
	.ascii "mod_pow2_L_22"
	.space 1
	.ascii "mod_pow2_L_21"
	.space 1
	.ascii "mod_pow2_L_20"
	.space 1
	.ascii "mod_pow2_L_19"
	.space 1
	.ascii "mod_pow2_L_18"
	.space 1
	.ascii "mod_pow2_L_17"
	.space 1
	.ascii "mod_pow2_L_16"
	.space 1
	.ascii "mod_pow2_L_15"
	.space 1
	.ascii "mod_pow2_L_14"
	.space 1
	.ascii "mod_pow2_L_13"
	.space 1
	.ascii "mod_pow2_L_12"
	.space 1
	.ascii "mod_pow2_L_11"
	.space 1
	.ascii "mod_pow2_L_10"
	.space 1
	.ascii "mod_pow2_L_9"
	.space 1
	.ascii "mod_pow2_L_8"
	.space 1
	.ascii "mod_pow2_L_7"
	.space 1
	.ascii "mod_pow2_L_6"
	.space 1
	.ascii "mod_pow2_L_5"
	.space 1
	.ascii "mod_pow2_L_4"
	.space 1
	.ascii "mod_pow2_L_3"
	.space 1
	.ascii "mod_pow2_L_2"
	.space 1
	.ascii "mod_pow2_L_1"
	.space 1
	.ascii "mod_pow2_L_0"
	.space 1
	.ascii "mod_pow2_C_63"
	.space 1
	.ascii "mod_pow2_C_62"
	.space 1
	.ascii "mod_pow2_C_61"
	.space 1
	.ascii "mod_pow2_C_60"
	.space 1
	.ascii "mod_pow2_C_59"
	.space 1
	.ascii "mod_pow2_C_58"
	.space 1
	.ascii "mod_pow2_C_57"
	.space 1
	.ascii "mod_pow2_C_56"
	.space 1
	.ascii "mod_pow2_C_55"
	.space 1
	.ascii "mod_pow2_C_54"
	.space 1
	.ascii "mod_pow2_C_53"
	.space 1
	.ascii "mod_pow2_C_52"
	.space 1
	.ascii "mod_pow2_C_51"
	.space 1
	.ascii "mod_pow2_C_50"
	.space 1
	.ascii "mod_pow2_C_49"
	.space 1
	.ascii "mod_pow2_C_48"
	.space 1
	.ascii "mod_pow2_C_47"
	.space 1
	.ascii "mod_pow2_C_46"
	.space 1
	.ascii "mod_pow2_C_45"
	.space 1
	.ascii "mod_pow2_C_44"
	.space 1
	.ascii "mod_pow2_C_43"
	.space 1
	.ascii "mod_pow2_C_42"
	.space 1
	.ascii "mod_pow2_C_41"
	.space 1
	.ascii "mod_pow2_C_40"
	.space 1
	.ascii "mod_pow2_C_39"
	.space 1
	.ascii "mod_pow2_C_38"
	.space 1
	.ascii "mod_pow2_C_37"
	.space 1
	.ascii "mod_pow2_C_36"
	.space 1
	.ascii "mod_pow2_C_35"
	.space 1
	.ascii "mod_pow2_C_34"
	.space 1
	.ascii "mod_pow2_C_33"
	.space 1
	.ascii "mod_pow2_C_32"
	.space 1
	.ascii "mod_pow2_C_31"
	.space 1
	.ascii "mod_pow2_C_30"
	.space 1
	.ascii "mod_pow2_C_29"
	.space 1
	.ascii "mod_pow2_C_28"
	.space 1
	.ascii "mod_pow2_C_27"
	.space 1
	.ascii "mod_pow2_C_26"
	.space 1
	.ascii "mod_pow2_C_25"
	.space 1
	.ascii "mod_pow2_C_24"
	.space 1
	.ascii "mod_pow2_C_23"
	.space 1
	.ascii "mod_pow2_C_22"
	.space 1
	.ascii "mod_pow2_C_21"
	.space 1
	.ascii "mod_pow2_C_20"
	.space 1
	.ascii "mod_pow2_C_19"
	.space 1
	.ascii "mod_pow2_C_18"
	.space 1
	.ascii "mod_pow2_C_17"
	.space 1
	.ascii "mod_pow2_C_16"
	.space 1
	.ascii "mod_pow2_C_15"
	.space 1
	.ascii "mod_pow2_C_14"
	.space 1
	.ascii "mod_pow2_C_13"
	.space 1
	.ascii "mod_pow2_C_12"
	.space 1
	.ascii "mod_pow2_C_11"
	.space 1
	.ascii "mod_pow2_C_10"
	.space 1
	.ascii "mod_pow2_C_9"
	.space 1
	.ascii "mod_pow2_C_8"
	.space 1
	.ascii "mod_pow2_C_7"
	.space 1
	.ascii "mod_pow2_C_6"
	.space 1
	.ascii "mod_pow2_C_5"
	.space 1
	.ascii "mod_pow2_C_4"
	.space 1
	.ascii "mod_pow2_C_3"
	.space 1
	.ascii "mod_pow2_C_2"
	.space 1
	.ascii "mod_pow2_C_1"
	.space 1
	.ascii "mod_pow2_C_0"
	.space 1
	.ascii "mod_pow2_I_63"
	.space 1
	.ascii "mod_pow2_I_62"
	.space 1
	.ascii "mod_pow2_I_61"
	.space 1
	.ascii "mod_pow2_I_60"
	.space 1
	.ascii "mod_pow2_I_59"
	.space 1
	.ascii "mod_pow2_I_58"
	.space 1
	.ascii "mod_pow2_I_57"
	.space 1
	.ascii "mod_pow2_I_56"
	.space 1
	.ascii "mod_pow2_I_55"
	.space 1
	.ascii "mod_pow2_I_54"
	.space 1
	.ascii "mod_pow2_I_53"
	.space 1
	.ascii "mod_pow2_I_52"
	.space 1
	.ascii "mod_pow2_I_51"
	.space 1
	.ascii "mod_pow2_I_50"
	.space 1
	.ascii "mod_pow2_I_49"
	.space 1
	.ascii "mod_pow2_I_48"
	.space 1
	.ascii "mod_pow2_I_47"
	.space 1
	.ascii "mod_pow2_I_46"
	.space 1
	.ascii "mod_pow2_I_45"
	.space 1
	.ascii "mod_pow2_I_44"
	.space 1
	.ascii "mod_pow2_I_43"
	.space 1
	.ascii "mod_pow2_I_42"
	.space 1
	.ascii "mod_pow2_I_41"
	.space 1
	.ascii "mod_pow2_I_40"
	.space 1
	.ascii "mod_pow2_I_39"
	.space 1
	.ascii "mod_pow2_I_38"
	.space 1
	.ascii "mod_pow2_I_37"
	.space 1
	.ascii "mod_pow2_I_36"
	.space 1
	.ascii "mod_pow2_I_35"
	.space 1
	.ascii "mod_pow2_I_34"
	.space 1
	.ascii "mod_pow2_I_33"
	.space 1
	.ascii "mod_pow2_I_32"
	.space 1
	.ascii "mod_pow2_I_31"
	.space 1
	.ascii "mod_pow2_I_30"
	.space 1
	.ascii "mod_pow2_I_29"
	.space 1
	.ascii "mod_pow2_I_28"
	.space 1
	.ascii "mod_pow2_I_27"
	.space 1
	.ascii "mod_pow2_I_26"
	.space 1
	.ascii "mod_pow2_I_25"
	.space 1
	.ascii "mod_pow2_I_24"
	.space 1
	.ascii "mod_pow2_I_23"
	.space 1
	.ascii "mod_pow2_I_22"
	.space 1
	.ascii "mod_pow2_I_21"
	.space 1
	.ascii "mod_pow2_I_20"
	.space 1
	.ascii "mod_pow2_I_19"
	.space 1
	.ascii "mod_pow2_I_18"
	.space 1
	.ascii "mod_pow2_I_17"
	.space 1
	.ascii "mod_pow2_I_16"
	.space 1
	.ascii "mod_pow2_I_15"
	.space 1
	.ascii "mod_pow2_I_14"
	.space 1
	.ascii "mod_pow2_I_13"
	.space 1
	.ascii "mod_pow2_I_12"
	.space 1
	.ascii "mod_pow2_I_11"
	.space 1
	.ascii "mod_pow2_I_10"
	.space 1
	.ascii "mod_pow2_I_9"
	.space 1
	.ascii "mod_pow2_I_8"
	.space 1
	.ascii "mod_pow2_I_7"
	.space 1
	.ascii "mod_pow2_I_6"
	.space 1
	.ascii "mod_pow2_I_5"
	.space 1
	.ascii "mod_pow2_I_4"
	.space 1
	.ascii "mod_pow2_I_3"
	.space 1
	.ascii "mod_pow2_I_2"
	.space 1
	.ascii "mod_pow2_I_1"
	.space 1
	.ascii "mod_pow2_I_0"
	.space 1
	.ascii "mod_pow2_u64_63"
	.space 1
	.ascii "mod_pow2_u64_62"
	.space 1
	.ascii "mod_pow2_u64_61"
	.space 1
	.ascii "mod_pow2_u64_60"
	.space 1
	.ascii "mod_pow2_u64_59"
	.space 1
	.ascii "mod_pow2_u64_58"
	.space 1
	.ascii "mod_pow2_u64_57"
	.space 1
	.ascii "mod_pow2_u64_56"
	.space 1
	.ascii "mod_pow2_u64_55"
	.space 1
	.ascii "mod_pow2_u64_54"
	.space 1
	.ascii "mod_pow2_u64_53"
	.space 1
	.ascii "mod_pow2_u64_52"
	.space 1
	.ascii "mod_pow2_u64_51"
	.space 1
	.ascii "mod_pow2_u64_50"
	.space 1
	.ascii "mod_pow2_u64_49"
	.space 1
	.ascii "mod_pow2_u64_48"
	.space 1
	.ascii "mod_pow2_u64_47"
	.space 1
	.ascii "mod_pow2_u64_46"
	.space 1
	.ascii "mod_pow2_u64_45"
	.space 1
	.ascii "mod_pow2_u64_44"
	.space 1
	.ascii "mod_pow2_u64_43"
	.space 1
	.ascii "mod_pow2_u64_42"
	.space 1
	.ascii "mod_pow2_u64_41"
	.space 1
	.ascii "mod_pow2_u64_40"
	.space 1
	.ascii "mod_pow2_u64_39"
	.space 1
	.ascii "mod_pow2_u64_38"
	.space 1
	.ascii "mod_pow2_u64_37"
	.space 1
	.ascii "mod_pow2_u64_36"
	.space 1
	.ascii "mod_pow2_u64_35"
	.space 1
	.ascii "mod_pow2_u64_34"
	.space 1
	.ascii "mod_pow2_u64_33"
	.space 1
	.ascii "mod_pow2_u64_32"
	.space 1
	.ascii "mod_pow2_u64_31"
	.space 1
	.ascii "mod_pow2_u64_30"
	.space 1
	.ascii "mod_pow2_u64_29"
	.space 1
	.ascii "mod_pow2_u64_28"
	.space 1
	.ascii "mod_pow2_u64_27"
	.space 1
	.ascii "mod_pow2_u64_26"
	.space 1
	.ascii "mod_pow2_u64_25"
	.space 1
	.ascii "mod_pow2_u64_24"
	.space 1
	.ascii "mod_pow2_u64_23"
	.space 1
	.ascii "mod_pow2_u64_22"
	.space 1
	.ascii "mod_pow2_u64_21"
	.space 1
	.ascii "mod_pow2_u64_20"
	.space 1
	.ascii "mod_pow2_u64_19"
	.space 1
	.ascii "mod_pow2_u64_18"
	.space 1
	.ascii "mod_pow2_u64_17"
	.space 1
	.ascii "mod_pow2_u64_16"
	.space 1
	.ascii "mod_pow2_u64_15"
	.space 1
	.ascii "mod_pow2_u64_14"
	.space 1
	.ascii "mod_pow2_u64_13"
	.space 1
	.ascii "mod_pow2_u64_12"
	.space 1
	.ascii "mod_pow2_u64_11"
	.space 1
	.ascii "mod_pow2_u64_10"
	.space 1
	.ascii "mod_pow2_u64_9"
	.space 1
	.ascii "mod_pow2_u64_8"
	.space 1
	.ascii "mod_pow2_u64_7"
	.space 1
	.ascii "mod_pow2_u64_6"
	.space 1
	.ascii "mod_pow2_u64_5"
	.space 1
	.ascii "mod_pow2_u64_4"
	.space 1
	.ascii "mod_pow2_u64_3"
	.space 1
	.ascii "mod_pow2_u64_2"
	.space 1
	.ascii "mod_pow2_u64_1"
	.space 1
	.ascii "mod_pow2_u64_0"
	.space 1
	.ascii "mod_pow2_i64_63"
	.space 1
	.ascii "mod_pow2_i64_62"
	.space 1
	.ascii "mod_pow2_i64_61"
	.space 1
	.ascii "mod_pow2_i64_60"
	.space 1
	.ascii "mod_pow2_i64_59"
	.space 1
	.ascii "mod_pow2_i64_58"
	.space 1
	.ascii "mod_pow2_i64_57"
	.space 1
	.ascii "mod_pow2_i64_56"
	.space 1
	.ascii "mod_pow2_i64_55"
	.space 1
	.ascii "mod_pow2_i64_54"
	.space 1
	.ascii "mod_pow2_i64_53"
	.space 1
	.ascii "mod_pow2_i64_52"
	.space 1
	.ascii "mod_pow2_i64_51"
	.space 1
	.ascii "mod_pow2_i64_50"
	.space 1
	.ascii "mod_pow2_i64_49"
	.space 1
	.ascii "mod_pow2_i64_48"
	.space 1
	.ascii "mod_pow2_i64_47"
	.space 1
	.ascii "mod_pow2_i64_46"
	.space 1
	.ascii "mod_pow2_i64_45"
	.space 1
	.ascii "mod_pow2_i64_44"
	.space 1
	.ascii "mod_pow2_i64_43"
	.space 1
	.ascii "mod_pow2_i64_42"
	.space 1
	.ascii "mod_pow2_i64_41"
	.space 1
	.ascii "mod_pow2_i64_40"
	.space 1
	.ascii "mod_pow2_i64_39"
	.space 1
	.ascii "mod_pow2_i64_38"
	.space 1
	.ascii "mod_pow2_i64_37"
	.space 1
	.ascii "mod_pow2_i64_36"
	.space 1
	.ascii "mod_pow2_i64_35"
	.space 1
	.ascii "mod_pow2_i64_34"
	.space 1
	.ascii "mod_pow2_i64_33"
	.space 1
	.ascii "mod_pow2_i64_32"
	.space 1
	.ascii "mod_pow2_i64_31"
	.space 1
	.ascii "mod_pow2_i64_30"
	.space 1
	.ascii "mod_pow2_i64_29"
	.space 1
	.ascii "mod_pow2_i64_28"
	.space 1
	.ascii "mod_pow2_i64_27"
	.space 1
	.ascii "mod_pow2_i64_26"
	.space 1
	.ascii "mod_pow2_i64_25"
	.space 1
	.ascii "mod_pow2_i64_24"
	.space 1
	.ascii "mod_pow2_i64_23"
	.space 1
	.ascii "mod_pow2_i64_22"
	.space 1
	.ascii "mod_pow2_i64_21"
	.space 1
	.ascii "mod_pow2_i64_20"
	.space 1
	.ascii "mod_pow2_i64_19"
	.space 1
	.ascii "mod_pow2_i64_18"
	.space 1
	.ascii "mod_pow2_i64_17"
	.space 1
	.ascii "mod_pow2_i64_16"
	.space 1
	.ascii "mod_pow2_i64_15"
	.space 1
	.ascii "mod_pow2_i64_14"
	.space 1
	.ascii "mod_pow2_i64_13"
	.space 1
	.ascii "mod_pow2_i64_12"
	.space 1
	.ascii "mod_pow2_i64_11"
	.space 1
	.ascii "mod_pow2_i64_10"
	.space 1
	.ascii "mod_pow2_i64_9"
	.space 1
	.ascii "mod_pow2_i64_8"
	.space 1
	.ascii "mod_pow2_i64_7"
	.space 1
	.ascii "mod_pow2_i64_6"
	.space 1
	.ascii "mod_pow2_i64_5"
	.space 1
	.ascii "mod_pow2_i64_4"
	.space 1
	.ascii "mod_pow2_i64_3"
	.space 1
	.ascii "mod_pow2_i64_2"
	.space 1
	.ascii "mod_pow2_i64_1"
	.space 1
	.ascii "mod_pow2_i64_0"
	.space 1
	.ascii "mod_pow2_u32_31"
	.space 1
	.ascii "mod_pow2_u32_30"
	.space 1
	.ascii "mod_pow2_u32_29"
	.space 1
	.ascii "mod_pow2_u32_28"
	.space 1
	.ascii "mod_pow2_u32_27"
	.space 1
	.ascii "mod_pow2_u32_26"
	.space 1
	.ascii "mod_pow2_u32_25"
	.space 1
	.ascii "mod_pow2_u32_24"
	.space 1
	.ascii "mod_pow2_u32_23"
	.space 1
	.ascii "mod_pow2_u32_22"
	.space 1
	.ascii "mod_pow2_u32_21"
	.space 1
	.ascii "mod_pow2_u32_20"
	.space 1
	.ascii "mod_pow2_u32_19"
	.space 1
	.ascii "mod_pow2_u32_18"
	.space 1
	.ascii "mod_pow2_u32_17"
	.space 1
	.ascii "mod_pow2_u32_16"
	.space 1
	.ascii "mod_pow2_u32_15"
	.space 1
	.ascii "mod_pow2_u32_14"
	.space 1
	.ascii "mod_pow2_u32_13"
	.space 1
	.ascii "mod_pow2_u32_12"
	.space 1
	.ascii "mod_pow2_u32_11"
	.space 1
	.ascii "mod_pow2_u32_10"
	.space 1
	.ascii "mod_pow2_u32_9"
	.space 1
	.ascii "mod_pow2_u32_8"
	.space 1
	.ascii "mod_pow2_u32_7"
	.space 1
	.ascii "mod_pow2_u32_6"
	.space 1
	.ascii "mod_pow2_u32_5"
	.space 1
	.ascii "mod_pow2_u32_4"
	.space 1
	.ascii "mod_pow2_u32_3"
	.space 1
	.ascii "mod_pow2_u32_2"
	.space 1
	.ascii "mod_pow2_u32_1"
	.space 1
	.ascii "mod_pow2_u32_0"
	.space 1
	.ascii "mod_pow2_i32_31"
	.space 1
	.ascii "mod_pow2_i32_30"
	.space 1
	.ascii "mod_pow2_i32_29"
	.space 1
	.ascii "mod_pow2_i32_28"
	.space 1
	.ascii "mod_pow2_i32_27"
	.space 1
	.ascii "mod_pow2_i32_26"
	.space 1
	.ascii "mod_pow2_i32_25"
	.space 1
	.ascii "mod_pow2_i32_24"
	.space 1
	.ascii "mod_pow2_i32_23"
	.space 1
	.ascii "mod_pow2_i32_22"
	.space 1
	.ascii "mod_pow2_i32_21"
	.space 1
	.ascii "mod_pow2_i32_20"
	.space 1
	.ascii "mod_pow2_i32_19"
	.space 1
	.ascii "mod_pow2_i32_18"
	.space 1
	.ascii "mod_pow2_i32_17"
	.space 1
	.ascii "mod_pow2_i32_16"
	.space 1
	.ascii "mod_pow2_i32_15"
	.space 1
	.ascii "mod_pow2_i32_14"
	.space 1
	.ascii "mod_pow2_i32_13"
	.space 1
	.ascii "mod_pow2_i32_12"
	.space 1
	.ascii "mod_pow2_i32_11"
	.space 1
	.ascii "mod_pow2_i32_10"
	.space 1
	.ascii "mod_pow2_i32_9"
	.space 1
	.ascii "mod_pow2_i32_8"
	.space 1
	.ascii "mod_pow2_i32_7"
	.space 1
	.ascii "mod_pow2_i32_6"
	.space 1
	.ascii "mod_pow2_i32_5"
	.space 1
	.ascii "mod_pow2_i32_4"
	.space 1
	.ascii "mod_pow2_i32_3"
	.space 1
	.ascii "mod_pow2_i32_2"
	.space 1
	.ascii "mod_pow2_i32_1"
	.space 1
	.ascii "mod_pow2_i32_0"
	.space 5
	.quad	_mod_pow2_M3
	.quad	_L_1
	.quad	_mod_pow2__mod_pow2_LC_63
	.quad	_L_1+12
	.quad	_mod_pow2__mod_pow2_LC_62
	.quad	_L_1+27
	.quad	_mod_pow2__mod_pow2_LC_61
	.quad	_L_1+42
	.quad	_mod_pow2__mod_pow2_LC_60
	.quad	_L_1+57
	.quad	_mod_pow2__mod_pow2_LC_59
	.quad	_L_1+72
	.quad	_mod_pow2__mod_pow2_LC_58
	.quad	_L_1+87
	.quad	_mod_pow2__mod_pow2_LC_57
	.quad	_L_1+102
	.quad	_mod_pow2__mod_pow2_LC_56
	.quad	_L_1+117
	.quad	_mod_pow2__mod_pow2_LC_55
	.quad	_L_1+132
	.quad	_mod_pow2__mod_pow2_LC_54
	.quad	_L_1+147
	.quad	_mod_pow2__mod_pow2_LC_53
	.quad	_L_1+162
	.quad	_mod_pow2__mod_pow2_LC_52
	.quad	_L_1+177
	.quad	_mod_pow2__mod_pow2_LC_51
	.quad	_L_1+192
	.quad	_mod_pow2__mod_pow2_LC_50
	.quad	_L_1+207
	.quad	_mod_pow2__mod_pow2_LC_49
	.quad	_L_1+222
	.quad	_mod_pow2__mod_pow2_LC_48
	.quad	_L_1+237
	.quad	_mod_pow2__mod_pow2_LC_47
	.quad	_L_1+252
	.quad	_mod_pow2__mod_pow2_LC_46
	.quad	_L_1+267
	.quad	_mod_pow2__mod_pow2_LC_45
	.quad	_L_1+282
	.quad	_mod_pow2__mod_pow2_LC_44
	.quad	_L_1+297
	.quad	_mod_pow2__mod_pow2_LC_43
	.quad	_L_1+312
	.quad	_mod_pow2__mod_pow2_LC_42
	.quad	_L_1+327
	.quad	_mod_pow2__mod_pow2_LC_41
	.quad	_L_1+342
	.quad	_mod_pow2__mod_pow2_LC_40
	.quad	_L_1+357
	.quad	_mod_pow2__mod_pow2_LC_39
	.quad	_L_1+372
	.quad	_mod_pow2__mod_pow2_LC_38
	.quad	_L_1+387
	.quad	_mod_pow2__mod_pow2_LC_37
	.quad	_L_1+402
	.quad	_mod_pow2__mod_pow2_LC_36
	.quad	_L_1+417
	.quad	_mod_pow2__mod_pow2_LC_35
	.quad	_L_1+432
	.quad	_mod_pow2__mod_pow2_LC_34
	.quad	_L_1+447
	.quad	_mod_pow2__mod_pow2_LC_33
	.quad	_L_1+462
	.quad	_mod_pow2__mod_pow2_LC_32
	.quad	_L_1+477
	.quad	_mod_pow2__mod_pow2_LC_31
	.quad	_L_1+492
	.quad	_mod_pow2__mod_pow2_LC_30
	.quad	_L_1+507
	.quad	_mod_pow2__mod_pow2_LC_29
	.quad	_L_1+522
	.quad	_mod_pow2__mod_pow2_LC_28
	.quad	_L_1+537
	.quad	_mod_pow2__mod_pow2_LC_27
	.quad	_L_1+552
	.quad	_mod_pow2__mod_pow2_LC_26
	.quad	_L_1+567
	.quad	_mod_pow2__mod_pow2_LC_25
	.quad	_L_1+582
	.quad	_mod_pow2__mod_pow2_LC_24
	.quad	_L_1+597
	.quad	_mod_pow2__mod_pow2_LC_23
	.quad	_L_1+612
	.quad	_mod_pow2__mod_pow2_LC_22
	.quad	_L_1+627
	.quad	_mod_pow2__mod_pow2_LC_21
	.quad	_L_1+642
	.quad	_mod_pow2__mod_pow2_LC_20
	.quad	_L_1+657
	.quad	_mod_pow2__mod_pow2_LC_19
	.quad	_L_1+672
	.quad	_mod_pow2__mod_pow2_LC_18
	.quad	_L_1+687
	.quad	_mod_pow2__mod_pow2_LC_17
	.quad	_L_1+702
	.quad	_mod_pow2__mod_pow2_LC_16
	.quad	_L_1+717
	.quad	_mod_pow2__mod_pow2_LC_15
	.quad	_L_1+732
	.quad	_mod_pow2__mod_pow2_LC_14
	.quad	_L_1+747
	.quad	_mod_pow2__mod_pow2_LC_13
	.quad	_L_1+762
	.quad	_mod_pow2__mod_pow2_LC_12
	.quad	_L_1+777
	.quad	_mod_pow2__mod_pow2_LC_11
	.quad	_L_1+792
	.quad	_mod_pow2__mod_pow2_LC_10
	.quad	_L_1+807
	.quad	_mod_pow2__mod_pow2_LC_9
	.quad	_L_1+822
	.quad	_mod_pow2__mod_pow2_LC_8
	.quad	_L_1+836
	.quad	_mod_pow2__mod_pow2_LC_7
	.quad	_L_1+850
	.quad	_mod_pow2__mod_pow2_LC_6
	.quad	_L_1+864
	.quad	_mod_pow2__mod_pow2_LC_5
	.quad	_L_1+878
	.quad	_mod_pow2__mod_pow2_LC_4
	.quad	_L_1+892
	.quad	_mod_pow2__mod_pow2_LC_3
	.quad	_L_1+906
	.quad	_mod_pow2__mod_pow2_LC_2
	.quad	_L_1+920
	.quad	_mod_pow2__mod_pow2_LC_1
	.quad	_L_1+934
	.quad	_mod_pow2__mod_pow2_LC_0
	.quad	_L_1+948
	.quad	_mod_pow2__mod_pow2_L_63
	.quad	_L_1+962
	.quad	_mod_pow2__mod_pow2_L_62
	.quad	_L_1+976
	.quad	_mod_pow2__mod_pow2_L_61
	.quad	_L_1+990
	.quad	_mod_pow2__mod_pow2_L_60
	.quad	_L_1+1004
	.quad	_mod_pow2__mod_pow2_L_59
	.quad	_L_1+1018
	.quad	_mod_pow2__mod_pow2_L_58
	.quad	_L_1+1032
	.quad	_mod_pow2__mod_pow2_L_57
	.quad	_L_1+1046
	.quad	_mod_pow2__mod_pow2_L_56
	.quad	_L_1+1060
	.quad	_mod_pow2__mod_pow2_L_55
	.quad	_L_1+1074
	.quad	_mod_pow2__mod_pow2_L_54
	.quad	_L_1+1088
	.quad	_mod_pow2__mod_pow2_L_53
	.quad	_L_1+1102
	.quad	_mod_pow2__mod_pow2_L_52
	.quad	_L_1+1116
	.quad	_mod_pow2__mod_pow2_L_51
	.quad	_L_1+1130
	.quad	_mod_pow2__mod_pow2_L_50
	.quad	_L_1+1144
	.quad	_mod_pow2__mod_pow2_L_49
	.quad	_L_1+1158
	.quad	_mod_pow2__mod_pow2_L_48
	.quad	_L_1+1172
	.quad	_mod_pow2__mod_pow2_L_47
	.quad	_L_1+1186
	.quad	_mod_pow2__mod_pow2_L_46
	.quad	_L_1+1200
	.quad	_mod_pow2__mod_pow2_L_45
	.quad	_L_1+1214
	.quad	_mod_pow2__mod_pow2_L_44
	.quad	_L_1+1228
	.quad	_mod_pow2__mod_pow2_L_43
	.quad	_L_1+1242
	.quad	_mod_pow2__mod_pow2_L_42
	.quad	_L_1+1256
	.quad	_mod_pow2__mod_pow2_L_41
	.quad	_L_1+1270
	.quad	_mod_pow2__mod_pow2_L_40
	.quad	_L_1+1284
	.quad	_mod_pow2__mod_pow2_L_39
	.quad	_L_1+1298
	.quad	_mod_pow2__mod_pow2_L_38
	.quad	_L_1+1312
	.quad	_mod_pow2__mod_pow2_L_37
	.quad	_L_1+1326
	.quad	_mod_pow2__mod_pow2_L_36
	.quad	_L_1+1340
	.quad	_mod_pow2__mod_pow2_L_35
	.quad	_L_1+1354
	.quad	_mod_pow2__mod_pow2_L_34
	.quad	_L_1+1368
	.quad	_mod_pow2__mod_pow2_L_33
	.quad	_L_1+1382
	.quad	_mod_pow2__mod_pow2_L_32
	.quad	_L_1+1396
	.quad	_mod_pow2__mod_pow2_L_31
	.quad	_L_1+1410
	.quad	_mod_pow2__mod_pow2_L_30
	.quad	_L_1+1424
	.quad	_mod_pow2__mod_pow2_L_29
	.quad	_L_1+1438
	.quad	_mod_pow2__mod_pow2_L_28
	.quad	_L_1+1452
	.quad	_mod_pow2__mod_pow2_L_27
	.quad	_L_1+1466
	.quad	_mod_pow2__mod_pow2_L_26
	.quad	_L_1+1480
	.quad	_mod_pow2__mod_pow2_L_25
	.quad	_L_1+1494
	.quad	_mod_pow2__mod_pow2_L_24
	.quad	_L_1+1508
	.quad	_mod_pow2__mod_pow2_L_23
	.quad	_L_1+1522
	.quad	_mod_pow2__mod_pow2_L_22
	.quad	_L_1+1536
	.quad	_mod_pow2__mod_pow2_L_21
	.quad	_L_1+1550
	.quad	_mod_pow2__mod_pow2_L_20
	.quad	_L_1+1564
	.quad	_mod_pow2__mod_pow2_L_19
	.quad	_L_1+1578
	.quad	_mod_pow2__mod_pow2_L_18
	.quad	_L_1+1592
	.quad	_mod_pow2__mod_pow2_L_17
	.quad	_L_1+1606
	.quad	_mod_pow2__mod_pow2_L_16
	.quad	_L_1+1620
	.quad	_mod_pow2__mod_pow2_L_15
	.quad	_L_1+1634
	.quad	_mod_pow2__mod_pow2_L_14
	.quad	_L_1+1648
	.quad	_mod_pow2__mod_pow2_L_13
	.quad	_L_1+1662
	.quad	_mod_pow2__mod_pow2_L_12
	.quad	_L_1+1676
	.quad	_mod_pow2__mod_pow2_L_11
	.quad	_L_1+1690
	.quad	_mod_pow2__mod_pow2_L_10
	.quad	_L_1+1704
	.quad	_mod_pow2__mod_pow2_L_9
	.quad	_L_1+1718
	.quad	_mod_pow2__mod_pow2_L_8
	.quad	_L_1+1731
	.quad	_mod_pow2__mod_pow2_L_7
	.quad	_L_1+1744
	.quad	_mod_pow2__mod_pow2_L_6
	.quad	_L_1+1757
	.quad	_mod_pow2__mod_pow2_L_5
	.quad	_L_1+1770
	.quad	_mod_pow2__mod_pow2_L_4
	.quad	_L_1+1783
	.quad	_mod_pow2__mod_pow2_L_3
	.quad	_L_1+1796
	.quad	_mod_pow2__mod_pow2_L_2
	.quad	_L_1+1809
	.quad	_mod_pow2__mod_pow2_L_1
	.quad	_L_1+1822
	.quad	_mod_pow2__mod_pow2_L_0
	.quad	_L_1+1835
	.quad	_mod_pow2__mod_pow2_C_63
	.quad	_L_1+1848
	.quad	_mod_pow2__mod_pow2_C_62
	.quad	_L_1+1862
	.quad	_mod_pow2__mod_pow2_C_61
	.quad	_L_1+1876
	.quad	_mod_pow2__mod_pow2_C_60
	.quad	_L_1+1890
	.quad	_mod_pow2__mod_pow2_C_59
	.quad	_L_1+1904
	.quad	_mod_pow2__mod_pow2_C_58
	.quad	_L_1+1918
	.quad	_mod_pow2__mod_pow2_C_57
	.quad	_L_1+1932
	.quad	_mod_pow2__mod_pow2_C_56
	.quad	_L_1+1946
	.quad	_mod_pow2__mod_pow2_C_55
	.quad	_L_1+1960
	.quad	_mod_pow2__mod_pow2_C_54
	.quad	_L_1+1974
	.quad	_mod_pow2__mod_pow2_C_53
	.quad	_L_1+1988
	.quad	_mod_pow2__mod_pow2_C_52
	.quad	_L_1+2002
	.quad	_mod_pow2__mod_pow2_C_51
	.quad	_L_1+2016
	.quad	_mod_pow2__mod_pow2_C_50
	.quad	_L_1+2030
	.quad	_mod_pow2__mod_pow2_C_49
	.quad	_L_1+2044
	.quad	_mod_pow2__mod_pow2_C_48
	.quad	_L_1+2058
	.quad	_mod_pow2__mod_pow2_C_47
	.quad	_L_1+2072
	.quad	_mod_pow2__mod_pow2_C_46
	.quad	_L_1+2086
	.quad	_mod_pow2__mod_pow2_C_45
	.quad	_L_1+2100
	.quad	_mod_pow2__mod_pow2_C_44
	.quad	_L_1+2114
	.quad	_mod_pow2__mod_pow2_C_43
	.quad	_L_1+2128
	.quad	_mod_pow2__mod_pow2_C_42
	.quad	_L_1+2142
	.quad	_mod_pow2__mod_pow2_C_41
	.quad	_L_1+2156
	.quad	_mod_pow2__mod_pow2_C_40
	.quad	_L_1+2170
	.quad	_mod_pow2__mod_pow2_C_39
	.quad	_L_1+2184
	.quad	_mod_pow2__mod_pow2_C_38
	.quad	_L_1+2198
	.quad	_mod_pow2__mod_pow2_C_37
	.quad	_L_1+2212
	.quad	_mod_pow2__mod_pow2_C_36
	.quad	_L_1+2226
	.quad	_mod_pow2__mod_pow2_C_35
	.quad	_L_1+2240
	.quad	_mod_pow2__mod_pow2_C_34
	.quad	_L_1+2254
	.quad	_mod_pow2__mod_pow2_C_33
	.quad	_L_1+2268
	.quad	_mod_pow2__mod_pow2_C_32
	.quad	_L_1+2282
	.quad	_mod_pow2__mod_pow2_C_31
	.quad	_L_1+2296
	.quad	_mod_pow2__mod_pow2_C_30
	.quad	_L_1+2310
	.quad	_mod_pow2__mod_pow2_C_29
	.quad	_L_1+2324
	.quad	_mod_pow2__mod_pow2_C_28
	.quad	_L_1+2338
	.quad	_mod_pow2__mod_pow2_C_27
	.quad	_L_1+2352
	.quad	_mod_pow2__mod_pow2_C_26
	.quad	_L_1+2366
	.quad	_mod_pow2__mod_pow2_C_25
	.quad	_L_1+2380
	.quad	_mod_pow2__mod_pow2_C_24
	.quad	_L_1+2394
	.quad	_mod_pow2__mod_pow2_C_23
	.quad	_L_1+2408
	.quad	_mod_pow2__mod_pow2_C_22
	.quad	_L_1+2422
	.quad	_mod_pow2__mod_pow2_C_21
	.quad	_L_1+2436
	.quad	_mod_pow2__mod_pow2_C_20
	.quad	_L_1+2450
	.quad	_mod_pow2__mod_pow2_C_19
	.quad	_L_1+2464
	.quad	_mod_pow2__mod_pow2_C_18
	.quad	_L_1+2478
	.quad	_mod_pow2__mod_pow2_C_17
	.quad	_L_1+2492
	.quad	_mod_pow2__mod_pow2_C_16
	.quad	_L_1+2506
	.quad	_mod_pow2__mod_pow2_C_15
	.quad	_L_1+2520
	.quad	_mod_pow2__mod_pow2_C_14
	.quad	_L_1+2534
	.quad	_mod_pow2__mod_pow2_C_13
	.quad	_L_1+2548
	.quad	_mod_pow2__mod_pow2_C_12
	.quad	_L_1+2562
	.quad	_mod_pow2__mod_pow2_C_11
	.quad	_L_1+2576
	.quad	_mod_pow2__mod_pow2_C_10
	.quad	_L_1+2590
	.quad	_mod_pow2__mod_pow2_C_9
	.quad	_L_1+2604
	.quad	_mod_pow2__mod_pow2_C_8
	.quad	_L_1+2617
	.quad	_mod_pow2__mod_pow2_C_7
	.quad	_L_1+2630
	.quad	_mod_pow2__mod_pow2_C_6
	.quad	_L_1+2643
	.quad	_mod_pow2__mod_pow2_C_5
	.quad	_L_1+2656
	.quad	_mod_pow2__mod_pow2_C_4
	.quad	_L_1+2669
	.quad	_mod_pow2__mod_pow2_C_3
	.quad	_L_1+2682
	.quad	_mod_pow2__mod_pow2_C_2
	.quad	_L_1+2695
	.quad	_mod_pow2__mod_pow2_C_1
	.quad	_L_1+2708
	.quad	_mod_pow2__mod_pow2_C_0
	.quad	_L_1+2721
	.quad	_mod_pow2__mod_pow2_I_63
	.quad	_L_1+2734
	.quad	_mod_pow2__mod_pow2_I_62
	.quad	_L_1+2748
	.quad	_mod_pow2__mod_pow2_I_61
	.quad	_L_1+2762
	.quad	_mod_pow2__mod_pow2_I_60
	.quad	_L_1+2776
	.quad	_mod_pow2__mod_pow2_I_59
	.quad	_L_1+2790
	.quad	_mod_pow2__mod_pow2_I_58
	.quad	_L_1+2804
	.quad	_mod_pow2__mod_pow2_I_57
	.quad	_L_1+2818
	.quad	_mod_pow2__mod_pow2_I_56
	.quad	_L_1+2832
	.quad	_mod_pow2__mod_pow2_I_55
	.quad	_L_1+2846
	.quad	_mod_pow2__mod_pow2_I_54
	.quad	_L_1+2860
	.quad	_mod_pow2__mod_pow2_I_53
	.quad	_L_1+2874
	.quad	_mod_pow2__mod_pow2_I_52
	.quad	_L_1+2888
	.quad	_mod_pow2__mod_pow2_I_51
	.quad	_L_1+2902
	.quad	_mod_pow2__mod_pow2_I_50
	.quad	_L_1+2916
	.quad	_mod_pow2__mod_pow2_I_49
	.quad	_L_1+2930
	.quad	_mod_pow2__mod_pow2_I_48
	.quad	_L_1+2944
	.quad	_mod_pow2__mod_pow2_I_47
	.quad	_L_1+2958
	.quad	_mod_pow2__mod_pow2_I_46
	.quad	_L_1+2972
	.quad	_mod_pow2__mod_pow2_I_45
	.quad	_L_1+2986
	.quad	_mod_pow2__mod_pow2_I_44
	.quad	_L_1+3000
	.quad	_mod_pow2__mod_pow2_I_43
	.quad	_L_1+3014
	.quad	_mod_pow2__mod_pow2_I_42
	.quad	_L_1+3028
	.quad	_mod_pow2__mod_pow2_I_41
	.quad	_L_1+3042
	.quad	_mod_pow2__mod_pow2_I_40
	.quad	_L_1+3056
	.quad	_mod_pow2__mod_pow2_I_39
	.quad	_L_1+3070
	.quad	_mod_pow2__mod_pow2_I_38
	.quad	_L_1+3084
	.quad	_mod_pow2__mod_pow2_I_37
	.quad	_L_1+3098
	.quad	_mod_pow2__mod_pow2_I_36
	.quad	_L_1+3112
	.quad	_mod_pow2__mod_pow2_I_35
	.quad	_L_1+3126
	.quad	_mod_pow2__mod_pow2_I_34
	.quad	_L_1+3140
	.quad	_mod_pow2__mod_pow2_I_33
	.quad	_L_1+3154
	.quad	_mod_pow2__mod_pow2_I_32
	.quad	_L_1+3168
	.quad	_mod_pow2__mod_pow2_I_31
	.quad	_L_1+3182
	.quad	_mod_pow2__mod_pow2_I_30
	.quad	_L_1+3196
	.quad	_mod_pow2__mod_pow2_I_29
	.quad	_L_1+3210
	.quad	_mod_pow2__mod_pow2_I_28
	.quad	_L_1+3224
	.quad	_mod_pow2__mod_pow2_I_27
	.quad	_L_1+3238
	.quad	_mod_pow2__mod_pow2_I_26
	.quad	_L_1+3252
	.quad	_mod_pow2__mod_pow2_I_25
	.quad	_L_1+3266
	.quad	_mod_pow2__mod_pow2_I_24
	.quad	_L_1+3280
	.quad	_mod_pow2__mod_pow2_I_23
	.quad	_L_1+3294
	.quad	_mod_pow2__mod_pow2_I_22
	.quad	_L_1+3308
	.quad	_mod_pow2__mod_pow2_I_21
	.quad	_L_1+3322
	.quad	_mod_pow2__mod_pow2_I_20
	.quad	_L_1+3336
	.quad	_mod_pow2__mod_pow2_I_19
	.quad	_L_1+3350
	.quad	_mod_pow2__mod_pow2_I_18
	.quad	_L_1+3364
	.quad	_mod_pow2__mod_pow2_I_17
	.quad	_L_1+3378
	.quad	_mod_pow2__mod_pow2_I_16
	.quad	_L_1+3392
	.quad	_mod_pow2__mod_pow2_I_15
	.quad	_L_1+3406
	.quad	_mod_pow2__mod_pow2_I_14
	.quad	_L_1+3420
	.quad	_mod_pow2__mod_pow2_I_13
	.quad	_L_1+3434
	.quad	_mod_pow2__mod_pow2_I_12
	.quad	_L_1+3448
	.quad	_mod_pow2__mod_pow2_I_11
	.quad	_L_1+3462
	.quad	_mod_pow2__mod_pow2_I_10
	.quad	_L_1+3476
	.quad	_mod_pow2__mod_pow2_I_9
	.quad	_L_1+3490
	.quad	_mod_pow2__mod_pow2_I_8
	.quad	_L_1+3503
	.quad	_mod_pow2__mod_pow2_I_7
	.quad	_L_1+3516
	.quad	_mod_pow2__mod_pow2_I_6
	.quad	_L_1+3529
	.quad	_mod_pow2__mod_pow2_I_5
	.quad	_L_1+3542
	.quad	_mod_pow2__mod_pow2_I_4
	.quad	_L_1+3555
	.quad	_mod_pow2__mod_pow2_I_3
	.quad	_L_1+3568
	.quad	_mod_pow2__mod_pow2_I_2
	.quad	_L_1+3581
	.quad	_mod_pow2__mod_pow2_I_1
	.quad	_L_1+3594
	.quad	_mod_pow2__mod_pow2_I_0
	.quad	_L_1+3607
	.quad	_mod_pow2__mod_pow2_u64_63
	.quad	_L_1+3620
	.quad	_mod_pow2__mod_pow2_u64_62
	.quad	_L_1+3636
	.quad	_mod_pow2__mod_pow2_u64_61
	.quad	_L_1+3652
	.quad	_mod_pow2__mod_pow2_u64_60
	.quad	_L_1+3668
	.quad	_mod_pow2__mod_pow2_u64_59
	.quad	_L_1+3684
	.quad	_mod_pow2__mod_pow2_u64_58
	.quad	_L_1+3700
	.quad	_mod_pow2__mod_pow2_u64_57
	.quad	_L_1+3716
	.quad	_mod_pow2__mod_pow2_u64_56
	.quad	_L_1+3732
	.quad	_mod_pow2__mod_pow2_u64_55
	.quad	_L_1+3748
	.quad	_mod_pow2__mod_pow2_u64_54
	.quad	_L_1+3764
	.quad	_mod_pow2__mod_pow2_u64_53
	.quad	_L_1+3780
	.quad	_mod_pow2__mod_pow2_u64_52
	.quad	_L_1+3796
	.quad	_mod_pow2__mod_pow2_u64_51
	.quad	_L_1+3812
	.quad	_mod_pow2__mod_pow2_u64_50
	.quad	_L_1+3828
	.quad	_mod_pow2__mod_pow2_u64_49
	.quad	_L_1+3844
	.quad	_mod_pow2__mod_pow2_u64_48
	.quad	_L_1+3860
	.quad	_mod_pow2__mod_pow2_u64_47
	.quad	_L_1+3876
	.quad	_mod_pow2__mod_pow2_u64_46
	.quad	_L_1+3892
	.quad	_mod_pow2__mod_pow2_u64_45
	.quad	_L_1+3908
	.quad	_mod_pow2__mod_pow2_u64_44
	.quad	_L_1+3924
	.quad	_mod_pow2__mod_pow2_u64_43
	.quad	_L_1+3940
	.quad	_mod_pow2__mod_pow2_u64_42
	.quad	_L_1+3956
	.quad	_mod_pow2__mod_pow2_u64_41
	.quad	_L_1+3972
	.quad	_mod_pow2__mod_pow2_u64_40
	.quad	_L_1+3988
	.quad	_mod_pow2__mod_pow2_u64_39
	.quad	_L_1+4004
	.quad	_mod_pow2__mod_pow2_u64_38
	.quad	_L_1+4020
	.quad	_mod_pow2__mod_pow2_u64_37
	.quad	_L_1+4036
	.quad	_mod_pow2__mod_pow2_u64_36
	.quad	_L_1+4052
	.quad	_mod_pow2__mod_pow2_u64_35
	.quad	_L_1+4068
	.quad	_mod_pow2__mod_pow2_u64_34
	.quad	_L_1+4084
	.quad	_mod_pow2__mod_pow2_u64_33
	.quad	_L_1+4100
	.quad	_mod_pow2__mod_pow2_u64_32
	.quad	_L_1+4116
	.quad	_mod_pow2__mod_pow2_u64_31
	.quad	_L_1+4132
	.quad	_mod_pow2__mod_pow2_u64_30
	.quad	_L_1+4148
	.quad	_mod_pow2__mod_pow2_u64_29
	.quad	_L_1+4164
	.quad	_mod_pow2__mod_pow2_u64_28
	.quad	_L_1+4180
	.quad	_mod_pow2__mod_pow2_u64_27
	.quad	_L_1+4196
	.quad	_mod_pow2__mod_pow2_u64_26
	.quad	_L_1+4212
	.quad	_mod_pow2__mod_pow2_u64_25
	.quad	_L_1+4228
	.quad	_mod_pow2__mod_pow2_u64_24
	.quad	_L_1+4244
	.quad	_mod_pow2__mod_pow2_u64_23
	.quad	_L_1+4260
	.quad	_mod_pow2__mod_pow2_u64_22
	.quad	_L_1+4276
	.quad	_mod_pow2__mod_pow2_u64_21
	.quad	_L_1+4292
	.quad	_mod_pow2__mod_pow2_u64_20
	.quad	_L_1+4308
	.quad	_mod_pow2__mod_pow2_u64_19
	.quad	_L_1+4324
	.quad	_mod_pow2__mod_pow2_u64_18
	.quad	_L_1+4340
	.quad	_mod_pow2__mod_pow2_u64_17
	.quad	_L_1+4356
	.quad	_mod_pow2__mod_pow2_u64_16
	.quad	_L_1+4372
	.quad	_mod_pow2__mod_pow2_u64_15
	.quad	_L_1+4388
	.quad	_mod_pow2__mod_pow2_u64_14
	.quad	_L_1+4404
	.quad	_mod_pow2__mod_pow2_u64_13
	.quad	_L_1+4420
	.quad	_mod_pow2__mod_pow2_u64_12
	.quad	_L_1+4436
	.quad	_mod_pow2__mod_pow2_u64_11
	.quad	_L_1+4452
	.quad	_mod_pow2__mod_pow2_u64_10
	.quad	_L_1+4468
	.quad	_mod_pow2__mod_pow2_u64_9
	.quad	_L_1+4484
	.quad	_mod_pow2__mod_pow2_u64_8
	.quad	_L_1+4499
	.quad	_mod_pow2__mod_pow2_u64_7
	.quad	_L_1+4514
	.quad	_mod_pow2__mod_pow2_u64_6
	.quad	_L_1+4529
	.quad	_mod_pow2__mod_pow2_u64_5
	.quad	_L_1+4544
	.quad	_mod_pow2__mod_pow2_u64_4
	.quad	_L_1+4559
	.quad	_mod_pow2__mod_pow2_u64_3
	.quad	_L_1+4574
	.quad	_mod_pow2__mod_pow2_u64_2
	.quad	_L_1+4589
	.quad	_mod_pow2__mod_pow2_u64_1
	.quad	_L_1+4604
	.quad	_mod_pow2__mod_pow2_u64_0
	.quad	_L_1+4619
	.quad	_mod_pow2__mod_pow2_i64_63
	.quad	_L_1+4634
	.quad	_mod_pow2__mod_pow2_i64_62
	.quad	_L_1+4650
	.quad	_mod_pow2__mod_pow2_i64_61
	.quad	_L_1+4666
	.quad	_mod_pow2__mod_pow2_i64_60
	.quad	_L_1+4682
	.quad	_mod_pow2__mod_pow2_i64_59
	.quad	_L_1+4698
	.quad	_mod_pow2__mod_pow2_i64_58
	.quad	_L_1+4714
	.quad	_mod_pow2__mod_pow2_i64_57
	.quad	_L_1+4730
	.quad	_mod_pow2__mod_pow2_i64_56
	.quad	_L_1+4746
	.quad	_mod_pow2__mod_pow2_i64_55
	.quad	_L_1+4762
	.quad	_mod_pow2__mod_pow2_i64_54
	.quad	_L_1+4778
	.quad	_mod_pow2__mod_pow2_i64_53
	.quad	_L_1+4794
	.quad	_mod_pow2__mod_pow2_i64_52
	.quad	_L_1+4810
	.quad	_mod_pow2__mod_pow2_i64_51
	.quad	_L_1+4826
	.quad	_mod_pow2__mod_pow2_i64_50
	.quad	_L_1+4842
	.quad	_mod_pow2__mod_pow2_i64_49
	.quad	_L_1+4858
	.quad	_mod_pow2__mod_pow2_i64_48
	.quad	_L_1+4874
	.quad	_mod_pow2__mod_pow2_i64_47
	.quad	_L_1+4890
	.quad	_mod_pow2__mod_pow2_i64_46
	.quad	_L_1+4906
	.quad	_mod_pow2__mod_pow2_i64_45
	.quad	_L_1+4922
	.quad	_mod_pow2__mod_pow2_i64_44
	.quad	_L_1+4938
	.quad	_mod_pow2__mod_pow2_i64_43
	.quad	_L_1+4954
	.quad	_mod_pow2__mod_pow2_i64_42
	.quad	_L_1+4970
	.quad	_mod_pow2__mod_pow2_i64_41
	.quad	_L_1+4986
	.quad	_mod_pow2__mod_pow2_i64_40
	.quad	_L_1+5002
	.quad	_mod_pow2__mod_pow2_i64_39
	.quad	_L_1+5018
	.quad	_mod_pow2__mod_pow2_i64_38
	.quad	_L_1+5034
	.quad	_mod_pow2__mod_pow2_i64_37
	.quad	_L_1+5050
	.quad	_mod_pow2__mod_pow2_i64_36
	.quad	_L_1+5066
	.quad	_mod_pow2__mod_pow2_i64_35
	.quad	_L_1+5082
	.quad	_mod_pow2__mod_pow2_i64_34
	.quad	_L_1+5098
	.quad	_mod_pow2__mod_pow2_i64_33
	.quad	_L_1+5114
	.quad	_mod_pow2__mod_pow2_i64_32
	.quad	_L_1+5130
	.quad	_mod_pow2__mod_pow2_i64_31
	.quad	_L_1+5146
	.quad	_mod_pow2__mod_pow2_i64_30
	.quad	_L_1+5162
	.quad	_mod_pow2__mod_pow2_i64_29
	.quad	_L_1+5178
	.quad	_mod_pow2__mod_pow2_i64_28
	.quad	_L_1+5194
	.quad	_mod_pow2__mod_pow2_i64_27
	.quad	_L_1+5210
	.quad	_mod_pow2__mod_pow2_i64_26
	.quad	_L_1+5226
	.quad	_mod_pow2__mod_pow2_i64_25
	.quad	_L_1+5242
	.quad	_mod_pow2__mod_pow2_i64_24
	.quad	_L_1+5258
	.quad	_mod_pow2__mod_pow2_i64_23
	.quad	_L_1+5274
	.quad	_mod_pow2__mod_pow2_i64_22
	.quad	_L_1+5290
	.quad	_mod_pow2__mod_pow2_i64_21
	.quad	_L_1+5306
	.quad	_mod_pow2__mod_pow2_i64_20
	.quad	_L_1+5322
	.quad	_mod_pow2__mod_pow2_i64_19
	.quad	_L_1+5338
	.quad	_mod_pow2__mod_pow2_i64_18
	.quad	_L_1+5354
	.quad	_mod_pow2__mod_pow2_i64_17
	.quad	_L_1+5370
	.quad	_mod_pow2__mod_pow2_i64_16
	.quad	_L_1+5386
	.quad	_mod_pow2__mod_pow2_i64_15
	.quad	_L_1+5402
	.quad	_mod_pow2__mod_pow2_i64_14
	.quad	_L_1+5418
	.quad	_mod_pow2__mod_pow2_i64_13
	.quad	_L_1+5434
	.quad	_mod_pow2__mod_pow2_i64_12
	.quad	_L_1+5450
	.quad	_mod_pow2__mod_pow2_i64_11
	.quad	_L_1+5466
	.quad	_mod_pow2__mod_pow2_i64_10
	.quad	_L_1+5482
	.quad	_mod_pow2__mod_pow2_i64_9
	.quad	_L_1+5498
	.quad	_mod_pow2__mod_pow2_i64_8
	.quad	_L_1+5513
	.quad	_mod_pow2__mod_pow2_i64_7
	.quad	_L_1+5528
	.quad	_mod_pow2__mod_pow2_i64_6
	.quad	_L_1+5543
	.quad	_mod_pow2__mod_pow2_i64_5
	.quad	_L_1+5558
	.quad	_mod_pow2__mod_pow2_i64_4
	.quad	_L_1+5573
	.quad	_mod_pow2__mod_pow2_i64_3
	.quad	_L_1+5588
	.quad	_mod_pow2__mod_pow2_i64_2
	.quad	_L_1+5603
	.quad	_mod_pow2__mod_pow2_i64_1
	.quad	_L_1+5618
	.quad	_mod_pow2__mod_pow2_i64_0
	.quad	_L_1+5633
	.quad	_mod_pow2__mod_pow2_u32_31
	.quad	_L_1+5648
	.quad	_mod_pow2__mod_pow2_u32_30
	.quad	_L_1+5664
	.quad	_mod_pow2__mod_pow2_u32_29
	.quad	_L_1+5680
	.quad	_mod_pow2__mod_pow2_u32_28
	.quad	_L_1+5696
	.quad	_mod_pow2__mod_pow2_u32_27
	.quad	_L_1+5712
	.quad	_mod_pow2__mod_pow2_u32_26
	.quad	_L_1+5728
	.quad	_mod_pow2__mod_pow2_u32_25
	.quad	_L_1+5744
	.quad	_mod_pow2__mod_pow2_u32_24
	.quad	_L_1+5760
	.quad	_mod_pow2__mod_pow2_u32_23
	.quad	_L_1+5776
	.quad	_mod_pow2__mod_pow2_u32_22
	.quad	_L_1+5792
	.quad	_mod_pow2__mod_pow2_u32_21
	.quad	_L_1+5808
	.quad	_mod_pow2__mod_pow2_u32_20
	.quad	_L_1+5824
	.quad	_mod_pow2__mod_pow2_u32_19
	.quad	_L_1+5840
	.quad	_mod_pow2__mod_pow2_u32_18
	.quad	_L_1+5856
	.quad	_mod_pow2__mod_pow2_u32_17
	.quad	_L_1+5872
	.quad	_mod_pow2__mod_pow2_u32_16
	.quad	_L_1+5888
	.quad	_mod_pow2__mod_pow2_u32_15
	.quad	_L_1+5904
	.quad	_mod_pow2__mod_pow2_u32_14
	.quad	_L_1+5920
	.quad	_mod_pow2__mod_pow2_u32_13
	.quad	_L_1+5936
	.quad	_mod_pow2__mod_pow2_u32_12
	.quad	_L_1+5952
	.quad	_mod_pow2__mod_pow2_u32_11
	.quad	_L_1+5968
	.quad	_mod_pow2__mod_pow2_u32_10
	.quad	_L_1+5984
	.quad	_mod_pow2__mod_pow2_u32_9
	.quad	_L_1+6000
	.quad	_mod_pow2__mod_pow2_u32_8
	.quad	_L_1+6015
	.quad	_mod_pow2__mod_pow2_u32_7
	.quad	_L_1+6030
	.quad	_mod_pow2__mod_pow2_u32_6
	.quad	_L_1+6045
	.quad	_mod_pow2__mod_pow2_u32_5
	.quad	_L_1+6060
	.quad	_mod_pow2__mod_pow2_u32_4
	.quad	_L_1+6075
	.quad	_mod_pow2__mod_pow2_u32_3
	.quad	_L_1+6090
	.quad	_mod_pow2__mod_pow2_u32_2
	.quad	_L_1+6105
	.quad	_mod_pow2__mod_pow2_u32_1
	.quad	_L_1+6120
	.quad	_mod_pow2__mod_pow2_u32_0
	.quad	_L_1+6135
	.quad	_mod_pow2__mod_pow2_i32_31
	.quad	_L_1+6150
	.quad	_mod_pow2__mod_pow2_i32_30
	.quad	_L_1+6166
	.quad	_mod_pow2__mod_pow2_i32_29
	.quad	_L_1+6182
	.quad	_mod_pow2__mod_pow2_i32_28
	.quad	_L_1+6198
	.quad	_mod_pow2__mod_pow2_i32_27
	.quad	_L_1+6214
	.quad	_mod_pow2__mod_pow2_i32_26
	.quad	_L_1+6230
	.quad	_mod_pow2__mod_pow2_i32_25
	.quad	_L_1+6246
	.quad	_mod_pow2__mod_pow2_i32_24
	.quad	_L_1+6262
	.quad	_mod_pow2__mod_pow2_i32_23
	.quad	_L_1+6278
	.quad	_mod_pow2__mod_pow2_i32_22
	.quad	_L_1+6294
	.quad	_mod_pow2__mod_pow2_i32_21
	.quad	_L_1+6310
	.quad	_mod_pow2__mod_pow2_i32_20
	.quad	_L_1+6326
	.quad	_mod_pow2__mod_pow2_i32_19
	.quad	_L_1+6342
	.quad	_mod_pow2__mod_pow2_i32_18
	.quad	_L_1+6358
	.quad	_mod_pow2__mod_pow2_i32_17
	.quad	_L_1+6374
	.quad	_mod_pow2__mod_pow2_i32_16
	.quad	_L_1+6390
	.quad	_mod_pow2__mod_pow2_i32_15
	.quad	_L_1+6406
	.quad	_mod_pow2__mod_pow2_i32_14
	.quad	_L_1+6422
	.quad	_mod_pow2__mod_pow2_i32_13
	.quad	_L_1+6438
	.quad	_mod_pow2__mod_pow2_i32_12
	.quad	_L_1+6454
	.quad	_mod_pow2__mod_pow2_i32_11
	.quad	_L_1+6470
	.quad	_mod_pow2__mod_pow2_i32_10
	.quad	_L_1+6486
	.quad	_mod_pow2__mod_pow2_i32_9
	.quad	_L_1+6502
	.quad	_mod_pow2__mod_pow2_i32_8
	.quad	_L_1+6517
	.quad	_mod_pow2__mod_pow2_i32_7
	.quad	_L_1+6532
	.quad	_mod_pow2__mod_pow2_i32_6
	.quad	_L_1+6547
	.quad	_mod_pow2__mod_pow2_i32_5
	.quad	_L_1+6562
	.quad	_mod_pow2__mod_pow2_i32_4
	.quad	_L_1+6577
	.quad	_mod_pow2__mod_pow2_i32_3
	.quad	_L_1+6592
	.quad	_mod_pow2__mod_pow2_i32_2
	.quad	_L_1+6607
	.quad	_mod_pow2__mod_pow2_i32_1
	.quad	_L_1+6622
	.quad	_mod_pow2__mod_pow2_i32_0
	.quad	_L_1+6637
	.space 8
	.ascii "../AMD64_DARWIN/mod_pow2.m3"
	.space 5
	.data
	.align 5
_MM_mod_pow2:
	.quad	_L_1+13848
	.space 32
	.quad	_L_1+6656
	.space 24
	.quad	_MM_mod_pow2+208
	.space 8
	.quad	_mod_pow2_M3
	.quad	3
	.quad	945
	.quad	946
	.long	1147993260
	.byte	-75
	.space 3
	.quad	950
	.byte	-73
	.space 3
	.long	952
	.quad	953
	.word	954
	.space 6
	.quad	955
	.long	4020089389
	.long	1083041703
	.quad	958
	.word	959
	.space 2
	.long	960
	.space 24
	.quad	_mod_pow2_I3
	.quad	_MM_mod_pow2+232
	.space 8
	.quad	_Long_I3
	.quad	_MM_mod_pow2+256
	.space 8
	.quad	_Word_I3
	.quad	_MM_mod_pow2+280
	.space 8
	.quad	_Cstdint_I3
	.quad	_MM_mod_pow2+304
	.space 8
	.quad	_RTHooks_I3
	.space 8
	.subsections_via_symbols
