	.text
.globl _return_parameter_convert__ret_i64_i64
	.private_extern _return_parameter_convert__ret_i64_i64
_return_parameter_convert__ret_i64_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_LC
	.private_extern _return_parameter_convert__ret_i64_LC
_return_parameter_convert__ret_i64_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_u8
	.private_extern _return_parameter_convert__ret_i64_u8
_return_parameter_convert__ret_i64_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_I
	.private_extern _return_parameter_convert__ret_i64_I
_return_parameter_convert__ret_i64_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_i8
	.private_extern _return_parameter_convert__ret_i64_i8
_return_parameter_convert__ret_i64_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_C
	.private_extern _return_parameter_convert__ret_i64_C
_return_parameter_convert__ret_i64_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_u32
	.private_extern _return_parameter_convert__ret_i64_u32
_return_parameter_convert__ret_i64_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_u16
	.private_extern _return_parameter_convert__ret_i64_u16
_return_parameter_convert__ret_i64_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_u64
	.private_extern _return_parameter_convert__ret_i64_u64
_return_parameter_convert__ret_i64_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_L
	.private_extern _return_parameter_convert__ret_i64_L
_return_parameter_convert__ret_i64_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_i16
	.private_extern _return_parameter_convert__ret_i64_i16
_return_parameter_convert__ret_i64_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_i32
	.private_extern _return_parameter_convert__ret_i64_i32
_return_parameter_convert__ret_i64_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_i64
	.private_extern _return_parameter_convert__ret_LC_i64
_return_parameter_convert__ret_LC_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_LC
	.private_extern _return_parameter_convert__ret_LC_LC
_return_parameter_convert__ret_LC_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_u8
	.private_extern _return_parameter_convert__ret_LC_u8
_return_parameter_convert__ret_LC_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_I
	.private_extern _return_parameter_convert__ret_LC_I
_return_parameter_convert__ret_LC_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_i8
	.private_extern _return_parameter_convert__ret_LC_i8
_return_parameter_convert__ret_LC_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_C
	.private_extern _return_parameter_convert__ret_LC_C
_return_parameter_convert__ret_LC_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_u32
	.private_extern _return_parameter_convert__ret_LC_u32
_return_parameter_convert__ret_LC_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_u16
	.private_extern _return_parameter_convert__ret_LC_u16
_return_parameter_convert__ret_LC_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_u64
	.private_extern _return_parameter_convert__ret_LC_u64
_return_parameter_convert__ret_LC_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_L
	.private_extern _return_parameter_convert__ret_LC_L
_return_parameter_convert__ret_LC_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_i16
	.private_extern _return_parameter_convert__ret_LC_i16
_return_parameter_convert__ret_LC_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_i32
	.private_extern _return_parameter_convert__ret_LC_i32
_return_parameter_convert__ret_LC_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_i64
	.private_extern _return_parameter_convert__ret_u8_i64
_return_parameter_convert__ret_u8_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_LC
	.private_extern _return_parameter_convert__ret_u8_LC
_return_parameter_convert__ret_u8_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_u8
	.private_extern _return_parameter_convert__ret_u8_u8
_return_parameter_convert__ret_u8_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_I
	.private_extern _return_parameter_convert__ret_u8_I
_return_parameter_convert__ret_u8_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_i8
	.private_extern _return_parameter_convert__ret_u8_i8
_return_parameter_convert__ret_u8_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_C
	.private_extern _return_parameter_convert__ret_u8_C
_return_parameter_convert__ret_u8_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_u32
	.private_extern _return_parameter_convert__ret_u8_u32
_return_parameter_convert__ret_u8_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_u16
	.private_extern _return_parameter_convert__ret_u8_u16
_return_parameter_convert__ret_u8_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_u64
	.private_extern _return_parameter_convert__ret_u8_u64
_return_parameter_convert__ret_u8_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_L
	.private_extern _return_parameter_convert__ret_u8_L
_return_parameter_convert__ret_u8_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_i16
	.private_extern _return_parameter_convert__ret_u8_i16
_return_parameter_convert__ret_u8_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_i32
	.private_extern _return_parameter_convert__ret_u8_i32
_return_parameter_convert__ret_u8_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_I_i64
	.private_extern _return_parameter_convert__ret_I_i64
_return_parameter_convert__ret_I_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_LC
	.private_extern _return_parameter_convert__ret_I_LC
_return_parameter_convert__ret_I_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_u8
	.private_extern _return_parameter_convert__ret_I_u8
_return_parameter_convert__ret_I_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_I
	.private_extern _return_parameter_convert__ret_I_I
_return_parameter_convert__ret_I_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_i8
	.private_extern _return_parameter_convert__ret_I_i8
_return_parameter_convert__ret_I_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_C
	.private_extern _return_parameter_convert__ret_I_C
_return_parameter_convert__ret_I_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_u32
	.private_extern _return_parameter_convert__ret_I_u32
_return_parameter_convert__ret_I_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_u16
	.private_extern _return_parameter_convert__ret_I_u16
_return_parameter_convert__ret_I_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_u64
	.private_extern _return_parameter_convert__ret_I_u64
_return_parameter_convert__ret_I_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_L
	.private_extern _return_parameter_convert__ret_I_L
_return_parameter_convert__ret_I_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_i16
	.private_extern _return_parameter_convert__ret_I_i16
_return_parameter_convert__ret_I_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_i32
	.private_extern _return_parameter_convert__ret_I_i32
_return_parameter_convert__ret_I_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i8_i64
	.private_extern _return_parameter_convert__ret_i8_i64
_return_parameter_convert__ret_i8_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_LC
	.private_extern _return_parameter_convert__ret_i8_LC
_return_parameter_convert__ret_i8_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_u8
	.private_extern _return_parameter_convert__ret_i8_u8
_return_parameter_convert__ret_i8_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_I
	.private_extern _return_parameter_convert__ret_i8_I
_return_parameter_convert__ret_i8_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_i8
	.private_extern _return_parameter_convert__ret_i8_i8
_return_parameter_convert__ret_i8_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_C
	.private_extern _return_parameter_convert__ret_i8_C
_return_parameter_convert__ret_i8_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_u32
	.private_extern _return_parameter_convert__ret_i8_u32
_return_parameter_convert__ret_i8_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_u16
	.private_extern _return_parameter_convert__ret_i8_u16
_return_parameter_convert__ret_i8_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_u64
	.private_extern _return_parameter_convert__ret_i8_u64
_return_parameter_convert__ret_i8_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_L
	.private_extern _return_parameter_convert__ret_i8_L
_return_parameter_convert__ret_i8_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_i16
	.private_extern _return_parameter_convert__ret_i8_i16
_return_parameter_convert__ret_i8_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_i32
	.private_extern _return_parameter_convert__ret_i8_i32
_return_parameter_convert__ret_i8_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_C_i64
	.private_extern _return_parameter_convert__ret_C_i64
_return_parameter_convert__ret_C_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_LC
	.private_extern _return_parameter_convert__ret_C_LC
_return_parameter_convert__ret_C_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_u8
	.private_extern _return_parameter_convert__ret_C_u8
_return_parameter_convert__ret_C_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_I
	.private_extern _return_parameter_convert__ret_C_I
_return_parameter_convert__ret_C_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_i8
	.private_extern _return_parameter_convert__ret_C_i8
_return_parameter_convert__ret_C_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_C
	.private_extern _return_parameter_convert__ret_C_C
_return_parameter_convert__ret_C_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_u32
	.private_extern _return_parameter_convert__ret_C_u32
_return_parameter_convert__ret_C_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_u16
	.private_extern _return_parameter_convert__ret_C_u16
_return_parameter_convert__ret_C_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_u64
	.private_extern _return_parameter_convert__ret_C_u64
_return_parameter_convert__ret_C_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_L
	.private_extern _return_parameter_convert__ret_C_L
_return_parameter_convert__ret_C_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_i16
	.private_extern _return_parameter_convert__ret_C_i16
_return_parameter_convert__ret_C_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_i32
	.private_extern _return_parameter_convert__ret_C_i32
_return_parameter_convert__ret_C_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u32_i64
	.private_extern _return_parameter_convert__ret_u32_i64
_return_parameter_convert__ret_u32_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_LC
	.private_extern _return_parameter_convert__ret_u32_LC
_return_parameter_convert__ret_u32_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_u8
	.private_extern _return_parameter_convert__ret_u32_u8
_return_parameter_convert__ret_u32_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_I
	.private_extern _return_parameter_convert__ret_u32_I
_return_parameter_convert__ret_u32_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_i8
	.private_extern _return_parameter_convert__ret_u32_i8
_return_parameter_convert__ret_u32_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_C
	.private_extern _return_parameter_convert__ret_u32_C
_return_parameter_convert__ret_u32_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_u32
	.private_extern _return_parameter_convert__ret_u32_u32
_return_parameter_convert__ret_u32_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_u16
	.private_extern _return_parameter_convert__ret_u32_u16
_return_parameter_convert__ret_u32_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_u64
	.private_extern _return_parameter_convert__ret_u32_u64
_return_parameter_convert__ret_u32_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_L
	.private_extern _return_parameter_convert__ret_u32_L
_return_parameter_convert__ret_u32_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_i16
	.private_extern _return_parameter_convert__ret_u32_i16
_return_parameter_convert__ret_u32_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_i32
	.private_extern _return_parameter_convert__ret_u32_i32
_return_parameter_convert__ret_u32_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u16_i64
	.private_extern _return_parameter_convert__ret_u16_i64
_return_parameter_convert__ret_u16_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_LC
	.private_extern _return_parameter_convert__ret_u16_LC
_return_parameter_convert__ret_u16_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_u8
	.private_extern _return_parameter_convert__ret_u16_u8
_return_parameter_convert__ret_u16_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_I
	.private_extern _return_parameter_convert__ret_u16_I
_return_parameter_convert__ret_u16_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_i8
	.private_extern _return_parameter_convert__ret_u16_i8
_return_parameter_convert__ret_u16_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_C
	.private_extern _return_parameter_convert__ret_u16_C
_return_parameter_convert__ret_u16_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_u32
	.private_extern _return_parameter_convert__ret_u16_u32
_return_parameter_convert__ret_u16_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_u16
	.private_extern _return_parameter_convert__ret_u16_u16
_return_parameter_convert__ret_u16_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_u64
	.private_extern _return_parameter_convert__ret_u16_u64
_return_parameter_convert__ret_u16_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_L
	.private_extern _return_parameter_convert__ret_u16_L
_return_parameter_convert__ret_u16_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_i16
	.private_extern _return_parameter_convert__ret_u16_i16
_return_parameter_convert__ret_u16_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_i32
	.private_extern _return_parameter_convert__ret_u16_i32
_return_parameter_convert__ret_u16_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_i64
	.private_extern _return_parameter_convert__ret_u64_i64
_return_parameter_convert__ret_u64_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_LC
	.private_extern _return_parameter_convert__ret_u64_LC
_return_parameter_convert__ret_u64_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_u8
	.private_extern _return_parameter_convert__ret_u64_u8
_return_parameter_convert__ret_u64_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_I
	.private_extern _return_parameter_convert__ret_u64_I
_return_parameter_convert__ret_u64_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_i8
	.private_extern _return_parameter_convert__ret_u64_i8
_return_parameter_convert__ret_u64_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_C
	.private_extern _return_parameter_convert__ret_u64_C
_return_parameter_convert__ret_u64_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_u32
	.private_extern _return_parameter_convert__ret_u64_u32
_return_parameter_convert__ret_u64_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_u16
	.private_extern _return_parameter_convert__ret_u64_u16
_return_parameter_convert__ret_u64_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_u64
	.private_extern _return_parameter_convert__ret_u64_u64
_return_parameter_convert__ret_u64_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_L
	.private_extern _return_parameter_convert__ret_u64_L
_return_parameter_convert__ret_u64_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_i16
	.private_extern _return_parameter_convert__ret_u64_i16
_return_parameter_convert__ret_u64_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_i32
	.private_extern _return_parameter_convert__ret_u64_i32
_return_parameter_convert__ret_u64_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_i64
	.private_extern _return_parameter_convert__ret_L_i64
_return_parameter_convert__ret_L_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_LC
	.private_extern _return_parameter_convert__ret_L_LC
_return_parameter_convert__ret_L_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_u8
	.private_extern _return_parameter_convert__ret_L_u8
_return_parameter_convert__ret_L_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_I
	.private_extern _return_parameter_convert__ret_L_I
_return_parameter_convert__ret_L_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_i8
	.private_extern _return_parameter_convert__ret_L_i8
_return_parameter_convert__ret_L_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_C
	.private_extern _return_parameter_convert__ret_L_C
_return_parameter_convert__ret_L_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_u32
	.private_extern _return_parameter_convert__ret_L_u32
_return_parameter_convert__ret_L_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_u16
	.private_extern _return_parameter_convert__ret_L_u16
_return_parameter_convert__ret_L_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_u64
	.private_extern _return_parameter_convert__ret_L_u64
_return_parameter_convert__ret_L_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_L
	.private_extern _return_parameter_convert__ret_L_L
_return_parameter_convert__ret_L_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_i16
	.private_extern _return_parameter_convert__ret_L_i16
_return_parameter_convert__ret_L_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_i32
	.private_extern _return_parameter_convert__ret_L_i32
_return_parameter_convert__ret_L_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i16_i64
	.private_extern _return_parameter_convert__ret_i16_i64
_return_parameter_convert__ret_i16_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_LC
	.private_extern _return_parameter_convert__ret_i16_LC
_return_parameter_convert__ret_i16_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_u8
	.private_extern _return_parameter_convert__ret_i16_u8
_return_parameter_convert__ret_i16_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_I
	.private_extern _return_parameter_convert__ret_i16_I
_return_parameter_convert__ret_i16_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_i8
	.private_extern _return_parameter_convert__ret_i16_i8
_return_parameter_convert__ret_i16_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_C
	.private_extern _return_parameter_convert__ret_i16_C
_return_parameter_convert__ret_i16_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_u32
	.private_extern _return_parameter_convert__ret_i16_u32
_return_parameter_convert__ret_i16_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_u16
	.private_extern _return_parameter_convert__ret_i16_u16
_return_parameter_convert__ret_i16_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_u64
	.private_extern _return_parameter_convert__ret_i16_u64
_return_parameter_convert__ret_i16_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_L
	.private_extern _return_parameter_convert__ret_i16_L
_return_parameter_convert__ret_i16_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_i16
	.private_extern _return_parameter_convert__ret_i16_i16
_return_parameter_convert__ret_i16_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_i32
	.private_extern _return_parameter_convert__ret_i16_i32
_return_parameter_convert__ret_i16_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_i64
	.private_extern _return_parameter_convert__ret_i32_i64
_return_parameter_convert__ret_i32_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_LC
	.private_extern _return_parameter_convert__ret_i32_LC
_return_parameter_convert__ret_i32_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_u8
	.private_extern _return_parameter_convert__ret_i32_u8
_return_parameter_convert__ret_i32_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_I
	.private_extern _return_parameter_convert__ret_i32_I
_return_parameter_convert__ret_i32_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_i8
	.private_extern _return_parameter_convert__ret_i32_i8
_return_parameter_convert__ret_i32_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_C
	.private_extern _return_parameter_convert__ret_i32_C
_return_parameter_convert__ret_i32_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_u32
	.private_extern _return_parameter_convert__ret_i32_u32
_return_parameter_convert__ret_i32_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_u16
	.private_extern _return_parameter_convert__ret_i32_u16
_return_parameter_convert__ret_i32_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_u64
	.private_extern _return_parameter_convert__ret_i32_u64
_return_parameter_convert__ret_i32_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_L
	.private_extern _return_parameter_convert__ret_i32_L
_return_parameter_convert__ret_i32_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_i16
	.private_extern _return_parameter_convert__ret_i32_i16
_return_parameter_convert__ret_i32_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_i32
	.private_extern _return_parameter_convert__ret_i32_i32
_return_parameter_convert__ret_i32_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert_M3
_return_parameter_convert_M3:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -8(%rbp)
	leaq	_MM_return_parameter_convert(%rip), %rax
	leave
	ret
	.const_data
	.align 5
_L_1:
	.ascii "return_parameter_convert_M3"
	.space 1
	.ascii "ret_i32_i32"
	.space 1
	.ascii "ret_i32_i16"
	.space 1
	.ascii "ret_i32_L"
	.space 1
	.ascii "ret_i32_u64"
	.space 1
	.ascii "ret_i32_u16"
	.space 1
	.ascii "ret_i32_u32"
	.space 1
	.ascii "ret_i32_C"
	.space 1
	.ascii "ret_i32_i8"
	.space 1
	.ascii "ret_i32_I"
	.space 1
	.ascii "ret_i32_u8"
	.space 1
	.ascii "ret_i32_LC"
	.space 1
	.ascii "ret_i32_i64"
	.space 1
	.ascii "ret_i16_i32"
	.space 1
	.ascii "ret_i16_i16"
	.space 1
	.ascii "ret_i16_L"
	.space 1
	.ascii "ret_i16_u64"
	.space 1
	.ascii "ret_i16_u16"
	.space 1
	.ascii "ret_i16_u32"
	.space 1
	.ascii "ret_i16_C"
	.space 1
	.ascii "ret_i16_i8"
	.space 1
	.ascii "ret_i16_I"
	.space 1
	.ascii "ret_i16_u8"
	.space 1
	.ascii "ret_i16_LC"
	.space 1
	.ascii "ret_i16_i64"
	.space 1
	.ascii "ret_L_i32"
	.space 1
	.ascii "ret_L_i16"
	.space 1
	.ascii "ret_L_L"
	.space 1
	.ascii "ret_L_u64"
	.space 1
	.ascii "ret_L_u16"
	.space 1
	.ascii "ret_L_u32"
	.space 1
	.ascii "ret_L_C"
	.space 1
	.ascii "ret_L_i8"
	.space 1
	.ascii "ret_L_I"
	.space 1
	.ascii "ret_L_u8"
	.space 1
	.ascii "ret_L_LC"
	.space 1
	.ascii "ret_L_i64"
	.space 1
	.ascii "ret_u64_i32"
	.space 1
	.ascii "ret_u64_i16"
	.space 1
	.ascii "ret_u64_L"
	.space 1
	.ascii "ret_u64_u64"
	.space 1
	.ascii "ret_u64_u16"
	.space 1
	.ascii "ret_u64_u32"
	.space 1
	.ascii "ret_u64_C"
	.space 1
	.ascii "ret_u64_i8"
	.space 1
	.ascii "ret_u64_I"
	.space 1
	.ascii "ret_u64_u8"
	.space 1
	.ascii "ret_u64_LC"
	.space 1
	.ascii "ret_u64_i64"
	.space 1
	.ascii "ret_u16_i32"
	.space 1
	.ascii "ret_u16_i16"
	.space 1
	.ascii "ret_u16_L"
	.space 1
	.ascii "ret_u16_u64"
	.space 1
	.ascii "ret_u16_u16"
	.space 1
	.ascii "ret_u16_u32"
	.space 1
	.ascii "ret_u16_C"
	.space 1
	.ascii "ret_u16_i8"
	.space 1
	.ascii "ret_u16_I"
	.space 1
	.ascii "ret_u16_u8"
	.space 1
	.ascii "ret_u16_LC"
	.space 1
	.ascii "ret_u16_i64"
	.space 1
	.ascii "ret_u32_i32"
	.space 1
	.ascii "ret_u32_i16"
	.space 1
	.ascii "ret_u32_L"
	.space 1
	.ascii "ret_u32_u64"
	.space 1
	.ascii "ret_u32_u16"
	.space 1
	.ascii "ret_u32_u32"
	.space 1
	.ascii "ret_u32_C"
	.space 1
	.ascii "ret_u32_i8"
	.space 1
	.ascii "ret_u32_I"
	.space 1
	.ascii "ret_u32_u8"
	.space 1
	.ascii "ret_u32_LC"
	.space 1
	.ascii "ret_u32_i64"
	.space 1
	.ascii "ret_C_i32"
	.space 1
	.ascii "ret_C_i16"
	.space 1
	.ascii "ret_C_L"
	.space 1
	.ascii "ret_C_u64"
	.space 1
	.ascii "ret_C_u16"
	.space 1
	.ascii "ret_C_u32"
	.space 1
	.ascii "ret_C_C"
	.space 1
	.ascii "ret_C_i8"
	.space 1
	.ascii "ret_C_I"
	.space 1
	.ascii "ret_C_u8"
	.space 1
	.ascii "ret_C_LC"
	.space 1
	.ascii "ret_C_i64"
	.space 1
	.ascii "ret_i8_i32"
	.space 1
	.ascii "ret_i8_i16"
	.space 1
	.ascii "ret_i8_L"
	.space 1
	.ascii "ret_i8_u64"
	.space 1
	.ascii "ret_i8_u16"
	.space 1
	.ascii "ret_i8_u32"
	.space 1
	.ascii "ret_i8_C"
	.space 1
	.ascii "ret_i8_i8"
	.space 1
	.ascii "ret_i8_I"
	.space 1
	.ascii "ret_i8_u8"
	.space 1
	.ascii "ret_i8_LC"
	.space 1
	.ascii "ret_i8_i64"
	.space 1
	.ascii "ret_I_i32"
	.space 1
	.ascii "ret_I_i16"
	.space 1
	.ascii "ret_I_L"
	.space 1
	.ascii "ret_I_u64"
	.space 1
	.ascii "ret_I_u16"
	.space 1
	.ascii "ret_I_u32"
	.space 1
	.ascii "ret_I_C"
	.space 1
	.ascii "ret_I_i8"
	.space 1
	.ascii "ret_I_I"
	.space 1
	.ascii "ret_I_u8"
	.space 1
	.ascii "ret_I_LC"
	.space 1
	.ascii "ret_I_i64"
	.space 1
	.ascii "ret_u8_i32"
	.space 1
	.ascii "ret_u8_i16"
	.space 1
	.ascii "ret_u8_L"
	.space 1
	.ascii "ret_u8_u64"
	.space 1
	.ascii "ret_u8_u16"
	.space 1
	.ascii "ret_u8_u32"
	.space 1
	.ascii "ret_u8_C"
	.space 1
	.ascii "ret_u8_i8"
	.space 1
	.ascii "ret_u8_I"
	.space 1
	.ascii "ret_u8_u8"
	.space 1
	.ascii "ret_u8_LC"
	.space 1
	.ascii "ret_u8_i64"
	.space 1
	.ascii "ret_LC_i32"
	.space 1
	.ascii "ret_LC_i16"
	.space 1
	.ascii "ret_LC_L"
	.space 1
	.ascii "ret_LC_u64"
	.space 1
	.ascii "ret_LC_u16"
	.space 1
	.ascii "ret_LC_u32"
	.space 1
	.ascii "ret_LC_C"
	.space 1
	.ascii "ret_LC_i8"
	.space 1
	.ascii "ret_LC_I"
	.space 1
	.ascii "ret_LC_u8"
	.space 1
	.ascii "ret_LC_LC"
	.space 1
	.ascii "ret_LC_i64"
	.space 1
	.ascii "ret_i64_i32"
	.space 1
	.ascii "ret_i64_i16"
	.space 1
	.ascii "ret_i64_L"
	.space 1
	.ascii "ret_i64_u64"
	.space 1
	.ascii "ret_i64_u16"
	.space 1
	.ascii "ret_i64_u32"
	.space 1
	.ascii "ret_i64_C"
	.space 1
	.ascii "ret_i64_i8"
	.space 1
	.ascii "ret_i64_I"
	.space 1
	.ascii "ret_i64_u8"
	.space 1
	.ascii "ret_i64_LC"
	.space 1
	.ascii "ret_i64_i64"
	.space 5
	.quad	_return_parameter_convert_M3
	.quad	_L_1
	.quad	_return_parameter_convert__ret_i32_i32
	.quad	_L_1+28
	.quad	_return_parameter_convert__ret_i32_i16
	.quad	_L_1+40
	.quad	_return_parameter_convert__ret_i32_L
	.quad	_L_1+52
	.quad	_return_parameter_convert__ret_i32_u64
	.quad	_L_1+62
	.quad	_return_parameter_convert__ret_i32_u16
	.quad	_L_1+74
	.quad	_return_parameter_convert__ret_i32_u32
	.quad	_L_1+86
	.quad	_return_parameter_convert__ret_i32_C
	.quad	_L_1+98
	.quad	_return_parameter_convert__ret_i32_i8
	.quad	_L_1+108
	.quad	_return_parameter_convert__ret_i32_I
	.quad	_L_1+119
	.quad	_return_parameter_convert__ret_i32_u8
	.quad	_L_1+129
	.quad	_return_parameter_convert__ret_i32_LC
	.quad	_L_1+140
	.quad	_return_parameter_convert__ret_i32_i64
	.quad	_L_1+151
	.quad	_return_parameter_convert__ret_i16_i32
	.quad	_L_1+163
	.quad	_return_parameter_convert__ret_i16_i16
	.quad	_L_1+175
	.quad	_return_parameter_convert__ret_i16_L
	.quad	_L_1+187
	.quad	_return_parameter_convert__ret_i16_u64
	.quad	_L_1+197
	.quad	_return_parameter_convert__ret_i16_u16
	.quad	_L_1+209
	.quad	_return_parameter_convert__ret_i16_u32
	.quad	_L_1+221
	.quad	_return_parameter_convert__ret_i16_C
	.quad	_L_1+233
	.quad	_return_parameter_convert__ret_i16_i8
	.quad	_L_1+243
	.quad	_return_parameter_convert__ret_i16_I
	.quad	_L_1+254
	.quad	_return_parameter_convert__ret_i16_u8
	.quad	_L_1+264
	.quad	_return_parameter_convert__ret_i16_LC
	.quad	_L_1+275
	.quad	_return_parameter_convert__ret_i16_i64
	.quad	_L_1+286
	.quad	_return_parameter_convert__ret_L_i32
	.quad	_L_1+298
	.quad	_return_parameter_convert__ret_L_i16
	.quad	_L_1+308
	.quad	_return_parameter_convert__ret_L_L
	.quad	_L_1+318
	.quad	_return_parameter_convert__ret_L_u64
	.quad	_L_1+326
	.quad	_return_parameter_convert__ret_L_u16
	.quad	_L_1+336
	.quad	_return_parameter_convert__ret_L_u32
	.quad	_L_1+346
	.quad	_return_parameter_convert__ret_L_C
	.quad	_L_1+356
	.quad	_return_parameter_convert__ret_L_i8
	.quad	_L_1+364
	.quad	_return_parameter_convert__ret_L_I
	.quad	_L_1+373
	.quad	_return_parameter_convert__ret_L_u8
	.quad	_L_1+381
	.quad	_return_parameter_convert__ret_L_LC
	.quad	_L_1+390
	.quad	_return_parameter_convert__ret_L_i64
	.quad	_L_1+399
	.quad	_return_parameter_convert__ret_u64_i32
	.quad	_L_1+409
	.quad	_return_parameter_convert__ret_u64_i16
	.quad	_L_1+421
	.quad	_return_parameter_convert__ret_u64_L
	.quad	_L_1+433
	.quad	_return_parameter_convert__ret_u64_u64
	.quad	_L_1+443
	.quad	_return_parameter_convert__ret_u64_u16
	.quad	_L_1+455
	.quad	_return_parameter_convert__ret_u64_u32
	.quad	_L_1+467
	.quad	_return_parameter_convert__ret_u64_C
	.quad	_L_1+479
	.quad	_return_parameter_convert__ret_u64_i8
	.quad	_L_1+489
	.quad	_return_parameter_convert__ret_u64_I
	.quad	_L_1+500
	.quad	_return_parameter_convert__ret_u64_u8
	.quad	_L_1+510
	.quad	_return_parameter_convert__ret_u64_LC
	.quad	_L_1+521
	.quad	_return_parameter_convert__ret_u64_i64
	.quad	_L_1+532
	.quad	_return_parameter_convert__ret_u16_i32
	.quad	_L_1+544
	.quad	_return_parameter_convert__ret_u16_i16
	.quad	_L_1+556
	.quad	_return_parameter_convert__ret_u16_L
	.quad	_L_1+568
	.quad	_return_parameter_convert__ret_u16_u64
	.quad	_L_1+578
	.quad	_return_parameter_convert__ret_u16_u16
	.quad	_L_1+590
	.quad	_return_parameter_convert__ret_u16_u32
	.quad	_L_1+602
	.quad	_return_parameter_convert__ret_u16_C
	.quad	_L_1+614
	.quad	_return_parameter_convert__ret_u16_i8
	.quad	_L_1+624
	.quad	_return_parameter_convert__ret_u16_I
	.quad	_L_1+635
	.quad	_return_parameter_convert__ret_u16_u8
	.quad	_L_1+645
	.quad	_return_parameter_convert__ret_u16_LC
	.quad	_L_1+656
	.quad	_return_parameter_convert__ret_u16_i64
	.quad	_L_1+667
	.quad	_return_parameter_convert__ret_u32_i32
	.quad	_L_1+679
	.quad	_return_parameter_convert__ret_u32_i16
	.quad	_L_1+691
	.quad	_return_parameter_convert__ret_u32_L
	.quad	_L_1+703
	.quad	_return_parameter_convert__ret_u32_u64
	.quad	_L_1+713
	.quad	_return_parameter_convert__ret_u32_u16
	.quad	_L_1+725
	.quad	_return_parameter_convert__ret_u32_u32
	.quad	_L_1+737
	.quad	_return_parameter_convert__ret_u32_C
	.quad	_L_1+749
	.quad	_return_parameter_convert__ret_u32_i8
	.quad	_L_1+759
	.quad	_return_parameter_convert__ret_u32_I
	.quad	_L_1+770
	.quad	_return_parameter_convert__ret_u32_u8
	.quad	_L_1+780
	.quad	_return_parameter_convert__ret_u32_LC
	.quad	_L_1+791
	.quad	_return_parameter_convert__ret_u32_i64
	.quad	_L_1+802
	.quad	_return_parameter_convert__ret_C_i32
	.quad	_L_1+814
	.quad	_return_parameter_convert__ret_C_i16
	.quad	_L_1+824
	.quad	_return_parameter_convert__ret_C_L
	.quad	_L_1+834
	.quad	_return_parameter_convert__ret_C_u64
	.quad	_L_1+842
	.quad	_return_parameter_convert__ret_C_u16
	.quad	_L_1+852
	.quad	_return_parameter_convert__ret_C_u32
	.quad	_L_1+862
	.quad	_return_parameter_convert__ret_C_C
	.quad	_L_1+872
	.quad	_return_parameter_convert__ret_C_i8
	.quad	_L_1+880
	.quad	_return_parameter_convert__ret_C_I
	.quad	_L_1+889
	.quad	_return_parameter_convert__ret_C_u8
	.quad	_L_1+897
	.quad	_return_parameter_convert__ret_C_LC
	.quad	_L_1+906
	.quad	_return_parameter_convert__ret_C_i64
	.quad	_L_1+915
	.quad	_return_parameter_convert__ret_i8_i32
	.quad	_L_1+925
	.quad	_return_parameter_convert__ret_i8_i16
	.quad	_L_1+936
	.quad	_return_parameter_convert__ret_i8_L
	.quad	_L_1+947
	.quad	_return_parameter_convert__ret_i8_u64
	.quad	_L_1+956
	.quad	_return_parameter_convert__ret_i8_u16
	.quad	_L_1+967
	.quad	_return_parameter_convert__ret_i8_u32
	.quad	_L_1+978
	.quad	_return_parameter_convert__ret_i8_C
	.quad	_L_1+989
	.quad	_return_parameter_convert__ret_i8_i8
	.quad	_L_1+998
	.quad	_return_parameter_convert__ret_i8_I
	.quad	_L_1+1008
	.quad	_return_parameter_convert__ret_i8_u8
	.quad	_L_1+1017
	.quad	_return_parameter_convert__ret_i8_LC
	.quad	_L_1+1027
	.quad	_return_parameter_convert__ret_i8_i64
	.quad	_L_1+1037
	.quad	_return_parameter_convert__ret_I_i32
	.quad	_L_1+1048
	.quad	_return_parameter_convert__ret_I_i16
	.quad	_L_1+1058
	.quad	_return_parameter_convert__ret_I_L
	.quad	_L_1+1068
	.quad	_return_parameter_convert__ret_I_u64
	.quad	_L_1+1076
	.quad	_return_parameter_convert__ret_I_u16
	.quad	_L_1+1086
	.quad	_return_parameter_convert__ret_I_u32
	.quad	_L_1+1096
	.quad	_return_parameter_convert__ret_I_C
	.quad	_L_1+1106
	.quad	_return_parameter_convert__ret_I_i8
	.quad	_L_1+1114
	.quad	_return_parameter_convert__ret_I_I
	.quad	_L_1+1123
	.quad	_return_parameter_convert__ret_I_u8
	.quad	_L_1+1131
	.quad	_return_parameter_convert__ret_I_LC
	.quad	_L_1+1140
	.quad	_return_parameter_convert__ret_I_i64
	.quad	_L_1+1149
	.quad	_return_parameter_convert__ret_u8_i32
	.quad	_L_1+1159
	.quad	_return_parameter_convert__ret_u8_i16
	.quad	_L_1+1170
	.quad	_return_parameter_convert__ret_u8_L
	.quad	_L_1+1181
	.quad	_return_parameter_convert__ret_u8_u64
	.quad	_L_1+1190
	.quad	_return_parameter_convert__ret_u8_u16
	.quad	_L_1+1201
	.quad	_return_parameter_convert__ret_u8_u32
	.quad	_L_1+1212
	.quad	_return_parameter_convert__ret_u8_C
	.quad	_L_1+1223
	.quad	_return_parameter_convert__ret_u8_i8
	.quad	_L_1+1232
	.quad	_return_parameter_convert__ret_u8_I
	.quad	_L_1+1242
	.quad	_return_parameter_convert__ret_u8_u8
	.quad	_L_1+1251
	.quad	_return_parameter_convert__ret_u8_LC
	.quad	_L_1+1261
	.quad	_return_parameter_convert__ret_u8_i64
	.quad	_L_1+1271
	.quad	_return_parameter_convert__ret_LC_i32
	.quad	_L_1+1282
	.quad	_return_parameter_convert__ret_LC_i16
	.quad	_L_1+1293
	.quad	_return_parameter_convert__ret_LC_L
	.quad	_L_1+1304
	.quad	_return_parameter_convert__ret_LC_u64
	.quad	_L_1+1313
	.quad	_return_parameter_convert__ret_LC_u16
	.quad	_L_1+1324
	.quad	_return_parameter_convert__ret_LC_u32
	.quad	_L_1+1335
	.quad	_return_parameter_convert__ret_LC_C
	.quad	_L_1+1346
	.quad	_return_parameter_convert__ret_LC_i8
	.quad	_L_1+1355
	.quad	_return_parameter_convert__ret_LC_I
	.quad	_L_1+1365
	.quad	_return_parameter_convert__ret_LC_u8
	.quad	_L_1+1374
	.quad	_return_parameter_convert__ret_LC_LC
	.quad	_L_1+1384
	.quad	_return_parameter_convert__ret_LC_i64
	.quad	_L_1+1394
	.quad	_return_parameter_convert__ret_i64_i32
	.quad	_L_1+1405
	.quad	_return_parameter_convert__ret_i64_i16
	.quad	_L_1+1417
	.quad	_return_parameter_convert__ret_i64_L
	.quad	_L_1+1429
	.quad	_return_parameter_convert__ret_i64_u64
	.quad	_L_1+1439
	.quad	_return_parameter_convert__ret_i64_u16
	.quad	_L_1+1451
	.quad	_return_parameter_convert__ret_i64_u32
	.quad	_L_1+1463
	.quad	_return_parameter_convert__ret_i64_C
	.quad	_L_1+1475
	.quad	_return_parameter_convert__ret_i64_i8
	.quad	_L_1+1485
	.quad	_return_parameter_convert__ret_i64_I
	.quad	_L_1+1496
	.quad	_return_parameter_convert__ret_i64_u8
	.quad	_L_1+1506
	.quad	_return_parameter_convert__ret_i64_LC
	.quad	_L_1+1517
	.quad	_return_parameter_convert__ret_i64_i64
	.quad	_L_1+1528
	.space 8
	.ascii "../AMD64_DARWIN/return_parameter_convert.m3"
	.space 5
	.data
	.align 5
_MM_return_parameter_convert:
	.quad	_L_1+3872
	.space 32
	.quad	_L_1+1544
	.space 24
	.quad	_MM_return_parameter_convert+208
	.space 8
	.quad	_return_parameter_convert_M3
	.quad	3
	.quad	113
	.quad	114
	.long	1122384740
	.byte	117
	.space 3
	.quad	118
	.byte	119
	.space 3
	.long	120
	.quad	121
	.word	122
	.space 6
	.quad	123
	.long	0
	.long	1079969792
	.quad	126
	.word	127
	.space 2
	.long	128
	.space 24
	.quad	_return_parameter_convert_I3
	.quad	_MM_return_parameter_convert+232
	.space 8
	.quad	_Long_I3
	.quad	_MM_return_parameter_convert+256
	.space 8
	.quad	_Word_I3
	.quad	_MM_return_parameter_convert+280
	.space 8
	.quad	_Cstdint_I3
	.quad	_MM_return_parameter_convert+304
	.space 8
	.quad	_RTHooks_I3
	.space 8
	.subsections_via_symbols
