	.text
.globl _return_parameter_convert__ret_u16_u16
	.private_extern _return_parameter_convert__ret_u16_u16
_return_parameter_convert__ret_u16_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_u64
	.private_extern _return_parameter_convert__ret_u16_u64
_return_parameter_convert__ret_u16_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_LC
	.private_extern _return_parameter_convert__ret_u16_LC
_return_parameter_convert__ret_u16_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_I
	.private_extern _return_parameter_convert__ret_u16_I
_return_parameter_convert__ret_u16_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_i32
	.private_extern _return_parameter_convert__ret_u16_i32
_return_parameter_convert__ret_u16_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_i16
	.private_extern _return_parameter_convert__ret_u16_i16
_return_parameter_convert__ret_u16_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_C
	.private_extern _return_parameter_convert__ret_u16_C
_return_parameter_convert__ret_u16_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_i64
	.private_extern _return_parameter_convert__ret_u16_i64
_return_parameter_convert__ret_u16_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_u8
	.private_extern _return_parameter_convert__ret_u16_u8
_return_parameter_convert__ret_u16_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_L
	.private_extern _return_parameter_convert__ret_u16_L
_return_parameter_convert__ret_u16_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_i8
	.private_extern _return_parameter_convert__ret_u16_i8
_return_parameter_convert__ret_u16_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u16_u32
	.private_extern _return_parameter_convert__ret_u16_u32
_return_parameter_convert__ret_u16_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movswq	-18(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_u16
	.private_extern _return_parameter_convert__ret_u64_u16
_return_parameter_convert__ret_u64_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_u64
	.private_extern _return_parameter_convert__ret_u64_u64
_return_parameter_convert__ret_u64_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_LC
	.private_extern _return_parameter_convert__ret_u64_LC
_return_parameter_convert__ret_u64_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_I
	.private_extern _return_parameter_convert__ret_u64_I
_return_parameter_convert__ret_u64_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_i32
	.private_extern _return_parameter_convert__ret_u64_i32
_return_parameter_convert__ret_u64_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_i16
	.private_extern _return_parameter_convert__ret_u64_i16
_return_parameter_convert__ret_u64_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_C
	.private_extern _return_parameter_convert__ret_u64_C
_return_parameter_convert__ret_u64_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_i64
	.private_extern _return_parameter_convert__ret_u64_i64
_return_parameter_convert__ret_u64_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_u8
	.private_extern _return_parameter_convert__ret_u64_u8
_return_parameter_convert__ret_u64_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_L
	.private_extern _return_parameter_convert__ret_u64_L
_return_parameter_convert__ret_u64_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_i8
	.private_extern _return_parameter_convert__ret_u64_i8
_return_parameter_convert__ret_u64_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u64_u32
	.private_extern _return_parameter_convert__ret_u64_u32
_return_parameter_convert__ret_u64_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_u16
	.private_extern _return_parameter_convert__ret_LC_u16
_return_parameter_convert__ret_LC_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_u64
	.private_extern _return_parameter_convert__ret_LC_u64
_return_parameter_convert__ret_LC_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_LC
	.private_extern _return_parameter_convert__ret_LC_LC
_return_parameter_convert__ret_LC_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_I
	.private_extern _return_parameter_convert__ret_LC_I
_return_parameter_convert__ret_LC_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_i32
	.private_extern _return_parameter_convert__ret_LC_i32
_return_parameter_convert__ret_LC_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_i16
	.private_extern _return_parameter_convert__ret_LC_i16
_return_parameter_convert__ret_LC_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_C
	.private_extern _return_parameter_convert__ret_LC_C
_return_parameter_convert__ret_LC_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_i64
	.private_extern _return_parameter_convert__ret_LC_i64
_return_parameter_convert__ret_LC_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_u8
	.private_extern _return_parameter_convert__ret_LC_u8
_return_parameter_convert__ret_LC_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_L
	.private_extern _return_parameter_convert__ret_LC_L
_return_parameter_convert__ret_LC_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_i8
	.private_extern _return_parameter_convert__ret_LC_i8
_return_parameter_convert__ret_LC_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_LC_u32
	.private_extern _return_parameter_convert__ret_LC_u32
_return_parameter_convert__ret_LC_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_u16
	.private_extern _return_parameter_convert__ret_I_u16
_return_parameter_convert__ret_I_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_u64
	.private_extern _return_parameter_convert__ret_I_u64
_return_parameter_convert__ret_I_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_LC
	.private_extern _return_parameter_convert__ret_I_LC
_return_parameter_convert__ret_I_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_I
	.private_extern _return_parameter_convert__ret_I_I
_return_parameter_convert__ret_I_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_i32
	.private_extern _return_parameter_convert__ret_I_i32
_return_parameter_convert__ret_I_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_i16
	.private_extern _return_parameter_convert__ret_I_i16
_return_parameter_convert__ret_I_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_C
	.private_extern _return_parameter_convert__ret_I_C
_return_parameter_convert__ret_I_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_i64
	.private_extern _return_parameter_convert__ret_I_i64
_return_parameter_convert__ret_I_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_u8
	.private_extern _return_parameter_convert__ret_I_u8
_return_parameter_convert__ret_I_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_L
	.private_extern _return_parameter_convert__ret_I_L
_return_parameter_convert__ret_I_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_i8
	.private_extern _return_parameter_convert__ret_I_i8
_return_parameter_convert__ret_I_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_I_u32
	.private_extern _return_parameter_convert__ret_I_u32
_return_parameter_convert__ret_I_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i32_u16
	.private_extern _return_parameter_convert__ret_i32_u16
_return_parameter_convert__ret_i32_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_u64
	.private_extern _return_parameter_convert__ret_i32_u64
_return_parameter_convert__ret_i32_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_LC
	.private_extern _return_parameter_convert__ret_i32_LC
_return_parameter_convert__ret_i32_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_I
	.private_extern _return_parameter_convert__ret_i32_I
_return_parameter_convert__ret_i32_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_i32
	.private_extern _return_parameter_convert__ret_i32_i32
_return_parameter_convert__ret_i32_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_i16
	.private_extern _return_parameter_convert__ret_i32_i16
_return_parameter_convert__ret_i32_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_C
	.private_extern _return_parameter_convert__ret_i32_C
_return_parameter_convert__ret_i32_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_i64
	.private_extern _return_parameter_convert__ret_i32_i64
_return_parameter_convert__ret_i32_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_u8
	.private_extern _return_parameter_convert__ret_i32_u8
_return_parameter_convert__ret_i32_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_L
	.private_extern _return_parameter_convert__ret_i32_L
_return_parameter_convert__ret_i32_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_i8
	.private_extern _return_parameter_convert__ret_i32_i8
_return_parameter_convert__ret_i32_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i32_u32
	.private_extern _return_parameter_convert__ret_i32_u32
_return_parameter_convert__ret_i32_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	mov	-20(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_u16
	.private_extern _return_parameter_convert__ret_i16_u16
_return_parameter_convert__ret_i16_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_u64
	.private_extern _return_parameter_convert__ret_i16_u64
_return_parameter_convert__ret_i16_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_LC
	.private_extern _return_parameter_convert__ret_i16_LC
_return_parameter_convert__ret_i16_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_I
	.private_extern _return_parameter_convert__ret_i16_I
_return_parameter_convert__ret_i16_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_i32
	.private_extern _return_parameter_convert__ret_i16_i32
_return_parameter_convert__ret_i16_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_i16
	.private_extern _return_parameter_convert__ret_i16_i16
_return_parameter_convert__ret_i16_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_C
	.private_extern _return_parameter_convert__ret_i16_C
_return_parameter_convert__ret_i16_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_i64
	.private_extern _return_parameter_convert__ret_i16_i64
_return_parameter_convert__ret_i16_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_u8
	.private_extern _return_parameter_convert__ret_i16_u8
_return_parameter_convert__ret_i16_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_L
	.private_extern _return_parameter_convert__ret_i16_L
_return_parameter_convert__ret_i16_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_i8
	.private_extern _return_parameter_convert__ret_i16_i8
_return_parameter_convert__ret_i16_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i16_u32
	.private_extern _return_parameter_convert__ret_i16_u32
_return_parameter_convert__ret_i16_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movw	%di, -18(%rbp)
	movzwl	-18(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_C_u16
	.private_extern _return_parameter_convert__ret_C_u16
_return_parameter_convert__ret_C_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_u64
	.private_extern _return_parameter_convert__ret_C_u64
_return_parameter_convert__ret_C_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_LC
	.private_extern _return_parameter_convert__ret_C_LC
_return_parameter_convert__ret_C_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_I
	.private_extern _return_parameter_convert__ret_C_I
_return_parameter_convert__ret_C_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_i32
	.private_extern _return_parameter_convert__ret_C_i32
_return_parameter_convert__ret_C_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_i16
	.private_extern _return_parameter_convert__ret_C_i16
_return_parameter_convert__ret_C_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_C
	.private_extern _return_parameter_convert__ret_C_C
_return_parameter_convert__ret_C_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_i64
	.private_extern _return_parameter_convert__ret_C_i64
_return_parameter_convert__ret_C_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_u8
	.private_extern _return_parameter_convert__ret_C_u8
_return_parameter_convert__ret_C_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_L
	.private_extern _return_parameter_convert__ret_C_L
_return_parameter_convert__ret_C_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_i8
	.private_extern _return_parameter_convert__ret_C_i8
_return_parameter_convert__ret_C_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_C_u32
	.private_extern _return_parameter_convert__ret_C_u32
_return_parameter_convert__ret_C_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_u16
	.private_extern _return_parameter_convert__ret_i64_u16
_return_parameter_convert__ret_i64_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_u64
	.private_extern _return_parameter_convert__ret_i64_u64
_return_parameter_convert__ret_i64_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_LC
	.private_extern _return_parameter_convert__ret_i64_LC
_return_parameter_convert__ret_i64_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_I
	.private_extern _return_parameter_convert__ret_i64_I
_return_parameter_convert__ret_i64_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_i32
	.private_extern _return_parameter_convert__ret_i64_i32
_return_parameter_convert__ret_i64_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_i16
	.private_extern _return_parameter_convert__ret_i64_i16
_return_parameter_convert__ret_i64_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_C
	.private_extern _return_parameter_convert__ret_i64_C
_return_parameter_convert__ret_i64_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_i64
	.private_extern _return_parameter_convert__ret_i64_i64
_return_parameter_convert__ret_i64_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_u8
	.private_extern _return_parameter_convert__ret_i64_u8
_return_parameter_convert__ret_i64_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_L
	.private_extern _return_parameter_convert__ret_i64_L
_return_parameter_convert__ret_i64_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_i8
	.private_extern _return_parameter_convert__ret_i64_i8
_return_parameter_convert__ret_i64_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i64_u32
	.private_extern _return_parameter_convert__ret_i64_u32
_return_parameter_convert__ret_i64_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_u16
	.private_extern _return_parameter_convert__ret_u8_u16
_return_parameter_convert__ret_u8_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_u64
	.private_extern _return_parameter_convert__ret_u8_u64
_return_parameter_convert__ret_u8_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_LC
	.private_extern _return_parameter_convert__ret_u8_LC
_return_parameter_convert__ret_u8_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_I
	.private_extern _return_parameter_convert__ret_u8_I
_return_parameter_convert__ret_u8_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_i32
	.private_extern _return_parameter_convert__ret_u8_i32
_return_parameter_convert__ret_u8_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_i16
	.private_extern _return_parameter_convert__ret_u8_i16
_return_parameter_convert__ret_u8_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_C
	.private_extern _return_parameter_convert__ret_u8_C
_return_parameter_convert__ret_u8_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_i64
	.private_extern _return_parameter_convert__ret_u8_i64
_return_parameter_convert__ret_u8_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_u8
	.private_extern _return_parameter_convert__ret_u8_u8
_return_parameter_convert__ret_u8_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_L
	.private_extern _return_parameter_convert__ret_u8_L
_return_parameter_convert__ret_u8_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_i8
	.private_extern _return_parameter_convert__ret_u8_i8
_return_parameter_convert__ret_u8_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_u8_u32
	.private_extern _return_parameter_convert__ret_u8_u32
_return_parameter_convert__ret_u8_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movsbq	-17(%rbp),%rax
	leave
	ret
.globl _return_parameter_convert__ret_L_u16
	.private_extern _return_parameter_convert__ret_L_u16
_return_parameter_convert__ret_L_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_u64
	.private_extern _return_parameter_convert__ret_L_u64
_return_parameter_convert__ret_L_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_LC
	.private_extern _return_parameter_convert__ret_L_LC
_return_parameter_convert__ret_L_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_I
	.private_extern _return_parameter_convert__ret_L_I
_return_parameter_convert__ret_L_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_i32
	.private_extern _return_parameter_convert__ret_L_i32
_return_parameter_convert__ret_L_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_i16
	.private_extern _return_parameter_convert__ret_L_i16
_return_parameter_convert__ret_L_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_C
	.private_extern _return_parameter_convert__ret_L_C
_return_parameter_convert__ret_L_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_i64
	.private_extern _return_parameter_convert__ret_L_i64
_return_parameter_convert__ret_L_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_u8
	.private_extern _return_parameter_convert__ret_L_u8
_return_parameter_convert__ret_L_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_L
	.private_extern _return_parameter_convert__ret_L_L
_return_parameter_convert__ret_L_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_i8
	.private_extern _return_parameter_convert__ret_L_i8
_return_parameter_convert__ret_L_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_L_u32
	.private_extern _return_parameter_convert__ret_L_u32
_return_parameter_convert__ret_L_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -24(%rbp)
	movq	-24(%rbp), %rax
	leave
	ret
.globl _return_parameter_convert__ret_i8_u16
	.private_extern _return_parameter_convert__ret_i8_u16
_return_parameter_convert__ret_i8_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_u64
	.private_extern _return_parameter_convert__ret_i8_u64
_return_parameter_convert__ret_i8_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_LC
	.private_extern _return_parameter_convert__ret_i8_LC
_return_parameter_convert__ret_i8_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_I
	.private_extern _return_parameter_convert__ret_i8_I
_return_parameter_convert__ret_i8_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_i32
	.private_extern _return_parameter_convert__ret_i8_i32
_return_parameter_convert__ret_i8_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_i16
	.private_extern _return_parameter_convert__ret_i8_i16
_return_parameter_convert__ret_i8_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_C
	.private_extern _return_parameter_convert__ret_i8_C
_return_parameter_convert__ret_i8_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_i64
	.private_extern _return_parameter_convert__ret_i8_i64
_return_parameter_convert__ret_i8_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_u8
	.private_extern _return_parameter_convert__ret_i8_u8
_return_parameter_convert__ret_i8_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_L
	.private_extern _return_parameter_convert__ret_i8_L
_return_parameter_convert__ret_i8_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_i8
	.private_extern _return_parameter_convert__ret_i8_i8
_return_parameter_convert__ret_i8_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_i8_u32
	.private_extern _return_parameter_convert__ret_i8_u32
_return_parameter_convert__ret_i8_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movb	%dil, -17(%rbp)
	movzbl	-17(%rbp), %eax
	leave
	ret
.globl _return_parameter_convert__ret_u32_u16
	.private_extern _return_parameter_convert__ret_u32_u16
_return_parameter_convert__ret_u32_u16:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_u64
	.private_extern _return_parameter_convert__ret_u32_u64
_return_parameter_convert__ret_u32_u64:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_LC
	.private_extern _return_parameter_convert__ret_u32_LC
_return_parameter_convert__ret_u32_LC:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_I
	.private_extern _return_parameter_convert__ret_u32_I
_return_parameter_convert__ret_u32_I:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_i32
	.private_extern _return_parameter_convert__ret_u32_i32
_return_parameter_convert__ret_u32_i32:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_i16
	.private_extern _return_parameter_convert__ret_u32_i16
_return_parameter_convert__ret_u32_i16:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_C
	.private_extern _return_parameter_convert__ret_u32_C
_return_parameter_convert__ret_u32_C:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_i64
	.private_extern _return_parameter_convert__ret_u32_i64
_return_parameter_convert__ret_u32_i64:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_u8
	.private_extern _return_parameter_convert__ret_u32_u8
_return_parameter_convert__ret_u32_u8:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_L
	.private_extern _return_parameter_convert__ret_u32_L
_return_parameter_convert__ret_u32_L:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_i8
	.private_extern _return_parameter_convert__ret_u32_i8
_return_parameter_convert__ret_u32_i8:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert__ret_u32_u32
	.private_extern _return_parameter_convert__ret_u32_u32
_return_parameter_convert__ret_u32_u32:
	pushq	%rbp
	movq	%rsp, %rbp
	movl	%edi, -20(%rbp)
	movl	-20(%rbp), %eax
	cltq
	leave
	ret
.globl _return_parameter_convert_M3
_return_parameter_convert_M3:
	pushq	%rbp
	movq	%rsp, %rbp
	movq	%rdi, -8(%rbp)
	leaq	_MM_return_parameter_convert(%rip), %rax
	leave
	ret
	.const_data
	.align 5
_L_1:
	.ascii "return_parameter_convert_M3"
	.space 1
	.ascii "ret_u32_u32"
	.space 1
	.ascii "ret_u32_i8"
	.space 1
	.ascii "ret_u32_L"
	.space 1
	.ascii "ret_u32_u8"
	.space 1
	.ascii "ret_u32_i64"
	.space 1
	.ascii "ret_u32_C"
	.space 1
	.ascii "ret_u32_i16"
	.space 1
	.ascii "ret_u32_i32"
	.space 1
	.ascii "ret_u32_I"
	.space 1
	.ascii "ret_u32_LC"
	.space 1
	.ascii "ret_u32_u64"
	.space 1
	.ascii "ret_u32_u16"
	.space 1
	.ascii "ret_i8_u32"
	.space 1
	.ascii "ret_i8_i8"
	.space 1
	.ascii "ret_i8_L"
	.space 1
	.ascii "ret_i8_u8"
	.space 1
	.ascii "ret_i8_i64"
	.space 1
	.ascii "ret_i8_C"
	.space 1
	.ascii "ret_i8_i16"
	.space 1
	.ascii "ret_i8_i32"
	.space 1
	.ascii "ret_i8_I"
	.space 1
	.ascii "ret_i8_LC"
	.space 1
	.ascii "ret_i8_u64"
	.space 1
	.ascii "ret_i8_u16"
	.space 1
	.ascii "ret_L_u32"
	.space 1
	.ascii "ret_L_i8"
	.space 1
	.ascii "ret_L_L"
	.space 1
	.ascii "ret_L_u8"
	.space 1
	.ascii "ret_L_i64"
	.space 1
	.ascii "ret_L_C"
	.space 1
	.ascii "ret_L_i16"
	.space 1
	.ascii "ret_L_i32"
	.space 1
	.ascii "ret_L_I"
	.space 1
	.ascii "ret_L_LC"
	.space 1
	.ascii "ret_L_u64"
	.space 1
	.ascii "ret_L_u16"
	.space 1
	.ascii "ret_u8_u32"
	.space 1
	.ascii "ret_u8_i8"
	.space 1
	.ascii "ret_u8_L"
	.space 1
	.ascii "ret_u8_u8"
	.space 1
	.ascii "ret_u8_i64"
	.space 1
	.ascii "ret_u8_C"
	.space 1
	.ascii "ret_u8_i16"
	.space 1
	.ascii "ret_u8_i32"
	.space 1
	.ascii "ret_u8_I"
	.space 1
	.ascii "ret_u8_LC"
	.space 1
	.ascii "ret_u8_u64"
	.space 1
	.ascii "ret_u8_u16"
	.space 1
	.ascii "ret_i64_u32"
	.space 1
	.ascii "ret_i64_i8"
	.space 1
	.ascii "ret_i64_L"
	.space 1
	.ascii "ret_i64_u8"
	.space 1
	.ascii "ret_i64_i64"
	.space 1
	.ascii "ret_i64_C"
	.space 1
	.ascii "ret_i64_i16"
	.space 1
	.ascii "ret_i64_i32"
	.space 1
	.ascii "ret_i64_I"
	.space 1
	.ascii "ret_i64_LC"
	.space 1
	.ascii "ret_i64_u64"
	.space 1
	.ascii "ret_i64_u16"
	.space 1
	.ascii "ret_C_u32"
	.space 1
	.ascii "ret_C_i8"
	.space 1
	.ascii "ret_C_L"
	.space 1
	.ascii "ret_C_u8"
	.space 1
	.ascii "ret_C_i64"
	.space 1
	.ascii "ret_C_C"
	.space 1
	.ascii "ret_C_i16"
	.space 1
	.ascii "ret_C_i32"
	.space 1
	.ascii "ret_C_I"
	.space 1
	.ascii "ret_C_LC"
	.space 1
	.ascii "ret_C_u64"
	.space 1
	.ascii "ret_C_u16"
	.space 1
	.ascii "ret_i16_u32"
	.space 1
	.ascii "ret_i16_i8"
	.space 1
	.ascii "ret_i16_L"
	.space 1
	.ascii "ret_i16_u8"
	.space 1
	.ascii "ret_i16_i64"
	.space 1
	.ascii "ret_i16_C"
	.space 1
	.ascii "ret_i16_i16"
	.space 1
	.ascii "ret_i16_i32"
	.space 1
	.ascii "ret_i16_I"
	.space 1
	.ascii "ret_i16_LC"
	.space 1
	.ascii "ret_i16_u64"
	.space 1
	.ascii "ret_i16_u16"
	.space 1
	.ascii "ret_i32_u32"
	.space 1
	.ascii "ret_i32_i8"
	.space 1
	.ascii "ret_i32_L"
	.space 1
	.ascii "ret_i32_u8"
	.space 1
	.ascii "ret_i32_i64"
	.space 1
	.ascii "ret_i32_C"
	.space 1
	.ascii "ret_i32_i16"
	.space 1
	.ascii "ret_i32_i32"
	.space 1
	.ascii "ret_i32_I"
	.space 1
	.ascii "ret_i32_LC"
	.space 1
	.ascii "ret_i32_u64"
	.space 1
	.ascii "ret_i32_u16"
	.space 1
	.ascii "ret_I_u32"
	.space 1
	.ascii "ret_I_i8"
	.space 1
	.ascii "ret_I_L"
	.space 1
	.ascii "ret_I_u8"
	.space 1
	.ascii "ret_I_i64"
	.space 1
	.ascii "ret_I_C"
	.space 1
	.ascii "ret_I_i16"
	.space 1
	.ascii "ret_I_i32"
	.space 1
	.ascii "ret_I_I"
	.space 1
	.ascii "ret_I_LC"
	.space 1
	.ascii "ret_I_u64"
	.space 1
	.ascii "ret_I_u16"
	.space 1
	.ascii "ret_LC_u32"
	.space 1
	.ascii "ret_LC_i8"
	.space 1
	.ascii "ret_LC_L"
	.space 1
	.ascii "ret_LC_u8"
	.space 1
	.ascii "ret_LC_i64"
	.space 1
	.ascii "ret_LC_C"
	.space 1
	.ascii "ret_LC_i16"
	.space 1
	.ascii "ret_LC_i32"
	.space 1
	.ascii "ret_LC_I"
	.space 1
	.ascii "ret_LC_LC"
	.space 1
	.ascii "ret_LC_u64"
	.space 1
	.ascii "ret_LC_u16"
	.space 1
	.ascii "ret_u64_u32"
	.space 1
	.ascii "ret_u64_i8"
	.space 1
	.ascii "ret_u64_L"
	.space 1
	.ascii "ret_u64_u8"
	.space 1
	.ascii "ret_u64_i64"
	.space 1
	.ascii "ret_u64_C"
	.space 1
	.ascii "ret_u64_i16"
	.space 1
	.ascii "ret_u64_i32"
	.space 1
	.ascii "ret_u64_I"
	.space 1
	.ascii "ret_u64_LC"
	.space 1
	.ascii "ret_u64_u64"
	.space 1
	.ascii "ret_u64_u16"
	.space 1
	.ascii "ret_u16_u32"
	.space 1
	.ascii "ret_u16_i8"
	.space 1
	.ascii "ret_u16_L"
	.space 1
	.ascii "ret_u16_u8"
	.space 1
	.ascii "ret_u16_i64"
	.space 1
	.ascii "ret_u16_C"
	.space 1
	.ascii "ret_u16_i16"
	.space 1
	.ascii "ret_u16_i32"
	.space 1
	.ascii "ret_u16_I"
	.space 1
	.ascii "ret_u16_LC"
	.space 1
	.ascii "ret_u16_u64"
	.space 1
	.ascii "ret_u16_u16"
	.space 5
	.quad	_return_parameter_convert_M3
	.quad	_L_1
	.quad	_return_parameter_convert__ret_u32_u32
	.quad	_L_1+28
	.quad	_return_parameter_convert__ret_u32_i8
	.quad	_L_1+40
	.quad	_return_parameter_convert__ret_u32_L
	.quad	_L_1+51
	.quad	_return_parameter_convert__ret_u32_u8
	.quad	_L_1+61
	.quad	_return_parameter_convert__ret_u32_i64
	.quad	_L_1+72
	.quad	_return_parameter_convert__ret_u32_C
	.quad	_L_1+84
	.quad	_return_parameter_convert__ret_u32_i16
	.quad	_L_1+94
	.quad	_return_parameter_convert__ret_u32_i32
	.quad	_L_1+106
	.quad	_return_parameter_convert__ret_u32_I
	.quad	_L_1+118
	.quad	_return_parameter_convert__ret_u32_LC
	.quad	_L_1+128
	.quad	_return_parameter_convert__ret_u32_u64
	.quad	_L_1+139
	.quad	_return_parameter_convert__ret_u32_u16
	.quad	_L_1+151
	.quad	_return_parameter_convert__ret_i8_u32
	.quad	_L_1+163
	.quad	_return_parameter_convert__ret_i8_i8
	.quad	_L_1+174
	.quad	_return_parameter_convert__ret_i8_L
	.quad	_L_1+184
	.quad	_return_parameter_convert__ret_i8_u8
	.quad	_L_1+193
	.quad	_return_parameter_convert__ret_i8_i64
	.quad	_L_1+203
	.quad	_return_parameter_convert__ret_i8_C
	.quad	_L_1+214
	.quad	_return_parameter_convert__ret_i8_i16
	.quad	_L_1+223
	.quad	_return_parameter_convert__ret_i8_i32
	.quad	_L_1+234
	.quad	_return_parameter_convert__ret_i8_I
	.quad	_L_1+245
	.quad	_return_parameter_convert__ret_i8_LC
	.quad	_L_1+254
	.quad	_return_parameter_convert__ret_i8_u64
	.quad	_L_1+264
	.quad	_return_parameter_convert__ret_i8_u16
	.quad	_L_1+275
	.quad	_return_parameter_convert__ret_L_u32
	.quad	_L_1+286
	.quad	_return_parameter_convert__ret_L_i8
	.quad	_L_1+296
	.quad	_return_parameter_convert__ret_L_L
	.quad	_L_1+305
	.quad	_return_parameter_convert__ret_L_u8
	.quad	_L_1+313
	.quad	_return_parameter_convert__ret_L_i64
	.quad	_L_1+322
	.quad	_return_parameter_convert__ret_L_C
	.quad	_L_1+332
	.quad	_return_parameter_convert__ret_L_i16
	.quad	_L_1+340
	.quad	_return_parameter_convert__ret_L_i32
	.quad	_L_1+350
	.quad	_return_parameter_convert__ret_L_I
	.quad	_L_1+360
	.quad	_return_parameter_convert__ret_L_LC
	.quad	_L_1+368
	.quad	_return_parameter_convert__ret_L_u64
	.quad	_L_1+377
	.quad	_return_parameter_convert__ret_L_u16
	.quad	_L_1+387
	.quad	_return_parameter_convert__ret_u8_u32
	.quad	_L_1+397
	.quad	_return_parameter_convert__ret_u8_i8
	.quad	_L_1+408
	.quad	_return_parameter_convert__ret_u8_L
	.quad	_L_1+418
	.quad	_return_parameter_convert__ret_u8_u8
	.quad	_L_1+427
	.quad	_return_parameter_convert__ret_u8_i64
	.quad	_L_1+437
	.quad	_return_parameter_convert__ret_u8_C
	.quad	_L_1+448
	.quad	_return_parameter_convert__ret_u8_i16
	.quad	_L_1+457
	.quad	_return_parameter_convert__ret_u8_i32
	.quad	_L_1+468
	.quad	_return_parameter_convert__ret_u8_I
	.quad	_L_1+479
	.quad	_return_parameter_convert__ret_u8_LC
	.quad	_L_1+488
	.quad	_return_parameter_convert__ret_u8_u64
	.quad	_L_1+498
	.quad	_return_parameter_convert__ret_u8_u16
	.quad	_L_1+509
	.quad	_return_parameter_convert__ret_i64_u32
	.quad	_L_1+520
	.quad	_return_parameter_convert__ret_i64_i8
	.quad	_L_1+532
	.quad	_return_parameter_convert__ret_i64_L
	.quad	_L_1+543
	.quad	_return_parameter_convert__ret_i64_u8
	.quad	_L_1+553
	.quad	_return_parameter_convert__ret_i64_i64
	.quad	_L_1+564
	.quad	_return_parameter_convert__ret_i64_C
	.quad	_L_1+576
	.quad	_return_parameter_convert__ret_i64_i16
	.quad	_L_1+586
	.quad	_return_parameter_convert__ret_i64_i32
	.quad	_L_1+598
	.quad	_return_parameter_convert__ret_i64_I
	.quad	_L_1+610
	.quad	_return_parameter_convert__ret_i64_LC
	.quad	_L_1+620
	.quad	_return_parameter_convert__ret_i64_u64
	.quad	_L_1+631
	.quad	_return_parameter_convert__ret_i64_u16
	.quad	_L_1+643
	.quad	_return_parameter_convert__ret_C_u32
	.quad	_L_1+655
	.quad	_return_parameter_convert__ret_C_i8
	.quad	_L_1+665
	.quad	_return_parameter_convert__ret_C_L
	.quad	_L_1+674
	.quad	_return_parameter_convert__ret_C_u8
	.quad	_L_1+682
	.quad	_return_parameter_convert__ret_C_i64
	.quad	_L_1+691
	.quad	_return_parameter_convert__ret_C_C
	.quad	_L_1+701
	.quad	_return_parameter_convert__ret_C_i16
	.quad	_L_1+709
	.quad	_return_parameter_convert__ret_C_i32
	.quad	_L_1+719
	.quad	_return_parameter_convert__ret_C_I
	.quad	_L_1+729
	.quad	_return_parameter_convert__ret_C_LC
	.quad	_L_1+737
	.quad	_return_parameter_convert__ret_C_u64
	.quad	_L_1+746
	.quad	_return_parameter_convert__ret_C_u16
	.quad	_L_1+756
	.quad	_return_parameter_convert__ret_i16_u32
	.quad	_L_1+766
	.quad	_return_parameter_convert__ret_i16_i8
	.quad	_L_1+778
	.quad	_return_parameter_convert__ret_i16_L
	.quad	_L_1+789
	.quad	_return_parameter_convert__ret_i16_u8
	.quad	_L_1+799
	.quad	_return_parameter_convert__ret_i16_i64
	.quad	_L_1+810
	.quad	_return_parameter_convert__ret_i16_C
	.quad	_L_1+822
	.quad	_return_parameter_convert__ret_i16_i16
	.quad	_L_1+832
	.quad	_return_parameter_convert__ret_i16_i32
	.quad	_L_1+844
	.quad	_return_parameter_convert__ret_i16_I
	.quad	_L_1+856
	.quad	_return_parameter_convert__ret_i16_LC
	.quad	_L_1+866
	.quad	_return_parameter_convert__ret_i16_u64
	.quad	_L_1+877
	.quad	_return_parameter_convert__ret_i16_u16
	.quad	_L_1+889
	.quad	_return_parameter_convert__ret_i32_u32
	.quad	_L_1+901
	.quad	_return_parameter_convert__ret_i32_i8
	.quad	_L_1+913
	.quad	_return_parameter_convert__ret_i32_L
	.quad	_L_1+924
	.quad	_return_parameter_convert__ret_i32_u8
	.quad	_L_1+934
	.quad	_return_parameter_convert__ret_i32_i64
	.quad	_L_1+945
	.quad	_return_parameter_convert__ret_i32_C
	.quad	_L_1+957
	.quad	_return_parameter_convert__ret_i32_i16
	.quad	_L_1+967
	.quad	_return_parameter_convert__ret_i32_i32
	.quad	_L_1+979
	.quad	_return_parameter_convert__ret_i32_I
	.quad	_L_1+991
	.quad	_return_parameter_convert__ret_i32_LC
	.quad	_L_1+1001
	.quad	_return_parameter_convert__ret_i32_u64
	.quad	_L_1+1012
	.quad	_return_parameter_convert__ret_i32_u16
	.quad	_L_1+1024
	.quad	_return_parameter_convert__ret_I_u32
	.quad	_L_1+1036
	.quad	_return_parameter_convert__ret_I_i8
	.quad	_L_1+1046
	.quad	_return_parameter_convert__ret_I_L
	.quad	_L_1+1055
	.quad	_return_parameter_convert__ret_I_u8
	.quad	_L_1+1063
	.quad	_return_parameter_convert__ret_I_i64
	.quad	_L_1+1072
	.quad	_return_parameter_convert__ret_I_C
	.quad	_L_1+1082
	.quad	_return_parameter_convert__ret_I_i16
	.quad	_L_1+1090
	.quad	_return_parameter_convert__ret_I_i32
	.quad	_L_1+1100
	.quad	_return_parameter_convert__ret_I_I
	.quad	_L_1+1110
	.quad	_return_parameter_convert__ret_I_LC
	.quad	_L_1+1118
	.quad	_return_parameter_convert__ret_I_u64
	.quad	_L_1+1127
	.quad	_return_parameter_convert__ret_I_u16
	.quad	_L_1+1137
	.quad	_return_parameter_convert__ret_LC_u32
	.quad	_L_1+1147
	.quad	_return_parameter_convert__ret_LC_i8
	.quad	_L_1+1158
	.quad	_return_parameter_convert__ret_LC_L
	.quad	_L_1+1168
	.quad	_return_parameter_convert__ret_LC_u8
	.quad	_L_1+1177
	.quad	_return_parameter_convert__ret_LC_i64
	.quad	_L_1+1187
	.quad	_return_parameter_convert__ret_LC_C
	.quad	_L_1+1198
	.quad	_return_parameter_convert__ret_LC_i16
	.quad	_L_1+1207
	.quad	_return_parameter_convert__ret_LC_i32
	.quad	_L_1+1218
	.quad	_return_parameter_convert__ret_LC_I
	.quad	_L_1+1229
	.quad	_return_parameter_convert__ret_LC_LC
	.quad	_L_1+1238
	.quad	_return_parameter_convert__ret_LC_u64
	.quad	_L_1+1248
	.quad	_return_parameter_convert__ret_LC_u16
	.quad	_L_1+1259
	.quad	_return_parameter_convert__ret_u64_u32
	.quad	_L_1+1270
	.quad	_return_parameter_convert__ret_u64_i8
	.quad	_L_1+1282
	.quad	_return_parameter_convert__ret_u64_L
	.quad	_L_1+1293
	.quad	_return_parameter_convert__ret_u64_u8
	.quad	_L_1+1303
	.quad	_return_parameter_convert__ret_u64_i64
	.quad	_L_1+1314
	.quad	_return_parameter_convert__ret_u64_C
	.quad	_L_1+1326
	.quad	_return_parameter_convert__ret_u64_i16
	.quad	_L_1+1336
	.quad	_return_parameter_convert__ret_u64_i32
	.quad	_L_1+1348
	.quad	_return_parameter_convert__ret_u64_I
	.quad	_L_1+1360
	.quad	_return_parameter_convert__ret_u64_LC
	.quad	_L_1+1370
	.quad	_return_parameter_convert__ret_u64_u64
	.quad	_L_1+1381
	.quad	_return_parameter_convert__ret_u64_u16
	.quad	_L_1+1393
	.quad	_return_parameter_convert__ret_u16_u32
	.quad	_L_1+1405
	.quad	_return_parameter_convert__ret_u16_i8
	.quad	_L_1+1417
	.quad	_return_parameter_convert__ret_u16_L
	.quad	_L_1+1428
	.quad	_return_parameter_convert__ret_u16_u8
	.quad	_L_1+1438
	.quad	_return_parameter_convert__ret_u16_i64
	.quad	_L_1+1449
	.quad	_return_parameter_convert__ret_u16_C
	.quad	_L_1+1461
	.quad	_return_parameter_convert__ret_u16_i16
	.quad	_L_1+1471
	.quad	_return_parameter_convert__ret_u16_i32
	.quad	_L_1+1483
	.quad	_return_parameter_convert__ret_u16_I
	.quad	_L_1+1495
	.quad	_return_parameter_convert__ret_u16_LC
	.quad	_L_1+1505
	.quad	_return_parameter_convert__ret_u16_u64
	.quad	_L_1+1516
	.quad	_return_parameter_convert__ret_u16_u16
	.quad	_L_1+1528
	.space 8
	.ascii "../AMD64_DARWIN/return_parameter_convert.m3"
	.space 5
	.data
	.align 5
_MM_return_parameter_convert:
	.quad	_L_1+3872
	.space 32
	.quad	_L_1+1544
	.space 24
	.quad	_MM_return_parameter_convert+208
	.space 8
	.quad	_return_parameter_convert_M3
	.quad	3
	.word	113
	.space 6
	.quad	114
	.quad	115
	.long	3985729651
	.long	1079838588
	.word	118
	.space 2
	.long	119
	.quad	120
	.quad	121
	.quad	122
	.long	1123434365
	.byte	125
	.byte	126
	.space 2
	.quad	127
	.long	128
	.space 28
	.quad	_return_parameter_convert_I3
	.quad	_MM_return_parameter_convert+232
	.space 8
	.quad	_Long_I3
	.quad	_MM_return_parameter_convert+256
	.space 8
	.quad	_Word_I3
	.quad	_MM_return_parameter_convert+280
	.space 8
	.quad	_Cstdint_I3
	.quad	_MM_return_parameter_convert+304
	.space 8
	.quad	_RTHooks_I3
	.space 8
	.subsections_via_symbols
