	.text
.no_dead_strip _return_parameter_convert__ret_u32_u32
_return_parameter_convert__ret_u32_u32:
LFB0:
	pushq	%rbp
LCFI0:
	movq	%rsp, %rbp
LCFI1:
	movl	%edi, -4(%rbp)
	mov	-4(%rbp), %eax
	leave
LCFI2:
	ret
LFE0:
.no_dead_strip _return_parameter_convert__ret_u32_u16
_return_parameter_convert__ret_u32_u16:
LFB1:
	pushq	%rbp
LCFI3:
	movq	%rsp, %rbp
LCFI4:
	movl	%edi, -4(%rbp)
	mov	-4(%rbp), %eax
	leave
LCFI5:
	ret
LFE1:
.no_dead_strip _return_parameter_convert__ret_u32_LC
_return_parameter_convert__ret_u32_LC:
LFB2:
	pushq	%rbp
LCFI6:
	movq	%rsp, %rbp
LCFI7:
	movl	%edi, -4(%rbp)
	mov	-4(%rbp), %eax
	leave
LCFI8:
	ret
LFE2:
.no_dead_strip _return_parameter_convert__ret_u32_I
_return_parameter_convert__ret_u32_I:
LFB3:
	pushq	%rbp
LCFI9:
	movq	%rsp, %rbp
LCFI10:
	movl	%edi, -4(%rbp)
	mov	-4(%rbp), %eax
	leave
LCFI11:
	ret
LFE3:
.no_dead_strip _return_parameter_convert__ret_u32_u64
_return_parameter_convert__ret_u32_u64:
LFB4:
	pushq	%rbp
LCFI12:
	movq	%rsp, %rbp
LCFI13:
	movl	%edi, -4(%rbp)
	mov	-4(%rbp), %eax
	leave
LCFI14:
	ret
LFE4:
.no_dead_strip _return_parameter_convert__ret_u32_i16
_return_parameter_convert__ret_u32_i16:
LFB5:
	pushq	%rbp
LCFI15:
	movq	%rsp, %rbp
LCFI16:
	movl	%edi, -4(%rbp)
	mov	-4(%rbp), %eax
	leave
LCFI17:
	ret
LFE5:
.no_dead_strip _return_parameter_convert__ret_u32_C
_return_parameter_convert__ret_u32_C:
LFB6:
	pushq	%rbp
LCFI18:
	movq	%rsp, %rbp
LCFI19:
	movl	%edi, -4(%rbp)
	mov	-4(%rbp), %eax
	leave
LCFI20:
	ret
LFE6:
.no_dead_strip _return_parameter_convert__ret_u32_i32
_return_parameter_convert__ret_u32_i32:
LFB7:
	pushq	%rbp
LCFI21:
	movq	%rsp, %rbp
LCFI22:
	movl	%edi, -4(%rbp)
	mov	-4(%rbp), %eax
	leave
LCFI23:
	ret
LFE7:
.no_dead_strip _return_parameter_convert__ret_u32_u8
_return_parameter_convert__ret_u32_u8:
LFB8:
	pushq	%rbp
LCFI24:
	movq	%rsp, %rbp
LCFI25:
	movl	%edi, -4(%rbp)
	mov	-4(%rbp), %eax
	leave
LCFI26:
	ret
LFE8:
.no_dead_strip _return_parameter_convert__ret_u32_i64
_return_parameter_convert__ret_u32_i64:
LFB9:
	pushq	%rbp
LCFI27:
	movq	%rsp, %rbp
LCFI28:
	movl	%edi, -4(%rbp)
	mov	-4(%rbp), %eax
	leave
LCFI29:
	ret
LFE9:
.no_dead_strip _return_parameter_convert__ret_u32_L
_return_parameter_convert__ret_u32_L:
LFB10:
	pushq	%rbp
LCFI30:
	movq	%rsp, %rbp
LCFI31:
	movl	%edi, -4(%rbp)
	mov	-4(%rbp), %eax
	leave
LCFI32:
	ret
LFE10:
.no_dead_strip _return_parameter_convert__ret_u32_i8
_return_parameter_convert__ret_u32_i8:
LFB11:
	pushq	%rbp
LCFI33:
	movq	%rsp, %rbp
LCFI34:
	movl	%edi, -4(%rbp)
	mov	-4(%rbp), %eax
	leave
LCFI35:
	ret
LFE11:
.no_dead_strip _return_parameter_convert__ret_u16_u32
_return_parameter_convert__ret_u16_u32:
LFB12:
	pushq	%rbp
LCFI36:
	movq	%rsp, %rbp
LCFI37:
	movw	%di, -2(%rbp)
	movzwl	-2(%rbp), %eax
	leave
LCFI38:
	ret
LFE12:
.no_dead_strip _return_parameter_convert__ret_u16_u16
_return_parameter_convert__ret_u16_u16:
LFB13:
	pushq	%rbp
LCFI39:
	movq	%rsp, %rbp
LCFI40:
	movw	%di, -2(%rbp)
	movzwl	-2(%rbp), %eax
	leave
LCFI41:
	ret
LFE13:
.no_dead_strip _return_parameter_convert__ret_u16_LC
_return_parameter_convert__ret_u16_LC:
LFB14:
	pushq	%rbp
LCFI42:
	movq	%rsp, %rbp
LCFI43:
	movw	%di, -2(%rbp)
	movzwl	-2(%rbp), %eax
	leave
LCFI44:
	ret
LFE14:
.no_dead_strip _return_parameter_convert__ret_u16_I
_return_parameter_convert__ret_u16_I:
LFB15:
	pushq	%rbp
LCFI45:
	movq	%rsp, %rbp
LCFI46:
	movw	%di, -2(%rbp)
	movzwl	-2(%rbp), %eax
	leave
LCFI47:
	ret
LFE15:
.no_dead_strip _return_parameter_convert__ret_u16_u64
_return_parameter_convert__ret_u16_u64:
LFB16:
	pushq	%rbp
LCFI48:
	movq	%rsp, %rbp
LCFI49:
	movw	%di, -2(%rbp)
	movzwl	-2(%rbp), %eax
	leave
LCFI50:
	ret
LFE16:
.no_dead_strip _return_parameter_convert__ret_u16_i16
_return_parameter_convert__ret_u16_i16:
LFB17:
	pushq	%rbp
LCFI51:
	movq	%rsp, %rbp
LCFI52:
	movw	%di, -2(%rbp)
	movzwl	-2(%rbp), %eax
	leave
LCFI53:
	ret
LFE17:
.no_dead_strip _return_parameter_convert__ret_u16_C
_return_parameter_convert__ret_u16_C:
LFB18:
	pushq	%rbp
LCFI54:
	movq	%rsp, %rbp
LCFI55:
	movw	%di, -2(%rbp)
	movzwl	-2(%rbp), %eax
	leave
LCFI56:
	ret
LFE18:
.no_dead_strip _return_parameter_convert__ret_u16_i32
_return_parameter_convert__ret_u16_i32:
LFB19:
	pushq	%rbp
LCFI57:
	movq	%rsp, %rbp
LCFI58:
	movw	%di, -2(%rbp)
	movzwl	-2(%rbp), %eax
	leave
LCFI59:
	ret
LFE19:
.no_dead_strip _return_parameter_convert__ret_u16_u8
_return_parameter_convert__ret_u16_u8:
LFB20:
	pushq	%rbp
LCFI60:
	movq	%rsp, %rbp
LCFI61:
	movw	%di, -2(%rbp)
	movzwl	-2(%rbp), %eax
	leave
LCFI62:
	ret
LFE20:
.no_dead_strip _return_parameter_convert__ret_u16_i64
_return_parameter_convert__ret_u16_i64:
LFB21:
	pushq	%rbp
LCFI63:
	movq	%rsp, %rbp
LCFI64:
	movw	%di, -2(%rbp)
	movzwl	-2(%rbp), %eax
	leave
LCFI65:
	ret
LFE21:
.no_dead_strip _return_parameter_convert__ret_u16_L
_return_parameter_convert__ret_u16_L:
LFB22:
	pushq	%rbp
LCFI66:
	movq	%rsp, %rbp
LCFI67:
	movw	%di, -2(%rbp)
	movzwl	-2(%rbp), %eax
	leave
LCFI68:
	ret
LFE22:
.no_dead_strip _return_parameter_convert__ret_u16_i8
_return_parameter_convert__ret_u16_i8:
LFB23:
	pushq	%rbp
LCFI69:
	movq	%rsp, %rbp
LCFI70:
	movw	%di, -2(%rbp)
	movzwl	-2(%rbp), %eax
	leave
LCFI71:
	ret
LFE23:
.no_dead_strip _return_parameter_convert__ret_LC_u32
_return_parameter_convert__ret_LC_u32:
LFB24:
	pushq	%rbp
LCFI72:
	movq	%rsp, %rbp
LCFI73:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI74:
	ret
LFE24:
.no_dead_strip _return_parameter_convert__ret_LC_u16
_return_parameter_convert__ret_LC_u16:
LFB25:
	pushq	%rbp
LCFI75:
	movq	%rsp, %rbp
LCFI76:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI77:
	ret
LFE25:
.no_dead_strip _return_parameter_convert__ret_LC_LC
_return_parameter_convert__ret_LC_LC:
LFB26:
	pushq	%rbp
LCFI78:
	movq	%rsp, %rbp
LCFI79:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI80:
	ret
LFE26:
.no_dead_strip _return_parameter_convert__ret_LC_I
_return_parameter_convert__ret_LC_I:
LFB27:
	pushq	%rbp
LCFI81:
	movq	%rsp, %rbp
LCFI82:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI83:
	ret
LFE27:
.no_dead_strip _return_parameter_convert__ret_LC_u64
_return_parameter_convert__ret_LC_u64:
LFB28:
	pushq	%rbp
LCFI84:
	movq	%rsp, %rbp
LCFI85:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI86:
	ret
LFE28:
.no_dead_strip _return_parameter_convert__ret_LC_i16
_return_parameter_convert__ret_LC_i16:
LFB29:
	pushq	%rbp
LCFI87:
	movq	%rsp, %rbp
LCFI88:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI89:
	ret
LFE29:
.no_dead_strip _return_parameter_convert__ret_LC_C
_return_parameter_convert__ret_LC_C:
LFB30:
	pushq	%rbp
LCFI90:
	movq	%rsp, %rbp
LCFI91:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI92:
	ret
LFE30:
.no_dead_strip _return_parameter_convert__ret_LC_i32
_return_parameter_convert__ret_LC_i32:
LFB31:
	pushq	%rbp
LCFI93:
	movq	%rsp, %rbp
LCFI94:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI95:
	ret
LFE31:
.no_dead_strip _return_parameter_convert__ret_LC_u8
_return_parameter_convert__ret_LC_u8:
LFB32:
	pushq	%rbp
LCFI96:
	movq	%rsp, %rbp
LCFI97:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI98:
	ret
LFE32:
.no_dead_strip _return_parameter_convert__ret_LC_i64
_return_parameter_convert__ret_LC_i64:
LFB33:
	pushq	%rbp
LCFI99:
	movq	%rsp, %rbp
LCFI100:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI101:
	ret
LFE33:
.no_dead_strip _return_parameter_convert__ret_LC_L
_return_parameter_convert__ret_LC_L:
LFB34:
	pushq	%rbp
LCFI102:
	movq	%rsp, %rbp
LCFI103:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI104:
	ret
LFE34:
.no_dead_strip _return_parameter_convert__ret_LC_i8
_return_parameter_convert__ret_LC_i8:
LFB35:
	pushq	%rbp
LCFI105:
	movq	%rsp, %rbp
LCFI106:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI107:
	ret
LFE35:
.no_dead_strip _return_parameter_convert__ret_I_u32
_return_parameter_convert__ret_I_u32:
LFB36:
	pushq	%rbp
LCFI108:
	movq	%rsp, %rbp
LCFI109:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI110:
	ret
LFE36:
.no_dead_strip _return_parameter_convert__ret_I_u16
_return_parameter_convert__ret_I_u16:
LFB37:
	pushq	%rbp
LCFI111:
	movq	%rsp, %rbp
LCFI112:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI113:
	ret
LFE37:
.no_dead_strip _return_parameter_convert__ret_I_LC
_return_parameter_convert__ret_I_LC:
LFB38:
	pushq	%rbp
LCFI114:
	movq	%rsp, %rbp
LCFI115:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI116:
	ret
LFE38:
.no_dead_strip _return_parameter_convert__ret_I_I
_return_parameter_convert__ret_I_I:
LFB39:
	pushq	%rbp
LCFI117:
	movq	%rsp, %rbp
LCFI118:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI119:
	ret
LFE39:
.no_dead_strip _return_parameter_convert__ret_I_u64
_return_parameter_convert__ret_I_u64:
LFB40:
	pushq	%rbp
LCFI120:
	movq	%rsp, %rbp
LCFI121:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI122:
	ret
LFE40:
.no_dead_strip _return_parameter_convert__ret_I_i16
_return_parameter_convert__ret_I_i16:
LFB41:
	pushq	%rbp
LCFI123:
	movq	%rsp, %rbp
LCFI124:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI125:
	ret
LFE41:
.no_dead_strip _return_parameter_convert__ret_I_C
_return_parameter_convert__ret_I_C:
LFB42:
	pushq	%rbp
LCFI126:
	movq	%rsp, %rbp
LCFI127:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI128:
	ret
LFE42:
.no_dead_strip _return_parameter_convert__ret_I_i32
_return_parameter_convert__ret_I_i32:
LFB43:
	pushq	%rbp
LCFI129:
	movq	%rsp, %rbp
LCFI130:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI131:
	ret
LFE43:
.no_dead_strip _return_parameter_convert__ret_I_u8
_return_parameter_convert__ret_I_u8:
LFB44:
	pushq	%rbp
LCFI132:
	movq	%rsp, %rbp
LCFI133:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI134:
	ret
LFE44:
.no_dead_strip _return_parameter_convert__ret_I_i64
_return_parameter_convert__ret_I_i64:
LFB45:
	pushq	%rbp
LCFI135:
	movq	%rsp, %rbp
LCFI136:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI137:
	ret
LFE45:
.no_dead_strip _return_parameter_convert__ret_I_L
_return_parameter_convert__ret_I_L:
LFB46:
	pushq	%rbp
LCFI138:
	movq	%rsp, %rbp
LCFI139:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI140:
	ret
LFE46:
.no_dead_strip _return_parameter_convert__ret_I_i8
_return_parameter_convert__ret_I_i8:
LFB47:
	pushq	%rbp
LCFI141:
	movq	%rsp, %rbp
LCFI142:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI143:
	ret
LFE47:
.no_dead_strip _return_parameter_convert__ret_u64_u32
_return_parameter_convert__ret_u64_u32:
LFB48:
	pushq	%rbp
LCFI144:
	movq	%rsp, %rbp
LCFI145:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI146:
	ret
LFE48:
.no_dead_strip _return_parameter_convert__ret_u64_u16
_return_parameter_convert__ret_u64_u16:
LFB49:
	pushq	%rbp
LCFI147:
	movq	%rsp, %rbp
LCFI148:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI149:
	ret
LFE49:
.no_dead_strip _return_parameter_convert__ret_u64_LC
_return_parameter_convert__ret_u64_LC:
LFB50:
	pushq	%rbp
LCFI150:
	movq	%rsp, %rbp
LCFI151:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI152:
	ret
LFE50:
.no_dead_strip _return_parameter_convert__ret_u64_I
_return_parameter_convert__ret_u64_I:
LFB51:
	pushq	%rbp
LCFI153:
	movq	%rsp, %rbp
LCFI154:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI155:
	ret
LFE51:
.no_dead_strip _return_parameter_convert__ret_u64_u64
_return_parameter_convert__ret_u64_u64:
LFB52:
	pushq	%rbp
LCFI156:
	movq	%rsp, %rbp
LCFI157:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI158:
	ret
LFE52:
.no_dead_strip _return_parameter_convert__ret_u64_i16
_return_parameter_convert__ret_u64_i16:
LFB53:
	pushq	%rbp
LCFI159:
	movq	%rsp, %rbp
LCFI160:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI161:
	ret
LFE53:
.no_dead_strip _return_parameter_convert__ret_u64_C
_return_parameter_convert__ret_u64_C:
LFB54:
	pushq	%rbp
LCFI162:
	movq	%rsp, %rbp
LCFI163:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI164:
	ret
LFE54:
.no_dead_strip _return_parameter_convert__ret_u64_i32
_return_parameter_convert__ret_u64_i32:
LFB55:
	pushq	%rbp
LCFI165:
	movq	%rsp, %rbp
LCFI166:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI167:
	ret
LFE55:
.no_dead_strip _return_parameter_convert__ret_u64_u8
_return_parameter_convert__ret_u64_u8:
LFB56:
	pushq	%rbp
LCFI168:
	movq	%rsp, %rbp
LCFI169:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI170:
	ret
LFE56:
.no_dead_strip _return_parameter_convert__ret_u64_i64
_return_parameter_convert__ret_u64_i64:
LFB57:
	pushq	%rbp
LCFI171:
	movq	%rsp, %rbp
LCFI172:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI173:
	ret
LFE57:
.no_dead_strip _return_parameter_convert__ret_u64_L
_return_parameter_convert__ret_u64_L:
LFB58:
	pushq	%rbp
LCFI174:
	movq	%rsp, %rbp
LCFI175:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI176:
	ret
LFE58:
.no_dead_strip _return_parameter_convert__ret_u64_i8
_return_parameter_convert__ret_u64_i8:
LFB59:
	pushq	%rbp
LCFI177:
	movq	%rsp, %rbp
LCFI178:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI179:
	ret
LFE59:
.no_dead_strip _return_parameter_convert__ret_i16_u32
_return_parameter_convert__ret_i16_u32:
LFB60:
	pushq	%rbp
LCFI180:
	movq	%rsp, %rbp
LCFI181:
	movw	%di, -2(%rbp)
	movswq	-2(%rbp), %rax
	leave
LCFI182:
	ret
LFE60:
.no_dead_strip _return_parameter_convert__ret_i16_u16
_return_parameter_convert__ret_i16_u16:
LFB61:
	pushq	%rbp
LCFI183:
	movq	%rsp, %rbp
LCFI184:
	movw	%di, -2(%rbp)
	movswq	-2(%rbp), %rax
	leave
LCFI185:
	ret
LFE61:
.no_dead_strip _return_parameter_convert__ret_i16_LC
_return_parameter_convert__ret_i16_LC:
LFB62:
	pushq	%rbp
LCFI186:
	movq	%rsp, %rbp
LCFI187:
	movw	%di, -2(%rbp)
	movswq	-2(%rbp), %rax
	leave
LCFI188:
	ret
LFE62:
.no_dead_strip _return_parameter_convert__ret_i16_I
_return_parameter_convert__ret_i16_I:
LFB63:
	pushq	%rbp
LCFI189:
	movq	%rsp, %rbp
LCFI190:
	movw	%di, -2(%rbp)
	movswq	-2(%rbp), %rax
	leave
LCFI191:
	ret
LFE63:
.no_dead_strip _return_parameter_convert__ret_i16_u64
_return_parameter_convert__ret_i16_u64:
LFB64:
	pushq	%rbp
LCFI192:
	movq	%rsp, %rbp
LCFI193:
	movw	%di, -2(%rbp)
	movswq	-2(%rbp), %rax
	leave
LCFI194:
	ret
LFE64:
.no_dead_strip _return_parameter_convert__ret_i16_i16
_return_parameter_convert__ret_i16_i16:
LFB65:
	pushq	%rbp
LCFI195:
	movq	%rsp, %rbp
LCFI196:
	movw	%di, -2(%rbp)
	movswq	-2(%rbp), %rax
	leave
LCFI197:
	ret
LFE65:
.no_dead_strip _return_parameter_convert__ret_i16_C
_return_parameter_convert__ret_i16_C:
LFB66:
	pushq	%rbp
LCFI198:
	movq	%rsp, %rbp
LCFI199:
	movw	%di, -2(%rbp)
	movswq	-2(%rbp), %rax
	leave
LCFI200:
	ret
LFE66:
.no_dead_strip _return_parameter_convert__ret_i16_i32
_return_parameter_convert__ret_i16_i32:
LFB67:
	pushq	%rbp
LCFI201:
	movq	%rsp, %rbp
LCFI202:
	movw	%di, -2(%rbp)
	movswq	-2(%rbp), %rax
	leave
LCFI203:
	ret
LFE67:
.no_dead_strip _return_parameter_convert__ret_i16_u8
_return_parameter_convert__ret_i16_u8:
LFB68:
	pushq	%rbp
LCFI204:
	movq	%rsp, %rbp
LCFI205:
	movw	%di, -2(%rbp)
	movswq	-2(%rbp), %rax
	leave
LCFI206:
	ret
LFE68:
.no_dead_strip _return_parameter_convert__ret_i16_i64
_return_parameter_convert__ret_i16_i64:
LFB69:
	pushq	%rbp
LCFI207:
	movq	%rsp, %rbp
LCFI208:
	movw	%di, -2(%rbp)
	movswq	-2(%rbp), %rax
	leave
LCFI209:
	ret
LFE69:
.no_dead_strip _return_parameter_convert__ret_i16_L
_return_parameter_convert__ret_i16_L:
LFB70:
	pushq	%rbp
LCFI210:
	movq	%rsp, %rbp
LCFI211:
	movw	%di, -2(%rbp)
	movswq	-2(%rbp), %rax
	leave
LCFI212:
	ret
LFE70:
.no_dead_strip _return_parameter_convert__ret_i16_i8
_return_parameter_convert__ret_i16_i8:
LFB71:
	pushq	%rbp
LCFI213:
	movq	%rsp, %rbp
LCFI214:
	movw	%di, -2(%rbp)
	movswq	-2(%rbp), %rax
	leave
LCFI215:
	ret
LFE71:
.no_dead_strip _return_parameter_convert__ret_C_u32
_return_parameter_convert__ret_C_u32:
LFB72:
	pushq	%rbp
LCFI216:
	movq	%rsp, %rbp
LCFI217:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI218:
	ret
LFE72:
.no_dead_strip _return_parameter_convert__ret_C_u16
_return_parameter_convert__ret_C_u16:
LFB73:
	pushq	%rbp
LCFI219:
	movq	%rsp, %rbp
LCFI220:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI221:
	ret
LFE73:
.no_dead_strip _return_parameter_convert__ret_C_LC
_return_parameter_convert__ret_C_LC:
LFB74:
	pushq	%rbp
LCFI222:
	movq	%rsp, %rbp
LCFI223:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI224:
	ret
LFE74:
.no_dead_strip _return_parameter_convert__ret_C_I
_return_parameter_convert__ret_C_I:
LFB75:
	pushq	%rbp
LCFI225:
	movq	%rsp, %rbp
LCFI226:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI227:
	ret
LFE75:
.no_dead_strip _return_parameter_convert__ret_C_u64
_return_parameter_convert__ret_C_u64:
LFB76:
	pushq	%rbp
LCFI228:
	movq	%rsp, %rbp
LCFI229:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI230:
	ret
LFE76:
.no_dead_strip _return_parameter_convert__ret_C_i16
_return_parameter_convert__ret_C_i16:
LFB77:
	pushq	%rbp
LCFI231:
	movq	%rsp, %rbp
LCFI232:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI233:
	ret
LFE77:
.no_dead_strip _return_parameter_convert__ret_C_C
_return_parameter_convert__ret_C_C:
LFB78:
	pushq	%rbp
LCFI234:
	movq	%rsp, %rbp
LCFI235:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI236:
	ret
LFE78:
.no_dead_strip _return_parameter_convert__ret_C_i32
_return_parameter_convert__ret_C_i32:
LFB79:
	pushq	%rbp
LCFI237:
	movq	%rsp, %rbp
LCFI238:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI239:
	ret
LFE79:
.no_dead_strip _return_parameter_convert__ret_C_u8
_return_parameter_convert__ret_C_u8:
LFB80:
	pushq	%rbp
LCFI240:
	movq	%rsp, %rbp
LCFI241:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI242:
	ret
LFE80:
.no_dead_strip _return_parameter_convert__ret_C_i64
_return_parameter_convert__ret_C_i64:
LFB81:
	pushq	%rbp
LCFI243:
	movq	%rsp, %rbp
LCFI244:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI245:
	ret
LFE81:
.no_dead_strip _return_parameter_convert__ret_C_L
_return_parameter_convert__ret_C_L:
LFB82:
	pushq	%rbp
LCFI246:
	movq	%rsp, %rbp
LCFI247:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI248:
	ret
LFE82:
.no_dead_strip _return_parameter_convert__ret_C_i8
_return_parameter_convert__ret_C_i8:
LFB83:
	pushq	%rbp
LCFI249:
	movq	%rsp, %rbp
LCFI250:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI251:
	ret
LFE83:
.no_dead_strip _return_parameter_convert__ret_i32_u32
_return_parameter_convert__ret_i32_u32:
LFB84:
	pushq	%rbp
LCFI252:
	movq	%rsp, %rbp
LCFI253:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	cltq
	leave
LCFI254:
	ret
LFE84:
.no_dead_strip _return_parameter_convert__ret_i32_u16
_return_parameter_convert__ret_i32_u16:
LFB85:
	pushq	%rbp
LCFI255:
	movq	%rsp, %rbp
LCFI256:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	cltq
	leave
LCFI257:
	ret
LFE85:
.no_dead_strip _return_parameter_convert__ret_i32_LC
_return_parameter_convert__ret_i32_LC:
LFB86:
	pushq	%rbp
LCFI258:
	movq	%rsp, %rbp
LCFI259:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	cltq
	leave
LCFI260:
	ret
LFE86:
.no_dead_strip _return_parameter_convert__ret_i32_I
_return_parameter_convert__ret_i32_I:
LFB87:
	pushq	%rbp
LCFI261:
	movq	%rsp, %rbp
LCFI262:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	cltq
	leave
LCFI263:
	ret
LFE87:
.no_dead_strip _return_parameter_convert__ret_i32_u64
_return_parameter_convert__ret_i32_u64:
LFB88:
	pushq	%rbp
LCFI264:
	movq	%rsp, %rbp
LCFI265:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	cltq
	leave
LCFI266:
	ret
LFE88:
.no_dead_strip _return_parameter_convert__ret_i32_i16
_return_parameter_convert__ret_i32_i16:
LFB89:
	pushq	%rbp
LCFI267:
	movq	%rsp, %rbp
LCFI268:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	cltq
	leave
LCFI269:
	ret
LFE89:
.no_dead_strip _return_parameter_convert__ret_i32_C
_return_parameter_convert__ret_i32_C:
LFB90:
	pushq	%rbp
LCFI270:
	movq	%rsp, %rbp
LCFI271:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	cltq
	leave
LCFI272:
	ret
LFE90:
.no_dead_strip _return_parameter_convert__ret_i32_i32
_return_parameter_convert__ret_i32_i32:
LFB91:
	pushq	%rbp
LCFI273:
	movq	%rsp, %rbp
LCFI274:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	cltq
	leave
LCFI275:
	ret
LFE91:
.no_dead_strip _return_parameter_convert__ret_i32_u8
_return_parameter_convert__ret_i32_u8:
LFB92:
	pushq	%rbp
LCFI276:
	movq	%rsp, %rbp
LCFI277:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	cltq
	leave
LCFI278:
	ret
LFE92:
.no_dead_strip _return_parameter_convert__ret_i32_i64
_return_parameter_convert__ret_i32_i64:
LFB93:
	pushq	%rbp
LCFI279:
	movq	%rsp, %rbp
LCFI280:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	cltq
	leave
LCFI281:
	ret
LFE93:
.no_dead_strip _return_parameter_convert__ret_i32_L
_return_parameter_convert__ret_i32_L:
LFB94:
	pushq	%rbp
LCFI282:
	movq	%rsp, %rbp
LCFI283:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	cltq
	leave
LCFI284:
	ret
LFE94:
.no_dead_strip _return_parameter_convert__ret_i32_i8
_return_parameter_convert__ret_i32_i8:
LFB95:
	pushq	%rbp
LCFI285:
	movq	%rsp, %rbp
LCFI286:
	movl	%edi, -4(%rbp)
	movl	-4(%rbp), %eax
	cltq
	leave
LCFI287:
	ret
LFE95:
.no_dead_strip _return_parameter_convert__ret_u8_u32
_return_parameter_convert__ret_u8_u32:
LFB96:
	pushq	%rbp
LCFI288:
	movq	%rsp, %rbp
LCFI289:
	movb	%dil, -1(%rbp)
	movzbl	-1(%rbp), %eax
	leave
LCFI290:
	ret
LFE96:
.no_dead_strip _return_parameter_convert__ret_u8_u16
_return_parameter_convert__ret_u8_u16:
LFB97:
	pushq	%rbp
LCFI291:
	movq	%rsp, %rbp
LCFI292:
	movb	%dil, -1(%rbp)
	movzbl	-1(%rbp), %eax
	leave
LCFI293:
	ret
LFE97:
.no_dead_strip _return_parameter_convert__ret_u8_LC
_return_parameter_convert__ret_u8_LC:
LFB98:
	pushq	%rbp
LCFI294:
	movq	%rsp, %rbp
LCFI295:
	movb	%dil, -1(%rbp)
	movzbl	-1(%rbp), %eax
	leave
LCFI296:
	ret
LFE98:
.no_dead_strip _return_parameter_convert__ret_u8_I
_return_parameter_convert__ret_u8_I:
LFB99:
	pushq	%rbp
LCFI297:
	movq	%rsp, %rbp
LCFI298:
	movb	%dil, -1(%rbp)
	movzbl	-1(%rbp), %eax
	leave
LCFI299:
	ret
LFE99:
.no_dead_strip _return_parameter_convert__ret_u8_u64
_return_parameter_convert__ret_u8_u64:
LFB100:
	pushq	%rbp
LCFI300:
	movq	%rsp, %rbp
LCFI301:
	movb	%dil, -1(%rbp)
	movzbl	-1(%rbp), %eax
	leave
LCFI302:
	ret
LFE100:
.no_dead_strip _return_parameter_convert__ret_u8_i16
_return_parameter_convert__ret_u8_i16:
LFB101:
	pushq	%rbp
LCFI303:
	movq	%rsp, %rbp
LCFI304:
	movb	%dil, -1(%rbp)
	movzbl	-1(%rbp), %eax
	leave
LCFI305:
	ret
LFE101:
.no_dead_strip _return_parameter_convert__ret_u8_C
_return_parameter_convert__ret_u8_C:
LFB102:
	pushq	%rbp
LCFI306:
	movq	%rsp, %rbp
LCFI307:
	movb	%dil, -1(%rbp)
	movzbl	-1(%rbp), %eax
	leave
LCFI308:
	ret
LFE102:
.no_dead_strip _return_parameter_convert__ret_u8_i32
_return_parameter_convert__ret_u8_i32:
LFB103:
	pushq	%rbp
LCFI309:
	movq	%rsp, %rbp
LCFI310:
	movb	%dil, -1(%rbp)
	movzbl	-1(%rbp), %eax
	leave
LCFI311:
	ret
LFE103:
.no_dead_strip _return_parameter_convert__ret_u8_u8
_return_parameter_convert__ret_u8_u8:
LFB104:
	pushq	%rbp
LCFI312:
	movq	%rsp, %rbp
LCFI313:
	movb	%dil, -1(%rbp)
	movzbl	-1(%rbp), %eax
	leave
LCFI314:
	ret
LFE104:
.no_dead_strip _return_parameter_convert__ret_u8_i64
_return_parameter_convert__ret_u8_i64:
LFB105:
	pushq	%rbp
LCFI315:
	movq	%rsp, %rbp
LCFI316:
	movb	%dil, -1(%rbp)
	movzbl	-1(%rbp), %eax
	leave
LCFI317:
	ret
LFE105:
.no_dead_strip _return_parameter_convert__ret_u8_L
_return_parameter_convert__ret_u8_L:
LFB106:
	pushq	%rbp
LCFI318:
	movq	%rsp, %rbp
LCFI319:
	movb	%dil, -1(%rbp)
	movzbl	-1(%rbp), %eax
	leave
LCFI320:
	ret
LFE106:
.no_dead_strip _return_parameter_convert__ret_u8_i8
_return_parameter_convert__ret_u8_i8:
LFB107:
	pushq	%rbp
LCFI321:
	movq	%rsp, %rbp
LCFI322:
	movb	%dil, -1(%rbp)
	movzbl	-1(%rbp), %eax
	leave
LCFI323:
	ret
LFE107:
.no_dead_strip _return_parameter_convert__ret_i64_u32
_return_parameter_convert__ret_i64_u32:
LFB108:
	pushq	%rbp
LCFI324:
	movq	%rsp, %rbp
LCFI325:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI326:
	ret
LFE108:
.no_dead_strip _return_parameter_convert__ret_i64_u16
_return_parameter_convert__ret_i64_u16:
LFB109:
	pushq	%rbp
LCFI327:
	movq	%rsp, %rbp
LCFI328:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI329:
	ret
LFE109:
.no_dead_strip _return_parameter_convert__ret_i64_LC
_return_parameter_convert__ret_i64_LC:
LFB110:
	pushq	%rbp
LCFI330:
	movq	%rsp, %rbp
LCFI331:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI332:
	ret
LFE110:
.no_dead_strip _return_parameter_convert__ret_i64_I
_return_parameter_convert__ret_i64_I:
LFB111:
	pushq	%rbp
LCFI333:
	movq	%rsp, %rbp
LCFI334:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI335:
	ret
LFE111:
.no_dead_strip _return_parameter_convert__ret_i64_u64
_return_parameter_convert__ret_i64_u64:
LFB112:
	pushq	%rbp
LCFI336:
	movq	%rsp, %rbp
LCFI337:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI338:
	ret
LFE112:
.no_dead_strip _return_parameter_convert__ret_i64_i16
_return_parameter_convert__ret_i64_i16:
LFB113:
	pushq	%rbp
LCFI339:
	movq	%rsp, %rbp
LCFI340:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI341:
	ret
LFE113:
.no_dead_strip _return_parameter_convert__ret_i64_C
_return_parameter_convert__ret_i64_C:
LFB114:
	pushq	%rbp
LCFI342:
	movq	%rsp, %rbp
LCFI343:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI344:
	ret
LFE114:
.no_dead_strip _return_parameter_convert__ret_i64_i32
_return_parameter_convert__ret_i64_i32:
LFB115:
	pushq	%rbp
LCFI345:
	movq	%rsp, %rbp
LCFI346:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI347:
	ret
LFE115:
.no_dead_strip _return_parameter_convert__ret_i64_u8
_return_parameter_convert__ret_i64_u8:
LFB116:
	pushq	%rbp
LCFI348:
	movq	%rsp, %rbp
LCFI349:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI350:
	ret
LFE116:
.no_dead_strip _return_parameter_convert__ret_i64_i64
_return_parameter_convert__ret_i64_i64:
LFB117:
	pushq	%rbp
LCFI351:
	movq	%rsp, %rbp
LCFI352:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI353:
	ret
LFE117:
.no_dead_strip _return_parameter_convert__ret_i64_L
_return_parameter_convert__ret_i64_L:
LFB118:
	pushq	%rbp
LCFI354:
	movq	%rsp, %rbp
LCFI355:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI356:
	ret
LFE118:
.no_dead_strip _return_parameter_convert__ret_i64_i8
_return_parameter_convert__ret_i64_i8:
LFB119:
	pushq	%rbp
LCFI357:
	movq	%rsp, %rbp
LCFI358:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI359:
	ret
LFE119:
.no_dead_strip _return_parameter_convert__ret_L_u32
_return_parameter_convert__ret_L_u32:
LFB120:
	pushq	%rbp
LCFI360:
	movq	%rsp, %rbp
LCFI361:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI362:
	ret
LFE120:
.no_dead_strip _return_parameter_convert__ret_L_u16
_return_parameter_convert__ret_L_u16:
LFB121:
	pushq	%rbp
LCFI363:
	movq	%rsp, %rbp
LCFI364:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI365:
	ret
LFE121:
.no_dead_strip _return_parameter_convert__ret_L_LC
_return_parameter_convert__ret_L_LC:
LFB122:
	pushq	%rbp
LCFI366:
	movq	%rsp, %rbp
LCFI367:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI368:
	ret
LFE122:
.no_dead_strip _return_parameter_convert__ret_L_I
_return_parameter_convert__ret_L_I:
LFB123:
	pushq	%rbp
LCFI369:
	movq	%rsp, %rbp
LCFI370:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI371:
	ret
LFE123:
.no_dead_strip _return_parameter_convert__ret_L_u64
_return_parameter_convert__ret_L_u64:
LFB124:
	pushq	%rbp
LCFI372:
	movq	%rsp, %rbp
LCFI373:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI374:
	ret
LFE124:
.no_dead_strip _return_parameter_convert__ret_L_i16
_return_parameter_convert__ret_L_i16:
LFB125:
	pushq	%rbp
LCFI375:
	movq	%rsp, %rbp
LCFI376:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI377:
	ret
LFE125:
.no_dead_strip _return_parameter_convert__ret_L_C
_return_parameter_convert__ret_L_C:
LFB126:
	pushq	%rbp
LCFI378:
	movq	%rsp, %rbp
LCFI379:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI380:
	ret
LFE126:
.no_dead_strip _return_parameter_convert__ret_L_i32
_return_parameter_convert__ret_L_i32:
LFB127:
	pushq	%rbp
LCFI381:
	movq	%rsp, %rbp
LCFI382:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI383:
	ret
LFE127:
.no_dead_strip _return_parameter_convert__ret_L_u8
_return_parameter_convert__ret_L_u8:
LFB128:
	pushq	%rbp
LCFI384:
	movq	%rsp, %rbp
LCFI385:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI386:
	ret
LFE128:
.no_dead_strip _return_parameter_convert__ret_L_i64
_return_parameter_convert__ret_L_i64:
LFB129:
	pushq	%rbp
LCFI387:
	movq	%rsp, %rbp
LCFI388:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI389:
	ret
LFE129:
.no_dead_strip _return_parameter_convert__ret_L_L
_return_parameter_convert__ret_L_L:
LFB130:
	pushq	%rbp
LCFI390:
	movq	%rsp, %rbp
LCFI391:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI392:
	ret
LFE130:
.no_dead_strip _return_parameter_convert__ret_L_i8
_return_parameter_convert__ret_L_i8:
LFB131:
	pushq	%rbp
LCFI393:
	movq	%rsp, %rbp
LCFI394:
	movq	%rdi, -8(%rbp)
	movq	-8(%rbp), %rax
	leave
LCFI395:
	ret
LFE131:
.no_dead_strip _return_parameter_convert__ret_i8_u32
_return_parameter_convert__ret_i8_u32:
LFB132:
	pushq	%rbp
LCFI396:
	movq	%rsp, %rbp
LCFI397:
	movb	%dil, -1(%rbp)
	movsbq	-1(%rbp), %rax
	leave
LCFI398:
	ret
LFE132:
.no_dead_strip _return_parameter_convert__ret_i8_u16
_return_parameter_convert__ret_i8_u16:
LFB133:
	pushq	%rbp
LCFI399:
	movq	%rsp, %rbp
LCFI400:
	movb	%dil, -1(%rbp)
	movsbq	-1(%rbp), %rax
	leave
LCFI401:
	ret
LFE133:
.no_dead_strip _return_parameter_convert__ret_i8_LC
_return_parameter_convert__ret_i8_LC:
LFB134:
	pushq	%rbp
LCFI402:
	movq	%rsp, %rbp
LCFI403:
	movb	%dil, -1(%rbp)
	movsbq	-1(%rbp), %rax
	leave
LCFI404:
	ret
LFE134:
.no_dead_strip _return_parameter_convert__ret_i8_I
_return_parameter_convert__ret_i8_I:
LFB135:
	pushq	%rbp
LCFI405:
	movq	%rsp, %rbp
LCFI406:
	movb	%dil, -1(%rbp)
	movsbq	-1(%rbp), %rax
	leave
LCFI407:
	ret
LFE135:
.no_dead_strip _return_parameter_convert__ret_i8_u64
_return_parameter_convert__ret_i8_u64:
LFB136:
	pushq	%rbp
LCFI408:
	movq	%rsp, %rbp
LCFI409:
	movb	%dil, -1(%rbp)
	movsbq	-1(%rbp), %rax
	leave
LCFI410:
	ret
LFE136:
.no_dead_strip _return_parameter_convert__ret_i8_i16
_return_parameter_convert__ret_i8_i16:
LFB137:
	pushq	%rbp
LCFI411:
	movq	%rsp, %rbp
LCFI412:
	movb	%dil, -1(%rbp)
	movsbq	-1(%rbp), %rax
	leave
LCFI413:
	ret
LFE137:
.no_dead_strip _return_parameter_convert__ret_i8_C
_return_parameter_convert__ret_i8_C:
LFB138:
	pushq	%rbp
LCFI414:
	movq	%rsp, %rbp
LCFI415:
	movb	%dil, -1(%rbp)
	movsbq	-1(%rbp), %rax
	leave
LCFI416:
	ret
LFE138:
.no_dead_strip _return_parameter_convert__ret_i8_i32
_return_parameter_convert__ret_i8_i32:
LFB139:
	pushq	%rbp
LCFI417:
	movq	%rsp, %rbp
LCFI418:
	movb	%dil, -1(%rbp)
	movsbq	-1(%rbp), %rax
	leave
LCFI419:
	ret
LFE139:
.no_dead_strip _return_parameter_convert__ret_i8_u8
_return_parameter_convert__ret_i8_u8:
LFB140:
	pushq	%rbp
LCFI420:
	movq	%rsp, %rbp
LCFI421:
	movb	%dil, -1(%rbp)
	movsbq	-1(%rbp), %rax
	leave
LCFI422:
	ret
LFE140:
.no_dead_strip _return_parameter_convert__ret_i8_i64
_return_parameter_convert__ret_i8_i64:
LFB141:
	pushq	%rbp
LCFI423:
	movq	%rsp, %rbp
LCFI424:
	movb	%dil, -1(%rbp)
	movsbq	-1(%rbp), %rax
	leave
LCFI425:
	ret
LFE141:
.no_dead_strip _return_parameter_convert__ret_i8_L
_return_parameter_convert__ret_i8_L:
LFB142:
	pushq	%rbp
LCFI426:
	movq	%rsp, %rbp
LCFI427:
	movb	%dil, -1(%rbp)
	movsbq	-1(%rbp), %rax
	leave
LCFI428:
	ret
LFE142:
.no_dead_strip _return_parameter_convert__ret_i8_i8
_return_parameter_convert__ret_i8_i8:
LFB143:
	pushq	%rbp
LCFI429:
	movq	%rsp, %rbp
LCFI430:
	movb	%dil, -1(%rbp)
	movsbq	-1(%rbp), %rax
	leave
LCFI431:
	ret
LFE143:
.globl _return_parameter_convert_M3
.no_dead_strip _return_parameter_convert_M3
_return_parameter_convert_M3:
LFB144:
	pushq	%rbp
LCFI432:
	movq	%rsp, %rbp
LCFI433:
	movq	%rdi, -8(%rbp)
	leaq	_MM_return_parameter_convert(%rip), %rax
	leave
LCFI434:
	ret
LFE144:
	.const_data
	.align 5
_L_1:
	.ascii "return_parameter_convert_M3"
	.space 1
	.ascii "ret_i8_i8"
	.space 1
	.ascii "ret_i8_L"
	.space 1
	.ascii "ret_i8_i64"
	.space 1
	.ascii "ret_i8_u8"
	.space 1
	.ascii "ret_i8_i32"
	.space 1
	.ascii "ret_i8_C"
	.space 1
	.ascii "ret_i8_i16"
	.space 1
	.ascii "ret_i8_u64"
	.space 1
	.ascii "ret_i8_I"
	.space 1
	.ascii "ret_i8_LC"
	.space 1
	.ascii "ret_i8_u16"
	.space 1
	.ascii "ret_i8_u32"
	.space 1
	.ascii "ret_L_i8"
	.space 1
	.ascii "ret_L_L"
	.space 1
	.ascii "ret_L_i64"
	.space 1
	.ascii "ret_L_u8"
	.space 1
	.ascii "ret_L_i32"
	.space 1
	.ascii "ret_L_C"
	.space 1
	.ascii "ret_L_i16"
	.space 1
	.ascii "ret_L_u64"
	.space 1
	.ascii "ret_L_I"
	.space 1
	.ascii "ret_L_LC"
	.space 1
	.ascii "ret_L_u16"
	.space 1
	.ascii "ret_L_u32"
	.space 1
	.ascii "ret_i64_i8"
	.space 1
	.ascii "ret_i64_L"
	.space 1
	.ascii "ret_i64_i64"
	.space 1
	.ascii "ret_i64_u8"
	.space 1
	.ascii "ret_i64_i32"
	.space 1
	.ascii "ret_i64_C"
	.space 1
	.ascii "ret_i64_i16"
	.space 1
	.ascii "ret_i64_u64"
	.space 1
	.ascii "ret_i64_I"
	.space 1
	.ascii "ret_i64_LC"
	.space 1
	.ascii "ret_i64_u16"
	.space 1
	.ascii "ret_i64_u32"
	.space 1
	.ascii "ret_u8_i8"
	.space 1
	.ascii "ret_u8_L"
	.space 1
	.ascii "ret_u8_i64"
	.space 1
	.ascii "ret_u8_u8"
	.space 1
	.ascii "ret_u8_i32"
	.space 1
	.ascii "ret_u8_C"
	.space 1
	.ascii "ret_u8_i16"
	.space 1
	.ascii "ret_u8_u64"
	.space 1
	.ascii "ret_u8_I"
	.space 1
	.ascii "ret_u8_LC"
	.space 1
	.ascii "ret_u8_u16"
	.space 1
	.ascii "ret_u8_u32"
	.space 1
	.ascii "ret_i32_i8"
	.space 1
	.ascii "ret_i32_L"
	.space 1
	.ascii "ret_i32_i64"
	.space 1
	.ascii "ret_i32_u8"
	.space 1
	.ascii "ret_i32_i32"
	.space 1
	.ascii "ret_i32_C"
	.space 1
	.ascii "ret_i32_i16"
	.space 1
	.ascii "ret_i32_u64"
	.space 1
	.ascii "ret_i32_I"
	.space 1
	.ascii "ret_i32_LC"
	.space 1
	.ascii "ret_i32_u16"
	.space 1
	.ascii "ret_i32_u32"
	.space 1
	.ascii "ret_C_i8"
	.space 1
	.ascii "ret_C_L"
	.space 1
	.ascii "ret_C_i64"
	.space 1
	.ascii "ret_C_u8"
	.space 1
	.ascii "ret_C_i32"
	.space 1
	.ascii "ret_C_C"
	.space 1
	.ascii "ret_C_i16"
	.space 1
	.ascii "ret_C_u64"
	.space 1
	.ascii "ret_C_I"
	.space 1
	.ascii "ret_C_LC"
	.space 1
	.ascii "ret_C_u16"
	.space 1
	.ascii "ret_C_u32"
	.space 1
	.ascii "ret_i16_i8"
	.space 1
	.ascii "ret_i16_L"
	.space 1
	.ascii "ret_i16_i64"
	.space 1
	.ascii "ret_i16_u8"
	.space 1
	.ascii "ret_i16_i32"
	.space 1
	.ascii "ret_i16_C"
	.space 1
	.ascii "ret_i16_i16"
	.space 1
	.ascii "ret_i16_u64"
	.space 1
	.ascii "ret_i16_I"
	.space 1
	.ascii "ret_i16_LC"
	.space 1
	.ascii "ret_i16_u16"
	.space 1
	.ascii "ret_i16_u32"
	.space 1
	.ascii "ret_u64_i8"
	.space 1
	.ascii "ret_u64_L"
	.space 1
	.ascii "ret_u64_i64"
	.space 1
	.ascii "ret_u64_u8"
	.space 1
	.ascii "ret_u64_i32"
	.space 1
	.ascii "ret_u64_C"
	.space 1
	.ascii "ret_u64_i16"
	.space 1
	.ascii "ret_u64_u64"
	.space 1
	.ascii "ret_u64_I"
	.space 1
	.ascii "ret_u64_LC"
	.space 1
	.ascii "ret_u64_u16"
	.space 1
	.ascii "ret_u64_u32"
	.space 1
	.ascii "ret_I_i8"
	.space 1
	.ascii "ret_I_L"
	.space 1
	.ascii "ret_I_i64"
	.space 1
	.ascii "ret_I_u8"
	.space 1
	.ascii "ret_I_i32"
	.space 1
	.ascii "ret_I_C"
	.space 1
	.ascii "ret_I_i16"
	.space 1
	.ascii "ret_I_u64"
	.space 1
	.ascii "ret_I_I"
	.space 1
	.ascii "ret_I_LC"
	.space 1
	.ascii "ret_I_u16"
	.space 1
	.ascii "ret_I_u32"
	.space 1
	.ascii "ret_LC_i8"
	.space 1
	.ascii "ret_LC_L"
	.space 1
	.ascii "ret_LC_i64"
	.space 1
	.ascii "ret_LC_u8"
	.space 1
	.ascii "ret_LC_i32"
	.space 1
	.ascii "ret_LC_C"
	.space 1
	.ascii "ret_LC_i16"
	.space 1
	.ascii "ret_LC_u64"
	.space 1
	.ascii "ret_LC_I"
	.space 1
	.ascii "ret_LC_LC"
	.space 1
	.ascii "ret_LC_u16"
	.space 1
	.ascii "ret_LC_u32"
	.space 1
	.ascii "ret_u16_i8"
	.space 1
	.ascii "ret_u16_L"
	.space 1
	.ascii "ret_u16_i64"
	.space 1
	.ascii "ret_u16_u8"
	.space 1
	.ascii "ret_u16_i32"
	.space 1
	.ascii "ret_u16_C"
	.space 1
	.ascii "ret_u16_i16"
	.space 1
	.ascii "ret_u16_u64"
	.space 1
	.ascii "ret_u16_I"
	.space 1
	.ascii "ret_u16_LC"
	.space 1
	.ascii "ret_u16_u16"
	.space 1
	.ascii "ret_u16_u32"
	.space 1
	.ascii "ret_u32_i8"
	.space 1
	.ascii "ret_u32_L"
	.space 1
	.ascii "ret_u32_i64"
	.space 1
	.ascii "ret_u32_u8"
	.space 1
	.ascii "ret_u32_i32"
	.space 1
	.ascii "ret_u32_C"
	.space 1
	.ascii "ret_u32_i16"
	.space 1
	.ascii "ret_u32_u64"
	.space 1
	.ascii "ret_u32_I"
	.space 1
	.ascii "ret_u32_LC"
	.space 1
	.ascii "ret_u32_u16"
	.space 1
	.ascii "ret_u32_u32"
	.space 5
	.quad	_return_parameter_convert_M3
	.quad	_L_1
	.quad	_return_parameter_convert__ret_i8_i8
	.quad	_L_1+28
	.quad	_return_parameter_convert__ret_i8_L
	.quad	_L_1+38
	.quad	_return_parameter_convert__ret_i8_i64
	.quad	_L_1+47
	.quad	_return_parameter_convert__ret_i8_u8
	.quad	_L_1+58
	.quad	_return_parameter_convert__ret_i8_i32
	.quad	_L_1+68
	.quad	_return_parameter_convert__ret_i8_C
	.quad	_L_1+79
	.quad	_return_parameter_convert__ret_i8_i16
	.quad	_L_1+88
	.quad	_return_parameter_convert__ret_i8_u64
	.quad	_L_1+99
	.quad	_return_parameter_convert__ret_i8_I
	.quad	_L_1+110
	.quad	_return_parameter_convert__ret_i8_LC
	.quad	_L_1+119
	.quad	_return_parameter_convert__ret_i8_u16
	.quad	_L_1+129
	.quad	_return_parameter_convert__ret_i8_u32
	.quad	_L_1+140
	.quad	_return_parameter_convert__ret_L_i8
	.quad	_L_1+151
	.quad	_return_parameter_convert__ret_L_L
	.quad	_L_1+160
	.quad	_return_parameter_convert__ret_L_i64
	.quad	_L_1+168
	.quad	_return_parameter_convert__ret_L_u8
	.quad	_L_1+178
	.quad	_return_parameter_convert__ret_L_i32
	.quad	_L_1+187
	.quad	_return_parameter_convert__ret_L_C
	.quad	_L_1+197
	.quad	_return_parameter_convert__ret_L_i16
	.quad	_L_1+205
	.quad	_return_parameter_convert__ret_L_u64
	.quad	_L_1+215
	.quad	_return_parameter_convert__ret_L_I
	.quad	_L_1+225
	.quad	_return_parameter_convert__ret_L_LC
	.quad	_L_1+233
	.quad	_return_parameter_convert__ret_L_u16
	.quad	_L_1+242
	.quad	_return_parameter_convert__ret_L_u32
	.quad	_L_1+252
	.quad	_return_parameter_convert__ret_i64_i8
	.quad	_L_1+262
	.quad	_return_parameter_convert__ret_i64_L
	.quad	_L_1+273
	.quad	_return_parameter_convert__ret_i64_i64
	.quad	_L_1+283
	.quad	_return_parameter_convert__ret_i64_u8
	.quad	_L_1+295
	.quad	_return_parameter_convert__ret_i64_i32
	.quad	_L_1+306
	.quad	_return_parameter_convert__ret_i64_C
	.quad	_L_1+318
	.quad	_return_parameter_convert__ret_i64_i16
	.quad	_L_1+328
	.quad	_return_parameter_convert__ret_i64_u64
	.quad	_L_1+340
	.quad	_return_parameter_convert__ret_i64_I
	.quad	_L_1+352
	.quad	_return_parameter_convert__ret_i64_LC
	.quad	_L_1+362
	.quad	_return_parameter_convert__ret_i64_u16
	.quad	_L_1+373
	.quad	_return_parameter_convert__ret_i64_u32
	.quad	_L_1+385
	.quad	_return_parameter_convert__ret_u8_i8
	.quad	_L_1+397
	.quad	_return_parameter_convert__ret_u8_L
	.quad	_L_1+407
	.quad	_return_parameter_convert__ret_u8_i64
	.quad	_L_1+416
	.quad	_return_parameter_convert__ret_u8_u8
	.quad	_L_1+427
	.quad	_return_parameter_convert__ret_u8_i32
	.quad	_L_1+437
	.quad	_return_parameter_convert__ret_u8_C
	.quad	_L_1+448
	.quad	_return_parameter_convert__ret_u8_i16
	.quad	_L_1+457
	.quad	_return_parameter_convert__ret_u8_u64
	.quad	_L_1+468
	.quad	_return_parameter_convert__ret_u8_I
	.quad	_L_1+479
	.quad	_return_parameter_convert__ret_u8_LC
	.quad	_L_1+488
	.quad	_return_parameter_convert__ret_u8_u16
	.quad	_L_1+498
	.quad	_return_parameter_convert__ret_u8_u32
	.quad	_L_1+509
	.quad	_return_parameter_convert__ret_i32_i8
	.quad	_L_1+520
	.quad	_return_parameter_convert__ret_i32_L
	.quad	_L_1+531
	.quad	_return_parameter_convert__ret_i32_i64
	.quad	_L_1+541
	.quad	_return_parameter_convert__ret_i32_u8
	.quad	_L_1+553
	.quad	_return_parameter_convert__ret_i32_i32
	.quad	_L_1+564
	.quad	_return_parameter_convert__ret_i32_C
	.quad	_L_1+576
	.quad	_return_parameter_convert__ret_i32_i16
	.quad	_L_1+586
	.quad	_return_parameter_convert__ret_i32_u64
	.quad	_L_1+598
	.quad	_return_parameter_convert__ret_i32_I
	.quad	_L_1+610
	.quad	_return_parameter_convert__ret_i32_LC
	.quad	_L_1+620
	.quad	_return_parameter_convert__ret_i32_u16
	.quad	_L_1+631
	.quad	_return_parameter_convert__ret_i32_u32
	.quad	_L_1+643
	.quad	_return_parameter_convert__ret_C_i8
	.quad	_L_1+655
	.quad	_return_parameter_convert__ret_C_L
	.quad	_L_1+664
	.quad	_return_parameter_convert__ret_C_i64
	.quad	_L_1+672
	.quad	_return_parameter_convert__ret_C_u8
	.quad	_L_1+682
	.quad	_return_parameter_convert__ret_C_i32
	.quad	_L_1+691
	.quad	_return_parameter_convert__ret_C_C
	.quad	_L_1+701
	.quad	_return_parameter_convert__ret_C_i16
	.quad	_L_1+709
	.quad	_return_parameter_convert__ret_C_u64
	.quad	_L_1+719
	.quad	_return_parameter_convert__ret_C_I
	.quad	_L_1+729
	.quad	_return_parameter_convert__ret_C_LC
	.quad	_L_1+737
	.quad	_return_parameter_convert__ret_C_u16
	.quad	_L_1+746
	.quad	_return_parameter_convert__ret_C_u32
	.quad	_L_1+756
	.quad	_return_parameter_convert__ret_i16_i8
	.quad	_L_1+766
	.quad	_return_parameter_convert__ret_i16_L
	.quad	_L_1+777
	.quad	_return_parameter_convert__ret_i16_i64
	.quad	_L_1+787
	.quad	_return_parameter_convert__ret_i16_u8
	.quad	_L_1+799
	.quad	_return_parameter_convert__ret_i16_i32
	.quad	_L_1+810
	.quad	_return_parameter_convert__ret_i16_C
	.quad	_L_1+822
	.quad	_return_parameter_convert__ret_i16_i16
	.quad	_L_1+832
	.quad	_return_parameter_convert__ret_i16_u64
	.quad	_L_1+844
	.quad	_return_parameter_convert__ret_i16_I
	.quad	_L_1+856
	.quad	_return_parameter_convert__ret_i16_LC
	.quad	_L_1+866
	.quad	_return_parameter_convert__ret_i16_u16
	.quad	_L_1+877
	.quad	_return_parameter_convert__ret_i16_u32
	.quad	_L_1+889
	.quad	_return_parameter_convert__ret_u64_i8
	.quad	_L_1+901
	.quad	_return_parameter_convert__ret_u64_L
	.quad	_L_1+912
	.quad	_return_parameter_convert__ret_u64_i64
	.quad	_L_1+922
	.quad	_return_parameter_convert__ret_u64_u8
	.quad	_L_1+934
	.quad	_return_parameter_convert__ret_u64_i32
	.quad	_L_1+945
	.quad	_return_parameter_convert__ret_u64_C
	.quad	_L_1+957
	.quad	_return_parameter_convert__ret_u64_i16
	.quad	_L_1+967
	.quad	_return_parameter_convert__ret_u64_u64
	.quad	_L_1+979
	.quad	_return_parameter_convert__ret_u64_I
	.quad	_L_1+991
	.quad	_return_parameter_convert__ret_u64_LC
	.quad	_L_1+1001
	.quad	_return_parameter_convert__ret_u64_u16
	.quad	_L_1+1012
	.quad	_return_parameter_convert__ret_u64_u32
	.quad	_L_1+1024
	.quad	_return_parameter_convert__ret_I_i8
	.quad	_L_1+1036
	.quad	_return_parameter_convert__ret_I_L
	.quad	_L_1+1045
	.quad	_return_parameter_convert__ret_I_i64
	.quad	_L_1+1053
	.quad	_return_parameter_convert__ret_I_u8
	.quad	_L_1+1063
	.quad	_return_parameter_convert__ret_I_i32
	.quad	_L_1+1072
	.quad	_return_parameter_convert__ret_I_C
	.quad	_L_1+1082
	.quad	_return_parameter_convert__ret_I_i16
	.quad	_L_1+1090
	.quad	_return_parameter_convert__ret_I_u64
	.quad	_L_1+1100
	.quad	_return_parameter_convert__ret_I_I
	.quad	_L_1+1110
	.quad	_return_parameter_convert__ret_I_LC
	.quad	_L_1+1118
	.quad	_return_parameter_convert__ret_I_u16
	.quad	_L_1+1127
	.quad	_return_parameter_convert__ret_I_u32
	.quad	_L_1+1137
	.quad	_return_parameter_convert__ret_LC_i8
	.quad	_L_1+1147
	.quad	_return_parameter_convert__ret_LC_L
	.quad	_L_1+1157
	.quad	_return_parameter_convert__ret_LC_i64
	.quad	_L_1+1166
	.quad	_return_parameter_convert__ret_LC_u8
	.quad	_L_1+1177
	.quad	_return_parameter_convert__ret_LC_i32
	.quad	_L_1+1187
	.quad	_return_parameter_convert__ret_LC_C
	.quad	_L_1+1198
	.quad	_return_parameter_convert__ret_LC_i16
	.quad	_L_1+1207
	.quad	_return_parameter_convert__ret_LC_u64
	.quad	_L_1+1218
	.quad	_return_parameter_convert__ret_LC_I
	.quad	_L_1+1229
	.quad	_return_parameter_convert__ret_LC_LC
	.quad	_L_1+1238
	.quad	_return_parameter_convert__ret_LC_u16
	.quad	_L_1+1248
	.quad	_return_parameter_convert__ret_LC_u32
	.quad	_L_1+1259
	.quad	_return_parameter_convert__ret_u16_i8
	.quad	_L_1+1270
	.quad	_return_parameter_convert__ret_u16_L
	.quad	_L_1+1281
	.quad	_return_parameter_convert__ret_u16_i64
	.quad	_L_1+1291
	.quad	_return_parameter_convert__ret_u16_u8
	.quad	_L_1+1303
	.quad	_return_parameter_convert__ret_u16_i32
	.quad	_L_1+1314
	.quad	_return_parameter_convert__ret_u16_C
	.quad	_L_1+1326
	.quad	_return_parameter_convert__ret_u16_i16
	.quad	_L_1+1336
	.quad	_return_parameter_convert__ret_u16_u64
	.quad	_L_1+1348
	.quad	_return_parameter_convert__ret_u16_I
	.quad	_L_1+1360
	.quad	_return_parameter_convert__ret_u16_LC
	.quad	_L_1+1370
	.quad	_return_parameter_convert__ret_u16_u16
	.quad	_L_1+1381
	.quad	_return_parameter_convert__ret_u16_u32
	.quad	_L_1+1393
	.quad	_return_parameter_convert__ret_u32_i8
	.quad	_L_1+1405
	.quad	_return_parameter_convert__ret_u32_L
	.quad	_L_1+1416
	.quad	_return_parameter_convert__ret_u32_i64
	.quad	_L_1+1426
	.quad	_return_parameter_convert__ret_u32_u8
	.quad	_L_1+1438
	.quad	_return_parameter_convert__ret_u32_i32
	.quad	_L_1+1449
	.quad	_return_parameter_convert__ret_u32_C
	.quad	_L_1+1461
	.quad	_return_parameter_convert__ret_u32_i16
	.quad	_L_1+1471
	.quad	_return_parameter_convert__ret_u32_u64
	.quad	_L_1+1483
	.quad	_return_parameter_convert__ret_u32_I
	.quad	_L_1+1495
	.quad	_return_parameter_convert__ret_u32_LC
	.quad	_L_1+1505
	.quad	_return_parameter_convert__ret_u32_u16
	.quad	_L_1+1516
	.quad	_return_parameter_convert__ret_u32_u32
	.quad	_L_1+1528
	.space 8
	.ascii "../AMD64_DARWIN/return_parameter_convert.m3"
	.space 5
	.data
	.align 5
_MM_return_parameter_convert:
	.quad	_L_1+3872
	.space 32
	.quad	_L_1+1544
	.space 24
	.quad	_MM_return_parameter_convert+224
	.space 8
	.quad	_return_parameter_convert_M3
	.quad	3
	.word	113
	.space 2
	.long	114
	.quad	115
	.quad	116
	.word	117
	.space 6
	.quad	118
	.long	343597384
	.long	1079887790
	.long	121
	.space 4
	.quad	122
	.byte	123
	.space 7
	.quad	124
	.long	1123696771
	.space 4
	.quad	127
	.byte	-128
	.space 31
	.quad	_return_parameter_convert_I3
	.quad	_MM_return_parameter_convert+248
	.space 8
	.quad	_Long_I3
	.quad	_MM_return_parameter_convert+272
	.space 8
	.quad	_Word_I3
	.quad	_MM_return_parameter_convert+296
	.space 8
	.quad	_Cstdint_I3
	.quad	_MM_return_parameter_convert+320
	.space 8
	.quad	_RTHooks_I3
	.space 8
_return_parameter_convert__ret_u32_u32.eh = 0
.no_dead_strip _return_parameter_convert__ret_u32_u32.eh
_return_parameter_convert__ret_u32_u16.eh = 0
.no_dead_strip _return_parameter_convert__ret_u32_u16.eh
_return_parameter_convert__ret_u32_LC.eh = 0
.no_dead_strip _return_parameter_convert__ret_u32_LC.eh
_return_parameter_convert__ret_u32_I.eh = 0
.no_dead_strip _return_parameter_convert__ret_u32_I.eh
_return_parameter_convert__ret_u32_u64.eh = 0
.no_dead_strip _return_parameter_convert__ret_u32_u64.eh
_return_parameter_convert__ret_u32_i16.eh = 0
.no_dead_strip _return_parameter_convert__ret_u32_i16.eh
_return_parameter_convert__ret_u32_C.eh = 0
.no_dead_strip _return_parameter_convert__ret_u32_C.eh
_return_parameter_convert__ret_u32_i32.eh = 0
.no_dead_strip _return_parameter_convert__ret_u32_i32.eh
_return_parameter_convert__ret_u32_u8.eh = 0
.no_dead_strip _return_parameter_convert__ret_u32_u8.eh
_return_parameter_convert__ret_u32_i64.eh = 0
.no_dead_strip _return_parameter_convert__ret_u32_i64.eh
_return_parameter_convert__ret_u32_L.eh = 0
.no_dead_strip _return_parameter_convert__ret_u32_L.eh
_return_parameter_convert__ret_u32_i8.eh = 0
.no_dead_strip _return_parameter_convert__ret_u32_i8.eh
_return_parameter_convert__ret_u16_u32.eh = 0
.no_dead_strip _return_parameter_convert__ret_u16_u32.eh
_return_parameter_convert__ret_u16_u16.eh = 0
.no_dead_strip _return_parameter_convert__ret_u16_u16.eh
_return_parameter_convert__ret_u16_LC.eh = 0
.no_dead_strip _return_parameter_convert__ret_u16_LC.eh
_return_parameter_convert__ret_u16_I.eh = 0
.no_dead_strip _return_parameter_convert__ret_u16_I.eh
_return_parameter_convert__ret_u16_u64.eh = 0
.no_dead_strip _return_parameter_convert__ret_u16_u64.eh
_return_parameter_convert__ret_u16_i16.eh = 0
.no_dead_strip _return_parameter_convert__ret_u16_i16.eh
_return_parameter_convert__ret_u16_C.eh = 0
.no_dead_strip _return_parameter_convert__ret_u16_C.eh
_return_parameter_convert__ret_u16_i32.eh = 0
.no_dead_strip _return_parameter_convert__ret_u16_i32.eh
_return_parameter_convert__ret_u16_u8.eh = 0
.no_dead_strip _return_parameter_convert__ret_u16_u8.eh
_return_parameter_convert__ret_u16_i64.eh = 0
.no_dead_strip _return_parameter_convert__ret_u16_i64.eh
_return_parameter_convert__ret_u16_L.eh = 0
.no_dead_strip _return_parameter_convert__ret_u16_L.eh
_return_parameter_convert__ret_u16_i8.eh = 0
.no_dead_strip _return_parameter_convert__ret_u16_i8.eh
_return_parameter_convert__ret_LC_u32.eh = 0
.no_dead_strip _return_parameter_convert__ret_LC_u32.eh
_return_parameter_convert__ret_LC_u16.eh = 0
.no_dead_strip _return_parameter_convert__ret_LC_u16.eh
_return_parameter_convert__ret_LC_LC.eh = 0
.no_dead_strip _return_parameter_convert__ret_LC_LC.eh
_return_parameter_convert__ret_LC_I.eh = 0
.no_dead_strip _return_parameter_convert__ret_LC_I.eh
_return_parameter_convert__ret_LC_u64.eh = 0
.no_dead_strip _return_parameter_convert__ret_LC_u64.eh
_return_parameter_convert__ret_LC_i16.eh = 0
.no_dead_strip _return_parameter_convert__ret_LC_i16.eh
_return_parameter_convert__ret_LC_C.eh = 0
.no_dead_strip _return_parameter_convert__ret_LC_C.eh
_return_parameter_convert__ret_LC_i32.eh = 0
.no_dead_strip _return_parameter_convert__ret_LC_i32.eh
_return_parameter_convert__ret_LC_u8.eh = 0
.no_dead_strip _return_parameter_convert__ret_LC_u8.eh
_return_parameter_convert__ret_LC_i64.eh = 0
.no_dead_strip _return_parameter_convert__ret_LC_i64.eh
_return_parameter_convert__ret_LC_L.eh = 0
.no_dead_strip _return_parameter_convert__ret_LC_L.eh
_return_parameter_convert__ret_LC_i8.eh = 0
.no_dead_strip _return_parameter_convert__ret_LC_i8.eh
_return_parameter_convert__ret_I_u32.eh = 0
.no_dead_strip _return_parameter_convert__ret_I_u32.eh
_return_parameter_convert__ret_I_u16.eh = 0
.no_dead_strip _return_parameter_convert__ret_I_u16.eh
_return_parameter_convert__ret_I_LC.eh = 0
.no_dead_strip _return_parameter_convert__ret_I_LC.eh
_return_parameter_convert__ret_I_I.eh = 0
.no_dead_strip _return_parameter_convert__ret_I_I.eh
_return_parameter_convert__ret_I_u64.eh = 0
.no_dead_strip _return_parameter_convert__ret_I_u64.eh
_return_parameter_convert__ret_I_i16.eh = 0
.no_dead_strip _return_parameter_convert__ret_I_i16.eh
_return_parameter_convert__ret_I_C.eh = 0
.no_dead_strip _return_parameter_convert__ret_I_C.eh
_return_parameter_convert__ret_I_i32.eh = 0
.no_dead_strip _return_parameter_convert__ret_I_i32.eh
_return_parameter_convert__ret_I_u8.eh = 0
.no_dead_strip _return_parameter_convert__ret_I_u8.eh
_return_parameter_convert__ret_I_i64.eh = 0
.no_dead_strip _return_parameter_convert__ret_I_i64.eh
_return_parameter_convert__ret_I_L.eh = 0
.no_dead_strip _return_parameter_convert__ret_I_L.eh
_return_parameter_convert__ret_I_i8.eh = 0
.no_dead_strip _return_parameter_convert__ret_I_i8.eh
_return_parameter_convert__ret_u64_u32.eh = 0
.no_dead_strip _return_parameter_convert__ret_u64_u32.eh
_return_parameter_convert__ret_u64_u16.eh = 0
.no_dead_strip _return_parameter_convert__ret_u64_u16.eh
_return_parameter_convert__ret_u64_LC.eh = 0
.no_dead_strip _return_parameter_convert__ret_u64_LC.eh
_return_parameter_convert__ret_u64_I.eh = 0
.no_dead_strip _return_parameter_convert__ret_u64_I.eh
_return_parameter_convert__ret_u64_u64.eh = 0
.no_dead_strip _return_parameter_convert__ret_u64_u64.eh
_return_parameter_convert__ret_u64_i16.eh = 0
.no_dead_strip _return_parameter_convert__ret_u64_i16.eh
_return_parameter_convert__ret_u64_C.eh = 0
.no_dead_strip _return_parameter_convert__ret_u64_C.eh
_return_parameter_convert__ret_u64_i32.eh = 0
.no_dead_strip _return_parameter_convert__ret_u64_i32.eh
_return_parameter_convert__ret_u64_u8.eh = 0
.no_dead_strip _return_parameter_convert__ret_u64_u8.eh
_return_parameter_convert__ret_u64_i64.eh = 0
.no_dead_strip _return_parameter_convert__ret_u64_i64.eh
_return_parameter_convert__ret_u64_L.eh = 0
.no_dead_strip _return_parameter_convert__ret_u64_L.eh
_return_parameter_convert__ret_u64_i8.eh = 0
.no_dead_strip _return_parameter_convert__ret_u64_i8.eh
_return_parameter_convert__ret_i16_u32.eh = 0
.no_dead_strip _return_parameter_convert__ret_i16_u32.eh
_return_parameter_convert__ret_i16_u16.eh = 0
.no_dead_strip _return_parameter_convert__ret_i16_u16.eh
_return_parameter_convert__ret_i16_LC.eh = 0
.no_dead_strip _return_parameter_convert__ret_i16_LC.eh
_return_parameter_convert__ret_i16_I.eh = 0
.no_dead_strip _return_parameter_convert__ret_i16_I.eh
_return_parameter_convert__ret_i16_u64.eh = 0
.no_dead_strip _return_parameter_convert__ret_i16_u64.eh
_return_parameter_convert__ret_i16_i16.eh = 0
.no_dead_strip _return_parameter_convert__ret_i16_i16.eh
_return_parameter_convert__ret_i16_C.eh = 0
.no_dead_strip _return_parameter_convert__ret_i16_C.eh
_return_parameter_convert__ret_i16_i32.eh = 0
.no_dead_strip _return_parameter_convert__ret_i16_i32.eh
_return_parameter_convert__ret_i16_u8.eh = 0
.no_dead_strip _return_parameter_convert__ret_i16_u8.eh
_return_parameter_convert__ret_i16_i64.eh = 0
.no_dead_strip _return_parameter_convert__ret_i16_i64.eh
_return_parameter_convert__ret_i16_L.eh = 0
.no_dead_strip _return_parameter_convert__ret_i16_L.eh
_return_parameter_convert__ret_i16_i8.eh = 0
.no_dead_strip _return_parameter_convert__ret_i16_i8.eh
_return_parameter_convert__ret_C_u32.eh = 0
.no_dead_strip _return_parameter_convert__ret_C_u32.eh
_return_parameter_convert__ret_C_u16.eh = 0
.no_dead_strip _return_parameter_convert__ret_C_u16.eh
_return_parameter_convert__ret_C_LC.eh = 0
.no_dead_strip _return_parameter_convert__ret_C_LC.eh
_return_parameter_convert__ret_C_I.eh = 0
.no_dead_strip _return_parameter_convert__ret_C_I.eh
_return_parameter_convert__ret_C_u64.eh = 0
.no_dead_strip _return_parameter_convert__ret_C_u64.eh
_return_parameter_convert__ret_C_i16.eh = 0
.no_dead_strip _return_parameter_convert__ret_C_i16.eh
_return_parameter_convert__ret_C_C.eh = 0
.no_dead_strip _return_parameter_convert__ret_C_C.eh
_return_parameter_convert__ret_C_i32.eh = 0
.no_dead_strip _return_parameter_convert__ret_C_i32.eh
_return_parameter_convert__ret_C_u8.eh = 0
.no_dead_strip _return_parameter_convert__ret_C_u8.eh
_return_parameter_convert__ret_C_i64.eh = 0
.no_dead_strip _return_parameter_convert__ret_C_i64.eh
_return_parameter_convert__ret_C_L.eh = 0
.no_dead_strip _return_parameter_convert__ret_C_L.eh
_return_parameter_convert__ret_C_i8.eh = 0
.no_dead_strip _return_parameter_convert__ret_C_i8.eh
_return_parameter_convert__ret_i32_u32.eh = 0
.no_dead_strip _return_parameter_convert__ret_i32_u32.eh
_return_parameter_convert__ret_i32_u16.eh = 0
.no_dead_strip _return_parameter_convert__ret_i32_u16.eh
_return_parameter_convert__ret_i32_LC.eh = 0
.no_dead_strip _return_parameter_convert__ret_i32_LC.eh
_return_parameter_convert__ret_i32_I.eh = 0
.no_dead_strip _return_parameter_convert__ret_i32_I.eh
_return_parameter_convert__ret_i32_u64.eh = 0
.no_dead_strip _return_parameter_convert__ret_i32_u64.eh
_return_parameter_convert__ret_i32_i16.eh = 0
.no_dead_strip _return_parameter_convert__ret_i32_i16.eh
_return_parameter_convert__ret_i32_C.eh = 0
.no_dead_strip _return_parameter_convert__ret_i32_C.eh
_return_parameter_convert__ret_i32_i32.eh = 0
.no_dead_strip _return_parameter_convert__ret_i32_i32.eh
_return_parameter_convert__ret_i32_u8.eh = 0
.no_dead_strip _return_parameter_convert__ret_i32_u8.eh
_return_parameter_convert__ret_i32_i64.eh = 0
.no_dead_strip _return_parameter_convert__ret_i32_i64.eh
_return_parameter_convert__ret_i32_L.eh = 0
.no_dead_strip _return_parameter_convert__ret_i32_L.eh
_return_parameter_convert__ret_i32_i8.eh = 0
.no_dead_strip _return_parameter_convert__ret_i32_i8.eh
_return_parameter_convert__ret_u8_u32.eh = 0
.no_dead_strip _return_parameter_convert__ret_u8_u32.eh
_return_parameter_convert__ret_u8_u16.eh = 0
.no_dead_strip _return_parameter_convert__ret_u8_u16.eh
_return_parameter_convert__ret_u8_LC.eh = 0
.no_dead_strip _return_parameter_convert__ret_u8_LC.eh
_return_parameter_convert__ret_u8_I.eh = 0
.no_dead_strip _return_parameter_convert__ret_u8_I.eh
_return_parameter_convert__ret_u8_u64.eh = 0
.no_dead_strip _return_parameter_convert__ret_u8_u64.eh
_return_parameter_convert__ret_u8_i16.eh = 0
.no_dead_strip _return_parameter_convert__ret_u8_i16.eh
_return_parameter_convert__ret_u8_C.eh = 0
.no_dead_strip _return_parameter_convert__ret_u8_C.eh
_return_parameter_convert__ret_u8_i32.eh = 0
.no_dead_strip _return_parameter_convert__ret_u8_i32.eh
_return_parameter_convert__ret_u8_u8.eh = 0
.no_dead_strip _return_parameter_convert__ret_u8_u8.eh
_return_parameter_convert__ret_u8_i64.eh = 0
.no_dead_strip _return_parameter_convert__ret_u8_i64.eh
_return_parameter_convert__ret_u8_L.eh = 0
.no_dead_strip _return_parameter_convert__ret_u8_L.eh
_return_parameter_convert__ret_u8_i8.eh = 0
.no_dead_strip _return_parameter_convert__ret_u8_i8.eh
_return_parameter_convert__ret_i64_u32.eh = 0
.no_dead_strip _return_parameter_convert__ret_i64_u32.eh
_return_parameter_convert__ret_i64_u16.eh = 0
.no_dead_strip _return_parameter_convert__ret_i64_u16.eh
_return_parameter_convert__ret_i64_LC.eh = 0
.no_dead_strip _return_parameter_convert__ret_i64_LC.eh
_return_parameter_convert__ret_i64_I.eh = 0
.no_dead_strip _return_parameter_convert__ret_i64_I.eh
_return_parameter_convert__ret_i64_u64.eh = 0
.no_dead_strip _return_parameter_convert__ret_i64_u64.eh
_return_parameter_convert__ret_i64_i16.eh = 0
.no_dead_strip _return_parameter_convert__ret_i64_i16.eh
_return_parameter_convert__ret_i64_C.eh = 0
.no_dead_strip _return_parameter_convert__ret_i64_C.eh
_return_parameter_convert__ret_i64_i32.eh = 0
.no_dead_strip _return_parameter_convert__ret_i64_i32.eh
_return_parameter_convert__ret_i64_u8.eh = 0
.no_dead_strip _return_parameter_convert__ret_i64_u8.eh
_return_parameter_convert__ret_i64_i64.eh = 0
.no_dead_strip _return_parameter_convert__ret_i64_i64.eh
_return_parameter_convert__ret_i64_L.eh = 0
.no_dead_strip _return_parameter_convert__ret_i64_L.eh
_return_parameter_convert__ret_i64_i8.eh = 0
.no_dead_strip _return_parameter_convert__ret_i64_i8.eh
_return_parameter_convert__ret_L_u32.eh = 0
.no_dead_strip _return_parameter_convert__ret_L_u32.eh
_return_parameter_convert__ret_L_u16.eh = 0
.no_dead_strip _return_parameter_convert__ret_L_u16.eh
_return_parameter_convert__ret_L_LC.eh = 0
.no_dead_strip _return_parameter_convert__ret_L_LC.eh
_return_parameter_convert__ret_L_I.eh = 0
.no_dead_strip _return_parameter_convert__ret_L_I.eh
_return_parameter_convert__ret_L_u64.eh = 0
.no_dead_strip _return_parameter_convert__ret_L_u64.eh
_return_parameter_convert__ret_L_i16.eh = 0
.no_dead_strip _return_parameter_convert__ret_L_i16.eh
_return_parameter_convert__ret_L_C.eh = 0
.no_dead_strip _return_parameter_convert__ret_L_C.eh
_return_parameter_convert__ret_L_i32.eh = 0
.no_dead_strip _return_parameter_convert__ret_L_i32.eh
_return_parameter_convert__ret_L_u8.eh = 0
.no_dead_strip _return_parameter_convert__ret_L_u8.eh
_return_parameter_convert__ret_L_i64.eh = 0
.no_dead_strip _return_parameter_convert__ret_L_i64.eh
_return_parameter_convert__ret_L_L.eh = 0
.no_dead_strip _return_parameter_convert__ret_L_L.eh
_return_parameter_convert__ret_L_i8.eh = 0
.no_dead_strip _return_parameter_convert__ret_L_i8.eh
_return_parameter_convert__ret_i8_u32.eh = 0
.no_dead_strip _return_parameter_convert__ret_i8_u32.eh
_return_parameter_convert__ret_i8_u16.eh = 0
.no_dead_strip _return_parameter_convert__ret_i8_u16.eh
_return_parameter_convert__ret_i8_LC.eh = 0
.no_dead_strip _return_parameter_convert__ret_i8_LC.eh
_return_parameter_convert__ret_i8_I.eh = 0
.no_dead_strip _return_parameter_convert__ret_i8_I.eh
_return_parameter_convert__ret_i8_u64.eh = 0
.no_dead_strip _return_parameter_convert__ret_i8_u64.eh
_return_parameter_convert__ret_i8_i16.eh = 0
.no_dead_strip _return_parameter_convert__ret_i8_i16.eh
_return_parameter_convert__ret_i8_C.eh = 0
.no_dead_strip _return_parameter_convert__ret_i8_C.eh
_return_parameter_convert__ret_i8_i32.eh = 0
.no_dead_strip _return_parameter_convert__ret_i8_i32.eh
_return_parameter_convert__ret_i8_u8.eh = 0
.no_dead_strip _return_parameter_convert__ret_i8_u8.eh
_return_parameter_convert__ret_i8_i64.eh = 0
.no_dead_strip _return_parameter_convert__ret_i8_i64.eh
_return_parameter_convert__ret_i8_L.eh = 0
.no_dead_strip _return_parameter_convert__ret_i8_L.eh
_return_parameter_convert__ret_i8_i8.eh = 0
.no_dead_strip _return_parameter_convert__ret_i8_i8.eh
.globl _return_parameter_convert_M3.eh
_return_parameter_convert_M3.eh = 0
.no_dead_strip _return_parameter_convert_M3.eh
	.subsections_via_symbols
