if not HasTrestle()
  build_standalone()
end

if not defined("TOP")
  TOP = PACKAGE_DIR & SL & ".." 
end

import("vbtkit")
import("ui")
import("m3tk")
import("libm3")
import("cit_util")
import("term")

%Module("PathnameUtils") % in cit_utils
template("liste")
generic_module("ListExtras")
template("channel")
generic_module("Channel")
module("KeyRec")
channel("Key", "KeyRec")
liste("Key", "KeyRec")

template("starter")
generic_module("Starter")
Module("Starter")
Interface("PaneVBT")
generic_module("VBTPane")
List("Starter","Starter")
Module("StarterScan")
List("StarterScan", "StarterScan")
module("StartingStarters")

template("squat")
generic_module("Squat")
squat("TextPane","TextPane")
squat("TextVBT","TextVBT")
module("TextPane")
Starter("TextPane","TextPane")
module("MiniPane")
interface("ListPane")
Starter("ListPane", "ListPane")

template("queue")
generic_module("Queue")

module("Pane")
module("PaneFrame")
Liste("Pane", "Pane")
module("KeyDaemon")
module("PaneManVBT")
Module("IOPaneMan")
Module("PaneMan")

Interface("PaneManOp")
interface("PaneManRequest")
channel("PMRequest", "PaneManRequest")
module("RequestDaemon")

Library("paneman")
