% Copyright (C) 1995, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Aug 27 10:55:43 PDT 1996 by najork
%      modified on Wed Jun 14 11:59:54 PDT 1995 by kalsow

if HasTrestle()

m3_option ("-times")
import ("libbuf")
import ("vbtkit")


%
% Find a place to put score files...
%
if not defined ("SCOREDIR")
  if equal(OS_TYPE, "POSIX")
    SCOREDIR = "/tmp"
  else
    SCOREDIR = "c:\\temp"
  end
  write (CR, "NOTE: Fours will put its score files in \"",SCOREDIR,"\"", CR)
  write ("To reconfigure Fours, run:  cm3 -DSCOREDIR=/your/path", CR, CR)
end
> "ScoreDir.i0" in
  write ("INTERFACE ScoreDir;", CR)
  write ("CONST Root = \"", escape(SCOREDIR & SL), "\";", CR)
  write ("END ScoreDir.", CR)
end
cp_if ("ScoreDir.i0", "ScoreDir.i3")
derived_interface ("ScoreDir", HIDDEN)

module ("ScoreFile")
module ("Config")
implementation ("Main")

m3_option ("-gui")
Program ("Fours")
ManPage ("Fours", "1")

end
