import("libm3")

template("physicalvalue")


module("PhysicalUnit")
module("PhysicalUnitFmtLex")

generic_module("CompositeUnit")
generic_module("UsualUnit")
generic_module("UnitDatabase")
UnitDatabase("Real",     "Real",     "Basic")
UnitDatabase("LongReal", "LongReal", "Basic")
UnitDatabase("Extended", "Extended", "Basic")

generic_module("SIUnit")
SIUnit("Real",     "Real",     "Basic")
SIUnit("LongReal", "LongReal", "Basic")
SIUnit("Extended", "Extended", "Basic")

generic_module("PhysicalValue")
PhysicalValue("Integer32",       "Integer32",       "Basic")
PhysicalValue("BigInteger",      "BigInteger",      "")
PhysicalValue("Real",            "Real",            "Basic")
PhysicalValue("LongReal",        "LongReal",        "Basic")
PhysicalValue("Extended",        "Extended",        "Basic")
PhysicalValue("RealComplex",     "RealComplex",     "Fast")
PhysicalValue("LongRealComplex", "LongRealComplex", "Fast")
PhysicalValue("ExtendedComplex", "ExtendedComplex", "Fast")

generic_module("PhysicalValueFmtLex")
PhysicalValueFmtLex("Real",            "Real",     "Basic", "",        "Basic")
PhysicalValueFmtLex("LongReal",        "LongReal", "Basic", "",        "Basic")
PhysicalValueFmtLex("Extended",        "Extended", "Basic", "",        "Basic")
PhysicalValueFmtLex("RealComplex",     "Real",     "Basic", "Complex", "Fast")
PhysicalValueFmtLex("LongRealComplex", "LongReal", "Basic", "Complex", "Fast")
PhysicalValueFmtLex("ExtendedComplex", "Extended", "Basic", "Complex", "Fast")
