import("libm3")

template("physicalvalue")


module("PhysicalUnit")
module("PhysicalUnitFmtLex")

generic_module("CompositeUnit")
generic_module("UsualUnit")
generic_module("UnitDatabase")
UnitDatabase("Real",     "Real",     "Basic")
UnitDatabase("LongReal", "LongReal", "Basic")
UnitDatabase("Extended", "Extended", "Basic")

generic_module("SIUnit")
SIUnit("Real",     "Real",     "Basic")
SIUnit("LongReal", "LongReal", "Basic")
SIUnit("Extended", "Extended", "Basic")

generic_module("PhysicalValue")
PhysicalValue("Integer32",       "Integer32Basic")
PhysicalValue("BigInteger",      "BigInteger")
PhysicalValue("Real",            "RealBasic")
PhysicalValue("LongReal",        "LongRealBasic")
PhysicalValue("Extended",        "ExtendedBasic")
PhysicalValue("RealComplex",     "RealComplex")
PhysicalValue("LongRealComplex", "LongRealComplex")
PhysicalValue("ExtendedComplex", "ExtendedComplex")

generic_module("PhysicalValueFmtLex")
PhysicalValueFmtLex("Real",            "Real",     "Basic", "Basic")
PhysicalValueFmtLex("LongReal",        "LongReal", "Basic", "Basic")
PhysicalValueFmtLex("Extended",        "Extended", "Basic", "Basic")
PhysicalValueFmtLex("RealComplex",     "Real",     "Basic", "")
PhysicalValueFmtLex("LongRealComplex", "LongReal", "Basic", "")
PhysicalValueFmtLex("ExtendedComplex", "Extended", "Basic", "")
