% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

interface      ("RTMachine")
c_source       ("RTStackC")
s_source       ("RTStackASM")
