/* Copyright (C) 1994, Digital Equipment Corporation                         */
/* Digital Internal Use Only                                                 */
/* All rights reserved.                                                      */
/*                                                                           */
/* Last modified on Tue Oct 10 15:44:50 PDT 1995 by najork                   */
/*       Created on Fri Aug 19 15:25:43 PDT 1994 by najork                   */

/* Relevant C header files:                                                  */
/* Vendor-Independent:  gl.h glu.h glx.h                                     */
/* Vendor-Dependent:    glxdecproto.h glxint.h glxmd.h glxproto.h            */

import ("X11R4")

% The Win32 bindings work on Unix.
% The Unix compiler ignores the Win32 calling convention annotations.
% The bindings were otherwise identical.
Interface ("../WIN32/GL")
Interface ("GLX")
Interface ("../WIN32/GLu")
