% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Feb 23 15:54:12 PST 1994 by kalsow
%      modified on Fri Jan 15 14:40:34 PST 1993 by jdd
%      modified on Tue Jun 16 19:06:34 PDT 1992 by muller

import ("vbtkit")

module ("ZIO")
implementation ("ShowNew")

build_standalone ()
Program ("shownew")

ManPage ("shownew","1")
