import("libm3")

Module("RandomBasic")
Interface("RandomRep")

%module("RandomNumber01")
Module("RandomDECSRC")
Module("RandomParkMiller")
Module("RandomBayesDurham")

%module("RandomNumber02")
Module("RandomCombinedSlow")
Module("RandomCombinedFast")
Module("RandomImprovedMcGill")
Module("RandomIteratedSquaring")
Module("RandomMultiplicativeFibo")
Module("RandomQuaternaryFibo")
Module("RandomSubtractiveFibo1")
Module("RandomSubtractiveFibo2")
Module("RandomWolframCA")

Module("Statistic")
