% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Oct 31 13:25:59 PST 1994 by kalsow
%      modified on Tue Mar 24 21:36:54 PST 1992 by muller

Module    ("Udir")
Module    ("Uerror")
Interface ("Uexec")
Interface ("Ugrp")
Module    ("Uin")
Interface ("Uipc")
Interface ("Umman")
Module    ("Umsg")
Module    ("Unetdb")
Module    ("Unix")
Interface ("Uprocess")
Interface ("Upwd")
Interface ("Uresource")
Interface ("Usem")
Interface ("Ushm")
Module    ("Usignal")
Interface ("Usocket")
Interface ("Ustat")
Interface ("Utime")
Module    ("Utypes")
Interface ("Uugid")
Interface ("Uuio")
Interface ("Uutmp")

% Dir.c is buggy on '/net'.
% c_source ("Dir")

