% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Jul 30 13:55:56 EST 1997 by hosking
%      modified on Mon Oct 31 13:25:59 PST 1994 by kalsow
%      modified on Tue Mar 24 21:36:54 PST 1992 by muller

Interface ("Udir")
Interface ("Uerror")
Interface ("Uexec")
Interface ("Uframe")
Interface ("Ugrp")
Module    ("Uin")
Interface ("Uipc")
Interface ("Umman")
Module    ("Umsg")
Module    ("Unetdb")
Module    ("Unix")
Interface ("Uprocess")
Interface ("Upwd")
Interface ("Uresource")
Interface ("Usem")
Interface ("Ushm")
Module    ("Usignal")
Interface ("Usocket")
Interface ("Ustat")
Interface ("Utermio")
Interface ("Utime")
Module    ("Utypes")
Interface ("Uucontext")
Interface ("Uugid")
Interface ("Uuio")
Interface ("Uutmp")
Interface ("Uutsname")

% Dir.c is buggy on '/net'.
% c_source ("Dir")

