% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Mon Feb 10 16:54:48 PST 1992 by muller

c_source ("dtoa")
h_source ("float")

