/* Copyright (C) 1993, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Tue May  4 10:17:51 PDT 1993 by mjordan                  */

include_dir ("Common")


if equal (OS_TYPE, "WIN32") or equal(TARGET, "NT386")
    or ({"NT", "MINGW", "CYGWIN"} contains TARGET)
  include_dir ("WIN32")
else
  if (not defined("NOPTHREAD"))
     and (not equal(TARGET_OS, "OPENBSD"))
     and (not IsTargetFreeBSD4())
    include_dir("PTHREAD")
  else
    include_dir (OS_TYPE)
  end
end
