/* $Id: m3makefile,v 1.2 2009/04/24 07:36:44 mika Exp $ */
import ("libm3")
import ("m3tk")
import ("mscheme")
import ("modula3scheme")
import ("schemereadline")
import ("m3readline")
import ("cit_util")
import ("sstubgen")

implementation("Main")

program ("sstubgen")
