% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Jan 24 08:34:02 PST 1995 by kalsow  
%      modified on Tue Jun 15 21:53:44 PDT 1993 by harrison
%      modified on Tue May  4 10:16:00 PDT 1993 by mjordan


readonly _DateImpls = {
  "CYGWIN"  : "DatePosix",
  "DARWIN"  : "DateBsd",
  "FREEBSD" : "DateBsd",
  "HPUX"    : "DatePosix",
  "INTERIX" : "DatePosix",
  "LINUX"   : "DateBsd",
  "NETBSD"  : "DateBsd",
  "NT"      : "DatePosix",
  "OPENBSD" : "DateBsd",
  "SOLARIS" : "DatePosix",
}

if equal(_DateImpls {TARGET_OS}, "DateBsd") and KernelThreads
  exec("grep -v \" mu \" ../src/time/POSIX/DateBsd.m3 > DateBsd.m3")
  derived_implementation ("DateBsd")
else
  implementation (_DateImpls {TARGET_OS})
end
Module("TimePosix")
