import ("libm3")
%import ("sequences")
import ("listfuncs")
import ("parseparams")
import("netobj")

List      ("EventConn","EventConn")
ListFuncs ("EventConn","EventConn","EventConnList")
Sequence  ("Event","Event")
Pqueue ("Event","EventNumber")

table     ("HostInfo","Fingerprint","HostInfo")
module ("HostInfo")

Module ("EventCounter")
Module ("EventNumber")
Interface ("EventNumberF")

Module ("EventWireRep")
Module ("EventSpaceID")

Module ("EventRd")
Module ("EventWr")
interface ("EventWrF")

Interface ("EventHandle")
Interface ("EventProtocol")
Interface ("EventIO")
Module ("EventStubLib")
Module ("Event")
Module ("EventConn")
Module ("EventPort")

Module ("RdWrMutex")

Interface ("Zombie")
Interface ("Work")
% Interface ("Worker")
sequence  ("Work","Work")
sequence  ("Zombie","Zombie")
Module ("WorkerPool")

Library("events")
