.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" File: m3.1
.\" Last modified on Fri Mar 11 02:25:28 PST 1994 by luca
.nh
.TH obliq-ui 1
.SH Name
Obliq-ui \- a lightweight language for network objects

.SH Syntax
.B obliq-ui
[options]

.SH Description

Obliq linked with user interface libraries. See "obliq".

.SH SRC Documentation

    /src/hypertext/SRC/obliq/Obliq.html    (quick start, for mosaic)

.SH External Site Documentation 
    (in /proj/m3/pkg/..., or equivalent)

    ...obliqdoc/src/Obliq.html/           (quick start, for mosaic)
    ...obliqdoc/src/ObliqPaper.ps         (paper/manual, for printing)
    ...obliqdoc/src/ObliqPaper-html/ObliqPaper.html (same, for mosaic)
    ...obliqdoc/src/Example/*.obl         (example programs)

.SH See Also

    obliq

.SH Author Of Object

  Luca Cardelli

.SH Author Of Documentation

  Luca Cardelli
