/* Copyright (C) 1993, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Tue Dec 21 10:48:16 PST 1993 by detlefs                  */
/*      modified on Wed May  5 20:47:28 PDT 1993 by mjordan                  */

m3_option("-times")

Interface("M3ArgsCL")
Interface("M3Args")
Interface("M3Time")
Interface("M3Assert")
Interface("Err")
Interface("Command")

Interface("TextExtras")
Interface("RdExtras")
Interface("FingerPrint")

implementation("M3Args")
implementation("M3Time")
implementation("M3Assert")
implementation("Command")

implementation("Err")
implementation("TextExtras")

Generic_interface("CITextTable")
Generic_implementation("CITextTable")

Module("CITextRefTbl")
Module("Args")
implementation("RdExtras")
implementation("FingerPrint")

Interface("Csort")
Module("SortText")
Generic_module("Sort")
