% Copyright 1996 Digital Equipment Corporation.
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Fri Apr 12 07:37:49 PDT 1996 by mhb

if HasTrestle()

import ("obliqlibm3")
import ("obliqlibui")
import ("obliqlibanim")
import ("obliqparse")
import ("obliq")

Module          ("ObLibWeb")
implementation  ("Oblet")
% Module          ("ObMetaEval")

end
