% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Mar 23 14:11:50 1994 by luca      
%      modified on Wed Dec 22 15:41:39 PST 1993 by kalsow

import("obliqlibm3")
import("obliqlibui")
import("obliq")
implementation("Main")

Program("obliqsrv-ui")
ManPage("obliqsrv-ui","1")
