import("sharedobj")
import("logitech")

% m3_option("-commands")
build_standalone()

% what the programmer would write
Module (TrackerPosition)
interface (TrackerPositionF)

% a call to
%    sharedobj(TrackerPosition, TrackerPositionF, T) 
% (where we have "interface module, revelation module, type in interface")
% would generate these:
Interface (TrackerPositionProxy)
Module (TrackerPositionCB)
implementation (TrackerPositionSO)

implementation (Echo)

netobj (TrackerPositionProxy, T)
% netobj (TrackerPosition, Public)

program(echotest)
