% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Makefile for netobj test program
% Last modified on Fri Mar 11 13:56:04 PST 1994 by wobber
%      modified on Mon Dec 20 14:14:37 PST 1993 by kalsow

import(libm3)
import(netobj)
import(tcp)

interface(Test)
implementation(LucaTest)
netobj(Test,T)

build_standalone()

program(test)


