/* $Id$ */

/* .top is made by the Makefile before building anything */
TOP = ROOT & "/caltech-parser"

/* when overriding, ld.so doesn't know where to find libraries */
/* this is even more true if we want to move the binaries or */
/* clean.. */

%if defined("pm3_version") 
%      	/* Polytechnique de Montreal Modula-3 */
%	option("shared_lib","")
%else 
%	/* SRC Modula-3 */
%	m3_option ("-X2@-static@")
%end

/* these are the packages that are part of this distribution */

override("prsparse",TOP)
override("magic",TOP)
override("magicextras",TOP)
override("cit_common",TOP)
override("cit_util",TOP)
override("bdd",TOP)
override("cptr",TOP)
override("bool",TOP)
override("boxes",TOP)
override("simplegrid",TOP)
override("router",TOP)
override("term",TOP)
override("m3-3",TOP)
override("paneman",TOP)
override("parserlib",TOP & "/parserlib")
override("ktoklib",TOP & "/parserlib")
override("cit_parse",TOP)
override("drawcontext",TOP)
override("dcpane",TOP & "/drawcontext")
override("tasks",TOP)
override("matrix",TOP)
override("layout",TOP)

% override other libraries if they exist locally

m3core = ROOT & "/m3-libs/m3core"
if not stale(m3core, m3core)
  override("m3core", ROOT & "/m3-libs")
end

libm3 = ROOT & "/m3-libs/libm3"
if not stale(libm3, libm3)
  override("libm3", ROOT & "/m3-libs")
end

m3tk = ROOT & "/m3-tools/m3tk"
if not stale(m3tk, m3tk)
  override("m3tk", ROOT & "/m3-tools")
end

ui = ROOT & "/m3-ui/ui"
if not stale(ui, ui)
  override("ui", ROOT & "/m3-ui")
end

vbtkit = ROOT & "/m3-ui/vbtkit"
if not stale(vbtkit, vbtkit)
  override("vbtkit", ROOT & "/m3-ui")
end

parseparams = ROOT & "/m3-libs/parseparams"
if not stale(parseparams, parseparams)
  override("parseparams", ROOT & "/m3-libs")
end
