import("libm3")

template("polynomial")


Generic_module("Polynomial")

Generic_module("PolynomialFast")
Generic_module("PolynomialBasic")
Polynomial("Real",     "Fast", "RealBasic")
Polynomial("LongReal", "Fast", "LongRealBasic")
Polynomial("Extended", "Fast", "ExtendedBasic")

Polynomial("RealComplex",        "Basic", "RealComplex")
Polynomial("LongRealComplex",    "Basic", "LongRealComplex")
Polynomial("ExtendedComplex",    "Basic", "ExtendedComplex")
Polynomial("Integer32",          "Basic", "Integer32Basic")
Polynomial("BigInteger",         "Basic", "BigInteger")
Polynomial("BigIntegerFraction", "Basic", "BigIntegerFraction")

Generic_module("PolynomialFmtLex")
PolynomialFmtLex("Real",               "RealBasic")
PolynomialFmtLex("LongReal",           "LongRealBasic")
PolynomialFmtLex("Extended",           "ExtendedBasic")
PolynomialFmtLex("LongRealComplex",    "LongRealComplex")
PolynomialFmtLex("Integer32",          "Integer32Basic")
PolynomialFmtLex("BigInteger",         "BigInteger")
PolynomialFmtLex("BigIntegerFraction", "BigIntegerFraction")
