/* Copyright 1993 Digital Equipment Corporation.                             */
/* Distributed only by permission.                                           */
/*                                                                           */
/* Last modified on Thu Sep  8 23:39:46 PDT 1994 by heydon                   */

include( ".." & SL & ".." & SL & ".." & SL & "src" & SL & "defs.quake" )

src = ".." & SL & "src"

import("libm3")
implementation("FromTTY")

program("FromTTY")

if defined("RUN")

  testids = [
    "change",
    "delete",
    "dmin",
    "fromelts",
    "heapgrow"
  ]

  foreach tid in testids
    write( "performing pqueue-" & tid & "...", CR )
    write( getwd(), CR )
    pin = src & SL & tid & ".txt.in"
    pexp = src & SL & tid & ".txt.out"
    pout = "." & SL & tid & ".txt.out"
    r = q_exec( "." & SL & "FromTTY " & pin & " > " & pout )
    ok = cmp_files( tid, pout, pexp )
  end

end
