import("libm3")
import("term")
import("ktoklib")


if not defined("_clean")
	if stale("RegExpLex.m3", "../src/boot/RegExpLex.m3")
		local result = exec(["../src/boot/install"])
	end
end
readonly proc _dmodule(nm) is
	derived_interface(nm, HIDDEN)
	derived_implementation(nm)
end
%these files must be copied from the boot directory
%import("parserlib")
%token("RegExp")
%lexer("RegExp", "RegExp")
%parser("RegExp", "RegExp")
%extended("RegExpLexStd")
%extended("RegExpParseNFA")
_dmodule("RegExpTok")
_dmodule("RegExpLex")
_dmodule("RegExpLexStd")
_dmodule("RegExpParse")
_dmodule("RegExpParseNFA")


Module("NFANode")
Listf("NFANode", "NFANode")
List_sort("NFANode", "NFANode")
Module("NFA")
Table("NFA", "Text", "NFA")

%module("yLex")
%module("yTab")
%c_source("lex.y")

Module("LexParse")

library("klexlib")