% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon May 22 15:46:25 PDT 1995 by kalsow

import ("libm3")
import ("tcp")
import ("m3scan")
import ("m3markup")

module ("OS")
module ("TCPServer")
implementation ("Main")

Program ("m3browser")
ManPage ("m3browser", "1")

