% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Oct 11 14:07:51 PDT 1995 by najork
%      modified on Wed Jan 12 15:55:18 PST 1994 by kalsow
%      modified on Mon May 04 15:16:48 PDT 1992 by muller

if HasTrestle()

import ("libbuf")
import ("vbtkit")

%
% Find a place to put score files...
%
if not defined ("SCOREDIR")
  if equal(OS_TYPE, "POSIX")
    SCOREDIR = "/tmp"
  else
    SCOREDIR = "c:\\temp"
  end
  write (CR, "NOTE: Columns will put its score files in \"",SCOREDIR,"\"", CR)
  write ("To reconfigure Columns, run:  cm3 -DSCOREDIR=/your/path", CR, CR)
end
> "ScoreDir.i0" in
  write ("INTERFACE ScoreDir;", CR)
  write ("CONST Root = \"", escape(SCOREDIR & SL), "\";", CR)
  write ("END ScoreDir.", CR)
end
cp_if ("ScoreDir.i0", "ScoreDir.i3")
derived_interface ("ScoreDir", HIDDEN)

module ("ScoreFile")

module ("Bars")
module ("Columns")
module ("Config")
module ("Rows")
module ("Squares")
module ("Threes")

implementation ("Main")

m3_option ("-gui")
Program ("columns")
ManPage ("columns", 6)

end
