override("libm3",             ROOT & SL & "m3-libs")
override("sysutils",          ROOT & SL & "m3-libs")
override("patternmatching",   ROOT & SL & "m3-libs")
override("fileinfo",          ROOT & SL & "elego")
