% Copyright (C) 1992, Digital Equipment Corporation.
% Distributed only by permission.
%
% Created by Carsten Weich
%
% Last modified on Thu Jan 19 14:28:12 PST 1995 by kalsow 
%      modified on Mon Sep 26 17:44:13 PDT 1994 by weich 
%
% Makefile for stable object stub generator

import("libm3")
import("m3tk")

module("TypeNames")
module("Value")
interface("ValueProc")
module("Type")
module("AstToType")
module("ImportList")
module("GenCode")
module("GenTypeCode")
module("GenModuleCode")
module("StablegenArgs")
module("StablegenError")
module("FRefRefTbl")
implementation("Main")

build_standalone ()
Program("stablegen")

import("mtex")
Mtex("stablegen",1)


