#!/bin/sh -x
echo "// generated macroizations" > ../macroizations
./macroize Calc.t CT
./macroize Calc.l CL
./macroize Calc.y CY
./macroize CalcTokStd.e CTS
./macroize CalcLexStd.e CLS
./macroize CalcParseStd.e CPS
./macroize CalcParseTree.e CPT
./macroize Main.m3 MM
./macroize m3makefile MF
./macroize ../../src/SeekRd.i3 SR
rm itemp
rm itemp2
for file in *.html; do
	cpp -P -imacros html.h <$file >../$file
done
