% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Jul 27 07:40:52 PDT 1994 by kalsow
%      modified on Thu Apr 29 15:44:23 PDT 1993 by muller

Module ("FloatMode")
Module ("FPU")

Interface ("Real")
Interface ("LongReal")
Interface ("Extended")

implementation ("RealFloat")
implementation ("LongFloat")
implementation ("ExtendedFloat")

interface ("RealRep")
interface ("LongRealRep")


