% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

interface      ("RTMachine")
c_source       ("RTStackC")

%needs to be in this order for linking
%not sure if this is correct place for these import_lib
import_lib("lzma","/usr/lib/x86_64-linux-gnu")
import_lib("unwind-x86_64","/usr/lib/x86_64-linux-gnu")
import_lib("unwind","/usr/lib/x86_64-linux-gnu")
import_lib("unwind-generic","/usr/lib/x86_64-linux-gnu")

