import("libm3")

template("vector")


generic_module("Vector")
generic_module("VectorRep")

generic_module("VectorFast")
generic_module("VectorBasic")

Vector("Real",     "Fast", "RealBasic")
Vector("LongReal", "Fast", "LongRealBasic")
Vector("Extended", "Fast", "ExtendedBasic")

Vector("RealComplex",        "Basic", "RealComplex")
Vector("LongRealComplex",    "Basic", "LongRealComplex")
Vector("ExtendedComplex",    "Basic", "ExtendedComplex")
Vector("Integer32",          "Basic", "Integer32Basic")
Vector("BigInteger",         "Basic", "BigInteger")
Vector("BigIntegerFraction", "Basic", "BigIntegerFraction")

generic_module("VectorTrans")
VectorTrans("Real",            "Real")
VectorTrans("LongReal",        "LongReal")
VectorTrans("Extended",        "Extended")
VectorTrans("RealComplex",     "Real")
VectorTrans("LongRealComplex", "LongReal")
VectorTrans("ExtendedComplex", "Extended")

generic_module("VectorFmtLex")
VectorFmtLex("Real")
VectorFmtLex("LongReal")
VectorFmtLex("Extended")
VectorFmtLex("LongRealComplex")
VectorFmtLex("Integer32")
VectorFmtLex("BigInteger")
