import("libm3")

template("vector")


generic_module("VectorBasic")
VectorBasic("Real",               "RealBasic")
VectorBasic("LongReal",           "LongRealBasic")
VectorBasic("Extended",           "ExtendedBasic")
VectorBasic("RealComplex",        "RealComplexBasic")
VectorBasic("LongRealComplex",    "LongRealComplexBasic")
VectorBasic("ExtendedComplex",    "ExtendedComplexBasic")
VectorBasic("Integer32",          "Integer32Basic")
VectorBasic("BigInteger",         "BigIntegerBasic")
VectorBasic("BigIntegerFraction", "BigIntegerFractionBasic")

generic_module("VectorFast")
VectorFast("Real",     "RealBasic")
VectorFast("LongReal", "LongRealBasic")
VectorFast("Extended", "ExtendedBasic")

generic_module("VectorTrans")
VectorTrans("Real",     "RealVectorFast",     "RealBasic",     "RealTrans",     "RealBasic",     "RealTrans")
VectorTrans("LongReal", "LongRealVectorFast", "LongRealBasic", "LongRealTrans", "LongRealBasic", "LongRealTrans")
VectorTrans("Extended", "ExtendedVectorFast", "ExtendedBasic", "ExtendedTrans", "ExtendedBasic", "ExtendedTrans")
VectorTrans("LongRealComplex", "LongRealComplexVectorBasic", "LongRealComplexBasic", "LongRealComplexTrans", "LongRealBasic", "LongRealTrans")

generic_module("VectorFmtLex")
VectorFmtLex("Real",            "RealVectorFast",             "RealFmtLex")
VectorFmtLex("LongReal",        "LongRealVectorFast",         "LongRealFmtLex")
VectorFmtLex("Extended",        "ExtendedVectorFast",         "ExtendedFmtLex")
VectorFmtLex("LongRealComplex", "LongRealComplexVectorBasic", "LongRealComplexFmtLex")
VectorFmtLex("Integer32",       "Integer32VectorBasic",       "Integer32FmtLex")
VectorFmtLex("BigInteger",      "BigIntegerVectorBasic",      "BigIntegerFmtLex")
