import("libm3")

template("vector")


generic_module("VectorFast")
VectorFast("Real",     "RealBasic")
VectorFast("LongReal", "LongRealBasic")
VectorFast("Extended", "ExtendedBasic")

generic_module("VectorBasic")
VectorBasic("RealComplex",        "RealComplexFast")
VectorBasic("LongRealComplex",    "LongRealComplexFast")
VectorBasic("ExtendedComplex",    "ExtendedComplexFast")
VectorBasic("Integer32",          "Integer32Basic")
VectorBasic("BigInteger",         "BigIntegerBasic")
VectorBasic("BigIntegerFraction", "BigIntegerFractionBasic")

generic_module("VectorTrans")
VectorTrans("Real",            "Fast",  "Real",     "",        "Basic")
VectorTrans("LongReal",        "Fast",  "LongReal", "",        "Basic")
VectorTrans("Extended",        "Fast",  "Extended", "",        "Basic")
VectorTrans("LongRealComplex", "Basic", "LongReal", "Complex", "Fast")

generic_module("VectorFmtLex")
VectorFmtLex("Real",            "Fast")
VectorFmtLex("LongReal",        "Fast")
VectorFmtLex("Extended",        "Fast")
VectorFmtLex("LongRealComplex", "Basic")
VectorFmtLex("Integer32",       "Basic")
VectorFmtLex("BigInteger",      "Basic")
