% Copyright (C) 1998, Compaq Computer Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Fri Dec 11 15:41:20 PST 1998 by heydon  

implementation ("UDPPosix")
