
include(".." & SL & ".." & SL & "quake.elego")

import("libm3")
import("parseparams")
import("vbtkit")

import("patternmatching")
import("sysutils")
import("graphicutils")
import("compact-copyright")

resource("m3msh.help")
resource("m3msh.desc")
bundle("MiniShellBundle")

implementation("M3MiniShell")
creation_date_module("Creation")

Program("m3msh")
