% compiled / works with with CM3 5.2.6 2003-06-27
import_lib("fftw3","/usr/lib")
import_lib("fftw3f","/usr/lib")
import("libm3")

module("LongRealFFTWRaw")
module("LongRealFFTW")
module("RealFFTWRaw")
module("RealFFTW")
% no library available under ix86-Linux
%module("ExtendedFFTWRaw")
%module("ExtendedFFTW")

library("m3fftw")
