% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Mar  2 08:30:57 PST 1994 by kalsow

write(CR, "--- tests in ", getwd(), "---", CR)

%override (sqrt, "../../..")
import ("libm3")

build_standalone ()
implementation ("SqrtTst")
program ("SqrtTst")

if defined("RUN")
  r = q_exec( "." & SL & "SqrtTst" )
  write( CR, "program returned ", r, CR )
end
