% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Mar 23 14:09:46 1994 by luca      
%      modified on Wed Dec 22 15:19:46 PST 1993 by kalsow

import("obliq")
implementation("Main")

Program("obliq-min")
ManPage("obliq-min",1)
