.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" File: m3.1
.nh
.TH repo-min 1
.SH Name
Repo-min \- a lightweight language for network objects

.SH Syntax
.B repo-min
[options]

.SH Description

Repo linked with minimum libraries. See "repo".

.SH Columbia Documentation

    /u/stieglitz/bm/projects/papers/ObliqStar/Repo.ps

.SH External Site Documentation 
    (in ftp.cs.columbia.edu:/pub/bm)

    ...repodoc/Repo.ps         (paper/manual, for printing)

.SH See Also

    repo

.SH Author Of Object

  Luca Cardelli
  Blair MacIntyre

.SH Author Of Documentation

  Luca Cardelli
  Blair MacIntyre
