/* Copyright © 1993, Digital Equipment Corporation                        */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Wed Dec 22 17:04:13 PST 1993 by mhb                      */
/*      modified on Thu Mar 25 14:56:02 PST 1993 by meehan                   */


resource   ("formseditvbt.fv")
resource   ("confirm.fv")
resource   ("finder.fv")
resource   ("yesno.fv")

resource   ("formsedit.txt")

resource   ("digitalLogo.pbm")
resource   ("bnote.pbm")
resource   ("pen.pbm")
