% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Nov  1 09:02:32 PST 1994 by kalsow 

include( ".." & SL & ".." & SL & ".." & SL & "src" & SL & "defs.quake" )

src = ".." & SL & "src"
inp = src & SL & "AutoTest.m3"

import("libm3")
implementation("AutoTest")
program("AutoTest")

if defined("RUN")

  tid = "rw-autotest"
  write( CR, "performing " & tid & "...", CR )
  r = q_exec( "." & SL & "AutoTest 10 1000 0.001 0.002 < " & inp )
  write( CR, "program returned ", r, CR )

end
