% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Nov  1 09:02:32 PST 1994 by kalsow 

include( ".." & SL & ".." & SL & ".." & SL & "src" & SL & "defs.quake" )

src = ".." & SL & "src"
inp = src & SL & "AutoTest.m3"

import("libm3")
implementation("AutoTest")
program("AutoTest")

if defined("RUN")

  tid = "rw-autotest"
  write( CR, "performing " & tid & "...", CR )
  r = q_exec( "." & SL & "AutoTest 10 1000 0.001 0.002 2> stderr < " & inp )
  write( CR, "program returned ", r, CR )
  rad = q_exec_get( "grep -v 'Bytes written:' stderr" )
  if not equal(rad[0], 0)
    write( CR, "grep returned ", rad[0], CR )
  end
  if not equal(rad[1], "")
    write( CR, "FAILED", CR, "stderr: ", rad[1], CR )
  end
end
