% Copyright (C) 1995, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Apr 13 13:42:52 PDT 1995 by kalsow

interface ("NetObjEpoch")
