% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Thu Jun 17 19:22:06 PDT 1993 by harrison
%      modified on Tue May  4 10:24:11 PDT 1993 by mjordan

include_dir("Common")

if equal (OS_TYPE, "WIN32") or equal (TARGET_OS, "CYGWIN")
  include_dir ("WIN32")
else
  include_dir (OS_TYPE) % Win32 or Posix
end
