#!/bin/tcsh
setenv PROVER_KILL_TIME 500
setenv SIMPLIFY $ESCTOOLS_ROOT/Simplify/simplify/$OUTPUTDIR/Simplify
setenv NICE /usr/bin/nice
# setenv PROVER_STATS
echo Running Simplify performance tests using $SIMPLIFY
echo Running Simplify performance tests using the following switches: $*
echo The machine is:  ${HOST}
printenv | egrep "AXIOM|PROVER" | xargs echo Environment variables:
date
foreach f (`cat m3tests`)
  echo $f
  time $NICE -n10 $SIMPLIFY -noprune -ax esc $* $f
end
foreach f (`cat tests`)
  echo $f
  time $NICE -n10 $SIMPLIFY -noprune $* $f
end
date
