% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Jan 24 08:32:45 PST 1995 by kalsow 
%      modified on Fri Apr 30 11:31:44 PDT 1993 by mjordan

readonly HAS_STACK_WALKER = {
  "ALPHA_OSF"  : TRUE,
  "DS3100"     : TRUE,
  "SOLgnu"     : TRUE,
  "SOLsun"     : TRUE,
}

include_dir ("common")
include_dir (OS_TYPE)

if equal (TARGET, "SPARC64_OPENBSD") or equal (TARGET, "PPC32_OPENBSD")
    or equal (TARGET, "MIPS64_OPENBSD") or equal (TARGET, "I386_OPENBSD")
    or equal (TARGET, "MIPS32_IRIX") or equal (TARGET, "MIPS64_IRIX")
    or equal (TARGET, "SPARC32_LINUX") or equal (TARGET, "SPARC64_LINUX")
    or equal (TARGET, "PPC_LINUX") or equal (TARGET, "AMD64_LINUX")
    or equal (TARGET, "AMD64_FREEBSD")

  % nothing

else
  include_dir (TARGET)
end

if defined("M3_USE_STACK_WALKER")
  if M3_USE_STACK_WALKER and HAS_STACK_WALKER contains TARGET
    if HAS_STACK_WALKER{TARGET}
      include_dir("ex_stack")
    else
      include_dir("ex_frame")
    end
  else
    include_dir("ex_frame")
  end
else
  include_dir("ex_frame")
end
