cd ..\m3-libs\m3core
cm3 -build
cm3 -ship
cd ..\..\m3-libs\libm3
cm3 -build
cm3 -ship
cd ..\..\m3-sys\m3middle
cm3 -build
cm3 -ship
cd ..\..\m3-sys\m3quake
cm3 -build
cm3 -ship
cd ..\..\m3-sys\m3scanner
cm3 -build
cm3 -ship
cd ..\..\m3-sys\m3tools
cm3 -build
cm3 -ship
cd ..\..\m3-sys\m3cgcat
cm3 -build
cm3 -ship
cd ..\..\m3-sys\m3cggen
cm3 -build
cm3 -ship
cd ..\..\m3-tools\m3bundle
cm3 -build
cm3 -ship
cd ..\..\m3-sys\mklib
cm3 -build
cm3 -ship
cd ..\..\m3-sys\dll2lib
cm3 -build
cm3 -ship
cd ..\..\m3-sys\fix_nl
cm3 -build
cm3 -ship
cd ..\..\m3-sys\libdump
cm3 -build
cm3 -ship
cd ..\..\m3-libs\bitvector
cm3 -build
cm3 -ship
cd ..\..\m3-libs\digraph
cm3 -build
cm3 -ship
cd ..\..\m3-libs\parseparams
cm3 -build
cm3 -ship
cd ..\..\m3-libs\realgeometry
cm3 -build
cm3 -ship
cd ..\..\m3-libs\set
cm3 -build
cm3 -ship
cd ..\..\m3-libs\slisp
cm3 -build
cm3 -ship
cd ..\..\m3-libs\sortedtableextras
cm3 -build
cm3 -ship
cd ..\..\m3-libs\table-list
cm3 -build
cm3 -ship
cd ..\..\m3-libs\tempfiles
cm3 -build
cm3 -ship
cd ..\..\m3-comm\tcp
cm3 -build
cm3 -ship
cd ..\..\m3-libs\debug
cm3 -build
cm3 -ship
cd ..\..\m3-libs\listfuncs
cm3 -build
cm3 -ship
cd ..\..\m3-libs\patternmatching
cm3 -build
cm3 -ship
cd ..\..\m3-libs\embutils
cm3 -build
cm3 -ship
cd ..\..\m3-libs\m3tk-misc
cm3 -build
cm3 -ship
cd ..\..\m3-www\http
cm3 -build
cm3 -ship
cd ..\..\m3-libs\binIO
cm3 -build
cm3 -ship
cd ..\..\m3-comm\tapi
cm3 -build
cm3 -ship
cd ..\..\m3-comm\serial
cm3 -build
cm3 -ship
cd ..\..\m3-tools\m3tk
cm3 -build
cm3 -ship
cd ..\..\m3-tools\mtex
cm3 -build
cm3 -ship
cd ..\..\m3-tools\m3totex
cm3 -build
cm3 -ship
cd ..\..\m3-tools\m3tohtml
cm3 -build
cm3 -ship
cd ..\..\m3-tools\cmpdir
cm3 -build
cm3 -ship
cd ..\..\m3-tools\cmpfp
cm3 -build
cm3 -ship
cd ..\..\m3-tools\dirfp
cm3 -build
cm3 -ship
cd ..\..\m3-tools\uniq
cm3 -build
cm3 -ship
cd ..\..\m3-comm\netobj
cm3 -build
cm3 -ship
cd ..\..\m3-comm\netobjd
cm3 -build
cm3 -ship
cd ..\..\m3-comm\stubgen
cm3 -build
cm3 -ship
cd ..\..\m3-comm\events
cm3 -build
cm3 -ship
cd ..\..\m3-comm\rdwr
cm3 -build
cm3 -ship
cd ..\..\m3-comm\sharedobj
cm3 -build
cm3 -ship
cd ..\..\m3-comm\sharedobjgen
cm3 -build
cm3 -ship
cd ..\..\m3-db\odbc
cm3 -build
cm3 -ship
cd ..\..\m3-db\postgres95
cm3 -build
cm3 -ship
cd ..\..\m3-db\db
cm3 -build
cm3 -ship
cd ..\..\m3-db\smalldb
cm3 -build
cm3 -ship
cd ..\..\m3-db\stable
cm3 -build
cm3 -ship
cd ..\..\m3-db\stablegen
cm3 -build
cm3 -ship
cd ..\..\m3-ui\ui
cm3 -build
cm3 -ship
cd ..\..\m3-ui\PEX
cm3 -build
cm3 -ship
cd ..\..\m3-ui\vbtkit
cm3 -build
cm3 -ship
cd ..\..\m3-ui\cmvbt
cm3 -build
cm3 -ship
cd ..\..\m3-ui\jvideo
cm3 -build
cm3 -ship
cd ..\..\m3-ui\videovbt
cm3 -build
cm3 -ship
cd ..\..\m3-www\web
cm3 -build
cm3 -ship
cd ..\..\m3-ui\formsvbtpixmaps
cm3 -build
cm3 -ship
cd ..\..\m3-ui\formsvbt
cm3 -build
cm3 -ship
cd ..\..\m3-ui\formsview
cm3 -build
cm3 -ship
cd ..\..\m3-ui\formsedit
cm3 -build
cm3 -ship
cd ..\..\m3-ui\codeview
cm3 -build
cm3 -ship
cd ..\..\m3-ui\mg
cm3 -build
cm3 -ship
cd ..\..\m3-ui\mgkit
cm3 -build
cm3 -ship
cd ..\..\m3-ui\opengl
cm3 -build
cm3 -ship
cd ..\..\m3-ui\anim3D
cm3 -build
cm3 -ship
cd ..\..\m3-ui\zeus
cm3 -build
cm3 -ship
cd ..\..\m3-ui\m3zume
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\synloc
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\synex
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\metasyn
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliqrt
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliqparse
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliqprint
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliq
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliqlibemb
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliqlibm3
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliqlibui
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliqlibanim
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliqsrvstd
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliqsrvui
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliqbinmin
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliqbinstd
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliqbinui
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\obliqbinanim
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\visualobliq
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\vocgi
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\voquery
cm3 -build
cm3 -ship
cd ..\..\m3-obliq\vorun
cm3 -build
cm3 -ship
cd ..\..\m3-ui\webvbt
cm3 -build
cm3 -ship
cd ..\..\m3-tools\recordheap
cm3 -build
cm3 -ship
cd ..\..\m3-tools\rehearsecode
cm3 -build
cm3 -ship
cd ..\..\m3-tools\replayheap
cm3 -build
cm3 -ship
cd ..\..\m3-tools\showheap
cm3 -build
cm3 -ship
cd ..\..\m3-tools\shownew
cm3 -build
cm3 -ship
cd ..\..\m3-demo\cube
cm3 -build
cm3 -ship
cd ..\..\m3-demo\calculator
cm3 -build
cm3 -ship
cd ..\..\m3-demo\fisheye
cm3 -build
cm3 -ship
cd ..\..\scripts
