/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Thu Apr 21 16:07:33 PDT 1994 by heydon                   */

/* m3makefile for /proj/m3/pkg/juno-compiler/tests/ScopeTest/src */

implementation(ScopeTest)

import(juno-machine)
import(juno-compiler)
import(libm3)

build_standalone()
program(ScopeTest)
