/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Sun Aug 15 22:49:06 PDT 1993 by heydon                   */

/* m3overrides for /proj/m3/pkg/juno-compiler/tests/scope/src */

override(juno-machine,  WDROOT)
override(juno-compiler, WDROOT)
