#! /bin/csh -f
#
# Copyright (C) 1992, Digital Equipment Corporation 
# All rights reserved.
# See the file COPYRIGHT for a full description.
#
# Last modified on Thu Apr 21 17:12:42 PDT 1994 by heydon
#      modified on Fri Feb 25 13:52:13 PST 1994 by kalsow

set arch = `/udir/heydon/libi/csh/m3arch`
set prog = ScopeTest

if (-e ../$arch/$prog) then
  set newoutfile = /tmp/scopetest-$$.txt.out
  foreach outfile ($*)
    ../$arch/$prog > $newoutfile
    echo "diff $outfile $newoutfile"
    diff $outfile $newoutfile
    rm $newoutfile
  end
else
  echo "Unknown host type \"$arch\""
endif
