import ("obliq")
import ("embutils")

/* some convenience modules for use in our obliq packages */
Module ("ObBool")
Module ("ObInt")
Module ("ObReal")
Module ("ObLongReal")
Module ("ObText")
Module ("ObError")
Module ("ObLoader")

% useful to folks implementing custom shared objects using ProxiedObjs
Module ("ObSharedObj")
resource ("SharedObj.hlp")
resource ("SharedObj.obl")

/* help for embedding m3 in obliq */
Module ("ObEmbProxiedObj")
resource ("EmbProxiedObj.hlp")
resource ("EmbProxiedObj.obl")

/*
interface ("LibEmbDirs")
if equal (OS_TYPE, "WIN32")
	implementation ("LibEmbDirsWin32")
else
	implementation ("LibEmbDirsPosix")
end
*/

bundle ("ObEmbBundle")

Module ("ObLibEmb")

Library ("obliqlibemb")
