% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Makefile for tcp library (generic)
% Last modified on Thu Feb  9 19:03:54 PST 1995 by wobber
%      modified on Thu Aug 18 14:16:47 PDT 1994 by kalsow
% $Id: m3makefile,v 1.1.1.1 2009-04-09 17:02:03 jkrell Exp $

include(path() & "/../../quake/cvsup.quake")

no_shared_lib()

import("libm3")
import("tcp")

include_dir(OS_TYPE)

include_dir("common")

library("suptcp")
