% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Sep 14 16:41:21 PDT 1994 by kalsow

Module ("CoffTime")
implementation ("M3Process")


