
import("lapack")

template("waveletmatch")

Generic_module("WaveletMatch")
Generic_module("WaveletMatchSmooth")
Generic_module("WaveletMatchGradientLift")
Generic_module("WaveletMatchGradient")
Generic_module("WaveletMatchBasis")

%WaveletMatch("Real",            "RealBasic")
WaveletMatch("LongReal",        "LongRealBasic")
