import("binIO")
import("commandrw")
import("plplot")

module("ProcessInOut")

module("ProcessPipeIn")
Module("ProcessLoad")

module("ProcessPipeOut")
Module("ProcessSave")
Module("ProcessPlot")

Interface("ProcessPlay")
implementation("ProcessPlay")
%implementation("ProcessPlaySolaris")
