
import("libm3")
import("m3quake")
import("vbtkit")

import("patternmatching")
import("tuple")
import("sysutils")
import("langutils")
import("compact-client")

Table("TextTextTupleSeq", "Text", "TextTupleSeq")
Interface("CompactEnvName")
Module("CompactRC")
Module("MiniEnv")

Library("compactrc")

