% Copyright (C) 1992, Xerox
% All rights reserved.
%
% Last modified on Fri Jun 24 07:37:20 PDT 1994 by kalsow
%      modified on Wed Mar  4 19:13:02 PST 1992 by muller

c_source ("dtoa")
h_source ("float")
c_source ("memmove")
c_source ("waitpid")

