/* Copyright (C) 1996, Digital Equipment Corporation                         */
/* Digital Internal Use Only                                                 */
/* All rights reserved.                                                      */
/*                                                                           */
/* Last modified on Fri Oct 18 13:32:58 PDT 1996 by najork                   */
/*       Created on Tue Oct 15 13:38:07 PDT 1996 by najork                   */

import ("formsvbt")

resource ("form.fv")
bundle ("MyBundle")

implementation ("Main")
Program ("TextureComTest")
