if equal (OS_TYPE, "POSIX")

import("libm3")
h_source("termios")
if equal (TARGET, "SOLgnu") or equal(TARGET, "SOLsun")
  c_source("cfmakeraw")
end
interface("Termios")
Module("Term")
Module("TermIO")
Library("term")

end
