
%%XXDIR = { "WIN32" : "N:\\m3-tools", "POSIX" : "/proj/cmass/src.2/m3-tools" }
%%WORKDIR = XXDIR {OS_TYPE}

%override ("libm3", ROOT & "/m3-libs")
%override ("m3tk", ROOT & "/m3-tools")
/* $Id: m3overrides,v 1.1 2010/11/05 21:59:10 mika Exp $ */
include("../../../../m3overrides")
