% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Mar 21 23:13:11 PST 1994 by luca  
%      modified on Wed Dec 22 15:07:31 PST 1993 by kalsow

import("synloc")
import("obliqrt")

Module ("ObPrintTree")
Module ("ObPrintValue")
Module ("ObliqPrinter")

Library("obliqprint")

/* ManPage(obliqprint,?) */

