% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Aug  3 10:14:34 PDT 1993 by kalsow  
%      modified on Thu Jun 17 19:17:06 PDT 1993 by harrison
%      modified on Wed Mar 10 16:34:40 PST 1993 by mjordan
%      modified on Tue Feb 11 15:07:32 PST 1992 by muller

Interface ("Thread")
Interface ("ThreadF")
Interface ("Scheduler")
if equal (OS_TYPE, "POSIX")
    Interface ("SchedulerPosix")
    interface("ThreadInternal")
    c_source("ThreadInternal")
end
if not equal (OS_TYPE, "POSIX") or equal (TARGET_OS, "CYGWIN")
    interface ("ThreadDebug")
    c_source("ThreadDebug")
end
Interface ("MutexRep")
Interface ("ThreadEvent")
