% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon May  2 16:14:31 PDT 1994 by kalsow 
%      modified on Thu Sep  2 15:08:45 PDT 1993 by mcjones
%      modified on Fri May  7 14:59:36 PDT 1993 by muller

% temporarily disable Grisu for Win32 and C backend until problems investigated
% NT386 fails to compile, C fails at runtime
if equal (OS_TYPE, "WIN32") or equal (M3_BACKEND_MODE, "C")
  include_dir("no_grisu")
else
  include_dir("grisu")
end

Interface ("FPU")

Generic_interface ("Float")

Interface ("RealFloat")
Interface ("LongFloat")
Interface ("ExtendedFloat")
Module ("IEEESpecial")

implementation ("Real")
implementation ("LongReal")
implementation ("Extended")

module ("DragonInt")
module ("DragonT")
module ("FloatUtils")
module ("TextToFloat")

% FloatMode.i3.template is not compilable.  Its purpose is to appear
% in the "Some Useful Modula-3 Interfaces" manual.  It should be
% identical to the versions in the other subdirectories except for the
% values of the constants IEEE and RoundDefault. -- Paul McJones
% 8/31/91
