
template("discretewavelettransform")


generic_module("DiscreteWaveletTransform")
generic_module("DyadicDiscreteWaveletTransform")

%DiscreteWaveletTransform("Real",            "RealBasic")
DiscreteWaveletTransform("LongReal",        "LongRealBasic")
%DiscreteWaveletTransform("Extended",        "ExtendedBasic")
%DiscreteWaveletTransform("RealComplex",     "RealComplex")
DiscreteWaveletTransform("LongRealComplex", "LongRealComplex")
%DiscreteWaveletTransform("ExtendedComplex", "ExtendedComplex")

Sequence("RealScaledSignal",     "RealScaledSignal")
Sequence("LongRealScaledSignal", "LongRealScaledSignal")
Sequence("ExtendedScaledSignal", "ExtendedScaledSignal")

Module("LongRealDWTPlot")
