
template("discretewavelettransform")


generic_module("DiscreteWaveletTransform")
%DiscreteWaveletTransform("Real",            "RealBasic")
DiscreteWaveletTransform("LongReal",        "LongRealBasic")
%DiscreteWaveletTransform("Extended",        "ExtendedBasic")
%DiscreteWaveletTransform("RealComplex",     "RealComplex")
DiscreteWaveletTransform("LongRealComplex", "LongRealComplex")
%DiscreteWaveletTransform("ExtendedComplex", "ExtendedComplex")
