/* Copyright (C) 1993, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Wed May  5 20:57:48 PDT 1993 by mjordan                  */

Interface("M3CFETool")
Interface("M3CGo")
Interface("M3CGoList")
Interface("WiredStandard")
Interface("StandardAsText")

implementation("M3CFETool")
implementation("M3CGo")
implementation("M3CGoList")
implementation("WiredStandard")
implementation("StandardAsText")

