% Copyright (C) 1996, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu May 16 16:27:02 PDT 1996 by mcjones

implementation("OSUtilsWin32")

