% Copyright 1996-2003 John D. Polstra.
% All rights reserved.
%
% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions
% are met:
% 1. Redistributions of source code must retain the above copyright
%    notice, this list of conditions and the following disclaimer.
% 2. Redistributions in binary form must reproduce the above copyright
%    notice, this list of conditions and the following disclaimer in the
%    documentation and/or other materials provided with the distribution.
% 3. All advertising materials mentioning features or use of this software
%    must display the following acknowledgment:
%      This product includes software developed by John D. Polstra.
% 4. The name of the author may not be used to endorse or promote products
%    derived from this software without specific prior written permission.
%
% THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
% IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
% OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
% IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
% INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
% NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
% DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
% THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
% (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
% THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
%
% $Id: m3makefile,v 1.2 2009-04-12 07:21:13 jkrell Exp $

include(path() & "/../../quake/cvsup.quake")

if defined("STATIC")
  build_standalone()
end

override("suplib", path() & "/../..")

import("libm3")
import("tempfiles")
import("suplib")
import("tcp")

interface("Version")
version_impl("Version")

generic_module("SyncQueue")
template("syncqueue")

interface("Fixup")
sequence("Fixup", "Fixup")
sync_queue("Fixup", "Fixup")

sequence("SupFileRec", "SupFileRec")
sequence("FileAttr", "FileAttr")

module("Auth")
module("SupFile")
module("Receive")

module("FileUpdater")
module("CheckoutCreator")
module("CheckoutUpdater")
module("RCSUpdater")
module("RegularCreator")
module("RegularUpdater")
module("RsyncUpdater")

module("TreeList")
module("Detailer")
module("Updater")
module("FSClient")

% Not yet ...
%
% module("SigAlert")

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% The GUI support is isolated right here ...
interface("SupGUI")

if defined("NOGUI")
  implementation("SupGUIFake")
else
  import("formsvbt")
  resource("Copyright.txt")
  resource("SupGUI.fv")
  resource("disk.pbm")
  resource("exit.pbm")
  resource("info.pbm")
  resource("stop.pbm")
  resource("tape_play.pbm")
  bundle("SupGUIBundle")
  module("EventSync")
  module("TextPortLogger")
  module("TextVBTLogger")
  implementation("SupGUI")
end
% End of GUI support
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

module("BackoffTimer")
implementation("Main")

program("cvsup")
ManPage("cvsup","1")
