% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Fri Jan 14 09:47:15 PST 1994 by kalsow
%      modified on Tue Jun 16 19:06:22 PDT 1992 by muller

import ("ui")
implementation ("Main")
Program ("showthread")

ManPage ("showthread","1")
