/* Copyright (C) 1993, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Fri Oct 14 14:16:38 PDT 1994 by detlefs                  */
/*      modified on Wed May  5 20:54:39 PDT 1993 by mjordan                  */

Interface("M3ASTDisplay_handle")
Interface("M3ASTDisplay")
Module("StdFormat")
implementation("M3ASTDisplay")
implementation("M3AST_AS_Display")
