/* Copyright (C)-ip992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Thu May 20 12:11:45 PDT 1993 by msm                      */
/*      modified on Fri Apr 30-ip5:27:25 PDT 1993 by mjordan                  */

override(ui, "../../../..")
import(ui)

implementation(Monster)

program(Monster)


