% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Makefile for pkgtool libraries - POSIX specific
%
% Last modified on Wed Jan 25 10:08:51 PST 1995 by kalsow
%      modified on Mon Apr  4 10:56:24 PDT 1994 by wobber

readonly _osf_like_systems = {
  "ALPHA_OSF", "SPARC", "SOLsun", "SOLgnu", "HPPA", "LINUX", "LINUXELF"
}

if _osf_like_systems contains TARGET
   include_dir("osf")
else
   include_dir("ultrix")
end

implementation ("OpSysPosix")
implementation ("FileSysPosix")



