implementation("Uin")

if equal (TARGET, "MIPS64_OPENBSD") or equal (TARGET, "I386_OPENBSD")
        or equal (TARGET, "PPC32_OPENBSD") or equal (TARGET, "SPARC64_OPENBSD")
        or equal (TARGET, "AMD64_LINUX") or equal (TARGET, "PPC_LINUX")
        or equal (TARGET, "SPARC32_LINUX") or equal (TARGET, "SPARC64_LINUX")
        or equal (TARGET, "NT386") or equal (TARGET, "AMD64_FREEBSD")

    Interface ("Uexec")

end
