import("libm3")

template("gcd")
template("integerpower")
template("combinatoric")


generic_module("IntegerPower")
IntegerPower("Integer32",            "Integer32",            "Basic")
IntegerPower("Cardinal32",           "Cardinal32",           "Basic")
IntegerPower("BigInteger",           "BigInteger",           "Basic")
IntegerPower("BigIntegerComplex",    "BigIntegerComplex",    "Basic")
IntegerPower("BigIntegerPolynomial", "BigIntegerPolynomial", "Basic")
IntegerPower("BigIntegerMatrix",     "BigIntegerMatrix",     "Basic")
IntegerPower("LongReal",             "LongReal",             "Basic")
IntegerPower("LongRealComplex",      "LongRealComplex",      "Fast")
IntegerPower("LongRealPolynomial",   "LongRealPolynomial",   "Fast")
IntegerPower("LongRealMatrix",       "LongRealMatrix",       "Fast")

generic_module("GCD")
GCD("Cardinal32",                   "Cardinal32",                   "Basic")
GCD("Integer32",                    "Integer32",                    "Basic")
GCD("Integer32Complex",             "Integer32Complex",             "Basic")
GCD("BigInteger",                   "BigInteger",                   "Basic")
GCD("BigIntegerComplex",            "BigIntegerComplex",            "Basic")
GCD("BigIntegerFractionPolynomial", "BigIntegerFractionPolynomial", "Basic")
% GCD will not work with floating point numbers,
% because values that should be zero, aren't zero most often

generic_module("Combinatoric")
Combinatoric("Cardinal32",          "Cardinal32", "Basic")
Combinatoric("BigInteger",          "BigInteger", "Basic")


module("NumberTheory")
implementation("PrimeNumber")
