% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Nov  1 08:59:57 PST 1994 by kalsow

%
% This hangs on OpenBSD/x86, needs further investigation.
%
if not equal(TARGET, "I386_OPENBSD")

write(CR, "--- tests in ", getwd(), "---", CR)

import("libm3")
implementation("RandomTest")
build_standalone()
program("RandomTest")

if defined("RUN")
  r = q_exec( "." & SL & "RandomTest -all > out" )
  write( CR, "program returned ", r, CR )
end

end
