
override("prjbase", "../../..")

import("libm3")
import("sysutils")
import("pkg_base")
import("prjbase")
import("compactrc")
import("miniscan")

implementation("Main")

build_standalone()
program("Test") 
