% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue May  2 11:37:20 PDT 1995 by kalsow

implementation ("RTExFrame")
c_source ("RTStackC")

/* this seems garbled - the whole mechanism to compile the stack walker
   is messy.
if HAS_STACK_WALKER contains TARGET
  if not HAS_STACK_WALKER{TARGET}
    c_source ("RTStackC")
  end
else
  c_source ("RTStackC")
end
*/
