% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue May  2 11:37:20 PDT 1995 by kalsow

implementation ("RTException")
interface ("RTExRep")
c_source ("RTStackC")

