if equal(TARGET,"AMD64_LINUX")
build_standalone() % dont attempt to build shared libs from asm
import ("libm3")
import ("cit_util")
import ("matrix")
import ("minimize")

%s_source ("bigden")
%s_source ("biglag")
%s_source ("calfun")
%%s_source ("main")
%s_source ("newuoa")
%s_source ("newuob")
%s_source ("trsapp")
%s_source ("update")

c_source ("bigden")
c_source ("biglag")
c_source ("calfun")
c_source ("newuoa")
c_source ("newuob")
c_source ("trsapp")
c_source ("update")

interface ("NewUOA")

Generic_module("LRScalarPll")
template ("lrscalar")

LrScalarPll("LRScalarFieldPll", "LRScalarField", "LRVectorLRTbl")
LrScalarPll("LRVectorFieldPll", "LRVectorField", "LRVectorVectorTbl")

Table("LRVectorVector", "LRVector", "LRVector")
Table("LRVectorRef", "LRVector", "Refany")
MkSet("LRVector", "LRVector")
MkSetDef("LRVector", "LRVector")

%Module ("LRScalarFieldPll")

Module ("NewUOA_M3")
Module ("NewUOAs")

%implementation("Main")
%program ("testnewuoa")
library ("newuoa")
end
