/* Copyright (C) 1993, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */

/* Last modified on Tue Jan 16 13:04:17 PST 1996 by heydon   */
/*      modified on Tue Sep 19 13:22:35 PDT 1995 by glassman */
/*      modified on Thu Feb  2 09:16:01 PST 1995 by kalsow  */
/*      modified on Wed Oct  5 21:43:51 PDT 1994 by mhb     */
/*      modified on Thu Jul  7 11:39:38 PDT 1994 by bharat  */
/*      modified on Tue Jun 16 18:26:52 PDT 1992 by muller  */

import ("formsvbt")
import ("obliqlibm3")
import ("obliqlibui")
import ("obliq")

include_dir ("../src/UI")
include_dir ("../src/OBLIQ")
include_dir ("../src/TEMPLATES")

bundle ("DialogBundle")

module ("KnobsVBT")
module ("ZHandleVBT")
module ("NodeVBT")
module ("Attributes")
module ("Browser")
module ("Clickable")
module ("Textual")
module ("Setting")
module ("VideoWidget")
module ("RW")
module ("GenerateObliq")
module ("DialogMenu")
module ("Dialog")
module ("ObliqRuntime")

Program	("visobliq")
ManPage ("visobliq", 1)

/*---------------------------------------------------
Here's what to do about the documentation:

There are two pieces to consider: the man page (in mtex)
and the doc (in html).

For the doc. the package to mimic is "obliqdoc".
There, the m3makefile has two calls to HtmlExport,
for the internal and external webs. The rest is 
known technology (for me): add a link from the
SRC home page, cite the URL from the project 
description page in src.opplan, the man page, and so on.

For the man page, the package to mimic is "juno-app".
There, the m3makefile has a call to MTex which exports
the man page written in mtex to all of the right
places in all of the various formats.

When this gets done, then add the appropriate hotlinks
to the visual obliq project plan in 

  /proj/cra/pkg/src.opplan/archive/visualobliq.html

---------------------------------------------------*/

