import("libm3")

template("complex")


generic_module("ComplexBasic")

generic_module("ComplexFast")
Complex("Real",       "Fast",  "RealBasic")
Complex("LongReal",   "Fast",  "LongRealBasic")
Complex("Extended",   "Fast",  "ExtendedBasic")
Complex("Integer32",  "Basic", "Integer32Basic")
Complex("BigInteger", "Basic", "BigInteger")


generic_module("ComplexTrans")
ComplexTrans("Real",     "RealBasic")
ComplexTrans("LongReal", "LongRealBasic")
ComplexTrans("Extended", "ExtendedBasic")

generic_module("ComplexFmtLex")
ComplexFmtLex("Real",	    "RealBasic")
ComplexFmtLex("LongReal",   "LongRealBasic")
ComplexFmtLex("Extended",   "ExtendedBasic")
ComplexFmtLex("Integer32",  "Integer32Basic")
ComplexFmtLex("BigInteger", "BigInteger")
