% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Jan 17 16:01:03 PST 1995 by kalsow 
%      modified on Fri Nov  5 16:41:57 PST 1993 by detlefs
%      modified on Mon Jan 18 19:09:20 PST 1993 by muller

%
%  To rebuild the parser or lexer tables, cd to this
%  directory and run the standard make.
%

%% c_source ("lex.yy.c")  -- it's really a .h file
c_source ("y.tab")
import_sys_lib ("FLEX-BISON")

