% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Nov  1 09:07:44 PST 1994 by kalsow 
%      modified on Tue Apr 27 08:58:59 PDT 1993 by mcjones

implementation("WrWin32")


