% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Fri Feb  4 09:47:38 PST 2000 by heydon

% m3overrides for /proj/m3/pkg/juno-app/src

% override ("vbtkit", WDROOT)
% override ("formsvbt", WDROOT)
override ("juno-machine",  WDROOT)
override ("juno-compiler", WDROOT)
