import("libm3")

template("functional")


Generic_module("Functional")
Functional("Real",     "Real",     "Basic", "Decomposition")
Functional("LongReal", "LongReal", "Basic", "Decomposition")
%Functional("Extended", "Extended", "Basic", "Decomposition")

Generic_module("FunctionalDeriv2")
FunctionalDeriv2("Real",     "Real",     "Basic")
FunctionalDeriv2("LongReal", "LongReal", "Basic")
FunctionalDeriv2("Extended", "Extended", "Basic")
