import("libm3")
override("m3na","/home/thielema/programming/m3/pkg")
%override("m3na","../../..")
import("m3na")

% if you import 'blas' functions like 'e_wsfe' cannot be found
% if you then switch to 'gslcblas', compile, switch back to 'blas'
% then it can be compiled
%import_lib("blas","/usr/lib")

import_lib("g2c","/usr/lib")  % needed for blas and lapack, part of the f2c package, I guess
import_lib("blas","/usr/lib")
import_lib("lapack","/usr/lib")

implementation("TestWordEx")
implementation("TestBits")
implementation("TestInteger")
implementation("TestReal64")
implementation("TestComplex")
implementation("TestVector")
implementation("TestMatrix")
implementation("TestRoot")
implementation("TestInterpolation")
implementation("TestPolynomial")
implementation("TestSLE")
implementation("TestRandom")
implementation("TestFFT")
implementation("TestBigInteger")
implementation("TestGCD")
implementation("TestEigenSystem")
implementation("TestChebyshev")
implementation("TestUnit")
implementation("TestLapack")
module("Test")
program("Test")
