% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon May  2 16:16:30 PDT 1994 by kalsow
%      modified on Tue Feb 11 16:32:02 PST 1992 by muller
%

Module("Fingerprint")
Module("Poly")
module("PolyBasis")
