/* Test program for MScheme Level 1 Compiler */

if not SYSTEM_LIBS contains "MPZ"
  SYSTEM_LIBS{"MPZ"} = [ "-L/opt/homebrew/lib", "-lgmp" ]
  SYSTEM_LIBORDER += [ "MPZ" ]
end

import("libm3")
import("cit_util")
import("mscheme")
import("modula3scheme")
import("schemecompiler")

m3_optimize("T")

_scheme_compile("CompiledTest", "test-input.scm", HIDDEN)

implementation("Main")

program("comptest")
