import("libm3")

template("chebypolynomial")


generic_module("ChebyPolynomialFast")
ChebyPolynomialFast("Real",     "RealBasic")
ChebyPolynomialFast("LongReal", "LongRealBasic")
ChebyPolynomialFast("Extended", "ExtendedBasic")
