import("libm3")

template("chebypolynomial")


Generic_module("ChebyPolynomial")
Generic_module("ChebyPolynomialFast")
ChebyPolynomial("Real",     "Fast", "RealBasic")
ChebyPolynomial("LongReal", "Fast", "LongRealBasic")
ChebyPolynomial("Extended", "Fast", "ExtendedBasic")
