% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Fri Feb 18 14:14:46 PST 1994 by kalsow
%      modified on Tue Feb 11 15:18:47 PST 1992 by muller

c_source ("dtoa")
c_source ("getdtablesize")
c_source ("utimes")

