% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Aug 23 09:39:43 PDT 1994 by kalsow  

import ("libm3")

% implementation ("Test1")
implementation ("Test2")
% implementation ("Time1")
% implementation ("Time2")

program ("xxx")

