% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Oct 11 14:03:24 PDT 1995 by najork
%      modified on Wed Aug 17 15:08:24 PDT 1994 by kalsow
%      modified on Mon May 04 14:52:49 PDT 1992 by muller

if defined("configure_system_libs")
  configure_system_libs()
end

if not equal(TARGET, "MIPS64EL_OPENBSD")

if SYSTEM_LIBS contains "X11"
  import ("X11R4")
  implementation ("Main")
  Program ("tetris")
  ManPage ("tetris",6)
end

end
