.\" Copyright (C) 1992, Digital Equipment Corporation
.\" All rights reserved.
.\" See the file COPYRIGHT for a full description.
.\"
.\" Last modified on Tue Feb 11 20:20:51 PST 1992 by muller
.nh
.TH tetris 6
.SH Name
tetris \- simple game for X

.SH Syntax
.B tetris

.SH Description
You know what it is ...

.SH Acknowledgements

Translation to Modula-3: Copyright 1990, 1991 Digital Equipment Corporation 

Modifications for Xaw widget set, and other improvements, designated
XTETRIS versions 2.X: Copyright 1990, 1991 Daniel R. Greening

Modifications for X : Didier Tallot <tallot@bdblues.altair.fr>:
Copyright 1989 Didier Tallot

Copyright 1989 Phill Everson & Martyn Shortley


