% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Jun 12 13:51:07 PDT 1996 by najork
%      modified on Tue Mar 22 01:01:48 PST 1994 by luca
%      modified on Wed Dec 22 14:52:17 PST 1993 by kalsow

import("netobj")
import("synloc")

interface ("OpSys")
include_dir (OS_TYPE)

Module ("ObErr")
Module ("ObCommand")
Module ("ObLib")
Module ("ObTree")
Module ("ObScope")
Module ("ObCheck")
Module ("ObValue")
Module ("ObEval")
Module ("ObBuiltIn")
Module ("Obliq")

netobj("ObValue","RemVar")
netobj("ObValue","RemArray")
netobj("ObValue","RemObj")
netobj("ObValue","RemEngine")
netobj("ObValue","RemFileSystem")

Library("obliqrt")

/* ManPage(obliqrt,?) */


