% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Jun 12 13:51:07 PDT 1996 by najork
%      modified on Tue Mar 22 01:01:48 PST 1994 by luca
%      modified on Wed Dec 22 14:52:17 PST 1993 by kalsow

%%%%  if AT_SRC m3_option("-O") end   --- old m3build
%%%% remove_m3_option("-w1")		--- old m3build
%%%% m3_option("-w2")			--- old m3build

import("netobj")
import("sharedobj")
import("synloc")
import ("patternmatching")

interface ("OpSys")
Interface ("ObPathSep")
%if equal (OS_TYPE, "WIN32")
%  implementation ("ObPathSepWin32")
%else if equal (OS_TYPE, "POSIX")
%  implementation ("ObPathSepPosix")
%else
%  error ("obliqparse: unrecognized OS: " & OS_TYPE & CR)
%end end
include_dir (OS_TYPE)

Module ("ObErr")
Module ("ObCommand")
Module ("ObLib")
Module ("ObTree")
Module ("ObScope")
Module ("ObCheck")
interface ("ObValueRep")
Module ("ObValue")
Module ("ObEval")
Module ("ObBuiltIn")
Module ("Obliq")

Module ("ObValueField")
array_sort("ObField", "ObValueField")
Module ("ObValueNotify")

table ("ObLib", "Fingerprint", "WeakerRef")

netobjv2("ObValue","RemVar")
netobjv2("ObValue","RemArray")
netobjv2("ObValue","RemObj")
netobjv2("ObValue","RemEngine")
netobjv2("ObValue","RemFileSystem")
netobjv2("ObValue","RemIterator")
netobjv2("ObValue","RemProcessor")
netobjv2("ObValue","RemProcess")

netobjv2("ObValue","NonRemValHook")

sharedobj("ObValue", ["ReplObjStd", "ReplVarStd", "ReplArrayStd"], ["ObValueRep"])

%implementation("ObValueSO")
%Interface("ObValueProxy")
%Interface("ObValuePickle")
%Module("ObValueCB")


Library("obliqrt")

/* ManPage(obliqrt,?) */
