override ("binIO", PACKAGE_DIR & SL & ".." & SL & "..")

import ("binIO")

implementation ("Test")
program ("Test")

if defined("RUN")
  r = q_exec( "." & SL & "Test" )
  write( CR, "program returned ", r, CR )
end
