/* Makefile for tcp library (generic) */
/* Copyright 1993 Digital Equipment Corporation. */
/* Distributed only by permission. */
/* Last modified on Tue Jan 25 18:07:39 PST 1994 by wobber     */

Interface("IP")
Module   ("IPError")
Interface("StreamRd")
Module("StreamRdClass")
Interface("StreamWr")
Module("StreamWrClass")
Interface("TCP")
Interface("TCPExtras")
Interface("TCPPeer")
Interface("TCPSpecial")
Interface("TCPMisc")
Interface("ConnFD")
Module("ConnRW")
Module("ConnMsgRW")
c_source("IP_c")
h_source("IP_h")
implementation("IPCommon")
module("IPInternal")
