/* Copyright (C) 1996, Digital Equipment Corporation                         */
/* Digital Internal Use Only                                                 */
/* All rights reserved.                                                      */
/*                                                                           */
/* Last modified on Thu Oct 17 13:12:01 PDT 1996 by najork                   */
/*       Created on Tue Oct 15 13:38:07 PDT 1996 by najork                   */

import ("libm3")
import ("ui")
import ("formsvbt")

resource ("form.fv")
bundle ("MyBundle")

implementation ("Main")
Program ("PixmapComTest")
