---
name: Windows upgrade release
description: Upgrade a binary release on a Windows system.

runs:
  using: composite

  steps:
  - name: Build a few of the things
    # Can't run "do-cm3-all.py buildship" in CI environment because of
    # insufficient memory.
    run: |
      python2 upgrade.py
      python2 do-cm3-all.py realclean skipgcc
      python2 do-cm3-min.py buildship
    shell: cmd
    working-directory: scripts/python
