% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed Dec 14 14:42:15 PST 1994 by kalsow 
%      modified on Mon Sep 26 14:44:07 PDT 1994 by isard 

% m3_option ("-times")

import ("libm3")
import ("m3middle")
import ("m3objfile")

Module    ("M3x86")
interface ("M3x86Rep")
module    ("Wrx86")
module    ("Stackx86")
module    ("Codex86")

build_standalone ()
Library ("m3back")

