% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Oct 17 09:28:11 PDT 1994 by kalsow
%      modified on Fri Jun 18 13:18:18 PDT 1993 by harrison
%      modified on Thu Feb  4 15:58:38 PST 1993 by mjordan
%      modified on Mon Oct 12 13:51:24 PDT 1992 by muller

c_source ("dtoa")
