% Copyright (C) 1995, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue May 16 11:46:41 PDT 1995 by kalsow
%
% Contributed by Harry George (hgeorge@eskimo.com), 5/16/95

import ("motif")

module ("HelloGUI")
implementation ("Hello")
program ("Hello")
