/* Copyright (C) 2002 Hewlett-Packard Company                                */
/* Copyright (C) 2000, 2002 Compaq Computer Corporation                      */

list("PredSx", "PredSx")
mkdigraph("OrdNode", "PO", "OrdNode", "POEdgeType")
table("FPReal", "Fingerprint", "RealType")
table("FPRef", "Fingerprint", "Refany")
sequence("FP", "Fingerprint")
sequence("ContextUndoRec", "ContextUndoRec")
sequence("ClauseListUndoRec", "ClauseListUndoRec")
sequence("AFTabUndoRec", "AFTabUndoRec")
sequence("LNUndoRec", "LNUndoRec")
sequence("Time", "LongrealType")
sequence("IdSet", "IdSet")
sequence("ParentSet", "ParentSet")
table("IntPairRef", "IntPair", "Refany")
array_sort("IntPair", "IntPair")

% On systems that do not support shared libraries the following
% line (or, on some systems, the one after it) is necessary:
% option("standalone", "T")
% "build_standalone()
% Using cm3 on OS X, neither line is necessary.
