% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Jan 24 08:29:28 PST 1995 by kalsow
%      modified on Fri May  7 17:38:10 PDT 1993 by muller
%      modified on Wed May  5 11:53:58 PDT 1993 by mjordan

_FloatPieces = {
% Fill in TARGET or TARGET_ARCH or TARGET_OS specifics here if they exist,
% otherwise we fallback to defaults below.
  "LINUXLIBC6"    : [ "IEEE", "IEEE-le", "C99" ],
  "AMD64_LINUX"   : [ "IEEE", "IEEE-le", "C99" ],
  "AMD64_FREEBSD" : [ "IEEE", "IEEE-le", "C99" ],
  "I386_DARWIN"   : [ "IEEE", "IEEE-le", "C99" ],
  "FreeBSD4"      : [ "IEEE", "IEEE-le", "C99" ]
}

% copy from TARGET_OS or TARGET_ARCH or TARGET_ENDIAN to TARGET

if _FloatPieces contains TARGET
  % nothing
else if _FloatPieces contains TARGET_OS
  _FloatPieces{TARGET} = _FloatPieces{TARGET_OS}
else if _FloatPieces contains TARGET_ARCH
  _FloatPieces{TARGET} = _FloatPieces{TARGET_ARCH}
else
  % worst case fallback
  _FloatPieces{TARGET} =
    { "LITTLE"  : [ "IEEE", "IEEE-le", "IEEE-default" ],
      "BIG"     : [ "IEEE", "IEEE-be", "IEEE-default" ] }{TARGET_ENDIAN}
  _FloatPieces{"IEEE-default"} = 1 % indicator to m3-sys/m3tests
end end end

if not defined ("M3TESTS")
  include_dir ("Common")
  foreach f in _FloatPieces{TARGET}
    include_dir (f)
  end
end

ship_source ("m3makefile")
