/* Copyright (C) 1992, Digital Equipment Corporation                         */
/* All rights reserved.                                                      */
/* See the file COPYRIGHT for a full description.                            */
/*                                                                           */
/* Last modified on Wed Apr  9 12:55:13 PDT 1997 by heydon                   */
/*      modified on Thu Dec  8 15:45:23 PDT 1994 by gnelson                  */
/*      modified on Mon Oct 31 18:13:51 PST 1994 by isard                    */

/* m3makefile for /proj/m3/pkg/juno-machine/src */

/* imported packages */
import		("libm3")

/* public interfaces */
Interface	("InUseRec")
Interface	("JunoArgs")
Module		("JunoRTError")
Module		("JunoByteCode")
Module		("JunoDisassem")
Module		("JunoMarshal")
Module		("JunoRT")
Module		("JunoValue")
Module		("RTVal")

/* private interfaces */
sequence        ("InUseRec", "InUseRec")
table           ("QIdInt", "QId", "Integer")
/*
module		("RowOp")
interface	("CRowOp")
import_obj	("CRowOp.o")
*/
module		("Equiv")
module		("Egraph")

/* The redundant solver replaces the old solver:
module		("NonLinearSolve")
module		("LinearSolve")
*/
module		("RedundantSolve")
module		("RedundantLSolve")

interface	("NonLinearSolveRep")
module		("JunoSolve")
module		("QId")

/* compiler options */
m3_option	("-times")                      % report compilation times
m3_option	("-O")				% generate optimized code
% m3_option	("-X0@-copying_struct_assign@") % disable Veach optimizations
% m3_option	("-keep")                       % keep intermediate files
% m3_option	("-commands")                   % see which tools are invoked
% m3_option	("-v")                          % verbose compiler switch
% m3_option	("-X2%-p%")                     % enable profiling
% m3_option	("-X0@-NoChecks@")              % disable array-bounds checking

/* build the "libjuno-machine.a" library */
library		("juno-machine")
