% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Sat Sep  2 22:43:44 PDT 1995 by najork    
%      modified on Wed Mar 23 14:10:13 1994 by luca      
%      modified on Wed Dec 22 15:33:15 PST 1993 by kalsow

import("obliq")
import("obliqlibm3")

> "compiletime.txt" in
	if equal(TARGET, "NT386")
		%%% a unix-like date command from a free set of unix
		%%% utilities
		exec("@unixdate")
	else
		exec("@date")
	end
end
derived_resource("compiletime.txt")

bundle("CompileTime")

implementation("Main")

%build_standalone()
Program("repo-std")
ManPage("repo-std","1")
