% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Sat Sep  2 22:43:44 PDT 1995 by najork    
%      modified on Wed Mar 23 14:10:13 1994 by luca      
%      modified on Wed Dec 22 15:33:15 PST 1993 by kalsow

if HasTrestle()

import("obliq")
import("obliqlibm3")
implementation("Main")

build_standalone()
Program("obliq-std")
ManPage("obliq-std","1")

end
