if equal (OS_TYPE, "WIN32")
  override("obliq", "\\\\stieglitz\\graphics\\arm3\\bm-work\\cm3\\m3-obliq")
  override("obliqlibm3", "\\\\stieglitz\\graphics\\arm3\\bm-work\\cm3\\m3-obliq")
else
  override("obliq", "/proj/graphics/arm3/bm-work/cm3/m3-obliq")
  override("obliqlibm3", "/proj/graphics/arm3/bm-work/cm3/m3-obliq")
end
