/* $Id$ */

if not equal (OS_TYPE, "WIN32")

import("libm3")
import("cit_util")
import("mscheme")
import("schemesig")
import("m3readline")
import("modula3scheme")

Module("SchemeReadLine")
Module("SchemeInteraction")

library("schemereadline")

end
