
m3_optimize("T")   % turns on optimizer

import ("libm3")

include_dir("libglob")

if not defined("PM3")
  % in PM3, RegEx is included in libm3
  Module ("RegEx")
end
interface("Uglob")
Module("Glob")
Module("GlobTree")

Library ("patternmatching")

