% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Aug 26 12:53:58 PDT 1993 by kalsow  
%      modified on Sun Jun 20 21:01:12 PDT 1993 by harrison
%      modified on Mon Apr 26 13:38:54 PDT 1993 by mcjones


Generic_module ("ArraySort")

template ("arraysort")

Array_sort ("Int",  "Integer")
Array_sort ("Text", "Text")

