import ("libm3")
import ("parseparams")

implementation ("Main")

if defined("CM3_VERSION")
	build_standalone()                 /* Critical Mass Modula-3 */
else
	if defined("pm3_version")
       		option("shared_lib","")    /* Polytech. de Montreal Modula-3 */
	else
		m3_option ("-X2@-static@") /* SRC Modula-3 */
	end
end

program ("threadtest")
