% Copyright (C) 1996, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
% Last modified on Thu Sep  5 16:34:03 PDT 1996 by detlefs

import("libm3")
%import(libm3-esc)

Generic_module("DiGraph")
template("digraph")
Module("NullEdgeType")
Module("POEdgeType")

Library("DiGraph")

/*
module(IntIntDiGraph)
module(IntNullDiGraph)
implementation(DiGraphTest)
program(DiGraphTest)
*/
/*
module(IntIntDiGraph)
implementation(TopSortTest)
program(TopSortTest)
*/
