
dirs = [ 
  % ".." & SL & "sqrt", 
  % disabled recently by Jay Krell as Sqrt is not implemented in CM3
  ".." & SL & "os",
  ".." & SL & "pqueue" & SL & "fromtty",
  ".." & SL & "pqueue" & SL & "heapsort1",
  ".." & SL & "pqueue" & SL & "heapsort2",
  ".." & SL & "rw" & SL & "autotest",
  ".." & SL & "rw" & SL & "copy",
  ".." & SL & "sequence",
  ".." & SL & "sortedtable",
  ".." & SL & "random"
]

foreach d in dirs
  dotests = "cm3 -build -override -DROOT=" & ROOT & " -DRUN -DTEST"
  pushd( d )
  write( CR, "=== performing tests in ", getwd(), " ===", CR )
  write( dotests, CR )
  r = q_exec( dotests )
  write( CR, "cm3 returned ", r, CR, CR )
  popd()
end
