% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Feb  7 11:21:05 PST 1995 by kalsow

implementation ("JVBuffer")
implementation ("JvsBuffer")
implementation ("JVSink")

