---
name: AMD64_LINUX

on:
  workflow_call:
    inputs:
      os:
        default: ubuntu-latest
        required: false
        type: string
      release:
        default: https://github.com/VictorMiasnikov/cm3/releases/download/d5.11.9-ZZYYXX-20241118_21-50
        required: false
        type: string
      bootstrap:
        default: cm3-boot-AMD64_LINUX-None.tar.xz
        required: false
        type: string

jobs:
  build-and-test:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 45

    strategy:
      fail-fast: false
      matrix:
        backend: [c, gcc]

    env:
      CM3_TARGET: AMD64_LINUX

    steps:
    - name: Install prerequisites
      run: |
        sudo apt-get update --quiet
        sudo apt-get install --quiet --assume-yes libglu1-mesa-dev ninja-build xorg-dev

    - name: Define install location
      run: |
        echo CM3_INSTALL="$(pwd)/../install" >> $GITHUB_ENV

    - name: Install bootstrap release
      run: |
        mkdir ../bootstrap ../build
        curl --location --silent "${{ inputs.release }}/${{ inputs.bootstrap }}" | tar Jxf - --directory=../bootstrap --strip-components=1
        cmake -S ../bootstrap -B ../build -G Ninja -DCMAKE_INSTALL_PREFIX="${CM3_INSTALL}"
        cmake --build ../build
        cmake --install ../build
        echo "${CM3_INSTALL}/bin" >> $GITHUB_PATH

    - name: Fetch sources
      uses: actions/checkout@v2

    - name: Build all the things
      run: |
        scripts/concierge.py full-upgrade --backend "${{ matrix.backend }}" all

    - name: Run compiler validation suite
      continue-on-error: true
      run: |
        cm3 -DHTML
      working-directory: m3-sys/m3tests

    - name: Generate test report
      uses: dorny/test-reporter@v1
      with:
        name: ${{ format('m3tests ({0}, {1})', env.CM3_TARGET, matrix.backend) }}
        fail-on-error: false
        max-annotations: 49
        path: m3-sys/m3tests/m3tests-results.xml
        reporter: java-junit
