---
name: AMD64_MINGW

on:
  workflow_call:
    inputs:
      os:
        default: windows-latest
        required: false
        type: string
      release:
        default: https://github.com/VictorMiasnikov/cm3/releases/download/d5.11.9-ZZYYXX-20241118_21-50
        required: false
        type: string
      bootstrap:
        default: cm3-boot-AMD64_NT-None.7z
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 35

    defaults:
      run:
        shell: msys2 {0}

    env:
      CM3_TARGET: AMD64_MINGW

    steps:
    - name: Install command-line tools
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: >-
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-toolchain
          p7zip
          wget

    - name: Define install location
      run: |
        echo CM3_INSTALL="$(pwd)/../install/cm3" >> $GITHUB_ENV

    - name: Install bootstrap release
      env:
        CMAKE_LIBRARY_PATH: /mingw64/x86_64-w64-mingw32/lib
      run: |
        mkdir ../build ../install
        cd ../install
        wget --quiet "${{ inputs.release }}/${{ inputs.bootstrap }}"
        7z x -o.. "${{ inputs.bootstrap }}"
        cmake -S ../bootstrap -B ../build -G Ninja -DCMAKE_INSTALL_PREFIX="${CM3_INSTALL}" -DCMAKE_LIBRARY_PATH="${CMAKE_LIBRARY_PATH}"
        cmake --build ../build
        cmake --install ../build

    - name: Fetch sources
      uses: actions/checkout@v2

    - name: Build all the things
      run: |
        python3 scripts/concierge.py full-upgrade all -caltech-other -caltech-parser -m3-scheme
