---
name: make release

on:
  push:
    tags: ["d*.*.*"]


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      BOOTSTRAP: https://github.com/VictorMiasnikov/cm3/releases/download/d5.11.9-ZZYYXX-20241118_21-50/cm3-boot-AMD64_LINUX-None.tar.xz

    steps:
    - name: Install prerequisites
      run: |
        sudo apt-get update --quiet
        sudo apt-get install --quiet --assume-yes ninja-build

    - name: Define install location
      run: |
        echo CM3_INSTALL="$(pwd)/../install" >> $GITHUB_ENV

    - name: Install bootstrap
      run: |
        mkdir ../bootstrap ../build
        curl --location --silent "${BOOTSTRAP}" | tar Jxf - --directory=../bootstrap --strip-components=1
        cmake -S ../bootstrap -B ../build -G Ninja -DCMAKE_INSTALL_PREFIX="${CM3_INSTALL}"
        cmake --build ../build
        cmake --install ../build
        echo "${CM3_INSTALL}/bin" >> $GITHUB_PATH

    - name: Fetch sources
      uses: actions/checkout@v2

    - name: Fetch tag
      run: git fetch --force origin ${{ github.ref }}:${{ github.ref }}

    - name: Upgrade compiler
      run: |
        scripts/concierge.py upgrade

    - name: Build distributions
      run: |
        scripts/concierge.py make-dist --target AMD64_LINUX
        scripts/concierge.py make-dist --target AMD64_NT
        scripts/concierge.py make-dist --target I386_LINUX
        scripts/concierge.py make-dist --target I386_NT

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          *.7z
          *.tar.xz
