% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Mar 21 23:09:47 PST 1994 by luca  
%      modified on Wed Dec 22 14:39:38 PST 1993 by kalsow

%%%%  if AT_SRC m3_option("-O") end   --- old m3build
%%%% remove_m3_option("-w1")		--- old m3build
%%%% m3_option("-w2")			--- old m3build

import("libm3")
import("synloc")

Module("SynScan")
Module("SynParse")

Library("synex")

