% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Mar 21 23:09:47 PST 1994 by luca  
%      modified on Wed Dec 22 14:39:38 PST 1993 by kalsow

import("libm3")
import("synloc")

Module("SynScan")
Module("SynParse")

Library("synex")

