% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Fri Jan 14 10:24:47 PST 1994 by kalsow
%      modified on Mon Apr 06 14:45:41 PDT 1992 by muller


override (tcl, "../../..")

import (libm3)
import (tcl)
implementation (TclCTest)
% implementation (TclTest)
program (test)
