% m3-sys/llvm/src/m3makefile
% This is the Modula-3 binding to the C binding to the llvm infrastructure. 

import ("libm3")
Interface ("LLVM") 

include_dir("llvmlibs")

build_standalone ()
Library ("M3LLVMCore")
