import("prover")

implementation("FPTest")

% On systems that do not support shared libraries the following
% line (or, on some systems, the one after it) is necessary:
% option("standalone", "T")
% "build_standalone()
% Using cm3 on OS X, neither line is necessary.

Program("FPTest")
